/** Categories, skills, interests, materials and badges. */

export const categories = [
  {
    slug: 'nature',
    nameEn: 'Nature',
    nameNl: 'Natuur',
    descriptionEn: 'Look closely at the living world, from a city park to a forest floor.',
    descriptionNl: 'Kijk goed naar de levende wereld, van een stadspark tot de bosbodem.',
    icon: 'leaf',
    colorToken: 'moss',
    sortOrder: 1,
  },
  {
    slug: 'science',
    nameEn: 'Science',
    nameNl: 'Wetenschap',
    descriptionEn: 'Ask a question, build a test, find out what really happens.',
    descriptionNl: 'Stel een vraag, bedenk een proef en ontdek wat er echt gebeurt.',
    icon: 'flask',
    colorToken: 'dusk',
    sortOrder: 2,
  },
  {
    slug: 'movement',
    nameEn: 'Movement',
    nameNl: 'Beweging',
    descriptionEn: 'Get the body going, indoors or out, alone or together.',
    descriptionNl: 'Kom in beweging, binnen of buiten, alleen of samen.',
    icon: 'run',
    colorToken: 'ember',
    sortOrder: 3,
  },
  {
    slug: 'creativity',
    nameEn: 'Creativity',
    nameNl: 'Creativiteit',
    descriptionEn: 'Make something that did not exist this morning.',
    descriptionNl: 'Maak iets dat er vanochtend nog niet was.',
    icon: 'brush',
    colorToken: 'berry',
    sortOrder: 4,
  },
  {
    slug: 'cooking',
    nameEn: 'Cooking',
    nameNl: 'Koken',
    descriptionEn: 'Plan, cook and share real food with the people you live with.',
    descriptionNl: 'Plan, kook en deel echt eten met de mensen om je heen.',
    icon: 'pot',
    colorToken: 'ember',
    sortOrder: 5,
  },
  {
    slug: 'practical-skills',
    nameEn: 'Practical skills',
    nameNl: 'Praktische vaardigheden',
    descriptionEn: 'Fix, fold, tie and mend the things a household runs on.',
    descriptionNl: 'Repareer, vouw, knoop en herstel waar een huishouden op draait.',
    icon: 'tool',
    colorToken: 'dusk',
    sortOrder: 6,
  },
  {
    slug: 'technology',
    nameEn: 'Technology',
    nameNl: 'Techniek',
    descriptionEn: 'Understand how machines think - mostly without a screen.',
    descriptionNl: 'Begrijp hoe machines denken — meestal zonder scherm.',
    icon: 'chip',
    colorToken: 'dusk',
    sortOrder: 7,
  },
  {
    slug: 'entrepreneurship',
    nameEn: 'Entrepreneurship',
    nameNl: 'Ondernemen',
    descriptionEn: 'Spot a need, make something, work out what it is worth.',
    descriptionNl: 'Zie een behoefte, maak iets en ontdek wat het waard is.',
    icon: 'coins',
    colorToken: 'sun',
    sortOrder: 8,
  },
  {
    slug: 'family-connection',
    nameEn: 'Family connection',
    nameNl: 'Gezinsband',
    descriptionEn: 'Adventures whose whole point is the people you do them with.',
    descriptionNl: 'Avonturen die juist draaien om de mensen met wie je ze doet.',
    icon: 'heart',
    colorToken: 'berry',
    sortOrder: 9,
  },
  {
    slug: 'social-contribution',
    nameEn: 'Social contribution',
    nameNl: 'Iets voor een ander',
    descriptionEn: 'Small, concrete good turns for the street you live in.',
    descriptionNl: 'Kleine, concrete goede daden voor de straat waarin je woont.',
    icon: 'hands',
    colorToken: 'moss',
    sortOrder: 10,
  },
  {
    slug: 'history-culture',
    nameEn: 'History and culture',
    nameNl: 'Geschiedenis en cultuur',
    descriptionEn: 'Find the past hiding in your own street, house and family.',
    descriptionNl: 'Vind het verleden dat verstopt zit in je eigen straat, huis en familie.',
    icon: 'scroll',
    colorToken: 'sun',
    sortOrder: 11,
  },
] as const

export const skills = [
  {
    slug: 'creativity',
    nameEn: 'Creativity',
    nameNl: 'Creativiteit',
    descriptionEn: 'Coming up with ideas and giving them a form.',
    descriptionNl: 'Ideeën bedenken en er vorm aan geven.',
  },
  {
    slug: 'problem-solving',
    nameEn: 'Problem solving',
    nameNl: 'Probleemoplossen',
    descriptionEn: 'Breaking a puzzle into pieces you can actually tackle.',
    descriptionNl: 'Een probleem opdelen in stukken die je echt aankunt.',
  },
  {
    slug: 'communication',
    nameEn: 'Communication',
    nameNl: 'Communicatie',
    descriptionEn: 'Listening well and making yourself understood.',
    descriptionNl: 'Goed luisteren en jezelf duidelijk maken.',
  },
  {
    slug: 'nature-awareness',
    nameEn: 'Nature awareness',
    nameNl: 'Natuurbesef',
    descriptionEn: 'Noticing what lives around you and how it fits together.',
    descriptionNl: 'Merken wat er om je heen leeft en hoe het samenhangt.',
  },
  {
    slug: 'movement',
    nameEn: 'Movement',
    nameNl: 'Beweging',
    descriptionEn: 'Coordination, stamina and confidence in your own body.',
    descriptionNl: 'Coördinatie, uithoudingsvermogen en vertrouwen in je lijf.',
  },
  {
    slug: 'practical-independence',
    nameEn: 'Practical independence',
    nameNl: 'Praktische zelfstandigheid',
    descriptionEn: 'Doing the everyday things yourself, safely.',
    descriptionNl: 'Dagelijkse dingen zelf doen, en veilig.',
  },
  {
    slug: 'financial-literacy',
    nameEn: 'Financial literacy',
    nameNl: 'Omgaan met geld',
    descriptionEn: 'Understanding cost, value, saving and trade.',
    descriptionNl: 'Snappen wat iets kost, waard is, en hoe sparen en ruilen werkt.',
  },
  {
    slug: 'teamwork',
    nameEn: 'Teamwork',
    nameNl: 'Samenwerken',
    descriptionEn: 'Dividing work, keeping promises, finishing together.',
    descriptionNl: 'Werk verdelen, afspraken nakomen en samen afmaken.',
  },
  {
    slug: 'citizenship',
    nameEn: 'Citizenship',
    nameNl: 'Burgerschap',
    descriptionEn: 'Taking care of the shared space and the people in it.',
    descriptionNl: 'Zorgen voor de gedeelde ruimte en de mensen daarin.',
  },
  {
    slug: 'curiosity',
    nameEn: 'Curiosity',
    nameNl: 'Nieuwsgierigheid',
    descriptionEn: 'Asking one more question than you were going to.',
    descriptionNl: 'Nog één vraag stellen meer dan je van plan was.',
  },
] as const

export const interests = [
  { slug: 'animals', nameEn: 'Animals', nameNl: 'Dieren', category: 'nature' },
  { slug: 'plants', nameEn: 'Plants and trees', nameNl: 'Planten en bomen', category: 'nature' },
  { slug: 'water', nameEn: 'Water and weather', nameNl: 'Water en weer', category: 'nature' },
  { slug: 'experiments', nameEn: 'Experiments', nameNl: 'Proefjes', category: 'science' },
  { slug: 'space', nameEn: 'Space', nameNl: 'Ruimte', category: 'science' },
  { slug: 'building', nameEn: 'Building things', nameNl: 'Dingen bouwen', category: 'science' },
  { slug: 'sports', nameEn: 'Sport and games', nameNl: 'Sport en spel', category: 'movement' },
  { slug: 'dance', nameEn: 'Dance', nameNl: 'Dansen', category: 'movement' },
  { slug: 'drawing', nameEn: 'Drawing and painting', nameNl: 'Tekenen en schilderen', category: 'creativity' },
  { slug: 'music', nameEn: 'Music', nameNl: 'Muziek', category: 'creativity' },
  { slug: 'stories', nameEn: 'Stories', nameNl: 'Verhalen', category: 'creativity' },
  { slug: 'baking', nameEn: 'Baking and cooking', nameNl: 'Bakken en koken', category: 'cooking' },
  { slug: 'repairing', nameEn: 'Repairing things', nameNl: 'Dingen repareren', category: 'practical-skills' },
  { slug: 'computers', nameEn: 'Computers and robots', nameNl: 'Computers en robots', category: 'technology' },
  { slug: 'money', nameEn: 'Money and trading', nameNl: 'Geld en handel', category: 'entrepreneurship' },
  { slug: 'helping', nameEn: 'Helping others', nameNl: 'Anderen helpen', category: 'social-contribution' },
  { slug: 'family', nameEn: 'Family and traditions', nameNl: 'Familie en tradities', category: 'family-connection' },
  { slug: 'history', nameEn: 'History', nameNl: 'Geschiedenis', category: 'history-culture' },
] as const

/** `isCommon: false` marks something a household may have to buy or borrow. */
export const materials = [
  { slug: 'paper', nameEn: 'Paper', nameNl: 'Papier' },
  { slug: 'pencil', nameEn: 'Pencil or pen', nameNl: 'Potlood of pen' },
  { slug: 'scissors', nameEn: 'Scissors', nameNl: 'Schaar' },
  { slug: 'tape', nameEn: 'Sticky tape', nameNl: 'Plakband' },
  { slug: 'string', nameEn: 'String', nameNl: 'Touw' },
  { slug: 'newspaper', nameEn: 'Old newspaper', nameNl: 'Oude krant' },
  { slug: 'cardboard', nameEn: 'Cardboard box', nameNl: 'Kartonnen doos' },
  { slug: 'glue', nameEn: 'Glue', nameNl: 'Lijm' },
  { slug: 'ruler', nameEn: 'Ruler or tape measure', nameNl: 'Liniaal of meetlint' },
  { slug: 'bag', nameEn: 'Bag or basket', nameNl: 'Tas of mandje' },
  { slug: 'jar', nameEn: 'Glass jar', nameNl: 'Glazen pot' },
  { slug: 'water', nameEn: 'Water', nameNl: 'Water' },
  { slug: 'kitchen-scale', nameEn: 'Kitchen scale', nameNl: 'Keukenweegschaal' },
  { slug: 'timer', nameEn: 'Timer or clock', nameNl: 'Timer of klok' },
  { slug: 'torch', nameEn: 'Torch', nameNl: 'Zaklamp' },
  { slug: 'chalk', nameEn: 'Chalk', nameNl: 'Stoepkrijt' },
  { slug: 'ball', nameEn: 'Ball', nameNl: 'Bal' },
  { slug: 'blanket', nameEn: 'Blanket', nameNl: 'Deken' },
  { slug: 'pan', nameEn: 'Pan', nameNl: 'Pan' },
  { slug: 'knife', nameEn: 'Kitchen knife', nameNl: 'Keukenmes' },
  { slug: 'cutting-board', nameEn: 'Cutting board', nameNl: 'Snijplank' },
  { slug: 'vegetables', nameEn: 'Vegetables', nameNl: 'Groenten' },
  { slug: 'baking-supplies', nameEn: 'Flour, oil and salt', nameNl: 'Bloem, olie en zout' },
  { slug: 'needle-thread', nameEn: 'Needle and thread', nameNl: 'Naald en draad' },
  { slug: 'screwdriver', nameEn: 'Screwdriver', nameNl: 'Schroevendraaier' },
  { slug: 'sticks', nameEn: 'Twigs and sticks', nameNl: 'Takjes en stokken' },
  { slug: 'stones', nameEn: 'Stones', nameNl: 'Stenen' },
  { slug: 'coins', nameEn: 'A few coins', nameNl: 'Wat munten' },
  { slug: 'phone-camera', nameEn: 'A camera or phone', nameNl: 'Een camera of telefoon' },
  { slug: 'envelope', nameEn: 'Envelope', nameNl: 'Envelop' },
  { slug: 'box-with-lid', nameEn: 'Box with a lid', nameNl: 'Doos met deksel' },
  { slug: 'magnifier', nameEn: 'Magnifying glass', nameNl: 'Vergrootglas', isCommon: false },
  { slug: 'bamboo-canes', nameEn: 'Bamboo canes', nameNl: 'Bamboestokken', isCommon: false },
  { slug: 'drill', nameEn: 'Drill', nameNl: 'Boormachine', isCommon: false },
  { slug: 'compass-tool', nameEn: 'Compass', nameNl: 'Kompas', isCommon: false },
  { slug: 'seeds', nameEn: 'Seeds', nameNl: 'Zaadjes', isCommon: false },
] as const

export const badges = [
  {
    slug: 'first-adventure',
    nameEn: 'First adventure',
    nameNl: 'Eerste avontuur',
    descriptionEn: 'You finished your very first Questly adventure together.',
    descriptionNl: 'Jullie rondden het allereerste Questly-avontuur samen af.',
    icon: 'star',
    criteria: 'COMPLETIONS_TOTAL',
    threshold: 1,
  },
  {
    slug: 'five-adventures',
    nameEn: 'Five adventures',
    nameNl: 'Vijf avonturen',
    descriptionEn: 'Five real-world adventures behind you.',
    descriptionNl: 'Vijf echte avonturen achter de rug.',
    icon: 'star',
    criteria: 'COMPLETIONS_TOTAL',
    threshold: 5,
  },
  {
    slug: 'ten-adventures',
    nameEn: 'Ten adventures',
    nameNl: 'Tien avonturen',
    descriptionEn: 'Ten adventures. That is a habit, not a coincidence.',
    descriptionNl: 'Tien avonturen. Dat is een gewoonte, geen toeval.',
    icon: 'star',
    criteria: 'FAMILY_MILESTONE',
    threshold: 10,
  },
  {
    slug: 'explorer',
    nameEn: 'Explorer',
    nameNl: 'Ontdekker',
    descriptionEn: 'You have tried adventures in four different categories.',
    descriptionNl: 'Jullie probeerden avonturen in vier verschillende categorieën.',
    icon: 'compass',
    criteria: 'DISTINCT_CATEGORIES',
    threshold: 4,
  },
  {
    slug: 'all-rounder',
    nameEn: 'All-rounder',
    nameNl: 'Allrounder',
    descriptionEn: 'Adventures in eight different categories.',
    descriptionNl: 'Avonturen in acht verschillende categorieën.',
    icon: 'compass',
    criteria: 'DISTINCT_CATEGORIES',
    threshold: 8,
  },
  {
    slug: 'nature-friend',
    nameEn: 'Friend of nature',
    nameNl: 'Natuurvriend',
    descriptionEn: 'Three nature adventures completed.',
    descriptionNl: 'Drie natuuravonturen afgerond.',
    icon: 'leaf',
    criteria: 'COMPLETIONS_IN_CATEGORY',
    threshold: 3,
    category: 'nature',
  },
  {
    slug: 'young-scientist',
    nameEn: 'Young scientist',
    nameNl: 'Jonge wetenschapper',
    descriptionEn: 'Three science adventures completed.',
    descriptionNl: 'Drie wetenschapsavonturen afgerond.',
    icon: 'flask',
    criteria: 'COMPLETIONS_IN_CATEGORY',
    threshold: 3,
    category: 'science',
  },
  {
    slug: 'home-cook',
    nameEn: 'Home cook',
    nameNl: 'Thuiskok',
    descriptionEn: 'Three cooking adventures completed.',
    descriptionNl: 'Drie kookavonturen afgerond.',
    icon: 'pot',
    criteria: 'COMPLETIONS_IN_CATEGORY',
    threshold: 3,
    category: 'cooking',
  },
  {
    slug: 'good-neighbour',
    nameEn: 'Good neighbour',
    nameNl: 'Goede buur',
    descriptionEn: 'Two adventures that made your street a little better.',
    descriptionNl: 'Twee avonturen die de straat een beetje beter maakten.',
    icon: 'hands',
    criteria: 'COMPLETIONS_IN_CATEGORY',
    threshold: 2,
    category: 'social-contribution',
  },
  {
    slug: 'problem-solver',
    nameEn: 'Problem solver',
    nameNl: 'Probleemoplosser',
    descriptionEn: 'You have practised problem solving again and again.',
    descriptionNl: 'Jullie oefenden keer op keer met probleemoplossen.',
    icon: 'tool',
    criteria: 'SKILL_POINTS',
    threshold: 5,
    skill: 'problem-solving',
  },
  {
    slug: 'storyteller',
    nameEn: 'Storyteller',
    nameNl: 'Verhalenverteller',
    descriptionEn: 'You have practised communication over many adventures.',
    descriptionNl: 'Jullie oefenden communicatie tijdens veel avonturen.',
    icon: 'scroll',
    criteria: 'SKILL_POINTS',
    threshold: 5,
    skill: 'communication',
  },
] as const
