import type { Topic, Word } from './types'

/**
 * The lexicon. One entry per thing the app can teach, ask about, or look up.
 *
 * Spelling follows how Moroccans write Darija to each other: Arabic script as
 * it is typed in messages, and a Latin transliteration with the numbers that
 * stand for sounds Latin letters do not have (3 = ع, 7 = ح, 9 = ق).
 */
const w = (
  id: string, ar: string, tr: string, nl: string, en: string,
  topic: Topic, emoji?: string, note?: string, phrase = false,
): Word => ({ id, ar, tr, nl, en, topic, emoji, note, phrase })

export const WORDS: Word[] = [
  // ---------------------------------------------------------------- groeten
  w('salam', 'السلام', 'salam', 'hallo', 'hello', 'groeten', '👋', 'Het gewone hallo, tegen iedereen.'),
  w('salam-alaykum', 'السلام عليكم', 'ssalamu 3alaykum', 'vrede zij met jou (hallo)', 'peace be upon you', 'groeten', '🤲', 'De beleefde begroeting. Je hoort hem overal.', true),
  w('wa-alaykum', 'وعليكم السلام', 'wa 3alaykum ssalam', 'en met jou ook (antwoord)', 'and upon you peace', 'groeten', '🤲', 'Zo antwoord je op “ssalamu 3alaykum”.', true),
  w('sbah-lkhir', 'صباح الخير', 'sbah lkhir', 'goedemorgen', 'good morning', 'groeten', '🌅', '', true),
  w('msa-lkhir', 'مسا الخير', 'msa lkhir', 'goedemiddag / goedenavond', 'good evening', 'groeten', '🌇', '', true),
  w('labas', 'لاباس؟', 'labas?', 'gaat het goed?', 'are you okay?', 'groeten', '🙂', 'Letterlijk: “geen kwaad?”', true),
  w('labas-hamdullah', 'لاباس الحمد لله', 'labas, lhamdullah', 'het gaat goed, godzijdank', 'I am fine, thank God', 'groeten', '😊', 'Het standaardantwoord op labas?', true),
  w('kif-dayr', 'كيف داير؟', 'kif dayr?', 'hoe gaat het? (tegen een jongen)', 'how are you? (to a boy)', 'groeten', '💬', 'Tegen een meisje zeg je kif dayra?', true),
  w('kif-dayra', 'كيف دايرة؟', 'kif dayra?', 'hoe gaat het? (tegen een meisje)', 'how are you? (to a girl)', 'groeten', '💬', '', true),
  w('bikhir', 'بخير', 'bikhir', 'prima, goed', 'well, fine', 'groeten', '👍'),
  w('shukran', 'شكرا', 'shukran', 'dankjewel', 'thank you', 'groeten', '🙏'),
  w('barakallah', 'بارك الله فيك', 'barakallahu fik', 'dank je wel (warm)', 'bless you / thanks', 'groeten', '💛', 'Warmer dan shukran. Letterlijk: God zegene je.', true),
  w('la-shukran-wajib', 'لا شكرا على واجب', 'la shukran 3la wajib', 'graag gedaan', 'you are welcome', 'groeten', '🤗', '', true),
  w('afak', 'عافاك', '3afak', 'alsjeblieft (als je iets vraagt)', 'please', 'groeten', '🙏'),
  w('smeh-liya', 'سمح ليا', 'smeh liya', 'sorry / neem me niet kwalijk', 'excuse me / sorry', 'groeten', '😅', '', true),
  w('maalish', 'معليش', 'ma3lish', 'geeft niet', 'never mind', 'groeten', '😌'),
  w('bslama', 'بسلامة', 'bslama', 'doei, tot ziens', 'goodbye', 'groeten', '👋'),
  w('thalla', 'تهلا', 'thalla', 'zorg goed voor jezelf (doei)', 'take care', 'groeten', '💫', 'Lief afscheid. Tegen meerdere mensen: thallaw.'),
  w('lila-saida', 'ليلة سعيدة', 'lila sa3ida', 'welterusten', 'good night', 'groeten', '🌙', '', true),
  w('merhba', 'مرحبا', 'merhba', 'welkom', 'welcome', 'groeten', '🚪'),
  w('iyeh', 'ايه', 'iyeh', 'ja', 'yes', 'groeten', '✅', 'Ook: “ah”. Formeel: na3am.'),
  w('la', 'لا', 'la', 'nee', 'no', 'groeten', '❌'),
  w('wakha', 'واخا', 'wakha', 'oké, goed', 'okay', 'groeten', '👌', 'Het meest gebruikte woord van Marokko.'),
  w('yallah', 'يالله', 'yallah', 'kom op, laten we gaan', "let's go", 'groeten', '🏃', ''),
  w('mzyan', 'مزيان', 'mzyan', 'goed, mooi', 'good, nice', 'groeten', '🌟', 'Vrouwelijk: mzyana.'),
  w('bezzaf', 'بزاف', 'bezzaf', 'heel veel', 'a lot', 'groeten', '💯'),
  w('inshallah', 'إن شاء الله', 'inshallah', 'als God het wil (hopelijk)', 'God willing', 'groeten', '🌤️', 'Gebruikt voor alles wat nog moet gebeuren.'),
  w('lhamdullah', 'الحمد لله', 'lhamdullah', 'godzijdank', 'thank God', 'groeten', '🤲'),

  // ------------------------------------------------------------- ik en jij
  w('ana', 'انا', 'ana', 'ik', 'I', 'ik-en-jij', '🙋'),
  w('nta', 'نتا', 'nta', 'jij (jongen)', 'you (m)', 'ik-en-jij', '👦'),
  w('nti', 'نتي', 'nti', 'jij (meisje)', 'you (f)', 'ik-en-jij', '👧'),
  w('huwa', 'هو', 'huwa', 'hij', 'he', 'ik-en-jij', '👨'),
  w('hiya', 'هي', 'hiya', 'zij', 'she', 'ik-en-jij', '👩'),
  w('hna', 'حنا', 'hna', 'wij', 'we', 'ik-en-jij', '👨‍👩‍👧'),
  w('ntuma', 'نتوما', 'ntuma', 'jullie', 'you (plural)', 'ik-en-jij', '👥'),
  w('huma', 'هوما', 'huma', 'zij (meervoud)', 'they', 'ik-en-jij', '👥'),
  w('smiti', 'سميتي', 'smiti...', 'ik heet...', 'my name is...', 'ik-en-jij', '📛', '', true),
  w('shnu-smitek', 'شنو سميتك؟', 'shnu smitek?', 'hoe heet je?', 'what is your name?', 'ik-en-jij', '❓', '', true),
  w('mtsherfin', 'متشرفين', 'mtsherfin', 'aangenaam kennis te maken', 'nice to meet you', 'ik-en-jij', '🤝', '', true),
  w('ana-men-hulanda', 'انا من هولندا', 'ana men Hulanda', 'ik kom uit Nederland', 'I am from the Netherlands', 'ik-en-jij', '🇳🇱', '', true),
  w('ana-men-lmghrib', 'انا من المغرب', 'ana men lMghrib', 'ik kom uit Marokko', 'I am from Morocco', 'ik-en-jij', '🇲🇦', '', true),
  w('fin-sakn', 'فين ساكن؟', 'fin sakn?', 'waar woon je? (tegen een jongen)', 'where do you live?', 'ik-en-jij', '🏠', 'Tegen een meisje: fin sakna?', true),
  w('shhal-f-3merek', 'شحال ف عمرك؟', 'shhal f 3merek?', 'hoe oud ben je?', 'how old are you?', 'ik-en-jij', '🎂', '', true),
  w('3endi-3achr-snin', 'عندي عشر سنين', '3endi 3achr snin', 'ik ben tien jaar', 'I am ten years old', 'ik-en-jij', '🎈', 'Letterlijk: ik heb tien jaren.', true),
  w('kanhder-shwiya', 'كنهضر شوية دارجة', 'kanhder shwiya darija', 'ik spreek een beetje Darija', 'I speak a little Darija', 'ik-en-jij', '🗣️', '', true),

  // --------------------------------------------------------------- familie
  w('aila', 'العائلة', 'l3a\'ila', 'de familie', 'the family', 'familie', '👨‍👩‍👧‍👦'),
  w('baba', 'بابا', 'baba', 'papa', 'dad', 'familie', '👨'),
  w('mama', 'ماما', 'mama', 'mama', 'mum', 'familie', '👩'),
  w('walidin', 'الوالدين', 'lwalidin', 'de ouders', 'the parents', 'familie', '👫'),
  w('khoya', 'خويا', 'khoya', 'mijn broer', 'my brother', 'familie', '👦'),
  w('khti', 'ختي', 'khti', 'mijn zus', 'my sister', 'familie', '👧'),
  w('jeddi', 'جدي', 'jeddi', 'mijn opa', 'my grandfather', 'familie', '👴'),
  w('jedda', 'جدتي', 'jeddti', 'mijn oma', 'my grandmother', 'familie', '👵'),
  w('ammi', 'عمي', '3ammi', 'mijn oom (kant van papa)', 'my uncle (father side)', 'familie', '🧔'),
  w('ammti', 'عمتي', '3ammti', 'mijn tante (kant van papa)', 'my aunt (father side)', 'familie', '👩'),
  w('khali', 'خالي', 'khali', 'mijn oom (kant van mama)', 'my uncle (mother side)', 'familie', '🧔'),
  w('khalti', 'خالتي', 'khalti', 'mijn tante (kant van mama)', 'my aunt (mother side)', 'familie', '👩'),
  w('weld', 'ولد', 'weld', 'jongen, zoon', 'boy, son', 'familie', '👦'),
  w('bent', 'بنت', 'bent', 'meisje, dochter', 'girl, daughter', 'familie', '👧'),
  w('drari', 'دراري', 'drari', 'kinderen', 'kids', 'familie', '🧒'),
  w('sahbi', 'صاحبي', 'sahbi', 'mijn vriend', 'my friend (m)', 'familie', '🧑‍🤝‍🧑'),
  w('sahbti', 'صاحبتي', 'sahbti', 'mijn vriendin', 'my friend (f)', 'familie', '👭'),
  w('hadi-khti', 'هادي ختي', 'hadi khti', 'dit is mijn zus', 'this is my sister', 'familie', '👉', 'hada = deze (m), hadi = deze (v).', true),
  w('hada-khoya', 'هادا خويا', 'hada khoya', 'dit is mijn broer', 'this is my brother', 'familie', '👉', '', true),

  // ---------------------------------------------------------------- cijfers
  w('wahed', 'واحد', 'wahed', 'één', 'one', 'cijfers', '1️⃣'),
  w('jouj', 'جوج', 'jouj', 'twee', 'two', 'cijfers', '2️⃣'),
  w('tlata', 'تلاتة', 'tlata', 'drie', 'three', 'cijfers', '3️⃣'),
  w('reb3a', 'ربعة', 'reb3a', 'vier', 'four', 'cijfers', '4️⃣'),
  w('khamsa', 'خمسة', 'khamsa', 'vijf', 'five', 'cijfers', '5️⃣'),
  w('setta', 'ستة', 'setta', 'zes', 'six', 'cijfers', '6️⃣'),
  w('seb3a', 'سبعة', 'seb3a', 'zeven', 'seven', 'cijfers', '7️⃣'),
  w('tmnya', 'تمنية', 'tmnya', 'acht', 'eight', 'cijfers', '8️⃣'),
  w('ts3ud', 'تسعود', 'ts3ud', 'negen', 'nine', 'cijfers', '9️⃣'),
  w('3achra', 'عشرة', '3achra', 'tien', 'ten', 'cijfers', '🔟'),
  w('hdach', 'حضاش', 'hdach', 'elf', 'eleven', 'cijfers', '1️⃣1️⃣'),
  w('tnach', 'طناش', 'tnach', 'twaalf', 'twelve', 'cijfers', '1️⃣2️⃣'),
  w('tltach', 'تلطاش', 'tltach', 'dertien', 'thirteen', 'cijfers'),
  w('rb3tach', 'ربعطاش', 'rb3tach', 'veertien', 'fourteen', 'cijfers'),
  w('khmstach', 'خمسطاش', 'khmstach', 'vijftien', 'fifteen', 'cijfers'),
  w('3achrin', 'عشرين', '3achrin', 'twintig', 'twenty', 'cijfers'),
  w('mya', 'مية', 'mya', 'honderd', 'hundred', 'cijfers', '💯'),
  w('shhal', 'شحال', 'shhal', 'hoeveel', 'how much / how many', 'cijfers', '❓'),

  // ---------------------------------------------------------------- kleuren
  w('hmer', 'حمر', 'hmer', 'rood', 'red', 'kleuren', '🔴', 'Vrouwelijk: hemra.'),
  w('zreq', 'زرق', 'zreq', 'blauw', 'blue', 'kleuren', '🔵', 'Vrouwelijk: zerqa.'),
  w('khder', 'خضر', 'khder', 'groen', 'green', 'kleuren', '🟢', 'Vrouwelijk: khedra.'),
  w('sfer', 'صفر', 'sfer', 'geel', 'yellow', 'kleuren', '🟡', 'Vrouwelijk: sefra.'),
  w('byed', 'بيض', 'byed', 'wit', 'white', 'kleuren', '⚪', 'Vrouwelijk: bida.'),
  w('khel', 'كحل', 'khel', 'zwart', 'black', 'kleuren', '⚫', 'Vrouwelijk: kehla.'),
  w('qehwi', 'قهوي', 'qehwi', 'bruin', 'brown', 'kleuren', '🟤', 'Van qehwa = koffie.'),
  w('wardi', 'وردي', 'wardi', 'roze', 'pink', 'kleuren', '🌸', 'Van werda = bloem.'),
  w('rmadi', 'رمادي', 'rmadi', 'grijs', 'grey', 'kleuren', '🩶'),
  w('brtqali', 'برتقالي', 'brtqali', 'oranje', 'orange', 'kleuren', '🟠'),
  w('shnu-lloun', 'شنو اللون؟', 'shnu lloun?', 'welke kleur is het?', 'what colour is it?', 'kleuren', '🎨', '', true),

  // ------------------------------------------------------------------- eten
  w('makla', 'الماكلة', 'lmakla', 'het eten', 'the food', 'eten', '🍽️'),
  w('lma', 'الما', 'lma', 'water', 'water', 'eten', '💧'),
  w('atay', 'أتاي', 'atay', 'muntthee', 'mint tea', 'eten', '🍵', 'Het hart van elke Marokkaanse ontvangst.'),
  w('qehwa', 'قهوة', 'qehwa', 'koffie', 'coffee', 'eten', '☕'),
  w('hlib', 'حليب', 'hlib', 'melk', 'milk', 'eten', '🥛'),
  w('khobz', 'خبز', 'khobz', 'brood', 'bread', 'eten', '🍞', 'In Marokko eet je bijna alles met khobz.'),
  w('zebda', 'زبدة', 'zebda', 'boter', 'butter', 'eten', '🧈'),
  w('3sel', 'عسل', '3sel', 'honing', 'honey', 'eten', '🍯'),
  w('bid', 'بيض', 'bid', 'eieren', 'eggs', 'eten', '🥚'),
  w('jben', 'جبن', 'jben', 'kaas', 'cheese', 'eten', '🧀'),
  w('lhem', 'لحم', 'lhem', 'vlees', 'meat', 'eten', '🥩'),
  w('djaj', 'دجاج', 'djaj', 'kip', 'chicken', 'eten', '🍗'),
  w('hut', 'حوت', 'hut', 'vis', 'fish', 'eten', '🐟'),
  w('khodra', 'خضرا', 'khodra', 'groente', 'vegetables', 'eten', '🥦'),
  w('fakya', 'فاكية', 'fakya', 'fruit', 'fruit', 'eten', '🍎'),
  w('tfah', 'تفاح', 'tfah', 'appel', 'apple', 'eten', '🍏'),
  w('banan', 'بانان', 'banan', 'banaan', 'banana', 'eten', '🍌'),
  w('limun', 'ليمون', 'limun', 'sinaasappel', 'orange (fruit)', 'eten', '🍊', 'Let op: de citroen heet hamd.'),
  w('hamd', 'حامض', 'hamd', 'citroen', 'lemon', 'eten', '🍋'),
  w('btata', 'بطاطا', 'btata', 'aardappel', 'potato', 'eten', '🥔'),
  w('matisha', 'مطيشة', 'matisha', 'tomaat', 'tomato', 'eten', '🍅'),
  w('bsla', 'بصلة', 'bsla', 'ui', 'onion', 'eten', '🧅'),
  w('sokkar', 'سكر', 'sokkar', 'suiker', 'sugar', 'eten', '🍬'),
  w('melha', 'ملحة', 'melha', 'zout', 'salt', 'eten', '🧂'),
  w('tajine', 'طاجين', 'tajine', 'tajine (stoofpot)', 'tagine', 'eten', '🍲', 'Ook de naam van de aardewerken pot met puntdeksel.'),
  w('kesksu', 'كسكسو', 'kesksu', 'couscous', 'couscous', 'eten', '🥘', 'Op vrijdag, na het gebed.'),
  w('harira', 'حريرة', 'harira', 'harira (soep)', 'harira soup', 'eten', '🍜', 'De soep waarmee je in ramadan de dag afsluit.'),
  w('msemmen', 'مسمن', 'msemmen', 'msemmen (bladerkoek)', 'msemmen pancake', 'eten', '🥞'),
  w('bnin', 'بنين', 'bnin', 'lekker', 'tasty', 'eten', '😋', 'Vrouwelijk: bnina.'),
  w('ju3an', 'جوعان', 'ju3an', 'hongerig', 'hungry', 'eten', '🍽️', 'Vrouwelijk: ju3ana.'),
  w('3etshan', 'عطشان', '3etshan', 'dorstig', 'thirsty', 'eten', '🥤'),
  w('bghit-nakol', 'بغيت ناكل', 'bghit nakol', 'ik wil eten', 'I want to eat', 'eten', '🍴', '', true),
  w('bsseha', 'بصحة', 'bsseha', 'eet smakelijk / gezondheid', 'enjoy your meal', 'eten', '🎉', 'Zeg je ook na een douche of een nieuw kapsel.'),

  // ------------------------------------------------------------------- huis
  w('dar', 'الدار', 'ddar', 'het huis', 'the house', 'huis', '🏠'),
  w('bit', 'البيت', 'lbit', 'de kamer', 'the room', 'huis', '🚪'),
  w('bit-n3as', 'بيت النعاس', 'bit nn3as', 'slaapkamer', 'bedroom', 'huis', '🛏️'),
  w('kuzina', 'كوزينا', 'kuzina', 'keuken', 'kitchen', 'huis', '🍳'),
  w('hemmam', 'حمام', 'hemmam', 'badkamer', 'bathroom', 'huis', '🛁'),
  w('bab', 'باب', 'bab', 'deur', 'door', 'huis', '🚪'),
  w('sherjem', 'شرجم', 'sherjem', 'raam', 'window', 'huis', '🪟'),
  w('tebla', 'طبلة', 'tebla', 'tafel', 'table', 'huis', '🪑'),
  w('kursi', 'كرسي', 'kursi', 'stoel', 'chair', 'huis', '🪑'),
  w('namusiya', 'ناموسية', 'namusiya', 'bed', 'bed', 'huis', '🛌'),
  w('telfaza', 'تلفازة', 'telfaza', 'televisie', 'television', 'huis', '📺'),
  w('telifun', 'تيليفون', 'telifun', 'telefoon', 'phone', 'huis', '📱'),
  w('sarut', 'ساروت', 'sarut', 'sleutel', 'key', 'huis', '🔑'),
  w('dou', 'ضو', 'dou', 'licht, lamp', 'light', 'huis', '💡'),
  w('zerbiya', 'زربية', 'zerbiya', 'tapijt', 'carpet', 'huis', '🧶'),
  w('mraya', 'مراية', 'mraya', 'spiegel', 'mirror', 'huis', '🪞'),
  w('stah', 'سطح', 'stah', 'dakterras', 'roof terrace', 'huis', '🏙️', 'Waar de was hangt en de buren praten.'),

  // ----------------------------------------------------------------- school
  w('medrasa', 'المدرسة', 'lmedrasa', 'de school', 'the school', 'school', '🏫'),
  w('qism', 'القسم', 'lqism', 'de klas', 'the classroom', 'school', '🧑‍🏫'),
  w('ostad', 'أستاد', 'lostad', 'de meester', 'the teacher (m)', 'school', '👨‍🏫'),
  w('ostada', 'أستادة', 'lostada', 'de juf', 'the teacher (f)', 'school', '👩‍🏫'),
  w('telmid', 'تلميذ', 'telmid', 'leerling', 'pupil', 'school', '🎒'),
  w('ktab', 'كتاب', 'ktab', 'boek', 'book', 'school', '📕'),
  w('kunash', 'كناش', 'kunash', 'schrift', 'notebook', 'school', '📓'),
  w('stilu', 'ستيلو', 'stilu', 'pen', 'pen', 'school', '🖊️'),
  w('qlem', 'قلم', 'qlem', 'potlood', 'pencil', 'school', '✏️'),
  w('memha', 'ممحاة', 'memha', 'gum', 'eraser', 'school', '🧽'),
  w('sebbura', 'سبورة', 'sebbura', 'schoolbord', 'blackboard', 'school', '🧑‍🏫'),
  w('wajib', 'واجب', 'wajib', 'huiswerk', 'homework', 'school', '📝'),
  w('3otla', 'عطلة', '3otla', 'vakantie', 'holiday', 'school', '🏖️'),
  w('imtihan', 'امتحان', 'imtihan', 'toets, examen', 'exam', 'school', '📄'),
  w('fhemt', 'فهمت', 'fhemt', 'ik snap het', 'I understand', 'school', '💡', '', true),
  w('mafhemtsh', 'مافهمتش', 'ma fhemtsh', 'ik snap het niet', 'I do not understand', 'school', '🤔', 'ma ... sh is de manier om nee te zeggen bij werkwoorden.', true),
  w('3awd-afak', 'عاود عافاك', '3awd 3afak', 'herhaal het alsjeblieft', 'repeat please', 'school', '🔁', '', true),
  w('bshwiya', 'بشوية', 'bshwiya', 'langzaam, rustig', 'slowly', 'school', '🐢', 'Handig: “hder bshwiya 3afak” = praat langzaam.'),

  // ----------------------------------------------------------------- dieren
  w('hayawanat', 'الحيوانات', 'lhayawanat', 'de dieren', 'the animals', 'dieren', '🐾'),
  w('mesh', 'مش', 'mesh', 'kat', 'cat', 'dieren', '🐈'),
  w('kelb', 'كلب', 'kelb', 'hond', 'dog', 'dieren', '🐕'),
  w('3wd', 'عود', '3wd', 'paard', 'horse', 'dieren', '🐎'),
  w('hmar', 'حمار', 'hmar', 'ezel', 'donkey', 'dieren', '🫏'),
  w('bgra', 'بقرة', 'bgra', 'koe', 'cow', 'dieren', '🐄'),
  w('khruf', 'خروف', 'khruf', 'schaap', 'sheep', 'dieren', '🐑'),
  w('m3za', 'معزة', 'm3za', 'geit', 'goat', 'dieren', '🐐', 'In Souss klimmen ze in de arganbomen.'),
  w('jmel', 'جمل', 'jmel', 'kameel, dromedaris', 'camel', 'dieren', '🐪'),
  w('djaja', 'دجاجة', 'djaja', 'kip (dier)', 'hen', 'dieren', '🐓'),
  w('tir', 'طير', 'tir', 'vogel', 'bird', 'dieren', '🐦'),
  w('far', 'فار', 'far', 'muis', 'mouse', 'dieren', '🐁'),
  w('nemla', 'نملة', 'nemla', 'mier', 'ant', 'dieren', '🐜'),
  w('sba3', 'سبع', 'sba3', 'leeuw', 'lion', 'dieren', '🦁', 'Het symbool van Marokko: Osud lAtlas.'),
  w('qerd', 'قرد', 'qerd', 'aap', 'monkey', 'dieren', '🐒'),
  w('fil', 'فيل', 'fil', 'olifant', 'elephant', 'dieren', '🐘'),
  w('hensh', 'حنش', 'hensh', 'slang', 'snake', 'dieren', '🐍'),
  w('fertetto', 'فرططو', 'fertetto', 'vlinder', 'butterfly', 'dieren', '🦋'),

  // ------------------------------------------------------------------- tijd
  w('lyum', 'اليوم', 'lyum', 'vandaag', 'today', 'tijd', '📅'),
  w('ghedda', 'غدا', 'ghedda', 'morgen', 'tomorrow', 'tijd', '🌅'),
  w('lbareh', 'البارح', 'lbareh', 'gisteren', 'yesterday', 'tijd', '🌘'),
  w('daba', 'دابا', 'daba', 'nu', 'now', 'tijd', '⏱️'),
  w('sbah', 'صباح', 'sbah', 'ochtend', 'morning', 'tijd', '🌄'),
  w('3shiya', 'عشية', '3shiya', 'middag, namiddag', 'afternoon', 'tijd', '🌇'),
  w('lil', 'ليل', 'lil', 'nacht', 'night', 'tijd', '🌙'),
  w('sa3a', 'الساعة', 'ssa3a', 'het uur, de klok', 'the hour', 'tijd', '🕰️'),
  w('simana', 'سيمانا', 'simana', 'week', 'week', 'tijd', '🗓️'),
  w('shher', 'شهر', 'shher', 'maand', 'month', 'tijd', '📆'),
  w('3am', 'عام', '3am', 'jaar', 'year', 'tijd', '🎉'),
  w('lethnin', 'التنين', 'lethnin', 'maandag', 'Monday', 'tijd', '1️⃣'),
  w('ttlat', 'التلات', 'ttlat', 'dinsdag', 'Tuesday', 'tijd', '2️⃣'),
  w('larb3', 'الاربع', 'larb3', 'woensdag', 'Wednesday', 'tijd', '3️⃣'),
  w('lekhmis', 'الخميس', 'lekhmis', 'donderdag', 'Thursday', 'tijd', '4️⃣'),
  w('jjem3a', 'الجمعة', 'jjem3a', 'vrijdag', 'Friday', 'tijd', '🕌', 'De dag van couscous en het vrijdaggebed.'),
  w('ssebt', 'السبت', 'ssebt', 'zaterdag', 'Saturday', 'tijd', '6️⃣'),
  w('lhedd', 'الحد', 'lhedd', 'zondag', 'Sunday', 'tijd', '7️⃣'),
  w('shhal-sa3a', 'شحال فالساعة؟', 'shhal f ssa3a?', 'hoe laat is het?', 'what time is it?', 'tijd', '⏰', '', true),
  w('jjaw', 'الجو', 'jjaw', 'het weer', 'the weather', 'tijd', '🌤️'),
  w('shta', 'شتا', 'shta', 'regen', 'rain', 'tijd', '🌧️'),
  w('shems', 'شمس', 'shems', 'zon', 'sun', 'tijd', '☀️'),
  w('rih', 'ريح', 'rih', 'wind', 'wind', 'tijd', '💨', 'Essaouira staat er bekend om.'),
  w('bred', 'برد', 'bred', 'koud', 'cold', 'tijd', '🥶'),
  w('skhun', 'سخون', 'skhun', 'warm, heet', 'hot', 'tijd', '🥵'),
  w('telj', 'تلج', 'telj', 'sneeuw', 'snow', 'tijd', '❄️', 'Ja, het sneeuwt in de Atlas.'),

  // --------------------------------------------------------------- lichaam
  w('ras', 'راس', 'ras', 'hoofd', 'head', 'lichaam', '🧠'),
  w('sh3ar', 'شعر', 'sh3ar', 'haar', 'hair', 'lichaam', '💇'),
  w('3in', 'عين', '3in', 'oog', 'eye', 'lichaam', '👁️', 'Twee ogen: 3inin.'),
  w('wden', 'ودن', 'wden', 'oor', 'ear', 'lichaam', '👂'),
  w('nif', 'نيف', 'nif', 'neus', 'nose', 'lichaam', '👃'),
  w('fomm', 'فم', 'fomm', 'mond', 'mouth', 'lichaam', '👄'),
  w('snan', 'سنان', 'snan', 'tanden', 'teeth', 'lichaam', '🦷'),
  w('yedd', 'يد', 'yedd', 'hand', 'hand', 'lichaam', '✋'),
  w('rjel', 'رجل', 'rjel', 'been, voet', 'leg, foot', 'lichaam', '🦵'),
  w('kersh', 'كرش', 'kersh', 'buik', 'belly', 'lichaam', '🫃'),
  w('qelb', 'قلب', 'qelb', 'hart', 'heart', 'lichaam', '❤️'),
  w('ferhan', 'فرحان', 'ferhan', 'blij', 'happy', 'lichaam', '😄', 'Vrouwelijk: ferhana.'),
  w('hzin', 'حزين', 'hzin', 'verdrietig', 'sad', 'lichaam', '😢'),
  w('3eyyan', 'عيان', '3eyyan', 'moe', 'tired', 'lichaam', '😴'),
  w('mrid', 'مريض', 'mrid', 'ziek', 'ill', 'lichaam', '🤒'),
  w('khayf', 'خايف', 'khayf', 'bang', 'scared', 'lichaam', '😨'),
  w('kayderni-rasi', 'كيضرني راسي', 'kayderni rasi', 'ik heb hoofdpijn', 'my head hurts', 'lichaam', '🤕', '', true),
  w('kanbghik', 'كنبغيك', 'kanbghik', 'ik hou van je', 'I love you', 'lichaam', '💛', 'Tegen familie en vrienden, heel gewoon.', true),

  // ----------------------------------------------------------- werkwoorden
  w('kanakol', 'كناكل', 'kanakol', 'ik eet', 'I eat', 'werkwoorden', '🍽️', 'ka- vooraan betekent: nu, gewoonlijk.'),
  w('kanshreb', 'كنشرب', 'kanshreb', 'ik drink', 'I drink', 'werkwoorden', '🥤'),
  w('kanmshi', 'كنمشي', 'kanmshi', 'ik ga', 'I go', 'werkwoorden', '🚶'),
  w('kanji', 'كنجي', 'kanji', 'ik kom', 'I come', 'werkwoorden', '🏃'),
  w('kanqra', 'كنقرا', 'kanqra', 'ik leer, ik lees', 'I study, I read', 'werkwoorden', '📖'),
  w('kanl3eb', 'كنلعب', 'kanl3eb', 'ik speel', 'I play', 'werkwoorden', '⚽'),
  w('kan3es', 'كنعس', 'kan3es', 'ik slaap', 'I sleep', 'werkwoorden', '😴'),
  w('kanshuf', 'كنشوف', 'kanshuf', 'ik kijk, ik zie', 'I look, I see', 'werkwoorden', '👀'),
  w('kansme3', 'كنسمع', 'kansme3', 'ik luister, ik hoor', 'I listen', 'werkwoorden', '👂'),
  w('kanhder', 'كنهضر', 'kanhder', 'ik praat', 'I speak', 'werkwoorden', '🗣️'),
  w('kanktab', 'كنكتب', 'kanktab', 'ik schrijf', 'I write', 'werkwoorden', '✍️'),
  w('kandhek', 'كنضحك', 'kandhek', 'ik lach', 'I laugh', 'werkwoorden', '😂'),
  w('kanjri', 'كنجري', 'kanjri', 'ik ren', 'I run', 'werkwoorden', '🏃'),
  w('bghit', 'بغيت', 'bghit', 'ik wil', 'I want', 'werkwoorden', '🙋'),
  w('3endi', 'عندي', '3endi', 'ik heb', 'I have', 'werkwoorden', '🎒'),
  w('ma3endish', 'ماعنديش', 'ma 3endish', 'ik heb niet', 'I do not have', 'werkwoorden', '🚫'),
  w('khessni', 'خصني', 'khessni', 'ik heb nodig', 'I need', 'werkwoorden', '🆘'),
  w('ndir', 'ندير', 'ndir', 'ik doe / ik zal doen', 'I do', 'werkwoorden', '🔧'),
  w('sir', 'سير', 'sir', 'ga! (tegen een jongen)', 'go! (m)', 'werkwoorden', '➡️', 'Tegen een meisje: siri. Tegen meerdere: siru.'),
  w('aji', 'اجي', 'aji', 'kom!', 'come!', 'werkwoorden', '👋'),
  w('shuf', 'شوف', 'shuf', 'kijk!', 'look!', 'werkwoorden', '👁️'),

  // ----------------------------------------------------------------- vragen
  w('shnu', 'شنو', 'shnu', 'wat', 'what', 'vragen', '❓'),
  w('shkun', 'شكون', 'shkun', 'wie', 'who', 'vragen', '🕵️'),
  w('fin', 'فين', 'fin', 'waar', 'where', 'vragen', '📍'),
  w('imta', 'امتى', 'imta', 'wanneer', 'when', 'vragen', '🕐'),
  w('3lash', 'علاش', '3lash', 'waarom', 'why', 'vragen', '🤔'),
  w('kifash', 'كيفاش', 'kifash', 'hoe', 'how', 'vragen', '🛠️'),
  w('wesh', 'واش', 'wesh', 'of...? (ja/nee-vraag)', 'question marker', 'vragen', '❔', 'Zet het vooraan om een ja/nee-vraag te maken: wesh nta mzyan?'),
  w('shnu-hada', 'شنو هادا؟', 'shnu hada?', 'wat is dit?', 'what is this?', 'vragen', '🔍', '', true),
  w('fin-kayn', 'فين كاين؟', 'fin kayn...?', 'waar is...?', 'where is...?', 'vragen', '🗺️', '', true),

  // -------------------------------------------------------------- winkelen
  w('souq', 'السوق', 'ssouq', 'de markt', 'the market', 'winkelen', '🛍️'),
  w('hanut', 'حانوت', 'hanut', 'winkeltje', 'small shop', 'winkelen', '🏪', 'De buurtwinkel waar alles is.'),
  w('flus', 'فلوس', 'flus', 'geld', 'money', 'winkelen', '💶'),
  w('derhem', 'درهم', 'derhem', 'dirham', 'dirham', 'winkelen', '🪙', 'De munt van Marokko (MAD).'),
  w('ghali', 'غالي', 'ghali', 'duur', 'expensive', 'winkelen', '💸'),
  w('rkhis', 'رخيص', 'rkhis', 'goedkoop', 'cheap', 'winkelen', '🏷️'),
  w('shhal-hada', 'شحال هادا؟', 'shhal hada?', 'hoeveel kost dit?', 'how much is this?', 'winkelen', '💰', '', true),
  w('ghali-bezzaf', 'غالي بزاف', 'ghali bezzaf!', 'veel te duur!', 'too expensive!', 'winkelen', '😮', 'Het startsein om te onderhandelen.', true),
  w('3tini', 'عطيني', '3tini', 'geef me...', 'give me...', 'winkelen', '🤲'),
  w('bghit-hada', 'بغيت هادا', 'bghit hada', 'ik wil deze', 'I want this one', 'winkelen', '👉', '', true),
  w('kbir', 'كبير', 'kbir', 'groot', 'big', 'winkelen', '🐘'),
  w('sghir', 'صغير', 'sghir', 'klein', 'small', 'winkelen', '🐜'),
  w('jdid', 'جديد', 'jdid', 'nieuw', 'new', 'winkelen', '✨'),
  w('qdim', 'قديم', 'qdim', 'oud', 'old', 'winkelen', '📜'),

  // -------------------------------------------------------------------- weg
  w('limen', 'ليمن', 'limen', 'rechts', 'right', 'weg', '👉'),
  w('lisar', 'ليسار', 'lisar', 'links', 'left', 'weg', '👈'),
  w('nishan', 'نيشان', 'nishan', 'rechtdoor', 'straight ahead', 'weg', '⬆️'),
  w('qeddam', 'قدام', 'qeddam', 'voor, vooruit', 'in front, forward', 'weg', '🎯', 'Hier komt de naam Gedmma vandaan: vooruit.'),
  w('mor', 'مور', 'mor', 'achter', 'behind', 'weg', '⬅️'),
  w('fuq', 'فوق', 'fuq', 'boven, op', 'above, on', 'weg', '⬆️'),
  w('teht', 'تحت', 'teht', 'onder', 'under', 'weg', '⬇️'),
  w('hda', 'حدا', 'hda', 'naast', 'next to', 'weg', '↔️'),
  w('hnaya', 'هنا', 'hnaya', 'hier', 'here', 'weg', '📍'),
  w('temma', 'تما', 'temma', 'daar', 'there', 'weg', '🗺️'),
  w('zenqa', 'زنقة', 'zenqa', 'straat', 'street', 'weg', '🛣️'),
  w('medina', 'مدينة', 'medina', 'stad, oude stad', 'city, old town', 'weg', '🏙️'),
  w('bhar', 'بحر', 'bhar', 'zee', 'sea', 'weg', '🌊'),
  w('jbel', 'جبل', 'jbel', 'berg', 'mountain', 'weg', '⛰️'),
  w('sahra', 'صحرا', 'sahra', 'woestijn', 'desert', 'weg', '🐪'),
  w('jame3', 'جامع', 'jame3', 'moskee', 'mosque', 'weg', '🕌'),
  w('mustashfa', 'مستشفى', 'mustashfa', 'ziekenhuis', 'hospital', 'weg', '🏥'),
  w('tobis', 'طوبيس', 'tobis', 'bus', 'bus', 'weg', '🚌'),
  w('tomobil', 'طوموبيل', 'tomobil', 'auto', 'car', 'weg', '🚗'),
  w('bshklit', 'بشكليط', 'bshklit', 'fiets', 'bicycle', 'weg', '🚲'),

  // --------------------------------------------------------------- cultuur
  w('mghrib', 'المغرب', 'lMghrib', 'Marokko', 'Morocco', 'cultuur', '🇲🇦', 'Letterlijk: het westen.'),
  w('darija', 'الدارجة', 'ddarija', 'Darija (Marokkaans-Arabisch)', 'Darija', 'cultuur', '💬'),
  w('tamazight', 'تامازيغت', 'tamazight', 'Amazigh (Berbers)', 'Amazigh', 'cultuur', '🪶', 'De tweede taal van Marokko, met een eigen alfabet: ⵜⵉⴼⵉⵏⴰⵖ.'),
  w('ramadan', 'رمضان', 'Ramadan', 'ramadan', 'Ramadan', 'cultuur', '🌙'),
  w('3id', 'العيد', 'l3id', 'het feest (Eid)', 'Eid', 'cultuur', '🎉'),
  w('3id-mubarak', 'عيد مبارك', '3id mubarak', 'fijne Eid', 'happy Eid', 'cultuur', '🎊', '', true),
  w('henna', 'حنة', 'henna', 'henna', 'henna', 'cultuur', '🖐️'),
  w('jellaba', 'جلابة', 'jellaba', 'djellaba (lang gewaad)', 'djellaba', 'cultuur', '🧥'),
  w('babouche', 'بلغة', 'belgha', 'babouches (slippers)', 'babouche slippers', 'cultuur', '👡'),
  w('gnawa', 'كناوة', 'gnawa', 'gnawa (muziek)', 'Gnawa music', 'cultuur', '🎶', 'Muziek met de guembri en ijzeren qraqeb.'),
  w('casablanca', 'الدار البيضاء', 'ddar lbida', 'Casablanca', 'Casablanca', 'cultuur', '🏙️', 'Letterlijk: het witte huis.'),
  w('marrakech', 'مراكش', 'Merrakch', 'Marrakech', 'Marrakesh', 'cultuur', '🏰'),
  w('rabat', 'الرباط', 'Rrbat', 'Rabat', 'Rabat', 'cultuur', '🏛️', 'De hoofdstad.'),
  w('tanja', 'طنجة', 'Tanja', 'Tanger', 'Tangier', 'cultuur', '⛴️'),
  w('fas', 'فاس', 'Fas', 'Fez', 'Fez', 'cultuur', '🕌'),
  w('agadir', 'أكادير', 'Agadir', 'Agadir', 'Agadir', 'cultuur', '🏖️'),
]
