import { createHash } from 'node:crypto';
import { analyticsToken, IS_PRODUCTION_BUILD } from './render.js';

/**
 * Cloudflare Pages reads two plain-text files from the root of the published
 * directory: _headers sets response headers, _redirects sets redirects. Both
 * are generated here rather than kept by hand, because the Content-Security-
 * Policy has to list a hash of every inline script the build writes — a policy
 * maintained by hand goes stale the first time a line of copy changes and then
 * silently blocks the sign-up form.
 */

/** Matches a <script> element that has no src, capturing its exact contents. */
const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g;

/**
 * The CSP hash is taken over the bytes between the tags, exactly as they are
 * served — no trimming, no re-indenting. Anything else and the browser blocks
 * the script it was meant to allow.
 */
export function inlineScriptHashes(html: string): string[] {
  const hashes: string[] = [];
  for (const [, body = ''] of html.matchAll(INLINE_SCRIPT)) {
    hashes.push(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
  return hashes;
}

function contentSecurityPolicy(scriptHashes: string[]): string {
  // Cloudflare Web Analytics loads one script and posts what it counts back to
  // Cloudflare. Both hosts are named only when a token is configured: an
  // allowance for a script the site does not load is an allowance an attacker
  // can use and the site cannot miss.
  const measuring = analyticsToken() !== '';
  const scripts = measuring ? "'self' https://static.cloudflareinsights.com" : "'self'";
  const connects = measuring ? "'self' https://cloudflareinsights.com" : "'self'";

  // The forms post to this same origin, so 'self' covers them and no second
  // hostname has to be trusted here.
  return [
    "default-src 'self'",
    "base-uri 'self'",
    // The form is submitted by fetch, never by the browser's own navigation,
    // so nothing legitimate posts anywhere.
    "form-action 'none'",
    "frame-ancestors 'none'",
    "object-src 'none'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self'",
    "media-src 'self'",
    `connect-src ${connects}`,
    `script-src ${scripts} ${[...new Set(scriptHashes)].sort().join(' ')}`,
    'upgrade-insecure-requests',
  ].join('; ');
}

/**
 * Cache lifetimes. None of the filenames carry a content hash, so nothing may
 * be cached for a year unless changing it would mean giving it a new name
 * anyway. The fonts qualify — a different cut of Inter would be a different
 * file. The stylesheet does not, so it gets an hour, and the pages themselves
 * are revalidated on every view: a wrong price left in a reader's cache for a
 * day is worse than the request it saves.
 */
const CACHE: [pattern: string, value: string][] = [
  ['/fonts/*', 'public, max-age=31536000, immutable'],
  ['/icons/*', 'public, max-age=2592000'],
  ['/og/*', 'public, max-age=2592000'],
  ['/video/*', 'public, max-age=2592000'],
  ['/favicon.svg', 'public, max-age=2592000'],
  ['/styles.css', 'public, max-age=3600'],
];

export function renderHeaders(scriptHashes: string[]): string {
  const global = [
    `  Content-Security-Policy: ${contentSecurityPolicy(scriptHashes)}`,
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    '  X-Frame-Options: DENY',
    '  Permissions-Policy: geolocation=(), camera=(), microphone=(), payment=(), usb=()',
    '  Cross-Origin-Opener-Policy: same-origin',
    // Only the real domain makes this promise. Setting it on a preview would
    // pin every future subdomain of the preview host to HTTPS as well.
    ...(IS_PRODUCTION_BUILD
      ? ['  Strict-Transport-Security: max-age=31536000; includeSubDomains']
      : ['  X-Robots-Tag: noindex, nofollow']),
    '  Cache-Control: public, max-age=0, must-revalidate',
  ];

  const blocks = [
    `/*\n${global.join('\n')}`,
    ...CACHE.map(([pattern, value]) => `${pattern}\n  Cache-Control: ${value}`),
  ];

  return `# Generated by apps/web/src/build.ts — do not edit by hand.\n${blocks.join('\n\n')}\n`;
}

/**
 * There is no _redirects file, and that is deliberate.
 *
 * The one redirect this site wants is www to the bare domain, so that two
 * hostnames do not split the ranking between them. Cloudflare Pages can express
 * that, because its _redirects accepts a full URL. Workers cannot: it allows
 * only relative paths, and a relative rule cannot tell one hostname from
 * another — `/* https://buurklus.nl/:splat` would also match the bare domain
 * and loop forever.
 *
 * So www is handled where it belongs on Workers: attach only the bare domain as
 * a custom domain, or add a Redirect Rule in the dashboard. docs/DEPLOY.md says
 * how. Nothing else on this site redirects, so the file has no other reason to
 * exist and is not written at all.
 */
// (No export: the absence of the file is the whole point.)
