import { createHash } from 'node:crypto';
import { API_URL, CANONICAL_SITE_URL, IS_PRODUCTION_BUILD } from './render.js';

/**
 * Cloudflare Pages reads two plain-text files from the root of the published
 * directory: _headers sets response headers, _redirects sets redirects. Both
 * are generated here rather than kept by hand, because the Content-Security-
 * Policy has to list a hash of every inline script the build writes — a policy
 * maintained by hand goes stale the first time a line of copy changes and then
 * silently blocks the sign-up form.
 */

/** Matches a <script> element that has no src, capturing its exact contents. */
const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g;

/**
 * The CSP hash is taken over the bytes between the tags, exactly as they are
 * served — no trimming, no re-indenting. Anything else and the browser blocks
 * the script it was meant to allow.
 */
export function inlineScriptHashes(html: string): string[] {
  const hashes: string[] = [];
  for (const [, body = ''] of html.matchAll(INLINE_SCRIPT)) {
    hashes.push(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
  return hashes;
}

function contentSecurityPolicy(scriptHashes: string[]): string {
  // connect-src has to name the API host: the sign-up form posts there, and
  // under default-src 'self' the browser would refuse the request.
  const api = new URL(API_URL).origin;
  return [
    "default-src 'self'",
    "base-uri 'self'",
    // The form is submitted by fetch, never by the browser's own navigation,
    // so nothing legitimate posts anywhere.
    "form-action 'none'",
    "frame-ancestors 'none'",
    "object-src 'none'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self'",
    "media-src 'self'",
    `connect-src 'self' ${api}`,
    `script-src 'self' ${[...new Set(scriptHashes)].sort().join(' ')}`,
    'upgrade-insecure-requests',
  ].join('; ');
}

/**
 * Cache lifetimes. None of the filenames carry a content hash, so nothing may
 * be cached for a year unless changing it would mean giving it a new name
 * anyway. The fonts qualify — a different cut of Inter would be a different
 * file. The stylesheet does not, so it gets an hour, and the pages themselves
 * are revalidated on every view: a wrong price left in a reader's cache for a
 * day is worse than the request it saves.
 */
const CACHE: [pattern: string, value: string][] = [
  ['/fonts/*', 'public, max-age=31536000, immutable'],
  ['/icons/*', 'public, max-age=2592000'],
  ['/og/*', 'public, max-age=2592000'],
  ['/video/*', 'public, max-age=2592000'],
  ['/favicon.svg', 'public, max-age=2592000'],
  ['/styles.css', 'public, max-age=3600'],
];

export function renderHeaders(scriptHashes: string[]): string {
  const global = [
    `  Content-Security-Policy: ${contentSecurityPolicy(scriptHashes)}`,
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    '  X-Frame-Options: DENY',
    '  Permissions-Policy: geolocation=(), camera=(), microphone=(), payment=(), usb=()',
    '  Cross-Origin-Opener-Policy: same-origin',
    // Only the real domain makes this promise. Setting it on a preview would
    // pin every future subdomain of the preview host to HTTPS as well.
    ...(IS_PRODUCTION_BUILD
      ? ['  Strict-Transport-Security: max-age=31536000; includeSubDomains']
      : ['  X-Robots-Tag: noindex, nofollow']),
    '  Cache-Control: public, max-age=0, must-revalidate',
  ];

  const blocks = [
    `/*\n${global.join('\n')}`,
    ...CACHE.map(([pattern, value]) => `${pattern}\n  Cache-Control: ${value}`),
  ];

  return `# Generated by apps/web/src/build.ts — do not edit by hand.\n${blocks.join('\n\n')}\n`;
}

export function renderRedirects(): string {
  const apex = new URL(CANONICAL_SITE_URL).host;
  // Two hostnames serving the same pages split the ranking between them, so
  // www is sent to the bare domain. The free *.pages.dev hostname is left
  // alone: every page already carries a canonical link to the real domain,
  // which is what tells Google which copy counts.
  return [
    '# Generated by apps/web/src/build.ts — do not edit by hand.',
    `https://www.${apex}/* ${CANONICAL_SITE_URL}/:splat 301`,
    '',
  ].join('\n');
}
