import type { SleutelVertaling } from './sleutels-talen'

/**
 * De sleutels van Marokko in het Duits.
 *
 * Wordt deel voor deel vertaald. Wat hier staat is af; de rest valt terug op
 * het Nederlands tot het zover is.
 *
 * De regelval van het Nederlands blijft staan: één alinea daar is één alinea
 * hier. Dat is geen vormfetisj — een hoofdstuk van dit boek is opgebouwd uit
 * korte alinea’s met stiltes ertussen, en wie die samenvoegt haalt het tempo
 * eruit.
 *
 * Aanhalingstekens zijn de Duitse „ en “, de apostrof is overal de
 * typografische ’ en nooit de rechte: die breekt de string waar dit bestand
 * in staat.
 */
export const DE_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'Der Olivenbrand',
    jaar: '± 200',
    waar: 'Walili (Volubilis), am Fuß des Zerhoun',
    verteller: 'Tala, elf Jahre, Tochter eines erkrankten Ölmüllers',
    flap: 'Tala hat den Schlüssel zum Lager, und der Aufseher will ihn haben. Als das Öl der ganzen Stadt in Gefahr gerät, muss sie zwischen Gehorchen und Rechthaben wählen.',
    sleutel: 'Der Schlüssel wird in Walili von Talas Großvater geschmiedet und zieht am Ende mit einer amazighischen Karawane in die Hügel.',
    echt: [
      'Volubilis — auf Arabisch Walili — war eine wirkliche römische Stadt bei Meknès, mit Tausenden Einwohnern, Thermen und gepflasterten Straßen.',
      'Die Stadt lebte vom Olivenöl. Dutzende Ölpressen sind ausgegraben worden, und sie arbeiteten nach demselben Prinzip wie die Pressen, die in Marokko heute noch benutzt werden.',
      'Die Böden waren voller Mosaiken. Ein Teil davon liegt noch immer da, unter freiem Himmel.',
      'Die Bevölkerung war größtenteils amazighisch; römisches und amazighisches Leben gingen hier ineinander über.',
    ],
    verzonnen: [
      'Tala, ihre Familie und der Aufseher Marcus haben nicht existiert.',
      'Das Feuer in der Geschichte ist erfunden. Es gibt keinen Beleg für einen großen Brand in Walili in dieser Zeit.',
      'Der Schlüssel mit dem achtzackigen Stern ist erfunden. Der achtzackige Khatam ist dagegen ein echtes und jahrhundertealtes marokkanisches Motiv.',
    ],
    hoofdstukken: [
      { titel: 'Der Schlüssel', tekst: [
        'Tala wachte von dem Geruch auf.',
        'Oliven. Gepresste Oliven, warm und bitter. Die ganze Stadt roch in diesen Wochen danach. Sie blieb kurz liegen und horchte. Draußen knarrte die große Presse schon. Das hieß, sie war zu spät.',
        'Sie sprang aus dem Bett und zog sich das Kleid über den Kopf.',
        '„Tala!“, rief ihre Mutter von unten. „Das Tor!“',
        'Das Tor. Natürlich das Tor.',
        'Seit ihr Vater krank geworden war, machte Tala seine Arbeit. Jeden Morgen ging sie zum Lager hinter dem Haus und schloss die Tür auf. Dort standen die Krüge. Hundert Krüge, bis zum Rand mit Öl gefüllt, bereit für den Hafen.',
        'Der Schlüssel hing an einer Schnur um ihren Hals. Er war aus Bronze und so lang wie ihre Hand. Ihr Großvater hatte ihn geschmiedet, lange bevor es sie gab. Im Kopf saßen acht Zacken, wie ein Stern.',
        '„Verlier ihn nicht“, hatte ihr Vater gesagt. Er hatte es leise gesagt, denn lauter konnte er nicht mehr. „Diese Tür geht für nichts anderes auf.“',
        'Tala rannte die Treppe hinunter, an der Küche vorbei, über den Innenhof. Es war noch früh. Die Sonne stand gerade über den Hügeln und die Steine waren kalt unter ihren Füßen.',
        'Beim Lager stand ein Mann.',
        'Sie blieb stehen.',
        'Er war groß und trug den roten Mantel des Aufsehers. Marcus. Jeder in Walili kannte Marcus, und niemand mochte ihn.',
        '„Du bist spät“, sagte er.',
        '„Ich bin pünktlich“, sagte Tala.',
        'Sie wusste, dass sie das nicht hätte sagen sollen. Sie sagte es trotzdem.',
        'Marcus sah sie an. Dann streckte er die Hand aus.',
        '„Gib mir den Schlüssel. Ein Kind hat nicht auf hundert Krüge aufzupassen.“',
        'Tala trat einen Schritt zurück.',
        'In ihrem Kopf hörte sie ihren Vater. *Diese Tür geht für nichts anderes auf.* Und sie dachte an etwas anderes, an etwas, das sie gestern gesehen und für nichts gehalten hatte.',
        'Zwei Krüge, die nicht an ihrem Platz standen.',
        '„Nun?“, sagte Marcus.',
        'Tala schloss die Hand um die Bronze. Sie war warm geworden von ihrer Haut.',
        '„Nein“, sagte sie.',
      ] },
      { titel: 'Zwei Krüge', tekst: [
        'Marcus lachte nicht. Er wurde auch nicht wütend. Das war das Schlimmste.',
        'Er ließ die Hand sinken, zog seinen Mantel zurecht und sagte: „Wie du willst.“ Dann ging er weg, die Gasse hinaus, ohne sich umzudrehen.',
        'Tala blieb stehen, bis sie seine Schritte nicht mehr hörte. Erst danach merkte sie, dass ihre Hände zitterten.',
        'Sie machte die Tür auf.',
        'Drinnen war es dunkel und kühl. Die Krüge standen in Reihen zu zehnt, mit Stroh dazwischen, damit sie nicht aneinanderschlugen. Zehn Reihen zu zehn. Jeden Morgen zählte sie sie. Das hatte ihr Vater ihr beigebracht, als sie sechs war, und damals war es noch ein Spiel.',
        'Sie fing links an und zählte laut, wie immer.',
        'Bei der hintersten Reihe hörte sie auf.',
        'Es standen neun da.',
        'Tala zählte noch einmal. Neun. Sie ging um die Reihe herum, bückte sich, sah hinter das Stroh. Neun.',
        'Gestern hatte sie auch etwas Seltsames gesehen. Zwei Krüge, die falsch standen, mit den Henkeln zur Wand statt zum Gang. Sie hatte gedacht: das hat jemand in Eile gemacht. Sie hatte sie zurechtgerückt und nicht mehr daran gedacht.',
        'Jetzt stand einer weniger da.',
        'Sie setzte sich in die Türöffnung, den Rücken am Pfosten, die Knie angezogen, und versuchte sich zu überlegen, was sie tun sollte.',
        'Sie konnte es ihrer Mutter sagen. Aber ihre Mutter hatte diesen Monat schon genug: einen kranken Mann oben, ein Haus voller Leute, die bezahlt werden mussten, und eine Ernte, die in drei Wochen zum Hafen sollte.',
        'Sie konnte es Marcus sagen. Marcus war der Aufseher. Das war seine Arbeit.',
        'Tala sah in die Gasse, in der er verschwunden war.',
        'Nein.',
        '„Du stehst im Weg“, sagte eine Stimme.',
        'Sie schreckte auf. Vor ihr stand ein Junge in ihrem Alter, mit einer Lederschürze und den Armen voller Reisigbündel. Seine Hände waren schwarz.',
        '„Ich stehe nicht im Weg“, sagte Tala. „Das ist meine Tür.“',
        '„Dann stehst du deiner eigenen Tür im Weg.“',
        'Er hieß Yidir und arbeitete in der Schmiede am Ende der Straße. Tala kannte ihn vom Sehen, so wie man in Walili jeden vom Sehen kannte, und sonst nicht.',
        'Sie stand auf, um ihn vorbeizulassen. Er ging nicht weiter.',
        '„Du zählst jeden Morgen“, sagte er.',
        '„Woher weißt du das?“',
        '„Ich komme jeden Morgen vorbei.“',
        'Tala zögerte. Dann sagte sie es doch, weil es heraus musste und weil er nun einmal dastand.',
        '„Einer fehlt.“',
        'Yidir stellte seine Reisigbündel ab.',
        '„Einer?“, sagte er. „Dann hast du Glück gehabt. Bei uns fehlen sechs Eisenstangen.“',
      ] },
      { titel: 'Wie man Öl macht', tekst: [
        'An diesem Nachmittag stand Tala bei der Presse, wie jeden Tag in der Ernte.',
        'Die Presse war ein ausgehöhlter Stein, so groß wie ein Karren, mit einem runden Stein darin, den ein Esel im Kreis zog. Die Oliven kamen hinein, wurden zerquetscht, und was herauskam war ein dicker brauner Brei, der nach nichts aussah.',
        'Das war der Teil, der Fremde immer enttäuschte. „Das soll Öl sein?“, fragten sie dann. Nein. Das war der Anfang.',
        'Der Brei kam in runde Matten aus geflochtenem Schilf. Diese Matten wurden unter der Balkenpresse aufeinandergestapelt, und dann drehten zwei Männer an der Schraube, langsam, als hätten sie Zeit. Unter dem Stapel lief eine Rinne.',
        'Da kam es heraus.',
        'Zuerst Wasser, trüb und schmutzig. Dann, nach einer Weile, etwas anderes. Etwas, das auf dem Wasser schwamm und grüner war als alles, was Tala kannte.',
        'Ihr Vater hatte sie das erste Mal am Nacken gepackt und ihren Kopf darübergehalten. „Riech“, hatte er gesagt. „Das ist es. Wenn es so riecht, ist es gut. Wenn es nach nichts riecht, hast du zu lange gewartet.“',
        'Sie hatte damals gelogen, dass sie es rieche. Jetzt roch sie es wirklich.',
        'Walili lebte davon. Nicht von den Mosaikböden, über die Besucher liefen, nicht von den Säulen auf dem Platz, nicht von den gepflasterten Straßen. Davon. Von gepressten Oliven, die in Krüge kamen, auf Karren an die Küste und auf Schiffe zu Orten, von denen Tala nur die Namen kannte.',
        'Sie achtete auf die Rinne und auf die Matten und auf den Esel, und dabei dachte sie an neunundneunzig Krüge.',
        'Sechs Eisenstangen, hatte Yidir gesagt. Aus der Schmiede.',
        'Eisen war teuer. Öl war teuer. Und beides ging in dieselbe Richtung aus der Stadt: über die Straße zum Hafen.',
        '„Tala.“ Einer der Männer zeigte auf die Rinne. „Sie läuft über.“',
        'Sie schoss nach vorn und schob die Schale darunter, zu spät. Ein Strahl Öl lief über den Stein und verschwand zwischen den Fugen.',
        'Ein Finger dick, vielleicht zwei. Genug für eine Familie für eine Woche.',
        'Der Mann sagte nichts dazu. Das machte es schlimmer.',
      ] },
      { titel: 'Was ein Aufseher darf', tekst: [
        'Marcus kam am dritten Tag wieder, und er kam nicht allein.',
        'Tala sah ihn den Innenhof betreten, zwei Männer hinter sich. Ihre Mutter kam heraus, wischte sich die Hände am Kleid ab und stellte sich genau zwischen ihn und die Tür.',
        '„Friede“, sagte Marcus.',
        '„Friede“, sagte ihre Mutter, in dem Ton, in dem man das sagt, wenn man es nicht so meint.',
        '„Dein Mann ist krank.“',
        '„Mein Mann ruht.“',
        '„Drei Wochen“, sagte Marcus. „In drei Wochen geht die Ernte zum Hafen, und die Stadt rechnet mit dem, was in diesem Haus steht. Ich muss wissen, dass es da ist.“',
        '„Es ist da.“',
        '„Ich will es sehen.“',
        'Es entstand eine Stille. Tala stand in der Küchentür und traute sich nicht, sich zu bewegen.',
        'Ihre Mutter sagte: „Du darfst schauen. Meine Tochter schließt auf.“',
        'Tala ging über den Innenhof unter den Augen von fünf Menschen. Sie zog die Schnur über den Kopf, steckte den Schlüssel ins Schloss und drückte die Tür auf.',
        'Marcus ging hinein. Er ging die Reihen entlang, langsam, die Hände auf dem Rücken. Bei der hintersten Reihe blieb er stehen.',
        'Tala hielt den Atem an.',
        '„Neunundneunzig“, sagte Marcus.',
        'Er drehte sich um und sah ihre Mutter an.',
        '„Es müssten hundert sein.“',
        'Ihre Mutter erstarrte. Tala sah es an ihren Schultern.',
        '„Dann ist einer zerbrochen“, sagte sie.',
        '„Dann lägen Scherben da.“ Marcus breitete die Hände aus. „Ich sehe keine Scherben. Ich sehe Stroh, das zurechtgezogen worden ist.“',
        'Er wartete kurz, genau lang genug.',
        '„Ich sage nicht, dass ihr stehlt“, sagte er dann. „Ich sage, dass ein Kind von elf Jahren den Schlüssel zu hundert Krügen hat und dass heute neunundneunzig dastehen. Das sage ich. Und das werde ich auch auf dem Platz sagen.“',
        'Er ging zur Tür hinaus und an Tala vorbei, als wäre sie ein Pfosten.',
        'Als er weg war, setzte sich ihre Mutter auf den Rand des Brunnens. Sie sagte sehr lange nichts.',
        '„Mama“, sagte Tala. „Ich habe ihn nicht—“',
        '„Ich weiß.“',
        '„Ich habe sie am Montag gezählt und da waren es noch—“',
        '„Tala.“ Ihre Mutter sah auf. Ihre Augen waren rot. „Ich weiß. Und das hilft uns nichts.“',
      ] },
      { titel: 'Die Schmiede', tekst: [
        'Yidir saß auf einem umgedrehten Eimer vor der Schmiede und schmirgelte ein Scharnier.',
        '„Du hattest recht“, sagte Tala.',
        '„Das sagen mir die Leute selten“, sagte Yidir, ohne aufzusehen. „Womit?“',
        '„Damit, dass es nicht ein Krug war.“',
        'Jetzt sah er doch auf.',
        'Tala setzte sich neben ihn auf die Schwelle und erzählte es. Von Marcus, von neunundneunzig, von dem, was er auf dem Platz sagen würde. Yidir hörte zu, wie er alles tat: als dächte er nebenbei an etwas anderes, und dabei entging ihm nichts.',
        '„Und dein Eisen?“, fragte sie.',
        '„Sechs Stangen. Mein Meister denkt, er hat sich verzählt.“ Yidir zuckte mit den Schultern. „Mein Meister verzählt sich nie.“',
        '„Wann?“',
        '„Letzte Woche. Und die Woche davor drei.“',
        'Tala zog die Knie an.',
        '„Was geht aus der Stadt hinaus?“, fragte sie. „Jeden Tag, meine ich.“',
        'Yidir dachte nach.',
        '„Karren“, sagte er. „Öl, Getreide, Häute, Eisen. Alles geht über die Straße nach Norden. Am Tor steht ein Wachposten. Da wird alles aufgeschrieben.“',
        '„Von wem?“',
        'Yidir sah sie an.',
        '„Vom Aufseher“, sagte er.',
        'Sie sagten beide eine Weile nichts.',
        '„Das beweist nichts“, sagte Tala schließlich.',
        '„Nein.“',
        '„Wenn ich das sage, sagen sie, ein Kind von elf beschuldigt einen Mann, weil er es nicht mag.“',
        '„Ja“, sagte Yidir. „Das sagen sie.“',
        'Er legte das Scharnier weg.',
        '„Also brauchst du etwas, das sie nicht wegreden können.“',
        '„Zum Beispiel?“',
        '„Zum Beispiel sehen, was nachts durch das Tor geht.“',
        'Tala sah ihn an. Er sah zurück, und zum ersten Mal, seit sie ihn kannte, lachte er.',
      ] },
      { titel: 'Was nachts durch das Tor geht', tekst: [
        'Sie lagen auf dem Dach des Badehauses, flach auf dem Bauch, das Kinn auf den Armen.',
        'Das Dach war warm vom Tag. Unter ihnen lag die Straße, die zum nördlichen Tor führte, breit genug für zwei Karren nebeneinander. Am Tor brannte eine Lampe.',
        '„Wie lange noch?“, flüsterte Tala.',
        '„Weiß ich nicht.“',
        '„Du hast gesagt, nachts gehen Karren.“',
        '„Ich habe gesagt, ich dáchte, dass nachts Karren gehen.“',
        'Tala seufzte und legte den Kopf auf den Arm.',
        'Die Sterne waren in dieser Nacht unglaublich. In der Stadt sah man sie halb, durch das Licht und den Rauch, aber hier oben waren es so viele, dass es unruhig machte.',
        '„Meine Großmutter sagt, sie sind eine Karte“, sagte Yidir.',
        '„Die Sterne?“',
        '„Ja. Wer sie lesen kann, kommt überallhin. Sie sagt, ihre Familie ist so aus der Wüste bis hierher gelaufen.“',
        '„Kannst du sie lesen?“',
        '„Nein“, sagte Yidir. „Es hat es mir niemand beigebracht.“',
        'Dann hörten sie es.',
        'Ein Karren. Keine zwei Esel, keine Pferde — ein Esel, langsam, und das Geräusch von Holz, das unter Gewicht knarrt.',
        'Tala rutschte an den Rand.',
        'Der Karren kam aus einer Seitengasse. Zwei Männer gingen daneben, beide mit einem Tuch um den Kopf. Auf dem Karren lag Stroh, und unter dem Stroh stand etwas Rundes.',
        'Am Tor hielt der Karren an.',
        'Aus dem Wachhäuschen kam ein Mann mit einer Lampe. Er ging nicht zum Karren. Er ging zu den Männern, sprach kurz mit ihnen und schrieb etwas auf ein Täfelchen.',
        'Dann hob er den Schlagbaum.',
        'Der Karren fuhr in die Nacht hinaus.',
        'Tala ließ den Atem los. Sie hatte nicht gemerkt, dass sie ihn anhielt.',
        '„Er hat nicht nachgesehen“, sagte sie. „Er hat nicht unter das Stroh gesehen.“',
        '„Nein.“',
        '„Das ist—“',
        '„Das ist immer noch nichts“, sagte Yidir. „Das ist ein Mann, der nicht gut genug hinsieht. Dafür hängt niemand.“',
        'Er hatte recht, und das wusste Tala auch.',
        'Aber als der Karren um die Kurve bog, geschah etwas. Der Esel erschrak vor etwas im Dunkeln, zog zur Seite, und der Karren fuhr mit einem Rad über die Bordkante.',
        'Etwas fiel vom Karren.',
        'Es rollte, kam an der Mauer zum Stehen und blieb dort liegen.',
        'Ein Krug.',
        'Einer der Männer fluchte, kam zurück, hob ihn auf und stellte ihn wieder unter das Stroh. Der Karren fuhr weiter.',
        'Aber Tala hatte gesehen, was darauf stand.',
        'Auf die Schulter jedes Krugs aus ihrem Haus setzte ihr Vater ein Zeichen in den Ton, bevor er gebrannt wurde. Acht Zacken. Ein Stern.',
        'Sie packte Yidirs Arm so fest, dass er zischte.',
        '„Der ist von uns“, sagte sie.',
      ] },
      { titel: 'Was du sagst und was sie hören', tekst: [
        'Am nächsten Morgen ging Tala zum Platz.',
        'Sie hatte die ganze Nacht darüber nachgedacht, jedenfalls über die halbe; die andere Hälfte hatte sie geschlafen, ohne es zu wollen. Sie wusste, was sie sagen würde. Sie hatte es dreimal gegen die Wand ihres Zimmers geübt.',
        'Auf dem Platz, unter den Säulen, tagte der Rat. Das hieß: fünf Männer auf Steinbänken, ein Schreiber daneben, und alle, die etwas zu klagen hatten, ringsherum.',
        'Marcus stand schon da.',
        'Tala wartete, bis ein Mann über eine Mauer und einen Nachbarn zu Ende geredet hatte. Dann trat sie vor.',
        '„Ich möchte etwas sagen“, sagte sie.',
        'Fünf Männer sahen auf. Einer von ihnen, der Älteste, mit einem Gesicht wie eine getrocknete Feige, beugte sich vor.',
        '„Wessen Kind bist du?“',
        '„Von Yuba, dem Ölmüller. Aus der Säulenstraße.“',
        '„Der ist krank.“',
        '„Ja“, sagte Tala. „Darum stehe ich hier.“',
        'Sie erzählte es. Von dem Krug, der fehlte, und am Tag darauf noch einem. Von dem Karren in der Nacht und dem Mann, der den Schlagbaum hob, ohne unter das Stroh zu sehen. Von dem Krug, der herunterfiel, und von dem Zeichen mit den acht Zacken.',
        'Sie erzählte es genau so, wie sie es geübt hatte, und während sie es tat, hörte sie es selbst auch.',
        'Sie hörte, wie es klang.',
        'Ein Kind. Ein Dach. Das Dunkel. Ein Zeichen, das niemand sonst gesehen hatte.',
        'Als sie fertig war, war es kurz still. Dann sagte Marcus, ganz ruhig: „Darf ich?“',
        'Der Älteste nickte.',
        '„Das Mädchen hat recht, dass Krüge fehlen“, sagte Marcus. „Das habe ich selbst gezählt, vorgestern, in ihrem eigenen Lager. Neunundneunzig von hundert. Ich habe es damals auch gesagt.“',
        'Er breitete die Hände aus, wie er das tat.',
        '„Wer hat den Schlüssel zu dieser Tür?“',
        'Niemand sagte etwas.',
        '„Sie“, sagte Marcus. „Ein Kind von elf Jahren. Und jetzt, wo einer fehlt, ist es ein Karren in der Nacht gewesen. Ein Karren, den nur sie gesehen hat.“',
        'Der Älteste des Rates sah Tala an, und sein Blick war nicht unfreundlich. Das war das Schlimmste daran.',
        '„Kind“, sagte er. „Geh nach Hause. Kümmere dich um deinen Vater.“',
        'Tala stand auf dem Platz, die Hände am Körper und die Ohren glühend, und um sie herum fing jeder wieder an, über eine Mauer und einen Nachbarn zu reden.',
      ] },
      { titel: 'Das Feuer', tekst: [
        'Das Feuer begann vier Tage später, und es begann nicht bei ihnen.',
        'Tala wachte davon auf. Nicht von Licht und nicht von Geschrei — von einem Geräusch. Einem tiefen, leisen Brüllen, als atmete irgendwo ganz in der Nähe jemand sehr lange aus.',
        'Sie war am Fenster, bevor sie wach war.',
        'Gegenüber auf der anderen Straßenseite, zwei Häuser weiter, brannte das Lager von Quintus. Quintus presste auch Öl. Seine Krüge standen in einem Raum unter seinem Haus, und daraus kam jetzt Feuer zum Fenster heraus, flach, und nicht nach oben, wie Feuer es tun sollte.',
        'Das kommt vom Öl, wusste Tala später. Öl brennt anders.',
        'Es wurde schon geschrien. Es waren schon Leute auf der Straße mit Eimern und Decken, und jemand schlug mit einem Stock gegen die bronzene Platte am Brunnen, und Tala rannte ohne Schuhe die Treppe hinunter.',
        'Ihre Mutter packte sie in der Tür am Arm.',
        '„Nicht dahin.“',
        '„Aber—“',
        '„Tala.“ Ihre Mutter hielt sie mit beiden Händen fest. „Unsere Tür. Sofort.“',
        'Und Tala begriff.',
        'Wenn es überspringt, dann zu ihnen. Hundert Krüge — neunundneunzig — mit Öl, hinter einer Holztür, an derselben Mauer.',
        'Sie rannte zum Lager, zog die Schnur über den Kopf und steckte den Schlüssel ins Schloss. Ihre Hände waren so nass, dass die Bronze wegdrehte. Beim dritten Mal gelang es.',
        'Die Tür ging auf. Die Kühle kam ihr entgegen, und der Geruch.',
        'Hinter ihr fing die ganze Straße an, Krüge zu tragen.',
        'Sie trugen sie in den Innenhof, zum Brunnen, auf die Straße, überallhin, wo keine Mauer brannte. Die Nachbarn trugen mit, Menschen, die sie kaum kannte, Menschen, mit denen ihr Vater nie gesprochen hatte. Jemand hatte eine Leiter. Jemand warf Decken ins Wasser des Brunnens und reichte sie weiter.',
        'Tala trug, bis ihre Arme nicht mehr wollten, und dann trug sie weiter.',
        'Beim siebzigsten Krug sah sie Yidir. Er kam mit vier anderen aus der Schmiede und sie schleppten etwas, das aussah wie ein langer Haken.',
        'Beim fünfundachtzigsten stürzte das Dach von Quintus’ Lager ein.',
        'Beim letzten ging die Sonne schon fast auf.',
        'Da war kein Feuer mehr. Da war nur Rauch, der tief über der Straße hing, und zweihundert Menschen, die zusahen, ohne etwas zu sagen, und schwarze Hände, und irgendwo ein Kind, das weinte.',
        'Tala saß auf der Stufe an ihre Mutter gelehnt.',
        'Und deshalb sah sie als Einzige den Mann, der aus der Gasse neben Quintus’ Haus kam, gegen den Strom, den Mantel über dem Arm statt um die Schultern.',
        'Der Mantel war rot.',
      ] },
      { titel: 'Der rote Mantel', tekst: [
        'Sie erzählte es Yidir, bevor sie es irgendwem sonst erzählte.',
        'Er hörte es sich an, ohne sie zu unterbrechen, und als sie fertig war, sagte er: „Das ist immer noch nichts.“',
        '„Ich habe ihn gesehen.“',
        '„Du hast einen Mann mit einem roten Mantel gesehen, in einer Straße voller Leute mit Ruß im Gesicht.“ Yidir trat gegen einen Stein. „Ich glaube dir. Der Rat nicht.“',
        'Tala wusste, dass er recht hatte, und sie hatte genug davon, dass er immer recht hatte.',
        '„Was denn?“, sagte sie. „Ich kann doch nicht nichts tun.“',
        '„Nein“, sagte Yidir. „Aber du brauchst etwas, das nicht von dir kommt.“',
        'Er setzte sich auf den Brunnenrand, die Fersen gegen den Stein.',
        '„Am Tor schreiben sie alles auf“, sagte er. „Auf Wachs. Was hinausgeht, wie viel, und von wem. Diese Täfelchen gehen jeden Monat zum Rathaus.“',
        '„Und wenn nichts Seltsames draufsteht?“',
        '„Dann steht nichts Seltsames drauf“, sagte Yidir. „Und dann weißt du, dass es nicht in den Büchern steckt, sondern im Dunkeln. Das ist auch etwas.“',
        'Er sah sie an.',
        '„Aber wenn doch etwas draufsteht — wenn da zwölf Krüge stehen, während dreizehn durch das Tor gingen — dann ist das kein Kind, das etwas gesehen hat. Dann ist das eine Zahl neben einer Zahl, und Zahlen redet niemand weg.“',
        'Tala dachte an die Nacht auf dem Dach. An den Mann, der nicht unter das Stroh gesehen hatte.',
        '„Wer kann diese Täfelchen einsehen?“',
        '„Wir nicht.“',
        '„Wer dann?“',
        'Yidir schwieg kurz.',
        '„Mein Meister“, sagte er. „Er liefert das Eisen für die Schlösser des Rathauses. Er kommt da hinein, ohne dass jemand fragt, warum.“',
        '„Dann frag ihn.“',
        '„Er ist keiner, der sich mit dem Aufseher anlegt.“',
        '„Frag ihn“, sagte Tala noch einmal.',
        'Yidir sah auf seine schwarzen Hände.',
        '„Gut“, sagte er. „Aber nicht heute Abend. Heute Abend ist Markt-Freitag und da ist er schlecht gelaunt.“',
        'Trotz allem musste Tala lachen.',
        'Es war das erste Mal seit Tagen.',
      ] },
      { titel: 'Was auf dem Wachs stand', tekst: [
        'Der Schmied hieß Amanar und er war der größte Mann, den Tala je aus der Nähe gesehen hatte.',
        'Er sagte zwei Tage lang nichts. Dann kam er am dritten Morgen in die Säulenstraße, ein Päckchen unter dem Arm, und setzte sich auf die Stufe des Lagers, als gehörte sich das so.',
        '„Du bist die Tochter von Yuba“, sagte er.',
        '„Ja.“',
        '„Dein Vater hat meiner Mutter einmal einen Winter lang Öl gegeben, ohne dafür bezahlen zu lassen.“ Amanar sah die Straße hinunter. „Das ist sechzehn Jahre her. Ich habe es nicht vergessen und er weiß nicht mehr, dass er es getan hat.“',
        'Er legte das Päckchen auf die Stufe.',
        'Es waren zwei Wachstäfelchen in einem Holzrahmen, Kratzer über Kratzer über Kratzer.',
        '„Ansehen ja“, sagte Amanar. „Mitnehmen nein. Sie liegen in einer Stunde wieder, wo sie hingehören.“',
        'Tala setzte sich und las.',
        'Sie konnte lesen. Nicht flüssig, aber genug. Ihr Vater hatte darauf bestanden: „Wer nicht lesen kann, glaubt, was ein anderer sagt, dass da steht.“',
        'Auf dem Wachs standen Reihen. Datum, Tor, was, wie viel, wessen.',
        'Sie suchte ihren eigenen Namen. Sie fand ihn elfmal.',
        '*Yuba, Ölmüller, Säulenstraße. Acht Krüge.*',
        '*Yuba, Ölmüller. Zwölf Krüge.*',
        '*Yuba, Ölmüller. Neun Krüge.*',
        'Tala zählte zusammen. Sie zählte zweimal und beim zweiten Mal schrieb sie es in den Sand neben ihren Füßen.',
        'Hundertsiebzehn Krüge. In vier Wochen, zum Tor hinaus, auf den Namen ihres Vaters.',
        'Sie sah auf.',
        '„Das stimmt nicht“, sagte sie.',
        '„Nein?“, sagte Amanar.',
        '„Wir haben in dieser Saison hundertsechzig gemacht. Ich weiß es genau, ich habe sie gezählt, als sie gebrannt wurden. Sechzig sind in der Stadt verkauft worden. Hundert standen im Lager.“ Sie zeigte auf den Sand. „Hundertsechzig. Nicht hundertsiebenundsiebzig.“',
        'Amanar sagte nichts.',
        '„Es sind siebzehn Krüge durch das Tor gegangen, die wir nie gemacht haben“, sagte Tala. „Auf unseren Namen.“',
        'Sie hörte selbst, was das bedeutete, während sie es sagte.',
        'Es waren nicht nur ihre Krüge, die gestohlen wurden.',
        'Es war ihr Name.',
        'Wenn später im Rathaus gezählt wurde und weniger ankam, als durch das Tor hinausgegangen war, dann gäbe es ein Haus, in dem die Spur endete. Und dieses Haus war ihres.',
        '„Amanar“, sagte sie, und ihre Stimme klang seltsam. „Sie stellen uns hin.“',
        'Der Schmied stand auf und klopfte sich den Staub von den Knien.',
        '„Ja“, sagte er. „Das tun sie.“',
        'Er nahm die Täfelchen auf.',
        '„Komm morgen mit deiner Mutter zum Platz. Und bring den Sand mit, oder nein — schreib es auf etwas ab, das nicht wegweht.“',
      ] },
      { titel: 'Zwei Zahlen nebeneinander', tekst: [
        'Der Rat tagte wie immer: fünf Männer, ein Schreiber, und das Gemurmel von Leuten, die warteten, bis es um sie ging.',
        'Diesmal stand Tala nicht allein da.',
        'Links von ihr stand ihre Mutter, in dem Kleid, das sie nur trug, wenn etwas Schlimmes oder etwas Schönes war. Rechts von ihr stand Amanar, und hinter Amanar standen vier Männer aus der Schmiede, die damit nichts zu tun hatten und trotzdem da waren.',
        'Weiter hinten, an einer Säule, stand Yidir.',
        'Der Älteste des Rates — der mit dem Gesicht wie eine getrocknete Feige — sah die Gruppe an und zog die Augenbrauen hoch.',
        '„Du schon wieder“, sagte er zu Tala.',
        '„Ich habe gezählt“, sagte Tala.',
        'Sie hatte es auf ein Stück Leder geschrieben, denn Leder weht nicht weg. Sie las es vor. Was sie gemacht hatten. Was in der Stadt verkauft worden war. Was im Lager stand. Und danach, was den Täfelchen am Tor zufolge auf den Namen ihres Vaters aus der Stadt gegangen war.',
        'Zwei Zahlen.',
        'Als sie fertig war, war es still auf eine andere Art als beim letzten Mal.',
        'Marcus trat vor. Er war immer noch ruhig, aber nicht mehr auf dieselbe Weise.',
        '„Ein Kind hat in die Stadttäfelchen gesehen“, sagte er. „Das ist verboten.“',
        '„Ich habe sie gebracht“, sagte Amanar.',
        'Es wurde noch stiller.',
        'Der Älteste des Rates wandte sich an den Schreiber neben sich.',
        '„Hol sie.“',
        'Es dauerte lange. Niemand ging weg. Jemand gab Talas Mutter einen Hocker und sie setzte sich nicht darauf.',
        'Als die Täfelchen da waren, las der Schreiber laut vor, was darauf stand, und ein anderer Mann zählte mit Steinen auf einem Brett zusammen, und alle auf dem Platz hörten es.',
        'Hundertsiebzehn.',
        'Der Älteste sah lange auf die Zahlen, und danach auf Marcus, und danach wieder auf die Zahlen.',
        '„Wer schreibt am Nordtor?“, fragte er.',
        '„Das wechselt“, sagte Marcus.',
        '„Wer bestimmt, wer schreibt?“',
        'Marcus antwortete nicht.',
        'Der Älteste seufzte, und es war der Seufzer eines Mannes, der etwas begreift, das er lieber nicht begriffen hätte, und der weiß, dass er jetzt etwas damit tun muss.',
        '„Setz dich“, sagte er zu Tala. „Du nicht, Marcus. Du bleibst stehen.“',
      ] },
      { titel: 'Was übrig bleibt', tekst: [
        'Es dauerte noch drei Wochen, bis sich wirklich etwas änderte, und das war die längste Lehre jenes Sommers: dass die Wahrheit nicht so funktioniert wie in einer Geschichte, wo man sie sagt und alle nicken.',
        'Es kam ein Mann aus der Mutterstadt von Volubilis, um die Bücher zu prüfen. Es wurden Leute angehört. Zweimal wurde nichts gesagt und einmal etwas, das niemand erwartet hatte: der Wächter des Nordtors, ein Junge von neunzehn Jahren, brach bei der dritten Frage zusammen und erzählte alles.',
        'Marcus verschwand, bevor es abgeschlossen war. Sein Haus stand einen Monat leer und wurde dann jemand anderem gegeben.',
        'Talas Vater wurde nicht mehr gesund, nicht ganz. Er konnte im Herbst wieder im Innenhof sitzen und die Presse knarren hören, und damit schien er zufrieden. Er fragte nach den Zahlen und sie nannte sie ihm. Er ließ sie dreimal erzählen, was auf dem Platz geschehen war, und beim dritten Mal weinte er, und das hatte sie ihn noch nie tun sehen.',
        'Die Ernte ging zum Hafen. Hundert Krüge. Es stimmte.',
        'In der Woche darauf kam Yidir mit seiner Großmutter vorbei.',
        'Seine Großmutter war klein und alt und hatte Augen wie jemand, der viel weiter sieht als bis dahin, wo sie steht. Sie sagte, sie gehe fort: zurück zu ihrer Familie, auf die Weiden in den Bergen, bevor es Winter würde. Sie sagte es, als spräche sie von einem Spaziergang.',
        '„Yidir kommt mit“, sagte sie. „Eine Weile.“',
        'Tala sah Yidir an. Yidir sah auf seine Hände.',
        '„Wie lang ist eine Weile?“, fragte sie.',
        '„Das weißt du erst hinterher“, sagte seine Großmutter.',
        'An diesem Abend zog Tala die Schnur über den Kopf.',
        'Der Schlüssel war warm, wie immer. Acht Zacken im Kopf, ein Stern. Ihr Großvater hatte ihn in einer Schmiede geschmiedet, die es jetzt nicht mehr gab.',
        'Sie hielt ihn in der Hand und dachte an das, was ihr Vater gesagt hatte. *Diese Tür geht für nichts anderes auf.*',
        'Sie gab ihn Yidir.',
        '„Das geht nicht“, sagte er sofort.',
        '„Du hast mir geglaubt, als mir niemand geglaubt hat.“',
        '„Das ist keinen Schlüssel wert.“',
        '„Es ist mein Schlüssel“, sagte Tala. „Ich bestimme, was er wert ist.“',
        'Yidir hielt ihn fest, als wäre er zu heiß.',
        '„Was soll ich damit?“',
        '„Weiß ich nicht“, sagte Tala. „Weggeben, denke ich. An jemanden, dem du glaubst.“',
        'Sie gingen am nächsten Morgen fort, mit drei Eseln und einem Hund, in die Hügel, und Tala stieg auf das Dach des Badehauses und sah ihnen nach, bis sie nicht mehr zu sehen waren.',
        'Sie wusste damals noch nicht, dass es gut war, dass der Schlüssel fortging.',
        'Denn Walili würde nicht immer da sein. Das Erdbeben kam viel später, und die Stadt wurde langsam abgetragen — Stein für Stein, bis nichts übrig blieb als die Säulen, die Ölpressen und die Mosaikböden, die heute noch da liegen, unter freiem Himmel, bei Meknès.',
        'Alles, was in den Häusern stand, ist verschwunden.',
        'Nur der Schlüssel nicht.',
      ] },
    ],
  },
  2: {
    titel: 'Die andere Seite',
    jaar: '711',
    waar: 'Tanger und die Meerenge nach Norden',
    verteller: 'Ayyur, zwölf Jahre, Sohn eines Schafhirten, der die Pferde versorgt',
    flap: 'Ein Heer setzt über in ein Land, das niemand kennt. Ayyur darf mit, um die Pferde zu versorgen — und entdeckt, dass der Mann, dem alle folgen, selbst auch Angst hat.',
    sleutel: 'Der Schlüssel hängt am Zaumzeug eines Pferdes und bleibt drüben zurück, in der Tasche eines Schreibers.',
    echt: [
      'Tariq ibn Ziyad war ein amazighischer Heerführer, der 711 mit einem Heer die Meerenge in den Süden des heutigen Spanien überquerte.',
      'Der Felsen, an dem er landete, trägt noch seinen Namen: Jabal Tariq, der Berg des Tariq — verschliffen zu Gibraltar.',
      'Der größte Teil seines Heeres bestand aus amazighischen Soldaten aus Nordafrika.',
      'Die Geschichte, er habe seine Schiffe verbrennen lassen, ist erst Jahrhunderte später aufgeschrieben worden und gilt Historikern nicht als Tatsache.',
    ],
    verzonnen: [
      'Ayyur und seine Familie haben nicht existiert.',
      'Die Gespräche mit Tariq sind erfunden. Über seinen Charakter ist fast nichts bekannt.',
      'Dass der Schlüssel mitreiste, ist erfunden.',
    ],
    hoofdstukken: [
      { titel: 'Der Junge bei den Pferden', tekst: [
        'Ayyur war zwölf und er war gut in zwei Dingen: Pferden und Warten.',
        'Das Zweite hatte er von seinem Vater gelernt, der in den Hügeln hinter Tanger Schafe hütete und der von Sonnenaufgang bis Sonnenuntergang schweigen konnte, ohne dass es ihm etwas ausmachte. Das Erste hatte er von niemandem. Pferde mochten ihn einfach, und das war so, seit er laufen konnte.',
        'Darum stand er jetzt im Lager vor der Stadtmauer und nicht in den Hügeln.',
        'Sein Vater hatte im Winter dreißig Schafe an die Kälte verloren und den Rest an die Schulden. Es gab keine Herde mehr zu hüten. Es gab aber ein Heer, und ein Heer hat Pferde, und Pferde brauchen jemanden, der nachts bei ihnen bleibt.',
        'Sie bezahlten in Essen und in Kupfer. Nicht viel Kupfer.',
        'Ayyur beklagte sich nicht. Er durfte bei den Pferden schlafen und kannte inzwischen alle siebenundvierzig beim Namen, auch die Namen, die er selbst erfunden hatte, weil sie ihm niemand gesagt hatte.',
        'Das Lager war in diesen Märzwochen voller geworden, als er es je gesehen hatte. Erst hundert Mann, dann fünfhundert, dann so viele, dass Zählen nicht mehr ging. Sie kamen aus dem Süden und aus dem Osten, aus den Bergen und von der Küste. Die meisten waren Amazigh wie er. Sie sprachen seine Sprache, mit anderen Wörtern für dieselben Dinge, und sie lachten darüber, wie er es sagte.',
        'Es gab auch welche, die Arabisch sprachen. Nicht viele. Ein paar hundert.',
        'Und alle warteten.',
        'Worauf, das wussten sie schon: auf Schiffe. Wofür die Schiffe da waren, darüber wurde geredet, wie Männer über etwas reden, das sie nicht sicher wissen — sehr bestimmt, und jeden Tag anders.',
        '„Die andere Seite“, sagte der eine.',
        '„Auf der anderen Seite ist nichts“, sagte der andere. „Wasser und dann noch mehr Wasser.“',
        '„Auf der anderen Seite ist ein König“, sagte ein dritter. „Mit einer Krone aus Gold, so schwer, dass er sie nicht tragen kann.“',
        'Ayyur bürstete die Flanke einer Stute, die er Tafukt nannte, was Sonne bedeutet, und hörte allen dreien zu.',
        'Er hatte die andere Seite gesehen. Jeder in Tanger hatte die andere Seite gesehen. An einem klaren Tag lag da ein Streifen Land am Horizont, und darüber ein Felsen, der aussah, als hätte ihn jemand dorthin gestellt.',
        'Man konnte ein ganzes Leben lang hinsehen, ohne je darüber nachzudenken.',
        'Bis jemand anfing, Schiffe zu sammeln.',
      ] },
      { titel: 'Der Mann, der nicht groß war', tekst: [
        'Er sah Tariq zum ersten Mal an einem Dienstag, bei den Pferden, und eine halbe Minute lang wusste er nicht, wen er vor sich hatte.',
        'Der Mann war nicht groß. Das war das Erste.',
        'Ayyur hatte sich jemanden vorgestellt wie in den Geschichten: einen Kopf größer als alle, ein Mantel, der hinter ihm herschleifte, zehn Mann drumherum. Dieser Mann stand allein da, in einer staubigen Jacke ohne Verzierung, und er sah Tafukt an, wie jemand ein Pferd ansieht, der etwas von Pferden versteht.',
        '„Wer reitet die?“, fragte er.',
        '„Niemand“, sagte Ayyur. „Sie lässt niemanden auf sich sitzen.“',
        '„Warum nicht?“',
        '„Weiß ich nicht. Sie ist einmal gestürzt, glaube ich. Bevor sie hierherkam.“',
        'Der Mann legte die Hand an den Hals der Stute und ließ sie dort liegen, ohne zu streicheln.',
        '„Und bei dir?“',
        '„Bei mir ist sie ruhig.“',
        '„Dann hat sie keine Angst vor Menschen“, sagte der Mann. „Dann hat sie Angst vor dem, was Menschen mit ihr getan haben.“',
        'Er sah Ayyur zum ersten Mal an.',
        '„Wie heißt du?“',
        '„Ayyur.“',
        '„Der Mond.“ Der Mann nickte, als wäre das ein vernünftiger Name. „Sorg dafür, dass sie in zwei Wochen noch so dasteht.“',
        'Dann ging er weg.',
        'Es dauerte bis zum Abend, bis es Ayyur jemand sagte, und als er es hörte, setzte er sich auf eine Kiste und blieb eine Weile sitzen.',
        'Tariq ibn Ziyad. Amazigh, wie er. Aus einer Familie, die niemand kannte. Statthalter von Tanger, und der Mann, der das Heer, das hier am Strand lag, über das Wasser bringen sollte.',
        'Er hatte ein Pferd angesehen.',
        '„Er kommt jeden Tag“, sagte Sa3id, der alte Reiter mit dem schlechten Bein, der sich inzwischen neben ihn gesetzt hatte, weil er sich immer neben jemanden setzte. „Jeden Tag zu den Pferden und jeden Tag zu den Schiffen. Er schläft nicht, glaube ich.“',
        '„Er ist nicht groß“, sagte Ayyur.',
        'Sa3id lachte so laut, dass er husten musste.',
        '„Nein, Junge“, sagte er. „Das ist er nicht.“',
      ] },
      { titel: 'Vier Schiffe für siebentausend Mann', tekst: [
        'Das Problem war einfach und niemand konnte es lösen.',
        'Da lagen siebentausend Mann an diesem Strand, dazu Pferde, dazu Waffen, dazu Essen für Wochen. Und es gab vier Schiffe.',
        'Ayyur hörte Sa3id einmal ausrechnen, wie oft diese vier Schiffe dann hin und her müssten, und Sa3id kam auf eine Zahl, über die er selbst lachen musste, und danach wurde er still.',
        '„Was ist?“, fragte Ayyur.',
        '„Nichts.“',
        '„Sa3id.“',
        'Der alte Mann rieb sich das Knie, was er tat, wenn er nachdachte.',
        '„Wenn du vier Schiffe hast“, sagte er, „dann ist die erste Ladung die gefährlichste. Die steht drüben, allein, mit niemandem hinter sich. Und wenn etwas schiefgeht, sind die Schiffe zwei Tage weg.“',
        'Er sah aufs Meer.',
        '„Ich wollte nicht in der ersten Ladung sein.“',
        'Die Schiffe gehörten ihnen nicht. Das wusste das ganze Lager. Sie kamen von einem Mann von drüben, einem Herrn aus Ceuta, der Streit mit seinem eigenen König hatte und deshalb half. Sein Name wurde auf zehn Arten ausgesprochen und niemand hatte ihn je gesehen.',
        '„Warum hilft er?“, fragte Ayyur.',
        '„Weil er etwas will.“',
        '„Was denn?“',
        '„Das wissen wir erst, wenn wir es gegeben haben“, sagte Sa3id.',
        'In diesen Wochen lernte Ayyur mehr über Krieg, als er je hatte wissen wollen, und fast nichts davon handelte vom Kämpfen. Es handelte von Wasser in Fässern, das nach vier Tagen verdarb. Davon, wie viel Gerste ein Pferd am Tag frisst und wie viel das für siebenhundert Pferde ist. Von Männern, die krank wurden vom Warten und sich um nichts stritten.',
        'An einem Morgen gab es eine Schlägerei am Brunnen. Zwei Männer aus verschiedenen Stämmen, um einen Eimer.',
        'Tariq kam selbst. Er ließ sie beide aufstehen, er sprach leise mit ihnen, und er schickte sie zusammen weg mit demselben Auftrag: ein Eimer, zwei Mann, den ganzen Tag Wasser für die Pferde tragen.',
        'Am Abend saßen sie nebeneinander und aßen.',
        'Sa3id sah Ayyur zusehen.',
        '„Das ist es“, sagte er. „Das ist der Grund, warum sie mit ihm gehen. Nicht weil er kämpfen kann. Kämpfen können sie alle.“',
      ] },
      { titel: 'Die Nacht davor', tekst: [
        'Der Abend vor der ersten Überfahrt war warm und es ging kein Wind, und genau das Letzte war das Problem.',
        'Ayyur konnte nicht schlafen. Er lag zwischen den Pferden, den Kopf auf einem Sattel, der nach Leder und Schweiß roch, und sah zu den Sternen, die zwischen den Zeltbahnen zu sehen waren.',
        'Neben ihm lag Sa3id, und der schlief auch nicht.',
        '„Hast du Angst?“, fragte Ayyur.',
        '„Ja“, sagte Sa3id sofort.',
        'Das hatte Ayyur nicht erwartet. Er hatte erwartet, dass der alte Mann lachen und etwas darüber sagen würde, dass er schon in zwanzig Schlachten gestanden habe.',
        '„Jeder, der Nein sagt, lügt“, sagte Sa3id. „Oder er ist dumm. Mit dummen Männern ist einem in einem Boot nicht geholfen.“',
        'Er setzte sich auf, langsam, die Hand am Knie.',
        '„Weißt du, was ich mache, wenn ich Angst habe?“',
        '„Nein.“',
        '„Ich sage den Namen Gottes und dann tue ich das nächste Ding, das getan werden muss. Nicht das ganze Ding. Das nächste Ding.“',
        'Ayyur dachte darüber nach.',
        'Der Glaube war in seinem Dorf etwas aus den letzten Jahren. Seine Großmutter hatte ihn nicht, seine Mutter halb, sein Vater ganz — auf seine eigene Art, still, ohne viel darüber zu sagen. Im Lager war er überall: Männer, die aufhörten mit dem, was sie taten, und sich in dieselbe Richtung drehten, und danach weitermachten, als wäre nichts gewesen.',
        'Er hatte es nie richtig verstanden. Es hatte es ihm niemand erklärt. Sie taten es einfach, und er stand mit einer Bürste in der Hand daneben.',
        '„Sa3id“, sagte er. „Ich weiß nicht, wie es geht.“',
        'Der alte Mann sah ihn im Dunkeln an.',
        '„Was weißt du nicht?“',
        '„Alles. Die Worte. Wann. Wie man steht.“',
        'Sa3id schwieg lange genug, um Ayyur unbehaglich zu machen.',
        '„Morgen früh“, sagte er dann, „stellst du dich neben mich. Du machst, was ich mache. Du musst nichts sagen, was du nicht weißt.“',
        '„Reicht das?“',
        '„Für morgen früh schon“, sagte Sa3id. „Den Rest lernst du von jemandem, der mehr davon versteht als ich. Ich bin nur ein Reiter mit einem kaputten Knie.“',
        'Er legte sich wieder hin.',
        '„Schlaf jetzt. Morgen wird lang.“',
      ] },
      { titel: 'Der Strand bei Sonnenaufgang', tekst: [
        'Sie gingen im Dunkeln zum Wasser, und als es hell wurde, stand der ganze Strand voll.',
        'Ayyur hatte noch nie so viele Menschen gleichzeitig still gesehen.',
        'Sie standen in Reihen, Schulter an Schulter, von den Dünen bis zur Flutlinie. Männer, die einander nicht verstanden, weil sie aus Dörfern kamen, die zehn Tagesreisen auseinanderlagen, in dieselbe Richtung, in derselben Ordnung.',
        'Er stand neben Sa3id und tat, was Sa3id tat, und er kam sich die ersten drei Atemzüge lächerlich vor und danach nicht mehr.',
        'Das Meer lag an diesem Morgen da wie ein See.',
        'Als es vorbei war, blieb es noch kurz still. Danach fingen alle gleichzeitig an zu reden und es wurde wieder ein Lager.',
        'Ayyur brachte acht Pferde zur Flutlinie. Das war sein Auftrag: acht, in der ersten Ladung, mit Sa3id dabei, wenn sie drüben wären.',
        'Tafukt war eines davon.',
        'Pferde und Boote passen nicht zusammen. Das wusste er, und an diesem Morgen lernte er, wie schlimm es ist. Sie mussten die Tiere über eine Planke ins Boot bekommen, und die Planke bewegte sich, und das Boot bewegte sich anders als die Planke.',
        'Zwei Pferde weigerten sich. Ein drittes geriet auf halbem Weg in Panik und schlug einen Mann zu Boden.',
        'Tafukt ging hinter Ayyur die Planke hinauf, als wäre es ein Pfad in den Hügeln.',
        'Er hielt ihren Kopf fest, als sie erst einmal drin war, und redete in seiner eigenen Sprache auf sie ein, über Dinge, die um nichts gingen: über seinen Vater, über die Herde, die es nicht mehr gab, über den Namen, den er ihr gegeben hatte, und warum.',
        'Jemand schlug ihm auf die Schulter.',
        'Er sah auf.',
        'Tariq stand im Boot, zwischen den Pferden, die Hand am Rand.',
        '„Rede weiter mit ihr“, sagte er. „Die ganze Überfahrt. Hör nicht auf.“',
        '„Ja“, sagte Ayyur.',
        'Tariq sah zur Planke, wo das vierte und fünfte noch mussten.',
        '„Und Ayyur“, sagte er, ohne sich umzudrehen. „Wenn es auf dem Wasser schiefgeht, schneidest du sie los. Nicht festhalten. Ein Pferd kann schwimmen. Ein Junge mit einem Seil um den Arm nicht.“',
      ] },
      { titel: 'Wasser', tekst: [
        'Die Meerenge ist an ihrer schmalsten Stelle vierzehn Kilometer breit.',
        'Ayyur wusste das nicht. Er wusste nur, dass der Strand hinter ihm kleiner wurde und dass eine Stunde verging, in der nichts geschah, und danach noch eine.',
        'Es ging nicht schief. Das war das Seltsame.',
        'Er hatte sich alles vorgestellt: Wellen, Geschrei, Wasser über dem Rand. Stattdessen waren da die Sonne, das Geräusch der Riemen, und eine Dünung, die gerade genug war, um jeden, der Boote nicht gewohnt war, über die Reling hängen zu lassen.',
        'Er redete mit Tafukt, bis seine Stimme heiser wurde.',
        'Zwischendurch sah er zurück.',
        'Hinter ihnen lag die Küste, an der er geboren war: die Hügel, wo die Schafe gelaufen waren, die Stadt mit der Mauer, die Stelle, wo sein Vater jetzt wahrscheinlich saß und schaute, ohne etwas zu sagen.',
        'Er hatte sich nicht verabschiedet. Nicht richtig. Er hatte gesagt, er sei in einem Monat zurück, und sein Vater hatte genickt, und sie hatten beide so getan, als wäre das ein Satz, der etwas bedeutet.',
        'Vor ihnen wurde der Felsen größer.',
        'Er war anders, als er von Tanger aus aussah. Von weitem schien es ein Dreieck. Von nahem war es eine Wand aus Stein, die gerade aus dem Wasser hochkam, grau und kahl, mit Möwen, die darum trieben wie Staub.',
        'Es saß niemand darauf. Es stand nichts darauf. Es war einfach ein Felsen.',
        'Neben ihm sagte Sa3id etwas.',
        '„Was?“',
        '„Ich sagte: sieh gut hin.“ Der alte Mann stützte die Arme auf den Rand. „In hundert Jahren fragt jemand deinen Enkel, wo seine Familie herkommt, und dann sagt er den Namen von diesem Ding.“',
        '„Es hat keinen Namen.“',
        'Sa3id grinste mit seinen schiefen Zähnen.',
        '„Noch nicht“, sagte er.',
        'Die Boote landeten an einem Strand am Fuß des Felsens. Da war niemand. Kein Heer, kein Wachposten, kein Dorf. Nur Kiesel, Tang und das Geräusch des Meeres.',
        'Siebenhundert Mann und zweiundsechzig Pferde standen an einer fremden Küste, und die Schiffe wendeten sofort für die nächste Ladung.',
        'Zwei Tage allein, hatte Sa3id gesagt.',
        'Ayyur brachte die Pferde höher, zum Gras hinter den Kieseln, und begann eine Linie in den Sand zu ziehen für die Umzäunung. Das nächste Ding, das getan werden musste.',
        'Hinter ihm stieg Tariq den ersten Hang hinauf, um zu sehen, wie das Land aussah.',
      ] },
      { titel: 'Zwei Tage allein', tekst: [
        'In der ersten Nacht auf der anderen Seite schlief niemand.',
        'Das lag nicht an der Angst, obwohl die auch da war. Es lag daran, dass siebenhundert Männer, die gerade von Bord gegangen sind, alle gleichzeitig finden, dass sie etwas tun müssen, und dass niemand da ist, der weiß, was.',
        'Es wurde eine Umzäunung gesetzt und wieder versetzt. Es wurde ein Feuer gemacht und wieder gelöscht, weil jemand sagte, ein Feuer sehe man von weitem. Es wurden Wachen aufgestellt an Stellen, wo es nichts zu bewachen gab.',
        'Ayyur tat, was er immer tat. Er brachte die Pferde ins Gras, zählte sie, zählte sie noch einmal, und legte sich zu ihnen.',
        'Zweiundsechzig. Es stimmte.',
        'Über ihm stand der Felsen wie eine Mauer, die jemand auf halber Höhe hatte stehen lassen.',
        'Gegen Morgen wurde es kalt, wie es am Meer kalt wird: nicht scharf, sondern überall gleichzeitig. Ayyur zog die Decke über sich und hörte den Pferden zu, die um ihn herum atmeten, und dachte an seinen Vater in den Hügeln hinter Tanger, sechs Stunden Fahrt und ein ganzes Leben entfernt.',
        'Dann fing jemand an zu rufen.',
        'Er fuhr hoch, denn Rufen bedeutet meistens, dass etwas kommt.',
        'Aber es kam nichts. Es war ein Mann, der sich am Rand des Lagers auf einen Stein gestellt hatte, das Gesicht nach Osten, und der rief, wie sie im Lager bei Tanger auch gerufen hatten, jeden Morgen, seit Ayyur dort arbeitete.',
        'Männer standen auf. Nicht alle. Genug, um es zu sehen.',
        'Sie stellten sich in Reihen auf die Kiesel, und sie verneigten sich, und sie standen wieder auf, und sie verneigten sich wieder, und es klang über dem Wasser, als atmete der Strand.',
        'Ayyur blieb bei den Pferden sitzen.',
        'Er hatte keine Angst davor. Er verstand es nur nicht, und niemand hatte sich die Mühe gemacht, es ihm zu erklären, denn niemand erklärt dem Jungen etwas, der bei den Pferden schläft.',
        'Was er aber sah, war dies: sie waren danach ruhiger. Die ganze Nacht waren sie wie Hühner durch das Lager gelaufen, und nach dieser einen Viertelstunde gingen sie wie Männer mit einer Aufgabe.',
        'Das war das Erste, was er vom neuen Glauben verstand. Nicht, was darin stand. Was er tat.',
        'Die Schiffe kamen an diesem Nachmittag für die zweite Ladung zurück, und die zwei Tage allein erwiesen sich als anderthalb.',
      ] },
      { titel: 'Der Hirte und die Ziege', tekst: [
        'Am vierten Tag kam jemand.',
        'Er kam von oben, vom Hang, mit einem Stock und mit elf Ziegen, und er ging ins Lager, als hätte es immer schon dort gestanden.',
        'Drei Männer hatten ihn gleichzeitig zu fassen.',
        'Ayyur sah es von der Umzäunung aus und dachte: er ist alt. Das war das Erste. Er war alt, und mager, und er hielt seinen Stock, wie man etwas hält, das man schon vierzig Jahre hält.',
        'Sie brachten ihn zum Zelt. Es kam ein Mann dazu, der Latein konnte, und der redete mit ihm, und der alte Mann antwortete in etwas, das kein Latein war.',
        'Dann kam jemand, der Berberisch sprach, aus derselben Gegend wie Ayyur, und der versuchte es, und der alte Mann sah ihn an, als lauschte er einem Vogel.',
        'Am Ende ging es mit den Händen.',
        'Die Ziegen gehörten ihm. Der Hang gehörte ihm, das heißt: er lief dort sein Leben lang mit Ziegen, was auf dasselbe hinausläuft. Er hatte die Schiffe gesehen. Er hatte niemanden gewarnt, denn wen sollte er warnen, und wovor.',
        'Das Letzte wurde dreimal gefragt und dreimal gleich beantwortet.',
        'Sie ließen ihn gehen.',
        'Sa3id fand das dumm und sagte es laut. „Er geht ins erste Dorf und dann wissen sie es.“',
        '„Sie wissen es schon“, sagte der Mann mit dem Latein. „Da lagen vier Schiffe im Wasser. Das sieht jeder von Tarifa bis Algeciras.“',
        'Der alte Mann ging mit seinen elf Ziegen den Hang wieder hinauf und sah sich nicht um.',
        'Ayyur sah ihm nach, bis er hinter der Kante verschwand.',
        'Er hatte sich die andere Seite anders vorgestellt. Als ein Land mit einem König und einer Krone und Mauern, oder als nichts, als Wasser und dann noch mehr Wasser. Nicht als einen alten Mann mit Ziegen, der denselben Stock hielt wie die Männer in den Hügeln hinter Tanger.',
        '„Was hast du denn gedacht“, sagte Sa3id, als er es sagte. „Dass hier Äffchen wären?“',
        'Ayyur sagte nichts, denn er hatte ehrlich gesagt nicht gewusst, was er dachte.',
        'An diesem Abend kam der alte Mann mit zwei Ziegen an einem Strick zurück, stellte sie beim Zelt ab und deutete etwas an, das niemand genau verstand und trotzdem jeder verstand.',
        'Sie bezahlten ihn in Kupfer. Nicht viel Kupfer.',
        'Er nahm es an, sah sich die Münzen an, steckte sie weg und ging den Hang wieder hinauf.',
        'So begann die Eroberung des Landes auf der anderen Seite: mit zwei Ziegen und einem ehrlichen Preis.',
      ] },
      { titel: 'Woran Sa3id glaubt', tekst: [
        'Sa3id hatte schiefe Zähne, eine Narbe durch die Augenbraue und zu allem eine Meinung.',
        'Er war aus Tlemcen, er war achtundzwanzig, und er war von Anfang an dabei. Er hatte Ayyur am ersten Tag bei den Pferden gefunden und war danach immer wiedergekommen, aus Gründen, die Ayyur nie ganz verstand. Vielleicht, weil der Junge zuhörte. Vielleicht, weil sonst niemand zuhörte.',
        'Am siebten Abend fragte Ayyur es endlich.',
        '„Warum ruft ihr morgens?“',
        'Sa3id sah von seinem Riemen auf, den er gerade einfettete.',
        '„Das ist der Ruf“, sagte er.',
        '„Das weiß ich. Warum?“',
        'Sa3id dachte darüber nach, was für ihn ungewöhnlich war.',
        '„Weil es Zeit ist“, sagte er dann. „Fünfmal am Tag ist es Zeit. Wenn es hell wird, wenn die Sonne am höchsten steht, wenn dein Schatten länger wird als du, wenn die Sonne weg ist, und wenn es dunkel ist.“',
        '„Und dann?“',
        '„Dann hörst du auf mit dem, was du tust, und stehst still.“',
        '„Wofür?“',
        '„Für Gott.“ Sa3id zuckte mit den Schultern. „Es gibt einen. Mehr sollst du von mir nicht verlangen, denn ich bin kein Gelehrter. Ich bin ein Mann mit einem Pferd und einem Speer.“',
        'Ayyur schwieg kurz.',
        '„Mein Vater sagt, dass in der Quelle bei uns im Dorf etwas wohnt“, sagte er. „Er stellt dort jedes Frühjahr Milch hin.“',
        'Er sagte es mit der Spannung von jemandem, der nicht weiß, ob er ausgelacht wird.',
        'Sa3id lachte nicht.',
        '„Dann sagt dein Vater das“, sagte er. „Ich sage, was ich sage. Dein Vater und ich haben beide keine Zeit, es herauszufinden, also tun wir unsere Arbeit.“',
        'Er machte mit dem Riemen weiter.',
        '„Wir haben es auch erst seit Kurzem“, sagte er danach. „Mein Großvater wusste nichts davon. Mein Vater hat damit angefangen und wusste die Hälfte davon. Ich weiß etwas mehr als er und weniger als der Mann, der morgens ruft. In hundert Jahren wissen sie alles darüber und denken, es sei immer so gewesen.“',
        'Er hielt den Riemen gegen das Licht.',
        '„So geht das mit allem“, sagte er.',
        'Ayyur dachte darüber noch lange nach, länger, als Sa3id es vermutlich gemeint hatte.',
        'Er hatte sich nicht dazugestellt, nicht an diesem Abend und nicht in den Wochen danach. Aber er hörte von da an auf, bei den Pferden sitzen zu bleiben, als geschähe nichts. Er stand auf, wenn es anfing. Das war alles, was er tat. Er stand auf, und er wartete, bis es vorbei war, und dann machte er weiter.',
        'Es schien ihm das Mindeste, was man tun konnte für etwas, wofür siebenhundert Mann still werden.',
      ] },
      { titel: 'Tafukt', tekst: [
        'In der zweiten Woche starb ein Pferd.',
        'Es war nicht Tafukt. Es war ein brauner Hengst ohne Namen, einer aus der letzten Ladung, der mit einem Bein in den Kieseln steckengeblieben war, als sie ihn vom Boot holten.',
        'Sie hatten es gehört. Jeder am Strand hatte es gehört.',
        'Sa3id tat es mit einem Messer und er tat es schnell, und er ließ Ayyur es nicht tun, obwohl Ayyur angeboten hatte, es zu tun, weil es sein Pferd war, für das er sorgte.',
        '„Nein“, hatte Sa3id gesagt. „Du bist zwölf.“',
        '„In zwei Monaten dreizehn.“',
        '„Dann tust du es in zwei Monaten.“',
        'Danach saß Ayyur den Rest des Nachmittags an der Umzäunung, ohne etwas zu tun, was ihm nie passierte.',
        'Es war nicht wegen des Hengstes. Er hatte Schafe sterben sehen, viele Schafe, und in einem Winter so viele, dass er aufgehört hatte zu zählen.',
        'Es war, weil ihm klar wurde, dass zu Hause niemand es erfahren würde.',
        'Niemand zu Hause wusste, wo er war. Er hatte es nicht sagen können, denn er konnte nicht schreiben und es ging niemand in diese Richtung. Wenn er morgen an einem Strand auf der anderen Seite stürbe, würde sein Vater in den Hügeln hinter Tanger bis in den Winter warten und danach denken, er sei weggelaufen.',
        'Tafukt drückte ihre Nase gegen seine Schulter.',
        'Er blieb sitzen, bis es dunkel wurde, und stand auf, als der Ruf kam, wie er es jetzt tat, und ging danach an die Arbeit.',
        'Am nächsten Morgen suchte er den Schreiber auf.',
        'Der Schreiber war ein kleiner Mann mit Tintenfingern, der den ganzen Tag auf einem Stein saß und Dinge aufschrieb, um die ihn niemand gebeten hatte. Er hieß Yunus und kam aus Kairouan.',
        '„Kannst du etwas für mich aufschreiben?“',
        'Yunus sah auf. „Für wen?“',
        '„Meinen Vater.“',
        '„Kann dein Vater lesen?“',
        'Ayyur schwieg.',
        '„Nein“, sagte er dann.',
        '„Kennt er jemanden, der es kann?“',
        '„Der Mann, der die Steuer eintreibt, kommt zweimal im Jahr. Der kann es.“',
        'Yunus dachte nach, holte dann eine Scherbe aus seiner Kiste und setzte sie sich aufs Knie.',
        '„Sag es.“',
        'Ayyur sagte: „Ayyur lebt. Ayyur ist bei den Pferden. Ayyur kommt zurück.“',
        'Yunus schrieb es auf, sah es an und sagte: „Ist das alles?“',
        '„Was sollte sonst noch dastehen?“',
        'Der Schreiber zuckte mit den Schultern und legte die Scherbe in die Kiste zu den Briefen, die mit dem nächsten Boot zurückgehen würden.',
        'Es war das erste Mal in seinem Leben, dass Ayyurs Name irgendwo stand.',
        'Er dachte den Rest des Tages daran, während er Hufe ausschnitt und Wasser holte, und er ertappte sich dabei, dass er es schön fand auf eine Art, für die er sich fast schämte.',
      ] },
      { titel: 'Der Berg des Tariq', tekst: [
        'In der dritten Woche bekam der Felsen seinen Namen, und Ayyur war dabei, als es geschah, auch wenn er das in dem Moment nicht wusste.',
        'Es gab da schon ein Lager. Es gab Umzäunungen, es gab einen Brunnen, den sie ausgegraben hatten, es standen Zelte in Reihen. Vier Ladungen waren angekommen und es würden noch mehr kommen.',
        'Yunus saß auf seinem Stein mit einem Täfelchen auf den Knien, und er fragte den Mann neben sich, wie er den Ort aufschreiben solle.',
        '„Welchen Ort?“',
        '„Diesen. Wo wir sind. Ich muss aufschreiben, wo das Heer ist.“',
        'Der Mann zuckte mit den Schultern.',
        '„Beim Berg“, sagte er.',
        '„Welchem Berg?“',
        'Sie sahen beide hinauf.',
        '„Dem Berg des Tariq“, sagte der Mann, und er sagte es, wie man etwas sagt, das auf der Hand liegt.',
        'Yunus schrieb es auf. Jabal Tariq.',
        'Ayyur stand zwei Schritte weiter mit einem Eimer in der Hand und hörte es, und dachte: gut, und ging weiter.',
        'So gehen diese Dinge. Es ist nie jemand dabei, der denkt: das ist der Augenblick. Der Augenblick sieht aus wie ein Schreiber, der ein Wort braucht, und ein Soldat, der keine Lust hat.',
        'Dreizehnhundert Jahre später steht dieser Name noch auf jeder Karte der Welt, abgeschliffen zu etwas, das kein Mensch mehr wiedererkennt, und niemand, der ihn ausspricht, weiß, dass es einen Mann gab, der Tariq hieß.',
        'Ayyur brachte den Eimer zu den Pferden.',
      ] },
      { titel: 'Das Heer zieht nach Norden', tekst: [
        'Sie brachen an einem Julimorgen auf, und es dauerte vom ersten Licht bis weit nach Mittag, bis die letzte Reihe außer Sicht war.',
        'Ayyur ging nicht mit.',
        'Das war ihm zwei Tage früher gesagt worden, von Sa3id, der es brachte, wie er alles brachte: ohne Umschweife und in der falschen Reihenfolge.',
        '„Du bleibst hier.“',
        '„Warum?“',
        '„Weil hundert Pferde zurückbleiben und jemand für sie sorgen muss.“',
        '„Es gibt andere Männer.“',
        '„Es gibt keine anderen Männer, die alle Namen kennen.“',
        'Ayyur wusste nicht, ob das ein Lob war oder eine Art, ihn aus dem Kampf zu halten. Er vermutete das Zweite, und er war darüber gleichzeitig wütend und erleichtert, und diese zwei Dinge nebeneinander zu fühlen ist etwas, wofür man mit zwölf noch kein Wort hat.',
        'Sa3id ging mit.',
        'Am Morgen des Aufbruchs kam er an der Umzäunung vorbei, sein Pferd an der Hand — ein grauer Wallach, den Ayyur schon drei Monate versorgte und den er Amellal nannte, was weiß bedeutet, was nicht stimmte, was der Wallach aber nie bestritten hatte.',
        '„Sorg dafür, dass er trinkt, bevor es heiß wird“, sagte Ayyur.',
        '„Das weiß ich.“',
        '„Er trinkt nicht aus stehendem Wasser. Du musst es mit der Hand bewegen.“',
        '„Das weiß ich auch.“',
        'Sie standen beide da, als müsste noch etwas kommen.',
        '„Wenn etwas ist“, sagte Sa3id, „gehst du zu Yunus. Der ist nicht tapfer, aber der ist klug, und klug ist hier mehr wert.“',
        '„Gut.“',
        'Sa3id stieg auf, sah noch einmal hinunter und sagte: „Du bist kein schlechter Junge, Ayyur. Bleib vom Wasser weg, du kannst nicht schwimmen.“',
        'Dann ritt er weg.',
        'Ayyur sah ihn bis irgendwo auf halber Höhe des zweiten Hügels und danach nicht mehr, denn ab da war es eine Staubwolke und waren es keine Menschen mehr.',
        'Er ging zurück zu den Pferden.',
        'Es waren hundertvier. Er zählte sie zweimal.',
      ] },
      { titel: 'Warten ist auch etwas', tekst: [
        'Die Wochen danach waren die längsten seines Lebens und es geschah fast nichts darin.',
        'Das ist das Seltsame am Krieg, entdeckte Ayyur: für fast alle ist er Warten. Die Geschichten handeln vom Tag, an dem es geschah. Niemand erzählt von den vier Wochen davor, in denen man Gras sucht für hundertvier Pferde an einem Hang, wo das Gras alle ist.',
        'Er lernte in diesen Wochen drei Dinge.',
        'Das erste lernte er von dem alten Mann mit den Ziegen, der alle paar Tage vorbeikam und danach jeden Tag, und der schließlich seine Nachmittage an der Umzäunung verbrachte, ohne dass jemand erklären konnte, warum. Er hieß etwas, das Ayyur nie richtig aussprechen konnte. Er zeigte auf Dinge und sagte das Wort, und Ayyur sagte es nach, und der alte Mann verbesserte ihn, und das ging so den ganzen Sommer.',
        'Wasser. Stein. Ziege. Berg. Kind. Brot.',
        'So lernt man eine Sprache. Nicht aus einem Buch. Von einem alten Mann, der nichts Besseres zu tun hat.',
        'Das zweite lernte er von Yunus. Er fragte eines Nachmittags, halb im Scherz, ob der Schreiber ihm Buchstaben beibringen könne, und Yunus sagte: „Nein“, und saß drei Tage später mit einem Stock im Sand neben ihm.',
        'Es ging langsam. Ayyur war schlecht darin. Seine Hand tat nicht, was sein Kopf sich ausdachte, und die Buchstaben kamen schief heraus, wie etwas, das ein Tier angefasst hat.',
        'Nach einem Monat konnte er seinen eigenen Namen.',
        'Er schrieb ihn an diesem Abend zwanzigmal in den Sand bei der Umzäunung und wischte ihn zwanzigmal aus, und das einundzwanzigste Mal ließ er ihn stehen, bis der Wind ihn mitnahm.',
        'Das dritte lernte er von niemandem.',
        'Er entdeckte, dass er beim Ruf nicht mehr nur aufstand, weil es höflich war.',
        'Es war irgendwann im August. Er stand bei Tafukt, es wurde dunkel, der Mann auf dem Stein fing an, und Ayyur merkte, dass er es schön fand, dass es geschah. Nicht wegen dem, was gesagt wurde — er verstand immer noch wenig davon. Wegen der Tatsache, dass an einem Tag fünfmal ein Strich gezogen wurde, an einer Küste, wo er niemanden kannte und niemand ihn kannte, und dass der Tag dadurch kein Brei war, sondern ein Ding mit Teilen.',
        'Er stellte sich immer noch nicht dazu.',
        'Aber er fragte Yunus in dieser Woche doch, wie die Worte gingen, und Yunus sprach sie ihm langsam vor, und Ayyur sprach sie nach, und der Schreiber verbesserte ihn, wie der alte Mann ihn bei Wasser, Stein, Ziege verbesserte.',
        'Dabei bleibt es in diesem Buch, denn dabei blieb es.',
        'Was in den Jahren danach daraus geworden ist, wissen wir nicht. Wir wissen nur, dass es bei Tausenden Jungen wie ihm so anfing: nicht mit einem Heer, nicht mit einem Kampf, sondern mit jemandem, der etwas fünfmal am Tag geschehen sah, bis es zum Tag gehörte.',
      ] },
      { titel: 'Die Nachricht vom Fluss', tekst: [
        'Die Nachricht kam an einem Dienstag, mit einem Reiter, der so schnell geritten war, dass sein Pferd nicht mehr zu retten war.',
        'Ayyur sah es dem Pferd an, bevor er es dem Mann ansah. So ist das, wenn man zu den Pferden gehört.',
        'Es war an einem Fluss im Süden des Landes gekämpft worden, acht Tage weit. Es hatte drei Tage gedauert, oder fünf, je nachdem, wen man fragte. Der König mit der Krone war dort gewesen und war es nicht mehr, und darüber gingen die Geschichten sofort so weit auseinander, dass Ayyur aufhörte zuzuhören.',
        'Was in jeder Geschichte gleich war: das Heer war nicht geschlagen. Es zog weiter nach Norden. Es würden Städte fallen, die niemand im Lager beim Namen kannte.',
        'An diesem Abend wurde am Strand gejubelt.',
        'Ayyur jubelte nicht, denn er hatte immer noch nicht gehört, was er hören wollte.',
        'Er fragte den Reiter, der zu müde war, um höflich zu sein.',
        '„Sa3id aus Tlemcen. Graues Pferd. Narbe durch die Augenbraue.“',
        'Der Mann sah ihn an, als fragte er ihn nach einem Schaf aus einer Herde von zehntausend.',
        '„Junge“, sagte er. „Ich weiß nicht mal den Namen des Königs sicher.“',
        'Drei Wochen später kam ein zweiter Reiter, und der wusste es auch nicht.',
        'Im Oktober kam ein Karren zurück mit Verwundeten und mit Männern, die nicht mehr wollten, und Ayyur ging alle achtundzwanzig ab und fragte es achtundzwanzigmal.',
        'Der fünfundzwanzigste kannte ihn.',
        '„Sa3id“, sagte er. „Ja. Beim Fluss.“',
        'Ayyur wartete.',
        '„Er lebte, als ich ihn sah“, sagte der Mann. „Danach bin ich gefallen und habe nichts mehr gesehen.“',
        'Das war alles. Das ist alles, was Ayyur je erfahren hat, und es ist auch alles, was wir wissen, denn von den siebentausend Männern, die in jenem Jahr die Meerenge überquerten, sind vier beim Namen bekannt und der Rest ist Staub.',
        'Ayyur ging zurück zur Umzäunung.',
        'Amellal stand nicht dabei. Das hatte er seit drei Monaten nicht, und trotzdem sah er jedes Mal hin.',
        'Er holte Wasser, bewegte es mit der Hand, wie man das für ein Pferd tut, das nicht aus stehendem Wasser trinkt, und gab es einem anderen Tier.',
      ] },
      { titel: 'Die Kiste', tekst: [
        'Ende Oktober ging Yunus mit einer Kiste unter dem Arm durch das Lager, auf der Suche nach jemandem, der mit Pferden umgehen konnte und den Weg die Küste entlang wusste.',
        'Es war sonst niemand mehr da. Das war die ehrliche Antwort auf die Frage, warum er bei Ayyur landete.',
        'Die Kiste musste nach Norden, an einen Ort, wo das Heer ein Winterlager eingerichtet hatte. Es waren Täfelchen darin, und Briefe, und ein Ledersack mit kleinen Dingen, die Soldaten abgegeben hatten, weil sie sie nicht verlieren wollten — und die sie nicht abgeholt hatten, was über diese Soldaten alles sagt, was man nicht wissen will.',
        '„Wie lange?“, fragte Ayyur.',
        '„Sechs Tage. Acht, wenn es regnet.“',
        '„Und dann?“',
        'Yunus sah ihn an.',
        '„Dann bist du dort“, sagte er. „Und dort ist mehr als hier.“',
        'Ayyur lud die Kiste auf Tafukt.',
        'Beim Festzurren fiel der Sack um und es rollte etwas heraus auf den Boden.',
        'Es war aus Bronze, so lang wie seine Hand, und es hatte einen Kopf mit acht Zacken. Wie ein Stern.',
        '„Was ist das?“, fragte er.',
        'Yunus sah kaum hin.',
        '„Ein Schlüssel“, sagte er. „Der war schon im Sack, als ich ihn bekam. Niemand weiß, von wem.“',
        'Ayyur hielt ihn kurz in der Hand. Er war warm von der Sonne.',
        'Er dachte an eine Tür irgendwo, auf der anderen Seite des Wassers, die jemand zum letzten Mal hinter sich zugezogen hatte, ohne zu wissen, dass es das letzte Mal war. An ein Haus, das vielleicht noch stand. An einen Mann, der sich eingeschifft hatte mit einem Schlüssel in der Tasche, weil man den nicht zurücklässt, und der ihn abgegeben hatte, weil man ihn auch nicht mit über den Fluss nimmt.',
        'Er ließ ihn in den Sack zurückgleiten.',
        'Dann holte er ihn wieder heraus und steckte ihn in seinen eigenen Gürtel.',
        'Yunus sah es und sagte nichts.',
        '„Es kommt niemand dafür“, sagte Ayyur.',
        '„Nein“, sagte Yunus. „Es kommt niemand dafür.“',
        'Ayyur zog den Riemen an und stieg auf.',
      ] },
      { titel: 'Nach Norden', tekst: [
        'Er ritt an diesem Nachmittag die Küste entlang davon, mit einer Kiste, einer Stute und einem Schlüssel, der niemandem gehörte.',
        'An der letzten Kurve vor dem Hang hielt er an und sah zurück.',
        'Das Lager lag unter ihm, als hätte es immer dort gelegen: Umzäunungen, Zelte in Reihen, der Brunnen, Rauch von zwei Feuern. Vor sieben Monaten waren es Kiesel und Tang gewesen.',
        'Der alte Mann mit den Ziegen stand am Rand seines Hangs, wie er dort jeden Nachmittag stand.',
        'Ayyur hob die Hand.',
        'Der alte Mann hob seinen Stock.',
        'Das war es.',
        'Er ritt weiter, und das Land, in das er hineinritt, war grün auf eine Art, die er nicht kannte, mit anderen Bäumen und zu viel Wasser, und mit Dörfern, wo Leute am Weg standen und einem Jungen auf einer Stute mit einer Kiste nachsahen.',
        'Er grüßte sie mit den Wörtern, die er von dem alten Mann gelernt hatte. Wasser. Stein. Brot.',
        'Manche lachten. Eine Frau gab ihm Brot.',
        'Das hätte er später aufschreiben sollen, denn es ist die Art Ding, die verschwindet: dass die ersten Wochen der Eroberung jenes Landes für einen Jungen von zwölf aus fremden Bäumen, zu viel Wasser und einer Frau bestanden, die ihm Brot gab.',
        'Er ist nie zurückgegangen in die Hügel hinter Tanger.',
        'Das war kein Entschluss. Das ist es bei fast niemandem. Es wurde Winter, und es gab Arbeit, und es gab Pferde, und dann war ein Jahr vorbei und noch eins, und irgendwann ist es keine Reise mehr, die man aufschiebt, sondern ein Leben, das man hat.',
        'Die Scherbe mit seinem Namen ist bei seinem Vater angekommen. Das wissen wir nicht. Das hoffen wir.',
        'Was wir wissen, ist, dass in den Jahrhunderten danach Millionen Menschen diese Meerenge überquert haben, in die eine Richtung und in die andere, und dass jedes Mal jemand zurückblieb, der wartete.',
        'Der Schlüssel zog mit nach Norden, im Gürtel eines Jungen, der ihn von niemandem bekommen hatte.',
        'Wohin er danach ging, steht im nächsten Band.',
      ] },
    ],
  },
}
