import type { Hoofdstuk } from './sleutels'

/** Deel 10 — De stad aan zee. Essaouira, vanaf 1764. */
export const DEEL10_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Wind', tekst: [
    'Er staat daar altijd wind.',
    'Dat is geen manier van zeggen. Aan die kust waait het driehonderd dagen per jaar uit het noordwesten, en de mensen die er woonden wisten niet beter.',
    'Yto was dertien en ze hielp haar vader met de netten, en haar leven bestond uit vis, zand, wind, en een dorp van veertig huizen achter de duinen.',
    'Er was een fort. Een oud Portugees fort, half ingestort, waar niemand meer in kwam behalve de meeuwen.',
    'En er was een eiland voor de kust waar ze vroeger purperslakken vandaan haalden om stof mee te verven, duizend jaar geleden, in de tijd van de Romeinen.',
    'Verder was er niets.',
    'In de zomer dat Yto dertien werd, kwamen er schepen die niet kwamen vissen.',
  ] },
  { nummer: 2, titel: 'De man met de passer', tekst: [
    'Er stapten mannen aan wal die ze nog nooit had gezien: soldaten, en daarna mannen met rollen papier.',
    'Een van hen was geen Marokkaan. Dat zag je meteen.',
    'Hij was bleek, hij had het te warm, hij droeg schoenen die niet deugden in zand, en hij liep de hele dag met een passer en een lange ketting over het strand.',
    'Hij mat.',
    'Yto keek er drie dagen naar voordat ze dichterbij kwam.',
    '“Wat doet u?”',
    'Hij keek op. Hij sprak een soort Arabisch, slecht, maar te volgen.',
    '“Ik teken een stad.”',
    '“Hier is geen stad.”',
    '“Nee,” zei hij. “Daarom teken ik hem eerst.”',
    'Hij heette Théodore. Hij kwam uit Frankrijk en hij was ingenieur, en de sultan had hem laten komen om een havenstad te ontwerpen op deze plek.',
    '“Waarom hier?” vroeg Yto. “Het waait hier altijd.”',
    '“Daarom,” zei Théodore. “Wind is een haven waard. En er is diep water, en er is een eiland dat de golven breekt.”',
    'Hij draaide zijn papier om zodat ze het kon zien.',
    'Er stonden rechte lijnen op. Straten die elkaar kruisten in vierkanten. Een muur eromheen met torens op de hoeken.',
    'Yto had nog nooit een stad gezien die rechte straten had.',
  ] },
  { nummer: 3, titel: 'De stad op papier', tekst: [
    'Wat er toen gebeurde, ging sneller dan iemand had verwacht.',
    'De sultan — Mohammed ben Abdallah — wilde één haven waar alle handel met Europa doorheen ging, en hij wilde die kunnen overzien.',
    'Dus werd er gebouwd. Duizenden mannen. Steen uit de omgeving, hout uit de bergen, kalk uit ovens die ze op het strand bouwden.',
    'Yto’s vader werkte mee, want vissen leverde minder op dan stenen dragen.',
    'Binnen tien jaar stond er een stad waar veertig huizen hadden gestaan.',
    'En de sultan haalde er mensen naartoe.',
    'Kooplieden uit Fes en Marrakech. Europeanen met consulaten. En een grote joodse gemeenschap, die de handel met Europa deed en die in de stad een eigen wijk kreeg — de mellah — met synagogen en scholen.',
    'Op een markt in Essaouira hoorde je in die jaren Arabisch, Tamazight, Hebreeuws, Frans, Engels en Portugees op dezelfde ochtend.',
    'Yto heeft dat als kind normaal gevonden.',
    'Pas veel later, toen ze oud was en het anders was geworden, heeft ze begrepen dat het niet normaal was.',
  ] },
  { nummer: 4, titel: 'Wat een naam betekent', tekst: [
    'Over de naam is nooit iedereen het eens geworden.',
    'De meesten zeggen dat Essaouira "de kleine muur" betekent, of "de mooi getekende". Dat laatste past bij een stad die op papier is bedacht voordat hij bestond.',
    'De Europeanen noemden hem Mogador, en dat is waarschijnlijk een verbastering van de naam van een heilige die daar begraven ligt.',
    'Twee namen voor dezelfde stad, en dat is in Marokko eerder regel dan uitzondering.',
    'Yto leerde in die jaren lezen. Dat is het echte verhaal van dit deel.',
    'Ze leerde het van een klerk op de haven die haar in dienst nam om vangsten te noteren, omdat ze kon tellen en omdat hij een hekel had aan tellen.',
    'Binnen een jaar deed ze de boeken.',
    'Binnen drie jaar wist ze wat er in en uit ging, en wist ze meer over de handel van die haven dan de meeste mannen die er hun geld verdienden.',
  ] },
  { nummer: 5, titel: 'Een schip naar het westen', tekst: [
    'Ze vond de sleutel in het zand.',
    'Dat is de eerlijke versie, en het is toevallig, en zo gaat het meestal.',
    'Hij lag bij de vloedlijn achter het nieuwe havenhoofd, tussen scherven en wier. Brons, groen uitgeslagen, met acht punten aan de kop.',
    'Ze maakte hem schoon met zand en azijn en legde hem op de tafel waar ze de boeken bijhield, als gewicht op de papieren tegen de wind.',
    'Jaren lag hij daar.',
    'In 1778 kwam er een schip dat alle klerken in de haven zich zijn blijven herinneren. Het voer onder een vlag die niemand kende: strepen en sterren.',
    'Het kwam uit een land dat twee jaar daarvoor had gezegd dat het een land was, en waar de meeste mensen in Essaouira nog nooit van hadden gehoord.',
    'De kapitein had papieren nodig en Yto maakte ze op.',
    'Toen hij weg was, was de sleutel er niet meer.',
    'Ze heeft nooit geweten of hij hem gepakt heeft of dat hij tussen de papieren mee de loopplank op is gegaan.',
    'Ze was er niet boos over. Ze vond het passen.',
  ] },
  { nummer: 6, titel: 'Wat ervan over is', tekst: [
    'Essaouira staat er nog, met dezelfde rechte straten die Théodore op papier zette.',
    'De muren staan er, de kanonnen staan er nog op de wallen, de blauwe boten liggen er nog in de haven. De stad staat op de Werelderfgoedlijst, en er komen mensen uit alle landen naar de plek waar Yto netten boette.',
    'De joodse wijk is er nog. De mensen grotendeels niet; die zijn in de twintigste eeuw vertrokken, naar Israël, naar Frankrijk, naar Canada.',
    'Er zijn in Essaouira nog steeds synagogen die worden onderhouden, en een begraafplaats aan zee, en families in Casablanca en in Parijs die zeggen: wij komen uit Mogador.',
    'Yto is negentig geworden.',
    'Ze heeft tot haar laatste jaar de boeken van de haven gedaan.',
    'En ze heeft haar kleindochters leren lezen, alle vijf, ook degenen die het niet wilden.',
  ] },
]
