import type { Hoofdstuk } from './sleutels'

/** Deel 12 — De berg die niet meeging. Het Rif, 1921–1926. */
export const DEEL12_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Het dorp', tekst: [
    'Itto was vijftien en haar vader gaf les in een kamer met zeven kinderen en geen ramen.',
    'Hun dorp lag in het Rif, hoog, tussen rotsen waar amandelbomen groeiden die niemand had geplant. Vanaf het dak van hun huis kon ze op heldere dagen de zee zien.',
    'Wat ze niet kon zien, waren de grenzen.',
    'Die waren er sinds 1912 wel. Toen was Marokko verdeeld: Frankrijk kreeg het grootste deel, Spanje het noorden, en er was afgesproken dat de sultan er nog was maar niet echt.',
    'Niemand in het dorp had die afspraak getekend. Niemand had het gevraagd.',
    'Haar vader zei er weinig over. Hij zei: leer lezen, dan kun je zelf nagaan wat er is opgeschreven.',
    'Hij leerde haar Arabisch lezen en schrijven, en ook Spaans, omdat hij zei dat je de taal van degene die over je beslist moet kennen.',
    'Dat laatste heeft haar leven bepaald.',
  ] },
  { nummer: 2, titel: 'Drie talen', tekst: [
    'Thuis spraken ze Tarifit en dat stond nergens geschreven.',
    'Dat is een vreemd ding om uit te leggen aan iemand die het niet kent, en Itto heeft er haar hele leven les over gegeven.',
    'Tarifit is de taal van het Rif. Het is Amazigh, het is er al duizenden jaren, en het was de taal waarin haar moeder haar riep en waarin de buurvrouw ruziede en waarin ze telde als ze in haar hoofd telde.',
    'En er was geen boek in.',
    'Niet omdat het niet kon. Omdat het niet gedaan werd.',
    'Wat er in het dorp aan schrift was, was Arabisch. Dat leerde je in de kamer van haar vader, met zeven kinderen en geen ramen.',
    'En daarnaast leerde hij haar Spaans, en dat vonden de mensen in het dorp vreemd.',
    '“Waarom?” had de buurman gevraagd.',
    '“Omdat zij beslissen,” had haar vader gezegd. “En je moet kunnen lezen wat er over je besloten wordt.”',
    'Itto was daar als kind boos over geweest, omdat ze Spaans moest leren van mannen die ze niet aardig vond.',
    'Op haar zestiende begreep ze het.',
    'Op haar achttiende was het de reden dat ze nog leefde, want ze heeft twee keer een soldaat in zijn eigen taal antwoord gegeven op een moment waarop zwijgen verkeerd zou zijn afgelopen.',
    'Ze heeft later, als lerares, altijd hetzelfde gezegd tegen kinderen die vroegen waarom ze een taal moesten leren die ze niet nodig dachten te hebben.',
    '“Je hebt hem niet nodig,” zei ze dan. “Tot je hem nodig hebt.”',
    'Tarifit is pas in deze eeuw officieel erkend in Marokko, met een eigen schrift dat op straatnaamborden staat.',
    'Itto heeft dat niet meer meegemaakt. Haar kleindochter wel, en die heeft op de dag dat het bekend werd naar het graf van haar oma gebeld met een telefoon in haar hand, wat nergens op sloeg en wat ze toch deed.',
  ] },
  { nummer: 3, titel: 'Annual', tekst: [
    'In juli 1921 kwam er nieuws dat te groot was om te geloven.',
    'Bij een plek die Annual heet, was het Spaanse leger verslagen. Niet teruggedrongen — verslagen. Duizenden soldaten, tientallen posten, allemaal weg in een paar dagen.',
    'De man die het bevel voerde aan hun kant heette Abd el-Krim. Hij was rechter geweest, en journalist, en hij had in Spanje gestudeerd.',
    'In het dorp werd er die avond gezongen.',
    'Itto heeft later geschreven dat ze zich die avond herinnert als de laatste waarop iedereen alleen maar blij was.',
    'Want daarna kwam de rest.',
    'Abd el-Krim riep een republiek uit. Er kwam een bestuur, er kwamen wetten, er was een raad. Voor het eerst in de geschiedenis van die bergen was er iets dat niet van een stam was maar van iedereen.',
    'En Spanje kwam terug met alles wat het had.',
  ] },
  { nummer: 4, titel: 'Wie hij was', tekst: [
    'Over Abd el-Krim is later van alles beweerd en het meeste klopt niet, en het klopt aan twee kanten niet.',
    'Aan de ene kant is hij een wilde man uit de bergen genoemd.',
    'Aan de andere kant is hij een held gemaakt die nooit een fout heeft gemaakt.',
    'Dit is wat er van hem bekend is, en het is interessanter dan allebei.',
    'Hij was een geleerde. Hij had aan de al-Qarawiyyin in Fes gestudeerd — dezelfde school die in het derde deel van dit boek gebouwd wordt.',
    'Hij was rechter geweest in Melilla, de Spaanse stad aan de kust. In Spaanse dienst.',
    'Hij had bij een krant gewerkt. Hij schreef stukken in het Arabisch voor een Spaanse krant, over wat er in het Rif gebeurde, voor een publiek dat in Madrid woonde.',
    'Zijn vader had jarenlang met de Spanjaarden samengewerkt, omdat dat beter leek dan het alternatief.',
    'En toen is hij van mening veranderd, en dat is het deel dat er in de boeken meestal niet bij staat.',
    'Hij is in 1915 door de Spanjaarden opgepakt, omdat ze hem niet meer vertrouwden.',
    'Hij heeft geprobeerd te ontsnappen door uit een raam te klimmen. Hij is gevallen en heeft zijn been gebroken, en dat is nooit goed gekomen.',
    'De man die zes jaar later een leger versloeg, liep mank van een val uit een raam.',
    'Itto heeft hem twee keer gezien.',
    'Wat ze zich herinnerde, en wat ze haar leerlingen vertelde als ze ernaar vroegen: dat hij eruitzag als een schoolmeester.',
    'Niet als een generaal. Als iemand die in een kamer met papieren hoort.',
    'Ze vond dat later het belangrijkste wat ze over hem kon zeggen.',
    'Omdat het betekent dat het geen bijzonder soort mens nodig heeft.',
  ] },
  { nummer: 5, titel: 'Wat ze bouwden', tekst: [
    'Tussen 1921 en 1926 is er in die bergen geprobeerd een land te maken, en daar gaat dit hoofdstuk over, want daar gaat het meestal niet over.',
    'Het heette de Republiek van het Rif.',
    'Er kwam een raad. Er kwamen rechters die niet van één stam waren maar van het geheel — en dat was de grootste verandering van allemaal, want in die bergen was recht altijd een zaak van je eigen mensen geweest.',
    'Er kwam belasting. Niet veel, en met moeite geïnd, maar het bestond.',
    'Er kwam een poging tot een postdienst. Er is zelfs een telefoonlijn geweest, over een paar bergkammen, die het een deel van de tijd deed.',
    'En er kwamen scholen.',
    'Itto’s vader werd in het derde jaar gevraagd om mee te helpen met het opzetten van lessen in drie dorpen tegelijk. Hij was zesenveertig en hij had zijn hele leven zeven kinderen tegelijk lesgegeven.',
    'Ze heeft hem in die tijd gelukkiger gezien dan ooit, en ze heeft zich daar later schuldig over gevoeld, want het was oorlog.',
    'Ze heeft dat aan haar dochter zo uitgelegd:',
    '“Hij dacht dat het ergens toe leidde.”',
    'Wat er in die vijf jaar is opgebouwd, is er in het zesde jaar afgebroken, en er is bijna niets van bewaard gebleven — geen archief, geen gebouwen, weinig papier.',
    'Wat er is, is wat mensen zich herinnerden en wat een paar buitenlandse journalisten hebben opgeschreven.',
    'Dat is precies het soort geschiedenis dat verdwijnt.',
    'Niet omdat iemand het verstopt. Omdat de mensen die het weten geen boeken schrijven, en de mensen die boeken schrijven er niet waren.',
  ] },
  { nummer: 6, titel: 'Boodschappen', tekst: [
    'Itto werd loopster.',
    'Ze kon lezen, ze kon Spaans, ze was vijftien en een meisje, en dat laatste was het belangrijkste: soldaten hielden een jongen van vijftien aan en een meisje met een mand niet.',
    'Ze bracht berichten tussen de dorpen. In haar hoofd als het kon, op papier als het niet anders kon, en dan opgevouwen in de zoom van haar jurk.',
    'Ze heeft in vier jaar meer van die bergen gezien dan de meeste mensen in hun leven.',
    'Ze heeft ook dingen gezien die ze niet wilde zien.',
    'In dit boek staan die er niet in. Niet omdat ze niet gebeurd zijn, maar omdat Itto ze zelf nooit heeft opgeschreven, en het is niet aan iemand anders om dat voor haar te doen.',
    'Wat er wel in staat, is dit.',
    'Vanaf 1924 werd er iets gebruikt dat niet mag. Vliegtuigen lieten gas vallen op dorpen en op markten, op plekken waar geen soldaten waren.',
    'Spanje heeft dat tientallen jaren ontkend. Pas veel later is het erkend.',
    'Itto was toen achttien.',
  ] },
  { nummer: 7, titel: 'Wie het werk deed', tekst: [
    'De mannen vochten en over de mannen gaan de boeken, en dit hoofdstuk gaat over de rest.',
    'Iemand moest eten maken voor mannen die in de bergen zaten. Elke dag. Voor honderden tegelijk, op plekken zonder weg.',
    'Iemand moest dat eten dragen. Uren lopen, heuvel op, met een last op je rug, en op tijd terug zijn voor het donker werd.',
    'Iemand moest de gewonden verzorgen, want er waren geen dokters. Er waren vrouwen die wisten wat je met een wond doet, en die het aan andere vrouwen leerden, en die dat deden tot ze niet meer konden.',
    'Iemand moest de velden doen. Vijf jaar oorlog, en er moest elk jaar geoogst worden, anders was er in de winter niets.',
    'Itto heeft dat allemaal gedaan tussen haar boodschappen door.',
    'Ze schrijft daar één zin over die haar kleindochter heeft bewaard:',
    '*Ik heb in die jaren meer gelopen dan gepraat.*',
    'Er is over die oorlog veel geschreven en er staan namen in van mannen.',
    'De vrouw die vier jaar lang elke dag eten naar een bergkam bracht, heeft geen naam in enig boek.',
    'Er waren er honderden.',
    'Dit hoofdstuk is er voor hen en het is het kortste van dit deel, omdat er over hen het minste bekend is, en dat is zelf het punt.',
  ] },
  { nummer: 8, titel: 'Wat er uit de lucht kwam', tekst: [
    'Vanaf 1924 gebeurde er iets waar dit boek voorzichtig over moet zijn en waar het niet omheen mag.',
    'Er werden vliegtuigen ingezet, en die lieten geen gewone bommen vallen.',
    'Het was gas. Een gas dat je huid en je longen kapotmaakt, dat in de grond trekt en er jaren blijft, en dat in de Eerste Wereldoorlog was gebruikt en daarna door bijna de hele wereld verboden was.',
    'Het werd niet op soldaten gegooid.',
    'Het werd gegooid op dorpen en op markten. Op de dagen dat er markt was, want dan waren er de meeste mensen.',
    'Itto was achttien.',
    'Ze heeft er in haar leven twee keer over gesproken tegen mensen buiten haar familie, en beide keren heeft ze gezegd dat ze het niet uitvoerig ging doen.',
    'Dat respecteert dit boek.',
    'Wat er wel in hoort, is wat er daarna is gebeurd met dat feit.',
    'Spanje heeft het ontkend. Tientallen jaren. Het stond niet in de geschiedenisboeken daar, en wie ernaar vroeg kreeg te horen dat het propaganda was.',
    'Pas veel later zijn de documenten boven water gekomen — bestellingen, leveringen, verslagen van vluchten — en is er in het Spaanse parlement over gesproken.',
    'Er is nooit excuus gemaakt.',
    'In het Rif liggen tot op vandaag opvallend veel kankergevallen. Onderzoekers zijn het er niet over eens of dat komt door wat er toen is gebeurd, en er is nooit een groot onderzoek geweest dat het zou kunnen uitwijzen.',
    'Dit is de reden dat Itto haar hele leven heeft gezegd dat je moet weten wie de pen vasthield.',
    'Niet omdat mensen liegen. Omdat wat niet wordt opgeschreven, over twee generaties niet gebeurd is.',
  ] },
  { nummer: 9, titel: 'Twee legers', tekst: [
    'In 1925 kwam Frankrijk erbij.',
    'Dat was het einde, al duurde het nog een jaar. Tegen één leger kon het Rif het opnemen. Tegen twee, met vliegtuigen en met honderdduizenden soldaten, niet.',
    'In mei 1926 gaf Abd el-Krim zich over.',
    'Hij werd verbannen naar een eiland in de Indische Oceaan, en later ontsnapte hij naar Egypte, waar hij in 1963 is gestorven.',
    'De republiek was voorbij.',
    'Het dorp van Itto is ontruimd. Dat woord staat in de papieren. Wat het betekende was: iedereen weg, de huizen leeg, en wie niet wegging werd weggehaald.',
    'Haar vader heeft zijn boeken begraven in een kist achter het huis. Dat deden meer mensen.',
    'Itto heeft toen iets gedaan wat ze nooit helemaal heeft kunnen uitleggen.',
    'Ze had een sleutel. Een oude, van brons, met acht punten. Die had ze gekregen van een man in Tetouan die haar berichten doorgaf en die zei dat hij hem uit een kelder in Tanger had.',
    'Ze heeft hem bij de boeken in de kist gelegd.',
    'Dat was haar manier om te zeggen: dit huis is van ons en we komen terug.',
  ] },
  { nummer: 10, titel: 'Eenentwintig jaar op een eiland', tekst: [
    'Wat er met Abd el-Krim is gebeurd, is een verhaal apart en het hoort hier omdat Itto het haar hele leven heeft gevolgd.',
    'Hij gaf zich over in mei 1926.',
    'Hij is niet berecht en niet doodgeschoten. Hij werd op een schip gezet met zijn familie en naar een eiland gebracht dat Réunion heet, in de Indische Oceaan, tienduizend kilometer van het Rif.',
    'Daar heeft hij eenentwintig jaar gewoond.',
    'Hij had een huis, hij mocht het eiland niet af, en hij kreeg geld van de Franse staat waar hij van leefde.',
    'Eenentwintig jaar is lang. Zijn kinderen zijn daar opgegroeid. Er zijn er die het eiland als thuis zijn gaan zien.',
    'In 1947 mocht hij naar Frankrijk verhuizen. Hij is op een schip gezet dat via het Suezkanaal voer.',
    'Bij Port Said is hij van boord gegaan en niet teruggekomen.',
    'Egypte heeft hem opgenomen en niet uitgeleverd. Hij was toen vijfenzestig.',
    'Hij heeft de rest van zijn leven in Caïro gewoond, hij heeft de onafhankelijkheid van Marokko in 1956 meegemaakt, en hij is er niet naartoe gegaan.',
    'Waarom niet, daar zijn verschillende verklaringen voor en geen ervan is zeker.',
    'Hij is in 1963 in Caïro gestorven en daar begraven.',
    'Itto was toen zevenenvijftig en gaf les in Tetouan.',
    'Ze heeft het in de krant gelezen. Ze heeft haar leerlingen die dag verteld wie hij was — niet als held en niet als wilde man, maar zoals ze hem had gezien.',
    'Een man die eruitzag als een schoolmeester en die mank liep van een val uit een raam.',
  ] },
  { nummer: 11, titel: 'Wat de winnaars opschrijven', tekst: [
    'Ze kwamen niet terug. Niet naar dat huis.',
    'Itto is in Tetouan terechtgekomen en daar getrouwd en daar oud geworden.',
    'Ze heeft haar hele leven les gegeven, net als haar vader, eerst in het geheim en later gewoon.',
    'En ze heeft één ding steeds tegen haar leerlingen gezegd.',
    'Dat wat er in de boeken staat, is opgeschreven door degene die won.',
    'Dat dat niet betekent dat het gelogen is — maar dat het betekent dat je moet kijken wie de pen vasthield.',
    'Ze zei dat het niet genoeg is om te kunnen lezen. Dat je ook moet weten wie het heeft geschreven, en waarom, en wat er niet in staat.',
    'Toen Marokko in 1956 onafhankelijk werd, was ze vijftig.',
    'Ze zei tegen haar dochter: ik heb het gezien. Ik heb het niet meegemaakt, want dat is iets anders. Maar ik heb het gezien.',
  ] },
  { nummer: 12, titel: 'De kist onder de vloer', tekst: [
    'De kist is in 1974 teruggevonden.',
    'Een kleinzoon van de buurman bouwde op de plek van de oude dorpen, en bij het graven stuitte zijn schop op hout.',
    'Er zaten zeven boeken in. Vijf waren onleesbaar geworden. Twee niet.',
    'En er zat iets van brons in met acht punten aan de kop.',
    'De man heeft de boeken naar de moskee gebracht en de sleutel meegenomen naar huis, en hij heeft hem in een koperen doos gelegd bij andere dingen waarvan niemand meer wist waar ze vandaan kwamen.',
    'Die doos stond in dat dorp in de Hoge Atlas waar zijn familie naartoe was verhuisd.',
    'Daar staat hij nu nog.',
  ] },
]
