import type { Hoofdstuk } from './sleutels'

/** Deel 4 — De stad die er nog niet was. Marrakech, rond 1070. */
export const DEEL4_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Niets', tekst: [
    'Het eerste wat Isli zag toen ze aankwamen, was niets.',
    'Dat klinkt als een grap en dat was het niet. Er was een vlakte. Er was gras dat in augustus geel was. Er waren palmen in de verte en bergen achter de palmen, met sneeuw erop, in de zomer, wat Isli nog steeds niet geloofde ook al keek hij ernaar.',
    'En er waren geen huizen.',
    '“Hier?” zei hij.',
    '“Hier,” zei zijn oom.',
    'Isli was twaalf en hij dreef kamelen, samen met zijn oom, en ze kwamen uit het zuiden — van achter de bergen, waar het zand begint. Hun werk was simpel: iets ergens vandaan halen en ergens anders neerzetten.',
    'Deze keer was het steen, en de plek waar het neer moest was een vlakte zonder naam.',
    'Er lagen al stapels. Er stonden al tenten, honderden, in rijen. Er waren mannen die geulen groeven in een patroon dat van dichtbij nergens op sloeg.',
    '“Wat wordt het?” vroeg Isli.',
    'Zijn oom spuwde in het zand.',
    '“Een stad, zeggen ze.”',
    '“Waarom hier?”',
    '“Omdat iemand het gezegd heeft.”',
    'Dat was geen antwoord, en Isli bleef ernaar zoeken, en hij vond het pas toen iemand het hem uitlegde die er verstand van had.',
  ] },
  { nummer: 2, titel: 'De vrouw die de vraag stelde', tekst: [
    'Ze was niet wat hij verwachtte, en inmiddels had hij moeten weten dat niemand ooit is wat je verwacht.',
    'Hij zag haar bij de geulen. Ze stond met drie mannen te praten die tekeningen vasthielden, en ze stelde vragen. Dat was het eerste wat hem opviel: ze zei bijna niets, ze vroeg.',
    '“Hoe diep?”',
    '“Vijf el.”',
    '“En in augustus?”',
    'Stilte.',
    '“In augustus,” zei ze nog een keer.',
    'De man met de tekening keek naar zijn voeten.',
    'Ze heette Zaynab. Dat hoorde Isli later. De vrouw van de man die het bevel gaf, en volgens de kooplieden degene die wist hoe geld werkt.',
    'Die avond kwam ze bij de kamelen. Ze liep langs de dieren zoals iemand langs dieren loopt die weet hoe ze staan als ze te zwaar geladen zijn.',
    '“Waar kom je vandaan?” vroeg ze aan Isli.',
    'Hij noemde zijn dorp. Ze knikte alsof ze het kende, en misschien was dat zo.',
    '“Waarom hier?” vroeg Isli, voordat hij bedacht dat je dat niet vraagt.',
    'Zaynab keek hem aan.',
    'Toen wees ze naar de bergen.',
    '“Daar ligt water,” zei ze. “Het hele jaar. In de sneeuw.” Ze wees naar de vlakte. “Hier is niets. Maar hier kruisen de wegen: uit het zuiden het goud, uit het noorden het graan, uit het oosten de mensen.”',
    '“En het water dan?”',
    '“Dat halen we hierheen,” zei ze. “Onder de grond.”',
  ] },
  { nummer: 3, titel: 'De rivier die je niet ziet', tekst: [
    'Het systeem heette khettara en Isli heeft er een halve zomer aan meegewerkt, en hij vond het het knapste wat hij ooit had gezien.',
    'Het idee is eenvoudig genoeg om aan een kind uit te leggen en moeilijk genoeg om er honderden mannen jarenlang aan te laten werken.',
    'Aan de voet van de bergen zit water in de grond. Je graaft daar een put. Dan graaf je een stukje verderop nog een put, iets minder diep. Dan nog een. En onder de grond verbind je ze allemaal met een gang die héél licht afloopt.',
    'Het water loopt vanzelf. Geen emmer, geen dier, geen pomp. Het loopt kilometers ondergronds en komt aan de andere kant tevoorschijn in een stad die er zonder dat water niet had kunnen staan.',
    'En het verdampt niet, want de zon komt er niet bij.',
    'Isli bracht steen naar de putten. Hij klom er een keer in, tegen de regels, en stond in het donker in een gang waar water langs zijn enkels liep.',
    'Boven hem, door het putgat, was een cirkel blauw.',
    'Hij bleef daar langer staan dan verstandig was.',
  ] },
  { nummer: 4, titel: 'De naam', tekst: [
    'De stad kreeg haar naam voordat ze bestond, en daar heeft Isli altijd om moeten lachen.',
    'Er werd over gepraat bij de vuren. Het meest gehoorde verhaal was dat het uit het Amazigh kwam: *mur akush*, het land van God. Er waren er ook die zeiden dat het iets anders betekende en dat zij het beter wisten.',
    'Wat Isli wel zeker weet, is dat er die zomer al mensen waren die zeiden “ik ga naar Marrakech” terwijl er niets stond dan tenten en geulen.',
    'Een naam gaat sneller dan muren.',
    'In de tweede zomer stond er een muur. In de derde stonden er huizen binnen die muur, en een markt, en een moskee waar de mannen uit het kamp naartoe gingen op vrijdag in plaats van op het zand.',
    'Isli bracht nog steeds steen.',
    'Zijn oom rekende uit dat ze in drie jaar meer verdiend hadden dan in de tien jaar daarvoor, en hij zei dat ze moesten stoppen nu het goed was, en dat deden ze niet.',
  ] },
  { nummer: 5, titel: 'Wat hij achterliet', tekst: [
    'De sleutel kwam bij hem terecht op de manier waarop de meeste dingen bij mensen terechtkomen: per ongeluk en zonder dat iemand oplette.',
    'Hij kocht een zadeltas van een handelaar uit het noorden, tweedehands, omdat zijn eigen tas kapot was. Er zat van alles in dat de handelaar vergeten was eruit te halen: twee munten die niet meer golden, een stuk touw, en iets van brons met acht punten aan de kop.',
    'Isli hield het tegen het licht.',
    '“Waar is dit van?”',
    '“Weet ik veel,” zei de handelaar. “Uit Fes. Alles wat ik heb komt uit Fes.”',
    'Isli hield hem. Hij was mooi, en hij was warm in je hand, en hij deed hem denken aan de ster die zijn moeder in het deeg drukte voordat ze brood bakte.',
    'In de vierde zomer bouwden ze de poort aan de noordkant, en Isli hielp met de laatste lading steen.',
    'Terwijl de metselaars de bovenkant dichtzetten, deed hij iets wat hij nooit aan iemand heeft verteld.',
    'Hij legde de sleutel in de muur.',
    'Niet om hem te verstoppen. Hij dacht: ik heb hier vier jaar van mijn leven gelaten, en straks ga ik terug naar het zuiden en dan weet niemand meer dat ik er was.',
    'Zo weet de poort het.',
  ] },
  { nummer: 6, titel: 'Wat er van komt', tekst: [
    'Isli is later teruggekomen. Twee keer.',
    'De eerste keer was hij negenentwintig. Er woonden toen meer mensen in Marrakech dan in alle dorpen die hij kende bij elkaar. Er stonden tuinen waar hij geulen had gegraven. Het water uit de bergen kwam onder de grond aan en liep door de binnenhoven alsof het altijd zo was geweest.',
    'De tweede keer was hij oud en had hij een kleinzoon bij zich, en hij wees naar de noordelijke poort en zei: “Daar zit iets van mij in.”',
    'Zijn kleinzoon geloofde hem niet.',
    'Dat gaf niet.',
    'Wat er van gekomen is, staat er nog: een stad die uit niets is gebouwd op een kruispunt van wegen, met water dat van veertig kilometer verderop onder de grond wordt aangevoerd.',
    'En het land dat eromheen ligt heeft de naam van die stad gekregen. Marrakech werd in de talen van het noorden verbasterd tot Marokko — en zo heet het vandaag nog.',
    'Een muur is later afgebroken en weer opgebouwd, en de sleutel kwam vrij tussen het puin, en een metselaarsjongen nam hem mee naar het noorden omdat hij mooi was.',
    'Dat is niet zeker. Dat is wat een verhaal doet met een gat.',
  ] },
]
