import type { Hoofdstuk } from './sleutels'

/** Deel 14 — Zwart op wit. Rabat en de Hoge Atlas, 2011. */
export const DEEL14_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'De taal van thuis', tekst: [
    'Anir was twaalf en hij sprak twee talen, en op school telde er maar één.',
    'Thuis sprak iedereen Tamazight. Zijn oma sprak niets anders. Op school was alles Arabisch, en wie thuis geen Arabisch sprak begon achter en liep dat zelden in.',
    'Dat was niet iets waar hij boos over was. Het was gewoon hoe het was, zoals de winter koud is.',
    'Zijn oma heette Tadla en ze kon niet lezen. Niet in het Arabisch, niet in iets anders. Ze was in 1938 geboren in een dorp met geen school, en ze had zes kinderen grootgebracht en twee begraven, en ze wist alles over schapen en kruiden en niets over letters.',
    'Ze schaamde zich er niet voor. Ze zei: ik heb mijn hoofd gebruikt voor andere dingen.',
    'Maar als er post kwam, gaf ze hem aan Anir en dan keek ze de andere kant op terwijl hij voorlas.',
  ] },
  { nummer: 2, titel: 'Twee uur lopen', tekst: [
    'Het dorp lag op veertienhonderd meter en de school lag in het dal.',
    'Twee uur heen, twee uur terug, als het weer meezat.',
    'Anir liep het vanaf zijn zevende, met vier andere kinderen, en er is nooit iemand geweest die dat bijzonder vond behalve mensen van buiten.',
    'In de winter ging het soms niet. Dan lag er sneeuw op de pas en bleven ze thuis, een week, soms twee.',
    'Dat is de reden dat kinderen uit zulke dorpen achterlopen, en het heeft niets met knapheid te maken.',
    'Wat hij zich van die tocht herinnert is dat hij er op gewend raakte om na te denken.',
    'Vier uur per dag waarin niemand iets van je wil.',
    'Hij heeft er zijn hele schooltijd in gerekend, verhalen bedacht, en woorden van de ene taal in de andere gedraaid om te kijken of het paste.',
    'Dat laatste is waar dit deel over gaat en hij wist toen niet dat hij het deed.',
    'Sommige woorden pasten niet.',
    'Er is in het Tamazight een woord voor de manier waarop water uit de rots komt op de plek waar de sneeuw smelt, en er is geen Arabisch woord dat hetzelfde zegt, en zeker geen Nederlands woord.',
    'Anir heeft dat een keer aan zijn juf gevraagd en die zei dat dat bij elke taal zo is.',
    'Dat klopt. Het maakt het niet minder erg als je taal er geen is die wordt opgeschreven.',
    'Want dan verdwijnt dat woord als de laatste die het gebruikt doodgaat.',
  ] },
  { nummer: 3, titel: 'Wat er in de krant stond', tekst: [
    'In de zomer van 2011 stond er iets in de krant dat zijn vader hardop voorlas aan tafel.',
    'Er kwam een nieuwe grondwet. En daarin stond dat Tamazight een officiële taal van het land werd, naast het Arabisch.',
    'Anir snapte niet meteen wat dat betekende.',
    '“Het betekent,” zei zijn vader, “dat het op papier mag.”',
    '“Het mocht toch al?”',
    'Zijn vader lachte, maar niet vrolijk.',
    '“Vraag je oma eens of haar naam ooit ergens goed geschreven stond.”',
    'Anir vroeg het.',
    'Zijn oma dacht lang na en zei toen dat op haar papieren een Arabische naam stond die haar moeder haar nooit had gegeven, omdat de ambtenaar in 1938 had gezegd dat de naam die ze wél had niet kon.',
    'Ze had zeventig jaar een naam gehad die niet de hare was.',
  ] },
  { nummer: 4, titel: 'De naam die niet kon', tekst: [
    'Dit is het verhaal van hoe zijn oma aan een naam kwam die niet van haar was, en het is niet alleen haar verhaal.',
    'In 1938 kwam haar vader bij de ambtenaar om haar te laten inschrijven.',
    'Hij zei de naam die haar moeder had gekozen: Tadla.',
    'De ambtenaar zei dat die naam niet kon.',
    'Er was een lijst. Op die lijst stonden namen die mochten, en dat waren Arabische namen, en de namen die mensen in de bergen aan hun kinderen gaven stonden er niet op.',
    'Dus is ze ingeschreven als iets anders. Op haar identiteitskaart staat dat nog steeds, en op haar trouwakte, en op de papieren van haar kinderen.',
    'Thuis heeft nooit iemand haar zo genoemd.',
    'Zeventig jaar lang was er een naam op papier en een naam aan tafel, en iedereen wist welke de echte was en de papieren wonnen het toch.',
    'Dit is niet lang geleden opgehouden.',
    'Pas in deze eeuw is die lijst losgelaten, en ook daarna zijn er nog ouders weggestuurd bij het loket omdat de ambtenaar de naam niet kende. Er zijn brieven over geschreven, er is over vergaderd, en uiteindelijk is er uitdrukkelijk bepaald dat een Amazigh-naam gewoon een Marokkaanse naam is.',
    'Anir is aangegeven als Anir.',
    'Zijn oma is daarbij geweest en heeft er niets over gezegd, en op de terugweg heeft ze twee keer gevraagd of het echt gelukt was.',
  ] },
  { nummer: 5, titel: 'Het jaar van de pleinen', tekst: [
    'Om te begrijpen waarom het in 2011 gebeurde en niet in 2001 of 1991, moet je weten wat er dat jaar aan de hand was.',
    'Het begon ergens anders. In Tunesië, en daarna in Egypte, gingen mensen de straat op tegen hun regering, en in een paar weken gebeurde er wat niemand had verwacht.',
    'Het sloeg over. Overal in de Arabische wereld.',
    'In Marokko kwamen er in februari mensen bijeen in de steden. Vooral jonge mensen, vooral via internet georganiseerd, met eisen die gingen over werk, over corruptie, en over een grondwet waarin meer geregeld zou zijn.',
    'Anir was twaalf en woonde op veertienhonderd meter, en hij heeft er niets van gezien.',
    'Hij heeft het gehoord van zijn neef in Beni Mellal, aan de telefoon, in korte zinnen.',
    'Wat er daarna gebeurde is dat de koning in maart een toespraak hield waarin hij een nieuwe grondwet aankondigde, dat er een commissie kwam, en dat er in juli over gestemd werd.',
    'En in die grondwet stond Tamazight.',
    'Dit is de eerlijke zin van dit hoofdstuk, en Anir heeft hem pas op zijn twintigste begrepen:',
    'De taal van zijn oma is niet officieel geworden omdat iemand op een ochtend bedacht dat het netjes was.',
    'Het is gebeurd in een jaar waarin er in heel de regio mensen op straat stonden, en waarin een regering redenen had om te laten zien dat ze luisterde.',
    'Dat maakt het niet minder waar en niet minder waardevol.',
    'Het betekent alleen dat dingen die vanzelfsprekend lijken als ze er eenmaal zijn, meestal niet vanzelf zijn gekomen.',
  ] },
  { nummer: 6, titel: 'Tifinagh', tekst: [
    'Op school kwam er dat jaar een uur bij.',
    'Tamazight, met een schrift dat Anir nog nooit had gezien: Tifinagh.',
    'Het lijkt op niets. Geen Arabisch, geen Latijn. Cirkels, driehoeken, kruisjes, lijnen met puntjes. Het ziet eruit alsof iemand het gisteren heeft bedacht.',
    'Dat is precies het tegenovergestelde van waar.',
    'De juf liet ze een foto zien van een rots in het zuiden waarop hetzelfde schrift stond, en ze zei dat die tweeduizend jaar oud was. Ouder dan de meeste dingen waar ze op school over leerden.',
    'Het is altijd blijven bestaan bij de Toeareg in de Sahara. In het noorden was het bijna verdwenen, en in 2003 is er een versie vastgesteld die op scholen gebruikt kan worden.',
    'Anir vond het eerst kinderachtig. Rondjes en streepjes.',
    'Toen schreef hij zijn eigen naam.',
    'ⴰⵏⵉⵔ',
    'Hij heeft dat blaadje bewaard.',
  ] },
  { nummer: 7, titel: 'Ouder dan Rome', tekst: [
    'De juf heeft ze in dat eerste jaar een keer meegenomen naar iets wat twee dalen verderop lag.',
    'Het was een rotswand. Meer niet. Grijze steen, mos, een paar doornstruiken.',
    'Ze moest hun wijzen waar ze moesten kijken, want je ziet het niet als je niet weet dat het er is.',
    'Er stonden tekens in de steen. Ingekrast, versleten, maar leesbaar: cirkels, driehoeken, lijnen met puntjes.',
    'Hetzelfde schrift dat ze die week op het bord hadden gehad.',
    'De juf zei dat niemand precies weet hoe oud het is. Tweeduizend jaar zeker. Waarschijnlijk ouder.',
    'Anir is met zijn hand over de steen gegaan.',
    'Dat is het moment waarop hij ophield het kinderachtig te vinden, en hij kan dat zelf aanwijzen.',
    'Want hij had op school geleerd over de Romeinen en over Walili, en dat waren oude dingen die in boeken stonden en die met hem niets te maken hadden.',
    'En hier stond iets in een rots in zijn eigen dal, in het schrift waarin hij die ochtend zijn naam had geschreven, dat er al stond voordat er in Walili een steen op een steen lag.',
    'Dat schrift is nooit helemaal weg geweest.',
    'In de Sahara, bij de Toeareg, is het altijd gebruikt. Vrouwen schreven er berichten in, en versieringen, en namen op sieraden. Daar is het nooit opgehouden.',
    'In het noorden was het bijna verdwenen, en wat er nu op de borden staat, is teruggehaald en opnieuw vastgesteld — met tekens erbij voor klanken die de oude versie niet had.',
    'Het is dus tegelijk tweeduizend jaar oud en nieuw.',
    'Anir heeft dat lang niet kunnen rijmen en is het uiteindelijk gaan zien als het gewoonste wat er is.',
    'Zo is alles wat nog leeft.',
  ] },
  { nummer: 8, titel: 'Zestien lessen', tekst: [
    'Het idee kwam van hemzelf en hij heeft het maandenlang niet durven voorstellen.',
    'Op een avond in oktober zat zijn oma bij de kachel thee te drinken, en hij ging naast haar zitten met een schrift.',
    '“Jeddti. Ik wil je iets leren.”',
    'Ze keek hem aan zoals oude vrouwen naar kinderen kijken die iets willen.',
    '“Ik ben drieënzeventig.”',
    '“Het is maar één letter per keer.”',
    'Ze heeft nee gezegd. Drie avonden achter elkaar.',
    'Op de vierde avond zei ze: “Hoeveel zijn het er?”',
    '“Drieëndertig.”',
    '“Zoveel?”',
    '“Je hoeft er maar vier te leren,” zei Anir. “Voor je naam.”',
    'Dat is hoe het begon.',
    'Het heeft zestien avonden geduurd, want haar handen waren niet gewend om een potlood zo vast te houden en ze werd kwaad op zichzelf.',
    'Op de zeventiende avond schreef ze haar naam.',
    'ⵜⴰⴷⵍⴰ',
    'Ze heeft er lang naar gekeken en toen heeft ze het blaadje omgedraaid en is opgestaan om thee te zetten die niemand had gevraagd.',
  ] },
  { nummer: 9, titel: 'Wat zijn oma wel wist', tekst: [
    'Er moet in dit deel iets rechtgezet worden, anders klopt het niet.',
    'Zijn oma kon niet lezen, en dit boek gaat over letters, en dan is de kans groot dat het klinkt alsof ze daarom iets tekortkwam.',
    'Dus hier staat wat ze wél wist.',
    'Ze kon aan een schaap zien of het ziek werd, drie dagen voordat iemand anders het zag.',
    'Ze kende veertig planten in de heuvels om het dorp bij naam, en van elke plant waarvoor je hem gebruikt en in welke maand je hem moet halen en welk deel je weggooit.',
    'Ze kon weven. Niet zomaar weven: ze kende de patronen van haar eigen familie, die haar moeder haar had geleerd, en die staan nergens op papier — dat is precies het punt. Zo’n patroon zit in de handen en in het hoofd en het gaat van vrouw op vrouw.',
    'Ze wist welk jaar het geregend had en welk jaar niet, veertig jaar terug, zonder iets op te zoeken.',
    'Ze kende elk pad in een gebied van twee uur lopen in alle richtingen, en ze wist welke in de winter dichtlagen.',
    'Dat is een bibliotheek.',
    'Alleen staat hij niet in een kast en gaat hij weg als zij weggaat.',
    'Anir heeft dat begrepen op de avond dat ze haar naam schreef, en hij heeft toen iets bedacht wat hij de jaren daarna heeft gedaan.',
    'Hij is opschrijven wat ze zei.',
    'Niet als een project. Gewoon, in een schrift, als er iets voorbijkwam.',
    'Achtenzeventig bladzijden is het geworden. Planten, weerspreuken, twee liedjes, en een recept voor iets wat ze tegen hoest maakte.',
    'Zij vond het onzin en ze ging er wel voor zitten.',
  ] },
  { nummer: 10, titel: 'Wat een wet wel en niet doet', tekst: [
    'Het eerlijke deel van dit verhaal is dit.',
    'De wet van 2011 heeft niet meteen iets veranderd.',
    'Het duurde jaren voordat er iets mee gedaan werd. Het duurde tot 2019 voordat er een wet kwam die regelde hóe het moest. Op de meeste scholen is het nog lang niet overal. Ambtenaren die het schrift kunnen lezen zijn zeldzaam.',
    'Er zijn mensen die zeggen dat het symboliek is.',
    'Anir denkt daar anders over, en hij heeft er één argument voor.',
    'Zijn oma heeft op haar drieënzeventigste haar eigen naam geschreven in het schrift van haar eigen taal.',
    'Dat had niet gekund als er niet eerst iemand had gezegd dat het schrift bestond.',
  ] },
  { nummer: 11, titel: 'De brief', tekst: [
    'Anir was zestien toen hij de brief schreef, en het is het enige officiële stuk in dit hele boek dat iets heeft opgeleverd.',
    'Het ging over de naam.',
    'Hij had uitgezocht dat het kon: dat je bij de rechtbank een verzoek kunt indienen om een naam in de registers te laten verbeteren, en wat je daarvoor nodig hebt.',
    'Het was niet eenvoudig. Er moesten stukken bij uit 1938 die er niet meer waren, en er moesten getuigen komen die konden verklaren hoe ze altijd was genoemd.',
    'Zijn oma was toen zevenenzeventig.',
    'Ze wilde eerst niet.',
    '“Ik ben te oud om een andere naam te krijgen.”',
    '“Het is niet een andere naam. Het is je naam.”',
    'Daar had ze geen antwoord op, en dat is de enige keer geweest dat Anir een discussie met haar heeft gewonnen.',
    'Het heeft veertien maanden geduurd.',
    'De dag dat het papier kwam, hebben ze het aan tafel opengemaakt en heeft zijn vader het hardop voorgelezen, en stond er onderaan haar naam zoals haar moeder hem had bedoeld.',
    'Ze heeft ernaar gekeken en gezegd dat het krom gedrukt stond.',
    'Dat was alles wat ze zei.',
    'Anir heeft later begrepen dat dat haar manier was, en dat ze het papier daarna twee jaar lang in de koperen doos heeft bewaard, bij de ring en de twee knopen en de foto van de man die niemand kon thuisbrengen.',
    'Bij de dingen die je houdt.',
  ] },
  { nummer: 12, titel: 'De koperen doos', tekst: [
    'In het huis stond een koperen doos op de kast waar niemand ooit in keek.',
    'Er zaten dingen in die van familie waren geweest en waarvan niemand meer wist wie: een ring, twee knopen, een stukje stof, een foto van een man die niemand kon thuisbrengen.',
    'En een sleutel van brons, met acht punten aan de kop.',
    'Anir heeft er een keer naar gevraagd.',
    'Zijn oma zei dat haar man hem van zijn vader had, en die van een kist die uit het Rif kwam, en verder wist ze het niet.',
    '“Waar is hij van?”',
    '“Van een huis,” zei ze.',
    '“Welk huis?”',
    'Ze haalde haar schouders op.',
    '“Een huis dat er niet meer is. Daarom bewaren we hem.”',
    'Anir vond dat op dat moment een rare zin.',
    'Later, toen hij zelf ergens anders woonde dan waar hij geboren was, vond hij het de minst rare zin die hij ooit had gehoord.',
  ] },
]
