import type { Hoofdstuk } from './sleutels'

/** Deel 6 — Dertig jaar onderweg. Vanaf Tanger, 1325. */
export const DEEL6_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Vertrekken', tekst: [
    'Op de ochtend dat ze vertrokken, huilde Musa niet, en daar is hij later trots op geweest en heeft hij zich later voor geschaamd.',
    'Hij was dertien. Hij kon lezen en schrijven, wat in zijn straat bijzonder was, en daarom was hij meegegeven aan een jongeman uit Tanger die op bedevaart ging en een hulpje nodig had.',
    'De jongeman was eenentwintig. Hij heette Muhammad ibn Battuta en hij was in zijn leven nog nooit verder geweest dan een dagreis van huis.',
    '“Hoe lang duurt het?” had Musa’s moeder gevraagd.',
    '“Zestien maanden,” had Ibn Battuta gezegd. “Misschien achttien.”',
    'Dat was de waarheid, voor zover iemand hem kende. De bedevaart naar Mekka duurde vanuit Marokko ongeveer een jaar heen en een jaar terug, en dan was je thuis en vertelde je erover tot je stierf.',
    'Ze zijn er dertig jaar over gedaan.',
    'Niemand heeft dat op die ochtend geweten. Musa’s moeder gaf hem brood mee voor drie dagen en zei dat hij moest opletten, en toen liepen ze de poort uit.',
    'Achter hen lag Tanger.',
    'Het was 1325 en ze hadden één ezel.',
  ] },
  { nummer: 2, titel: 'Wat je opschrijft', tekst: [
    'Zijn werk was simpel: opschrijven.',
    'Ibn Battuta praatte de hele dag. Hij praatte tegen iedereen die ze tegenkwamen, hij vroeg alles, en ’s avonds vertelde hij wat hij gehoord had. Musa schreef het op.',
    'In het begin schreef hij alles.',
    '*Vandaag zes uur gelopen. Brood gekocht voor twee munten. Een man vertelde dat er verderop water is.*',
    'Na een maand hield hij daarmee op, want er stond te veel en er stond niets in.',
    'Hij leerde kiezen. Dat was het eerste vak dat hij in zijn leven leerde en hij heeft er nooit les in gehad.',
    'Wat je opschrijft is wat blijft. Wat je weglaat is weg. En het rare is: je weet het op het moment zelf nooit.',
    'In Tlemcen schreef hij een bladzijde over een tuin. In Tunis vergat hij te schrijven dat Ibn Battuta twee dagen ziek was en huilde omdat hij zijn moeder miste.',
    'Dat laatste heeft hij later toch opgeschreven, veertig jaar later, in de kantlijn van een ander boek.',
  ] },
  { nummer: 3, titel: 'Alexandrië', tekst: [
    'Alexandrië was de eerste stad waar Musa niet meer wist waar hij moest kijken.',
    'De vuurtoren stond er nog, half. Er waren zeven poorten en een haven met zoveel masten dat het op een bos leek. Er werden talen gesproken die hij nooit had gehoord.',
    'Ze bleven er langer dan de bedoeling was.',
    'Daar gebeurde het ding dat alles veranderde, en het was een gesprek.',
    'Een oude man — een geleerde bij wie ze logeerden — vroeg aan Ibn Battuta waar hij heen ging.',
    '“Mekka.”',
    '“En daarna?”',
    '“Naar huis.”',
    'De oude man keek hem aan alsof hij iets onzinnigs had gezegd.',
    '“Ik heb broeders in India,” zei hij. “En in China. Ga naar ze toe. Zeg dat ik je gestuurd heb.”',
    'Musa zag het gezicht van Ibn Battuta.',
    'Hij heeft later vaak gezegd dat hij het toen al wist: dat ze niet over achttien maanden thuis zouden zijn.',
    'Dat is waarschijnlijk niet waar. Zo werkt geheugen niet. Maar hij was er wel bij.',
  ] },
  { nummer: 4, titel: 'De jaren', tekst: [
    'Wat volgde, past niet in een hoofdstuk en het past eerlijk gezegd ook niet in een boek.',
    'Ze gingen naar Mekka. Ze gingen naar Perzië en naar de steden aan de Zwarte Zee. Ze voeren langs de kust van Afrika tot aan plaatsen waar de taal veranderde in iets wat op Arabisch leek en het niet was.',
    'Ibn Battuta werd rechter in India en bleef er jaren. Hij werd rijk, en armer dan arm, en toen weer rijk. Hij trouwde meerdere keren. Hij werd beroofd. Hij lag een keer een week ziek in een dorp waar niemand zijn naam kende.',
    'Musa groeide op onderweg.',
    'Hij was dertien toen ze vertrokken en drieëntwintig toen hij voor het eerst overwoog om terug te gaan en het niet deed, en vierendertig toen hij het wel deed.',
    'Hij heeft alles opgeschreven.',
    'Vijf kisten. Papier, perkament, stukken linnen als er niets anders was. In het begin netjes, later in een handschrift dat alleen hij kon lezen.',
    'Op de Malediven is één kist overboord geslagen. Daar zat drie jaar in.',
    'Dat is het enige waarover hij ooit echt boos is geweest.',
  ] },
  { nummer: 5, titel: 'Terug', tekst: [
    'Hij kwam eerder thuis dan zijn meester.',
    'In 1349 stond Musa in Tanger, vierendertig jaar oud, met een baard en met handen die niet meer op schrijvershanden leken.',
    'Zijn moeder leefde niet meer. Dat had hij geweten — er was een brief geweest, jaren eerder, die er zeven maanden over had gedaan.',
    'Zijn zus kende hem niet meteen.',
    'Hij is drie dagen in het huis gebleven en toen weer weggegaan naar Fes, want daar was werk voor iemand die kon schrijven, en omdat hij niet wist hoe hij in Tanger moest zitten.',
    'Ibn Battuta kwam later terug. Hij maakte nog één reis, naar het zuiden, naar het rijk van Mali en de stad Timboektoe, en pas daarna was hij klaar.',
    'De sultan van Fes gaf hem opdracht zijn verhaal op te schrijven, en zette er een schrijver bij: Ibn Juzayy, een geleerde uit Granada.',
    'Musa heeft hem zijn aantekeningen gegeven.',
    'Alles. Vier kisten.',
    'In het boek dat eruit kwam — de Rihla, wat gewoon "reis" betekent — staat zijn naam nergens.',
  ] },
  { nummer: 6, titel: 'De vijfde kist', tekst: [
    'Hij heeft er niet om gevraagd. Dat is het antwoord op de vraag die iedereen stelt.',
    'Het was niet zijn reis. Hij was het hulpje dat meeging, en wat hij opschreef schreef hij op in opdracht, en zo dacht men daar toen over.',
    'Wat hij wel deed, was één ding voor zichzelf houden.',
    'De vijfde kist.',
    'Daar zat niet het reisverslag in, maar wat hij ernaast had geschreven: de dingen die er voor een boek niet toe deden. Dat Ibn Battuta in Tunis om zijn moeder huilde. Wat een man in Alexandrië precies zei. Hoe de lucht ruikt in de Malediven voor een storm. De naam van een hond in een dorp in Anatolië.',
    'En helemaal onderin, in een lap linnen, iets van brons met acht punten aan de kop, dat hij in een markt in Damascus had gekocht van een handelaar die zei dat het uit het westen kwam.',
    'Musa heeft die kist nooit aan iemand laten zien.',
    'Zijn dochter heeft hem geopend na zijn dood, en zijn kleinzoon heeft er een kaars bij aangestoken en zes bladzijden gelezen en toen is hij gaan huilen, en dat is hoe het verder is gegaan.',
    'Van de Rihla bestaan tientallen handschriften. Het is in tientallen talen vertaald. Er wordt nog steeds over geruzied door geleerden, omdat sommige stukken verdacht veel lijken op reisverslagen van anderen.',
    'Van de vijfde kist is nooit iets teruggevonden.',
    'Alleen de sleutel.',
  ] },
]
