import type { Hoofdstuk } from './sleutels'

/** Deel 5 — De wereld op één vel. Ceuta en Palermo, 1154. */
export const DEEL5_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Inkt', tekst: [
    'Sanaa was veertien en ze kon inkt maken die niet verbleekte, en dat was in haar familie het enige wat telde.',
    'Haar vader tekende kaarten. Niet de grote kaarten waar geleerden over praten — zeekaarten voor kapiteins, met kusten en diepten en de plekken waar je niet moest komen. Die verkocht hij in de haven van Ceuta voor geld waar ze net van konden leven.',
    'Sanaa maakte zijn inkt. Roet, gom, water, en iets wat haar grootmoeder eraan had toegevoegd en wat ze aan niemand vertelden.',
    'Ze tekende ook. Stiekem, op de achterkant van mislukte vellen.',
    'Op een middag in het voorjaar stond er een man in de werkplaats die daar niet hoorde.',
    'Hij was oud en hij was goed gekleed en hij pakte een van haar vaders kaarten op zonder te vragen.',
    '“Deze kust klopt niet,” zei hij.',
    'Haar vader kwam overeind. “Die kust vaar ik al twintig jaar.”',
    '“U vaart hem. U meet hem niet.” De man legde de kaart neer. “Er zit een bocht in die er niet is. Ik weet het, want ik ben er geweest en ik heb geteld hoeveel dagen.”',
    'Het bleef even stil, en Sanaa dacht dat haar vader hem eruit zou gooien.',
    'In plaats daarvan zei hij: “Laat zien.”',
  ] },
  { nummer: 2, titel: 'De man die overal was geweest', tekst: [
    'Hij heette Muhammad al-Idrisi en hij was in Ceuta geboren, en hij was sindsdien overal geweest waar je met een schip of een kameel kunt komen.',
    'Hij bleef drie dagen. Op de derde dag zat Sanaa op de grond bij de deur te luisteren terwijl hij aan haar vader uitlegde waar hij mee bezig was.',
    'Een kaart van de hele wereld.',
    'Niet een kust of een zee. Alles. Van de oceaan in het westen tot waar de zijde vandaan komt. Zeventig bladen, en een boek erbij waarin per streek stond wat er groeide, wie er woonde en hoe ver het was naar de volgende stad.',
    '“Voor wie?” vroeg haar vader.',
    '“Voor de koning van Sicilië.”',
    'Haar vader zei een tijdje niets.',
    '“Die is christen.”',
    '“Die is christen,” zei al-Idrisi. “En hij betaalt voor vijftien jaar werk, en hij laat mij kiezen wie eraan meewerkt, en aan zijn hof zitten mensen uit Alexandrië en uit Córdoba en uit Athene in dezelfde zaal.”',
    'Hij schonk zichzelf water in.',
    '“Ik heb mannen naar plekken gestuurd om ze na te meten. Niet om er iets te halen. Alleen om te kijken en terug te komen en te vertellen. Weet u hoeveel koningen daar geld aan uitgeven?”',
    'Hij hield een vinger omhoog.',
    '“Eén.”',
  ] },
  { nummer: 3, titel: 'Palermo', tekst: [
    'Ze gingen mee. Haar vader voor het werk, Sanaa omdat haar vader de inkt niet zonder haar kon maken en dat allebei wisten zonder het uit te spreken.',
    'Palermo rook naar citroen.',
    'Dat was het eerste wat ze schreef in het schrift dat ze bijhield: *het ruikt hier naar citroen en naar vis en er zijn hier drie soorten kerkklokken en de oproep tot gebed, allemaal op dezelfde ochtend.*',
    'Ze had niet geweten dat dat kon.',
    'In de werkkamers van het paleis werkten dertig mensen aan de kaart. Er werd Arabisch gesproken en Grieks en Latijn en iets wat het midden hield tussen alle drie. Er waren dagen dat er ruzie was over één kustlijn en dat er drie mannen stonden te schreeuwen in drie talen tegelijk.',
    'Sanaa maakte inkt. Kilo’s inkt.',
    'En op een avond, toen iedereen weg was, ging ze staan bij de grote tafel waar de bladen naast elkaar lagen.',
    'Ze zag voor het eerst de hele wereld.',
    'Het zuiden stond boven. Zo tekenden ze het toen. Afrika lag bovenaan het vel en Europa hing eronder, klein en rommelig, en helemaal onderaan lagen landen waar sneeuw viel.',
    'Ze zocht Ceuta.',
    'Het was een stip. Kleiner dan haar nagel.',
  ] },
  { nummer: 4, titel: 'Wat een kaart doet', tekst: [
    'Het jaar erna begreep ze waarom een kaart gevaarlijk is.',
    'Er kwamen mannen op bezoek die geen geleerden waren. Ze keken lang naar de bladen en ze stelden vragen die niets met kennis te maken hadden.',
    '“Hoeveel dagen van hier naar daar?”',
    '“Waar is de haven diep genoeg?”',
    '“Hoeveel mensen wonen daar?”',
    'Sanaa hoorde het aan terwijl ze inkt stond te roeren, en ’s avonds zei ze het tegen haar vader.',
    '“Ze willen weten waar ze kunnen landen.”',
    'Haar vader roerde door.',
    '“Ja.”',
    '“En dat maken wij voor ze.”',
    '“Ja.”',
    'Hij legde de stok neer.',
    '“Sanaa. Een kaart is een mes. Je kunt er brood mee snijden en je kunt er iemand mee doodsteken, en het mes weet het verschil niet.” Hij keek haar aan. “De man die het mes smeedt ook niet. Die maakt het zo goed als hij kan.”',
    '“Is dat genoeg?”',
    '“Nee,” zei haar vader. “Maar het is wat we hebben.”',
    'Ze heeft daar haar hele leven over nagedacht en ze is er nooit uitgekomen.',
  ] },
  { nummer: 5, titel: 'De mannen die binnenkwamen', tekst: [
    'Er kwamen mannen binnen, en dat was het eigenlijke werk.',
    'Sanaa had gedacht dat je een kaart maakt door te reizen. Dat is wat iedereen denkt. Je gaat kijken, je komt terug, je tekent.',
    'Zo ging het niet.',
    'Al-Idrisi zat in een kamer in Palermo en er kwamen mannen bij hem.',
    'Zeekapiteins. Kooplieden. Pelgrims die terug waren uit Mekka. Soldaten die ergens gelegerd waren geweest en die het zich half herinnerden. Een monnik die in het noorden was geweest waar het ’s winters de hele dag donker is, wat niemand in de kamer geloofde.',
    'Ze kwamen binnen, ze kregen thee of wijn, afhankelijk van wie ze waren, en dan begonnen de vragen.',
    'En de vragen waren nooit: hoe was het.',
    'De vragen waren: hoeveel dagen van de haven tot de rivier. Ligt de berg links of rechts als je het noorden in het gezicht hebt. Is er zoet water op het eiland. Hoe heet het dorp — niet hoe noemen jullie het, hoe noemen zíj het.',
    'Sanaa zat erbij met de inkt en ze verveelde zich de eerste maanden dood.',
    'Toen begon ze het te zien.',
    'Er kwam een kapitein die zei dat de vaart van Tunis naar Palermo drie dagen was. Twee weken later kwam er een die zei vier.',
    'Al-Idrisi schreef ze allebei op.',
    '“Welke is goed?” vroeg Sanaa.',
    '“Dat weet ik nog niet.”',
    '“Waarom schrijf je ze dan allebei op?”',
    'Hij keek haar aan alsof ze eindelijk iets nuttigs had gezegd.',
    '“Omdat ik er nog zes nodig heb,” zei hij. “Als er dan vijf drie zeggen en drie vier, dan is het drie met een goede wind en vier met een slechte, en dan weet ik iets wat geen van die mannen wist.”',
    'Dat was de eerste keer dat Sanaa begreep wat er in die kamer gebeurde.',
    'Het was niet reizen. Het was tellen. Het was twintig mannen hetzelfde vragen en kijken waar ze het over eens waren, en de rest weggooien.',
    'Achthonderd jaar later heet dat wetenschap en doen ze het op universiteiten.',
    'Toen heette het: een man in een kamer met een jongen die inkt maalt.',
  ] },
  { nummer: 6, titel: 'Wat er in de inkt zit', tekst: [
    'Inkt maken is smerig werk en het duurt lang en het gaat vaak mis.',
    'Sanaa kon het op haar veertiende beter dan haar vader, en dat wisten ze allebei en geen van beiden zei het.',
    'Je hebt galnoten nodig. Dat zijn geen noten maar bolletjes die aan een eik groeien omdat een wesp er een ei in heeft gelegd — dat is waar, dat is hoe het werkt, en Sanaa heeft het jaren niet geloofd tot ze er zelf een openbrak.',
    'Die stamp je fijn. Je laat ze weken in water staan tot het bruin is en zuur ruikt. Dan gaat er ijzer bij, en gom, en dan wacht je nog een keer.',
    'Als het goed is, is het eerst lichtbruin op het perkament en wordt het daarna zwart. Dat kan dagen duren. Je schrijft iets en het is de volgende ochtend donkerder dan toen je het neerzette.',
    'Sanaa vond dat het mooiste wat er bestond.',
    '“Hij groeit,” zei ze tegen haar vader toen ze klein was.',
    '“Hij droogt.”',
    '“Nee. Hij groeit.”',
    'Haar vader had toen gelachen en later heeft hij het zelf ook zo gezegd, tegen klanten, alsof hij het had bedacht.',
    'Te veel ijzer en je inkt vreet na honderd jaar een gat in het perkament waar hij op staat. Dat is geen theorie; dat is waarom er in bibliotheken bladzijden liggen waar de letters doorheen gevallen zijn.',
    'Te weinig ijzer en hij wordt nooit echt zwart en verbleekt in een eeuw tot niets.',
    'Sanaa heeft haar hele leven inkt gemaakt die precies goed was, en ze heeft nooit iets geschreven wat bewaard is gebleven.',
    'Ergens ligt een blad van de Tabula Rogeriana waar de kustlijn van Noord-Afrika op staat, en die lijn is zwart geworden in een kamer in Palermo, in de dagen nadat een geleerde hem had getrokken, in inkt die door een meisje van veertien was gemaakt.',
    'Dat is een soort schrijven. Ze heeft het zo nooit genoemd.',
  ] },
  { nummer: 7, titel: 'Drie talen op één munt', tekst: [
    'Palermo was het vreemdste wat Sanaa ooit heeft gezien en ze is er zeven jaar gebleven.',
    'De koning was een christen uit het noorden, van mensen die honderd jaar eerder uit een land met sneeuw waren gekomen en het eiland op de moslims hadden veroverd.',
    'En toch.',
    'Zijn munten hadden Arabisch op de ene kant en Latijn op de andere. Zijn schrijvers werkten in drie talen: Arabisch, Grieks en Latijn, en een brief van het hof ging er soms in alle drie uit.',
    'Zijn lijfarts was een moslim. Zijn rekenmeesters waren moslims. In de haven stond een moskee en in de straat daarnaast een kerk en verderop een synagoge, en er waren dagen dat je ze alle drie tegelijk hoorde.',
    'Sanaa heeft dat in haar schrift geschreven, die ochtend met de klokken en de oproep door elkaar heen, en ze heeft het opgeschreven omdat ze dacht: dit gelooft thuis niemand.',
    'Ze had gelijk. Thuis geloofde niemand het.',
    'Toen ze op haar tweeëntwintigste terug was in Ceuta en het vertelde, keken mensen haar aan alsof ze een reisverhaal opsierde.',
    '“Een christelijke koning met Arabisch op zijn geld.”',
    '“Ja.”',
    '“Waarom zou hij dat doen?”',
    'En daar had ze het echte antwoord op, want ze was erbij geweest.',
    'Niet omdat hij van moslims hield. Niet omdat hij een goed mens was, al was hij dat misschien ook.',
    'Omdat de helft van zijn eiland moslim was, en omdat je een eiland niet bestuurt in een taal die de helft niet leest.',
    'Het was rekenwerk.',
    'Sanaa heeft daar iets uit gehaald wat ze nooit helemaal onder woorden kreeg, en wat in dit boek zo mag staan: het hoeft niet uit liefde te komen om goed uit te pakken. Mensen die naast elkaar moeten leven omdat het niet anders kan, vinden na twee generaties dat het normaal is.',
    'Het heeft op Sicilië ongeveer honderdvijftig jaar geduurd.',
    'Daarna is het misgegaan, en daarover staat verderop meer, want dat hoort er ook bij.',
  ] },
  { nummer: 8, titel: 'Zeventig bladen', tekst: [
    'De kaart werd niet één kaart. Dat was het slimme eraan en daar heeft Sanaa maanden over gedaan voordat ze het doorhad.',
    'Al-Idrisi deelde de wereld op.',
    'Van de evenaar naar het noorden zeven stroken, die hij klimaten noemde. En elke strook in tien stukken van west naar oost.',
    'Zeven maal tien is zeventig.',
    'Zeventig bladen perkament, en elk blad een stuk wereld, en als je ze allemaal naast elkaar legt heb je alles.',
    'Sanaa heeft ze nooit alle zeventig tegelijk gezien. Daar was in die kamer geen tafel voor, en trouwens ook geen vloer.',
    'Wat ze wel deed, elke keer als er een af was, was hem opzoeken op de plek waar zij vandaan kwam.',
    'Het derde klimaat. Het eerste stuk, helemaal links.',
    'Daar lag de zeestraat, en daar lag Ceuta, met een naam ernaast in de letters die zij las, op een blad dat in een paleis op Sicilië lag en dat straks door mensen in Egypte en Spanje en misschien nog verder zou worden gelezen.',
    'Ze heeft er een keer met haar vinger op gedrukt en meteen gekeken of ze een vlek had gemaakt.',
    'Ze had geen vlek gemaakt. Ze maakte goede inkt.',
    'Op dat blad staat ook de Atlas, en de weg naar het zuiden, en de plaatsen waar het goud vandaan komt — verder naar beneden dan iemand in Europa toen wist dat er nog wat was.',
    'En het zuiden staat boven.',
    'Dat heeft ze later aan mensen moeten uitleggen tot ze er moe van werd. Dat is geen fout en geen grap. Zo tekende je toen een kaart in de wereld waar zij vandaan kwam: met Mekka als het punt waar je je op richt, en de rest eromheen.',
    'Dat noorden boven staat is ook maar een afspraak. Iemand heeft hem gemaakt en iedereen is hem gaan volgen.',
    'Draai de Tabula Rogeriana om en je herkent de kust van Afrika meteen.',
  ] },
  { nummer: 9, titel: 'Wat ze over hem zeiden', tekst: [
    'Niet iedereen vond het mooi wat er in die kamer gebeurde.',
    'Sanaa hoorde het voor het eerst in de haven, van een koopman uit Tunis die niet wist wie ze was.',
    '“Die van Roger,” zei hij. “De geleerde die voor de christen werkt.”',
    'Hij zei het zoals je iets zegt wat vies is.',
    'Ze heeft er die avond haar vader naar gevraagd.',
    'Haar vader was lang stil.',
    '“Ze hebben niet helemaal ongelijk,” zei hij toen, wat het laatste was wat ze had verwacht.',
    '“Hoezo?”',
    '“Hij eet aan de tafel van een koning die deze stad op moslims heeft veroverd. Er zijn mensen die daarvoor gevochten hebben en verloren. Die vinden hem een verrader en dat is niet gek.”',
    '“En jij?”',
    'Haar vader draaide een perkament recht dat al recht lag.',
    '“Ik denk dat hij een boek maakt dat er zonder deze koning niet zou zijn,” zei hij. “Geen enkele vorst aan onze kant betaalt veertien jaar voor zeventig bladen. Dit was de enige plek waar het kon.”',
    '“Is dat genoeg?”',
    '“Dat is de vraag,” zei haar vader. “Dat is de hele vraag.”',
    'Aan de andere kant ging het net zo.',
    'Er waren mannen aan het hof, christenen, die vonden dat er te veel moslims op belangrijke plekken zaten. Die hielden hun mond zolang Roger leefde.',
    'Sanaa heeft in die zeven jaar geleerd hoe dat voelt: dat je aan twee kanten degene bent die er niet helemaal bij hoort.',
    'Ze was daar veertien jaar oud te jong voor en ze heeft het toch geleerd.',
    'En ze heeft, veel later, in Ceuta, haar dochter iets meegegeven wat ze zelf nooit had horen zeggen: dat je soms moet kiezen tussen gelijk hebben en iets afmaken, en dat allebei verdedigbaar is, en dat mensen die het ene kiezen altijd neerkijken op mensen die het andere kozen.',
  ] },
  { nummer: 10, titel: 'De man die de bocht wegnam', tekst: [
    'Het mooiste wat Sanaa heeft meegemaakt, duurde een halve dag en er was verder niemand bij.',
    'Er lag een oude kaart in de kamer. Grieks, heel oud, overgeschreven en nog eens overgeschreven, met de kust van Noord-Afrika erop.',
    'En die kust had een bocht.',
    'Een dikke bocht naar het noorden, halverwege, alsof het land daar een buik had.',
    'Al-Idrisi had er twee jaar niets mee gedaan. Hij had hem overgenomen zoals hij was, want hij stond op elke kaart die hij kende.',
    'Toen kwam er een kapitein binnen die twintig jaar op die kust had gevaren.',
    'De vragen gingen zoals altijd. Hoeveel dagen. Links of rechts. Zoet water.',
    'En ergens halverwege zei al-Idrisi: “En dan loopt de kust naar het noorden.”',
    'De kapitein keek hem aan.',
    '“Nee,” zei hij.',
    'Sanaa zat erbij met de inkt en herinnert zich dat er niets gebeurde. Geen uitroep, geen opspringen.',
    'Al-Idrisi vroeg het nog een keer, anders geformuleerd.',
    'De kapitein zei weer nee. De kust liep recht. Hij had er twintig jaar langs gevaren en hij was er nooit een buik tegengekomen.',
    'Toen liet al-Idrisi de oude kaart halen en legde hem voor de man neer.',
    'De kapitein keek ernaar en begon te lachen.',
    '“Wie heeft dat getekend?”',
    '“Iemand die er niet is geweest,” zei al-Idrisi.',
    'Die middag heeft Sanaa hem de bocht zien weghalen.',
    'Het was geen dramatisch werk. Hij tekende een nieuwe lijn, recht, met de afstanden van de kapitein erbij, en hij schreef in de marge waar het vandaan kwam.',
    'Achthonderd jaar stond die bocht op kaarten. Hij is er die middag af gegaan omdat een man die er wél was geweest zei dat hij er niet was.',
    'Sanaa heeft daar de rest van haar leven aan teruggedacht als aan de belangrijkste les die ze ooit heeft gekregen, en ze heeft hem zo doorverteld: geloof de man die er is geweest, ook als het in alle boeken anders staat.',
  ] },
  { nummer: 11, titel: 'Veertien jaar', tekst: [
    'Het duurde veertien jaar en dat is iets waar in verhalen altijd overheen gestapt wordt.',
    'Veertien jaar werk, en Sanaa was er zeven van mee: van veertien tot eenentwintig. Het is haar vader van sterk naar oud. Het is drie kamers, want ze zijn twee keer verhuisd, en twee keer de pest in de stad, en één keer een jaar waarin er bijna niet gewerkt werd omdat de koning oorlog voerde en niemand aan kaarten dacht.',
    'Mensen vragen later altijd naar de dag dat het af was.',
    'Sanaa vond de dag dat het af was niet bijzonder. Ze vond dat de veertien jaar het bijzondere waren.',
    'Elke ochtend hetzelfde. De inkt. De kamer. De mannen die binnenkwamen. De vragen die nooit gingen over hoe het was, maar over hoeveel dagen.',
    'Er zijn drie mensen in die veertien jaar gestorven die aan het boek werkten. Een schrijver, een tekenaar en een oude man die de perkamenten sneed en van wie niemand de naam op het boek heeft gezet, zijzelf ook niet.',
    'Er is één blad drie keer opnieuw gedaan omdat er telkens iets niet klopte, en het derde was volgens al-Idrisi nog steeds niet goed.',
    'Er zijn honderden dagen geweest waarop er helemaal niets gebeurde behalve dat een man iets opschreef wat een ander hem vertelde.',
    'Zo wordt alles gemaakt wat er lang staat.',
    'Sanaa heeft dat haar hele leven tegen mensen gezegd die iets wilden beginnen, en niemand vond het een leuk antwoord.',
  ] },
  { nummer: 12, titel: 'Het zilveren vel', tekst: [
    'In 1154 was het af.',
    'Er werd ook een versie in zilver gemaakt: de hele wereld gegraveerd in een schijf van bijna vierhonderd pond, die in de zaal van de koning lag.',
    'Sanaa mocht erbij zijn toen hij werd neergelegd. Ze stond achteraan tussen mensen die belangrijker waren dan zij, en ze keek naar een wereld van zilver waar zij inkt voor had gemaakt.',
    'Koning Roger II stierf datzelfde jaar.',
    'De zilveren kaart is later omgesmolten. Door wie en wanneer weet niemand precies; in de onrust na zijn dood is het paleis geplunderd en dat ding was zijn gewicht in geld waard.',
    'Wat bleef, waren de bladen van perkament en het boek.',
    'Dat boek is vierhonderd jaar lang in Europa gebruikt door iedereen die iets over de wereld wilde weten, en de naam van de man die het schreef werd daar verbasterd tot iets wat hij zelf niet zou hebben herkend.',
    'Maar het was er. Het klopte. De kusten zaten op de goede plek, en de bocht die er niet was, was eruit.',
  ] },
  { nummer: 13, titel: 'Het gewicht op het perkament', tekst: [
    'De sleutel lag al die jaren op de tafel.',
    'Haar vader had hem gekregen van een metselaar in Fes toen Sanaa klein was, in ruil voor een kaart. Hij gebruikte hem als gewicht: perkament rolt op, en je hebt iets nodig dat zwaar genoeg is en dat je inkt niet vlekt.',
    'Acht punten aan de kop. Een ster.',
    'Toen ze terugvoeren naar Ceuta — haar vader oud, zijzelf tweeëntwintig en getrouwd met een man uit Palermo die mee wilde — zat hij in de kist met het gereedschap.',
    'Sanaa heeft nooit kaarten getekend. Vrouwen deden dat niet, en ze had het ook niet doorgezet toen ze het had gekund.',
    'Ze heeft wel inkt gemaakt. Haar leven lang, voor iedereen die erom vroeg, en ze heeft het recept aan haar dochter geleerd en die aan de hare.',
    'En ze heeft dat schrift bewaard waarin stond dat het in Palermo naar citroen rook en dat er op dezelfde ochtend drie soorten klokken en de oproep tot gebed klonken.',
    'Van al haar spullen is dat het enige dat bewaard is gebleven, en het is er nu ook niet meer.',
    'De sleutel wel.',
  ] },
]
