import type { Hoofdstuk } from './sleutels'

/**
 * Deel 2 — De overkant. Tanger en de zeestraat, 711.
 *
 * Hier komt het nieuwe geloof de reeks binnen, en het komt binnen zoals het
 * werkelijk kwam: met soldaten, met kooplieden, met mensen die het pas net
 * zelf hadden. Ayyur ziet het van dichtbij en snapt de helft — wat precies
 * klopt, want zo zag het er voor de meeste Amazigh in die jaren uit.
 */
export const DEEL2_HOOFDSTUKKEN: Hoofdstuk[] = [
  {
    nummer: 1,
    titel: 'De jongen bij de paarden',
    tekst: [
      'Ayyur was twaalf en hij was goed in twee dingen: paarden en wachten.',
      'Het tweede had hij van zijn vader geleerd, die schapen hoedde in de heuvels achter Tanger en die kon zwijgen van zonsopgang tot zonsondergang zonder dat het hem iets deed. Het eerste had hij van niemand. Paarden vonden hem gewoon aardig, en dat was al zo sinds hij kon lopen.',
      'Daarom stond hij nu in het kamp buiten de stadsmuur en niet in de heuvels.',
      'Zijn vader had in de winter dertig schapen verloren aan de kou en de rest aan de schuld. Er was geen kudde meer om te hoeden. Er was wel een leger, en een leger heeft paarden, en paarden hebben iemand nodig die er ’s nachts bij blijft.',
      'Ze betaalden in eten en in koper. Niet veel koper.',
      'Ayyur klaagde er niet over. Hij mocht bij de paarden slapen en hij kende inmiddels alle zevenenveertig bij naam, ook de namen die hij zelf verzonnen had omdat niemand hem ze had verteld.',
      'Het kamp was in die weken van maart voller geworden dan hij ooit had gezien. Eerst honderd man, toen vijfhonderd, toen zoveel dat tellen niet meer ging. Ze kwamen uit het zuiden en uit het oosten, uit de bergen en van de kust. De meesten waren Amazigh zoals hij. Ze spraken zijn taal, met andere woorden voor dezelfde dingen, en ze lachten om hoe hij het zei.',
      'Er waren er ook die Arabisch spraken. Niet veel. Een paar honderd.',
      'En iedereen wachtte.',
      'Waarop wisten ze wel: op schepen. Waarvoor de schepen waren, daar werd over gepraat op de manier waarop mannen over iets praten dat ze niet zeker weten — heel stellig, en elke dag anders.',
      '“De overkant,” zei de een.',
      '“Er is niets aan de overkant,” zei de ander. “Water en dan nog meer water.”',
      '“Er is een koning aan de overkant,” zei een derde. “Met een kroon van goud zo zwaar dat hij hem niet kan dragen.”',
      'Ayyur borstelde de flank van een merrie die hij Tafukt noemde, wat zon betekent, en luisterde naar alle drie.',
      'Hij had de overkant gezien. Iedereen in Tanger had de overkant gezien. Op een heldere dag lag er een streep land aan de horizon, met daarboven een rots die eruitzag alsof iemand hem daar had neergezet.',
      'Je kon er kijken zonder er ooit over na te denken, je hele leven lang.',
      'Tot iemand schepen begon te verzamelen.',
    ],
  },
  {
    nummer: 2,
    titel: 'De man die niet groot was',
    tekst: [
      'Hij zag Tariq voor het eerst op een dinsdag, bij de paarden, en hij wist een halve minuut lang niet wie hij voor zich had.',
      'De man was niet groot. Dat was het eerste.',
      'Ayyur had zich iemand voorgesteld als de verhalen: een kop boven iedereen uit, een mantel die achter hem aan sleepte, tien man eromheen. Deze man stond alleen, in een stoffige jas zonder versiering, en hij stond naar Tafukt te kijken zoals iemand naar een paard kijkt die verstand van paarden heeft.',
      '“Wie rijdt op deze?” vroeg hij.',
      '“Niemand,” zei Ayyur. “Ze laat niemand op zich zitten.”',
      '“Waarom niet?”',
      '“Weet ik niet. Ze is een keer gevallen, denk ik. Voordat ze hier kwam.”',
      'De man legde zijn hand op de hals van de merrie en liet hem daar liggen zonder te aaien.',
      '“En bij jou?”',
      '“Bij mij is ze rustig.”',
      '“Dan is ze niet bang voor mensen,” zei de man. “Dan is ze bang voor wat mensen met haar deden.”',
      'Hij keek Ayyur aan voor het eerst.',
      '“Hoe heet je?”',
      '“Ayyur.”',
      '“De maan.” De man knikte, alsof dat een redelijke naam was. “Zorg dat ze er over twee weken nog zo bij staat.”',
      'Toen liep hij weg.',
      'Het duurde tot de avond voordat iemand het Ayyur vertelde, en toen hij het hoorde ging hij op een kist zitten en bleef daar een tijdje zitten.',
      'Tariq ibn Ziyad. Amazigh, zoals hij. Uit een familie die niemand kende. Gouverneur van Tanger, en de man die het leger dat hier op het strand lag over het water moest zetten.',
      'Hij had naar een paard staan kijken.',
      '“Hij komt elke dag,” zei Sa3id, de oude ruiter met het slechte been, die inmiddels naast hem was komen zitten omdat hij altijd naast iemand kwam zitten. “Elke dag bij de paarden en elke dag bij de schepen. Hij slaapt niet, geloof ik.”',
      '“Hij is niet groot,” zei Ayyur.',
      'Sa3id lachte zo hard dat hij moest hoesten.',
      '“Nee, jongen,” zei hij. “Dat is hij niet.”',
    ],
  },
  {
    nummer: 3,
    titel: 'Vier schepen voor zevenduizend man',
    tekst: [
      'Het probleem was eenvoudig en niemand kon het oplossen.',
      'Er lagen zevenduizend man op dat strand, plus paarden, plus wapens, plus eten voor weken. En er waren vier schepen.',
      'Ayyur hoorde Sa3id een keer uitrekenen hoeveel keer die vier schepen dan heen en weer moesten, en Sa3id kwam op een getal waar hij zelf om moest lachen, en daarna werd hij stil.',
      '“Wat is er?” vroeg Ayyur.',
      '“Niets.”',
      '“Sa3id.”',
      'De oude man wreef over zijn knie, wat hij deed als hij nadacht.',
      '“Als je vier schepen hebt,” zei hij, “dan is de eerste lading het gevaarlijkst. Die staat aan de overkant, alleen, met niemand achter zich. En als er iets misgaat, zijn de schepen twee dagen weg.”',
      'Hij keek naar de zee.',
      '“Ik zou niet in de eerste lading willen zitten.”',
      'De schepen waren niet van hen. Dat wist het hele kamp. Ze kwamen van een man aan de overkant, een heer van Ceuta die ruzie had met zijn eigen koning en die daarom hielp. Zijn naam werd op tien manieren uitgesproken en niemand had hem ooit gezien.',
      '“Waarom helpt hij?” vroeg Ayyur.',
      '“Omdat hij iets wil.”',
      '“Wat dan?”',
      '“Dat weten we pas als we het hebben gegeven,” zei Sa3id.',
      'In die weken leerde Ayyur meer over oorlog dan hij ooit had willen weten, en bijna niets ervan ging over vechten. Het ging over water in vaten dat na vier dagen bedierf. Over hoeveel gerst een paard per dag eet en hoeveel dat is voor zevenhonderd paarden. Over mannen die ziek werden van het wachten en ruzie kregen over niets.',
      'Op een ochtend was er een vechtpartij bij de put. Twee mannen uit verschillende stammen, om een emmer.',
      'Tariq kwam zelf. Hij liet ze allebei opstaan, hij sprak zacht met ze, en hij stuurde ze samen weg met dezelfde opdracht: één emmer, twee man, de hele dag water dragen voor de paarden.',
      '’s Avonds zaten ze naast elkaar te eten.',
      'Sa3id zag Ayyur kijken.',
      '“Dát is het,” zei hij. “Dát is waarom ze met hem meegaan. Niet omdat hij kan vechten. Ze kunnen allemaal vechten.”',
    ],
  },
  {
    nummer: 4,
    titel: 'De nacht ervoor',
    tekst: [
      'De avond voor de eerste overtocht was warm en er stond geen wind, en dat laatste was precies het probleem.',
      'Ayyur kon niet slapen. Hij lag tussen de paarden, met zijn hoofd op een zadel dat naar leer en zweet rook, en hij keek naar de sterren die tussen de tentdoeken door te zien waren.',
      'Naast hem lag Sa3id, en die sliep ook niet.',
      '“Ben je bang?” vroeg Ayyur.',
      '“Ja,” zei Sa3id meteen.',
      'Dat had Ayyur niet verwacht. Hij had verwacht dat de oude man zou lachen en iets zou zeggen over dat hij al in twintig veldslagen had gestaan.',
      '“Iedereen die zegt van niet, liegt,” zei Sa3id. “Of hij is dom. Aan domme mannen heb je niets in een boot.”',
      'Hij ging rechtop zitten, langzaam, met zijn hand op zijn knie.',
      '“Weet je wat ik doe als ik bang ben?”',
      '“Nee.”',
      '“Ik zeg de naam van God en dan doe ik het volgende ding dat gedaan moet worden. Niet het hele ding. Het volgende ding.”',
      'Ayyur dacht daarover na.',
      'Het geloof was in zijn dorp iets van de laatste jaren. Zijn grootmoeder had het niet, zijn moeder half, zijn vader helemaal — op zijn eigen manier, stil, zonder er veel over te zeggen. In het kamp was het overal: mannen die stopten met waar ze mee bezig waren en zich in dezelfde richting draaiden, en daarna weer verder gingen alsof er niets gebeurd was.',
      'Hij had het nooit zo goed begrepen. Niemand had het hem uitgelegd. Ze deden het gewoon, en hij stond erbij met een borstel in zijn hand.',
      '“Sa3id,” zei hij. “Ik weet niet hoe het moet.”',
      'De oude man keek hem aan in het donker.',
      '“Wat weet je niet?”',
      '“Alles. De woorden. Wanneer. Hoe je staat.”',
      'Sa3id zweeg lang genoeg om Ayyur ongemakkelijk te maken.',
      '“Morgenochtend,” zei hij toen, “ga je naast mij staan. Je doet wat ik doe. Je hoeft niets te zeggen wat je niet weet.”',
      '“Is dat genoeg?”',
      '“Voor vanochtend wel,” zei Sa3id. “De rest leer je van iemand die er meer verstand van heeft dan ik. Ik ben maar een ruiter met een kapotte knie.”',
      'Hij ging weer liggen.',
      '“Slaap nu. Morgen wordt lang.”',
    ],
  },
  {
    nummer: 5,
    titel: 'Het strand bij zonsopgang',
    tekst: [
      'Ze gingen in het donker naar het water, en toen het licht werd stond het hele strand vol.',
      'Ayyur had nog nooit zoveel mensen tegelijk stil gezien.',
      'Ze stonden in rijen, schouder aan schouder, van de duinen tot aan de vloedlijn. Mannen die elkaar niet verstonden omdat ze uit dorpen kwamen die tien dagreizen uit elkaar lagen, in dezelfde richting, in dezelfde volgorde.',
      'Hij stond naast Sa3id en deed wat Sa3id deed, en hij voelde zich de eerste drie tellen belachelijk en daarna niet meer.',
      'De zee lag er die ochtend bij als een meer.',
      'Toen het afgelopen was, bleef het nog even stil. Daarna begon iedereen tegelijk te praten en werd het weer een kamp.',
      'Ayyur bracht acht paarden naar de vloedlijn. Dat was zijn opdracht: acht, in de eerste lading, met Sa3id erbij als ze aan de overkant waren.',
      'Tafukt was er een van.',
      'Paarden en boten gaan niet samen. Dat wist hij, en die ochtend leerde hij hoe erg het is. Ze moesten de dieren over een plank de boot in krijgen, en de plank bewoog, en de boot bewoog anders dan de plank.',
      'Twee paarden weigerden. Een derde raakte in paniek halverwege en sloeg een man tegen de grond.',
      'Tafukt liep achter Ayyur aan de plank op alsof het een pad in de heuvels was.',
      'Hij hield haar hoofd vast toen ze eenmaal binnen was, en hij praatte tegen haar in zijn eigen taal over dingen die nergens over gingen: over zijn vader, over de kudde die er niet meer was, over de naam die hij haar gegeven had en waarom.',
      'Iemand sloeg hem op zijn schouder.',
      'Hij keek op.',
      'Tariq stond in de boot, tussen de paarden, met zijn hand op de rand.',
      '“Blijf bij haar praten,” zei hij. “De hele overtocht. Hou niet op.”',
      '“Ja,” zei Ayyur.',
      'Tariq keek naar de plank, waar de vierde en vijfde nog moesten.',
      '“En Ayyur,” zei hij, zonder om te kijken. “Als het misgaat op het water, snij je haar los. Niet vasthouden. Een paard kan zwemmen. Een jongen met een touw om zijn arm niet.”',
    ],
  },
  {
    nummer: 6,
    titel: 'Water',
    tekst: [
      'De zeestraat is op zijn smalst veertien kilometer.',
      'Ayyur wist dat niet. Hij wist alleen dat het strand achter hem kleiner werd en dat er een uur voorbijging waarin er niets gebeurde, en daarna nog een uur.',
      'Het ging niet mis. Dat was het vreemde.',
      'Hij had zich alles voorgesteld: golven, schreeuwen, water over de rand. In plaats daarvan was er de zon, het geluid van riemen, en een deining die precies genoeg was om iedereen die niet gewend was aan boten over de reling te laten hangen.',
      'Hij praatte tegen Tafukt tot zijn stem hees werd.',
      'Tussendoor keek hij om.',
      'Achter hen lag de kust waar hij geboren was: de heuvels waar de schapen hadden gelopen, de stad met de muur, het punt waar zijn vader nu waarschijnlijk zat te kijken zonder iets te zeggen.',
      'Hij had geen afscheid genomen. Niet echt. Hij had gezegd dat hij over een maand terug zou zijn, en zijn vader had geknikt, en ze hadden allebei gedaan alsof dat een zin was die iets betekende.',
      'Voor hem uit werd de rots groter.',
      'Die was anders dan hij eruitzag vanaf Tanger. Van veraf leek het een driehoek. Van dichtbij was het een muur van steen die recht uit het water omhoogkwam, grijs en kaal, met meeuwen die eromheen dreven als stof.',
      'Er zat niemand op. Er stond niets op. Het was gewoon een rots.',
      'Naast hem zei Sa3id iets.',
      '“Wat?”',
      '“Ik zei: kijk goed.” De oude man leunde met zijn armen op de rand. “Over honderd jaar vraagt iemand je kleinzoon waar zijn familie vandaan komt, en dan zegt hij de naam van dit ding.”',
      '“Het heeft geen naam.”',
      'Sa3id grijnsde met zijn scheve gebit.',
      '“Nog niet,” zei hij.',
      'De boten kwamen aan land op een strand aan de voet van de rots. Er was niemand. Geen leger, geen wachtpost, geen dorp. Alleen kiezels, wier en het geluid van de zee.',
      'Zevenhonderd man en tweeënzestig paarden stonden op een vreemde kust, en de schepen keerden meteen om voor de volgende lading.',
      'Twee dagen alleen, had Sa3id gezegd.',
      'Ayyur bracht de paarden hogerop, naar het gras achter de kiezels, en begon een lijn te trekken in het zand voor de omheining. Het volgende ding dat gedaan moest worden.',
      'Achter hem klom Tariq de eerste helling op om te kijken hoe het land eruitzag.',
    ],
  },
  {
    nummer: 7,
    titel: 'De berg van Tariq',
    tekst: [
      'In de derde week kreeg de rots zijn naam, en Ayyur was erbij toen het gebeurde, al wist hij dat op dat moment niet.',
      'Er was toen al een kamp. Er waren omheiningen, er was een put die ze hadden uitgegraven, er stonden tenten in rijen. Er waren vier ladingen aangekomen en er zouden er nog meer komen.',
      'Een schrijver zat op een steen met een tablet op zijn knieën, en hij vroeg aan de man naast hem hoe hij de plaats moest opschrijven.',
      '“Welke plaats?”',
      '“Deze. Waar we zijn. Ik moet opschrijven waar het leger is.”',
      'De man haalde zijn schouders op.',
      '“Bij de berg,” zei hij.',
      '“Welke berg?”',
      'Ze keken allebei omhoog.',
      '“De berg van Tariq,” zei de man, en hij zei het zoals je iets zegt wat voor de hand ligt.',
      'De schrijver schreef het op. Jabal Tariq.',
      'Ayyur stond twee passen verderop met een emmer in zijn hand en hoorde het, en dacht: goed, en liep door.',
      'Zo gaan die dingen. Er is nooit iemand bij die denkt: dit is het moment.',
      'Later in de zomer trok het leger noordwaarts en kwam het bij een rivier tegenover een koning met een kroon die inderdaad bestond, en wat daar gebeurde heeft de geschiedenis van twee landen veranderd. Maar dat is een ander verhaal, en Ayyur was er niet bij. Hij bleef bij de paarden aan de kust, zoals hem gezegd was, en hoorde het pas weken later.',
      'Wat hij wel meemaakte was dit.',
      'Op een avond kwam er een schrijver het kamp door met een kist onder zijn arm, op zoek naar iemand die met paarden kon rijden en de weg wist langs de kust. Sa3id wees naar Ayyur.',
      'De kist moest naar het noorden. Er zaten tabletten in, en brieven, en een leren zak met kleine dingen die soldaten hadden ingeleverd omdat ze ze niet wilden verliezen.',
      'Ayyur laadde de kist op Tafukt.',
      'Bij het vastsjorren viel de zak om en er rolde iets uit op de grond.',
      'Het was van brons, zo lang als zijn hand, en er zat een kop aan met acht punten. Als een ster.',
      '“Wat is dat?” vroeg hij.',
      'De schrijver keek er nauwelijks naar.',
      '“Een sleutel,” zei hij. “Die zat al in de zak toen ik hem kreeg. Niemand weet van wie.”',
      'Ayyur hield hem even in zijn hand. Hij was warm van de zon.',
      'Toen liet hij hem terugglijden in de zak, trok de riem aan, en klom op.',
    ],
  },
]
