import type { Hoofdstuk } from './sleutels'

/** Deel 10 — De stad aan zee. Essaouira, vanaf 1764. */
export const DEEL10_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Wind', tekst: [
    'Er staat daar altijd wind.',
    'Dat is geen manier van zeggen. Aan die kust waait het driehonderd dagen per jaar uit het noordwesten, en de mensen die er woonden wisten niet beter.',
    'Yto was dertien en ze hielp haar vader met de netten, en haar leven bestond uit vis, zand, wind, en een dorp van veertig huizen achter de duinen.',
    'Er was een fort. Een oud Portugees fort, half ingestort, waar niemand meer in kwam behalve de meeuwen.',
    'En er was een eiland voor de kust waar ze vroeger purperslakken vandaan haalden om stof mee te verven, duizend jaar geleden, in de tijd van de Romeinen.',
    'Verder was er niets.',
    'In de zomer dat Yto dertien werd, kwamen er schepen die niet kwamen vissen.',
  ] },
  { nummer: 2, titel: 'Het eiland', tekst: [
    'Voor de kust ligt een eiland en Yto is er twee keer geweest, en allebei de keren mocht het niet.',
    'Het is niet groot. Je kunt er in een uur omheen lopen. Er staat niets op behalve meeuwen en een paar ruïnes waar niemand naar omkeek.',
    'Haar vader had haar verteld wat die ruïnes waren, zoals zijn vader het hem had verteld.',
    'Lang geleden — zó lang dat er geen getal bij hoort in een vissersdorp — kwamen hier mensen die slakken van de rotsen haalden.',
    'Niet om te eten. Om te verven.',
    'In die slak zit een druppel vocht die in de zon paars wordt. Niet lichtpaars. Het diepste paars dat er bestaat, en het gaat er nooit meer uit.',
    'Je hebt er duizenden slakken voor nodig voor één kledingstuk.',
    'Daarom was die kleur zo duur dat alleen keizers hem droegen, en daarom heette het keizerspurper, en daarom stonden er op een eilandje voor de kust van Marokko bakken waar mannen slakken in kookten voor een stof die tweeduizend kilometer verderop om de schouders van iemand hing die hun naam niet kende.',
    'Yto heeft in die bakken gestaan toen ze veertien was.',
    'Ze zijn er met de boot van haar neef heen gegaan, wat verboden was, en ze heeft er scherven gevonden en een stuk steen met een gat erin.',
    'Wat ze zich herinnerde, was de stank.',
    'Na tweeduizend jaar. De rotsen daar ruiken nog steeds, en iedereen die er is geweest zegt hetzelfde.',
    'Ze heeft later, toen ze de boeken van de haven bijhield, vaak aan dat eiland gedacht.',
    'Want dat is waar deze plek altijd voor is gebruikt. Er komen mensen van ver, ze halen iets weg wat hier ligt, en ze varen het ergens anders heen waar het meer waard is.',
    'Eerst purper. Daarna suiker, amandelen, huiden, struisvogelveren en gom.',
    'De plek is hetzelfde gebleven. De lading verandert.',
  ] },
  { nummer: 3, titel: 'De man met de passer', tekst: [
    'Er stapten mannen aan wal die ze nog nooit had gezien: soldaten, en daarna mannen met rollen papier.',
    'Een van hen was geen Marokkaan. Dat zag je meteen.',
    'Hij was bleek, hij had het te warm, hij droeg schoenen die niet deugden in zand, en hij liep de hele dag met een passer en een lange ketting over het strand.',
    'Hij mat.',
    'Yto keek er drie dagen naar voordat ze dichterbij kwam.',
    '“Wat doet u?”',
    'Hij keek op. Hij sprak een soort Arabisch, slecht, maar te volgen.',
    '“Ik teken een stad.”',
    '“Hier is geen stad.”',
    '“Nee,” zei hij. “Daarom teken ik hem eerst.”',
    'Hij heette Théodore. Hij kwam uit Frankrijk en hij was ingenieur, en de sultan had hem laten komen om een havenstad te ontwerpen op deze plek.',
    '“Waarom hier?” vroeg Yto. “Het waait hier altijd.”',
    '“Daarom,” zei Théodore. “Wind is een haven waard. En er is diep water, en er is een eiland dat de golven breekt.”',
    'Hij draaide zijn papier om zodat ze het kon zien.',
    'Er stonden rechte lijnen op. Straten die elkaar kruisten in vierkanten. Een muur eromheen met torens op de hoeken.',
    'Yto had nog nooit een stad gezien die rechte straten had.',
  ] },
  { nummer: 4, titel: 'De ovens op het strand', tekst: [
    'Een stad bouwen waar niets is, begint met kalk, en kalk maak je zelf.',
    'Dat had Yto nooit geweten en ze heeft het van dichtbij gezien, want haar vader stookte een van de ovens.',
    'Je metselt een ronde oven op het strand. Je stapelt er schelpen en kalksteen in. Je stookt hem drie dagen en nachten aan één stuk door, zo heet dat je er op vijf passen afstand niet tegenaan kunt kijken.',
    'Wat eruit komt, valt uit elkaar als je er water bij doet, en het kookt daarbij — echt kookt, het borrelt en het brandt je handen.',
    'Meng het met zand en je hebt de specie waar een stad van aan elkaar zit.',
    'Er stonden er zeven op dat strand.',
    'Ze brandden drie jaar lang bijna onafgebroken, en ’s nachts zag je ze van kilometers ver, zeven oranje vlekken op een donkere kust.',
    'Yto’s vader is opgehouden met vissen. Dat is wat dit hoofdstuk eigenlijk vertelt.',
    'Hij was zesendertig, hij had zijn hele leven gevist zoals zijn vader, en toen kwam er werk waar drie keer zoveel voor betaald werd en dat het hele jaar door duurde.',
    'Hij heeft de boot verkocht in het tweede jaar.',
    'Yto heeft dat erger gevonden dan ze toen liet merken. Ze heeft er op haar veertigste nog over gepraat.',
    'Niet omdat het verkeerd was — het was niet verkeerd, ze aten er beter van — maar omdat er iets ophield dat al vier generaties duurde, op een middag, voor een goede reden.',
    'Zo gaat het altijd. Niemand kondigt het aan.',
  ] },
  { nummer: 5, titel: 'Rechte straten', tekst: [
    'Het vreemdste aan die stad, voor iedereen die uit Marokko kwam, waren de straten.',
    'Ze waren recht.',
    'In Fes, in Marrakech, in elke stad die gegroeid is, lopen de straten zoals mensen liepen. Ze buigen om een huis heen dat er eerder stond. Ze worden smal waar iemand een uitbouw maakte. Je kunt er verdwalen en dat hoort erbij.',
    'Hier had iemand eerst lijnen op papier gezet en daarna waren de huizen ertussen gekomen.',
    'Yto heeft Théodore daar een keer naar gevraagd, in het tweede jaar, toen ze hem beter kende.',
    '“Waarom recht?”',
    'Hij legde zijn passer neer.',
    '“Kanonnen,” zei hij.',
    'Dat was het hele antwoord en het duurde even voor ze het snapte.',
    'Een rechte straat kun je vanaf één punt overzien. Je kunt er soldaten doorheen sturen die aan het eind uitkomen waar je ze hebben wilt. Je kunt hem afsluiten met twee man.',
    'Een gegroeide stad kun je niet besturen zonder de mensen die er wonen. Een getekende stad wel.',
    'Yto vond dat als dertienjarige interessant en als veertigjarige iets anders.',
    'Want er zit een tweede kant aan, en die is er ook.',
    'In een rechte straat komt de wind erdoor en de zon erin. Het water loopt weg waar je het wilt hebben. Een kar kan overal komen. Een brand slaat niet over.',
    'De stad die ze bouwden was gezonder dan de stad waar Yto’s tante woonde, en dat is geen kleinigheid in een eeuw waarin de helft van de kinderen het niet haalt.',
    'Dat is het antwoord dat ze uiteindelijk zelf heeft gegeven, en het is geen mooi antwoord:',
    'Het is allebei waar. Iemand heeft die stad getekend om hem te kunnen beheersen, en het is er beter wonen dan waar hij vandaan kwam.',
  ] },
  { nummer: 6, titel: 'De stad op papier', tekst: [
    'Wat er toen gebeurde, ging sneller dan iemand had verwacht.',
    'De sultan — Mohammed ben Abdallah — wilde één haven waar alle handel met Europa doorheen ging, en hij wilde die kunnen overzien.',
    'Dus werd er gebouwd. Duizenden mannen. Steen uit de omgeving, hout uit de bergen, kalk uit ovens die ze op het strand bouwden.',
    'Yto’s vader werkte mee, want vissen leverde minder op dan stenen dragen.',
    'Binnen tien jaar stond er een stad waar veertig huizen hadden gestaan.',
    'En de sultan haalde er mensen naartoe.',
    'Kooplieden uit Fes en Marrakech. Europeanen met consulaten. En een grote joodse gemeenschap, die de handel met Europa deed en die in de stad een eigen wijk kreeg — de mellah — met synagogen en scholen.',
    'Op een markt in Essaouira hoorde je in die jaren Arabisch, Tamazight, Hebreeuws, Frans, Engels en Portugees op dezelfde ochtend.',
    'Yto heeft dat als kind normaal gevonden.',
    'Pas veel later, toen ze oud was en het anders was geworden, heeft ze begrepen dat het niet normaal was.',
  ] },
  { nummer: 7, titel: 'De mellah', tekst: [
    'Yto’s beste vriendin heette Esther en woonde vier straten verderop in de wijk waar de joodse families woonden.',
    'Zo’n wijk heette een mellah, en die waren er in bijna elke Marokkaanse stad.',
    'In Essaouira was hij groot. Op het hoogtepunt was bijna de helft van de stad joods, en dat was niet toevallig: de sultan had ze er met opzet naartoe gehaald.',
    'Dat zit zo.',
    'Hij wilde handel met Europa, en handel met Europa doe je met mensen die er familie hebben, de talen kennen en de gewoonten kennen. Dat waren in die jaren voor een groot deel joodse kooplieden, met neven in Livorno, in Amsterdam, in Londen, in Marseille.',
    'Er is toen een groep van een stuk of tien families uitgekozen die van de sultan het recht kregen om namens hem handel te drijven. Ze heetten de kooplieden van de sultan, en ze werden rijk, en de haven werd er rijk van.',
    'Yto heeft dat in de boeken zien staan voordat ze het begreep: namen die steeds terugkwamen bij de grootste ladingen.',
    'Esther was de dochter van een van die families, en ze kenden elkaar van de haven, waar ze allebei niets te zoeken hadden en allebei stonden te kijken.',
    'Yto heeft bij hen gegeten. Op een vrijdagavond, met kaarsen, en ze moest van tevoren van haar moeder beloven dat ze zich zou gedragen en achteraf vertellen hoe het was.',
    'Wat ze zich herinnerde: dat het zo ongeveer hetzelfde was.',
    'Ander eten, andere woorden, en verder een familie aan een tafel waar te veel tegelijk werd gepraat.',
    'Ze zijn hun hele leven bevriend gebleven.',
    'Van die gemeenschap is bijna niemand meer over. In de twintigste eeuw is vrijwel iedereen vertrokken, naar Israël, naar Frankrijk, naar Canada, om redenen die in het laatste deel van dit boek aan de orde komen.',
    'De synagogen staan er nog. Sommige zijn opgeknapt. De begraafplaats ligt er nog, op de wind, met de zee ernaast.',
    'Er komen elk jaar mensen uit Toronto en Parijs en Ashdod naar Essaouira om te zoeken naar het huis van hun overgrootmoeder.',
    'Dat hoort bij dit verhaal net zo goed als de kanonnen op de muur.',
  ] },
  { nummer: 8, titel: 'Wat een naam betekent', tekst: [
    'Over de naam is nooit iedereen het eens geworden.',
    'De meesten zeggen dat Essaouira "de kleine muur" betekent, of "de mooi getekende". Dat laatste past bij een stad die op papier is bedacht voordat hij bestond.',
    'De Europeanen noemden hem Mogador, en dat is waarschijnlijk een verbastering van de naam van een heilige die daar begraven ligt.',
    'Twee namen voor dezelfde stad, en dat is in Marokko eerder regel dan uitzondering.',
    'Yto leerde in die jaren lezen. Dat is het echte verhaal van dit deel.',
    'Ze leerde het van een klerk op de haven die haar in dienst nam om vangsten te noteren, omdat ze kon tellen en omdat hij een hekel had aan tellen.',
    'Binnen een jaar deed ze de boeken.',
    'Binnen drie jaar wist ze wat er in en uit ging, en wist ze meer over de handel van die haven dan de meeste mannen die er hun geld verdienden.',
  ] },
  { nummer: 9, titel: 'Cijfers', tekst: [
    'De klerk op de haven heette Abdeslam en hij had een hekel aan tellen, en dat is Yto’s hele carrière.',
    'Hij nam haar in dienst omdat ze op de kade stond en omdat hij haar een keer hardop de manden had horen tellen van een boot die binnenkwam, in het Tamazight, sneller dan hij het in het Arabisch kon.',
    '“Kun je schrijven?”',
    '“Nee.”',
    '“Wil je dat leren?”',
    'Zo simpel ging het. Ze was vijftien.',
    'Hij leerde haar cijfers eerst, want die had hij nodig, en letters pas daarna.',
    'Yto heeft dat later als de goede volgorde verdedigd tegenover iedereen die het met haar oneens was. Je leert een kind eerst waar hij iets aan heeft.',
    'De boeken van een haven zien er zo uit: per schip een regel. Waar het vandaan komt, wat erin zit, hoeveel, van wie, wat er aan recht betaald moet worden.',
    'Binnen drie jaar deed ze het alleen.',
    'Binnen vijf wist ze dingen die niemand anders wist, omdat niemand anders alle regels naast elkaar had gezien.',
    'Ze wist welke koopman elk jaar iets meer aangaf dan hij vervoerde en welke iets minder. Ze wist in welke maand de prijs van amandelen omhoogging en waarom. Ze wist welk schip in geen twee jaar was teruggekomen en dat er dus ergens een familie zat te wachten.',
    'Ze heeft daar nooit iets mee gedaan behalve haar werk.',
    'Dat is misschien wel het meest opvallende aan Yto, en het is de reden dat ze in dit boek staat: ze had jarenlang de sleutel tot alles wat er in die haven gebeurde, in een la, in haar eigen handschrift.',
    'En ze deed haar werk.',
  ] },
  { nummer: 10, titel: 'De storm van het zevende jaar', tekst: [
    'De wind die een haven waard was, heeft in het zevende jaar veertien mensen het leven gekost.',
    'Het begon op een middag in februari en het was de volgende ochtend nog niet afgelopen.',
    'Er lagen elf schepen in de baai. Drie hebben het niet gered.',
    'Yto was toen twintig en ze stond op de muur met de rest van de stad, en er was niets te doen behalve kijken, en dat is wat ze deden.',
    'Wat je in zo’n nacht leert over een plaats:',
    'Dat het eiland de golven breekt, maar niet allemaal.',
    'Dat een haven die op papier is getekend nog steeds aan een oceaan ligt.',
    'Dat een ingenieur uit Frankrijk met een passer en een ketting kan uitrekenen waar de muur moet staan, en dat de zee daar niet om vraagt.',
    'De volgende dagen heeft ze in de boeken geschreven wat er verloren was, en dat was het moment waarop ze begreep wat die boeken eigenlijk waren.',
    'Geen lijst met ladingen. Een lijst met mensen die ergens op wachtten.',
    'Ze heeft die winter de eerste brieven geschreven die ze niet hoefde te schrijven: aan families in Salé en in Agadir, om te melden wat er met hun schip was gebeurd.',
    'Abdeslam vond het onzin en heeft er niets van gezegd.',
    'Ze is er haar hele loopbaan mee doorgegaan.',
  ] },
  { nummer: 11, titel: 'Een schip naar het westen', tekst: [
    'Ze vond de sleutel in het zand.',
    'Dat is de eerlijke versie, en het is toevallig, en zo gaat het meestal.',
    'Hij lag bij de vloedlijn achter het nieuwe havenhoofd, tussen scherven en wier. Brons, groen uitgeslagen, met acht punten aan de kop.',
    'Ze maakte hem schoon met zand en azijn en legde hem op de tafel waar ze de boeken bijhield, als gewicht op de papieren tegen de wind.',
    'Jaren lag hij daar.',
    'In 1778 kwam er een schip dat alle klerken in de haven zich zijn blijven herinneren. Het voer onder een vlag die niemand kende: strepen en sterren.',
    'Het kwam uit een land dat twee jaar daarvoor had gezegd dat het een land was, en waar de meeste mensen in Essaouira nog nooit van hadden gehoord.',
    'De kapitein had papieren nodig en Yto maakte ze op.',
    'Toen hij weg was, was de sleutel er niet meer.',
    'Ze heeft nooit geweten of hij hem gepakt heeft of dat hij tussen de papieren mee de loopplank op is gegaan.',
    'Ze was er niet boos over. Ze vond het passen.',
  ] },
  { nummer: 12, titel: 'Wat ervan over is', tekst: [
    'Essaouira staat er nog, met dezelfde rechte straten die Théodore op papier zette.',
    'De muren staan er, de kanonnen staan er nog op de wallen, de blauwe boten liggen er nog in de haven. De stad staat op de Werelderfgoedlijst, en er komen mensen uit alle landen naar de plek waar Yto netten boette.',
    'De joodse wijk is er nog. De mensen grotendeels niet; die zijn in de twintigste eeuw vertrokken, naar Israël, naar Frankrijk, naar Canada.',
    'Er zijn in Essaouira nog steeds synagogen die worden onderhouden, en een begraafplaats aan zee, en families in Casablanca en in Parijs die zeggen: wij komen uit Mogador.',
    'Yto is negentig geworden.',
    'Ze heeft tot haar laatste jaar de boeken van de haven gedaan.',
    'En ze heeft haar kleindochters leren lezen, alle vijf, ook degenen die het niet wilden.',
  ] },
]
