import type { Hoofdstuk } from './sleutels'

/** Deel 7 — De jongen die twee namen kreeg. Fes en Rome, rond 1520. */
export const DEEL7_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Twee steden', tekst: [
    'Hassan was in Granada geboren en hij kon zich er niets van herinneren, en dat is een vreemde manier om ergens vandaan te komen.',
    'Zijn familie was vertrokken toen hij klein was, over zee naar Fes, met duizenden anderen. In Fes praatte zijn moeder over Granada alsof het een mens was dat gestorven was.',
    'Hij groeide op in een stad met boeken.',
    'Dat is niet overdreven. Er waren in Fes bibliotheken waar je niet meer uit kwam, er waren straten met alleen maar papiermakers, en er was de al-Qarawiyyin waar geleerd werd zoals dat al zeshonderd jaar gebeurde.',
    'Hij was goed. Iedereen zei dat hij goed was.',
    'Op zijn zestiende schreef hij al voor de rechtbank. Op zijn zeventiende ging hij voor het eerst mee met zijn oom, die gezant was — de man die namens de sultan naar andere hoven reisde en daar praatte namens iemand anders.',
    'Ze gingen naar Timboektoe, dwars door de woestijn.',
    'Ze gingen naar Egypte en naar Constantinopel.',
    'En Hassan schreef alles op, want dat was wat hij deed en wat hij het liefste deed.',
  ] },
  { nummer: 2, titel: 'De zee', tekst: [
    'Het gebeurde bij Djerba, op de terugweg.',
    'Ze waren met een klein schip en er kwam een groter schip, en dat is het hele verhaal. De Middellandse Zee zat in die jaren vol met kapers van alle kanten: christelijke uit Malta en Sicilië, islamitische uit Algiers en Salé. Iedereen kaapte iedereen.',
    'Hassan was eenentwintig.',
    'Ze namen hem mee naar Rhodos en van Rhodos naar Napels en van Napels naar Rome, en hij begreep onderweg dat hij geen gewone gevangene was.',
    'Een gezant die dertig steden had gezien en er een boek over kon schrijven, was iets waard.',
    'In Rome werd hij aan de paus gegeven.',
    'Niet verkocht. Gegeven, zoals je iets zeldzaams geeft aan iemand die het waardeert.',
    'De paus heette Leo. Hij was een Medici en hij verzamelde mensen die iets wisten.',
  ] },
  { nummer: 3, titel: 'Een nieuwe naam', tekst: [
    'Ze hielden hem een jaar in het Engelenburcht vast en behandelden hem goed, en dat is een zin die twee dingen tegelijk zegt.',
    'Hij kreeg boeken. Hij kreeg les in Italiaans en in Latijn. Er kwamen geleerden op bezoek die met hem wilden praten over Afrika, en hij praatte, want praten was beter dan niet praten.',
    'En na dat jaar werd hij gedoopt.',
    'Hij kreeg de naam van de paus: Johannes Leo de Medici.',
    'In Europa noemen ze hem sindsdien Leo Africanus. Leo de Afrikaan.',
    'Wat hij daarvan vond, weet niemand.',
    'Er staat niets over in wat hij geschreven heeft. Geen regel. Hij schrijft over steden en rivieren en over hoeveel mensen er in een dal wonen, en over wat hij zelf heeft meegemaakt schrijft hij bijna niets.',
    'Er is één plek waar iets doorschemert. In zijn boek vertelt hij een fabel over een vogel die zowel bij de vogels als bij de vissen hoorde, en die bij allebei aanklopte als het hem uitkwam.',
    'Hij schrijft erbij dat hij zelf die vogel is.',
    'Meer heeft hij er niet over gezegd.',
  ] },
  { nummer: 4, titel: 'Het boek', tekst: [
    'Hij schreef het in het Italiaans, dat hij pas net kende, en hij schreef het in drie jaar.',
    '*Della descrittione dell’Africa.* De beschrijving van Afrika.',
    'Het gaat over alles. De steden van Marokko, straat voor straat. Wat er op de markt ligt. Hoeveel een huis kost. Welke stammen waar wonen en wat ze eten en hoe ze hun kinderen noemen. De routes door de woestijn met het aantal dagen erbij.',
    'Het is geen reisverhaal. Het is een inventaris.',
    'Het werd in 1550 gedrukt, en daarna vertaald in het Latijn, het Frans, het Engels, het Nederlands.',
    'Driehonderd jaar lang was dit hét boek waaruit Europa wist wat er ten zuiden van de Middellandse Zee lag. Alles wat een Engelse of Nederlandse geleerde over Marokko dacht te weten, kwam uiteindelijk hiervandaan.',
    'Daar zit een ongemakkelijke kant aan, en die moet erbij.',
    'Toen Europa later schepen en legers naar Afrika stuurde, namen ze dat boek mee.',
    'Zijn vader had hem geleerd dat kennis een opdracht is. Niemand had hem geleerd wat je doet als iemand anders bepaalt wat er met die kennis gebeurt.',
  ] },
  { nummer: 5, titel: 'Terug over zee', tekst: [
    'In 1527 werd Rome geplunderd door een leger dat niemand had zien aankomen. De stad brandde, de paus zat opgesloten, en in de chaos verdween Hassan.',
    'De meeste geleerden denken dat hij naar Tunis is gegaan.',
    'Daarna wordt het stil. Er is een vermelding dat hij daar gestorven is, jaren later. Er is niets over hoe hij geleefd heeft.',
    'Men neemt aan — en meer dan aannemen is het niet — dat hij terugkeerde naar het geloof waarin hij was opgevoed.',
    'Dat is het einde van wat we weten.',
    'Wat een schrijver dan doet, is stoppen. Wat een verteller doet, is dit.',
  ] },
  { nummer: 6, titel: 'De band van het boek', tekst: [
    'In Rome liet hij één exemplaar van zijn boek inbinden voor zichzelf.',
    'Hij deed er iets in.',
    'Tussen het leer en het karton van de achterste band schoof hij iets plats van brons, zo lang als zijn hand, met acht punten aan de kop. Hij had het jaren geleden in Fes gekregen van een boekbinder, als betaling voor een brief die hij voor hem schreef.',
    'Waarom hij dat deed, staat er niet bij.',
    'Misschien omdat hij op dat moment twee namen had en geen van beide huizen, en omdat een mens dan iets wil hebben dat van vóór alles komt.',
    'Dat boek is met hem meegegaan over zee.',
    'Het is in Tunis in een bibliotheek terechtgekomen, en die bibliotheek is twee keer verhuisd en één keer half verbrand, en in de negentiende eeuw heeft een boekbinder de band opengesneden om hem te herstellen.',
    'Er viel iets uit.',
    'Hij legde het op zijn werkbank, keek ernaar, en stak het in zijn zak.',
  ] },
]
