import type { Hoofdstuk } from './sleutels'

/** Deel 8 — Drie koningen, één dag. Ksar el-Kebir, 4 augustus 1578. */
export const DEEL8_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'De trom', tekst: [
    'Driss was veertien en hij sloeg de trom, en dat betekent iets anders dan je denkt.',
    'Hij vocht niet. Hij had geen zwaard en hij zou er ook niet mee overweg kunnen. Zijn werk was: het leger laten weten wat het moest doen, met geluid, omdat een stem niet ver genoeg draagt en een vlag niet werkt als er stof hangt.',
    'Drie slagen kort: vooruit. Twee lang: stop. Een roffel: terug.',
    'Hij had het van zijn vader geleerd, die het van zijn vader had geleerd, en hij was er goed in.',
    'In juli van dat jaar lag het leger bij de rivier de Loukkos, en iedereen wist dat er iets ging gebeuren, want er kwam een vloot aan de kust die er niet hoorde.',
    'De Portugese koning was er zelf bij. Dat was het gekke.',
    'Koningen stuurden legers. Deze kwam mee.',
  ] },
  { nummer: 2, titel: 'Drie', tekst: [
    'Driss heeft het pas later helemaal begrepen, en dit is hoe het zat.',
    'Er waren twee mannen die allebei sultan van Marokko wilden zijn. De een, Abd al-Malik, zat op de troon. De ander, zijn neef Mohammed, was ervan afgezet en wilde hem terug.',
    'Die neef had hulp gezocht in Portugal.',
    'En de jonge Portugese koning Sebastiaan had ja gezegd. Hij was vierentwintig, hij was vroom, hij wilde een kruistocht, en zijn raadgevers hadden hem gesmeekt het niet te doen.',
    'Dus kwamen er drie koningen naar dezelfde vlakte: de zittende sultan, de afgezette sultan, en de koning van Portugal.',
    'Wat niemand wist, was dat Abd al-Malik stervende was.',
    'Hij was al weken ziek. Hij kon niet meer op een paard zitten. Ze droegen hem rond in een draagstoel en hij gaf zijn bevelen vanachter een gordijn, en zijn broer Ahmad stond ernaast.',
    'Dat hoorde Driss van een ruiter die het van een schrijver had.',
    'In een leger van dertigduizend man reist zo’n gerucht in een middag van voor naar achter.',
  ] },
  { nummer: 3, titel: 'De ochtend', tekst: [
    'De vierde augustus begon met bidden, zoals elke dag begon.',
    'Wat anders was, was de stilte daarna. Geen gepraat, geen ruzie bij het water. Mannen die hun spullen drie keer nakeken.',
    'Driss zat op een kar met de trom tussen zijn knieën en zijn handen waren nat.',
    'Naast hem zat Aziz, die de tweede trom sloeg en die zeventien was en die de hele ochtend niets zei.',
    '“Aziz.”',
    '“Wat.”',
    '“Ben jij bang?”',
    'Aziz keek naar de vlakte.',
    '“Ik denk aan mijn zus,” zei hij.',
    'Dat was zijn antwoord en Driss heeft het nooit meer gevraagd.',
    'Om acht uur kwamen de Portugezen in beweging. Je zag het eerst aan het stof.',
  ] },
  { nummer: 4, titel: 'Wat hij ervan zag', tekst: [
    'Wat Driss ervan gezien heeft, is dit, en het is minder dan je zou willen.',
    'Hij zag stof.',
    'Hij zag de ruiters van de eigen kant naar links en naar rechts wegdraaien, in een beweging die geoefend was, en hij sloeg wat hij moest slaan toen het bevel kwam.',
    'Hij zag de Portugese linie doorstoten in het midden en ver komen, verder dan de bedoeling was, en toen zag hij hem niet meer omdat er stof overheen ging.',
    'Hij hoorde het.',
    'Daar gaat hij verder niets over zeggen. Er zijn boeken waarin staat hoe een veldslag klinkt, geschreven door mannen die het hebben meegemaakt, en die boeken zijn er en dit is er geen.',
    'Wat er gebeurde: de Portugese aanval liep vast, de flanken sloten zich, en tegen de middag was het leger dat ’s ochtends was aangetreden er niet meer.',
    'Er zijn die dag duizenden mensen gestorven. De meesten waren geen koning.',
  ] },
  { nummer: 5, titel: 'Drie doden', tekst: [
    'Abd al-Malik stierf in zijn draagstoel, halverwege de slag, aan de ziekte die hem al weken had.',
    'Zijn adviseurs hielden het geheim. Ze lieten het gordijn dicht en gaven de bevelen door alsof hij ze nog gaf, de hele middag, tot het afgelopen was.',
    'Mohammed, de afgezette sultan, verdronk in de rivier op de vlucht.',
    'Koning Sebastiaan van Portugal is die dag gesneuveld. Zijn lichaam is teruggevonden en er is decennialang in Portugal beweerd dat hij nog leefde en terug zou komen, omdat mensen dat nu eenmaal doen met koningen die verdwijnen.',
    'Drie koningen, één dag.',
    'Ahmad, de broer van Abd al-Malik, werd diezelfde avond tot sultan uitgeroepen op het slagveld. Hij kreeg later de naam al-Mansur: de overwinnaar.',
    'En Portugal, dat zijn koning en zijn leger had verloren en geen troonopvolger had, werd twee jaar later ingelijfd door Spanje en was zestig jaar lang geen eigen land meer.',
    'Dat is wat er die dag is gebeurd, en Driss heeft er niets van gezien behalve stof.',
  ] },
  { nummer: 6, titel: 'Wat je vindt als je opruimt', tekst: [
    'De dag erna moest iedereen die kon lopen het veld op om op te ruimen.',
    'Dat woord gebruikten ze. Opruimen.',
    'Driss heeft die dag dingen gezien waar hij de rest van zijn leven niet over heeft gepraat, en dat is zijn goed recht.',
    'Wat hij wel heeft verteld, aan zijn zoon, één keer, toen die veertien werd en zei dat hij soldaat wilde worden:',
    'Dat er op zo’n veld geen verschil is.',
    'Dat je niet kunt zien wie er aan welke kant lag.',
    'Dat er jongens lagen van zijn leeftijd met een trom naast zich.',
    'Zijn zoon is geen soldaat geworden.',
    'Tussen de spullen die bij elkaar werden gelegd — riemen, gespen, een schoen, dingen die niemand meer nodig had — lag iets van brons met acht punten aan de kop.',
    'Driss nam het mee. Niet uit hebzucht; er lag genoeg dat meer waard was.',
    'Hij nam het mee omdat het geen wapen was.',
    'Van alles wat op die vlakte lag, was dit het enige ding dat niet gemaakt was om iemand iets aan te doen.',
    'Drie maanden later verkocht hij het in Marrakech aan een tegelzetter, voor zes munten en een maaltijd.',
  ] },
]
