import type { Hoofdstuk } from './sleutels'

/** Deel 7 — De jongen die twee namen kreeg. Fes en Rome, rond 1520. */
export const DEEL7_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Twee steden', tekst: [
    'Hassan was in Granada geboren en hij kon zich er niets van herinneren, en dat is een vreemde manier om ergens vandaan te komen.',
    'Zijn familie was vertrokken toen hij klein was, over zee naar Fes, met duizenden anderen. In Fes praatte zijn moeder over Granada alsof het een mens was dat gestorven was.',
    'Hij groeide op in een stad met boeken.',
    'Dat is niet overdreven. Er waren in Fes bibliotheken waar je niet meer uit kwam, er waren straten met alleen maar papiermakers, en er was de al-Qarawiyyin waar geleerd werd zoals dat al zeshonderd jaar gebeurde.',
    'Hij was goed. Iedereen zei dat hij goed was.',
    'Op zijn zestiende schreef hij al voor de rechtbank. Op zijn zeventiende ging hij voor het eerst mee met zijn oom, die gezant was — de man die namens de sultan naar andere hoven reisde en daar praatte namens iemand anders.',
    'Ze gingen naar Timboektoe, dwars door de woestijn.',
    'Ze gingen naar Egypte en naar Constantinopel.',
    'En Hassan schreef alles op, want dat was wat hij deed en wat hij het liefste deed.',
  ] },
  { nummer: 2, titel: 'Het gasthuis', tekst: [
    'Zijn eerste werk was in een gekkenhuis, en dat heeft hem gevormd op een manier die niemand had voorzien.',
    'Hij was vijftien. Hij kon schrijven, en in Fes stond een maristan — een gasthuis, waar zieken werden verpleegd en waar ook mensen zaten die in hun hoofd ziek waren.',
    'Zo’n huis had een schrijver nodig. Iemand die opschreef wie er binnenkwam, wat de familie betaalde, wat de dokter zei.',
    'Twee jaar lang zat Hassan aan een tafel bij de deur.',
    'Hij schrijft er later maar één alinea over, in een boek van vierhonderd bladzijden, en het is een van de weinige plekken waar hij iets over zichzelf vertelt.',
    'Wat er niet in staat maar wat er wel gebeurd moet zijn:',
    'Dat een jongen van vijftien elke dag mensen zag die de draad kwijt waren. Dat hun families ze brachten en soms niet meer ophaalden. Dat er iemand bij was die dacht dat hij een ander was, en dat je dan opschrijft welke naam de familie geeft en niet welke naam hij zelf zegt.',
    'Er is in zijn latere leven iets wat daarop lijkt.',
    'Hij is de man geworden die twee namen had en die in elk van beide werelden opschreef wat de andere wereld niet wist.',
    'Hij heeft in dat gasthuis geleerd wat je doet als iemands naam en iemands leven niet meer op elkaar passen.',
    'Je schrijft ze allebei op.',
  ] },
  { nummer: 3, titel: 'Taghaza', tekst: [
    'Op zijn zeventiende ging hij de woestijn in met zijn oom, en de woestijn is niet leeg.',
    'Dat is het eerste wat hij opschreef en het staat nog in het boek: er lopen wegen, er zijn putten, er zijn plaatsen waar je moet zijn op de dag dat je er moet zijn.',
    'Een karavaan is geen avontuur. Het is een onderneming met een rooster.',
    'Halverwege, twintig dagen ten zuiden van de laatste stad, ligt Taghaza.',
    'Daar wordt zout gedolven, en het bijzondere is hoe.',
    'Ze graven het in platen uit de grond. Grote platen, zo groot als een deur, en zo zwaar dat er twee man voor nodig zijn.',
    'En de huizen in Taghaza zijn gemaakt van diezelfde platen.',
    'Hassan heeft dat opgeschreven en hij is drie keer gaan kijken om zeker te weten dat hij het goed zag. Muren van zout. Daken van zout. Een moskee van zout.',
    'Er woont daar niemand vrijwillig. De mensen die het delven zijn erheen gebracht en mogen niet weg, en ze eten wat de karavanen meebrengen, want er groeit niets.',
    'Als er een karavaan te laat komt, gaan ze dood.',
    'Dat staat er ook in het boek, in dezelfde toon als de rest, zonder uitroepteken.',
    'Zeventienhonderd kilometer verderop, in Timboektoe, is dat zout bijna net zoveel waard als goud, want in de hitte gaat een mens dood zonder zout en dat weten ze daar beter dan waar ook.',
    'Dit is wat Hassan leerde op zijn zeventiende, en het is de les waar zijn hele boek op rust:',
    'Alles wat ergens niets waard is, is ergens anders een vermogen. Daarom rijden er mensen dertig dagen door de woestijn met stenen op een kameel.',
  ] },
  { nummer: 4, titel: 'Boeken zijn duurder dan goud', tekst: [
    'Timboektoe was de rijkste stad die Hassan ooit heeft gezien, en hij had Fes gezien en Caïro en Constantinopel.',
    'Ze kwamen er aan het eind van de reis aan, stoffig en uitgeput, en reden een stad binnen met een paleis, een grote moskee van aarde, en straten vol handelaren uit landen waarvan hij de naam niet kende.',
    'De koning heette Askia Muhammad en hij regeerde over een gebied dat groter was dan alles ten noorden van de woestijn.',
    'Er lag goud. Zoveel goud dat het gewoon goud was, zoals ijzer ergens anders ijzer is.',
    'En dan schrijft Hassan de zin op waar zijn boek in Europa het beroemdst om is geworden, en die twee eeuwen lang door niemand geloofd werd:',
    '*Er worden hier meer boeken verkocht dan enige andere koopwaar, en daar wordt meer aan verdiend.*',
    'Meer dan aan goud.',
    'Er waren in Timboektoe bibliotheken. Er waren families die generaties lang handschriften verzamelden. Er waren mannen die van het overschrijven van boeken leefden, en die goed leefden.',
    'Hassan is daar dagen geweest en heeft gekocht wat hij dragen kon.',
    'Toen Europese reizigers in de negentiende eeuw eindelijk in Timboektoe kwamen en er een stoffige stad aantroffen, hebben ze geschreven dat Leo Africanus overdreven had.',
    'In de jaren tachtig van de vorige eeuw zijn er kelders opengegaan.',
    'Er lagen honderdduizenden handschriften. Ze liggen er nog, en er zijn er in 2012 duizenden in het geheim de stad uit gesmokkeld toen gewapende mannen ze wilden verbranden — verstopt in ezelskarren en op boten over de rivier, door bibliothecarissen die dachten: dit niet.',
    'Hij had gelijk. Vierhonderd jaar lang dacht Europa van niet.',
  ] },
  { nummer: 5, titel: 'De zee', tekst: [
    'Het gebeurde bij Djerba, op de terugweg.',
    'Ze waren met een klein schip en er kwam een groter schip, en dat is het hele verhaal. De Middellandse Zee zat in die jaren vol met kapers van alle kanten: christelijke uit Malta en Sicilië, islamitische uit Algiers en Salé. Iedereen kaapte iedereen.',
    'Hassan was eenentwintig.',
    'Ze namen hem mee naar Rhodos en van Rhodos naar Napels en van Napels naar Rome, en hij begreep onderweg dat hij geen gewone gevangene was.',
    'Een gezant die dertig steden had gezien en er een boek over kon schrijven, was iets waard.',
    'In Rome werd hij aan de paus gegeven.',
    'Niet verkocht. Gegeven, zoals je iets zeldzaams geeft aan iemand die het waardeert.',
    'De paus heette Leo. Hij was een Medici en hij verzamelde mensen die iets wisten.',
  ] },
  { nummer: 6, titel: 'Het jaar in de burcht', tekst: [
    'De Engelenburcht in Rome is een ronde toren die ooit een graf was van een keizer, en daarna een fort, en daarna een gevangenis voor mensen die te belangrijk waren voor een gewone cel.',
    'Daar heeft Hassan veertien maanden gezeten.',
    'Hij had een kamer. Hij mocht lopen op de muur. Hij kreeg eten dat beter was dan wat de bewakers kregen, en hij kreeg boeken, en hij kreeg elke week bezoek van geleerden die vragen kwamen stellen.',
    'Het is de beleefdste gevangenschap die je je kunt voorstellen, en het was gevangenschap.',
    'Dat is het hele hoofdstuk en het is moeilijk uit te leggen aan iemand die het nooit heeft meegemaakt.',
    'Wat hij deed, was leren.',
    'Hij leerde Italiaans van een man die elke dinsdag kwam. Hij leerde Latijn omdat de boeken in Latijn waren. Hij las wat er over Afrika in die boeken stond en schrijft daar later één zin over die hard aankomt:',
    '*Wat zij over mijn land hebben geschreven, is geschreven door mensen die er nooit zijn geweest.*',
    'Ergens in die veertien maanden is hij iets gaan begrijpen.',
    'Hij was de enige mens in Europa die het antwoord had op vragen die honderden geleerden bezighielden. Niet omdat hij slimmer was. Omdat hij er was geweest.',
    'En zij hadden hem.',
    'Er is geen enkele aantekening waarin hij zegt dat hij toen besloot het boek te schrijven.',
    'Maar er is wel een lijst bewaard van de boeken die hij in die maanden heeft gevraagd, en het zijn allemaal aardrijkskundige werken, en hij heeft er in de kantlijn van drie ervan met de hand fouten in verbeterd.',
    'Dat is geen gevangene die de tijd doodt. Dat is iemand die aan het werk is.',
  ] },
  { nummer: 7, titel: 'Een nieuwe naam', tekst: [
    'Ze hielden hem een jaar in het Engelenburcht vast en behandelden hem goed, en dat is een zin die twee dingen tegelijk zegt.',
    'Hij kreeg boeken. Hij kreeg les in Italiaans en in Latijn. Er kwamen geleerden op bezoek die met hem wilden praten over Afrika, en hij praatte, want praten was beter dan niet praten.',
    'En na dat jaar werd hij gedoopt.',
    'Hij kreeg de naam van de paus: Johannes Leo de Medici.',
    'In Europa noemen ze hem sindsdien Leo Africanus. Leo de Afrikaan.',
    'Wat hij daarvan vond, weet niemand.',
    'Er staat niets over in wat hij geschreven heeft. Geen regel. Hij schrijft over steden en rivieren en over hoeveel mensen er in een dal wonen, en over wat hij zelf heeft meegemaakt schrijft hij bijna niets.',
    'Er is één plek waar iets doorschemert. In zijn boek vertelt hij een fabel over een vogel die zowel bij de vogels als bij de vissen hoorde, en die bij allebei aanklopte als het hem uitkwam.',
    'Hij schrijft erbij dat hij zelf die vogel is.',
    'Meer heeft hij er niet over gezegd.',
  ] },
  { nummer: 8, titel: 'De zesde januari', tekst: [
    'Op 6 januari 1520 werd hij gedoopt in de Sint-Pieter, en de paus stond erbij als peetvader.',
    'Dat is geen kleine plechtigheid. Dat is de grootste kerk van de christenheid, met kardinalen erbij, en de man die gedoopt wordt is een moslimgeleerde uit Fes.',
    'Hij kreeg de naam van de paus: Johannes Leo de Medici.',
    'Hier moet in dit boek iets staan wat eerlijk is, en het is dit: we weten niet wat hij ervan vond.',
    'Er is geen brief. Er is geen regel in zijn werk. Hij schrijft over dorpen in de Rif en over de prijs van een schaap, en over de dag waarop hij van geloof veranderde in de Sint-Pieter schrijft hij niets.',
    'Er zijn drie manieren om daarnaar te kijken en ze zijn alle drie verdedigbaar.',
    'De eerste: hij meende het. Mensen veranderen van geloof, ook uit overtuiging, en wij hebben niet het recht om dat voor iemand anders in te vullen.',
    'De tweede: hij had geen keus. Een gevangene in het Vaticaan die weigert te dopen, komt niet vrij. Dat wisten zij ook en hij ook.',
    'De derde: hij deed wat moest en hield wat van hem was.',
    'Die derde is waar de meeste geleerden op uitkomen, en het is ook waar dat vogeltje vandaan komt.',
    'In zijn boek staat namelijk een fabel, midden tussen de beschrijvingen van steden, zomaar.',
    'Over een vogel die kon zwemmen. Als de koning van de vogels belasting kwam innen, dook hij het water in en zei: ik ben een vis. Als de koning van de vissen kwam, vloog hij op en zei: ik ben een vogel.',
    'Hij schrijft erbij dat hij zelf die vogel is.',
    'Het staat er als grapje. Het is het enige wat hij erover heeft willen zeggen, en hij heeft het zo opgeschreven dat je het kunt overslaan.',
    'Wie het niet overslaat, leest een man die uitlegt hoe hij het heeft overleefd.',
  ] },
  { nummer: 9, titel: 'De dokter uit Bologna', tekst: [
    'Er is een detail uit die jaren dat bijna niemand kent en dat het mooiste is van dit hele deel.',
    'In Bologna werkte een arts die Jacob Mantino heette. Hij was Jood, hij was uit Spanje gevlucht — net als Hassans familie, in hetzelfde jaar, om dezelfde reden.',
    'Die twee hebben samen aan een woordenboek gewerkt.',
    'Arabisch, Hebreeuws en Latijn naast elkaar. Drie talen, drie schriften, drie werelden die in Italië meestal alleen over elkaar praatten.',
    'Stel je die kamer voor.',
    'Een moslim uit Fes die op papier christen is en die van de paus zijn naam heeft. Een Jood uit Spanje die in Italië mag wonen zolang hij nuttig is. Samen aan een tafel, ruziënd over welk woord waar hoort.',
    'Allebei verjaagd uit hetzelfde land door dezelfde koningen.',
    'Allebei bezig met het enige waar ze niet uit weggejaagd konden worden.',
    'Er is een blad van bewaard gebleven, in een bibliotheek in Italië, met twee handschriften erop.',
    'Ze hebben het nooit afgemaakt.',
    'Hassan heeft in die jaren nog meer gedaan waar weinig over bekend is: hij heeft Arabisch gegeven aan wie het wilde leren, hij heeft handschriften overgeschreven, hij heeft een leven van Arabische geleerden samengesteld.',
    'Hij was, zonder dat iemand er een woord voor had, de eerste hoogleraar Arabisch van Europa.',
    'Er staat geen plaquette.',
  ] },
  { nummer: 10, titel: 'Het boek', tekst: [
    'Hij schreef het in het Italiaans, dat hij pas net kende, en hij schreef het in drie jaar.',
    '*Della descrittione dell’Africa.* De beschrijving van Afrika.',
    'Het gaat over alles. De steden van Marokko, straat voor straat. Wat er op de markt ligt. Hoeveel een huis kost. Welke stammen waar wonen en wat ze eten en hoe ze hun kinderen noemen. De routes door de woestijn met het aantal dagen erbij.',
    'Het is geen reisverhaal. Het is een inventaris.',
    'Het werd in 1550 gedrukt, en daarna vertaald in het Latijn, het Frans, het Engels, het Nederlands.',
    'Driehonderd jaar lang was dit hét boek waaruit Europa wist wat er ten zuiden van de Middellandse Zee lag. Alles wat een Engelse of Nederlandse geleerde over Marokko dacht te weten, kwam uiteindelijk hiervandaan.',
    'Daar zit een ongemakkelijke kant aan, en die moet erbij.',
    'Toen Europa later schepen en legers naar Afrika stuurde, namen ze dat boek mee.',
    'Zijn vader had hem geleerd dat kennis een opdracht is. Niemand had hem geleerd wat je doet als iemand anders bepaalt wat er met die kennis gebeurt.',
  ] },
  { nummer: 11, titel: 'Schrijven in een taal die je net kent', tekst: [
    'Het boek is geschreven in het Italiaans door een man die het zeven jaar eerder nog niet sprak, en dat zie je eraan.',
    'De zinnen zijn kort. De woordvolgorde is soms Arabisch met Italiaanse woorden erin. Er staan vormen in die geen Italiaan zou gebruiken.',
    'Latere uitgevers hebben dat allemaal gladgestreken, en daar is veel mee verloren gegaan.',
    'Want die vreemde zinnen zijn het bewijs van wie het schreef.',
    'Hij deed er drie jaar over. Vierhonderd bladzijden, uit zijn hoofd en uit zijn aantekeningen, over een gebied zo groot als half Europa.',
    'Hij schreef het in negen delen. Het land van de Amazigh. Fes en omstreken. Marrakech. De woestijn. Het land van de zwarte koningen. Egypte. En steeds hetzelfde soort gegevens: hoeveel inwoners, wat er verbouwd wordt, wat het kost, hoe ver het is, welke taal er gesproken wordt.',
    'Er staat geen woord in over hoe hij het vond.',
    'Op één plek na, en dat is aan het eind, waar hij zich verontschuldigt.',
    'Hij schrijft dat een reiziger die over zijn eigen land vertelt aan vreemden, altijd iets doet wat niet helemaal netjes is. Dat hij dingen vertelt die niet voor hen bedoeld waren.',
    'En dan schrijft hij dat hij hoopt dat het ertoe leidt dat er beter over gedacht wordt.',
    'Dat is de zin waar dit deel om draait, en de eeuwen erna hebben er een ongemakkelijk antwoord op gegeven.',
    'Het boek werd in 1550 gedrukt en driehonderd jaar lang gelezen, en toen Europa schepen en legers naar Afrika stuurde, lag het in de kajuit.',
    'Hij kon dat niet weten. Hij heeft het opgeschreven zoals hij alles opschreef: precies, en zonder zich af te vragen wie het later zou pakken.',
    'Zijn vader had hem geleerd dat kennis een opdracht is. Niemand had hem geleerd wat je doet als een ander bepaalt wat er met jouw kennis gebeurt.',
  ] },
  { nummer: 12, titel: 'De plundering', tekst: [
    'Op 6 mei 1527 stond er een leger voor Rome dat niemand had zien aankomen en dat door niemand meer werd aangestuurd.',
    'Het waren huurlingen die al maanden niet betaald waren. Hun bevelhebber sneuvelde in het eerste uur, en daarna was er niets meer dat ze tegenhield.',
    'Wat er acht dagen lang in die stad is gebeurd, hoort niet in een boek voor kinderen en het staat er daarom niet in.',
    'Wat er wel in hoort: de paus zat opgesloten in dezelfde Engelenburcht waar Hassan zeven jaar eerder had vastgezeten, en de bibliotheken brandden, en handschriften waar eeuwen werk in zat werden gebruikt om paarden op te laten staan.',
    'Hassan was drieëndertig.',
    'Ergens in die dagen is hij de stad uit gekomen. Hoe, weet niemand.',
    'Er is geen document waarin hij voorkomt na die week.',
    'De meeste geleerden denken dat hij naar Tunis is gegaan, waar mensen uit Granada woonden, waar zijn taal werd gesproken.',
    'Er is één latere vermelding, van een man die zegt dat hij daar gestorven is en dat hij was teruggekeerd tot het geloof waarin hij was opgegroeid.',
    'Dat is één zin, van één man, opgeschreven jaren later.',
    'Meer hebben we niet.',
    'Wat we wel hebben is dit: hij heeft in zijn leven twee keer alles verloren en is twee keer opnieuw begonnen, en allebei de keren heeft hij het eerst opgeschreven.',
  ] },
  { nummer: 13, titel: 'Terug over zee', tekst: [
    'In 1527 werd Rome geplunderd door een leger dat niemand had zien aankomen. De stad brandde, de paus zat opgesloten, en in de chaos verdween Hassan.',
    'De meeste geleerden denken dat hij naar Tunis is gegaan.',
    'Daarna wordt het stil. Er is een vermelding dat hij daar gestorven is, jaren later. Er is niets over hoe hij geleefd heeft.',
    'Men neemt aan — en meer dan aannemen is het niet — dat hij terugkeerde naar het geloof waarin hij was opgevoed.',
    'Dat is het einde van wat we weten.',
    'Wat een schrijver dan doet, is stoppen. Wat een verteller doet, is dit.',
  ] },
  { nummer: 14, titel: 'De band van het boek', tekst: [
    'In Rome liet hij één exemplaar van zijn boek inbinden voor zichzelf.',
    'Hij deed er iets in.',
    'Tussen het leer en het karton van de achterste band schoof hij iets plats van brons, zo lang als zijn hand, met acht punten aan de kop. Hij had het jaren geleden in Fes gekregen van een boekbinder, als betaling voor een brief die hij voor hem schreef.',
    'Waarom hij dat deed, staat er niet bij.',
    'Misschien omdat hij op dat moment twee namen had en geen van beide huizen, en omdat een mens dan iets wil hebben dat van vóór alles komt.',
    'Dat boek is met hem meegegaan over zee.',
    'Het is in Tunis in een bibliotheek terechtgekomen, en die bibliotheek is twee keer verhuisd en één keer half verbrand, en in de negentiende eeuw heeft een boekbinder de band opengesneden om hem te herstellen.',
    'Er viel iets uit.',
    'Hij legde het op zijn werkbank, keek ernaar, en stak het in zijn zak.',
  ] },
]
