import type { Hoofdstuk } from './sleutels'

/** Deel 13 — Het jaar dat de koning terugkwam. 1953–1956. */
export const DEEL13_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'De drukkerij', tekst: [
    'Nadia was veertien en ze rook naar inkt, en dat is haar hele jeugd in één zin.',
    'Haar vader had een drukkerij in Casablanca: twee persen, een zetkast, en een achterkamer waar niemand kwam. Ze drukten menukaarten, briefpapier, rouwkaarten en aankondigingen van bruiloften.',
    'Nadia zette letters vanaf haar tiende. Achterstevoren, want een zetkast werkt in spiegelbeeld, en na een jaar kon ze spiegelschrift sneller lezen dan gewoon schrift.',
    'In augustus 1953 veranderde alles op één dag.',
    'De Fransen zetten de sultan af.',
    'Mohammed V, die al twintig jaar op de troon zat en die steeds duidelijker had gezegd dat Marokko van de Marokkanen was, werd op een vliegtuig gezet. Eerst naar Corsica. Daarna naar Madagaskar, zo ver weg dat het bijna een grap was.',
    'Ze zetten er een oude neef voor in de plaats.',
    'Nadia hoorde het op straat, en ze zag dat de straat er anders bij lag dan ze ooit had gezien.',
  ] },
  { nummer: 2, titel: 'De maan', tekst: [
    'Wat er toen gebeurde, is het soort ding dat je in een geschiedenisboek leest en waarvan je denkt: dat verzinnen ze.',
    'Mensen begonnen de koning in de maan te zien.',
    'Het begon ergens, niemand weet waar, en binnen weken keek het halve land op de zevenentwintigste van de maand omhoog en zei dat het gezicht van Mohammed V in de volle maan stond.',
    'De Fransen wisten niet wat ze ermee aan moesten. Je kunt een krant verbieden. Je kunt de maan niet verbieden.',
    'Nadia heeft het zelf ook gezien, zegt ze. Of ze heeft zichzelf laten zien dat ze het zag; op haar oude dag zei ze dat ze het verschil niet meer wist.',
    'In de drukkerij veranderde er iets in diezelfde weken.',
    'Haar vader begon ’s avonds door te werken.',
  ] },
  { nummer: 3, titel: 'De achterkamer', tekst: [
    'Ze wist het al voordat hij het haar vertelde. Je weet zoiets.',
    'Op een avond in november riep hij haar in de achterkamer, deed de deur dicht en liet haar een vel zien dat van de kleine pers kwam.',
    'Geen menukaart.',
    '“Als ze het vinden,” zei hij, “dan zeg jij dat je niets weet.”',
    '“Dat geloven ze niet.”',
    '“Nee,” zei hij. “Maar dan zeg je het toch.”',
    'Vanaf dat moment hielp ze mee.',
    'Dat ging zo: overdag briefpapier, ’s avonds het andere. De pamfletten gingen in stapels papier die naar klanten werden gebracht, tussen de menukaarten van een restaurant.',
    'Nadia bracht ze weg met een tas over haar schouder, veertien jaar oud, en ze heeft in die jaren geleerd hoe je loopt als je niets te verbergen hebt.',
    'Niet te snel. Niet te langzaam. Kijk mensen aan.',
  ] },
  { nummer: 4, titel: 'Wat het kostte', tekst: [
    'Het waren geen mooie jaren en dit is geen mooi hoofdstuk.',
    'Er werd gestaakt en er werd gevochten. Er vielen doden, in Casablanca en in Oued Zem en op plekken waarvan de namen nu op scholen worden geleerd.',
    'De vader van haar vriendin werd opgepakt en kwam na acht maanden terug en was een andere man.',
    'Haar eigen vader is twee keer opgehaald en twee keer teruggekomen. De tweede keer duurde het elf dagen, en hij heeft er nooit over verteld, en hij drukte daarna weer.',
    'Nadia was zestien toen ze voor het eerst dacht: misschien wint dit niet.',
    'Ze heeft dat aan niemand gezegd.',
  ] },
  { nummer: 5, titel: 'November', tekst: [
    'Op 16 november 1955 kwam hij terug.',
    'Nadia was zeventien. Ze stond langs de weg in Rabat, waar ze met haar neef naartoe was gereisd omdat ze het wilde zien, tussen honderdduizenden mensen die allemaal hetzelfde wilden zien.',
    'Wat ze zich herinnert is niet het gezicht van de koning. Dat was ver weg en het ging snel.',
    'Wat ze zich herinnert is het geluid.',
    'Ze heeft later gezegd dat ze nooit meer in haar leven zoveel mensen tegelijk heeft horen huilen en juichen op hetzelfde moment.',
    'Op 2 maart 1956 werd Marokko onafhankelijk van Frankrijk. In april volgde het Spaanse deel.',
    'Haar vader heeft die dag de persen laten stilstaan, wat hij nooit deed.',
    'Hij zette twee stoelen op de stoep en ze hebben daar de hele middag gezeten.',
  ] },
  { nummer: 6, titel: 'Het valse boek', tekst: [
    'In de achterkamer stond een boek dat geen boek was.',
    'Haar vader had het gemaakt in het eerste jaar: een band van een oud wetboek, uitgehold, waar precies twintig gevouwen pamfletten in pasten. Als er iemand kwam die niet vertrouwd was, ging alles daarin en het boek in de kast bij de andere.',
    'Er lag nog iets in.',
    'Een sleutel van brons met acht punten aan de kop, die haar vader in 1948 had gekocht op de vlooienmarkt omdat hij mooi was, en die hij in het boek had gelegd omdat hij er niets anders mee kon.',
    'Na de onafhankelijkheid is het boek nooit meer gebruikt.',
    'Het heeft in de kast gestaan tot de drukkerij in 1971 werd verkocht, en toen heeft Nadia het meegenomen naar haar eigen huis, en later naar het huis van haar dochter.',
    'Haar dochter is in 1979 naar Nederland gegaan.',
    'Het boek ging mee.',
  ] },
]
