import type { Hoofdstuk } from './sleutels'

/** Deel 12 — De berg die niet meeging. Het Rif, 1921–1926. */
export const DEEL12_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Het dorp', tekst: [
    'Itto was vijftien en haar vader gaf les in een kamer met zeven kinderen en geen ramen.',
    'Hun dorp lag in het Rif, hoog, tussen rotsen waar amandelbomen groeiden die niemand had geplant. Vanaf het dak van hun huis kon ze op heldere dagen de zee zien.',
    'Wat ze niet kon zien, waren de grenzen.',
    'Die waren er sinds 1912 wel. Toen was Marokko verdeeld: Frankrijk kreeg het grootste deel, Spanje het noorden, en er was afgesproken dat de sultan er nog was maar niet echt.',
    'Niemand in het dorp had die afspraak getekend. Niemand had het gevraagd.',
    'Haar vader zei er weinig over. Hij zei: leer lezen, dan kun je zelf nagaan wat er is opgeschreven.',
    'Hij leerde haar Arabisch lezen en schrijven, en ook Spaans, omdat hij zei dat je de taal van degene die over je beslist moet kennen.',
    'Dat laatste heeft haar leven bepaald.',
  ] },
  { nummer: 2, titel: 'Annual', tekst: [
    'In juli 1921 kwam er nieuws dat te groot was om te geloven.',
    'Bij een plek die Annual heet, was het Spaanse leger verslagen. Niet teruggedrongen — verslagen. Duizenden soldaten, tientallen posten, allemaal weg in een paar dagen.',
    'De man die het bevel voerde aan hun kant heette Abd el-Krim. Hij was rechter geweest, en journalist, en hij had in Spanje gestudeerd.',
    'In het dorp werd er die avond gezongen.',
    'Itto heeft later geschreven dat ze zich die avond herinnert als de laatste waarop iedereen alleen maar blij was.',
    'Want daarna kwam de rest.',
    'Abd el-Krim riep een republiek uit. Er kwam een bestuur, er kwamen wetten, er was een raad. Voor het eerst in de geschiedenis van die bergen was er iets dat niet van een stam was maar van iedereen.',
    'En Spanje kwam terug met alles wat het had.',
  ] },
  { nummer: 3, titel: 'Boodschappen', tekst: [
    'Itto werd loopster.',
    'Ze kon lezen, ze kon Spaans, ze was vijftien en een meisje, en dat laatste was het belangrijkste: soldaten hielden een jongen van vijftien aan en een meisje met een mand niet.',
    'Ze bracht berichten tussen de dorpen. In haar hoofd als het kon, op papier als het niet anders kon, en dan opgevouwen in de zoom van haar jurk.',
    'Ze heeft in vier jaar meer van die bergen gezien dan de meeste mensen in hun leven.',
    'Ze heeft ook dingen gezien die ze niet wilde zien.',
    'In dit boek staan die er niet in. Niet omdat ze niet gebeurd zijn, maar omdat Itto ze zelf nooit heeft opgeschreven, en het is niet aan iemand anders om dat voor haar te doen.',
    'Wat er wel in staat, is dit.',
    'Vanaf 1924 werd er iets gebruikt dat niet mag. Vliegtuigen lieten gas vallen op dorpen en op markten, op plekken waar geen soldaten waren.',
    'Spanje heeft dat tientallen jaren ontkend. Pas veel later is het erkend.',
    'Itto was toen achttien.',
  ] },
  { nummer: 4, titel: 'Twee legers', tekst: [
    'In 1925 kwam Frankrijk erbij.',
    'Dat was het einde, al duurde het nog een jaar. Tegen één leger kon het Rif het opnemen. Tegen twee, met vliegtuigen en met honderdduizenden soldaten, niet.',
    'In mei 1926 gaf Abd el-Krim zich over.',
    'Hij werd verbannen naar een eiland in de Indische Oceaan, en later ontsnapte hij naar Egypte, waar hij in 1963 is gestorven.',
    'De republiek was voorbij.',
    'Het dorp van Itto is ontruimd. Dat woord staat in de papieren. Wat het betekende was: iedereen weg, de huizen leeg, en wie niet wegging werd weggehaald.',
    'Haar vader heeft zijn boeken begraven in een kist achter het huis. Dat deden meer mensen.',
    'Itto heeft toen iets gedaan wat ze nooit helemaal heeft kunnen uitleggen.',
    'Ze had een sleutel. Een oude, van brons, met acht punten. Die had ze gekregen van een man in Tetouan die haar berichten doorgaf en die zei dat hij hem uit een kelder in Tanger had.',
    'Ze heeft hem bij de boeken in de kist gelegd.',
    'Dat was haar manier om te zeggen: dit huis is van ons en we komen terug.',
  ] },
  { nummer: 5, titel: 'Wat de winnaars opschrijven', tekst: [
    'Ze kwamen niet terug. Niet naar dat huis.',
    'Itto is in Tetouan terechtgekomen en daar getrouwd en daar oud geworden.',
    'Ze heeft haar hele leven les gegeven, net als haar vader, eerst in het geheim en later gewoon.',
    'En ze heeft één ding steeds tegen haar leerlingen gezegd.',
    'Dat wat er in de boeken staat, is opgeschreven door degene die won.',
    'Dat dat niet betekent dat het gelogen is — maar dat het betekent dat je moet kijken wie de pen vasthield.',
    'Ze zei dat het niet genoeg is om te kunnen lezen. Dat je ook moet weten wie het heeft geschreven, en waarom, en wat er niet in staat.',
    'Toen Marokko in 1956 onafhankelijk werd, was ze vijftig.',
    'Ze zei tegen haar dochter: ik heb het gezien. Ik heb het niet meegemaakt, want dat is iets anders. Maar ik heb het gezien.',
  ] },
  { nummer: 6, titel: 'De kist onder de vloer', tekst: [
    'De kist is in 1974 teruggevonden.',
    'Een kleinzoon van de buurman bouwde op de plek van de oude dorpen, en bij het graven stuitte zijn schop op hout.',
    'Er zaten zeven boeken in. Vijf waren onleesbaar geworden. Twee niet.',
    'En er zat iets van brons in met acht punten aan de kop.',
    'De man heeft de boeken naar de moskee gebracht en de sleutel meegenomen naar huis, en hij heeft hem in een koperen doos gelegd bij andere dingen waarvan niemand meer wist waar ze vandaan kwamen.',
    'Die doos stond in dat dorp in de Hoge Atlas waar zijn familie naartoe was verhuisd.',
    'Daar staat hij nu nog.',
  ] },
]
