/**
 * De sleutels van Marokko in het Italiaans.
 *
 * De dialoog staat tussen Italiaanse aanhalingstekens («…»). Dat is dezelfde
 * keuze als bij het Spaans: het Nederlands zet de dialoog midden in de alinea,
 * en met gedachtestreepjes — de gewoonte in een Italiaanse roman — zou elke
 * zin een eigen regel vragen en viel het tempo van het origineel weg.
 */
import type { SleutelVertaling } from './sleutels-talen'

export const IT_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'L’incendio delle olive',
    jaar: '± 200',
    waar: 'Walili (Volubilis), ai piedi dello Zerhoun',
    verteller: 'Tala, undici anni, figlia di un capo frantoio che si è ammalato',
    flap: 'Tala ha la chiave del magazzino e il sorvegliante la vuole. Quando l’olio di tutta la città è in pericolo, deve scegliere fra ubbidire e avere ragione.',
    sleutel: 'La chiave viene forgiata a Walili dal nonno di Tala e alla fine parte con una carovana amazigh verso le colline.',
    echt: [
      'Volubilis — in arabo Walili — è stata una vera città romana vicino a Meknès, con migliaia di abitanti, terme e strade lastricate.',
      'La città viveva di olio d’oliva. Sono stati scavati decine di frantoi, e funzionavano con la stessa idea dei frantoi che in Marocco si usano ancora oggi.',
      'I pavimenti erano coperti di mosaici. Una parte è ancora lì, all’aperto.',
      'La popolazione era in gran parte amazigh; la vita romana e quella amazigh qui si intrecciavano.',
    ],
    verzonnen: [
      'Tala, la sua famiglia e il sorvegliante Marcus non sono esistiti.',
      'L’incendio della storia è inventato. Non ci sono prove di un grande incendio a Walili in quel periodo.',
      'La chiave con la stella a otto punte è inventata. Il khatam a otto punte è invece un motivo marocchino vero e antichissimo.',
    ],
    hoofdstukken: [
      { titel: 'La chiave', tekst: [
        'Tala si svegliò per l’odore.',
        'Olive. Olive frante, calde e amare. In quelle settimane tutta la città odorava così. Restò un momento sdraiata e ascoltò. Fuori il grande frantoio scricchiolava già. Voleva dire che era in ritardo.',
        'Saltò giù dal letto e si infilò il vestito dalla testa.',
        '«Tala!» gridò sua madre da basso. «La porta!»',
        'La porta. Naturalmente la porta.',
        'Da quando suo padre si era ammalato, Tala faceva il suo lavoro. Ogni mattina andava al magazzino dietro casa e apriva la porta. Lì stavano le giare. Cento giare, riempite fino all’orlo di olio, pronte per andare al porto.',
        'La chiave le pendeva al collo da un cordoncino. Era di bronzo e lunga come la sua mano. Gliel’aveva forgiata suo nonno, molto prima che lei ci fosse. Nella testa aveva otto punte, come una stella.',
        '«Non perderla», aveva detto suo padre. L’aveva detto piano, perché più forte non gli riusciva più. «Quella porta non si apre con nient’altro.»',
        'Tala corse giù per le scale, oltre la cucina, attraverso il cortile. Era ancora presto. Il sole stava appena sopra le colline e le pietre erano fredde sotto i suoi piedi.',
        'Davanti al magazzino c’era un uomo.',
        'Si fermò.',
        'Era grande e portava il mantello rosso del sorvegliante. Marcus. A Walili conoscevano tutti Marcus, e non piaceva a nessuno.',
        '«Sei in ritardo», disse lui.',
        '«Sono in orario», disse Tala.',
        'Sapeva che non avrebbe dovuto dirlo. Lo disse lo stesso.',
        'Marcus la guardò. Poi tese la mano.',
        '«Dammi quella chiave. Una bambina non deve sorvegliare cento giare.»',
        'Tala fece un passo indietro.',
        'Nella testa sentiva suo padre. *Quella porta non si apre con nient’altro.* E pensò a un’altra cosa, una cosa che aveva visto il giorno prima e che le era sembrata niente.',
        'Due giare che non erano al loro posto.',
        '«Allora?» disse Marcus.',
        'Tala strinse la mano attorno al bronzo. Si era scaldato sulla sua pelle.',
        '«No», disse.',
      ] },
      { titel: 'Due giare', tekst: [
        'Marcus non rise. E non si arrabbiò neanche. Quella fu la cosa peggiore.',
        'Abbassò la mano, si aggiustò il mantello e disse: «Come vuoi.» Poi se ne andò, fuori dal vicolo, senza voltarsi.',
        'Tala rimase ferma finché non sentì più i suoi passi. Solo dopo si accorse che le tremavano le mani.',
        'Aprì la porta.',
        'Dentro era buio e fresco. Le giare stavano in file da dieci, con la paglia in mezzo perché non sbattessero l’una contro l’altra. Dieci file da dieci. Ogni mattina le contava. Gliel’aveva insegnato suo padre quando aveva sei anni, e allora era ancora un gioco.',
        'Cominciò da sinistra e contò ad alta voce, come sempre.',
        'All’ultima fila si fermò.',
        'Ce n’erano nove.',
        'Tala contò di nuovo. Nove. Girò intorno alla fila, si chinò, guardò dietro la paglia. Nove.',
        'Anche il giorno prima aveva visto una cosa strana. Due giare messe male, con i manici verso il muro invece che verso il passaggio. Aveva pensato: qualcuno ha fatto in fretta. Le aveva raddrizzate e non ci aveva più pensato.',
        'Adesso ce n’era una in meno.',
        'Si sedette sulla soglia con la schiena contro lo stipite e le ginocchia raccolte, e cercò di capire cosa doveva fare.',
        'Poteva dirlo a sua madre. Ma quel mese sua madre ne aveva già abbastanza: un marito malato di sopra, una casa piena di gente da pagare, e un raccolto che fra tre settimane doveva partire per il porto.',
        'Poteva dirlo a Marcus. Marcus era il sorvegliante. Era il suo lavoro.',
        'Tala guardò il vicolo dove era sparito.',
        'No.',
        '«Sei in mezzo», disse una voce.',
        'Sobbalzò. Davanti a lei c’era un ragazzo più o meno della sua età, con un grembiule di cuoio e le braccia piene di fascine. Aveva le mani nere.',
        '«Non sono in mezzo», disse Tala. «Questa è la mia porta.»',
        '«Allora sei in mezzo alla tua porta.»',
        'Si chiamava Yidir e lavorava alla fucina in fondo alla strada. Tala lo conosceva di vista come si conoscono tutti di vista a Walili, e nient’altro.',
        'Si alzò per farlo passare. Lui non passò.',
        '«Tu conti ogni mattina», disse.',
        '«Come fai a saperlo?»',
        '«Passo di qui ogni mattina.»',
        'Tala esitò. Poi lo disse lo stesso, perché doveva uscirle e perché lui ormai era lì.',
        '«Ne manca una.»',
        'Yidir posò le fascine per terra.',
        '«Una?» disse. «Allora sei stata fortunata. Da noi mancano sei barre di ferro.»',
      ] },
      { titel: 'Come si fa l’olio', tekst: [
        'Quel pomeriggio Tala era al frantoio, come ogni giorno durante il raccolto.',
        'Il frantoio era una pietra scavata grande come un carro, con dentro una pietra rotonda che un asino trascinava in tondo. Le olive andavano dentro, venivano schiacciate, e quello che ne usciva era una massa bruna e spessa che non somigliava a niente.',
        'Era la parte che deludeva sempre i forestieri. «*Quello* sarebbe olio?» chiedevano. No. Quello era l’inizio.',
        'La massa andava in stuoie rotonde di giunco intrecciato. Le stuoie si impilavano una sull’altra sotto la pressa a trave, e poi due uomini giravano la vite, lentamente, come se avessero tempo. Sotto la pila correva un canaletto.',
        'Era da lì che usciva.',
        'Prima acqua, torbida e sporca. Poi, dopo un po’, un’altra cosa. Qualcosa che restava a galla sull’acqua ed era più verde di tutto quello che Tala conosceva.',
        'La prima volta suo padre l’aveva presa per la nuca e le aveva tenuto la testa sopra. «Annusa», aveva detto. «È questo. Se odora *così*, è buono. Se non odora di niente, hai aspettato troppo.»',
        'Allora aveva mentito, aveva detto che lo sentiva. Adesso lo sentiva davvero.',
        'Walili viveva di questo. Non dei pavimenti a mosaico su cui camminavano i visitatori, non delle colonne della piazza, non delle strade lastricate. Di questo. Di olive frante che finivano nelle giare, sui carri verso la costa, e sulle navi verso posti di cui Tala conosceva soltanto i nomi.',
        'Teneva d’occhio il canaletto e le stuoie e l’asino, e intanto pensava a novantanove giare.',
        'Sei barre di ferro, aveva detto Yidir. Dalla fucina.',
        'Il ferro costava caro. L’olio costava caro. E tutti e due uscivano dalla città nella stessa direzione: per la strada del porto.',
        '«Tala.» Uno degli uomini indicò il canaletto. «Trabocca.»',
        'Scattò in avanti e ci mise sotto la ciotola, troppo tardi. Un filo d’olio corse sulla pietra e sparì fra le fughe.',
        'Un dito, forse due. Abbastanza per una famiglia per una settimana.',
        'L’uomo non disse niente. Questo la fece sentire peggio.',
      ] },
      { titel: 'Cosa può fare un sorvegliante', tekst: [
        'Marcus tornò il terzo giorno, e non venne da solo.',
        'Tala lo vide entrare nel cortile con due uomini dietro. Sua madre uscì, si asciugò le mani sul vestito e si mise esattamente fra lui e la porta.',
        '«Pace», disse Marcus.',
        '«Pace», disse sua madre, con il tono che si usa quando non lo si pensa.',
        '«Tuo marito è malato.»',
        '«Mio marito riposa.»',
        '«Tre settimane», disse Marcus. «Fra tre settimane il raccolto parte per il porto, e la città conta su quello che c’è in questa casa. Devo sapere che c’è.»',
        '«C’è.»',
        '«Voglio vederlo.»',
        'Cadde un silenzio. Tala stava sulla soglia della cucina e non osava muoversi.',
        'Sua madre disse: «Puoi guardare. Apre mia figlia.»',
        'Tala attraversò il cortile sotto gli occhi di cinque persone. Si sfilò il cordoncino dalla testa, infilò la chiave nella serratura e spinse la porta.',
        'Marcus entrò. Camminò lungo le file, lentamente, con le mani dietro la schiena. All’ultima fila si fermò.',
        'Tala trattenne il fiato.',
        '«Novantanove», disse Marcus.',
        'Si voltò e guardò sua madre.',
        '«Ne dovrebbero essere cento.»',
        'Sua madre si irrigidì. Tala lo vide dalle spalle.',
        '«Allora una si è rotta», disse.',
        '«Allora ci sarebbero i cocci.» Marcus allargò le mani. «Non vedo cocci. Vedo paglia che è stata rimessa a posto.»',
        'Aspettò un momento, esattamente quanto bastava.',
        '«Non sto dicendo che rubate», disse poi. «Sto dicendo che una bambina di undici anni ha la chiave di cento giare, e che oggi ce ne sono novantanove. Questo dico. E questo dirò anche in piazza.»',
        'Uscì e passò accanto a Tala come se fosse un palo.',
        'Quando se ne fu andato, sua madre si sedette sul bordo del pozzo. Per molto tempo non disse niente.',
        '«Mamma», disse Tala. «Non l’ho—»',
        '«Lo so.»',
        '«L’ho contate lunedì e allora erano ancora—»',
        '«Tala.» Sua madre alzò gli occhi. Erano rossi. «Lo so. E questo non ci aiuta.»',
      ] },
      { titel: 'La fucina', tekst: [
        'Yidir era seduto su un secchio rovesciato davanti alla fucina e limava un cardine.',
        '«Avevi ragione», disse Tala.',
        '«È una cosa che la gente mi dice di rado», disse Yidir senza alzare gli occhi. «Su cosa?»',
        '«Sul fatto che non era una giara sola.»',
        'Adesso alzò gli occhi.',
        'Tala si sedette accanto a lui sulla soglia e raccontò. Di Marcus, di novantanove, di quello che avrebbe detto in piazza. Yidir ascoltò come faceva tutto: come se intanto pensasse ad altro, ma non gli sfuggiva niente.',
        '«E il tuo ferro?» chiese lei.',
        '«Sei barre. Il mio maestro pensa di aver sbagliato a contare.» Yidir fece spallucce. «Il mio maestro non sbaglia mai a contare.»',
        '«Quando?»',
        '«La settimana scorsa. E tre quella prima.»',
        'Tala raccolse le ginocchia.',
        '«Cosa esce dalla città?» chiese. «Ogni giorno, intendo.»',
        'Yidir ci pensò.',
        '«Carri», disse. «Olio, grano, pelli, ferro. Tutto passa per la strada verso nord. Alla porta c’è un posto di guardia. Lì si scrive tutto.»',
        '«Chi scrive?»',
        'Yidir la guardò.',
        '«Il sorvegliante», disse.',
        'Per un po’ non dissero niente, né l’uno né l’altra.',
        '«Questo non prova niente», disse alla fine Tala.',
        '«No.»',
        '«Se lo dico, diranno che una bambina di undici anni accusa un uomo perché non le sta simpatico.»',
        '«Sì», disse Yidir. «Lo diranno.»',
        'Mise via il cardine.',
        '«Quindi ti serve qualcosa che non possano rigirare a parole.»',
        '«Tipo?»',
        '«Tipo vedere cosa passa di notte da quella porta.»',
        'Tala lo guardò. Lui ricambiò lo sguardo, e per la prima volta da quando lo conosceva, rise.',
      ] },
      { titel: 'Cosa passa di notte dalla porta', tekst: [
        'Erano sdraiati sul tetto delle terme, a pancia in giù, con il mento sulle braccia.',
        'Il tetto era caldo dalla giornata. Sotto di loro c’era la strada che andava alla porta nord, larga abbastanza per due carri affiancati. Alla porta ardeva una lampada.',
        '«Quanto manca?» sussurrò Tala.',
        '«Non lo so.»',
        '«Avevi detto che di notte passano i carri.»',
        '«Avevo detto che *pensavo* che di notte passassero i carri.»',
        'Tala sospirò e posò la testa sul braccio.',
        'Quella notte le stelle erano incredibili. In città le vedevi a metà, per via della luce e del fumo, ma quassù erano così tante che diventava inquietante.',
        '«Mia nonna dice che sono una mappa», disse Yidir.',
        '«Le stelle?»',
        '«Sì. Se le sai leggere, puoi andare dappertutto. Dice che la sua famiglia è arrivata così dal deserto fin qui.»',
        '«Tu le sai leggere?»',
        '«No», disse Yidir. «Nessuno me l’ha insegnato.»',
        'Poi lo sentirono.',
        'Un carro. Non due asini, non cavalli — un asino solo, lento, e il rumore del legno che scricchiola sotto il peso.',
        'Tala si spostò sul bordo.',
        'Il carro sbucò da una traversa. Accanto camminavano due uomini, tutti e due con un panno in testa. Sul carro c’era paglia, e sotto la paglia qualcosa di tondo.',
        'Alla porta il carro si fermò.',
        'Dalla garitta uscì un uomo con una lampada. Non andò verso il carro. Andò verso gli uomini, parlò con loro un momento, e scrisse qualcosa su una tavoletta.',
        'Poi alzò la sbarra.',
        'Il carro entrò nella notte.',
        'Tala lasciò andare il fiato. Non si era accorta di trattenerlo.',
        '«Non ha guardato», disse. «Non ha guardato sotto la paglia.»',
        '«No.»',
        '«Questo è—»',
        '«Questo continua a non essere niente», disse Yidir. «È un uomo che non guarda abbastanza bene. Non si impicca nessuno per questo.»',
        'Aveva ragione, e Tala lo sapeva.',
        'Ma quando il carro prese la curva, successe una cosa. L’asino si spaventò per qualcosa nel buio, tirò di lato, e il carro salì con una ruota sul bordo della strada.',
        'Dal carro cadde qualcosa.',
        'Rotolò, si fermò contro il muro, e lì rimase.',
        'Una giara.',
        'Uno degli uomini imprecò, tornò indietro, la raccolse e la rimise sotto la paglia. Il carro proseguì.',
        'Ma Tala aveva visto cosa c’era sopra.',
        'Sulla spalla di ogni giara della loro casa suo padre imprimeva un segno nell’argilla prima della cottura. Otto punte. Una stella.',
        'Afferrò il braccio di Yidir così forte che lui sibilò.',
        '«Quella è nostra», disse.',
      ] },
      { titel: 'Quel che dici e quel che sentono', tekst: [
        'La mattina dopo Tala andò in piazza.',
        'Ci aveva pensato tutta la notte, o almeno per metà; l’altra metà aveva dormito senza volerlo. Sapeva cosa avrebbe detto. L’aveva provato tre volte davanti al muro della sua stanza.',
        'In piazza, sotto le colonne, il consiglio teneva seduta. Voleva dire: cinque uomini su panche di pietra, uno scrivano accanto, e intorno chiunque avesse qualcosa da lamentare.',
        'Marcus era già lì.',
        'Tala aspettò che un uomo finisse di litigare su un muro e un vicino. Poi si fece avanti.',
        '«Voglio dire una cosa», disse.',
        'Cinque uomini alzarono gli occhi. Uno di loro, il più vecchio, con una faccia come un fico secco, si sporse in avanti.',
        '«Di chi sei figlia?»',
        '«Di Yuba, il frantoiano. Della via delle Colonne.»',
        '«Quello è malato.»',
        '«Sì», disse Tala. «Per questo sono qui io.»',
        'Raccontò. Della giara sparita, e del giorno dopo un’altra. Del carro nella notte e dell’uomo che aveva alzato la sbarra senza guardare sotto la paglia. Della giara caduta e del segno con le otto punte.',
        'Lo raccontò esattamente come l’aveva provato, e mentre lo faceva, lo sentì anche lei.',
        'Sentì come suonava.',
        'Una bambina. Un tetto. Il buio. Un segno che non aveva visto nessun altro.',
        'Quando ebbe finito, per un momento ci fu silenzio. Poi Marcus disse, molto tranquillo: «Posso?»',
        'Il più vecchio annuì.',
        '«La bambina ha ragione, mancano delle giare», disse Marcus. «L’ho contate io stesso, l’altro ieri, nel loro magazzino. Novantanove su cento. L’ho detto anche allora.»',
        'Allargò le mani, come faceva lui.',
        '«Chi ha la chiave di quella porta?»',
        'Nessuno disse niente.',
        '«Lei», disse Marcus. «Una bambina di undici anni. E adesso che ne manca una, è stato un carro nella notte. Un carro che ha visto soltanto lei.»',
        'Il più vecchio del consiglio guardò Tala, e il suo sguardo non era ostile. Quella fu la cosa peggiore.',
        '«Bambina», disse. «Vai a casa. Occupati di tuo padre.»',
        'Tala rimase in piazza con le braccia lungo i fianchi e le orecchie che bruciavano, e intorno a lei ricominciarono tutti a parlare di un muro e di un vicino.',
      ] },
      { titel: 'L’incendio', tekst: [
        'L’incendio scoppiò quattro giorni dopo, e non scoppiò da loro.',
        'Tala si svegliò per quello. Non per la luce e non per le grida — per il suono. Un brontolio basso e sordo, come se lì vicinissimo qualcuno stesse buttando fuori il fiato per moltissimo tempo.',
        'Era alla finestra prima di essere sveglia.',
        'Dall’altra parte della strada, due case più in là, bruciava il magazzino di Quintus. Anche Quintus faceva olio. Le sue giare stavano in un locale sotto casa, e adesso dalla finestra usciva il fuoco, piatto, e non verso l’alto come il fuoco dovrebbe fare.',
        'È per via dell’olio, lo imparò dopo. L’olio brucia in un altro modo.',
        'Si gridava già. C’era già gente in strada con secchi e coperte, e qualcuno batteva con un bastone sulla lastra di bronzo accanto al pozzo, e Tala corse giù per le scale senza scarpe.',
        'Sua madre la afferrò per un braccio sulla soglia.',
        '«Non da quella parte.»',
        '«Ma—»',
        '«Tala.» Sua madre la teneva con tutte e due le mani. «La nostra porta. *Adesso.*»',
        'E Tala capì.',
        'Se si propaga, viene da loro. Cento giare — novantanove — piene d’olio, dietro una porta di legno, contro lo stesso muro.',
        'Corse al magazzino, si sfilò il cordoncino dalla testa e infilò la chiave nella serratura. Aveva le mani così bagnate che il bronzo le girava via. La terza volta ci riuscì.',
        'La porta si aprì. Le venne incontro il fresco, e l’odore.',
        'Dietro di lei tutta la strada cominciò a portare giare.',
        'Le portarono nel cortile, al pozzo, in strada, dovunque non ci fosse un muro che bruciava. I vicini portavano, gente che conosceva appena, gente con cui suo padre non aveva mai parlato. Qualcuno aveva una scala. Qualcuno buttava le coperte nell’acqua del pozzo e le passava avanti.',
        'Tala portò finché le braccia non vollero più, e poi portò ancora.',
        'Alla settantesima giara vide Yidir. Arrivò con altri quattro della fucina e trascinavano una cosa che sembrava un lungo gancio.',
        'All’ottantacinquesima il tetto del magazzino di Quintus crollò dentro.',
        'All’ultima il sole stava quasi sorgendo.',
        'Allora non c’era più fuoco. C’era solo fumo basso sulla strada, e duecento persone che guardavano senza dire niente, e mani nere, e da qualche parte un bambino che piangeva.',
        'Tala era seduta sul gradino, appoggiata a sua madre.',
        'Ed è per questo che fu l’unica a vedere l’uomo che usciva dal vicolo accanto alla casa di Quintus, controcorrente, con il mantello sul braccio invece che sulle spalle.',
        'Il mantello era rosso.',
      ] },
      { titel: 'Il mantello rosso', tekst: [
        'Lo raccontò a Yidir prima di raccontarlo a chiunque altro.',
        'Lui ascoltò senza interromperla, e quando ebbe finito disse: «Continua a non essere niente.»',
        '«L’ho visto.»',
        '«Hai visto un uomo con un mantello rosso in una strada piena di gente con la fuliggine in faccia.» Yidir diede un calcio a un sasso. «Io ti credo. Il consiglio no.»',
        'Tala sapeva che aveva ragione e ne aveva abbastanza che avesse sempre ragione.',
        '«E allora cosa?» disse. «Non posso mica non fare niente.»',
        '«No», disse Yidir. «Ma ti serve qualcosa che non venga da te.»',
        'Si sedette sul bordo del pozzo, con i talloni contro la pietra.',
        '«Alla porta scrivono tutto», disse. «Sulla cera. Cosa esce, quanto, e di chi. Quelle tavolette ogni mese vanno al municipio.»',
        '«E se non c’è scritto niente di strano?»',
        '«Allora non c’è scritto niente di strano», disse Yidir. «E allora sai che non è nei registri ma nel buio. Anche quello è qualcosa.»',
        'La guardò.',
        '«Ma se invece c’è scritto qualcosa — se lì ci sono dodici giare mentre dalla porta ne sono uscite tredici — allora non è una bambina che ha visto una cosa. È un numero accanto a un numero, e i numeri non li rigira nessuno a parole.»',
        'Tala pensò alla notte sul tetto. All’uomo che non aveva guardato sotto la paglia.',
        '«Chi può vedere quelle tavolette?»',
        '«Noi no.»',
        '«E chi allora?»',
        'Yidir tacque un momento.',
        '«Il mio maestro», disse. «Fornisce il ferro per le serrature del municipio. Entra lì senza che nessuno gli chieda perché.»',
        '«E allora chiediglielo.»',
        '«Non è uno che si mette contro il sorvegliante.»',
        '«Chiediglielo», disse Tala un’altra volta.',
        'Yidir si guardò le mani nere.',
        '«Va bene», disse. «Ma non stasera. Stasera è il venerdì del mercato e allora è di cattivo umore.»',
        'Nonostante tutto Tala dovette ridere.',
        'Era la prima volta dopo giorni.',
      ] },
      { titel: 'Cosa c’era scritto sulla cera', tekst: [
        'Il fabbro si chiamava Amanar ed era l’uomo più grande che Tala avesse mai visto da vicino.',
        'Per due giorni non disse niente. Poi la terza mattina arrivò nella via delle Colonne con un pacchetto sotto il braccio, e si sedette sul gradino del magazzino come se fosse la cosa più normale.',
        '«Tu sei la figlia di Yuba», disse.',
        '«Sì.»',
        '«Tuo padre una volta ha dato a mia madre olio per tutto un inverno senza farselo pagare.» Amanar guardò la strada. «Erano sedici anni fa. Io non l’ho dimenticato e lui non si ricorda più di averlo fatto.»',
        'Posò il pacchetto sul gradino.',
        'Erano due tavolette di cera, in una cornice di legno, con graffio su graffio su graffio.',
        '«Guardare sì», disse Amanar. «Portare via no. Fra un’ora sono di nuovo dove devono stare.»',
        'Tala si sedette e lesse.',
        'Sapeva leggere. Non spedita, ma abbastanza. Suo padre ci aveva tenuto: «Chi non sa leggere crede a quello che un altro dice che c’è scritto.»',
        'Sulla cera c’erano righe. Data, porta, cosa, quanto, di chi.',
        'Cercò il proprio nome. Lo trovò undici volte.',
        '*Yuba, frantoiano, via delle Colonne. Otto giare.*',
        '*Yuba, frantoiano. Dodici giare.*',
        '*Yuba, frantoiano. Nove giare.*',
        'Tala le sommò. Contò due volte e la seconda volta scrisse il risultato nella sabbia accanto ai suoi piedi.',
        'Centodiciassette giare. In quattro settimane, fuori dalla porta, a nome di suo padre.',
        'Alzò gli occhi.',
        '«Non torna», disse.',
        '«No?» disse Amanar.',
        '«Questa stagione ne abbiamo fatte centosessanta. Lo so con precisione, le ho contate quando le hanno cotte. Sessanta sono state vendute in città. Cento erano nel magazzino.» Indicò la sabbia. «Centosessanta. Non centosettantasette.»',
        'Amanar non disse niente.',
        '«Sono uscite dalla porta diciassette giare che noi non abbiamo mai fatto», disse Tala. «A nostro nome.»',
        'Mentre lo diceva, sentì lei stessa cosa voleva dire.',
        'Non erano solo le loro giare a essere rubate.',
        'Era il loro nome.',
        'Se al municipio avessero fatto i conti, e fosse arrivato meno di quanto era uscito dalla porta, ci sarebbe stata una sola casa in cui la traccia finiva. E quella casa era la loro.',
        '«Amanar», disse, e le venne una voce strana. «Ci stanno preparando.»',
        'Il fabbro si alzò e si scrollò la polvere dalle ginocchia.',
        '«Sì», disse. «È così.»',
        'Raccolse le tavolette.',
        '«Domani vieni in piazza con tua madre. E porta quella sabbia, anzi no — riscrivila su qualcosa che non voli via.»',
      ] },
      { titel: 'Due numeri accanto', tekst: [
        'Il consiglio teneva seduta come sempre: cinque uomini, uno scrivano, e il brusio della gente che aspettava che toccasse a lei.',
        'Questa volta Tala non era sola.',
        'Alla sua sinistra c’era sua madre, con il vestito che metteva solo quando c’era qualcosa di brutto o qualcosa di bello. Alla sua destra c’era Amanar, e dietro Amanar c’erano quattro uomini della fucina che non c’entravano niente ed erano lì lo stesso.',
        'Più in là, contro una colonna, c’era Yidir.',
        'Il più vecchio del consiglio — quello con la faccia come un fico secco — guardò il gruppo e inarcò le sopracciglia.',
        '«Ancora tu», disse a Tala.',
        '«Ho contato», disse Tala.',
        'L’aveva scritto su un pezzo di cuoio, perché il cuoio non vola via. Lo lesse. Quello che avevano prodotto. Quello che era stato venduto in città. Quello che c’era nel magazzino. E poi quello che secondo le tavolette della porta era uscito dalla città a nome di suo padre.',
        'Due numeri.',
        'Quando ebbe finito, il silenzio fu di un genere diverso dalla volta prima.',
        'Marcus si fece avanti. Era ancora tranquillo, ma non più allo stesso modo.',
        '«Una bambina ha guardato nelle tavolette della città», disse. «È vietato.»',
        '«Le ho portate io», disse Amanar.',
        'Il silenzio si fece ancora più grande.',
        'Il più vecchio del consiglio si voltò verso lo scrivano accanto a lui.',
        '«Vai a prenderle.»',
        'Ci volle molto. Non se ne andò nessuno. Qualcuno diede uno sgabello alla madre di Tala e lei non ci si sedette.',
        'Quando le tavolette arrivarono, lo scrivano lesse ad alta voce cosa c’era scritto, e un altro uomo sommò con dei sassolini su una tavola, e tutta la piazza sentì.',
        'Centodiciassette.',
        'Il più vecchio guardò a lungo i numeri, e poi Marcus, e poi di nuovo i numeri.',
        '«Chi scrive alla porta nord?» chiese.',
        '«Cambia», disse Marcus.',
        '«E chi decide chi scrive?»',
        'Marcus non rispose.',
        'Il più vecchio sospirò, e fu il sospiro di un uomo che capisce una cosa che avrebbe preferito non capire, e che sa che adesso deve farci qualcosa.',
        '«Siediti», disse a Tala. «Non tu, Marcus. Tu resti in piedi.»',
      ] },
      { titel: 'Quel che resta', tekst: [
        'Ci vollero ancora tre settimane prima che cambiasse davvero qualcosa, e fu la lezione più lunga di quell’estate: che la verità non funziona come in una storia, dove la dici e tutti annuiscono.',
        'Venne un uomo dalla città madre di Volubilis a controllare i registri. Furono ascoltate delle persone. Due volte non si disse niente e una volta si disse una cosa che nessuno si aspettava: la guardia della porta nord, un ragazzo di diciannove anni, crollò alla terza domanda e raccontò tutto.',
        'Marcus sparì prima che la cosa si chiudesse. La sua casa restò vuota un mese e poi fu data a un altro.',
        'Il padre di Tala non guarì più, non del tutto. In autunno poté di nuovo sedersi nel cortile e sentire scricchiolare il frantoio, e di quello sembrava contento. Chiedeva i numeri e lei glieli diceva. Si fece raccontare tre volte cos’era successo in piazza, e la terza volta pianse, e lei non l’aveva mai visto piangere.',
        'Il raccolto andò al porto. Cento giare. Tornava.',
        'La settimana dopo passò Yidir con sua nonna.',
        'Sua nonna era piccola e vecchia e aveva gli occhi di chi guarda molto più in là di dove sta. Disse che se ne andava: tornava dalla sua famiglia, ai pascoli in montagna, prima dell’inverno. Lo disse come se parlasse di una passeggiata.',
        '«Yidir viene con me», disse. «Per un po’.»',
        'Tala guardò Yidir. Yidir si guardò le mani.',
        '«Quanto è un po’?» chiese.',
        '«Lo si sa solo dopo», disse sua nonna.',
        'Quella sera Tala si sfilò il cordoncino dalla testa.',
        'La chiave era calda, come sempre. Otto punte nella testa, una stella. Suo nonno l’aveva forgiata in una fucina che adesso non esisteva più.',
        'La tenne in mano e pensò a quello che aveva detto suo padre. *Quella porta non si apre con nient’altro.*',
        'La diede a Yidir.',
        '«Non si può», disse lui subito.',
        '«Tu mi hai creduta quando non mi credeva nessuno.»',
        '«Non vale una chiave.»',
        '«È la mia chiave», disse Tala. «Decido io quanto vale.»',
        'Yidir la teneva come se scottasse.',
        '«E che ci faccio?»',
        '«Non lo so», disse Tala. «Regalarla, credo. A qualcuno a cui credi.»',
        'Partirono la mattina dopo, con tre asini e un cane, verso le colline, e Tala salì sul tetto delle terme per guardarli finché non si videro più.',
        'Allora non sapeva ancora che era un bene che la chiave se ne andasse.',
        'Perché Walili non sarebbe stata lì per sempre. Il terremoto venne molto più tardi, e la città fu svuotata lentamente — pietra dopo pietra, finché non restarono che le colonne, i frantoi e i pavimenti a mosaico che ci sono ancora oggi, all’aperto, vicino a Meknès.',
        'Tutto quello che stava nelle case è sparito.',
        'Solo la chiave no.',
      ] },
    ],
  },
  2: {
    titel: 'L’altra sponda',
    jaar: '711',
    waar: 'Tangeri e lo stretto verso nord',
    verteller: 'Ayyur, dodici anni, figlio di un pastore, si occupa dei cavalli',
    flap: 'Un esercito attraversa il mare verso una terra che nessuno conosce. Ayyur può venire per badare ai cavalli — e scopre che anche l’uomo che tutti seguono ha paura.',
    sleutel: 'La chiave pende dai finimenti di un cavallo e resta sull’altra sponda, nella sacca di uno scrivano.',
    echt: [
      'Tariq ibn Ziyad era un condottiero amazigh che nel 711 attraversò lo stretto con un esercito verso il sud dell’attuale Spagna.',
      'La rocca dove sbarcò porta ancora il suo nome: Jabal Tariq, la montagna di Tariq — deformato in Gibilterra.',
      'La maggior parte del suo esercito era fatta di soldati amazigh del Nord Africa.',
      'La storia secondo cui avrebbe fatto bruciare le navi è stata messa per iscritto solo secoli dopo e gli storici non la considerano un fatto.',
    ],
    verzonnen: [
      'Ayyur e la sua famiglia non sono esistiti.',
      'Le conversazioni con Tariq sono inventate. Del suo carattere non si sa quasi nulla.',
      'Che la chiave abbia fatto quel viaggio è inventato.',
    ],
    hoofdstukken: [
      { titel: 'Il ragazzo dei cavalli', tekst: [
        'Ayyur aveva dodici anni ed era bravo in due cose: i cavalli e l’attesa.',
        'La seconda l’aveva imparata da suo padre, che pascolava le pecore sulle colline dietro Tangeri e sapeva stare zitto dall’alba al tramonto senza che gli costasse nulla. La prima non l’aveva imparata da nessuno. Ai cavalli semplicemente piaceva, ed era così da quando camminava.',
        'Per questo adesso era nell’accampamento fuori dalle mura e non sulle colline.',
        'In inverno suo padre aveva perso trenta pecore per il freddo e il resto per i debiti. Non c’era più un gregge da pascolare. C’era però un esercito, e un esercito ha cavalli, e i cavalli hanno bisogno di qualcuno che stia con loro la notte.',
        'Pagavano in cibo e in rame. Non molto rame.',
        'Ayyur non si lamentava. Poteva dormire con i cavalli e ormai li conosceva tutti e quarantasette per nome, anche i nomi che si era inventato lui perché nessuno glieli aveva detti.',
        'In quelle settimane di marzo l’accampamento si era riempito come non l’aveva mai visto. Prima cento uomini, poi cinquecento, poi tanti che contare non si poteva più. Venivano dal sud e dall’est, dalle montagne e dalla costa. Quasi tutti erano amazigh come lui. Parlavano la sua lingua, con altre parole per le stesse cose, e ridevano di come le diceva lui.',
        'C’erano anche quelli che parlavano arabo. Non molti. Qualche centinaio.',
        'E tutti aspettavano.',
        'Cosa, lo sapevano: le navi. A cosa servissero le navi, se ne parlava nel modo in cui gli uomini parlano di una cosa che non sanno — con grande sicurezza, e ogni giorno in modo diverso.',
        '«L’altra sponda», diceva uno.',
        '«Sull’altra sponda non c’è niente», diceva un altro. «Acqua e poi ancora acqua.»',
        '«Sull’altra sponda c’è un re», diceva un terzo. «Con una corona d’oro così pesante che non riesce a portarla.»',
        'Ayyur spazzolava il fianco di una giumenta che chiamava Tafukt, che vuol dire sole, e ascoltava tutti e tre.',
        'L’altra sponda l’aveva vista. A Tangeri l’avevano vista tutti. In una giornata limpida all’orizzonte c’era una striscia di terra, e sopra una rocca che sembrava messa lì da qualcuno.',
        'Potevi guardarla senza pensarci mai, per tutta la vita.',
        'Finché qualcuno non cominciò a radunare navi.',
      ] },
      { titel: 'L’uomo che non era grande', tekst: [
        'Vide Tariq per la prima volta di martedì, dai cavalli, e per mezzo minuto non seppe chi aveva davanti.',
        'L’uomo non era grande. Quella fu la prima cosa.',
        'Ayyur si era immaginato qualcuno come nelle storie: una testa più alto di tutti, un mantello che striscia dietro, dieci uomini attorno. Quest’uomo era solo, con una giacca impolverata e senza ornamenti, e stava guardando Tafukt come guarda un cavallo chi di cavalli se ne intende.',
        '«Chi la monta?» chiese.',
        '«Nessuno», disse Ayyur. «Non si fa montare.»',
        '«Perché no?»',
        '«Non lo so. Credo che sia caduta una volta. Prima di arrivare qui.»',
        'L’uomo posò la mano sul collo della giumenta e ce la lasciò senza accarezzarla.',
        '«E con te?»',
        '«Con me sta tranquilla.»',
        '«Allora non ha paura delle persone», disse l’uomo. «Ha paura di quello che le persone le hanno fatto.»',
        'Guardò Ayyur per la prima volta.',
        '«Come ti chiami?»',
        '«Ayyur.»',
        '«La luna.» L’uomo annuì, come se fosse un nome ragionevole. «Fa’ in modo che fra due settimane stia ancora così.»',
        'Poi se ne andò.',
        'Ci volle fino a sera prima che qualcuno lo dicesse ad Ayyur, e quando lo seppe si sedette su una cassa e ci rimase un bel po’.',
        'Tariq ibn Ziyad. Amazigh, come lui. Di una famiglia che non conosceva nessuno. Governatore di Tangeri, e l’uomo che doveva portare oltre l’acqua l’esercito steso su quella spiaggia.',
        'Era stato lì a guardare un cavallo.',
        '«Viene tutti i giorni», disse Sa3id, il vecchio cavaliere con la gamba malandata, che intanto si era seduto accanto a lui perché si sedeva sempre accanto a qualcuno. «Tutti i giorni dai cavalli e tutti i giorni dalle navi. Credo che non dorma.»',
        '«Non è grande», disse Ayyur.',
        'Sa3id rise così forte che dovette tossire.',
        '«No, ragazzo», disse. «Non lo è.»',
      ] },
      { titel: 'Quattro navi per settemila uomini', tekst: [
        'Il problema era semplice e nessuno sapeva risolverlo.',
        'Su quella spiaggia c’erano settemila uomini, più i cavalli, più le armi, più il cibo per settimane. E c’erano quattro navi.',
        'Ayyur sentì Sa3id calcolare una volta quante volte quelle quattro navi dovessero andare avanti e indietro, e Sa3id arrivò a un numero di cui rise lui stesso, e poi rimase zitto.',
        '«Che c’è?» chiese Ayyur.',
        '«Niente.»',
        '«Sa3id.»',
        'Il vecchio si sfregò il ginocchio, cosa che faceva quando pensava.',
        '«Se hai quattro navi», disse, «il primo carico è il più pericoloso. Quello sta sull’altra sponda, da solo, senza nessuno dietro. E se va storto qualcosa, le navi sono via per due giorni.»',
        'Guardò il mare.',
        '«Non vorrei essere nel primo carico.»',
        'Le navi non erano loro. Lo sapeva tutto l’accampamento. Venivano da un uomo dell’altra sponda, un signore di Ceuta che era in lite con il proprio re e che per questo li aiutava. Il suo nome si pronunciava in dieci modi e non l’aveva mai visto nessuno.',
        '«Perché ci aiuta?» chiese Ayyur.',
        '«Perché vuole qualcosa.»',
        '«E cosa?»',
        '«Lo sapremo solo quando gliel’avremo dato», disse Sa3id.',
        'In quelle settimane Ayyur imparò sulla guerra più di quanto avesse mai voluto sapere, e quasi niente riguardava il combattere. Riguardava l’acqua nelle botti che dopo quattro giorni andava a male. Quanto orzo mangia un cavallo al giorno e quanto fa per settecento cavalli. Uomini che si ammalavano di attesa e litigavano per niente.',
        'Una mattina ci fu una rissa al pozzo. Due uomini di tribù diverse, per un secchio.',
        'Tariq venne di persona. Li fece alzare tutti e due, parlò piano con loro, e li mandò via insieme con lo stesso ordine: un secchio, due uomini, tutto il giorno a portare acqua ai cavalli.',
        'La sera mangiavano seduti l’uno accanto all’altro.',
        'Sa3id vide come guardava Ayyur.',
        '«*Questo* è il punto», disse. «*Questo* è il motivo per cui lo seguono. Non perché sa combattere. Combattere sanno tutti.»',
      ] },
      { titel: 'La notte prima', tekst: [
        'La sera prima della prima traversata era calda e non c’era vento, e quest’ultima cosa era esattamente il problema.',
        'Ayyur non riusciva a dormire. Era sdraiato fra i cavalli, con la testa su una sella che odorava di cuoio e di sudore, e guardava le stelle che si vedevano fra i teli delle tende.',
        'Accanto a lui c’era Sa3id, e neanche lui dormiva.',
        '«Hai paura?» chiese Ayyur.',
        '«Sì», disse subito Sa3id.',
        'Ayyur non se l’aspettava. Si aspettava che il vecchio ridesse e dicesse qualcosa sulle venti battaglie in cui era stato.',
        '«Chi dice di no mente», disse Sa3id. «Oppure è stupido. Gli uomini stupidi in una barca non servono a niente.»',
        'Si mise seduto, lentamente, con la mano sul ginocchio.',
        '«Lo sai cosa faccio quando ho paura?»',
        '«No.»',
        '«Dico il nome di Dio e poi faccio la cosa successiva che va fatta. Non tutta la cosa. La cosa successiva.»',
        'Ayyur ci pensò su.',
        'Nel suo villaggio la fede era una cosa degli ultimi anni. Sua nonna non ce l’aveva, sua madre a metà, suo padre del tutto — a modo suo, in silenzio, senza dirne granché. Nell’accampamento era dappertutto: uomini che smettevano quello che stavano facendo e si voltavano nella stessa direzione, e poi riprendevano come se non fosse successo niente.',
        'Lui non l’aveva mai capito bene. Nessuno si era preso la briga di spiegarglielo, perché a chi dorme con i cavalli nessuno spiega niente.',
        '«Sa3id», disse. «Io non so come si fa.»',
        'Il vecchio lo guardò nel buio.',
        '«Cosa non sai?»',
        '«Tutto. Le parole. Quando. Come si sta.»',
        'Sa3id tacque abbastanza a lungo da mettere a disagio Ayyur.',
        '«Domani mattina», disse poi, «ti metti accanto a me. Fai quello che faccio io. Non devi dire niente che non sai.»',
        '«Basta così?»',
        '«Per domattina sì», disse Sa3id. «Il resto lo impari da qualcuno che se ne intende più di me. Io sono solo un cavaliere con un ginocchio rotto.»',
        'Si sdraiò di nuovo.',
        '«Adesso dormi. Domani sarà lungo.»',
      ] },
      { titel: 'La spiaggia all’alba', tekst: [
        'Andarono all’acqua nel buio, e quando si fece chiaro la spiaggia era piena.',
        'Ayyur non aveva mai visto tanta gente ferma tutta insieme.',
        'Stavano in file, spalla a spalla, dalle dune fino alla battigia. Uomini che non si capivano fra loro perché venivano da villaggi lontani dieci giorni di cammino, nella stessa direzione, nello stesso ordine.',
        'Lui stava accanto a Sa3id e faceva quello che faceva Sa3id, e per i primi tre tempi si sentì ridicolo e dopo non più.',
        'Quella mattina il mare era come un lago.',
        'Quando finì, per un momento restò il silenzio. Poi ricominciarono a parlare tutti insieme e tornò a essere un accampamento.',
        'Ayyur portò otto cavalli alla battigia. Era il suo compito: otto, nel primo carico, con Sa3id accanto una volta dall’altra parte.',
        'Tafukt era uno di quelli.',
        'Cavalli e barche non vanno d’accordo. Lo sapeva, e quella mattina imparò quanto. Dovevano far salire gli animali in barca su una passerella, e la passerella si muoveva, e la barca si muoveva diversamente dalla passerella.',
        'Due cavalli si rifiutarono. Un terzo andò nel panico a metà e buttò a terra un uomo.',
        'Tafukt salì la passerella dietro ad Ayyur come se fosse un sentiero fra le colline.',
        'Una volta dentro le tenne la testa, e le parlò nella sua lingua di cose che non c’entravano niente: di suo padre, del gregge che non c’era più, del nome che le aveva dato e del perché.',
        'Qualcuno gli batté la mano sulla spalla.',
        'Alzò gli occhi.',
        'Tariq era nella barca, in mezzo ai cavalli, con la mano sul bordo.',
        '«Continua a parlarle», disse. «Per tutta la traversata. Non smettere.»',
        '«Sì», disse Ayyur.',
        'Tariq guardò la passerella, dove mancavano ancora il quarto e il quinto.',
        '«E Ayyur», disse, senza voltarsi. «Se va male sull’acqua, tagliale la corda. Non tenerla. Un cavallo sa nuotare. Un ragazzo con una corda al braccio no.»',
      ] },
      { titel: 'Acqua', tekst: [
        'Lo stretto nel punto più stretto è quattordici chilometri.',
        'Ayyur non lo sapeva. Sapeva solo che la spiaggia dietro di lui si faceva più piccola e che passò un’ora in cui non successe niente, e poi un’altra.',
        'Non andò male. Fu questa la cosa strana.',
        'Si era immaginato tutto: onde, grida, acqua oltre il bordo. Invece c’era il sole, il rumore dei remi, e un beccheggio esattamente sufficiente a far penzolare oltre la fiancata tutti quelli che non erano abituati alle barche.',
        'Parlò a Tafukt finché non gli venne la voce roca.',
        'Ogni tanto si voltava.',
        'Dietro di loro c’era la costa dove era nato: le colline dove avevano camminato le pecore, la città con le mura, il punto dove suo padre adesso stava probabilmente seduto a guardare senza dire niente.',
        'Non si era congedato. Non davvero. Aveva detto che sarebbe tornato entro un mese, e suo padre aveva annuito, e tutti e due avevano fatto finta che fosse una frase che significava qualcosa.',
        'Davanti a lui la rocca si faceva più grande.',
        'Era diversa da come sembrava da Tangeri. Da lontano pareva un triangolo. Da vicino era un muro di pietra che usciva dritto dall’acqua, grigio e nudo, con i gabbiani che ci volteggiavano intorno come polvere.',
        'Non c’era nessuno sopra. Non c’era niente sopra. Era solo una rocca.',
        'Accanto a lui Sa3id disse qualcosa.',
        '«Cosa?»',
        '«Ho detto: guarda bene.» Il vecchio si appoggiò con le braccia al bordo. «Fra cent’anni qualcuno chiederà a tuo nipote da dove viene la sua famiglia, e lui dirà il nome di questo coso.»',
        '«Non ha un nome.»',
        'Sa3id sogghignò con i suoi denti storti.',
        '«Non ancora», disse.',
        'Le barche toccarono terra su una spiaggia ai piedi della rocca. Non c’era nessuno. Nessun esercito, nessun posto di guardia, nessun villaggio. Solo ciottoli, alghe e il rumore del mare.',
        'Settecento uomini e sessantadue cavalli stavano su una costa straniera, e le navi ripartirono subito per il carico successivo.',
        'Due giorni da soli, aveva detto Sa3id.',
        'Ayyur portò i cavalli più in alto, all’erba dietro i ciottoli, e cominciò a tracciare una linea nella sabbia per il recinto. La cosa successiva che andava fatta.',
        'Dietro di lui Tariq saliva sulla prima altura per vedere com’era la terra.',
      ] },
      { titel: 'Due giorni da soli', tekst: [
        'La prima notte sull’altra sponda non dormì nessuno.',
        'Non per la paura, anche se c’era. Perché settecento uomini appena sbarcati pensano tutti nello stesso momento che devono fare qualcosa, e non c’è nessuno che sappia cosa.',
        'Fu montato un recinto e poi spostato. Fu acceso un fuoco e poi spento, perché qualcuno disse che un fuoco si vede da lontano. Furono messe sentinelle in posti dove non c’era niente da sorvegliare.',
        'Ayyur fece quello che faceva sempre. Portò i cavalli all’erba, li contò, li ricontò, e si sdraiò con loro.',
        'Sessantadue. Tornava.',
        'Sopra di lui la rocca stava come un muro che qualcuno avesse lasciato a metà.',
        'Verso mattina venne freddo, come viene freddo al mare: non pungente, ma dappertutto insieme. Ayyur si tirò addosso la coperta e ascoltò i cavalli respirare intorno a lui, e pensò a suo padre sulle colline dietro Tangeri, sei ore di navigazione e tutta una vita più in là.',
        'Poi qualcuno cominciò a chiamare.',
        'Si tirò su di scatto, perché chiamare di solito vuol dire che sta arrivando qualcosa.',
        'Ma non arrivava niente. Era un uomo salito su una pietra al margine dell’accampamento, con la faccia verso est, che chiamava come avevano chiamato anche all’accampamento di Tangeri, ogni mattina, da quando Ayyur ci lavorava.',
        'Degli uomini si alzarono. Non tutti. Abbastanza per vederlo.',
        'Si misero in file sui ciottoli, e si inchinarono, e si rialzarono, e si inchinarono di nuovo, e sull’acqua suonava come se la spiaggia respirasse.',
        'Ayyur restò seduto con i cavalli.',
        'Non ne aveva paura. Semplicemente non lo capiva, e nessuno si era preso la briga di spiegarglielo, perché al ragazzo che dorme con i cavalli nessuno spiega niente.',
        'Quello che vide invece fu questo: dopo erano più tranquilli. Tutta la notte avevano girato per l’accampamento come galline, e dopo quel quarto d’ora camminavano come uomini con un compito.',
        'Fu la prima cosa che capì della nuova fede. Non cosa c’era dentro. Cosa faceva.',
        'Le navi tornarono quel pomeriggio per il secondo carico, e i due giorni da soli si rivelarono essere stati uno e mezzo.',
      ] },
      { titel: 'Il pastore e la capra', tekst: [
        'Il quarto giorno arrivò qualcuno.',
        'Arrivò dall’alto, dal pendio, con un bastone e con undici capre, ed entrò nell’accampamento come se fosse sempre stato lì.',
        'Tre uomini lo presero nello stesso momento.',
        'Ayyur lo vide dal recinto e pensò: è vecchio. Quella fu la prima cosa. Era vecchio, e magro, e teneva il bastone come si tiene una cosa che si tiene da quarant’anni.',
        'Lo portarono alla tenda. Arrivò un uomo che sapeva il latino, e gli parlò, e il vecchio rispose in qualcosa che non era latino.',
        'Poi arrivò uno che parlava berbero, della stessa zona di Ayyur, e ci provò, e il vecchio lo guardò come se stesse ascoltando un uccello.',
        'Alla fine si fece a gesti.',
        'Le capre erano sue. Il pendio era suo, cioè: ci camminava con le capre da tutta la vita, che è la stessa cosa. Aveva visto le navi. Non aveva avvertito nessuno, perché chi doveva avvertire, e di cosa.',
        'Quest’ultima cosa gli fu chiesta tre volte e tre volte rispose lo stesso.',
        'Lo lasciarono andare.',
        'Sa3id lo trovò stupido e lo disse ad alta voce. «Va al primo villaggio e allora lo sanno.»',
        '«Lo sanno già», disse l’uomo del latino. «Nell’acqua c’erano quattro navi. Lo vedono tutti da Tarifa ad Algeciras.»',
        'Il vecchio risalì il pendio con le sue undici capre e non si voltò.',
        'Ayyur lo guardò finché non sparì dietro il ciglio.',
        'Si era immaginato l’altra sponda come un’altra cosa. Come una terra con un re e una corona e delle mura, oppure come niente, come acqua e poi ancora acqua. Non come un vecchio con le capre che teneva lo stesso bastone degli uomini sulle colline dietro Tangeri.',
        '«E cosa credevi», disse Sa3id quando glielo disse. «Che qui ci fossero le scimmie?»',
        'Ayyur non disse niente, perché a essere onesti non sapeva cosa avesse creduto.',
        'Quella sera il vecchio tornò con due capre a una corda, le lasciò davanti alla tenda e fece un gesto che nessuno capì con precisione ma che capirono tutti.',
        'Lo pagarono in rame. Non molto rame.',
        'Lui lo prese, guardò le monete, le mise via, e risalì il pendio.',
        'Così cominciò la conquista della terra dell’altra sponda: con due capre e un prezzo onesto.',
      ] },
      { titel: 'In cosa crede Sa3id', tekst: [
        'Sa3id aveva i denti storti, una cicatrice che gli attraversava il sopracciglio e un’opinione su tutto.',
        'Era di Tlemcen, aveva ventotto anni, ed era lì dall’inizio. Aveva trovato Ayyur il primo giorno dai cavalli e poi aveva continuato a passare, per motivi che Ayyur non capì mai del tutto. Forse perché il ragazzo ascoltava. Forse perché non ascoltava nessun altro.',
        'La settima sera Ayyur lo chiese finalmente.',
        '«Perché chiamate la mattina?»',
        'Sa3id alzò gli occhi dalla cinghia che stava ingrassando.',
        '«È la chiamata», disse.',
        '«Questo lo so. Perché?»',
        'Sa3id ci rifletté, cosa insolita per lui.',
        '«Perché è ora», disse poi. «Cinque volte al giorno è ora. Quando si fa chiaro, quando il sole è più alto, quando la tua ombra è più lunga di te, quando il sole è andato via, e quando è buio.»',
        '«E poi?»',
        '«E poi smetti quello che stai facendo e stai fermo.»',
        '«Per cosa?»',
        '«Per Dio.» Sa3id fece spallucce. «Ce n’è uno. Di più non chiederlo a me, perché non sono un dotto. Sono un uomo con un cavallo e una lancia.»',
        'Ayyur tacque un momento.',
        '«Mio padre dice che nella sorgente del nostro villaggio abita qualcosa», disse. «Ogni primavera ci lascia del latte.»',
        'Lo disse con la tensione di chi non sa se lo prenderanno in giro.',
        'Sa3id non rise.',
        '«Allora tuo padre dice così», disse. «Io dico quello che dico. Né tuo padre né io abbiamo tempo per andare a fondo, quindi facciamo il nostro lavoro.»',
        'Riprese con la cinghia.',
        '«Anche noi ce l’abbiamo da poco», disse dopo. «Mio nonno non ne sapeva niente. Mio padre ha cominciato e ne sapeva la metà. Io ne so un po’ più di lui e meno dell’uomo che chiama la mattina. Fra cent’anni ne sapranno tutto e penseranno che sia sempre stato così.»',
        'Tenne la cinghia contro la luce.',
        '«Funziona così con tutto», disse.',
        'Ayyur ci pensò ancora a lungo, più a lungo di quanto Sa3id avesse probabilmente inteso.',
        'Non era andato a mettersi con loro, né quella sera né le settimane dopo. Ma da allora smise di restare seduto con i cavalli come se non stesse succedendo niente. Si alzava quando cominciava. Era tutto quello che faceva. Si alzava, e aspettava che finisse, e poi riprendeva.',
        'Gli sembrava il minimo per una cosa davanti a cui settecento uomini si fermano.',
      ] },
      { titel: 'Tafukt', tekst: [
        'La seconda settimana morì un cavallo.',
        'Non fu Tafukt. Fu uno stallone baio senza nome, dell’ultimo carico, che era rimasto con una zampa incastrata nei ciottoli mentre lo tiravano giù dalla barca.',
        'L’avevano sentito. L’aveva sentito tutta la spiaggia.',
        'Sa3id lo fece con un coltello e lo fece in fretta, e non lasciò che lo facesse Ayyur, anche se Ayyur si era offerto perché era un cavallo di cui doveva occuparsi lui.',
        '«No», aveva detto Sa3id. «Tu hai dodici anni.»',
        '«Tredici fra due mesi.»',
        '«Allora lo farai fra due mesi.»',
        'Dopo, Ayyur restò seduto al recinto tutto il resto del pomeriggio senza fare niente, cosa che non gli capitava mai.',
        'Non era per lo stallone. Aveva visto morire delle pecore, molte pecore, e un inverno così tante che aveva smesso di contare.',
        'Era perché si era reso conto che a casa non l’avrebbe saputo nessuno.',
        'A casa nessuno sapeva dov’era. Non aveva potuto dirlo, perché non sapeva scrivere e nessuno andava da quella parte. Se domani fosse morto su una spiaggia dell’altra sponda, suo padre sulle colline dietro Tangeri avrebbe aspettato fino all’inverno e poi avrebbe pensato che era scappato.',
        'Tafukt gli spinse il muso contro la spalla.',
        'Restò seduto finché non fu buio e si alzò quando venne la chiamata, come faceva adesso, e poi si mise al lavoro.',
        'La mattina dopo andò a cercare lo scrivano.',
        'Lo scrivano era un uomo piccolo con le dita d’inchiostro che passava la giornata seduto su una pietra a scrivere cose che nessuno gli chiedeva di scrivere. Si chiamava Yunus e veniva da Kairouan.',
        '«Mi scrivi una cosa?»',
        'Yunus alzò gli occhi. «Per chi?»',
        '«Per mio padre.»',
        '«Tuo padre sa leggere?»',
        'Ayyur tacque.',
        '«No», disse poi.',
        '«Conosce qualcuno che sa?»',
        '«L’uomo che riscuote le tasse viene due volte all’anno. Lui sa.»',
        'Yunus ci pensò, poi tirò fuori dalla cassa un frammento di tavoletta e se lo mise sul ginocchio.',
        '«Dimmi.»',
        'Ayyur disse: «Ayyur è vivo. Ayyur sta con i cavalli. Ayyur torna.»',
        'Yunus scrisse, guardò il risultato, e disse: «Tutto qui?»',
        '«Cos’altro ci deve stare?»',
        'Lo scrivano fece spallucce e mise il frammento nella cassa con le lettere che sarebbero tornate indietro con la barca successiva.',
        'Era la prima volta in vita sua che il nome di Ayyur stava scritto da qualche parte.',
        'Ci ripensò tutto il resto della giornata, mentre pareggiava zoccoli e portava acqua, e si sorprese a trovarlo bello in un modo di cui quasi si vergognava.',
      ] },
      { titel: 'La montagna di Tariq', tekst: [
        'La terza settimana la rocca ebbe il suo nome, e Ayyur c’era quando successe, anche se in quel momento non lo sapeva.',
        'Ormai c’era un accampamento. C’erano recinti, c’era un pozzo che avevano scavato, c’erano tende in file. Erano arrivati quattro carichi e ne sarebbero arrivati altri.',
        'Yunus stava sulla sua pietra con una tavoletta sulle ginocchia, e chiese all’uomo accanto a lui come doveva scrivere il posto.',
        '«Quale posto?»',
        '«Questo. Dove siamo. Devo scrivere dov’è l’esercito.»',
        'L’uomo fece spallucce.',
        '«Alla montagna», disse.',
        '«Quale montagna?»',
        'Guardarono tutti e due in alto.',
        '«La montagna di Tariq», disse l’uomo, e lo disse come si dice una cosa ovvia.',
        'Yunus lo scrisse. Jabal Tariq.',
        'Ayyur era due passi più in là con un secchio in mano e lo sentì, e pensò: va bene, e tirò dritto.',
        'Queste cose vanno così. Non c’è mai nessuno che pensi: questo è il momento. Il momento ha l’aspetto di uno scrivano che ha bisogno di una parola e di un soldato che non ha voglia.',
        'Milletrecento anni dopo quel nome è ancora su ogni carta geografica del mondo, consumato fino a diventare una cosa che nessuno riconosce più, e nessuno di quelli che lo pronunciano sa che c’è stato un uomo che si chiamava Tariq.',
        'Ayyur portò il secchio ai cavalli.',
      ] },
      { titel: 'L’esercito va a nord', tekst: [
        'Partirono una mattina di luglio, e ci volle dalla prima luce a ben oltre mezzogiorno perché l’ultima fila sparisse dalla vista.',
        'Ayyur non andò.',
        'Gliel’avevano detto due giorni prima, Sa3id, che lo portò come portava tutto: senza giri di parole e nell’ordine sbagliato.',
        '«Tu resti qui.»',
        '«Perché?»',
        '«Perché restano cento cavalli e qualcuno se ne deve occupare.»',
        '«Ci sono altri uomini.»',
        '«Non ci sono altri uomini che sanno tutti i nomi.»',
        'Ayyur non sapeva se fosse un complimento o un modo per tenerlo fuori dai combattimenti. Sospettava la seconda cosa, e ne era insieme arrabbiato e sollevato, e sentire quelle due cose l’una accanto all’altra è qualcosa per cui a dodici anni non hai ancora una parola.',
        'Sa3id invece andò.',
        'La mattina della partenza passò dal recinto con il suo cavallo a mano — un castrone grigio di cui Ayyur si occupava da tre mesi e che chiamava Amellal, che vuol dire bianco, che non era vero e che il castrone non aveva mai contestato.',
        '«Fallo bere prima che faccia caldo», disse Ayyur.',
        '«Lo so.»',
        '«Non beve dall’acqua ferma. La devi muovere con la mano.»',
        '«Anche questo lo so.»',
        'Rimasero lì tutti e due come se dovesse arrivare ancora qualcosa.',
        '«Se c’è qualcosa», disse Sa3id, «vai da Yunus. Non è coraggioso ma è furbo, e qui la furbizia vale di più.»',
        '«Va bene.»',
        'Sa3id montò, guardò ancora una volta in basso e disse: «Non sei un cattivo ragazzo, Ayyur. Sta’ lontano dall’acqua, non sai nuotare.»',
        'Poi se ne andò a cavallo.',
        'Ayyur lo vide fino a metà della seconda collina e poi non più, perché da lì in avanti era una sola nuvola di polvere e non erano più persone.',
        'Tornò dai cavalli.',
        'Erano centoquattro. Li contò due volte.',
      ] },
      { titel: 'Anche aspettare è qualcosa', tekst: [
        'Le settimane che seguirono furono le più lunghe della sua vita e non ci successe quasi niente.',
        'È questa la cosa strana della guerra, scoprì Ayyur: per quasi tutti è attesa. Le storie parlano del giorno in cui è successo. Nessuno racconta delle quattro settimane prima, in cui cerchi erba per centoquattro cavalli su un pendio dove l’erba è finita.',
        'In quelle settimane imparò tre cose.',
        'La prima la imparò dal vecchio delle capre, che passava ogni pochi giorni e poi ogni giorno, e che alla fine passava i pomeriggi al recinto senza che nessuno sapesse spiegare perché. Si chiamava in un modo che Ayyur non è mai riuscito a dire bene. Indicava le cose e diceva la parola, e Ayyur la ripeteva, e il vecchio lo correggeva, e andò avanti così per tutta l’estate.',
        'Acqua. Pietra. Capra. Montagna. Bambino. Pane.',
        'Così si impara una lingua. Non da un libro. Da un vecchio che non ha di meglio da fare.',
        'La seconda la imparò da Yunus. Un pomeriggio gli chiese, mezzo per scherzo, se lo scrivano poteva insegnargli le lettere, e Yunus disse: «No», e tre giorni dopo era seduto accanto a lui con un bastone nella sabbia.',
        'Andava piano. Ayyur era negato. La mano non faceva quello che la testa pensava e le lettere venivano storte, come una cosa toccata da un animale.',
        'Dopo un mese sapeva scrivere il proprio nome.',
        'Quella sera lo scrisse venti volte nella sabbia accanto al recinto e lo cancellò venti volte, e la ventunesima lo lasciò lì finché non se lo portò via il vento.',
        'La terza non la imparò da nessuno.',
        'Scoprì che alla chiamata non si alzava più soltanto per educazione.',
        'Fu verso agosto. Era accanto a Tafukt, veniva buio, l’uomo sulla pietra cominciò, e Ayyur si accorse che gli faceva piacere che succedesse. Non per quello che veniva detto — ne capiva ancora poco. Per il fatto che in un giorno si tracciasse cinque volte una riga, su una costa dove non conosceva nessuno e nessuno conosceva lui, e che per questo la giornata non fosse una poltiglia ma una cosa con dei pezzi.',
        'Continuava a non mettersi con loro.',
        'Ma quella settimana chiese a Yunus come andavano le parole, e Yunus gliele disse piano, e Ayyur le ripeté, e lo scrivano lo corresse come lo correggeva il vecchio con acqua, pietra, capra.',
        'E in questo libro la cosa finisce qui, perché finì qui.',
        'Cosa ne sia diventato negli anni dopo, non lo sappiamo. Sappiamo solo che cominciò così per migliaia di ragazzi come lui: non con un esercito, non con una battaglia, ma con qualcuno che vedeva una cosa succedere cinque volte al giorno finché non fece parte della giornata.',
      ] },
      { titel: 'La notizia del fiume', tekst: [
        'La notizia arrivò di martedì, con un cavaliere che aveva corso così forte che il suo cavallo non si poteva più salvare.',
        'Ayyur lo capì dal cavallo prima che dall’uomo. Funziona così quando appartieni ai cavalli.',
        'C’era stata una battaglia a un fiume nel sud del paese, a otto giorni da lì. Era durata tre giorni, o cinque, a seconda di chi lo chiedevi. Il re con la corona c’era stato e non c’era più, e su questo le versioni divergevano subito tanto che Ayyur smise di ascoltare.',
        'Quello che in ogni versione era uguale: l’esercito non era stato sconfitto. Proseguiva verso nord. Sarebbero cadute città di cui nessuno nell’accampamento sapeva il nome.',
        'Quella sera sulla spiaggia si esultò.',
        'Ayyur non esultò, perché ancora non aveva sentito quello che voleva sentire.',
        'Lo chiese al cavaliere, che era troppo stanco per essere cortese.',
        '«Sa3id di Tlemcen. Cavallo grigio. Cicatrice sul sopracciglio.»',
        'L’uomo lo guardò come se gli avesse chiesto di una pecora sola in un gregge di diecimila.',
        '«Ragazzo», disse. «Non so con certezza nemmeno il nome del re.»',
        'Tre settimane dopo arrivò un secondo cavaliere, e non lo sapeva neanche lui.',
        'In ottobre tornò un carro con dei feriti e con uomini che non volevano più, e Ayyur passò in rassegna tutti e ventotto e lo chiese ventotto volte.',
        'Il venticinquesimo lo conosceva.',
        '«Sa3id», disse. «Sì. Al fiume.»',
        'Ayyur aspettò.',
        '«Quando l’ho visto era vivo», disse l’uomo. «Poi sono caduto e non ho visto più niente.»',
        'Fu tutto. È tutto quello che Ayyur ha mai saputo, ed è anche tutto quello che sappiamo noi, perché dei settemila uomini che quell’anno attraversarono lo stretto quattro sono noti per nome e il resto è polvere.',
        'Ayyur tornò al recinto.',
        'Amellal non c’era. Non c’era già da tre mesi, e ogni volta ci guardava lo stesso.',
        'Prese l’acqua, la mosse con la mano come si fa per un cavallo che non beve dall’acqua ferma, e la diede a un altro animale.',
      ] },
      { titel: 'La cassa', tekst: [
        'A fine ottobre Yunus attraversò l’accampamento con una cassa sotto il braccio, in cerca di qualcuno che sapesse andare a cavallo e conoscesse la strada lungo la costa.',
        'Non c’era più nessun altro. Era questa la risposta onesta alla domanda del perché fosse finito da Ayyur.',
        'La cassa doveva andare a nord, in un posto dove l’esercito aveva messo su un accampamento invernale. Dentro c’erano tavolette, e lettere, e una sacca di cuoio con piccole cose che i soldati avevano consegnato per non perderle — e che non erano venuti a riprendersi, il che di quei soldati dice tutto quello che non vuoi sapere.',
        '«Quanto ci vuole?» chiese Ayyur.',
        '«Sei giorni. Otto se piove.»',
        '«E poi?»',
        'Yunus lo guardò.',
        '«E poi sei lì», disse. «E lì c’è più che qui.»',
        'Ayyur caricò la cassa su Tafukt.',
        'Mentre la legava la sacca si rovesciò e ne rotolò fuori qualcosa per terra.',
        'Era di bronzo, lungo come la sua mano, e in cima aveva una testa con otto punte. Come una stella.',
        '«Cos’è?» chiese.',
        'Yunus la guardò appena.',
        '«Una chiave», disse. «Era già nella sacca quando me l’hanno data. Nessuno sa di chi.»',
        'Ayyur la tenne un momento in mano. Era calda di sole.',
        'Pensò a una porta da qualche parte, dall’altra parte dell’acqua, che qualcuno si era tirato dietro per l’ultima volta senza sapere che era l’ultima. A una casa che forse era ancora lì. A un uomo che si era imbarcato con una chiave in tasca perché una chiave non la lasci, e che l’aveva consegnata perché nemmeno te la porti dall’altra parte del fiume.',
        'La lasciò riscivolare nella sacca.',
        'Poi la tirò fuori di nuovo, e se la infilò nella propria cintura.',
        'Yunus lo vide e non disse niente.',
        '«Non viene nessuno a riprenderla», disse Ayyur.',
        '«No», disse Yunus. «Non viene nessuno.»',
        'Ayyur strinse la cinghia e montò.',
      ] },
      { titel: 'Verso nord', tekst: [
        'Quel pomeriggio partì lungo la costa, con una cassa, una giumenta e una chiave che non era di nessuno.',
        'All’ultima curva prima della salita si fermò e si voltò.',
        'Sotto di lui l’accampamento stava lì come se ci fosse sempre stato: recinti, tende in file, il pozzo, il fumo di due fuochi. Sette mesi prima erano ciottoli e alghe.',
        'Il vecchio delle capre stava sul ciglio del suo pendio, come ci stava ogni pomeriggio.',
        'Ayyur alzò la mano.',
        'Il vecchio alzò il bastone.',
        'Fu tutto.',
        'Proseguì, e la terra in cui entrava era verde in un modo che non conosceva, con altri alberi e troppa acqua, e con villaggi dove la gente stava lungo la strada e guardava un ragazzo su una giumenta con una cassa.',
        'Li salutava con le parole che aveva imparato dal vecchio. Acqua. Pietra. Pane.',
        'Alcuni ridevano. Una donna gli diede del pane.',
        'Avrebbe dovuto scriverlo, dopo, perché è il genere di cosa che sparisce: che per un ragazzo di dodici anni le prime settimane della conquista di quella terra furono alberi strani, troppa acqua e una donna che gli diede del pane.',
        'Non è mai tornato alle colline dietro Tangeri.',
        'Non fu una decisione. Per quasi nessuno lo è. Venne l’inverno, e c’era lavoro, e c’erano cavalli, e poi era passato un anno e poi un altro, e a un certo punto non è più un viaggio che rimandi ma una vita che hai.',
        'Il frammento con il suo nome è arrivato da suo padre. Questo non lo sappiamo. Lo speriamo.',
        'Quello che sappiamo è che nei secoli successivi milioni di persone hanno attraversato quello stretto, in un senso e nell’altro, e che ogni volta è rimasto indietro qualcuno che aspettava.',
        'La chiave andò a nord, nella cintura di un ragazzo che non l’aveva ricevuta da nessuno.',
        'Dove andò dopo, sta nel libro seguente.',
      ] },
    ],
  },
}
