import type { Hoofdstuk } from './sleutels'

/** Deel 13 — Het jaar dat de koning terugkwam. 1953–1956. */
export const DEEL13_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'De drukkerij', tekst: [
    'Nadia was veertien en ze rook naar inkt, en dat is haar hele jeugd in één zin.',
    'Haar vader had een drukkerij in Casablanca: twee persen, een zetkast, en een achterkamer waar niemand kwam. Ze drukten menukaarten, briefpapier, rouwkaarten en aankondigingen van bruiloften.',
    'Nadia zette letters vanaf haar tiende. Achterstevoren, want een zetkast werkt in spiegelbeeld, en na een jaar kon ze spiegelschrift sneller lezen dan gewoon schrift.',
    'In augustus 1953 veranderde alles op één dag.',
    'De Fransen zetten de sultan af.',
    'Mohammed V, die al twintig jaar op de troon zat en die steeds duidelijker had gezegd dat Marokko van de Marokkanen was, werd op een vliegtuig gezet. Eerst naar Corsica. Daarna naar Madagaskar, zo ver weg dat het bijna een grap was.',
    'Ze zetten er een oude neef voor in de plaats.',
    'Nadia hoorde het op straat, en ze zag dat de straat er anders bij lag dan ze ooit had gezien.',
  ] },
  { nummer: 2, titel: 'Achterstevoren', tekst: [
    'Een zetkast is een houten lade met honderdzeventien vakjes en in elk vakje ligt een letter van lood.',
    'Je pakt ze één voor één en je zet ze in een haakje dat je in je linkerhand houdt. Van links naar rechts, en elke letter staat op zijn kop en in spiegelbeeld, want als je straks inkt op het lood doet en er papier tegenaan drukt, draait alles om.',
    'Nadia heeft dat geleerd toen ze tien was en ze kon het op haar twaalfde blind.',
    'De vakjes liggen niet op alfabet. Ze liggen op hoe vaak je een letter nodig hebt: de a en de e vlak voor je, de q en de w in de verste hoek.',
    'Wie het kan, kijkt niet meer. Je hand weet waar de letter ligt zoals je vingers weten waar de toetsen van een piano liggen.',
    'Twee dingen daaruit hebben haar later geholpen op een manier die niemand had bedacht.',
    'Het eerste: ze kon spiegelschrift lezen. Sneller dan gewoon schrift, zei ze zelf, en dat is geen opschepperij maar een beroepsafwijking.',
    'Dat betekent dat ze op een zetsel kon zien wat erop stond zonder het te drukken. Van een afstand, ondersteboven, in een halve seconde.',
    'Toen er in de jaren daarna mannen in de drukkerij kwamen kijken wat er op de pers lag, stond zij ernaast en wist zij als enige in de kamer binnen één blik of er iets fout stond.',
    'Het tweede was het loodstof.',
    'Wie met lood werkt, heeft zwarte randen onder zijn nagels die er niet uit gaan. Iedereen in het vak heeft ze.',
    'Nadia heeft er in die jaren twee keer haar handen mee gered. Een man die vroeg wat ze deed, kreeg haar handen te zien.',
    '“Ik zet letters,” zei ze dan.',
    'En dat klopte.',
  ] },
  { nummer: 3, titel: 'De maan', tekst: [
    'Wat er toen gebeurde, is het soort ding dat je in een geschiedenisboek leest en waarvan je denkt: dat verzinnen ze.',
    'Mensen begonnen de koning in de maan te zien.',
    'Het begon ergens, niemand weet waar, en binnen weken keek het halve land op de zevenentwintigste van de maand omhoog en zei dat het gezicht van Mohammed V in de volle maan stond.',
    'De Fransen wisten niet wat ze ermee aan moesten. Je kunt een krant verbieden. Je kunt de maan niet verbieden.',
    'Nadia heeft het zelf ook gezien, zegt ze. Of ze heeft zichzelf laten zien dat ze het zag; op haar oude dag zei ze dat ze het verschil niet meer wist.',
    'In de drukkerij veranderde er iets in diezelfde weken.',
    'Haar vader begon ’s avonds door te werken.',
  ] },
  { nummer: 4, titel: 'De stem uit Caïro', tekst: [
    'In het tweede jaar kwam er een radio in de achterkamer, en dat was gevaarlijker dan de pers.',
    'Niet het apparaat. Wat eruit kwam.',
    'Uit Caïro zond een station uit dat De Stem van de Arabieren heette, en dat was in die jaren in het hele Midden-Oosten en Noord-Afrika te horen als het weer meezat.',
    'Ze praatten daar over Marokko. Over de verbannen koning. Over de Fransen.',
    'Dat was het bijzondere: ergens op tweeduizend kilometer afstand zei een stem hardop wat je hier niet mocht zeggen, en je kon hem horen in je eigen achterkamer.',
    'Ze luisterden met zijn drieën, met het volume zo laag dat je je hoofd ernaartoe moest buigen.',
    'Nadia heeft daar twee dingen geleerd.',
    'Het eerste was hoop, en die was echt en die hadden ze nodig.',
    'Het tweede duurde jaren voordat ze het hardop durfde te zeggen.',
    'De stem uit Caïro had het vaak over dingen die ze zelf kon controleren, omdat ze erbij was geweest. Een staking in Casablanca. Een demonstratie in haar eigen wijk.',
    'En soms klopte het niet.',
    'Dan werden er tienduizend mensen genoemd waar er drieduizend waren geweest. Dan werd er iets fel gemaakt wat ze zelf hadden zien gebeuren en wat anders was gegaan.',
    'Ze heeft dat aan haar vader gezegd, één keer, en hij heeft er lang over nagedacht.',
    '“Ze staan aan onze kant,” zei hij toen.',
    '“Dat vroeg ik niet.”',
    'Hij knikte.',
    '“Nee,” zei hij. “Dat vroeg je niet.”',
    'Meer is er niet over gezegd. De radio bleef aan, elke avond, zachter dan een fluistering. Maar Nadia luisterde er vanaf die avond anders naar.',
  ] },
  { nummer: 5, titel: 'De achterkamer', tekst: [
    'Ze wist het al voordat hij het haar vertelde. Je weet zoiets.',
    'Op een avond in november riep hij haar in de achterkamer, deed de deur dicht en liet haar een vel zien dat van de kleine pers kwam.',
    'Geen menukaart.',
    '“Als ze het vinden,” zei hij, “dan zeg jij dat je niets weet.”',
    '“Dat geloven ze niet.”',
    '“Nee,” zei hij. “Maar dan zeg je het toch.”',
    'Vanaf dat moment hielp ze mee.',
    'Dat ging zo: overdag briefpapier, ’s avonds het andere. De pamfletten gingen in stapels papier die naar klanten werden gebracht, tussen de menukaarten van een restaurant.',
    'Nadia bracht ze weg met een tas over haar schouder, veertien jaar oud, en ze heeft in die jaren geleerd hoe je loopt als je niets te verbergen hebt.',
    'Niet te snel. Niet te langzaam. Kijk mensen aan.',
  ] },
  { nummer: 6, titel: 'Niet kopen', tekst: [
    'Het slimste wapen van die jaren was niet drukken en niet schieten. Het was niet kopen.',
    'Op een gegeven moment — Nadia wist niet meer precies wanneer, het ging van mond tot mond — hield iedereen op met het kopen van Franse sigaretten.',
    'Dat klinkt klein. Het was het niet.',
    'De tabak was een staatsmonopolie. Elk pakje dat je kocht was geld voor het bestuur dat je weg wilde hebben.',
    'En rokers zijn rokers. Er waren mannen in haar straat die dertig jaar hetzelfde merk hadden gerookt.',
    'Ze stopten.',
    'Sommigen begonnen zelf te draaien met tabak die uit de bergen kwam. Sommigen stopten helemaal en waren maandenlang onuitstaanbaar.',
    'Er kwam meer bij. Franse winkels waar niemand meer kwam. Trams waar mensen naast liepen in plaats van in te stappen.',
    'Nadia heeft dat het indrukwekkendste van alles gevonden, en ze heeft het later aan haar kleinkinderen uitgelegd toen die vroegen wat je kunt doen als je niks bent.',
    'Dit.',
    'Eén persoon die geen sigaretten koopt, is een man die geen sigaretten koopt.',
    'Driehonderdduizend mensen die geen sigaretten kopen, is een probleem waar in Parijs vergaderingen over worden gehouden.',
    'En er is niemand die je ervoor kan oppakken, want je hebt niets gedaan.',
  ] },
  { nummer: 7, titel: 'De enige vrouw op de lijst', tekst: [
    'Er is een naam die Nadia’s vader in de drukkerij heeft laten zetten en die zij zich herinnerde omdat ze ernaar vroeg.',
    'Malika El Fassi.',
    'In januari 1944 was er een document opgesteld waarin voor het eerst met zoveel woorden om onafhankelijkheid werd gevraagd. Zesenzestig mensen hebben het ondertekend.',
    'Vijfenzestig mannen en zij.',
    'Ze was toen zesentwintig. Ze schreef in tijdschriften onder een schuilnaam omdat een vrouw die onder haar eigen naam schreef problemen kreeg — niet van de Fransen, maar van haar eigen omgeving.',
    'Waar ze haar hele leven voor heeft gevochten, was onderwijs voor meisjes.',
    'Nadia vroeg aan haar vader waarom er maar één vrouw op die lijst stond.',
    'Hij zei: “Omdat er maar één gevraagd is.”',
    'Dat antwoord is haar bijgebleven omdat het geen excuus was.',
    'In de jaren daarna heeft ze gezien wie het werk deed in haar eigen wijk.',
    'Vrouwen brachten boodschappen, want vrouwen werden minder vaak aangehouden. Vrouwen verstopten mensen in hun huis, want daar werd minder vaak gezocht. Vrouwen hielden huishoudens draaiende waarvan de man vastzat.',
    'Op de foto’s van november 1955 staan mannen op de daken.',
    'Op de straat eronder, waar geen foto van is, stonden vrouwen.',
    'Nadia heeft daar haar hele leven les over gegeven op de manier waarop zij lesgaf: door het te noemen, elke keer, zonder er een punt van te maken.',
  ] },
  { nummer: 8, titel: 'Wat het kostte', tekst: [
    'Het waren geen mooie jaren en dit is geen mooi hoofdstuk.',
    'Er werd gestaakt en er werd gevochten. Er vielen doden, in Casablanca en in Oued Zem en op plekken waarvan de namen nu op scholen worden geleerd.',
    'De vader van haar vriendin werd opgepakt en kwam na acht maanden terug en was een andere man.',
    'Haar eigen vader is twee keer opgehaald en twee keer teruggekomen. De tweede keer duurde het elf dagen, en hij heeft er nooit over verteld, en hij drukte daarna weer.',
    'Nadia was zestien toen ze voor het eerst dacht: misschien wint dit niet.',
    'Ze heeft dat aan niemand gezegd.',
  ] },
  { nummer: 9, titel: 'Elf dagen', tekst: [
    'Over de elf dagen dat haar vader weg was, staat in dit boek weinig, en dat is met opzet.',
    'Hij heeft er nooit over verteld. Niet aan zijn vrouw, niet aan Nadia, niet aan zijn kleinkinderen die ernaar vroegen toen ze oud genoeg waren om te weten dat ze het niet moesten vragen.',
    'Wat er wel over te zeggen valt, is hoe het in huis was.',
    'Ze wisten niet waar hij was. Dat is het eerste.',
    'Er was geen bericht, geen papier, geen adres waar je je kon melden. Je ging naar het bureau en dan zei iemand dat hij er niet was, en dat was alles.',
    'Nadia was zestien en ze heeft die elf dagen de drukkerij opengehouden.',
    'Ze heeft menukaarten gedrukt en rouwkaarten en een aankondiging van een bruiloft, en ze heeft de achterkamer niet aangeraakt.',
    'Op de negende dag kwam er een klant die zijn bestelling kwam halen en die zei: “Ik hoorde het van je vader.”',
    'Verder niets. Hij betaalde, hij nam zijn dozen mee, en toen hij weg was lag er onder het geld een tweede biljet dat er niet hoorde.',
    'Nadia heeft nooit geweten wie die man was.',
    'Op de elfde dag kwam haar vader terug. Hij is meteen gaan slapen en heeft de volgende ochtend om zeven uur de persen aangezet.',
    'Wat Nadia hierover heeft gezegd, veel later, is dit:',
    '“Ik heb in die dagen geleerd dat een stad uit meer mensen bestaat dan je denkt. Er waren er honderd die niets zeiden en die wisten wie wij waren en die niets hebben gedaan.”',
    '“Dat klinkt niet als veel.”',
    '“Niets doen,” zei ze, “is in zulke jaren een keuze die honderd mensen elke dag maken.”',
  ] },
  { nummer: 10, titel: 'November', tekst: [
    'Op 16 november 1955 kwam hij terug.',
    'Nadia was zeventien. Ze stond langs de weg in Rabat, waar ze met haar neef naartoe was gereisd omdat ze het wilde zien, tussen honderdduizenden mensen die allemaal hetzelfde wilden zien.',
    'Wat ze zich herinnert is niet het gezicht van de koning. Dat was ver weg en het ging snel.',
    'Wat ze zich herinnert is het geluid.',
    'Ze heeft later gezegd dat ze nooit meer in haar leven zoveel mensen tegelijk heeft horen huilen en juichen op hetzelfde moment.',
    'Op 2 maart 1956 werd Marokko onafhankelijk van Frankrijk. In april volgde het Spaanse deel.',
    'Haar vader heeft die dag de persen laten stilstaan, wat hij nooit deed.',
    'Hij zette twee stoelen op de stoep en ze hebben daar de hele middag gezeten.',
  ] },
  { nummer: 11, titel: 'En toen', tekst: [
    'Op 2 maart 1956 was het land onafhankelijk, en dit hoofdstuk gaat over de dag daarna.',
    'Want dat is de vraag die niemand stelt in een boek dat eindigt bij het feest.',
    'Wat Nadia zich van 1956 herinnert, behalve de stoelen op de stoep, is dat er ontzettend veel geregeld moest worden.',
    'Er was een land en er was bijna geen bestuur dat van hen was. De Fransen die het hadden gedaan, gingen weg. Postkantoren, scholen, belastingen, ziekenhuizen, de haven, de spoorwegen — alles had mensen nodig.',
    'Er waren niet genoeg mensen.',
    'Dat is wat honderdvijftig jaar van een land maken waarin de meeste kinderen niet naar school gaan: als je het terugkrijgt, kun je het niet meteen bemannen.',
    'De scholen zijn in tien jaar verdrievoudigd. Er zijn onderwijzers opgeleid in cursussen van een half jaar die eigenlijk drie jaar hadden moeten duren, en die hebben lesgegeven aan kinderen van wie de ouders niet konden lezen.',
    'Nadia’s vader heeft in die jaren schoolboeken gedrukt.',
    'Dat vond hij het beste werk van zijn leven en hij heeft het gezegd ook.',
    'Er ging ook van alles mis, en daar is dit boek niet de plek voor, behalve deze zin: een land dat vrij wordt, wordt niet meteen ook rechtvaardig, en de mensen die daarover in de jaren daarna hun mond opendeden hebben het zwaar gehad.',
    'Nadia is onderwijzeres geworden. Ze heeft achtendertig jaar voor de klas gestaan in Casablanca.',
    'Haar dochter is in 1979 naar Nederland vertrokken, met een koffer en een adres van een neef in Utrecht. Daar begint het laatste deel van dit boek.',
  ] },
  { nummer: 12, titel: 'Het valse boek', tekst: [
    'In de achterkamer stond een boek dat geen boek was.',
    'Haar vader had het gemaakt in het eerste jaar: een band van een oud wetboek, uitgehold, waar precies twintig gevouwen pamfletten in pasten. Als er iemand kwam die niet vertrouwd was, ging alles daarin en het boek in de kast bij de andere.',
    'Er lag nog iets in.',
    'Een sleutel van brons met acht punten aan de kop, die haar vader in 1948 had gekocht op de vlooienmarkt omdat hij mooi was, en die hij in het boek had gelegd omdat hij er niets anders mee kon.',
    'Na de onafhankelijkheid is het boek nooit meer gebruikt.',
    'Het heeft in de kast gestaan tot de drukkerij in 1971 werd verkocht, en toen heeft Nadia het meegenomen naar haar eigen huis, en later naar het huis van haar dochter.',
    'Haar dochter is in 1979 naar Nederland gegaan.',
    'Het boek ging mee.',
  ] },
]
