import type { SleutelVertaling } from './sleutels-talen'

/**
 * De sleutels van Marokko in het Spaans.
 *
 * Wordt deel voor deel vertaald. Wat hier staat is af; de rest valt terug op
 * het Nederlands tot het zover is.
 *
 * De dialoog staat tussen Spaanse aanhalingstekens («…»). Dat is een keuze:
 * het Nederlands zet de dialoog midden in de alinea, en met gedachtestreepjes
 * — de gewoonte in een Spaanse roman — zou elke zin een eigen regel vragen en
 * viel het tempo van het origineel weg.
 */
export const ES_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'El incendio de las aceitunas',
    jaar: '± 200',
    waar: 'Walili (Volubilis), al pie del Zerhoun',
    verteller: 'Tala, once años, hija de un maestro de almazara que ha caído enfermo',
    flap: 'Tala tiene la llave del almacén y el capataz la quiere. Cuando el aceite de toda la ciudad corre peligro, ha de elegir entre obedecer y tener razón.',
    sleutel: 'La llave la forja en Walili el abuelo de Tala y al final se va con una caravana amazigh hacia las colinas.',
    echt: [
      'Volubilis — en árabe Walili — fue una ciudad romana de verdad, cerca de Mequinez, con miles de habitantes, termas y calles de piedra.',
      'La ciudad vivía del aceite de oliva. Se han excavado decenas de prensas, y funcionaban según la misma idea que las prensas que todavía hoy se usan en Marruecos.',
      'Los suelos estaban llenos de mosaicos. Una parte sigue allí, al aire libre.',
      'La población era en su mayoría amazigh; la vida romana y la amazigh se entrelazaban aquí.',
    ],
    verzonnen: [
      'Tala, su familia y el capataz Marco no existieron.',
      'El incendio de la historia es inventado. No hay pruebas de un gran incendio en Walili en esta época.',
      'La llave de la estrella de ocho puntas es inventada. El khatam de ocho puntas sí es un motivo marroquí real y antiquísimo.',
    ],
    hoofdstukken: [
      { titel: 'La llave', tekst: [
        'A Tala la despertó el olor.',
        'Aceitunas. Aceitunas prensadas, calientes y amargas. En estas semanas la ciudad entera olía así. Se quedó quieta un momento y escuchó. Fuera ya crujía la prensa grande. Eso quería decir que llegaba tarde.',
        'Saltó de la cama y se pasó el vestido por la cabeza.',
        '«¡Tala!», gritó su madre desde abajo. «¡La puerta!»',
        'La puerta. Cómo no, la puerta.',
        'Desde que su padre había caído enfermo, Tala hacía su trabajo. Cada mañana iba al almacén detrás de la casa y abría la puerta. Allí estaban las tinajas. Cien tinajas, llenas hasta el borde de aceite, listas para ir al puerto.',
        'La llave colgaba de un cordón a su cuello. Era de bronce y larga como su mano. Su abuelo la había forjado mucho antes de que ella existiera. En la cabeza tenía ocho puntas, como una estrella.',
        '«No la pierdas», le había dicho su padre. Lo había dicho bajito, porque más alto ya no podía. «Esa puerta no se abre con ninguna otra cosa.»',
        'Tala bajó corriendo la escalera, pasó la cocina, cruzó el patio. Todavía era temprano. El sol acababa de asomar por encima de las colinas y las piedras estaban frías bajo sus pies.',
        'Junto al almacén había un hombre.',
        'Se paró en seco.',
        'Era grande y llevaba el manto rojo del capataz. Marco. Todo el mundo en Walili conocía a Marco, y a nadie le caía bien.',
        '«Llegas tarde», dijo él.',
        '«Llego a tiempo», dijo Tala.',
        'Sabía que no debería haber dicho eso. Lo dijo igual.',
        'Marco la miró. Después alargó la mano.',
        '«Dame esa llave. Una niña no tiene por qué guardar cien tinajas.»',
        'Tala dio un paso atrás.',
        'En su cabeza oía a su padre. *Esa puerta no se abre con ninguna otra cosa.* Y pensó en otra cosa, algo que había visto ayer y que había creído que no era nada.',
        'Dos tinajas que no estaban en su sitio.',
        '«¿Y bien?», dijo Marco.',
        'Tala cerró la mano alrededor del bronce. Se había entibiado con su piel.',
        '«No», dijo.',
      ] },
      { titel: 'Dos tinajas', tekst: [
        'Marco no se rió. Tampoco se enfadó. Eso fue lo peor.',
        'Bajó la mano, se estiró el manto y dijo: «Como quieras.» Después se fue, callejón abajo, sin volver la vista.',
        'Tala se quedó de pie hasta que dejó de oír sus pasos. Solo entonces notó que le temblaban las manos.',
        'Abrió la puerta.',
        'Dentro estaba oscuro y fresco. Las tinajas estaban en filas de diez, con paja entre ellas para que no chocaran. Diez filas de diez. Cada mañana las contaba. Se lo había enseñado su padre cuando ella tenía seis años, y entonces todavía era un juego.',
        'Empezó por la izquierda y contó en voz alta, como siempre.',
        'En la última fila se detuvo.',
        'Había nueve.',
        'Tala contó otra vez. Nueve. Rodeó la fila, se agachó, miró detrás de la paja. Nueve.',
        'Ayer también había visto algo raro. Dos tinajas mal puestas, con las asas hacia la pared en vez de hacia el pasillo. Había pensado: alguien lo ha hecho con prisa. Las había enderezado y no había vuelto a pensar en ello.',
        'Ahora había una menos.',
        'Se sentó en el umbral con la espalda contra la jamba y las rodillas recogidas, y trató de pensar qué hacer.',
        'Podía contárselo a su madre. Pero su madre ya tenía bastante este mes: un marido enfermo arriba, una casa llena de gente a la que había que pagar, y una cosecha que dentro de tres semanas tenía que ir al puerto.',
        'Podía contárselo a Marco. Marco era el capataz. Ese era su trabajo.',
        'Tala miró hacia el callejón por donde él había desaparecido.',
        'No.',
        '«Estás estorbando», dijo una voz.',
        'Se sobresaltó. Delante de ella había un chico más o menos de su edad, con un delantal de cuero y los brazos llenos de haces de leña. Tenía las manos negras.',
        '«No estoy estorbando», dijo Tala. «Esta es mi puerta.»',
        '«Entonces estorbas tu propia puerta.»',
        'Se llamaba Yidir y trabajaba en la herrería del final de la calle. Tala lo conocía de vista como se conoce de vista a todo el mundo en Walili, y nada más.',
        'Se levantó para dejarlo pasar. Él no pasó.',
        '«Cuentas todas las mañanas», dijo.',
        '«¿Y tú cómo lo sabes?»',
        '«Paso por aquí todas las mañanas.»',
        'Tala dudó. Después lo dijo igualmente, porque tenía que salir y porque él estaba allí.',
        '«Falta una.»',
        'Yidir dejó los haces en el suelo.',
        '«¿Una?», dijo. «Pues has tenido suerte. A nosotros nos faltan seis barras de hierro.»',
      ] },
      { titel: 'Cómo se hace el aceite', tekst: [
        'Aquella tarde Tala estaba junto a la prensa, como cada día de la cosecha.',
        'La prensa era una piedra ahuecada del tamaño de un carro, con otra piedra redonda dentro que un burro hacía girar. Las aceitunas entraban, se machacaban, y lo que salía era una masa espesa y parda que no se parecía a nada.',
        'Esa era la parte que siempre decepcionaba a los forasteros. «¿Eso es aceite?», preguntaban. No. Eso era el principio.',
        'La masa iba a esteras redondas de junco trenzado. Esas esteras se apilaban bajo la prensa de viga, y entonces dos hombres daban vueltas al husillo, despacio, como si tuvieran todo el tiempo del mundo. Bajo la pila corría un canalillo.',
        'De ahí salía.',
        'Primero agua, turbia y sucia. Después, al cabo de un rato, otra cosa. Algo que se quedaba flotando sobre el agua y era más verde que nada que Tala conociera.',
        'La primera vez su padre la había cogido por el cuello y le había puesto la cabeza encima. «Huele», había dicho. «Eso es. Si huele así, está bien. Si no huele a nada, has esperado demasiado.»',
        'Ella había mentido entonces diciendo que lo olía. Ahora lo olía de verdad.',
        'Walili vivía de esto. No de los suelos de mosaico por los que caminaban los visitantes, ni de las columnas de la plaza, ni de las calles de piedra. De esto. De aceitunas prensadas que iban a tinajas, en carros hacia la costa, y en barcos hacia lugares de los que Tala solo conocía el nombre.',
        'Vigilaba el canalillo y las esteras y el burro, y mientras tanto pensaba en noventa y nueve tinajas.',
        'Seis barras de hierro, había dicho Yidir. De la herrería.',
        'El hierro era caro. El aceite era caro. Y los dos salían de la ciudad en la misma dirección: por el camino del puerto.',
        '«Tala.» Uno de los hombres señaló el canalillo. «Se desborda.»',
        'Se lanzó hacia delante y metió el cuenco debajo, tarde. Un chorro de aceite corrió por la piedra y desapareció entre las juntas.',
        'Un dedo de grueso, puede que dos. Suficiente para una familia durante una semana.',
        'El hombre no dijo nada. Eso lo hizo peor.',
      ] },
      { titel: 'Lo que puede un capataz', tekst: [
        'Marco volvió al tercer día, y no vino solo.',
        'Tala lo vio entrar en el patio con dos hombres detrás. Su madre salió, se secó las manos en el vestido y se plantó justo entre él y la puerta.',
        '«Paz», dijo Marco.',
        '«Paz», dijo su madre, en el tono en que se dice eso cuando no se dice en serio.',
        '«Tu marido está enfermo.»',
        '«Mi marido descansa.»',
        '«Tres semanas», dijo Marco. «Dentro de tres semanas la cosecha va al puerto, y la ciudad cuenta con lo que hay en esta casa. Tengo que saber que está.»',
        '«Está.»',
        '«Quiero verlo.»',
        'Se hizo un silencio. Tala estaba en la puerta de la cocina y no se atrevía a moverse.',
        'Su madre dijo: «Puedes mirar. Abre mi hija.»',
        'Tala cruzó el patio bajo la mirada de cinco personas. Se pasó el cordón por encima de la cabeza, metió la llave en la cerradura y empujó la puerta.',
        'Marco entró. Recorrió las filas, despacio, con las manos a la espalda. En la última fila se detuvo.',
        'Tala contuvo la respiración.',
        '«Noventa y nueve», dijo Marco.',
        'Se dio la vuelta y miró a su madre.',
        '«Deberían ser cien.»',
        'Su madre se puso rígida. Tala lo vio en sus hombros.',
        '«Entonces se ha roto una», dijo ella.',
        '«Entonces habría cascos.» Marco abrió las manos. «No veo cascos. Veo paja que alguien ha vuelto a estirar.»',
        'Esperó un momento, exactamente lo justo.',
        '«No digo que robéis», dijo entonces. «Digo que una niña de once años tiene la llave de cien tinajas, y que hoy hay noventa y nueve. Eso digo. Y eso diré también en la plaza.»',
        'Salió por la puerta y pasó junto a Tala como si ella fuera un poste.',
        'Cuando se hubo ido, su madre se sentó en el brocal del pozo. Estuvo muchísimo rato sin decir nada.',
        '«Mamá», dijo Tala. «Yo no la he…»',
        '«Lo sé.»',
        '«Las conté el lunes y entonces todavía eran…»',
        '«Tala.» Su madre levantó la vista. Tenía los ojos rojos. «Lo sé. Y eso no nos sirve de nada.»',
      ] },
      { titel: 'La herrería', tekst: [
        'Yidir estaba sentado en un cubo del revés delante de la herrería, lijando un gozne.',
        '«Tenías razón», dijo Tala.',
        '«Eso me lo dice poca gente», dijo Yidir sin levantar la vista. «¿En qué?»',
        '«En que no era una sola tinaja.»',
        'Ahora sí levantó la vista.',
        'Tala se sentó a su lado en el umbral y se lo contó. Lo de Marco, lo de noventa y nueve, lo que él iba a decir en la plaza. Yidir escuchó como hacía todo: como si mientras tanto estuviera pensando en otra cosa, pero no se le escapaba nada.',
        '«¿Y vuestro hierro?», preguntó ella.',
        '«Seis barras. Mi maestro cree que se ha equivocado al contar.» Yidir se encogió de hombros. «Mi maestro no se equivoca nunca al contar.»',
        '«¿Cuándo?»',
        '«La semana pasada. Y la anterior tres.»',
        'Tala recogió las rodillas.',
        '«¿Qué sale de la ciudad?», preguntó. «Cada día, quiero decir.»',
        'Yidir se lo pensó.',
        '«Carros», dijo. «Aceite, grano, pieles, hierro. Todo va por el camino del norte. Hay un puesto de guardia en la puerta. Allí se anota todo.»',
        '«¿Quién lo anota?»',
        'Yidir la miró.',
        '«El capataz», dijo.',
        'Los dos se quedaron callados un rato.',
        '«Eso no demuestra nada», dijo Tala al final.',
        '«No.»',
        '«Si lo digo, dirán que una niña de once años acusa a un hombre porque no le cae bien.»',
        '«Sí», dijo Yidir. «Eso dirán.»',
        'Dejó el gozne a un lado.',
        '«Así que necesitas algo que no puedan quitarte con palabras.»',
        '«¿Como qué?»',
        '«Como ver qué sale de noche por esa puerta.»',
        'Tala lo miró. Él le devolvió la mirada, y por primera vez desde que lo conocía, se rió.',
      ] },
      { titel: 'Lo que pasa de noche por la puerta', tekst: [
        'Estaban tumbados en el tejado de las termas, boca abajo, con la barbilla sobre los brazos.',
        'El tejado estaba caliente del día. Debajo de ellos quedaba la calle que iba a la puerta del norte, lo bastante ancha para dos carros uno al lado del otro. Junto a la puerta ardía una lámpara.',
        '«¿Cuánto falta?», susurró Tala.',
        '«No lo sé.»',
        '«Dijiste que de noche pasan carros.»',
        '«Dije que *creía* que de noche pasan carros.»',
        'Tala suspiró y apoyó la cabeza en el brazo.',
        'Aquella noche las estrellas eran increíbles. En la ciudad se veían a medias, por la luz y el humo, pero aquí arriba había tantas que daba inquietud.',
        '«Mi abuela dice que son un mapa», dijo Yidir.',
        '«¿Las estrellas?»',
        '«Sí. Si sabes leerlas, puedes llegar a cualquier parte. Dice que su familia llegó así desde el desierto hasta aquí.»',
        '«¿Tú sabes leerlas?»',
        '«No», dijo Yidir. «Nadie me lo ha enseñado.»',
        'Entonces lo oyeron.',
        'Un carro. No dos burros, no caballos — un burro, despacio, y el ruido de la madera que cruje bajo un peso.',
        'Tala se arrastró hasta el borde.',
        'El carro venía de una bocacalle. A su lado iban dos hombres, los dos con un paño en la cabeza. Sobre el carro había paja, y bajo la paja algo redondo.',
        'En la puerta el carro se detuvo.',
        'De la garita salió un hombre con una lámpara. No se acercó al carro. Se acercó a los hombres, habló brevemente con ellos y anotó algo en una tablilla.',
        'Después levantó la barrera.',
        'El carro se metió en la noche.',
        'Tala soltó el aire. No se había dado cuenta de que lo estaba aguantando.',
        '«No ha mirado», dijo. «No ha mirado debajo de la paja.»',
        '«No.»',
        '«Eso es…»',
        '«Eso sigue sin ser nada», dijo Yidir. «Eso es un hombre que no mira lo bastante bien. Por eso no cuelgan a nadie.»',
        'Tenía razón, y Tala también lo sabía.',
        'Pero cuando el carro tomó la curva, pasó algo. El burro se asustó de algo en la oscuridad, se echó a un lado, y el carro pasó con una rueda por encima del bordillo.',
        'Algo se cayó del carro.',
        'Rodó, se paró contra el muro y se quedó allí.',
        'Una tinaja.',
        'Uno de los hombres soltó un juramento, volvió sobre sus pasos, la recogió y la puso otra vez bajo la paja. El carro siguió.',
        'Pero Tala había visto lo que llevaba.',
        'En el hombro de cada tinaja de su casa su padre marcaba un signo en la arcilla antes de que se cociera. Ocho puntas. Una estrella.',
        'Agarró el brazo de Yidir tan fuerte que él siseó.',
        '«Esa es nuestra», dijo.',
      ] },
      { titel: 'Lo que dices y lo que oyen', tekst: [
        'A la mañana siguiente Tala fue a la plaza.',
        'Se lo había pensado toda la noche, o por lo menos la mitad; la otra mitad la había dormido sin querer. Sabía lo que iba a decir. Lo había ensayado tres veces contra la pared de su cuarto.',
        'En la plaza, bajo las columnas, el consejo celebraba sesión. Eso quería decir: cinco hombres en bancos de piedra, un escribano al lado, y alrededor todo el que tuviera una queja.',
        'Marco ya estaba allí.',
        'Tala esperó a que un hombre terminara de hablar sobre un muro y un vecino. Después dio un paso al frente.',
        '«Quiero decir algo», dijo.',
        'Cinco hombres levantaron la vista. Uno de ellos, el más viejo, con una cara como un higo seco, se inclinó hacia delante.',
        '«¿De quién eres tú?»',
        '«De Yuba, el de la almazara. De la calle de las Columnas.»',
        '«Ese está enfermo.»',
        '«Sí», dijo Tala. «Por eso estoy aquí.»',
        'Lo contó. La tinaja que faltaba, y al día siguiente otra. El carro en la noche y el hombre que levantó la barrera sin mirar bajo la paja. La tinaja que se cayó y el signo de las ocho puntas.',
        'Lo contó exactamente como lo había ensayado, y mientras lo hacía, también se oyó a sí misma.',
        'Oyó cómo sonaba.',
        'Una niña. Un tejado. La oscuridad. Un signo que nadie más había visto.',
        'Cuando terminó, hubo un silencio. Entonces Marco dijo, muy tranquilo: «¿Puedo?»',
        'El más viejo asintió.',
        '«La niña tiene razón en que faltan tinajas», dijo Marco. «Lo conté yo mismo, anteayer, en su propio almacén. Noventa y nueve de cien. Ya lo dije entonces.»',
        'Abrió las manos, como hacía él.',
        '«¿Quién tiene la llave de esa puerta?»',
        'Nadie dijo nada.',
        '«Ella», dijo Marco. «Una niña de once años. Y ahora que falta una, ha sido un carro en la noche. Un carro que solo ha visto ella.»',
        'El más viejo del consejo miró a Tala, y su mirada no era antipática. Eso era lo peor.',
        '«Niña», dijo. «Vete a casa. Cuida de tu padre.»',
        'Tala se quedó en la plaza con los brazos pegados al cuerpo y las orejas ardiendo, y a su alrededor todos volvieron a hablar de un muro y un vecino.',
      ] },
      { titel: 'El incendio', tekst: [
        'El incendio empezó cuatro días después, y no empezó en su casa.',
        'A Tala la despertó. No la luz ni los gritos — el sonido. Un rugido hondo y suave, como si muy cerca alguien estuviera soltando el aire durante muchísimo rato.',
        'Estaba en la ventana antes de estar despierta.',
        'Al otro lado de la calle, dos casas más allá, ardía el almacén de Quinto. Quinto también prensaba aceite. Sus tinajas estaban en un espacio bajo su casa, y de allí salía ahora fuego por la ventana, plano, y no hacia arriba como debe hacer el fuego.',
        'Eso es por el aceite, lo supo Tala más tarde. El aceite arde de otra manera.',
        'Ya había gritos. Ya había gente en la calle con cubos y mantas, y alguien golpeaba con un palo la plancha de bronce junto al pozo, y Tala bajó corriendo la escalera descalza.',
        'Su madre la agarró del brazo en la puerta.',
        '«Por ahí no.»',
        '«Pero…»',
        '«Tala.» Su madre la sujetó con las dos manos. «Nuestra puerta. Ya.»',
        'Y Tala lo entendió.',
        'Si se propaga, viene hacia ellos. Cien tinajas — noventa y nueve — de aceite, detrás de una puerta de madera, contra el mismo muro.',
        'Corrió al almacén, se pasó el cordón por encima de la cabeza y metió la llave en la cerradura. Tenía las manos tan mojadas que el bronce se le escurría. A la tercera lo consiguió.',
        'La puerta se abrió. El frescor le salió al encuentro, y el olor.',
        'Detrás de ella la calle entera empezó a cargar tinajas.',
        'Las llevaron al patio, al pozo, a la calle, a todas partes donde no hubiera un muro ardiendo. Los vecinos cargaron con ellos, gente a la que apenas conocía, gente con la que su padre nunca había hablado. Alguien trajo una escalera. Alguien echaba mantas al agua del pozo y las iba pasando.',
        'Tala cargó hasta que los brazos ya no quisieron y entonces cargó más.',
        'En la tinaja número setenta vio a Yidir. Vino con otros cuatro de la herrería y arrastraban algo que parecía un gancho largo.',
        'En la ochenta y cinco se hundió el tejado del almacén de Quinto.',
        'Con la última ya estaba saliendo el sol.',
        'Para entonces ya no había fuego. Solo había humo que colgaba bajo sobre la calle, y doscientas personas que miraban sin decir nada, y manos negras, y en alguna parte un niño que lloraba.',
        'Tala estaba sentada en el escalón, apoyada en su madre.',
        'Y por eso fue la única que vio al hombre que salía del callejón junto a la casa de Quinto, a contracorriente, con el manto sobre el brazo en vez de sobre los hombros.',
        'El manto era rojo.',
      ] },
      { titel: 'El manto rojo', tekst: [
        'Se lo contó a Yidir antes que a nadie.',
        'Él la escuchó sin interrumpirla, y cuando terminó dijo: «Eso sigue sin ser nada.»',
        '«Lo he visto.»',
        '«Has visto a un hombre con un manto rojo en una calle llena de gente con hollín en la cara.» Yidir dio una patada a una piedra. «Yo te creo. El consejo no.»',
        'Tala sabía que tenía razón y estaba harta de que siempre la tuviera.',
        '«¿Entonces qué?», dijo. «No puedo no hacer nada.»',
        '«No», dijo Yidir. «Pero necesitas algo que no venga de ti.»',
        'Se sentó en el brocal del pozo, con los talones contra la piedra.',
        '«En la puerta lo anotan todo», dijo. «En cera. Lo que sale, cuánto, y de quién. Esas tablillas van cada mes a la casa de la ciudad.»',
        '«¿Y si no hay nada raro?»',
        '«Entonces no hay nada raro», dijo Yidir. «Y entonces sabes que no está en los libros, sino en la oscuridad. Eso también es algo.»',
        'La miró.',
        '«Pero si sí hay algo — si allí pone doce tinajas y por la puerta salieron trece — entonces no es una niña que ha visto algo. Entonces es un número al lado de otro número, y a los números nadie se los quita con palabras.»',
        'Tala pensó en la noche en el tejado. En el hombre que no había mirado bajo la paja.',
        '«¿Quién puede ver esas tablillas?»',
        '«Nosotros no.»',
        '«¿Quién entonces?»',
        'Yidir calló un momento.',
        '«Mi maestro», dijo. «Él entrega el hierro para las cerraduras de la casa de la ciudad. Entra allí sin que nadie pregunte por qué.»',
        '«Pues pídeselo.»',
        '«No es hombre de meterse con el capataz.»',
        '«Pídeselo», dijo Tala otra vez.',
        'Yidir se miró las manos negras.',
        '«Está bien», dijo. «Pero esta noche no. Esta noche es el viernes del mercado y está de mal humor.»',
        'A pesar de todo, Tala tuvo que reírse.',
        'Era la primera vez en días.',
      ] },
      { titel: 'Lo que ponía en la cera', tekst: [
        'El herrero se llamaba Amanar y era el hombre más grande que Tala había visto nunca de cerca.',
        'Durante dos días no dijo nada. Entonces, la tercera mañana, apareció por la calle de las Columnas con un paquete bajo el brazo, y se sentó en el escalón del almacén como si le correspondiera.',
        '«Tú eres la hija de Yuba», dijo.',
        '«Sí.»',
        '«Tu padre le dio a mi madre aceite durante todo un invierno sin cobrarle nada.» Amanar miró calle abajo. «Fue hace dieciséis años. Yo no lo he olvidado y él ya no se acuerda de haberlo hecho.»',
        'Dejó el paquete en el escalón.',
        'Eran dos tablillas de cera, en un marquito de madera, con raya sobre raya sobre raya.',
        '«Mirar, sí», dijo Amanar. «Llevárselas, no. Dentro de una hora están otra vez donde deben estar.»',
        'Tala se sentó y leyó.',
        'Sabía leer. No con soltura, pero lo suficiente. Su padre se había empeñado: «Quien no sabe leer, se cree lo que otro dice que pone.»',
        'En la cera había filas. Fecha, puerta, qué, cuánto, de quién.',
        'Buscó su propio apellido. Lo encontró once veces.',
        '*Yuba, almazara, calle de las Columnas. Ocho tinajas.*',
        '*Yuba, almazara. Doce tinajas.*',
        '*Yuba, almazara. Nueve tinajas.*',
        'Tala las sumó. Sumó dos veces y la segunda vez lo escribió en la arena junto a sus pies.',
        'Ciento diecisiete tinajas. En cuatro semanas, fuera de la ciudad, a nombre de su padre.',
        'Levantó la vista.',
        '«Eso no cuadra», dijo.',
        '«¿No?», dijo Amanar.',
        '«Esta temporada hemos hecho ciento sesenta. Lo sé exactamente, las conté cuando se cocieron. Se han vendido sesenta en la ciudad. Había cien en el almacén.» Señaló la arena. «Ciento sesenta. No ciento setenta y siete.»',
        'Amanar no dijo nada.',
        '«Han salido diecisiete tinajas por la puerta que nosotros no hemos hecho nunca», dijo Tala. «A nuestro nombre.»',
        'Oyó ella misma lo que eso significaba, mientras lo decía.',
        'No eran solo sus tinajas lo que estaban robando.',
        'Era su nombre.',
        'Cuando dentro de poco se contara en la casa de la ciudad, y entrara menos de lo que había salido por la puerta, habría una sola casa donde acababa el rastro. Y esa casa era la suya.',
        '«Amanar», dijo, y la voz le salió rara. «Nos están preparando.»',
        'El herrero se levantó y se sacudió el polvo de las rodillas.',
        '«Sí», dijo. «Eso están haciendo.»',
        'Recogió las tablillas.',
        '«Ven mañana a la plaza con tu madre. Y trae esa arena, o mejor — cópialo en algo que no se vuele.»',
      ] },
      { titel: 'Dos números uno al lado del otro', tekst: [
        'El consejo celebraba sesión como siempre: cinco hombres, un escribano, y el murmullo de la gente que esperaba a que le tocara.',
        'Esta vez Tala no estaba sola.',
        'A su izquierda estaba su madre, con el vestido que solo se ponía cuando había algo muy malo o algo muy bueno. A su derecha estaba Amanar, y detrás de Amanar cuatro hombres de la herrería que no tenían nada que ver y aun así estaban allí.',
        'Más allá, apoyado en una columna, estaba Yidir.',
        'El más viejo del consejo — el de la cara como un higo seco — miró al grupo y levantó las cejas.',
        '«Otra vez tú», le dijo a Tala.',
        '«He contado», dijo Tala.',
        'Lo había escrito en un trozo de cuero, porque el cuero no se vuela. Lo leyó en voz alta. Lo que habían hecho. Lo que se había vendido en la ciudad. Lo que había en el almacén. Y después lo que, según las tablillas de la puerta, había salido de la ciudad a nombre de su padre.',
        'Dos números.',
        'Cuando terminó, hubo un silencio distinto del de la otra vez.',
        'Marco dio un paso al frente. Seguía tranquilo, pero ya no de la misma manera.',
        '«Una niña ha mirado en las tablillas de la ciudad», dijo. «Eso está prohibido.»',
        '«Las he traído yo», dijo Amanar.',
        'Se hizo aún más silencio.',
        'El más viejo del consejo se volvió hacia el escribano que tenía al lado.',
        '«Tráelas.»',
        'Tardó mucho. Nadie se fue. Alguien le dio un taburete a la madre de Tala y ella no se sentó.',
        'Cuando llegaron las tablillas, el escribano leyó en voz alta lo que ponía, y otro hombre fue sumando con piedras en un tablero, y toda la plaza lo oyó.',
        'Ciento diecisiete.',
        'El más viejo miró largo rato los números, y después a Marco, y después otra vez los números.',
        '«¿Quién escribe en la puerta del norte?», preguntó.',
        '«Eso va cambiando», dijo Marco.',
        '«¿Quién señala a quien escribe?»',
        'Marco no contestó.',
        'El más viejo suspiró, y fue el suspiro de un hombre que entiende algo que habría preferido no entender, y que sabe que ahora tiene que hacer algo con ello.',
        '«Siéntate», le dijo a Tala. «Tú no, Marco. Tú te quedas de pie.»',
      ] },
      { titel: 'Lo que queda', tekst: [
        'Tardaron todavía tres semanas en cambiar de verdad las cosas, y esa fue la lección más larga de aquel verano: que la verdad no funciona como en un cuento, donde la dices y todos asienten.',
        'Vino un hombre de la ciudad madre de Volubilis a revisar los libros. Se tomó declaración a varias personas. Dos veces no se dijo nada y una vez se dijo algo que nadie esperaba: el guardia de la puerta del norte, un chico de diecinueve años, se vino abajo a la tercera pregunta y lo contó todo.',
        'Marco desapareció antes de que se cerrara el asunto. Su casa estuvo un mes vacía y después se le dio a otro.',
        'El padre de Tala no se curó, no del todo. En otoño pudo volver a sentarse en el patio y oír crujir la prensa, y con eso parecía contento. Preguntaba por los números y ella se los decía. Le hizo contar tres veces lo que había pasado en la plaza, y la tercera vez lloró, y eso ella no se lo había visto hacer nunca.',
        'La cosecha fue al puerto. Cien tinajas. Cuadraba.',
        'La semana siguiente Yidir pasó por allí con su abuela.',
        'Su abuela era pequeña y vieja y tenía ojos de quien mira mucho más lejos de donde está. Dijo que se iba: de vuelta con su familia, a los pastos de las montañas, antes de que llegara el invierno. Lo dijo como si hablara de un paseo.',
        '«Yidir viene conmigo», dijo. «Una temporada.»',
        'Tala miró a Yidir. Yidir se miró las manos.',
        '«¿Cuánto es una temporada?», preguntó.',
        '«Eso solo se sabe después», dijo su abuela.',
        'Aquella tarde Tala se pasó el cordón por encima de la cabeza.',
        'La llave estaba tibia, como siempre. Ocho puntas en la cabeza, una estrella. Su abuelo la había forjado en una herrería que ya no existía.',
        'La tuvo en la mano y pensó en lo que había dicho su padre. *Esa puerta no se abre con ninguna otra cosa.*',
        'Se la dio a Yidir.',
        '«No puede ser», dijo él enseguida.',
        '«Tú me creíste cuando no me creía nadie.»',
        '«Eso no vale una llave.»',
        '«Es mi llave», dijo Tala. «Yo decido lo que vale.»',
        'Yidir la sostuvo como si quemara.',
        '«¿Y qué hago con ella?»',
        '«No lo sé», dijo Tala. «Regalarla, creo. A alguien a quien creas.»',
        'Se fueron a la mañana siguiente, con tres burros y un perro, hacia las colinas, y Tala se subió al tejado de las termas para mirarlos hasta que no se vieron.',
        'Entonces todavía no sabía que era bueno que la llave se fuera.',
        'Porque Walili no iba a estar siempre. El terremoto llegó mucho más tarde, y la ciudad se fue vaciando despacio — piedra a piedra, hasta que no quedó más que las columnas, las prensas de aceite y los suelos de mosaico que siguen allí hoy, al aire libre, cerca de Mequinez.',
        'Todo lo que había en las casas ha desaparecido.',
        'Solo la llave no.',
      ] },
    ],
  },
}
