import type { Hoofdstuk } from './sleutels'

/** Deel 5 — De wereld op één vel. Ceuta en Palermo, 1154. */
export const DEEL5_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Inkt', tekst: [
    'Sanaa was veertien en ze kon inkt maken die niet verbleekte, en dat was in haar familie het enige wat telde.',
    'Haar vader tekende kaarten. Niet de grote kaarten waar geleerden over praten — zeekaarten voor kapiteins, met kusten en diepten en de plekken waar je niet moest komen. Die verkocht hij in de haven van Ceuta voor geld waar ze net van konden leven.',
    'Sanaa maakte zijn inkt. Roet, gom, water, en iets wat haar grootmoeder eraan had toegevoegd en wat ze aan niemand vertelden.',
    'Ze tekende ook. Stiekem, op de achterkant van mislukte vellen.',
    'Op een middag in het voorjaar stond er een man in de werkplaats die daar niet hoorde.',
    'Hij was oud en hij was goed gekleed en hij pakte een van haar vaders kaarten op zonder te vragen.',
    '“Deze kust klopt niet,” zei hij.',
    'Haar vader kwam overeind. “Die kust vaar ik al twintig jaar.”',
    '“U vaart hem. U meet hem niet.” De man legde de kaart neer. “Er zit een bocht in die er niet is. Ik weet het, want ik ben er geweest en ik heb geteld hoeveel dagen.”',
    'Het bleef even stil, en Sanaa dacht dat haar vader hem eruit zou gooien.',
    'In plaats daarvan zei hij: “Laat zien.”',
  ] },
  { nummer: 2, titel: 'De man die overal was geweest', tekst: [
    'Hij heette Muhammad al-Idrisi en hij was in Ceuta geboren, en hij was sindsdien overal geweest waar je met een schip of een kameel kunt komen.',
    'Hij bleef drie dagen. Op de derde dag zat Sanaa op de grond bij de deur te luisteren terwijl hij aan haar vader uitlegde waar hij mee bezig was.',
    'Een kaart van de hele wereld.',
    'Niet een kust of een zee. Alles. Van de oceaan in het westen tot waar de zijde vandaan komt. Zeventig bladen, en een boek erbij waarin per streek stond wat er groeide, wie er woonde en hoe ver het was naar de volgende stad.',
    '“Voor wie?” vroeg haar vader.',
    '“Voor de koning van Sicilië.”',
    'Haar vader zei een tijdje niets.',
    '“Die is christen.”',
    '“Die is christen,” zei al-Idrisi. “En hij betaalt voor vijftien jaar werk, en hij laat mij kiezen wie eraan meewerkt, en aan zijn hof zitten mensen uit Alexandrië en uit Córdoba en uit Athene in dezelfde zaal.”',
    'Hij schonk zichzelf water in.',
    '“Ik heb mannen naar plekken gestuurd om ze na te meten. Niet om er iets te halen. Alleen om te kijken en terug te komen en te vertellen. Weet u hoeveel koningen daar geld aan uitgeven?”',
    'Hij hield een vinger omhoog.',
    '“Eén.”',
  ] },
  { nummer: 3, titel: 'Palermo', tekst: [
    'Ze gingen mee. Haar vader voor het werk, Sanaa omdat haar vader de inkt niet zonder haar kon maken en dat allebei wisten zonder het uit te spreken.',
    'Palermo rook naar citroen.',
    'Dat was het eerste wat ze schreef in het schrift dat ze bijhield: *het ruikt hier naar citroen en naar vis en er zijn hier drie soorten kerkklokken en de oproep tot gebed, allemaal op dezelfde ochtend.*',
    'Ze had niet geweten dat dat kon.',
    'In de werkkamers van het paleis werkten dertig mensen aan de kaart. Er werd Arabisch gesproken en Grieks en Latijn en iets wat het midden hield tussen alle drie. Er waren dagen dat er ruzie was over één kustlijn en dat er drie mannen stonden te schreeuwen in drie talen tegelijk.',
    'Sanaa maakte inkt. Kilo’s inkt.',
    'En op een avond, toen iedereen weg was, ging ze staan bij de grote tafel waar de bladen naast elkaar lagen.',
    'Ze zag voor het eerst de hele wereld.',
    'Het zuiden stond boven. Zo tekenden ze het toen. Afrika lag bovenaan het vel en Europa hing eronder, klein en rommelig, en helemaal onderaan lagen landen waar sneeuw viel.',
    'Ze zocht Ceuta.',
    'Het was een stip. Kleiner dan haar nagel.',
  ] },
  { nummer: 4, titel: 'Wat een kaart doet', tekst: [
    'Het jaar erna begreep ze waarom een kaart gevaarlijk is.',
    'Er kwamen mannen op bezoek die geen geleerden waren. Ze keken lang naar de bladen en ze stelden vragen die niets met kennis te maken hadden.',
    '“Hoeveel dagen van hier naar daar?”',
    '“Waar is de haven diep genoeg?”',
    '“Hoeveel mensen wonen daar?”',
    'Sanaa hoorde het aan terwijl ze inkt stond te roeren, en ’s avonds zei ze het tegen haar vader.',
    '“Ze willen weten waar ze kunnen landen.”',
    'Haar vader roerde door.',
    '“Ja.”',
    '“En dat maken wij voor ze.”',
    '“Ja.”',
    'Hij legde de stok neer.',
    '“Sanaa. Een kaart is een mes. Je kunt er brood mee snijden en je kunt er iemand mee doodsteken, en het mes weet het verschil niet.” Hij keek haar aan. “De man die het mes smeedt ook niet. Die maakt het zo goed als hij kan.”',
    '“Is dat genoeg?”',
    '“Nee,” zei haar vader. “Maar het is wat we hebben.”',
    'Ze heeft daar haar hele leven over nagedacht en ze is er nooit uitgekomen.',
  ] },
  { nummer: 5, titel: 'Het zilveren vel', tekst: [
    'In 1154 was het af.',
    'Er werd ook een versie in zilver gemaakt: de hele wereld gegraveerd in een schijf van bijna vierhonderd pond, die in de zaal van de koning lag.',
    'Sanaa mocht erbij zijn toen hij werd neergelegd. Ze stond achteraan tussen mensen die belangrijker waren dan zij, en ze keek naar een wereld van zilver waar zij inkt voor had gemaakt.',
    'Koning Roger II stierf datzelfde jaar.',
    'De zilveren kaart is later omgesmolten. Door wie en wanneer weet niemand precies; in de onrust na zijn dood is het paleis geplunderd en dat ding was zijn gewicht in geld waard.',
    'Wat bleef, waren de bladen van perkament en het boek.',
    'Dat boek is vierhonderd jaar lang in Europa gebruikt door iedereen die iets over de wereld wilde weten, en de naam van de man die het schreef werd daar verbasterd tot iets wat hij zelf niet zou hebben herkend.',
    'Maar het was er. Het klopte. De kusten zaten op de goede plek, en de bocht die er niet was, was eruit.',
  ] },
  { nummer: 6, titel: 'Het gewicht op het perkament', tekst: [
    'De sleutel lag al die jaren op de tafel.',
    'Haar vader had hem gekregen van een metselaar in Fes toen Sanaa klein was, in ruil voor een kaart. Hij gebruikte hem als gewicht: perkament rolt op, en je hebt iets nodig dat zwaar genoeg is en dat je inkt niet vlekt.',
    'Acht punten aan de kop. Een ster.',
    'Toen ze terugvoeren naar Ceuta — haar vader oud, zijzelf tweeëntwintig en getrouwd met een man uit Palermo die mee wilde — zat hij in de kist met het gereedschap.',
    'Sanaa heeft nooit kaarten getekend. Vrouwen deden dat niet, en ze had het ook niet doorgezet toen ze het had gekund.',
    'Ze heeft wel inkt gemaakt. Haar leven lang, voor iedereen die erom vroeg, en ze heeft het recept aan haar dochter geleerd en die aan de hare.',
    'En ze heeft dat schrift bewaard waarin stond dat het in Palermo naar citroen rook en dat er op dezelfde ochtend drie soorten klokken en de oproep tot gebed klonken.',
    'Van al haar spullen is dat het enige dat bewaard is gebleven, en het is er nu ook niet meer.',
    'De sleutel wel.',
  ] },
]
