import type { Hoofdstuk } from './sleutels'

/** Deel 15 — De doos van jeddti. Utrecht en de Hoge Atlas, nu. */
export const DEEL15_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Drie weken', tekst: [
    'Adil wilde niet mee, en hij had er drie weken lang elke dag iets over gezegd.',
    'Hij was dertien. Zijn vrienden bleven de hele zomer in Utrecht. Er was een toernooi in juli waar hij voor was ingeschreven en dat hij nu ging missen.',
    'Hij stond linksachter en hij was er goed in, en het team zou het zonder hem moeten doen tegen een ploeg waar ze het jaar ervoor met 4-1 van hadden verloren.',
    'En hij ging in plaats daarvan drie weken naar een dorp in de bergen waar het internet niet werkt.',
    '“Je oma is oud,” zei zijn moeder.',
    '“Ze is elk jaar oud.”',
    'Dat had hij niet moeten zeggen. Hij zag het op haar gezicht en hij wist het meteen en hij kon het niet meer terugnemen.',
    'Zijn moeder heeft er niets van gezegd. Ze is de keuken uit gelopen en heeft de deur niet dichtgedaan, want ze doet nooit een deur hard dicht, en dat is erger.',
    'Ze zaten twee dagen later in het vliegtuig.',
    'Op Schiphol kocht ze bij de gate een zak snoep die hij al jaren niet meer lust, en hij heeft hem aangenomen en opgegeten.',
    'In de auto van het vliegveld naar het dorp — vier uur, waarvan het laatste uur over een weg die eigenlijk geen weg is — zei hij niets en keek hij uit het raam naar bergen die precies op elkaar leken.',
    'Hij heeft later uitgerekend dat hij dat toernooi met 3-0 heeft gemist en dat ze zonder hem hebben gewonnen.',
    'Het is het enige van die zomer waar hij nooit meer aan heeft gedacht.',
  ] },
  { nummer: 2, titel: 'Het dorp', tekst: [
    'Het dorp ligt op negentienhonderd meter en bestaat uit tweeëntwintig huizen, een moskee, een winkel die eigenlijk iemands voorkamer is, en een walnotenboom waar iedereen onder zit.',
    'Er is stroom. Die is er sinds Adils moeder een jaar of achttien was; daarvoor deed het hele dorp het met petroleum en met vroeg naar bed gaan.',
    'Zijn moeder wijst nog steeds de plek aan waar de mannen van de elektriciteit hun auto hadden neergezet, alsof dat gisteren was.',
    'Er is geen bereik. Op één plek wel, op de rots achter het huis van zijn oudoom, en daar staan elke avond tussen zeven en acht vier jongens naast elkaar met hun telefoon omhoog, als een soort gebed.',
    'Adil stond daar de eerste week ook.',
    'De tweede week nog twee keer.',
    'De derde week is hij er niet meer geweest, en dat kwam niet doordat hij het had opgegeven. Het kwam doordat er iets anders was gaan gebeuren.',
    'Maar dat wist hij in die eerste week nog niet, en in die eerste week was het vooral stil. Zo stil dat hij er niet van kon slapen. In Utrecht slaapt hij met zijn raam open boven een straat waar de hele nacht iets rijdt. Hier hoorde hij zijn eigen oren.',
    'En een ezel, om vier uur, elke ochtend, precies.',
    'Hij heeft op de derde nacht geprobeerd uit te vinden van wie die ezel was, om het eerlijk te kunnen opnemen tegen iemand, en het bleek er een van zijn oma te zijn.',
    'Zijn neef Ilyas was veertien en sprak drie talen, waarvan er geen één Nederlands was. Die heeft de eerste dagen opgelost door Adil overal mee naartoe te nemen en nooit iets te vragen.',
    'Ze hebben twee hele dagen samen doorgebracht met in totaal misschien veertig woorden, en dat was niet ongemakkelijk, en Adil heeft daar later vaak aan gedacht als mensen zeiden dat je zonder taal niets kunt.',
  ] },
  { nummer: 3, titel: 'De vrouw die praat', tekst: [
    'Het probleem met zijn oma was niet dat hij haar niet mocht.',
    'Het probleem was dat hij haar niet verstond.',
    'Ze sprak Tamazight en een beetje Darija, en hij sprak Nederlands en een beetje Darija, en dat beetje van hem was niet hetzelfde beetje als dat van haar.',
    'Zijn beetje bestond uit eten, begroetingen, en de drie dingen die zijn moeder zegt als ze kwaad wordt.',
    'Dus ging het zo: zij praatte, hij knikte. Zij vroeg iets, hij keek naar zijn moeder. Zijn moeder vertaalde. Hij antwoordde in het Nederlands. Zijn moeder vertaalde terug.',
    'Alles wat hij tegen zijn eigen oma zei, ging via iemand anders.',
    'En bij het vertalen ging er altijd iets af. Zijn oma zei vier zinnen en zijn moeder zei: “Ze vraagt of je genoeg hebt gegeten.” Dat kan niet alles geweest zijn.',
    'Hij had dat zijn hele leven normaal gevonden.',
    'Die zomer viel hem voor het eerst op dat zijn oma tijdens het vertalen altijd naar hem bleef kijken, en niet naar zijn moeder.',
    'Alsof ze wachtte.',
  ] },
  { nummer: 4, titel: 'Hoe het weggaat', tekst: [
    'Op een avond vroeg hij het aan zijn moeder, op het dak, toen het al donker was.',
    'Waarom hij het nooit had geleerd.',
    'Zijn moeder was elf toen ze naar Nederland kwam. Ze sprak Tamazight met haar moeder, Darija op straat, en ze leerde Nederlands op een school in Utrecht waar ze het eerste jaar in een apart lokaal zat.',
    '“Ze hebben tegen oma gezegd dat ze thuis Nederlands moest praten,” zei ze. “Voor mij. Anders zou het in de war lopen in mijn hoofd.”',
    '“En deed ze dat?”',
    '“Ze kón dat niet. Ze sprak geen Nederlands. Dus deed ik het.”',
    'Dat advies was niet kwaadaardig en het werd overal gegeven: door de juf, door het consultatiebureau, door buren die het goed bedoelden.',
    'Het is alleen niet waar. Kinderen raken niet in de war van twee talen. Wie zijn eerste taal goed kent, leert de tweede juist makkelijker — dat weten we inmiddels zeker. Toen wist men het niet, of men wilde het niet weten.',
    'Er was in die jaren zelfs les in. Onderwijs in Eigen Taal, op de gewone basisschool, begonnen in de jaren zeventig, bedoeld voor kinderen van gastarbeiders die ooit weer terug zouden gaan.',
    'Alleen was die les voor Marokkaanse kinderen bijna altijd in het Standaardarabisch.',
    'Dat is niet hetzelfde als Darija en het is al helemaal niet hetzelfde als Tamazight. Het is ongeveer zo ver weg als Latijn van het Nederlands.',
    'Dus zat Adils moeder op woensdagmiddag een taal te leren die haar eigen moeder niet sprak.',
    'Ze is er na twee jaar mee gestopt, en dat is niemand opgevallen.',
    'In 2004 zijn die lessen afgeschaft.',
    'Zo gaat een taal dus weg. Niet met een knal. Met goedbedoeld advies, een verkeerde les op woensdagmiddag, en een generatie die het druk heeft.',
    'De eerste generatie spreekt de taal. De tweede verstaat hem. De derde kent er nog een woord of vier van, en die gaan over eten.',
    '“En ik ben de derde,” zei Adil.',
    '“Ja,” zei zijn moeder. “Jij bent de derde.”',
    'Ze zei daarna nog iets wat hij niet had verwacht, namelijk dat zij het ook kwijt was aan het raken. Dat ze soms een woord zocht en het niet vond, en dat ze dan maar Nederlands zei en dat haar moeder dan knikte.',
    'Ze zaten daarna nog een hele tijd op dat dak zonder iets te zeggen, wat voor allebei makkelijker was.',
  ] },
  { nummer: 5, titel: 'De kast', tekst: [
    'Op de vierde dag regende het, wat daar bijna nooit gebeurt, en er was niets te doen.',
    'Zijn oma gaf hem een doek en wees naar de kast in de goede kamer, en het was duidelijk wat de bedoeling was: afstoffen.',
    'De goede kamer is de kamer waar niemand zit. Er staan banken langs drie muren, er ligt een tapijt dat zijn oma zelf heeft geweven, en er hangt een foto van een man die zijn opa is en die hij nooit heeft gekend.',
    'Op de bovenste plank stond een koperen doos.',
    'Adil zette hem op tafel en maakte hem open omdat hij dertien was en er niemand keek.',
    'Er zat rommel in. Een ring. Knopen. Een foto van een man met een hoed. Een stuk stof dat ooit rood was geweest.',
    'De foto was het vreemdste. Niemand in de familie had ooit zo’n hoed gedragen, en niemand wist meer wie het was.',
    'En onderin iets van brons dat zwaar was in zijn hand.',
    'Zo lang als zijn hand, groen uitgeslagen, met een kop waar acht punten in zaten.',
    'Een ster.',
    'Hij hield hem tegen het licht van het raam, en zijn oma kwam binnen met twee glazen thee en bleef staan in de deuropening.',
    'Ze zei iets.',
    'Adil verstond één woord: sarut.',
    'Sleutel.',
  ] },
  { nummer: 6, titel: 'Hij past nergens op', tekst: [
    'Hij heeft het die middag geprobeerd. Elke deur in het huis, ook de kelder en de schuur.',
    'Hij past nergens op.',
    'Dat is ook logisch, want de sloten die hier in de deuren zitten zijn van ijzer en van deze eeuw, en deze sleutel is van brons.',
    'Toen zijn moeder thuiskwam van de markt, vroeg hij het haar.',
    '“Van wie is die sleutel?”',
    'Zijn moeder pakte hem aan en draaide hem om, en ze zei dat ze het niet wist.',
    'Ze zei ook dat ze hem haar hele jeugd in die doos had zien liggen en er nooit naar had gevraagd, en dat ze dat nu een beetje dom vond.',
    '“Vraag het haar dan.”',
    'Dus vroeg zijn moeder het, en zijn oma begon te praten, en ze praatte lang.',
    'Zijn moeder vertaalde stukjes.',
    '“Van haar man. Van zijn vader. Uit een kist. Iets over het Rif.”',
    '“En daarvoor?”',
    'Nog meer praten.',
    '“Ze zegt: daarvoor weet niemand het.”',
    'Zijn oma zei daarna nog iets, korter, en zijn moeder lachte.',
    '“Wat zegt ze?”',
    '“Ze zegt: vraag het zelf, dan vertel ik het je zelf.”',
  ] },
  { nummer: 7, titel: 'Vierentwintig woorden', tekst: [
    'Het begon als koppigheid en het werd iets anders.',
    'Adil vroeg zijn moeder die avond om tien woorden. Gewoon tien. Woorden die je nodig hebt als je iets wilt vragen.',
    'Wat. Wie. Waar. Wanneer. Waarom. Ja. Nee. Alsjeblieft. Dankjewel. Nog een keer.',
    'Hij schreef ze op in zijn telefoon zoals ze klonken, niet zoals ze horen.',
    'De volgende ochtend ging hij bij zijn oma in de keuken staan en zei: “Shnu?” terwijl hij naar de pot wees.',
    'Zijn oma keek op.',
    'Wat er toen gebeurde was dit: ze zette de pot neer, ze veegde haar handen af, en ze ging zitten.',
    'En toen begon ze te praten op een andere manier dan alle dagen ervoor. Langzamer. Met haar handen. Ze wees dingen aan en zei hoe ze heetten, en als hij het nazei, knikte ze en zei ze het nog een keer.',
    'Ze hebben die ochtend twee uur in de keuken gezeten.',
    'Hij heeft er een stuk of tien fout gezegd, en bij twee daarvan heeft Ilyas in de deuropening zo moeten lachen dat hij weg moest lopen.',
    'Zijn oma lachte niet. Ze zei het nog een keer.',
    'Aan het eind van de week kende hij vierentwintig woorden.',
    'Het is niets. Vierentwintig woorden is niets.',
    'Het was het meeste wat hij ooit in zijn leven met haar had gedeeld.',
  ] },
  { nummer: 8, titel: 'De taal die niemand opschrijft', tekst: [
    'Er is iets grappigs met het woord dat hij als eerste had verstaan.',
    'Sarut. Sleutel.',
    'In het Standaardarabisch heet een sleutel miftah. Dat is niet hetzelfde woord en het lijkt er ook niet op.',
    'Sarut komt uit het Tamazight: tasarut.',
    'Het woord dat een Marokkaanse jongen in Utrecht om zijn nek draagt is dus geen Arabisch woord. Het is ouder dan het Arabisch in dit land.',
    'Zo zit Darija in elkaar.',
    'De ruggengraat is Arabisch, dat klopt. Maar er zit Amazigh in — in de woorden, in de klanken, in de manier waarop een zin loopt. Er zitten Spaanse woorden in, van de eeuwen aan de overkant en de eeuwen daarna: simana is een week, kuzina is de keuken. Er zitten Franse woorden in, van het protectoraat: tomobil, tobis, bshklit.',
    'En het is geen mengelmoes, en het is al helemaal geen gebroken Arabisch, want het heeft eigen regels en iedereen houdt zich eraan.',
    'Je zegt niet zomaar ergens ma en sh omheen: zo zeg je hier nee, en dat ligt vast. Je zet ghadi voor een werkwoord en je hebt het over morgen. Dat is grammatica. Die heeft niemand bedacht, niemand opgeschreven, en toch maakt niemand die de taal spreekt er fouten in.',
    'Een kind van vier in Casablanca heeft die regels al in zijn hoofd zitten, zonder één les, en het kan ze niet uitleggen.',
    'Wat Darija bijna niet heeft, is papier.',
    'Het is de taal van de keuken, de straat, de grap, de ruzie en het slaapliedje. Op school staat Standaardarabisch op het bord, en Frans op de andere helft. In de krant staat Standaardarabisch. Op het formulier bij de gemeente ook.',
    'Er zijn mensen die het wel opschrijven, met Latijnse letters en cijfers erin voor klanken die niet bestaan in het alfabet, en dat gebeurt elke dag miljoenen keren in berichtjes. Dat is geen spelling en niemand die het zo schrijft denkt dat het dat is.',
    'Een taal die iedereen spreekt en niemand schrijft, is precies de taal die het snelst verdwijnt als een familie verhuist. Er is niets om op terug te vallen. Geen boek, geen les, geen woordenboek dat je uit de kast trekt als je het even kwijt bent.',
    'Er is alleen iemand die hem tegen je praat.',
    'Daarom is vierentwintig woorden niet niets.',
  ] },
  { nummer: 9, titel: 'Wat ze vertelde', tekst: [
    'Met vierentwintig woorden en twee handen en zijn moeder erbij voor de moeilijke stukken, heeft hij in die drie weken meer over zijn familie gehoord dan in dertien jaar.',
    'Dat haar vader onderwijzer was geweest.',
    'Dat hij boeken in een kist had begraven toen ze het dorp moesten verlaten, en dat er iemand vijftig jaar later op was gestuit met een schop.',
    'Dat er in die kist iets zat dat niemand kon thuisbrengen.',
    'Dat haar moeder had gezegd: bewaren, want het is van een huis.',
    'Dat er een broer was geweest die ze nooit meer heeft gezien, en dat ze daarover niet verder wilde praten, en dat zijn moeder dat ook niet eerder had geweten.',
    '“Welk huis?” vroeg Adil, in het Nederlands, en zijn moeder vertaalde.',
    'Zijn oma keek hem aan en zei iets waar zijn moeder even over moest nadenken voordat ze het zei.',
    '“Ze zegt: dat is niet belangrijk.”',
    '“Wat is dan belangrijk?”',
    '“Ze zegt: dat er iemand is die vraagt.”',
  ] },
  { nummer: 10, titel: 'De ster die overal is', tekst: [
    'Toen hij de sleutel eenmaal had, ging hij hem overal zien.',
    'Acht punten. Twee vierkanten over elkaar, een kwartslag gedraaid.',
    'In de tegels bij de moskee van het dorp. In het hek van de school in het dal. In het houtsnijwerk boven de deur van de winkel die eigenlijk een voorkamer is. Op de theeglazen. Op het deksel van de koperen doos zelf, als je hem kantelde tegen het licht.',
    'Hij vroeg Ilyas hoe dat heette.',
    '“Khatam,” zei Ilyas.',
    'Dat betekent zegel. Een stempel die je ergens op zet, zodat iedereen kan zien: dit hoort bij ons, en het is af.',
    'Je vindt hem in de Koran, als teken tussen de stukken. Je vindt hem in het zellige van Fes en Marrakech, waar hele wanden vanaf één zo’n ster zijn uitgerekend, met een passer, door mannen die niet konden lezen maar de meetkunde in hun handen hadden zitten.',
    'Je vindt hem ook ver buiten Marokko: in Bagdad, in Granada, in Isfahan, en op een kerkvloer in Italië waar iemand hem heeft nagemaakt zonder te weten waar hij vandaan kwam.',
    'En je vindt hem in de kop van een sleutel die achttienhonderd jaar oud is.',
    'De ster op de Marokkaanse vlag is deze trouwens niet. Die heeft vijf punten, en hij hangt er pas sinds 1915.',
    'De ster met acht punten is veel ouder en heeft nooit een land gehad.',
    'Hij is alleen maar overal.',
  ] },
  { nummer: 11, titel: 'De laatste dag', tekst: [
    'Op de laatste ochtend stonden de koffers in de gang.',
    'Adil ging naar de keuken en zijn oma stond bij het aanrecht met haar rug naar hem toe, en hij wist dat als hij niets zei, dit weer een jaar zou zijn zoals alle andere.',
    'Hij had het de avond ervoor geoefend. Zesentwintig keer, op het dak, hardop.',
    'Hij had Ilyas gevraagd of het klopte, en Ilyas had gezegd van wel, en hij weet tot vandaag niet of dat waar was of aardig.',
    '“Jeddti.”',
    'Ze draaide zich om.',
    'Hij zei de zin.',
    'Zes woorden. Hij weet zeker dat hij er twee verkeerd uitsprak, en hij weet ook zeker dat de zinsvolgorde niet klopte.',
    'Wat hij zei was: *Ik kom volgend jaar terug, jeddti.*',
    'Zijn oma stond een hele tijd stil.',
    'Toen kwam ze naar hem toe en pakte zijn gezicht met twee handen vast, en ze zei iets terug wat hij niet verstond en ook niet hoefde te verstaan.',
    'In de auto naar het vliegveld huilde hij, en hij deed alsof het door de airco kwam, en zijn moeder heeft er niets van gezegd.',
    'Dat vond hij het aardigste wat ze ooit voor hem gedaan had.',
  ] },
  { nummer: 12, titel: 'Wat hij meekreeg', tekst: [
    'In zijn rugzak, tussen zijn shirts, vond hij hem toen hij thuis uitpakte.',
    'De sleutel.',
    'Er zat een briefje bij, in het handschrift van zijn moeder, want zijn oma kon niet schrijven.',
    'Er stond één regel op.',
    '*Voor jou. Vraag het volgend jaar zelf.*',
    'Adil heeft hem aan een koord om zijn nek gehangen, en hij draagt hem nog steeds, en op school vraagt iemand er ongeveer één keer per maand naar.',
    'Dan zegt hij: hij is van een huis dat er niet meer is.',
    'En als ze doorvragen, zegt hij dat het uit Marokko komt, en dat hij niet weet hoe oud hij is.',
    'Dat laatste is waar.',
    'Wat hij niet weet, en wat jij nu wel weet, is dit.',
    'Hij is gesmeed in Walili, achttienhonderd jaar geleden, door de grootvader van een meisje dat Tala heette en dat honderd kruiken telde en op negenennegentig uitkwam.',
    'Hij is meegegaan over een zeestraat in de tuigage van een paard.',
    'Hij heeft honderdveertig jaar in de muur van een school gelegen die een vrouw met haar eigen geld bouwde toen niemand snapte waarvoor.',
    'Hij heeft in een poort van Marrakech gezeten, op een tafel in Palermo, in een kist die dertig jaar de wereld rondging, in de band van een boek in Rome, op een slagveld, achter de tegels van een paleis dat is afgebroken, in het zand van een stad die nog niet bestond, in een kist met papieren op een schip met een nieuwe vlag, in een begraven boekenkist in het Rif, in een vals boek in een drukkerij in Casablanca, en in een koperen doos in een dorp in de Hoge Atlas.',
    'Hij is al die tijd door niemand bewaard omdat hij kostbaar was. Hij is bewaard omdat iemand hem niet weg kon gooien.',
    'En nu hangt hij om de nek van een jongen van dertien in Utrecht die vierentwintig woorden kent.',
    'Het worden er meer.',
  ] },
]
