import type { Hoofdstuk } from './sleutels'

/** Deel 3 — Wat Fatima bouwde. Fes, 859. */
export const DEEL3_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Water dragen', tekst: [
    'Hind was dertien en ze droeg water, en dat was alles wat iemand van haar wist.',
    'Ze had geen ouders. Dat is een zin die je snel opschrijft en die een heel leven beslaat. Haar moeder was gestorven toen zij vier was, haar vader twee jaar later op weg naar Kairouan, en sindsdien woonde ze bij de familie van haar moeders zus, in een huis met te weinig kamers en te veel kinderen.',
    'Ze klaagde niet. Ze was er ook niet dankbaar voor. Ze droeg water.',
    'Elke ochtend liep ze naar de rivier met twee kruiken aan een juk, en elke ochtend zag ze de bouwplaats.',
    'Die lag aan de overkant van de straat, op een stuk grond waar tot vorig jaar niets had gestaan. Nu stonden er stellingen, lagen er stapels steen, en werkten er mannen van zonsopgang tot het te donker werd.',
    'Iedereen in Fes had er een mening over.',
    '“Een moskee,” zei haar tante. “Er zijn al moskeeën.”',
    '“Ze betaalt het zelf,” zei de buurvrouw. “Uit de erfenis van haar vader. Alles. Tot de laatste munt.”',
    '“Dan is ze gek.”',
    'Hind zei niets, want niemand vroeg haar iets. Maar ze keek elke ochtend, en ze zag iets wat de anderen blijkbaar niet zagen.',
    'De bouwplaats had een vorm.',
    'Niet zomaar muren. Er was een binnenhof gepland die groter was dan het gebouw eromheen, en aan drie kanten kwamen er rijen bogen. Daar paste geen bidruimte in. Daar paste iets anders in, iets wat Hind niet kon benoemen omdat ze het nooit had gezien.',
  ] },
  { nummer: 2, titel: 'De vrouw met het stof', tekst: [
    'De eerste keer dat ze haar sprak, wist ze niet wie ze was.',
    'Het was midden op de dag. Hind bracht water naar de metselaars — dat was er sinds een maand bij gekomen, en het leverde koper op — en bij de put stond een vrouw in een eenvoudige jurk met stof tot aan haar ellebogen.',
    '“Mag ik?” vroeg de vrouw.',
    'Hind gaf haar de schep.',
    'De vrouw dronk, veegde haar mond af en keek naar de stellingen.',
    '“Wat vind je ervan?”',
    'Hind wist niet of ze antwoord moest geven.',
    '“Ik vind het te groot,” zei ze toen.',
    'De vrouw lachte. “Waarom?”',
    '“Voor wie is het? Er zijn al moskeeën. Er zijn geen mensen genoeg.”',
    '“Nee,” zei de vrouw. “Nu niet.”',
    'Ze zette de schep terug.',
    '“Mijn vader kwam hier vandaan de zee. Uit Kairouan. Hij had niets en hij is met handel begonnen, en toen hij stierf had hij genoeg om zijn dochters iets na te laten.” Ze keek Hind aan. “Ik heb geen zoon. Ik heb geen man meer. Ik heb geld en ik heb een stad die vol loopt met mensen die uit alle richtingen komen.”',
    '“En dan bouw je dit.”',
    '“En dan bouw je dit,” zei de vrouw.',
    'Ze liep terug naar de stellingen, en pas toen een voorman zich omdraaide en “Lalla Fatima” zei, begreep Hind wie er water uit haar schep had gedronken.',
  ] },
  { nummer: 3, titel: 'Wat er tussen de bogen past', tekst: [
    'Vanaf die dag lette Hind beter op.',
    'Ze telde de bogen. Ze telde de dagen. Ze leerde de namen van de steensoorten van de metselaars, die haar uitlachten en het haar daarna toch vertelden.',
    'En ze begreep waarom het niet klopte.',
    'Een moskee is voor bidden. Dit gebouw had ruimtes die daar niets mee te maken hadden: kleine kamers langs de rand van de binnenhof, met elk een deur en een raam. Nissen in de muren, op de hoogte van een zittende man.',
    '“Waar zijn die voor?” vroeg ze aan de oudste metselaar.',
    '“Boeken,” zei hij.',
    '“Boeken?”',
    '“Ze wil dat er boeken staan. En mensen die erbij zitten.” Hij spuugde in zijn handen. “Een moskee waar geleerd wordt, zegt ze. Ik doe wat ze zegt. Ik denk er niet over na.”',
    'Hind dacht er wel over na.',
    'Ze kon niet lezen. Bijna niemand die zij kende kon lezen. Lezen was iets voor kooplieden en voor de zonen van kooplieden, en voor mannen die daar jaren voor naar een andere stad gingen.',
    'Als er boeken in een binnenhof staan, en er zitten mensen bij die er hardop uit voorlezen, dan hoeft niemand ergens heen.',
    'Dan komt het naar hier.',
    'Ze zette haar kruiken neer op de rand van de put en ging zitten, en ze bleef daar zo lang zitten dat de voorman riep of ze soms betaald werd om te kijken.',
  ] },
  { nummer: 4, titel: 'De steen die niet paste', tekst: [
    'Het ging mis in het derde jaar.',
    'Het geld raakte op. Niet ineens — zoals geld opraakt: eerst twee dagen later betalen, dan een week, dan mannen die niet meer kwamen opdagen omdat ze elders wel geld kregen.',
    'De bouwplaats werd stil. Er stonden vier muren en een halve rij bogen, en er lag een stapel steen die langzaam begroeid raakte.',
    'In de stad werd erover gepraat op de toon waarop mensen praten als ze gelijk hebben gekregen.',
    '“Ik zei het toch.”',
    '“Een vrouw die bouwt.”',
    'Hind droeg water naar andere plekken. Ze hield niet op met langs de bouwplaats lopen.',
    'Op een ochtend stond Lalla Fatima er weer, alleen, met haar hand op een steen.',
    'Hind bleef staan met haar juk op haar schouders.',
    '“Het spijt me,” zei ze, en ze wist zelf niet precies waarvoor.',
    'Fatima keek op. Ze zag er ouder uit dan drie jaar geleden.',
    '“Weet je wat ik verkeerd heb gedaan?” zei ze. “Ik heb geteld wat ik had. Ik heb niet geteld wat het kost om iets te bouwen dat er nog nooit is geweest.”',
    '“Gaat het door?”',
    '“Ja.”',
    '“Hoe?”',
    'Fatima haalde haar schouders op, en voor het eerst leek ze op iedereen.',
    '“Langzamer,” zei ze. “Dat is hoe.”',
  ] },
  { nummer: 5, titel: 'Wat een stad doet', tekst: [
    'Wat er daarna gebeurde, heeft Hind haar hele leven niet helemaal kunnen uitleggen.',
    'Het begon met de metselaars. Drie van hen kwamen terug, onbetaald, en gingen verder waar ze gestopt waren. Niemand had ze gevraagd.',
    'Toen kwam er een koopman met een kar steen. Daarna nog een.',
    'De bakker aan de overkant begon brood te brengen om twaalf uur, elke dag, voor wie er werkte. Zijn vrouw zei dat hij gek was. Hij bleef het doen.',
    'Er kwam geld binnen dat niemand kon herleiden. Kleine bedragen. Iemand liet een zak bij de put staan.',
    'En Hind droeg water, want dat was wat zij had.',
    'Ze droeg het gratis. Ze had het koper nodig en ze deed het toch, en als haar tante ernaar vroeg zei ze dat ze het bij de rivier had verspeeld.',
    'Het duurde nog vier jaar.',
    'Op de dag dat de laatste boog werd gesloten, stond er zoveel volk in de straat dat de karren er niet door konden. Hind stond tussen de mensen met haar juk nog op haar schouders, omdat ze net van de rivier kwam en niet had willen wachten.',
    'Ze zag Lalla Fatima niet. Die stond ergens binnen, of thuis; daar werd later over gediscussieerd en niemand wist het zeker.',
    'Wat Hind wel zag, waren de kamers langs de binnenhof.',
    'Er stonden boeken in.',
  ] },
  { nummer: 6, titel: 'De sleutel in de muur', tekst: [
    'Ze is er tien jaar later nog een keer geweest, en toen kon ze lezen.',
    'Niet goed. Genoeg om een bord te ontcijferen en de eerste regel van een bladzijde, en daarna langzaam de tweede. Een man die bij de bogen zat had het haar geleerd omdat ze het gevraagd had, en omdat hij zei dat het zoeken naar kennis niet alleen voor de zonen van kooplieden was.',
    'Ze was toen drieëntwintig en getrouwd en ze had een dochter, en aan die dochter heeft ze het hele verhaal verteld, elk jaar opnieuw, tot het meisje het uit haar hoofd kende.',
    'Dit is het stuk dat er niemand anders van wist.',
    'In het eerste jaar, toen ze water bracht en de fundamenten nog open lagen, had ze iets in de muur gelegd.',
    'Ze had het gevonden in het zand bij de rivier: iets van brons, zo lang als haar hand, met een kop van acht punten. Ze had het meegenomen zonder te weten waarom, en toen de metselaars een nis dichtmetselden had ze het erin laten glijden tussen twee stenen.',
    'Ze wist niet waarom ze dat deed. Ze was dertien.',
    'Later dacht ze: ik wilde dat er iets van mij in stond.',
    'De sleutel bleef daar honderdveertig jaar zitten, tot er verbouwd werd en een metselaar hem eruit haalde en in zijn zak stak, en dat is hoe hij verder reisde.',
    'Het gebouw staat er nog. Er wordt nog steeds geleerd. Het heet al-Qarawiyyin, naar de stad waar Fatima’s vader vandaan kwam, en het is de oudste school ter wereld die nooit is opgehouden.',
    'En het is er gekomen omdat een vrouw haar hele erfenis uitgaf aan iets waarvan niemand snapte waar het goed voor was, en een stad langzaam besloot dat ze gelijk had.',
  ] },
]
