import type { Hoofdstuk } from './sleutels'

/** Deel 14 — Zwart op wit. Rabat en de Hoge Atlas, 2011. */
export const DEEL14_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'De taal van thuis', tekst: [
    'Anir was twaalf en hij sprak twee talen, en op school telde er maar één.',
    'Thuis sprak iedereen Tamazight. Zijn oma sprak niets anders. Op school was alles Arabisch, en wie thuis geen Arabisch sprak begon achter en liep dat zelden in.',
    'Dat was niet iets waar hij boos over was. Het was gewoon hoe het was, zoals de winter koud is.',
    'Zijn oma heette Tadla en ze kon niet lezen. Niet in het Arabisch, niet in iets anders. Ze was in 1938 geboren in een dorp met geen school, en ze had zes kinderen grootgebracht en twee begraven, en ze wist alles over schapen en kruiden en niets over letters.',
    'Ze schaamde zich er niet voor. Ze zei: ik heb mijn hoofd gebruikt voor andere dingen.',
    'Maar als er post kwam, gaf ze hem aan Anir en dan keek ze de andere kant op terwijl hij voorlas.',
  ] },
  { nummer: 2, titel: 'Wat er in de krant stond', tekst: [
    'In de zomer van 2011 stond er iets in de krant dat zijn vader hardop voorlas aan tafel.',
    'Er kwam een nieuwe grondwet. En daarin stond dat Tamazight een officiële taal van het land werd, naast het Arabisch.',
    'Anir snapte niet meteen wat dat betekende.',
    '“Het betekent,” zei zijn vader, “dat het op papier mag.”',
    '“Het mocht toch al?”',
    'Zijn vader lachte, maar niet vrolijk.',
    '“Vraag je oma eens of haar naam ooit ergens goed geschreven stond.”',
    'Anir vroeg het.',
    'Zijn oma dacht lang na en zei toen dat op haar papieren een Arabische naam stond die haar moeder haar nooit had gegeven, omdat de ambtenaar in 1938 had gezegd dat de naam die ze wél had niet kon.',
    'Ze had zeventig jaar een naam gehad die niet de hare was.',
  ] },
  { nummer: 3, titel: 'Tifinagh', tekst: [
    'Op school kwam er dat jaar een uur bij.',
    'Tamazight, met een schrift dat Anir nog nooit had gezien: Tifinagh.',
    'Het lijkt op niets. Geen Arabisch, geen Latijn. Cirkels, driehoeken, kruisjes, lijnen met puntjes. Het ziet eruit alsof iemand het gisteren heeft bedacht.',
    'Dat is precies het tegenovergestelde van waar.',
    'De juf liet ze een foto zien van een rots in het zuiden waarop hetzelfde schrift stond, en ze zei dat die tweeduizend jaar oud was. Ouder dan de meeste dingen waar ze op school over leerden.',
    'Het is altijd blijven bestaan bij de Toeareg in de Sahara. In het noorden was het bijna verdwenen, en in 2003 is er een versie vastgesteld die op scholen gebruikt kan worden.',
    'Anir vond het eerst kinderachtig. Rondjes en streepjes.',
    'Toen schreef hij zijn eigen naam.',
    'ⴰⵏⵉⵔ',
    'Hij heeft dat blaadje bewaard.',
  ] },
  { nummer: 4, titel: 'Zestien lessen', tekst: [
    'Het idee kwam van hemzelf en hij heeft het maandenlang niet durven voorstellen.',
    'Op een avond in oktober zat zijn oma bij de kachel thee te drinken, en hij ging naast haar zitten met een schrift.',
    '“Jeddti. Ik wil je iets leren.”',
    'Ze keek hem aan zoals oude vrouwen naar kinderen kijken die iets willen.',
    '“Ik ben drieënzeventig.”',
    '“Het is maar één letter per keer.”',
    'Ze heeft nee gezegd. Drie avonden achter elkaar.',
    'Op de vierde avond zei ze: “Hoeveel zijn het er?”',
    '“Drieëndertig.”',
    '“Zoveel?”',
    '“Je hoeft er maar vier te leren,” zei Anir. “Voor je naam.”',
    'Dat is hoe het begon.',
    'Het heeft zestien avonden geduurd, want haar handen waren niet gewend om een potlood zo vast te houden en ze werd kwaad op zichzelf.',
    'Op de zeventiende avond schreef ze haar naam.',
    'ⵜⴰⴷⵍⴰ',
    'Ze heeft er lang naar gekeken en toen heeft ze het blaadje omgedraaid en is opgestaan om thee te zetten die niemand had gevraagd.',
  ] },
  { nummer: 5, titel: 'Wat een wet wel en niet doet', tekst: [
    'Het eerlijke deel van dit verhaal is dit.',
    'De wet van 2011 heeft niet meteen iets veranderd.',
    'Het duurde jaren voordat er iets mee gedaan werd. Het duurde tot 2019 voordat er een wet kwam die regelde hóe het moest. Op de meeste scholen is het nog lang niet overal. Ambtenaren die het schrift kunnen lezen zijn zeldzaam.',
    'Er zijn mensen die zeggen dat het symboliek is.',
    'Anir denkt daar anders over, en hij heeft er één argument voor.',
    'Zijn oma heeft op haar drieënzeventigste haar eigen naam geschreven in het schrift van haar eigen taal.',
    'Dat had niet gekund als er niet eerst iemand had gezegd dat het schrift bestond.',
  ] },
  { nummer: 6, titel: 'De koperen doos', tekst: [
    'In het huis stond een koperen doos op de kast waar niemand ooit in keek.',
    'Er zaten dingen in die van familie waren geweest en waarvan niemand meer wist wie: een ring, twee knopen, een stukje stof, een foto van een man die niemand kon thuisbrengen.',
    'En een sleutel van brons, met acht punten aan de kop.',
    'Anir heeft er een keer naar gevraagd.',
    'Zijn oma zei dat haar man hem van zijn vader had, en die van een kist die uit het Rif kwam, en verder wist ze het niet.',
    '“Waar is hij van?”',
    '“Van een huis,” zei ze.',
    '“Welk huis?”',
    'Ze haalde haar schouders op.',
    '“Een huis dat er niet meer is. Daarom bewaren we hem.”',
    'Anir vond dat op dat moment een rare zin.',
    'Later, toen hij zelf ergens anders woonde dan waar hij geboren was, vond hij het de minst rare zin die hij ooit had gehoord.',
  ] },
]
