import type { Hoofdstuk } from './sleutels'

/** Deel 6 — Dertig jaar onderweg. Vanaf Tanger, 1325. */
export const DEEL6_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Vertrekken', tekst: [
    'Op de ochtend dat ze vertrokken, huilde Musa niet, en daar is hij later trots op geweest en heeft hij zich later voor geschaamd.',
    'Hij was dertien. Hij kon lezen en schrijven, wat in zijn straat bijzonder was, en daarom was hij meegegeven aan een jongeman uit Tanger die op bedevaart ging en een hulpje nodig had.',
    'De jongeman was eenentwintig. Hij heette Muhammad ibn Battuta en hij was in zijn leven nog nooit verder geweest dan een dagreis van huis.',
    '“Hoe lang duurt het?” had Musa’s moeder gevraagd.',
    '“Zestien maanden,” had Ibn Battuta gezegd. “Misschien achttien.”',
    'Dat was de waarheid, voor zover iemand hem kende. De bedevaart naar Mekka duurde vanuit Marokko ongeveer een jaar heen en een jaar terug, en dan was je thuis en vertelde je erover tot je stierf.',
    'Ze zijn er dertig jaar over gedaan.',
    'Niemand heeft dat op die ochtend geweten. Musa’s moeder gaf hem brood mee voor drie dagen en zei dat hij moest opletten, en toen liepen ze de poort uit.',
    'Achter hen lag Tanger.',
    'Het was 1325 en ze hadden één ezel.',
  ] },
  { nummer: 2, titel: 'Wat je opschrijft', tekst: [
    'Zijn werk was simpel: opschrijven.',
    'Ibn Battuta praatte de hele dag. Hij praatte tegen iedereen die ze tegenkwamen, hij vroeg alles, en ’s avonds vertelde hij wat hij gehoord had. Musa schreef het op.',
    'In het begin schreef hij alles.',
    '*Vandaag zes uur gelopen. Brood gekocht voor twee munten. Een man vertelde dat er verderop water is.*',
    'Na een maand hield hij daarmee op, want er stond te veel en er stond niets in.',
    'Hij leerde kiezen. Dat was het eerste vak dat hij in zijn leven leerde en hij heeft er nooit les in gehad.',
    'Wat je opschrijft is wat blijft. Wat je weglaat is weg. En het rare is: je weet het op het moment zelf nooit.',
    'In Tlemcen schreef hij een bladzijde over een tuin. In Tunis vergat hij te schrijven dat Ibn Battuta twee dagen ziek was en huilde omdat hij zijn moeder miste.',
    'Dat laatste heeft hij later toch opgeschreven, veertig jaar later, in de kantlijn van een ander boek.',
  ] },
  { nummer: 3, titel: 'Alexandrië', tekst: [
    'Alexandrië was de eerste stad waar Musa niet meer wist waar hij moest kijken.',
    'De vuurtoren stond er nog, half. Er waren zeven poorten en een haven met zoveel masten dat het op een bos leek. Er werden talen gesproken die hij nooit had gehoord.',
    'Ze bleven er langer dan de bedoeling was.',
    'Daar gebeurde het ding dat alles veranderde, en het was een gesprek.',
    'Een oude man — een geleerde bij wie ze logeerden — vroeg aan Ibn Battuta waar hij heen ging.',
    '“Mekka.”',
    '“En daarna?”',
    '“Naar huis.”',
    'De oude man keek hem aan alsof hij iets onzinnigs had gezegd.',
    '“Ik heb broeders in India,” zei hij. “En in China. Ga naar ze toe. Zeg dat ik je gestuurd heb.”',
    'Musa zag het gezicht van Ibn Battuta.',
    'Hij heeft later vaak gezegd dat hij het toen al wist: dat ze niet over achttien maanden thuis zouden zijn.',
    'Dat is waarschijnlijk niet waar. Zo werkt geheugen niet. Maar hij was er wel bij.',
  ] },
  { nummer: 4, titel: 'De jaren', tekst: [
    'Wat volgde, past niet in een hoofdstuk en het past eerlijk gezegd ook niet in een boek.',
    'Ze gingen naar Mekka. Ze gingen naar Perzië en naar de steden aan de Zwarte Zee. Ze voeren langs de kust van Afrika tot aan plaatsen waar de taal veranderde in iets wat op Arabisch leek en het niet was.',
    'Ibn Battuta werd rechter in India en bleef er jaren. Hij werd rijk, en armer dan arm, en toen weer rijk. Hij trouwde meerdere keren. Hij werd beroofd. Hij lag een keer een week ziek in een dorp waar niemand zijn naam kende.',
    'Musa groeide op onderweg.',
    'Hij was dertien toen ze vertrokken en drieëntwintig toen hij voor het eerst overwoog om terug te gaan en het niet deed, en vierendertig toen hij het wel deed.',
    'Hij heeft alles opgeschreven.',
    'Vijf kisten. Papier, perkament, stukken linnen als er niets anders was. In het begin netjes, later in een handschrift dat alleen hij kon lezen.',
    'Wat hierna komt, is er een handvol uit.',
    'Niet de belangrijkste. De hoofdstukken die hij het vaakst heeft overgelezen, wat iets anders is.',
  ] },
  { nummer: 5, titel: 'Mekka', tekst: [
    'Ze kwamen aan in het najaar van het jaar daarna, en Musa was veertien.',
    'Hij had er achttien maanden over gedaan wat een man te paard in vier maanden kan. Zo reisde je: je sloot aan bij een karavaan, je wachtte tot er genoeg mensen waren, je bleef ergens twee maanden omdat de weg onveilig was, je ging mee met wie dezelfde kant op ging.',
    'Van Mekka zelf heeft Musa verrassend weinig opgeschreven.',
    'Dat viel hem later zelf op, toen hij zijn eigen aantekeningen teruglas. Over Alexandrië drie bladzijden. Over Damascus vier. Over Mekka een halve.',
    'Dit staat erop.',
    'Dat het zo vol was dat hij twee keer zijn meester kwijtraakte en hem beide keren terugvond doordat iemand hem herkende aan zijn stem.',
    'Dat er mensen waren uit landen waarvan hij de naam niet kon uitspreken, en dat ze allemaal hetzelfde deden, op hetzelfde moment, in dezelfde richting.',
    'Dat een man naast hem huilde en dat Musa niet wist waarom en het ook niet gevraagd heeft.',
    'Dat hij zelf niets bijzonders voelde, en dat hij zich daarvoor schaamde, en dat hij dat aan niemand ooit heeft verteld behalve aan dit papier.',
    'En helemaal onderaan, in een ander handschrift — hij heeft het er jaren later bij gezet — staat één zin:',
    '*Ik was veertien en ik dacht dat het een begin was. Het was het enige moment in dertig jaar dat we precies waren waar we naartoe wilden.*',
  ] },
  { nummer: 6, titel: 'De broeders van Anatolië', tekst: [
    'Na Mekka gingen ze noordwaarts, en in Anatolië kwam Musa iets tegen waarvan hij dacht dat het niet kon bestaan.',
    'Ze kwamen ’s avonds een stadje binnen waar ze niemand kenden. Geen brief, geen naam, geen plek om te slapen.',
    'Binnen een uur stonden er twee jonge mannen bij hun ezel te ruziën.',
    'Musa dacht eerst dat ze ruzieden mét hen. Dat was niet zo. Ze ruzieden over wie de gasten mocht hebben.',
    'Zo ging het de hele winter door. Elke stad, elk dorp.',
    'Ze heetten *akhi* — broeder — en het waren verenigingen van jonge ambachtslieden. Een leerlooier, een schoenmaker, een smid. Ze legden geld bij elkaar, ze hadden een huis, en van dat geld onderhielden ze dat huis om er vreemden in te ontvangen.',
    'Eten, een bed, een bad, en de volgende ochtend een man die met je meeliep tot de volgende stad om je aan de volgende broederschap voor te stellen.',
    'Musa heeft in zijn aantekeningen uitgerekend wat het kostte. Hij kwam op bedragen waar hij zelf niet van terugkon.',
    '“Waarom?” heeft hij een keer gevraagd, aan een jongen van ongeveer zijn leeftijd die hun ezel verzorgde.',
    'De jongen keek hem aan alsof hij vroeg waarom water nat is.',
    '“Jij bent er,” zei hij.',
    'Dat was het hele antwoord.',
    'Musa heeft dat zijn leven lang het mooiste gevonden wat hij onderweg is tegengekomen. Niet de paleizen, niet Mekka, niet China.',
    'Een stad waar je binnenkomt zonder iets, en waar twee jongens ruziën over wie voor je mag zorgen.',
    'Die broederschappen hebben eeuwen bestaan en zijn daarna verdwenen, en er is bijna niets van over behalve wat reizigers erover hebben opgeschreven.',
    'Eén van die reizigers was hij.',
  ] },
  { nummer: 7, titel: 'De steppe', tekst: [
    'Ten noorden van de Zwarte Zee houdt het land op interessant te zijn en begint het gras.',
    'Musa schrijft: *Achttien dagen. Elke dag hetzelfde. Ik heb niets opgeschreven omdat er niets was, en dat is ook iets.*',
    'Daar woonde een khan die Uzbeg heette, en zijn hofhouding was geen stad maar een kamp dat verhuisde.',
    'Dat is het ding dat Musa niet kon bevatten en dat hij drie keer heeft beschreven om het goed te krijgen.',
    'Duizenden tenten, karren, kudden, een markt, een moskee — alles wat een stad heeft. En dan brak het op en reisde het honderd kilometer verderop en stond het er weer.',
    'De moskee ging mee. Op een kar.',
    'Musa heeft geprobeerd te tellen en is gestopt bij de zesduizend wagens.',
    'Hij schrijft ook iets op wat hem niet losliet: dat de vrouwen daar op hun eigen paard reden, zonder sluier, en dat ze meepraatten waar mannen bij waren, en dat niemand daar iets bijzonders in zag.',
    'Hij had toen al Egypte gezien, en Syrië, en Arabië, en overal was het anders geweest.',
    '*Ik dacht dat ik wist hoe het hoort,* schrijft hij. *Het hoort overal anders.*',
    'Dat is een gedachte die hij in dertig jaar ongeveer twintig keer opnieuw heeft gehad, elke keer alsof het de eerste was.',
  ] },
  { nummer: 8, titel: 'Constantinopel', tekst: [
    'Een van de vrouwen van de khan was een prinses uit Constantinopel, en ze was zwanger, en ze wilde het kind bij haar vader krijgen.',
    'Ze mocht gaan. Er werd een stoet samengesteld, en Ibn Battuta vroeg of hij mee mocht, en dat mocht.',
    'Zo is een rechtsgeleerde uit Tanger in de grootste christelijke stad van de wereld terechtgekomen: omdat hij het vroeg.',
    'Ze zijn er in de winter aangekomen. Musa was achttien.',
    'Hij schrijft over de muren, die hij niet kon geloven. Over kerken waar je tweehonderd mensen in kwijt kon en dan nog ruimte over had. Over een stad die half leeg stond, met wijken waar niemand meer woonde en waar het gras tussen de stenen kwam — want Constantinopel was toen al over zijn hoogtepunt heen, en dat zag je.',
    'Ze zijn bij de grote kerk geweest, de Aya Sofya.',
    'Naar binnen mochten ze niet, tenzij ze voor het kruis bij de deur bogen. Dat deed Ibn Battuta niet, en ze zijn buiten gebleven.',
    'Musa heeft dat opgeschreven zonder er iets van te vinden, wat hij vaker deed als hij het er niet mee eens was.',
    'Wat hij wel opschrijft is een gesprek van een paar dagen later.',
    'Ze aten bij een oom van de prinses, een oude man die Arabisch sprak omdat hij ooit in Egypte had gezeten.',
    'De oude man vroeg: “Hoe bevalt onze stad?”',
    '“Groot,” zei Ibn Battuta.',
    '“Hij was groter.”',
    'En toen zei hij iets waar Musa dertig jaar later nog aan dacht toen hij in Fes zat:',
    '“Alles wat je hier ziet is gemaakt door mensen die dachten dat het zou blijven.”',
    'Honderd jaar later is de stad gevallen en heet hij anders, en staat er in de Aya Sofya geen kruis meer.',
    'Dat heeft Musa niet meer meegemaakt. Maar hij had het antwoord al.',
  ] },
  { nummer: 9, titel: 'Waarvan ze leefden', tekst: [
    'Er is één vraag die kinderen altijd stellen als je dit verhaal vertelt, en het is de beste vraag: waar betaalden ze het van.',
    'Het antwoord is: van geschenken, en dat is ingewikkelder dan het klinkt.',
    'Een geleerde die op reis was, was in die wereld iemand die je in huis nam. Een sultan, een koopman, een gouverneur — die gaven je onderdak, een maaltijd, en bij het vertrek iets mee: geld, een paard, een kleed, soms een bediende.',
    'Dat was geen liefdadigheid. Het was hoe het hoorde, en het leverde de gever iets op: de reiziger vertelde in de volgende stad wie hem goed had ontvangen.',
    'Ibn Battuta was daar goed in. Musa schrijft het zonder oordeel en het staat er toch:',
    '*Hij weet binnen een dag wie er in een stad iets te geven heeft, en hij weet hoe hij ernaartoe moet praten. Ik kan dat niet en ik wil het ook niet leren.*',
    'Het ging soms mis.',
    'Er is een jaar geweest in Perzië waarin ze niets hadden. Twee maanden lang sliepen ze in een moskee en aten ze van wat de mensen daar overhielden.',
    'Musa heeft er één zin over: *Ik heb toen geleerd wat honger met je hoofd doet, en niet met je maag.*',
    'Later, in Dihli, gaf de sultan hem dorpen.',
    'Tussen die twee zinnen zit acht jaar.',
    'Dat is het eerlijkste beeld van dertig jaar reizen dat Musa heeft achtergelaten: het ging niet geleidelijk omhoog. Het ging van niets naar alles naar niets, soms binnen een half jaar, en je wist nooit welke kant je op ging.',
  ] },
  { nummer: 10, titel: 'Dihli', tekst: [
    'India is waar het verhaal gevaarlijk wordt, en dat duurde acht jaar.',
    'Ze kwamen er in 1334 aan, over de bergpassen in het noorden, na een reis waar Musa in zijn aantekeningen alleen over schrijft in aantallen: hoeveel dagen, hoeveel doden, hoeveel water.',
    'De sultan van Dihli heette Muhammad ibn Tughluq en hij was de rijkste man die Musa ooit heeft gezien.',
    'Hij gaf Ibn Battuta een huis, een salaris waar je vijftig families van kon onderhouden, en een ambt: rechter van de hoofdstad.',
    'Hij gaf hem ook dorpen. Letterlijk dorpen, met mensen erin, waarvan de opbrengst voortaan naar hem ging.',
    'Musa heeft in die jaren voor het eerst van zijn leven in een huis gewoond met een binnenhof en bedienden, en hij heeft er twee jaar van genoten en zes jaar niet meer kunnen slapen.',
    'Want dezelfde sultan liet mensen doden.',
    'Niet in een oorlog. Aan het hof, op een gewone dag, om iets wat ze gezegd hadden of niet gezegd hadden.',
    'Musa schrijft over een ochtend waarop hij langs de poort liep en er drie lichamen lagen, en dat de mensen eromheen doorliepen zoals je langs een kar loopt die is omgevallen.',
    'Er is in zijn aantekeningen uit die jaren een zin die hij drie keer heeft opgeschreven, op drie verschillende plekken, wat hij verder nooit deed:',
    '*Hij geeft met dezelfde hand.*',
    'Dat is wat Musa niet kon rijmen en wat hij nooit heeft opgelost. Dezelfde man die je een huis geeft, laat je doden. Niet als straf voor iets wat je hebt gedaan. Omdat hij het die dag zo ziet.',
    'Ibn Battuta is er acht jaar gebleven.',
    'Dat is de eerlijke zin en hij staat er met opzet. Hij wist wat voor man het was, en hij bleef, en hij werd rijk.',
    'Later, in het boek, staat het er allemaal in. Ibn Battuta heeft er niets van verzwegen — niet van de sultan en niet van zichzelf.',
    'Musa heeft daar altijd iets voor gevoeld wat geen bewondering was en ook geen minachting, en waar hij nooit een woord voor heeft gevonden.',
  ] },
  { nummer: 11, titel: 'Het jaar dat hij niets at', tekst: [
    'In het achtste jaar ging het mis, en het ging mis om niets.',
    'Er was een geleerde in Dihli, een vrome man die buiten de stad woonde en die kritiek had op de sultan. De sultan liet hem halen en liet hem doden.',
    'Ibn Battuta had die man gekend. Hij was er twee keer geweest.',
    'Dat was genoeg.',
    'Er kwamen vier ruiters naar het huis die er de hele dag bleven zitten en niets deden. De volgende dag weer. Vijf dagen lang.',
    'Musa schrijft: *Ze kwamen niet om ons te halen. Ze kwamen om ons te laten weten dat ze konden komen.*',
    'Ibn Battuta heeft toen iets gedaan wat Musa nooit had zien aankomen.',
    'Hij hield op met eten.',
    'Hij gaf zijn ambt terug, hij gaf zijn huis op, hij ging naar een man buiten de stad die daar met een handjevol anderen woonde, en hij at vijf dagen lang niets en dronk alleen water.',
    'Musa ging mee, omdat hij nergens anders heen kon, en hij heeft de ergste vijf dagen van zijn leven doorgebracht op een mat in een kamer waar niemand sprak.',
    'Op de zesde dag liet de sultan hem komen.',
    'Musa is er niet bij geweest. Niemand is erbij geweest behalve die twee.',
    'Wat er ook is gezegd, Ibn Battuta kwam terug met een opdracht in plaats van een doodvonnis: hij moest als gezant naar China.',
    'Musa heeft zijn hele leven twee verklaringen gehad en hij wisselde ertussen afhankelijk van zijn humeur.',
    'De ene: een man die alles opgeeft is niet gevaarlijk meer, en dat zag de sultan.',
    'De andere: hij wilde hem gewoon het land uit hebben, en een gezantschap naar China is de beleefdste manier om iemand weg te sturen waar hij misschien nooit van terugkomt.',
    'Ze vertrokken binnen een maand, met honderden mensen, met geschenken op vijftien karren, en met de opluchting van twee mannen die de stad uit reden zonder om te kijken.',
  ] },
  { nummer: 12, titel: 'Alles kwijt', tekst: [
    'Het gezantschap naar China is nooit in China aangekomen, en wat ervan over is, is dit hoofdstuk.',
    'Ze werden onderweg overvallen. Dat gebeurde; het was een stoet met geschenken voor een keizer en dat zie je van ver.',
    'Ze kwamen er levend uit, met minder dan de helft.',
    'Daarna gingen ze verder naar het zuiden, naar de kust, waar de schepen lagen die hen zouden brengen.',
    'Daar ging het echt mis.',
    'De schepen lagen klaar in de haven. De lading was aan boord, de geschenken ook, en Musa’s twee eerste kisten met tien jaar aantekeningen. Ibn Battuta was aan wal gebleven om naar het vrijdaggebed te gaan.',
    'Die nacht kwam er een storm.',
    'Musa heeft het vanaf de kade gezien en er is één zin in zijn aantekeningen die hij nooit heeft doorgestreept: *Het duurde niet lang.*',
    'Alles weg. De geschenken, de schepen, de mensen die aan boord sliepen.',
    'Ze stonden de volgende ochtend op een kade in een vreemd land, met wat ze aanhadden.',
    'Teruggaan naar Dihli kon niet. Je komt niet bij die sultan aan met het bericht dat zijn gezantschap en zijn geschenken op de bodem van de zee liggen.',
    'Ibn Battuta heeft daar op die kade gestaan en Musa schrijft dat hij lachte.',
    'Niet vrolijk. Zoals iemand lacht die begrijpt dat het niet erger kan.',
    '“Waar gaan we heen?” vroeg Musa.',
    'En Ibn Battuta keek naar het zuiden, over het water, waar niets te zien was.',
    '“Daarheen,” zei hij.',
    'Zo zijn ze op de Malediven terechtgekomen: niet omdat ze erheen wilden, maar omdat er een schip die kant op ging.',
    'Dat is het eerlijkste wat je over die dertig jaar kunt zeggen. Het grootste deel ervan is niet gekozen.',
  ] },
  { nummer: 13, titel: 'De kist die overboord sloeg', tekst: [
    'Op de Malediven is Ibn Battuta anderhalf jaar gebleven, en hij is er weer rechter geworden, en hij is er getrouwd, en hij is er met ruzie vertrokken.',
    'Musa vond het de mooiste plek van de hele reis.',
    'Hij schrijft over water waar je doorheen kijkt tot op de bodem. Over vis die ze zoutten en droogden en die naar heel Azië ging. Over huizen van koraal. Over een stilte in de nacht die hij nergens anders heeft gehoord.',
    'En over de lucht voor een storm, die daar anders ruikt, en waar de mensen op af gaan zoals wij op een donkere lucht.',
    'Ze vertrokken in het tweede najaar, op een schip naar Bengalen.',
    'Drie dagen uit de kust kregen ze slecht weer. Niet eens heel slecht; Musa heeft er later erger meegemaakt.',
    'Maar de lading schoof.',
    'Er lagen vier kisten van hem op het achterdek, vastgesjord onder een zeil. Toen het overhelde ging het zeil los.',
    'Drie kisten hielden het. Eén niet.',
    'Er zat drie jaar in. Dihli, het jaar met de ruiters voor de deur, de vijf dagen op de mat, en de storm op de kade waar alles verging.',
    'Musa was tweeëntwintig en hij is die dag over de reling gaan hangen en had achterna willen springen, en een zeeman heeft hem bij zijn riem teruggetrokken en hem uitgescholden.',
    'Hij heeft alles opnieuw opgeschreven. Uit zijn hoofd, in de zes weken daarna, elke avond.',
    'Het was niet hetzelfde. Dat wist hij.',
    'Wat je een half jaar later uit je hoofd opschrijft, is wat je je herinnert, en dat is al iets anders dan wat er was.',
    'Dit is precies wat er met de hele Rihla aan de hand is, en Musa is de enige geweest die dat van dichtbij wist.',
  ] },
  { nummer: 14, titel: 'Wat hij niet heeft gezien', tekst: [
    'Over China moet hier iets eerlijks staan, want in het boek staat het anders.',
    'In de Rihla staat dat Ibn Battuta in China is geweest. Dat hij Quanzhou heeft gezien, en Hangzhou, en de grote rivier, en de keizerlijke stad.',
    'Musa was erbij, en Musa wist het niet zeker.',
    'Ze zijn naar het oosten gevaren. Dat staat vast, en hij heeft de havens gezien en de schepen met vier masten en de mensen die een taal spraken die op geen enkele andere leek.',
    'Wat hij zich niet kan herinneren, is de reis het land in.',
    'Er zit een gat in zijn aantekeningen van ongeveer vijf maanden. Hij is toen ziek geweest; dat staat er wel.',
    'Toen Ibn Juzayy jaren later in Fes zat op te schrijven wat Ibn Battuta hem dicteerde, heeft Musa passages gehoord over steden die hij niet kende.',
    'Hij heeft er één keer iets van gezegd.',
    'Ibn Battuta keek hem aan zoals een oude man kijkt naar iemand die hem al dertig jaar kent.',
    '“Ik heb het gehoord van mannen die er waren,” zei hij.',
    '“Dat is iets anders.”',
    '“Voor jou.”',
    'En dat was het einde van het gesprek.',
    'Musa heeft er nooit ruzie over gemaakt. Hij vond het niet oneerlijk op de manier waarop wij het oneerlijk zouden vinden; zo werd er toen met verhalen omgegaan. Wat je van betrouwbare mensen hoorde, mocht je doorvertellen.',
    'Maar hij heeft het in zijn eigen aantekeningen anders opgeschreven, en daar staat overal bij van wie hij het had.',
    'Geleerden ruziën daar nu al tweehonderd jaar over: welke stukken van de Rihla heeft hij zelf gezien en welke heeft hij overgeschreven uit boeken van anderen.',
    'Het antwoord is waarschijnlijk: allebei, door elkaar heen, zonder dat er iemand was die het erg vond.',
    'Het maakt het boek niet waardeloos. Het maakt het een boek uit zijn eigen tijd, en dat is iets wat je van een kind van twaalf mag vragen te begrijpen.',
  ] },
  { nummer: 15, titel: 'De berg van Adam', tekst: [
    'Na de Malediven zijn ze naar het eiland Serendib gegaan, dat wij Sri Lanka noemen, en daar hebben ze een berg beklommen.',
    'Op de top van die berg zit een afdruk in de steen die op een voetafdruk lijkt. Hij is groot, groter dan een mens.',
    'Alle geloven die op dat eiland wonen zeggen dat hij van iemand anders is.',
    'Moslims zeggen: van Adam, die daar op aarde kwam. Boeddhisten zeggen: van Boeddha. Hindoes zeggen: van Shiva. De christenen op het eiland zeiden: van Thomas.',
    'En ze klommen allemaal naar boven.',
    'Musa was zesentwintig en hij was nooit eerder een berg op geweest.',
    'Er waren twee wegen. De makkelijke, waar je drie dagen over deed, en de steile, waar kettingen in de rots waren geslagen om je aan vast te houden.',
    'Ze namen de steile. Dat was niet Musa’s keuze.',
    'Hij schrijft over de laatste dag: dat het koud was op een manier die hij niet kende, dat hij zijn handen niet meer voelde, en dat er oude mensen omhoogklommen die het beter volhielden dan hij.',
    'Op de top was het mistig en zag je niets.',
    'Ze hebben er een half uur gestaan met een groep die uit vier geloven bestond, in de mist, om een afdruk waar niemand het over eens was.',
    'Musa schrijft: *Niemand maakte ruzie. Het was te koud.*',
    'Hij heeft dat als grap bedoeld en het is de beste zin uit zijn hele reis.',
    'Die berg heet nu Adam’s Peak, of Sri Pada, afhankelijk van wie je het vraagt, en er klimmen nog steeds elk jaar honderdduizenden mensen naar boven, uit vier geloven, langs dezelfde kettingen.',
  ] },
  { nummer: 16, titel: 'Damascus, 1348', tekst: [
    'Op de weg terug liepen ze de pest in, en dat is het enige hoofdstuk van dit deel dat Musa nooit aan iemand heeft voorgelezen.',
    'Ze kwamen in de zomer van 1348 in Damascus aan.',
    'De stad was stil op een manier die je meteen hoort. Geen markt. Geen kinderen op straat.',
    'Er stierven daar toen ruim tweeduizend mensen per dag.',
    'Musa was vierendertig en hij had in dertig jaar oorlog gezien en schipbreuk en een sultan die mensen liet doden voor een woord, en hij schrijft dat niets daarvan hierop leek.',
    'Wat hij opschreef ging over twee dingen.',
    'Het eerste was hoe snel het ging. Een man aan wie je ’s ochtends brood vroeg, was ’s avonds dood. Niet ziek. Dood.',
    'Het tweede was wat de stad deed.',
    'Ze gingen twee dagen vasten, allemaal, en op de derde dag kwam iedereen bij elkaar buiten de muren. Moslims, christenen en joden, in één stoet, met de boeken van hun eigen geloof in hun handen, en ze liepen de hele ochtend en ze riepen om hetzelfde.',
    'Musa heeft dat gezien en hij heeft het opgeschreven en hij heeft er nooit iets aan toegevoegd.',
    'Er staat geen uitleg bij. Er staat niet of hij het mooi vond of wanhopig.',
    'Er staat: *Ze liepen samen, en niemand vroeg wie de ander was.*',
    'De pest hield er niet van op. Dat is de wrede helft van dit verhaal, en die hoort erbij: ze liepen, en het ging door, en een derde van de mensen in die stad heeft dat jaar niet gehaald.',
    'Ibn Battuta heeft het ook opgeschreven. Het staat in de Rihla, en het is een van de weinige ooggetuigenverslagen van de Zwarte Dood in het Midden-Oosten die we hebben.',
    'Ze zijn doorgereisd naar het westen. Onderweg hoorden ze in elke stad hetzelfde.',
    'En in Tanger, toen ze er eindelijk aankwamen, hoorde Ibn Battuta dat zijn moeder een paar maanden eerder was gestorven.',
    'Aan de pest.',
    'Musa schrijft er vier woorden over, en die zijn het hele hoofdstuk waard: *Hij zei niets. Ik ook.*',
  ] },
  { nummer: 17, titel: 'De vuurtoren', tekst: [
    'Onderweg naar huis kwamen ze nog één keer door Alexandrië, en dat is het hoofdstuk waaraan Musa het vaakst heeft teruggedacht.',
    'Vierentwintig jaar eerder waren ze daar geweest, hij dertien en zijn meester eenentwintig, en hadden ze in de haven gestaan en naar de vuurtoren gekeken die er half nog stond.',
    'Ibn Battuta was er toen tegenaan geklommen. Hij vertelde er graag over: dat je door een deur naar binnen kon en dat er kamers waren.',
    'Nu stond er een hoop steen.',
    'Er was in de tussentijd een aardbeving geweest. De rest was omgevallen, en waar de toren had gestaan lag puin waar mensen doorheen liepen alsof het er altijd had gelegen.',
    'Ze hebben er samen naar staan kijken. Musa was zevenendertig en zijn meester vijfenveertig.',
    '“Ik ben erin geweest,” zei Ibn Battuta.',
    '“Ik weet het.”',
    '“Er waren kamers.”',
    '“Dat heb je verteld.”',
    'Ze stonden er nog een tijdje.',
    'Toen zei Ibn Battuta iets wat Musa diezelfde avond heeft opgeschreven omdat hij bang was het te vergeten, en het is de reden dat er van die hele reis een boek is gekomen:',
    '“Er is nu niemand meer die weet hoe het van binnen was, behalve ik.”',
    'Musa heeft het later zo begrepen: dat een man van vijfenveertig daar in het puin doorkreeg dat wat hij had gezien met hem mee zou gaan als hij het niet zou opschrijven.',
    'Twee jaar later gaf de sultan van Fes hem die opdracht, en hij heeft hem aangenomen.',
    'Van de vuurtoren van Alexandrië is niets over. Hij heeft vijftienhonderd jaar gestaan en hij was een van de zeven wonderen van de oude wereld, en het enige wat er nog van bestaat zijn beschrijvingen van mensen die erin zijn geweest.',
    'Eén daarvan is van hem.',
  ] },
  { nummer: 18, titel: 'Wat een reis met je doet', tekst: [
    'Er is nog iets wat in het boek niet staat, en dit hoofdstuk is het enige in dit deel dat helemaal over Musa gaat.',
    'Hij was dertien toen hij vertrok en vierendertig toen hij terugkwam, en dat betekent dat hij geen jeugd heeft gehad en ook geen thuis.',
    'Dat klinkt zieliger dan hij het vond. Hij heeft het nooit als verlies opgeschreven. Maar er staat in zijn aantekeningen wel een lijstje, ergens in een marge, in het jaar dat hij eenendertig werd, en dat lijstje is dit:',
    '*Wat ik niet heb: een vrouw. Kinderen. Een straat waar ze mijn naam kennen. Een vak. Een graf waar ik bij hoor.*',
    '*Wat ik wel heb: alles.*',
    'Hij is drie keer bijna gebleven.',
    'Eén keer in Dihli, bij een meisje van wie hij de naam niet heeft opgeschreven — wat hij bij niemand anders deed, en wat dus iets betekent.',
    'Eén keer op de Malediven, om geen reden die hij kon uitleggen behalve dat het er stil was.',
    'En één keer in Damascus, in het jaar vóór de pest, toen hem werk werd aangeboden bij een geleerde die zijn handschrift had gezien.',
    'Hij is alle drie de keren doorgereisd.',
    'De laatste keer heeft hij opgeschreven waarom, en het is geen mooi antwoord, en het staat er daarom:',
    '*Omdat ik niet weet wie ik ben als ik stilsta.*',
    'Hij is dat op zijn vierendertigste te weten gekomen, in een huis in Fes waar hij verder niets bijzonders heeft meegemaakt, en het viel hem mee.',
  ] },
  { nummer: 19, titel: 'Terug', tekst: [
    'Hij kwam eerder thuis dan zijn meester.',
    'In 1349 stond Musa in Tanger, vierendertig jaar oud, met een baard en met handen die niet meer op schrijvershanden leken.',
    'Zijn moeder leefde niet meer. Dat had hij geweten — er was een brief geweest, jaren eerder, die er zeven maanden over had gedaan.',
    'Zijn zus kende hem niet meteen.',
    'Hij is drie dagen in het huis gebleven en toen weer weggegaan naar Fes, want daar was werk voor iemand die kon schrijven, en omdat hij niet wist hoe hij in Tanger moest zitten.',
    'Ibn Battuta kwam later terug. Hij maakte nog één reis, naar het zuiden, naar het rijk van Mali en de stad Timboektoe, en pas daarna was hij klaar.',
    'De sultan van Fes gaf hem opdracht zijn verhaal op te schrijven, en zette er een schrijver bij: Ibn Juzayy, een geleerde uit Granada.',
    'Musa heeft hem zijn aantekeningen gegeven.',
    'Alles. Vier kisten.',
    'In het boek dat eruit kwam — de Rihla, wat gewoon "reis" betekent — staat zijn naam nergens.',
  ] },
  { nummer: 20, titel: 'Het dicteren', tekst: [
    'In 1355 zat Musa vijf maanden lang in een kamer in Fes en keek hij toe hoe zijn reis een boek werd.',
    'De sultan had het bevolen. Er was een schrijver aangewezen: Ibn Juzayy, een geleerde uit Granada, veertig jaar oud, met een handschrift waar Musa jaloers op was.',
    'Ibn Battuta praatte. Ibn Juzayy schreef.',
    'Musa zat erbij met zijn vier kisten en gaf aan wat er gevraagd werd.',
    'Het was de vreemdste ervaring van zijn leven, en hij heeft er lang over gedaan om uit te leggen waarom.',
    'Dit is wat er gebeurde.',
    'Ibn Battuta vertelde een dag die Musa had meegemaakt. Musa herinnerde zich hem anders. Hij zocht het op in zijn aantekeningen, en daar stond een derde versie.',
    'Dat was niet één keer. Dat was voortdurend.',
    'En het ging niet over grote dingen. Het ging over: was het in de ochtend of in de middag, waren het drie mannen of vijf, heette hij Ali of Umar.',
    'De eerste keren zei Musa er iets van.',
    'De vierde keer zei Ibn Juzayy, zonder op te kijken: “Laat maar.”',
    'En Musa liet het.',
    'Hij schrijft daarover, in de vijfde kist, de enige regel waarin hij boos klinkt:',
    '*Ze maken er iets van dat mooier loopt. Ik heb er dertig jaar naast gezeten en ik kan er niets aan doen.*',
    'Maar hij schrijft er ook, twintig regels verder, iets anders:',
    '*En toch klopt het. Niet op de dag en niet op de naam. Op wat het was.*',
    'Dat is het oordeel van de enige ooggetuige die we hebben, en het is eerlijker dan alles wat geleerden er sindsdien over hebben gezegd.',
    'Het boek werd afgemaakt en Ibn Battuta is daarna rechter geworden in een stad in Marokko en op een dag gestorven, en niemand weet precies wanneer of waar hij ligt.',
    'Een man die honderdtwintigduizend kilometer heeft gereisd, en we weten niet waar zijn graf is.',
  ] },
  { nummer: 21, titel: 'De vijfde kist', tekst: [
    'Hij heeft er niet om gevraagd. Dat is het antwoord op de vraag die iedereen stelt.',
    'Het was niet zijn reis. Hij was het hulpje dat meeging, en wat hij opschreef schreef hij op in opdracht, en zo dacht men daar toen over.',
    'Wat hij wel deed, was één ding voor zichzelf houden.',
    'De vijfde kist.',
    'Daar zat niet het reisverslag in, maar wat hij ernaast had geschreven: de dingen die er voor een boek niet toe deden. Dat Ibn Battuta in Tunis om zijn moeder huilde. Wat een man in Alexandrië precies zei. Hoe de lucht ruikt in de Malediven voor een storm. De naam van een hond in een dorp in Anatolië.',
    'En helemaal onderin, in een lap linnen, iets van brons met acht punten aan de kop, dat hij in een markt in Damascus had gekocht van een handelaar die zei dat het uit het westen kwam.',
    'Musa heeft die kist nooit aan iemand laten zien.',
    'Zijn dochter heeft hem geopend na zijn dood, en zijn kleinzoon heeft er een kaars bij aangestoken en zes bladzijden gelezen en toen is hij gaan huilen, en dat is hoe het verder is gegaan.',
    'Van de Rihla bestaan tientallen handschriften. Het is in tientallen talen vertaald. Er wordt nog steeds over geruzied door geleerden, omdat sommige stukken verdacht veel lijken op reisverslagen van anderen.',
    'Van de vijfde kist is nooit iets teruggevonden.',
    'Alleen de sleutel.',
  ] },
]
