import type { Hoofdstuk } from './sleutels'

/** Deel 8 — Drie koningen, één dag. Ksar el-Kebir, 4 augustus 1578. */
export const DEEL8_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'De trom', tekst: [
    'Driss was veertien en hij sloeg de trom, en dat betekent iets anders dan je denkt.',
    'Hij vocht niet. Hij had geen zwaard en hij zou er ook niet mee overweg kunnen. Zijn werk was: het leger laten weten wat het moest doen, met geluid, omdat een stem niet ver genoeg draagt en een vlag niet werkt als er stof hangt.',
    'Drie slagen kort: vooruit. Twee lang: stop. Een roffel: terug.',
    'Hij had het van zijn vader geleerd, die het van zijn vader had geleerd, en hij was er goed in.',
    'In juli van dat jaar lag het leger bij de rivier de Loukkos, en iedereen wist dat er iets ging gebeuren, want er kwam een vloot aan de kust die er niet hoorde.',
    'De Portugese koning was er zelf bij. Dat was het gekke.',
    'Koningen stuurden legers. Deze kwam mee.',
  ] },
  { nummer: 2, titel: 'Wat een trom doet', tekst: [
    'Een trom is geen muziek in een leger. Een trom is spraak.',
    'Driss heeft dat aan zijn eigen zoon uitgelegd met een lepel op een tafel, jaren later, en het ging zo.',
    'Dertigduizend mannen staan op een vlakte. De voorste rij ziet niet wat de achterste rij doet. Er hangt stof tot borsthoogte. Er wordt geschreeuwd.',
    'Iemand moet ze allemaal tegelijk iets kunnen zeggen.',
    'Een vlag valt weg in het stof. Een hoorn draagt ver maar kan weinig zeggen. Een trom draagt ver én kan veel zeggen, want een trom heeft ritme en ritme heeft woorden.',
    'Driss kende er zevenentwintig.',
    'Drie kort: vooruit. Twee lang: sta. Een roffel die aanzwelt: terug. Twee kort en één lang: de ruiters naar rechts. Een dubbele tik die vier keer komt: de bevelhebber wil je zien.',
    'Hij had er twee jaar over gedaan om ze te leren en hij kon ze in zijn slaap.',
    'Wat er verder nog bij kwam kijken en wat niemand hem had uitgelegd:',
    'Je moet ze op het goede moment slaan. Niet als je ze hoort, maar als je ze krijgt. Een trommelaar die uit zichzelf slaat omdat hij denkt dat het moet, laat vijfduizend man de verkeerde kant op lopen.',
    'En je moet door blijven slaan.',
    'Dat is het eigenlijke werk. Niet het onthouden, niet het ritme. Doorgaan terwijl er van alles om je heen gebeurt waar je naar wilt kijken.',
    'Zijn vader had het zo gezegd: “Jij bent de stem. Als de stem stopt, weet niemand meer wat hij moet.”',
    'Driss was veertien en hij nam dat serieuzer dan wat ook.',
  ] },
  { nummer: 3, titel: 'Drie', tekst: [
    'Driss heeft het pas later helemaal begrepen, en dit is hoe het zat.',
    'Er waren twee mannen die allebei sultan van Marokko wilden zijn. De een, Abd al-Malik, zat op de troon. De ander, zijn neef Mohammed, was ervan afgezet en wilde hem terug.',
    'Die neef had hulp gezocht in Portugal.',
    'En de jonge Portugese koning Sebastiaan had ja gezegd. Hij was vierentwintig, hij was vroom, hij wilde een kruistocht, en zijn raadgevers hadden hem gesmeekt het niet te doen.',
    'Dus kwamen er drie koningen naar dezelfde vlakte: de zittende sultan, de afgezette sultan, en de koning van Portugal.',
    'Wat niemand wist, was dat Abd al-Malik stervende was.',
    'Hij was al weken ziek. Hij kon niet meer op een paard zitten. Ze droegen hem rond in een draagstoel en hij gaf zijn bevelen vanachter een gordijn, en zijn broer Ahmad stond ernaast.',
    'Dat hoorde Driss van een ruiter die het van een schrijver had.',
    'In een leger van dertigduizend man reist zo’n gerucht in een middag van voor naar achter.',
  ] },
  { nummer: 4, titel: 'De weken bij de rivier', tekst: [
    'Ze lagen drie weken bij de Loukkos en het was augustus, en dat is alles wat iemand die daar is geweest hoeft te horen.',
    'De hitte in die vlakte in augustus is niet de hitte van een warme dag. Het is een ding dat op je ligt.',
    'Er werd ’s middags niet gewerkt. Dat kon niet. Van elf tot vier lag het hele leger stil onder wat er aan schaduw was, en pas daarna kwam het weer op gang.',
    'Driss schrijft niets — hij kon niet schrijven — maar hij heeft het genoeg verteld, en dit is wat er van die weken is blijven hangen.',
    'De vliegen. Dertigduizend man en hun dieren op één plek, drie weken lang, en je kunt wel raden wat daar het gevolg van is.',
    'Het water. Ze zaten aan een rivier en toch was er ruzie om water, want wat er bovenstrooms in gaat komt benedenstrooms weer langs.',
    'De verhalen. Elke avond een ander verhaal over wat de Portugezen van plan waren, en het waren er zoveel dat je ze na een week niet meer geloofde en ook niet meer kon negeren.',
    'En het wachten.',
    'Dat is wat Driss het meest heeft bijgestaan. Dat een leger vooral zit.',
    'Hij heeft in die weken leren dobbelen, en hij heeft zijn tweede trom leren repareren, en hij heeft een man uit de Rif Tamazight horen spreken en er tien woorden van geleerd omdat er niets anders te doen was.',
    'Op de laatste avond zei een oude soldaat tegen hem: “Onthoud dit nog even.”',
    '“Wat?”',
    '“Dat je je verveelt,” zei de man. “Over drie dagen zou je er veel voor geven.”',
  ] },
  { nummer: 5, titel: 'De jongen die ze meebrachten', tekst: [
    'Acht dagen voor de slag brachten de verkenners iemand mee.',
    'Het was geen soldaat. Het was een jongen die water had gehaald bij een beek, twee uur rijden naar het westen, waar het Portugese leger lag.',
    'Hij was misschien vijftien.',
    'Ze zetten hem bij de karren, met zijn handen los, want er was niemand bang dat hij ergens heen zou gaan.',
    'Driss bracht hem eten omdat niemand anders het deed.',
    'Ze konden niet praten. De jongen sprak Portugees, Driss Arabisch en een beetje Tamazight, en daar zit niets tussen.',
    'Dus deden ze wat mensen dan doen. Ze wezen.',
    'De jongen wees naar de trom en maakte een gebaar: mag ik.',
    'Driss gaf hem de trom.',
    'Dat had hij niet mogen doen en hij heeft het gedaan.',
    'De jongen sloeg er een paar keer op, verkeerd, en lachte, en gaf hem terug.',
    'Toen wees hij naar zichzelf en zei een woord dat zijn naam moet zijn geweest, en Driss heeft het nooit goed kunnen onthouden. Het begon met een J.',
    'Hij wees naar Driss. Driss zei zijn naam.',
    'Daarna zaten ze een tijdje naast elkaar zonder iets te doen.',
    'De volgende ochtend was de jongen er niet meer. Hij was geruild tegen twee van hun eigen mensen; dat gebeurde de hele tijd, over en weer.',
    'Driss heeft hem nooit teruggezien en heeft er acht dagen later op het veld naar lopen kijken, wat hij aan niemand heeft verteld.',
    'Dit hoofdstuk staat hier omdat het het enige is wat Driss zijn hele leven over die oorlog met zoveel woorden heeft gezegd:',
    'Dat hij aan de overkant één iemand kende, en dat dat genoeg was om de rest nooit meer te kunnen zien zoals hij ze daarvoor zag.',
  ] },
  { nummer: 6, titel: 'De koning die niet had moeten komen', tekst: [
    'Over de Portugese koning werd in het kamp meer gepraat dan over de eigen sultan, en dat kwam doordat niemand hem begreep.',
    'Hij heette Sebastiaan. Hij was vierentwintig.',
    'Hij was koning geworden toen hij drie was, want zijn vader was gestorven voordat hij geboren werd. Hij was opgevoed door priesters en door zijn grootmoeder, hij was vroom op de manier waarop iemand vroom is die nooit is tegengesproken, en hij wilde een kruistocht.',
    'Zijn eigen raadgevers hadden hem gesmeekt het niet te doen. Zijn oom, die kardinaal was, had het hem afgeraden. De koning van Spanje, zijn eigen familie, had geweigerd mee te doen.',
    'Hij ging toch.',
    'En hij had geen kind.',
    'Dat is het punt waar dit hele verhaal op draait en het werd in het kamp bij de rivier al gezegd, door mannen die niet konden lezen.',
    '“Als die doodgaat, wie wordt het dan?”',
    '“Zijn oom. Die is oud.”',
    '“En daarna?”',
    'Dan haalde iedereen zijn schouders op, want daarna was Spanje, en dat wist een dobbelende soldaat aan de Loukkos net zo goed als de vorsten in Europa.',
    'Er is over die veldslag later geschreven dat het een botsing van geloven was, en dat is de makkelijke versie.',
    'Wat het ook was: een jonge man die niets te verliezen dacht te hebben, met een land achter zich dat alles te verliezen had.',
    'Driss heeft hem één keer gezien, van heel ver, op de ochtend zelf. Een ruiter in het wit, voorop.',
    'Meer niet.',
  ] },
  { nummer: 7, titel: 'De nacht ervoor', tekst: [
    'Op de avond van drie augustus werd het kamp vroeg stil, en dat was het vreemdste van alles.',
    'Er werd niet gedobbeld. Er werd niet geruzied. Mannen die drie weken lang de hele avond hadden zitten praten, zeiden niets.',
    'Er liepen schrijvers rond.',
    'Dat was Driss nooit eerder opgevallen. Er zijn in elk leger een paar mannen die kunnen schrijven, en op zo’n avond hebben die het druk, want iedereen wil ineens iets aan iemand laten weten.',
    'Er stond een rij.',
    'Aziz stond erin. Driss zag hem staan en ging er niet bij, want hij wist niet wat hij zou moeten laten opschrijven en aan wie.',
    'Zijn vader was dood. Zijn moeder kon het niet laten voorlezen zonder de hele straat erbij, en dan zou ze schrikken.',
    'Hij is gaan slapen en hij heeft niet geslapen.',
    'Ergens in die nacht kwam Aziz naast hem zitten.',
    '“Ik heb iets laten schrijven,” zei hij.',
    '“Aan je zus?”',
    '“Ja.”',
    'Stilte.',
    '“Wat staat erin?”',
    'Aziz dacht na.',
    '“Dat ze het huis moet verkopen als ik niet terugkom,” zei hij. “En dat ze niet moet wachten.”',
    'Driss heeft daar niets op gezegd, want hij was veertien en er is op zo’n zin niets te zeggen.',
    'Ze hebben er tot het licht werd naast elkaar gezeten.',
    'Dat is een vorm van vriendschap waar geen woord voor is en die alleen op zulke nachten bestaat.',
  ] },
  { nummer: 8, titel: 'De ochtend', tekst: [
    'De vierde augustus begon met bidden, zoals elke dag begon.',
    'Wat anders was, was de stilte daarna. Geen gepraat, geen ruzie bij het water. Mannen die hun spullen drie keer nakeken.',
    'Driss zat op een kar met de trom tussen zijn knieën en zijn handen waren nat.',
    'Naast hem zat Aziz, die de tweede trom sloeg en die zeventien was en die de hele ochtend niets zei.',
    '“Aziz.”',
    '“Wat.”',
    '“Ben jij bang?”',
    'Aziz keek naar de vlakte.',
    '“Ik denk aan mijn zus,” zei hij.',
    'Dat was zijn antwoord en Driss heeft het nooit meer gevraagd.',
    'Om acht uur kwamen de Portugezen in beweging. Je zag het eerst aan het stof.',
  ] },
  { nummer: 9, titel: 'Wat hij ervan zag', tekst: [
    'Wat Driss ervan gezien heeft, is dit, en het is minder dan je zou willen.',
    'Hij zag stof.',
    'Hij zag de ruiters van de eigen kant naar links en naar rechts wegdraaien, in een beweging die geoefend was, en hij sloeg wat hij moest slaan toen het bevel kwam.',
    'Hij zag de Portugese linie doorstoten in het midden en ver komen, verder dan de bedoeling was, en toen zag hij hem niet meer omdat er stof overheen ging.',
    'Hij hoorde het.',
    'Daar gaat hij verder niets over zeggen. Er zijn boeken waarin staat hoe een veldslag klinkt, geschreven door mannen die het hebben meegemaakt, en die boeken zijn er en dit is er geen.',
    'Wat er gebeurde: de Portugese aanval liep vast, de flanken sloten zich, en tegen de middag was het leger dat ’s ochtends was aangetreden er niet meer.',
    'Er zijn die dag duizenden mensen gestorven. De meesten waren geen koning.',
  ] },
  { nummer: 10, titel: 'Drie doden', tekst: [
    'Abd al-Malik stierf in zijn draagstoel, halverwege de slag, aan de ziekte die hem al weken had.',
    'Zijn adviseurs hielden het geheim. Ze lieten het gordijn dicht en gaven de bevelen door alsof hij ze nog gaf, de hele middag, tot het afgelopen was.',
    'Mohammed, de afgezette sultan, verdronk in de rivier op de vlucht.',
    'Koning Sebastiaan van Portugal is die dag gesneuveld. Zijn lichaam is teruggevonden en er is decennialang in Portugal beweerd dat hij nog leefde en terug zou komen, omdat mensen dat nu eenmaal doen met koningen die verdwijnen.',
    'Drie koningen, één dag.',
    'Ahmad, de broer van Abd al-Malik, werd diezelfde avond tot sultan uitgeroepen op het slagveld. Hij kreeg later de naam al-Mansur: de overwinnaar.',
    'En Portugal, dat zijn koning en zijn leger had verloren en geen troonopvolger had, werd twee jaar later ingelijfd door Spanje en was zestig jaar lang geen eigen land meer.',
    'Dat is wat er die dag is gebeurd, en Driss heeft er niets van gezien behalve stof.',
  ] },
  { nummer: 11, titel: 'Aziz', tekst: [
    'Aziz is die dag doodgegaan en dit hoofdstuk is kort, want Driss heeft er kort over gedaan.',
    'Hij is niet gesneuveld in een gevecht. Hij zat op dezelfde kar, twintig passen verderop, en er kwam iets aan waar niemand iets aan kon doen.',
    'Driss heeft doorgeslagen.',
    'Dat is de zin die er staat en die je twee keer moet lezen.',
    'Hij heeft de rest van die middag de trom geslagen met Aziz twintig passen verderop, omdat hij de stem was, en omdat er dertigduizend mensen waren die moesten weten wat ze deden.',
    'Hij was veertien.',
    'Het is hem later verweten, niet door anderen maar door hemzelf, en hij is er tot in zijn ouderdom mee bezig geweest.',
    'Een oude man in Marrakech, een veteraan van dezelfde dag, heeft hem daar ooit dit op geantwoord, en Driss heeft het doorverteld omdat het hem hielp:',
    '“Wat had je moeten doen? Ophouden?”',
    '“Ik had naar hem toe kunnen gaan.”',
    '“En dan?”',
    'Daar had Driss geen antwoord op, want er was geen antwoord.',
    'De brief aan zijn zus is aangekomen. Dat weten we omdat Driss hem zelf is gaan brengen, twee maanden later, te voet, vanuit Ksar el-Kebir naar een dorp bij Chefchaouen.',
    'Hij heeft haar niets verteld over hoe het ging. Hij heeft de brief gegeven en gezegd dat Aziz goed was geweest.',
    'Ze heeft het huis niet verkocht.',
  ] },
  { nummer: 12, titel: 'De losgelden', tekst: [
    'Wat er na de slag gebeurde, is het deel waar in de boeken het minst over staat en waar het meeste geld in omging.',
    'Er waren duizenden gevangenen.',
    'Geen soldaten alleen. Edelen. De halve Portugese adel was meegegaan, want een kruistocht met de koning is een eer, en die edelen waren nu allemaal in handen van de overwinnaar.',
    'En een edelman wordt niet gedood. Een edelman wordt terugverkocht.',
    'Er is maandenlang onderhandeld. Er kwamen schepen uit Lissabon met geld. Er werden families leeggehaald, landgoederen verkocht, sieraden omgesmolten — in heel Portugal, om zonen en vaders terug te krijgen.',
    'Wat er aan losgeld naar Marokko is gegaan, is nooit precies uitgerekend, maar het was genoeg om een land jarenlang van te besturen.',
    'Driss heeft in die maanden gevangenen eten gebracht, want daar was hij goed in gebleken.',
    'Hij schrijft — vertelt — dat er mannen bij waren die hem probeerden om te kopen met dingen die ze niet meer hadden. En dat er mannen bij waren die alleen maar zaten.',
    'En dat er één was die elke dag vroeg of er een jongen bij hen was die water had gehaald bij een beek.',
    'Driss heeft nooit geweten of dat dezelfde was.',
    'Van dat losgeld is later een paleis gebouwd in Marrakech dat het mooiste van zijn eeuw is genoemd, en dat is het volgende deel van dit boek.',
    'Alles wat daar van goud is, komt uit de zakken van families die hun zoon terug wilden.',
    'Dat hoort erbij als je erover leest. Een mooi gebouw is nooit alleen een mooi gebouw.',
  ] },
  { nummer: 13, titel: 'Wat je vindt als je opruimt', tekst: [
    'De dag erna moest iedereen die kon lopen het veld op om op te ruimen.',
    'Dat woord gebruikten ze. Opruimen.',
    'Driss heeft die dag dingen gezien waar hij de rest van zijn leven niet over heeft gepraat, en dat is zijn goed recht.',
    'Wat hij wel heeft verteld, aan zijn zoon, één keer, toen die veertien werd en zei dat hij soldaat wilde worden:',
    'Dat er op zo’n veld geen verschil is.',
    'Dat je niet kunt zien wie er aan welke kant lag.',
    'Dat er jongens lagen van zijn leeftijd met een trom naast zich.',
    'Zijn zoon is geen soldaat geworden.',
    'Tussen de spullen die bij elkaar werden gelegd — riemen, gespen, een schoen, dingen die niemand meer nodig had — lag iets van brons met acht punten aan de kop.',
    'Driss nam het mee. Niet uit hebzucht; er lag genoeg dat meer waard was.',
    'Hij nam het mee omdat het geen wapen was.',
    'Van alles wat op die vlakte lag, was dit het enige ding dat niet gemaakt was om iemand iets aan te doen.',
    'Drie maanden later verkocht hij het in Marrakech aan een tegelzetter, voor zes munten en een maaltijd.',
  ] },
]
