/**
 * De sleutels van Marokko in het Engels.
 *
 * Dialoog tussen dubbele aanhalingstekens, zoals in een Engels kinderboek.
 * Deel 15 speelt ook in het Engels in Utrecht: het gaat over een Nederlandse
 * derde generatie, en een verhaal dat per taal verhuist is nergens meer waar.
 */
import type { SleutelVertaling } from './sleutels-talen'

export const EN_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'The Olive Fire',
    jaar: '± 200',
    waar: 'Walili (Volubilis), at the foot of the Zerhoun',
    verteller: 'Tala, eleven, daughter of an oil-press owner who has fallen ill',
    flap: 'Tala holds the key to the storehouse and the overseer wants it. When the whole city’s oil is at risk, she has to choose between obeying and being right.',
    sleutel: 'The key is forged in Walili by Tala’s grandfather and leaves at the end with an Amazigh caravan into the hills.',
    echt: [
      'Volubilis — Walili in Arabic — was a real Roman city near Meknès, with thousands of inhabitants, bathhouses and stone streets.',
      'The city lived on olive oil. Dozens of presses have been excavated, and they worked on the same principle as the presses still used in Morocco today.',
      'The floors were covered in mosaic. Part of it is still there, in the open air.',
      'The population was largely Amazigh; Roman and Amazigh life ran through one another here.',
    ],
    verzonnen: [
      'Tala, her family and the overseer Marcus did not exist.',
      'The fire in the story is made up. There is no evidence of a great fire at Walili in this period.',
      'The key with the eight-pointed star is made up. The eight-pointed khatam is a real and very old Moroccan motif.',
    ],
    hoofdstukken: [
      { titel: 'The key', tekst: [
        'Tala woke up because of the smell.',
        'Olives. Pressed olives, warm and bitter. The whole city smelled of it in these weeks. She lay still for a moment and listened. Outside, the big press was already creaking. That meant she was late.',
        'She jumped off her bed and pulled her dress over her head.',
        '“Tala!” her mother called from below. “The door!”',
        'The door. Of course, the door.',
        'Since her father had fallen ill, Tala did his work. Every morning she walked to the storehouse behind the house and unlocked the door. The jars stood there. A hundred jars, filled to the brim with oil, ready to go to the harbour.',
        'The key hung on a cord around her neck. It was bronze and as long as her hand. Her grandfather had forged it, long before she existed. Its head had eight points, like a star.',
        '“Don’t lose it,” her father had said. He had said it quietly, because louder was no longer possible for him. “Nothing else opens that door.”',
        'Tala ran down the stairs, past the kitchen, across the courtyard. It was still early. The sun stood just above the hills and the stones were cold under her feet.',
        'There was a man at the storehouse.',
        'She stopped.',
        'He was big and he wore the red cloak of the overseer. Marcus. Everyone in Walili knew Marcus, and nobody liked him.',
        '“You’re late,” he said.',
        '“I’m on time,” said Tala.',
        'She knew she should not have said that. She said it anyway.',
        'Marcus looked at her. Then he held out his hand.',
        '“Give me that key. A child has no business guarding a hundred jars.”',
        'Tala took a step back.',
        'In her head she heard her father. *Nothing else opens that door.* And she thought of something else, something she had seen yesterday and had decided was nothing.',
        'Two jars that were not in their place.',
        '“Well?” said Marcus.',
        'Tala closed her hand around the bronze. It had grown warm from her skin.',
        '“No,” she said.',
      ] },
      { titel: 'Two jars', tekst: [
        'Marcus did not laugh. He did not get angry either. That was the worst of it.',
        'He lowered his hand, straightened his cloak and said: “As you wish.” Then he walked away, out of the alley, without looking back.',
        'Tala stood still until she could no longer hear his footsteps. Only then did she notice her hands were shaking.',
        'She opened the door.',
        'Inside it was dark and cool. The jars stood in rows of ten, with straw between them so they would not knock against each other. Ten rows of ten. Every morning she counted them. Her father had taught her that when she was six, and back then it was still a game.',
        'She started on the left and counted aloud, as always.',
        'At the back row she stopped.',
        'There were nine.',
        'Tala counted again. Nine. She walked around the row, crouched, looked behind the straw. Nine.',
        'Yesterday she had seen something odd too. Two jars standing the wrong way, handles towards the wall instead of towards the path. She had thought: someone did that in a hurry. She had set them straight and thought no more about it.',
        'Now there was one fewer.',
        'She sat down in the doorway with her back against the post and her knees pulled up, and tried to work out what to do.',
        'She could tell her mother. But her mother already had enough this month: a sick husband upstairs, a house full of people who had to be paid, and a harvest that had to go to the harbour in three weeks.',
        'She could tell Marcus. Marcus was the overseer. That was his job.',
        'Tala looked at the alley where he had disappeared.',
        'No.',
        '“You’re in the way,” said a voice.',
        'She started. In front of her stood a boy about her own age, in a leather apron, his arms full of bundles of kindling. His hands were black.',
        '“I’m not in the way,” said Tala. “This is my door.”',
        '“Then you’re in the way of your own door.”',
        'His name was Yidir and he worked at the smithy at the end of the street. Tala knew him by sight the way you know everyone in Walili by sight, and no further.',
        'She got up to let him past. He did not go past.',
        '“You count every morning,” he said.',
        '“How do you know that?”',
        '“I walk past every morning.”',
        'Tala hesitated. Then she said it anyway, because it had to come out and because he happened to be standing there.',
        '“One is gone.”',
        'Yidir put his bundles down on the ground.',
        '“One?” he said. “Then you’ve been lucky. We’re missing six iron bars.”',
      ] },
      { titel: 'How oil is made', tekst: [
        'That afternoon Tala stood at the press, as she did every day during the harvest.',
        'The press was a hollowed-out stone as big as a cart, with a round stone inside it that a donkey dragged round and round. The olives went in, were crushed, and what came out was a thick brown mass that looked like nothing at all.',
        'That was the part that always disappointed strangers. “*That* is oil?” they would ask. No. That was the beginning.',
        'The mass went into round mats of woven reed. The mats were stacked on top of each other under the beam press, and then two men turned the screw, slowly, as if they had all the time in the world. Under the stack ran a channel.',
        'That was where it came out.',
        'First water, cloudy and dirty. Then, after a while, something else. Something that floated on the water and was greener than anything Tala knew.',
        'The first time, her father had taken her by the neck and held her head over it. “Smell,” he had said. “That’s it. If it smells like *that*, it’s good. If it smells of nothing, you waited too long.”',
        'She had lied then and said she could smell it. Now she really could.',
        'Walili lived on this. Not on the mosaic floors that visitors walked across, not on the columns on the square, not on the stone streets. On this. On pressed olives that went into jars, onto carts to the coast, and onto ships to places whose names were all Tala knew of them.',
        'She watched the channel and the mats and the donkey, and all the while she was thinking about ninety-nine jars.',
        'Six iron bars, Yidir had said. From the smithy.',
        'Iron was expensive. Oil was expensive. And both left the city in the same direction: along the road to the harbour.',
        '“Tala.” One of the men pointed at the channel. “It’s overflowing.”',
        'She shot forward and pushed the bowl underneath, too late. A stream of oil ran over the stone and disappeared between the joints.',
        'A finger thick, maybe two. Enough for a family for a week.',
        'The man said nothing about it. That made it worse.',
      ] },
      { titel: 'What an overseer may do', tekst: [
        'Marcus came back on the third day, and he did not come alone.',
        'Tala saw him walk into the courtyard with two men behind him. Her mother came out, wiped her hands on her dress, and stood exactly between him and the door.',
        '“Peace,” said Marcus.',
        '“Peace,” said her mother, in the voice you use when you don’t mean it.',
        '“Your husband is ill.”',
        '“My husband is resting.”',
        '“Three weeks,” said Marcus. “In three weeks the harvest goes to the harbour, and the city is counting on what stands in this house. I need to know it’s there.”',
        '“It’s there.”',
        '“I want to see it.”',
        'There was a silence. Tala stood in the kitchen doorway and did not dare move.',
        'Her mother said: “You may look. My daughter will open it.”',
        'Tala walked across the courtyard under the eyes of five people. She lifted the cord over her head, put the key in the lock and pushed the door open.',
        'Marcus went in. He walked along the rows, slowly, hands behind his back. At the back row he stopped.',
        'Tala held her breath.',
        '“Ninety-nine,” said Marcus.',
        'He turned around and looked at her mother.',
        '“There should be a hundred.”',
        'Her mother went stiff. Tala could see it in her shoulders.',
        '“Then one has broken,” she said.',
        '“Then there would be shards.” Marcus spread his hands. “I see no shards. I see straw that has been pulled straight.”',
        'He waited a moment, exactly long enough.',
        '“I am not saying you are stealing,” he said then. “I am saying that an eleven-year-old child holds the key to a hundred jars, and that today there are ninety-nine. That is what I am saying. And that is what I shall say on the square as well.”',
        'He walked out of the door and past Tala as if she were a post.',
        'When he had gone, her mother sat down on the edge of the well. She said nothing for a very long time.',
        '“Mama,” said Tala. “I didn’t take—”',
        '“I know.”',
        '“I counted them on Monday and then there were still—”',
        '“Tala.” Her mother looked up. Her eyes were red. “I know. And it doesn’t help us.”',
      ] },
      { titel: 'The smithy', tekst: [
        'Yidir sat on an upturned bucket in front of the smithy, filing a hinge.',
        '“You were right,” said Tala.',
        '“People rarely say that to me,” said Yidir without looking up. “About what?”',
        '“About it not being one jar.”',
        'Now he did look up.',
        'Tala sat down beside him on the doorstep and told him. About Marcus, about ninety-nine, about what he was going to say on the square. Yidir listened the way he did everything: as if he were thinking about something else at the same time, but he missed nothing.',
        '“And your iron?” she asked.',
        '“Six bars. My master thinks he miscounted.” Yidir shrugged. “My master never miscounts.”',
        '“When?”',
        '“Last week. And three the week before.”',
        'Tala pulled up her knees.',
        '“What leaves the city?” she asked. “Every day, I mean.”',
        'Yidir thought about it.',
        '“Carts,” he said. “Oil, grain, hides, iron. Everything goes along the road to the north. There’s a guard post at the gate. Everything gets written down there.”',
        '“By whom?”',
        'Yidir looked at her.',
        '“By the overseer,” he said.',
        'Neither of them said anything for a while.',
        '“That proves nothing,” said Tala at last.',
        '“No.”',
        '“If I say it, they’ll say an eleven-year-old is accusing a man because he doesn’t like her.”',
        '“Yes,” said Yidir. “That’s what they’ll say.”',
        'He put the hinge down.',
        '“So you need something they can’t talk away.”',
        '“Such as?”',
        '“Such as seeing what goes through that gate at night.”',
        'Tala looked at him. He looked back, and for the first time since she had known him, he laughed.',
      ] },
      { titel: 'What goes through the gate at night', tekst: [
        'They lay on the roof of the bathhouse, flat on their stomachs, chins on their arms.',
        'The roof was warm from the day. Below them lay the street that ran to the northern gate, wide enough for two carts side by side. One lamp burned at the gate.',
        '“How much longer?” whispered Tala.',
        '“I don’t know.”',
        '“You said carts go at night.”',
        '“I said I *thought* carts go at night.”',
        'Tala sighed and laid her head on her arm.',
        'The stars that night were unbelievable. In the city you saw half of them, because of the light and the smoke, but up here there were so many it made you restless.',
        '“My grandmother says they’re a map,” said Yidir.',
        '“The stars?”',
        '“Yes. If you can read them, you can go anywhere. She says her family walked from the desert to here that way.”',
        '“Can you read them?”',
        '“No,” said Yidir. “Nobody taught me.”',
        'Then they heard it.',
        'A cart. Not two donkeys, not horses — one donkey, slow, and the sound of wood creaking under weight.',
        'Tala shifted to the edge.',
        'The cart came out of a side street. Two men walked beside it, both with cloths around their heads. On the cart lay straw, and under the straw stood something round.',
        'At the gate the cart stopped.',
        'A man with a lamp came out of the guard hut. He did not walk to the cart. He walked to the men, spoke with them briefly, and wrote something on a tablet.',
        'Then he lifted the barrier.',
        'The cart drove into the night.',
        'Tala let out her breath. She had not noticed she was holding it.',
        '“He didn’t look,” she said. “He didn’t look under the straw.”',
        '“No.”',
        '“That’s—”',
        '“That’s still nothing,” said Yidir. “That’s a man who doesn’t look carefully enough. Nobody hangs for that.”',
        'He was right, and Tala knew it.',
        'But as the cart went round the bend, something happened. The donkey shied at something in the dark, pulled sideways, and the cart went over the kerb with one wheel.',
        'Something fell off the cart.',
        'It rolled, came to rest against the wall, and stayed there.',
        'A jar.',
        'One of the men swore, came back, picked it up and set it under the straw again. The cart drove on.',
        'But Tala had seen what was on it.',
        'On the shoulder of every jar from their house, her father pressed a mark into the clay before it was fired. Eight points. A star.',
        'She grabbed Yidir’s arm so hard that he hissed.',
        '“That one is ours,” she said.',
      ] },
      { titel: 'What you say and what they hear', tekst: [
        'The next morning Tala went to the square.',
        'She had thought about it all night, or at least half the night; the other half she had slept without meaning to. She knew what she was going to say. She had practised it three times against the wall of her room.',
        'On the square, under the columns, the council was in session. That meant: five men on stone benches, a scribe beside them, and everyone with a complaint standing around.',
        'Marcus was already there.',
        'Tala waited until a man had finished about a wall and a neighbour. Then she stepped forward.',
        '“I want to say something,” she said.',
        'Five men looked up. One of them, the oldest, with a face like a dried fig, leaned forward.',
        '“Whose child are you?”',
        '“Yuba’s, the presser. From Column Street.”',
        '“He’s ill.”',
        '“Yes,” said Tala. “That’s why I’m here.”',
        'She told it. About the jar that was gone, and another the day after. About the cart in the night and the man who lifted the barrier without looking under the straw. About the jar that fell off and about the mark with the eight points.',
        'She told it exactly as she had practised it, and while she did, she heard it herself too.',
        'She heard how it sounded.',
        'A child. A roof. The dark. A mark nobody else had seen.',
        'When she had finished it was quiet for a moment. Then Marcus said, very calmly: “May I?”',
        'The oldest nodded.',
        '“The girl is right that jars are missing,” said Marcus. “I counted them myself, the day before yesterday, in their own storehouse. Ninety-nine out of a hundred. I said so at the time as well.”',
        'He spread his hands, the way he did.',
        '“Who holds the key to that door?”',
        'Nobody said anything.',
        '“She does,” said Marcus. “An eleven-year-old child. And now that one is gone, it was a cart in the night. A cart only she has seen.”',
        'The oldest of the council looked at Tala, and his look was not unkind. That was the worst part.',
        '“Child,” he said. “Go home. Look after your father.”',
        'Tala stood on the square with her hands at her sides and her ears burning, and all around her everyone started talking again about a wall and a neighbour.',
      ] },
      { titel: 'The fire', tekst: [
        'The fire started four days later, and it did not start with them.',
        'Tala woke from it. Not from light and not from shouting — from sound. A deep, soft roar, as if somewhere very close by someone were breathing out for a very long time.',
        'She was at the window before she was awake.',
        'Across the street, two houses along, Quintus’s storehouse was burning. Quintus pressed oil too. His jars stood in a room under his house, and fire was coming out of the window now, flat, and not upwards the way fire is supposed to.',
        'That is because of the oil, Tala learned later. Oil burns differently.',
        'There was already shouting. There were already people in the street with buckets and blankets, and someone was beating a stick against the bronze plate by the well, and Tala ran down the stairs without shoes.',
        'Her mother caught her by the arm in the doorway.',
        '“Not that way.”',
        '“But—”',
        '“Tala.” Her mother held her with both hands. “Our door. *Now.*”',
        'And Tala understood.',
        'If it spreads, it comes to them. A hundred jars — ninety-nine — of oil, behind a wooden door, against the same wall.',
        'She ran to the storehouse, lifted the cord over her head and put the key in the lock. Her hands were so wet that the bronze turned away from her. The third time it worked.',
        'The door opened. The coolness came to meet her, and the smell.',
        'Behind her the whole street started carrying jars.',
        'They carried them to the courtyard, to the well, to the street, anywhere there was no burning wall. The neighbours carried, people she hardly knew, people her father had never spoken to. Someone had a ladder. Someone threw blankets into the water of the well and passed them along.',
        'Tala carried until her arms would not, and then she carried some more.',
        'At the seventieth jar she saw Yidir. He came with four others from the smithy and they were dragging something that looked like a long hook.',
        'At the eighty-fifth the roof of Quintus’s storehouse fell in.',
        'At the last one the sun was almost up.',
        'By then there was no more fire. There was only smoke hanging low over the street, and two hundred people standing and looking without saying anything, and black hands, and somewhere a child crying.',
        'Tala sat on the step leaning against her mother.',
        'And that is why she was the only one who saw the man come out of the alley beside Quintus’s house, against the flow, his cloak over his arm instead of around his shoulders.',
        'The cloak was red.',
      ] },
      { titel: 'The red cloak', tekst: [
        'She told Yidir before she told anyone else.',
        'He listened without interrupting her, and when she had finished he said: “That’s still nothing.”',
        '“I saw him.”',
        '“You saw a man in a red cloak in a street full of people with soot on their faces.” Yidir kicked a stone. “I believe you. The council won’t.”',
        'Tala knew he was right and she had had enough of him always being right.',
        '“What then?” she said. “I can’t just do nothing.”',
        '“No,” said Yidir. “But you need something that doesn’t come from you.”',
        'He sat down on the edge of the well, heels against the stone.',
        '“At the gate they write everything down,” he said. “On wax. What goes out, how much, and whose. Those tablets go to the town hall every month.”',
        '“And if there’s nothing strange on them?”',
        '“Then there’s nothing strange on them,” said Yidir. “And then you know it isn’t in the books but in the dark. That’s something too.”',
        'He looked at her.',
        '“But if there *is* something on them — if it says twelve jars while thirteen went out of the gate — then that isn’t a child who saw something. Then it’s a number next to a number, and nobody talks numbers away.”',
        'Tala thought of the night on the roof. Of the man who had not looked under the straw.',
        '“Who can see those tablets?”',
        '“Not us.”',
        '“Who then?”',
        'Yidir was quiet for a moment.',
        '“My master,” he said. “He supplies the iron for the locks of the town hall. He walks in there without anyone asking why.”',
        '“Then ask him.”',
        '“He isn’t someone who gets involved with the overseer.”',
        '“Ask him,” said Tala again.',
        'Yidir looked at his black hands.',
        '“All right,” he said. “But not tonight. Tonight is market Friday and then he’s in a foul mood.”',
        'In spite of everything Tala had to laugh.',
        'It was the first time in days.',
      ] },
      { titel: 'What the wax said', tekst: [
        'The smith was called Amanar and he was the biggest man Tala had ever seen up close.',
        'He said nothing for two days. Then on the third morning he came walking into Column Street with a parcel under his arm, and he sat down on the storehouse step as if that were the natural thing to do.',
        '“You are Yuba’s daughter,” he said.',
        '“Yes.”',
        '“Your father once gave my mother oil for a whole winter without letting her pay.” Amanar looked down the street. “That was sixteen years ago. I have not forgotten it and he no longer remembers doing it.”',
        'He laid the parcel on the step.',
        'They were two tablets of wax, in a wooden frame, scratch upon scratch upon scratch.',
        '“Looking is allowed,” said Amanar. “Taking is not. In an hour they are back where they belong.”',
        'Tala sat down and read.',
        'She could read. Not fluently, but enough. Her father had insisted: “Whoever cannot read believes what somebody else says is written there.”',
        'On the wax were rows. Date, gate, what, how much, whose.',
        'She looked for her own name. She found it eleven times.',
        '*Yuba, presser, Column Street. Eight jars.*',
        '*Yuba, presser. Twelve jars.*',
        '*Yuba, presser. Nine jars.*',
        'Tala added them up. She counted twice and the second time she wrote it in the sand beside her feet.',
        'One hundred and seventeen jars. In four weeks, out of the gate, in her father’s name.',
        'She looked up.',
        '“That isn’t right,” she said.',
        '“No?” said Amanar.',
        '“We made a hundred and sixty this season. I know exactly, I counted them when they were fired. Sixty were sold in the city. A hundred stood in the storehouse.” She pointed at the sand. “A hundred and sixty. Not a hundred and seventy-seven.”',
        'Amanar said nothing.',
        '“Seventeen jars have gone out of that gate that we never made,” said Tala. “In our name.”',
        'She heard herself what that meant, as she said it.',
        'It was not only their jars that were being stolen.',
        'It was their name.',
        'When the counting was done at the town hall, and less came in than had gone out of the gate, there would be one house where the trail ended. And that house was theirs.',
        '“Amanar,” she said, and her voice went strange. “They are setting us up.”',
        'The smith stood up and brushed the dust from his knees.',
        '“Yes,” he said. “They are.”',
        'He picked up the tablets.',
        '“Come to the square tomorrow with your mother. And bring that sand — no, write it out on something that doesn’t blow away.”',
      ] },
      { titel: 'Two numbers side by side', tekst: [
        'The council was in session as always: five men, a scribe, and the murmur of people waiting for their turn.',
        'This time Tala was not alone.',
        'On her left stood her mother, in the dress she only wore when something was very bad or very good. On her right stood Amanar, and behind Amanar stood four men from the smithy who had nothing to do with it and were there anyway.',
        'Further off, against a column, stood Yidir.',
        'The oldest of the council — the one with the face like a dried fig — looked at the group and raised his eyebrows.',
        '“You again,” he said to Tala.',
        '“I have counted,” said Tala.',
        'She had written it on a piece of leather, because leather does not blow away. She read it out. What they had made. What had been sold in the city. What stood in the storehouse. And then what, according to the tablets at the gate, had left the city in her father’s name.',
        'Two numbers.',
        'When she had finished, the silence was a different kind from last time.',
        'Marcus stepped forward. He was still calm, but no longer in the same way.',
        '“A child has looked in the city tablets,” he said. “That is forbidden.”',
        '“I brought them,” said Amanar.',
        'It got quieter still.',
        'The oldest of the council turned to the scribe beside him.',
        '“Fetch them.”',
        'It took a long time. Nobody left. Someone gave Tala’s mother a stool and she did not sit on it.',
        'When the tablets came, the scribe read aloud what was on them, and another man added it up with pebbles on a board, and everyone on the square heard it.',
        'One hundred and seventeen.',
        'The oldest looked at the numbers for a long while, and then at Marcus, and then at the numbers again.',
        '“Who writes at the north gate?” he asked.',
        '“It varies,” said Marcus.',
        '“Who decides who writes?”',
        'Marcus did not answer.',
        'The oldest sighed, and it was the sigh of a man who understands something he would rather not have understood, and who knows he now has to do something about it.',
        '“Sit down,” he said to Tala. “Not you, Marcus. You stay standing.”',
      ] },
      { titel: 'What is left', tekst: [
        'It took another three weeks before anything really changed, and that was the longest lesson of that summer: that the truth does not work the way it does in a story, where you say it and everybody nods.',
        'A man came from Volubilis’s mother city to check the books. People were questioned. Twice nothing was said and once something was said that nobody expected: the guard of the north gate, a boy of nineteen, broke at the third question and told everything.',
        'Marcus disappeared before it was finished. His house stood empty for a month and was then given to someone else.',
        'Tala’s father did not get better, not entirely. In the autumn he could sit in the courtyard again and hear the press creak, and he seemed content with that. He asked about the numbers and she told him. He made her tell three times what had happened on the square, and the third time he cried, and she had never seen him do that.',
        'The harvest went to the harbour. A hundred jars. It added up.',
        'The week after, Yidir came by with his grandmother.',
        'His grandmother was small and old and she had the eyes of someone who looks much further than where she is standing. She said she was leaving: back to her family, to the pastures in the mountains, before winter came. She said it as if she were talking about a walk.',
        '“Yidir is coming,” she said. “For a while.”',
        'Tala looked at Yidir. Yidir looked at his hands.',
        '“How long is a while?” she asked.',
        '“You only know that afterwards,” said his grandmother.',
        'That evening Tala lifted the cord over her head.',
        'The key was warm, as always. Eight points in the head, a star. Her grandfather had forged it in a smithy that no longer existed.',
        'She held it in her hand and thought of what her father had said. *Nothing else opens that door.*',
        'She gave it to Yidir.',
        '“You can’t,” he said at once.',
        '“You believed me when nobody believed me.”',
        '“That isn’t worth a key.”',
        '“It’s my key,” said Tala. “I decide what it’s worth.”',
        'Yidir held it as if it were too hot.',
        '“What am I supposed to do with it?”',
        '“I don’t know,” said Tala. “Give it away, I think. To someone you believe.”',
        'They left the next morning, with three donkeys and a dog, into the hills, and Tala climbed onto the roof of the bathhouse to watch them until she could not see them any more.',
        'She did not know yet that it was a good thing the key was leaving.',
        'Because Walili would not always be there. The earthquake came much later, and the city was slowly emptied — stone by stone, until nothing was left but the columns, the olive presses and the mosaic floors that lie there to this day, in the open air, near Meknès.',
        'Everything that stood in the houses is gone.',
        'Only the key is not.',
      ] },
    ],
  },
  2: {
    titel: 'The Other Side',
    jaar: '711',
    waar: 'Tangier, and the strait to the north',
    verteller: 'Ayyur, twelve, a shepherd’s son who looks after the horses',
    flap: 'An army crosses to a land nobody knows. Ayyur is allowed to come along to care for the horses — and discovers that the man everyone follows is frightened too.',
    sleutel: 'The key hangs from a horse’s harness and stays behind on the other side, in a scribe’s bag.',
    echt: [
      'Tariq ibn Ziyad was an Amazigh commander who crossed the strait in 711 with an army to the south of present-day Spain.',
      'The rock where he landed still bears his name: Jabal Tariq, the mountain of Tariq — worn down into Gibraltar.',
      'Most of his army consisted of Amazigh soldiers from North Africa.',
      'The story that he had his ships burned was written down only centuries later and is not regarded by historians as fact.',
    ],
    verzonnen: [
      'Ayyur and his family did not exist.',
      'The conversations with Tariq are made up. Almost nothing is known about his character.',
      'That the key travelled along is made up.',
    ],
    hoofdstukken: [
      { titel: 'The boy with the horses', tekst: [
        'Ayyur was twelve and he was good at two things: horses and waiting.',
        'The second he had learned from his father, who herded sheep in the hills behind Tangier and could stay silent from sunrise to sunset without it costing him anything. The first he had learned from nobody. Horses simply liked him, and they had done since he could walk.',
        'That was why he was now standing in the camp outside the city wall and not in the hills.',
        'In the winter his father had lost thirty sheep to the cold and the rest to debt. There was no flock left to herd. There was an army, though, and an army has horses, and horses need someone to stay with them at night.',
        'They paid in food and in copper. Not much copper.',
        'Ayyur did not complain. He was allowed to sleep with the horses and by now he knew all forty-seven by name, including the names he had made up himself because nobody had told him any.',
        'In those weeks of March the camp had become fuller than he had ever seen. First a hundred men, then five hundred, then so many that counting no longer worked. They came from the south and from the east, from the mountains and from the coast. Most of them were Amazigh like him. They spoke his language, with other words for the same things, and they laughed at how he said it.',
        'There were some who spoke Arabic too. Not many. A few hundred.',
        'And everyone was waiting.',
        'What for, they did know: ships. What the ships were for was discussed the way men discuss something they are not sure of — very firmly, and differently every day.',
        '“The other side,” said one.',
        '“There is nothing on the other side,” said another. “Water and then more water.”',
        '“There is a king on the other side,” said a third. “With a gold crown so heavy he cannot carry it.”',
        'Ayyur brushed the flank of a mare he called Tafukt, which means sun, and listened to all three.',
        'He had seen the other side. Everyone in Tangier had seen the other side. On a clear day there was a strip of land on the horizon, and above it a rock that looked as if someone had set it down there.',
        'You could look at it without ever thinking about it, your whole life long.',
        'Until someone started gathering ships.',
      ] },
      { titel: 'The man who was not big', tekst: [
        'He saw Tariq for the first time on a Tuesday, at the horses, and for half a minute he did not know who was standing in front of him.',
        'The man was not big. That was the first thing.',
        'Ayyur had imagined someone like the stories: a head taller than everyone, a cloak dragging behind him, ten men around him. This man stood alone, in a dusty coat without ornament, and he was looking at Tafukt the way someone looks at a horse who knows about horses.',
        '“Who rides this one?” he asked.',
        '“Nobody,” said Ayyur. “She won’t let anyone sit on her.”',
        '“Why not?”',
        '“I don’t know. She fell once, I think. Before she came here.”',
        'The man laid his hand on the mare’s neck and left it there without stroking.',
        '“And with you?”',
        '“With me she’s calm.”',
        '“Then she isn’t afraid of people,” said the man. “She’s afraid of what people did to her.”',
        'He looked at Ayyur for the first time.',
        '“What’s your name?”',
        '“Ayyur.”',
        '“The moon.” The man nodded, as if that were a reasonable name. “Make sure she’s still standing like this in two weeks.”',
        'Then he walked away.',
        'It took until the evening before somebody told Ayyur, and when he heard it he sat down on a crate and stayed there for a while.',
        'Tariq ibn Ziyad. Amazigh, like him. From a family nobody knew. Governor of Tangier, and the man who had to get the army lying on this beach across the water.',
        'He had been standing looking at a horse.',
        '“He comes every day,” said Sa3id, the old rider with the bad leg, who had by then come to sit beside him because he always came to sit beside somebody. “Every day at the horses and every day at the ships. I don’t think he sleeps.”',
        '“He isn’t big,” said Ayyur.',
        'Sa3id laughed so hard he had to cough.',
        '“No, boy,” he said. “He isn’t.”',
      ] },
      { titel: 'Four ships for seven thousand men', tekst: [
        'The problem was simple and nobody could solve it.',
        'There were seven thousand men on that beach, plus horses, plus weapons, plus food for weeks. And there were four ships.',
        'Ayyur once heard Sa3id work out how many times those four ships would have to go back and forth, and Sa3id arrived at a number he laughed at himself, and then he went quiet.',
        '“What is it?” asked Ayyur.',
        '“Nothing.”',
        '“Sa3id.”',
        'The old man rubbed his knee, which he did when he was thinking.',
        '“If you have four ships,” he said, “the first load is the most dangerous. That one stands on the other side, alone, with nobody behind it. And if something goes wrong, the ships are two days away.”',
        'He looked at the sea.',
        '“I would not want to be in the first load.”',
        'The ships were not theirs. The whole camp knew that. They came from a man on the other side, a lord of Ceuta who was quarrelling with his own king and was helping for that reason. His name was pronounced ten different ways and nobody had ever seen him.',
        '“Why is he helping?” asked Ayyur.',
        '“Because he wants something.”',
        '“What?”',
        '“We’ll only know once we’ve given it,” said Sa3id.',
        'In those weeks Ayyur learned more about war than he had ever wanted to know, and almost none of it was about fighting. It was about water in barrels that spoiled after four days. About how much barley a horse eats in a day and how much that is for seven hundred horses. About men who got ill from waiting and quarrelled about nothing.',
        'One morning there was a fight at the well. Two men from different tribes, over a bucket.',
        'Tariq came himself. He made them both stand up, he spoke quietly with them, and he sent them off together with the same order: one bucket, two men, carrying water for the horses all day.',
        'In the evening they sat eating side by side.',
        'Sa3id saw Ayyur looking.',
        '“*That* is it,” he said. “*That* is why they go with him. Not because he can fight. They can all fight.”',
      ] },
      { titel: 'The night before', tekst: [
        'The evening before the first crossing was warm and there was no wind, and that last part was exactly the problem.',
        'Ayyur could not sleep. He lay among the horses, his head on a saddle that smelled of leather and sweat, and looked at the stars visible between the tent cloths.',
        'Beside him lay Sa3id, who was not sleeping either.',
        '“Are you afraid?” asked Ayyur.',
        '“Yes,” said Sa3id at once.',
        'Ayyur had not expected that. He had expected the old man to laugh and say something about the twenty battles he had stood in.',
        '“Anyone who says he isn’t is lying,” said Sa3id. “Or he’s stupid. Stupid men are no use in a boat.”',
        'He sat up, slowly, with his hand on his knee.',
        '“Do you know what I do when I’m afraid?”',
        '“No.”',
        '“I say the name of God and then I do the next thing that has to be done. Not the whole thing. The next thing.”',
        'Ayyur thought about that.',
        'In his village the faith was something of the last few years. His grandmother did not have it, his mother half, his father entirely — in his own way, quietly, without saying much about it. In the camp it was everywhere: men who stopped what they were doing and turned in the same direction, and then carried on as if nothing had happened.',
        'He had never really understood it. Nobody had taken the trouble to explain it to him, because nobody explains anything to the boy who sleeps with the horses.',
        '“Sa3id,” he said. “I don’t know how to do it.”',
        'The old man looked at him in the dark.',
        '“What don’t you know?”',
        '“Everything. The words. When. How you stand.”',
        'Sa3id was silent long enough to make Ayyur uncomfortable.',
        '“Tomorrow morning,” he said then, “you stand next to me. You do what I do. You don’t have to say anything you don’t know.”',
        '“Is that enough?”',
        '“For tomorrow morning it is,” said Sa3id. “The rest you learn from someone who knows more about it than I do. I’m only a rider with a broken knee.”',
        'He lay down again.',
        '“Sleep now. Tomorrow will be long.”',
      ] },
      { titel: 'The beach at sunrise', tekst: [
        'They went down to the water in the dark, and when it grew light the whole beach was full.',
        'Ayyur had never seen so many people standing still at once.',
        'They stood in rows, shoulder to shoulder, from the dunes to the waterline. Men who did not understand one another because they came from villages ten days’ travel apart, in the same direction, in the same order.',
        'He stood beside Sa3id and did what Sa3id did, and for the first three beats he felt ridiculous and after that he did not.',
        'The sea lay that morning like a lake.',
        'When it was over it stayed quiet for a moment. Then everyone started talking at once and it was a camp again.',
        'Ayyur brought eight horses to the waterline. That was his task: eight, in the first load, with Sa3id there once they were on the other side.',
        'Tafukt was one of them.',
        'Horses and boats do not go together. He knew that, and that morning he learned how badly. They had to get the animals into the boat over a plank, and the plank moved, and the boat moved differently from the plank.',
        'Two horses refused. A third panicked halfway and knocked a man to the ground.',
        'Tafukt walked up the plank behind Ayyur as if it were a path in the hills.',
        'He held her head once she was inside, and he talked to her in his own language about things that were about nothing: about his father, about the flock that was gone, about the name he had given her and why.',
        'Someone slapped him on the shoulder.',
        'He looked up.',
        'Tariq was standing in the boat, among the horses, his hand on the gunwale.',
        '“Keep talking to her,” he said. “The whole crossing. Don’t stop.”',
        '“Yes,” said Ayyur.',
        'Tariq looked at the plank, where the fourth and fifth still had to come.',
        '“And Ayyur,” he said, without looking round. “If it goes wrong on the water, cut her loose. Don’t hold on. A horse can swim. A boy with a rope round his arm can’t.”',
      ] },
      { titel: 'Water', tekst: [
        'At its narrowest the strait is fourteen kilometres.',
        'Ayyur did not know that. He only knew that the beach behind him grew smaller and that an hour went by in which nothing happened, and then another.',
        'It did not go wrong. That was the strange thing.',
        'He had imagined everything: waves, shouting, water over the side. Instead there was the sun, the sound of oars, and a swell exactly big enough to leave everyone who was not used to boats hanging over the rail.',
        'He talked to Tafukt until his voice went hoarse.',
        'In between he looked back.',
        'Behind them lay the coast where he was born: the hills where the sheep had walked, the city with the wall, the spot where his father was probably sitting now, looking, saying nothing.',
        'He had not said goodbye. Not really. He had said he would be back in a month, and his father had nodded, and both of them had pretended that was a sentence that meant something.',
        'Ahead of him the rock grew larger.',
        'It was different from how it looked from Tangier. From far away it seemed a triangle. From close up it was a wall of stone rising straight out of the water, grey and bare, with gulls drifting round it like dust.',
        'There was nobody on it. There was nothing on it. It was just a rock.',
        'Beside him Sa3id said something.',
        '“What?”',
        '“I said: look properly.” The old man leaned his arms on the rail. “In a hundred years somebody will ask your grandson where his family comes from, and he will say the name of this thing.”',
        '“It hasn’t got a name.”',
        'Sa3id grinned with his crooked teeth.',
        '“Not yet,” he said.',
        'The boats came ashore on a beach at the foot of the rock. There was nobody there. No army, no guard post, no village. Only pebbles, seaweed and the sound of the sea.',
        'Seven hundred men and sixty-two horses stood on a strange coast, and the ships turned round at once for the next load.',
        'Two days alone, Sa3id had said.',
        'Ayyur took the horses higher up, to the grass behind the pebbles, and started drawing a line in the sand for the enclosure. The next thing that had to be done.',
        'Behind him Tariq climbed the first slope to see what the land looked like.',
      ] },
      { titel: 'Two days alone', tekst: [
        'On the first night on the other side nobody slept.',
        'That was not because of fear, although that was there too. It was because seven hundred men who have just stepped off a boat all decide at the same moment that they must do something, and there is nobody who knows what.',
        'An enclosure was put up and moved again. A fire was lit and put out again, because someone said you can see a fire from far off. Watches were set in places where there was nothing to guard.',
        'Ayyur did what he always did. He took the horses to the grass, counted them, counted them again, and lay down with them.',
        'Sixty-two. It added up.',
        'Above him the rock stood like a wall somebody had left half finished.',
        'Towards morning it grew cold, the way it grows cold by the sea: not sharp, but everywhere at once. Ayyur pulled his blanket over himself and listened to the horses breathing around him, and thought of his father in the hills behind Tangier, six hours’ sailing and a whole life away.',
        'Then someone started calling.',
        'He shot upright, because calling usually means something is coming.',
        'But nothing was coming. It was a man who had climbed onto a stone at the edge of the camp, facing east, and who was calling the way they had called in the camp at Tangier too, every morning, since Ayyur had worked there.',
        'Men stood up. Not all of them. Enough to see it.',
        'They formed rows on the pebbles, and they bowed, and they stood up again, and they bowed again, and across the water it sounded as if the beach were breathing.',
        'Ayyur stayed sitting with the horses.',
        'He was not afraid of it. He simply did not understand it, and nobody had taken the trouble to explain it, because nobody explains anything to the boy who sleeps with the horses.',
        'What he did see was this: they were calmer afterwards. All night they had walked around the camp like chickens, and after that quarter of an hour they walked like men with a job.',
        'That was the first thing he understood about the new faith. Not what was in it. What it did.',
        'The ships came back that afternoon for the second load, and the two days alone turned out to have been one and a half.',
      ] },
      { titel: 'The shepherd and the goat', tekst: [
        'On the fourth day somebody came.',
        'He came from above, down the slope, with a stick and with eleven goats, and he walked into the camp as if it had always been there.',
        'Three men had hold of him at once.',
        'Ayyur saw it from the enclosure and thought: he is old. That was the first thing. He was old, and thin, and he held his stick the way you hold something you have held for forty years.',
        'They brought him to the tent. A man came who knew Latin, and spoke to him, and the old man answered in something that was not Latin.',
        'Then someone came who spoke Berber, from the same region as Ayyur, and tried, and the old man looked at him as though he were listening to a bird.',
        'In the end it went with hands.',
        'The goats were his. The slope was his, that is to say: he had walked there with goats all his life, which comes to the same thing. He had seen the ships. He had warned nobody, because whom would he warn, and about what.',
        'That last part was asked three times and answered the same three times.',
        'They let him go.',
        'Sa3id thought that was stupid and said so out loud. “He’ll walk to the first village and then they’ll know.”',
        '“They already know,” said the man with the Latin. “There were four ships in the water. Everyone from Tarifa to Algeciras can see that.”',
        'The old man walked back up the slope with his eleven goats and did not look round.',
        'Ayyur watched him until he disappeared over the ridge.',
        'He had imagined the other side as something else. As a land with a king and a crown and walls, or as nothing, as water and then more water. Not as an old man with goats holding the same stick as the men in the hills behind Tangier.',
        '“What did you think, then,” said Sa3id when he said it. “That there were monkeys here?”',
        'Ayyur said nothing, because honestly he had not known what he thought.',
        'That evening the old man came back with two goats on a rope and set them down by the tent, and made a gesture that nobody understood exactly and everybody understood.',
        'They paid him in copper. Not much copper.',
        'He took it, looked at the coins, put them away, and walked back up the slope.',
        'That is how the conquest of the land on the other side began: with two goats and a fair price.',
      ] },
      { titel: 'What Sa3id believes', tekst: [
        'Sa3id had crooked teeth, a scar through his eyebrow and an opinion about everything.',
        'He was from Tlemcen, he was twenty-eight, and he had been there from the start. He had found Ayyur at the horses on the first day and had kept coming back, for reasons Ayyur never entirely understood. Perhaps because the boy listened. Perhaps because nobody else listened.',
        'On the seventh evening Ayyur finally asked.',
        '“Why do you call out in the mornings?”',
        'Sa3id looked up from the strap he was greasing.',
        '“That’s the call,” he said.',
        '“I know that. Why?”',
        'Sa3id thought about it, which was unusual for him.',
        '“Because it’s time,” he said then. “Five times a day it’s time. When it gets light, when the sun is at its highest, when your shadow is longer than you are, when the sun has gone, and when it is dark.”',
        '“And then?”',
        '“Then you stop what you’re doing and stand still.”',
        '“What for?”',
        '“For God.” Sa3id shrugged. “There is one. Don’t ask me more than that, because I’m no scholar. I’m a man with a horse and a spear.”',
        'Ayyur was quiet for a moment.',
        '“My father says something lives in the spring by our village,” he said. “He leaves milk there every spring.”',
        'He said it with the tension of someone who does not know whether he is about to be laughed at.',
        'Sa3id did not laugh.',
        '“Then your father says that,” he said. “I say what I say. Neither your father nor I have time to work it out, so we do our work.”',
        'He went on with the strap.',
        '“We only got it recently too,” he said afterwards. “My grandfather knew nothing about it. My father started with it and knew half of it. I know a bit more than he did and less than the man who calls in the morning. In a hundred years they’ll know everything about it and think it was always like this.”',
        'He held the strap up to the light.',
        '“That’s how it goes with everything,” he said.',
        'Ayyur thought about that for a long time afterwards, longer than Sa3id had probably intended.',
        'He did not go and stand with them, not that evening and not in the weeks after. But from then on he stopped sitting with the horses as if nothing were happening. He stood up when it began. That was all he did. He stood up, and he waited until it was over, and then he carried on.',
        'It seemed to him the least you could do for something seven hundred men stand still for.',
      ] },
      { titel: 'Tafukt', tekst: [
        'In the second week a horse died.',
        'It was not Tafukt. It was a brown stallion without a name, from the last load, who had got a leg stuck in the pebbles when they took him off the boat.',
        'They had heard it. Everyone on the beach had heard it.',
        'Sa3id did it with a knife and he did it quickly, and he did not let Ayyur do it, even though Ayyur had offered because it was his horse to look after.',
        '“No,” Sa3id had said. “You’re twelve.”',
        '“Thirteen in two months.”',
        '“Then you’ll do it in two months.”',
        'Afterwards Ayyur sat by the enclosure for the rest of the afternoon doing nothing, which never happened to him.',
        'It was not about the stallion. He had seen sheep die, many sheep, and one winter so many that he had stopped counting.',
        'It was because he realised that nobody at home would know.',
        'Nobody at home knew where he was. He had not been able to say, because he could not write and nobody was going that way. If he died tomorrow on a beach on the other side, his father in the hills behind Tangier would wait until winter and then think he had run away.',
        'Tafukt pushed her nose against his shoulder.',
        'He stayed sitting until it got dark and stood up when the call came, as he did now, and then went to work.',
        'The next morning he went to find the scribe.',
        'The scribe was a small man with inky fingers who sat on a stone all day writing down things nobody had asked him to write down. His name was Yunus and he came from Kairouan.',
        '“Can you write something for me?”',
        'Yunus looked up. “For whom?”',
        '“My father.”',
        '“Can your father read?”',
        'Ayyur was silent.',
        '“No,” he said then.',
        '“Does he know anyone who can?”',
        '“The man who collects the tax comes twice a year. He can.”',
        'Yunus thought, then took a shard of tablet out of his box and put it on his knee.',
        '“Go ahead.”',
        'Ayyur said: “Ayyur is alive. Ayyur is with the horses. Ayyur is coming back.”',
        'Yunus wrote it down, looked at it, and said: “Is that all?”',
        '“What else should there be?”',
        'The scribe shrugged and laid the shard in the box with the letters that would go back on the next boat.',
        'It was the first time in his life that Ayyur’s name stood written anywhere.',
        'He thought about that for the rest of the day, while he trimmed hooves and fetched water, and he caught himself liking it in a way he was almost ashamed of.',
      ] },
      { titel: 'The mountain of Tariq', tekst: [
        'In the third week the rock got its name, and Ayyur was there when it happened, though he did not know it at the time.',
        'By then there was a camp. There were enclosures, there was a well they had dug, there were tents in rows. Four loads had arrived and more would come.',
        'Yunus sat on his stone with a tablet on his knees, and he asked the man next to him how he should write the place.',
        '“Which place?”',
        '“This one. Where we are. I have to write down where the army is.”',
        'The man shrugged.',
        '“By the mountain,” he said.',
        '“Which mountain?”',
        'They both looked up.',
        '“The mountain of Tariq,” said the man, and he said it the way you say something obvious.',
        'Yunus wrote it down. Jabal Tariq.',
        'Ayyur stood two paces away with a bucket in his hand and heard it, and thought: fine, and walked on.',
        'That is how these things go. There is never anybody present who thinks: this is the moment. The moment looks like a scribe who needs a word and a soldier who cannot be bothered.',
        'Thirteen hundred years later that name is still on every map in the world, worn down into something no human being recognises any more, and nobody who says it knows there was a man called Tariq.',
        'Ayyur took the bucket to the horses.',
      ] },
      { titel: 'The army goes north', tekst: [
        'They left one morning in July, and it took from first light until well past midday before the last row was out of sight.',
        'Ayyur did not go.',
        'He had been told two days earlier, by Sa3id, who delivered it the way he delivered everything: without preamble and in the wrong order.',
        '“You’re staying here.”',
        '“Why?”',
        '“Because a hundred horses are staying behind and somebody has to look after them.”',
        '“There are other men.”',
        '“There are no other men who know all the names.”',
        'Ayyur did not know whether that was a compliment or a way of keeping him out of the fighting. He suspected the second, and he was angry and relieved about it at the same time, and feeling those two things side by side is something you have no word for at twelve.',
        'Sa3id did go.',
        'On the morning of the departure he came past the enclosure leading his horse — a grey gelding Ayyur had been caring for for three months and whom he called Amellal, which means white, which was not true and which the gelding had never disputed.',
        '“Make sure he drinks before it gets hot,” said Ayyur.',
        '“I know that.”',
        '“He doesn’t drink from still water. You have to move it with your hand.”',
        '“I know that too.”',
        'They both stood there as if something else still had to come.',
        '“If anything happens,” said Sa3id, “go to Yunus. He isn’t brave but he’s clever, and clever is worth more here.”',
        '“All right.”',
        'Sa3id climbed up, looked down once more and said: “You’re not a bad boy, Ayyur. Stay away from the water, you can’t swim.”',
        'Then he rode away.',
        'Ayyur watched him to somewhere halfway up the second hill and after that no longer, because from there on it was one cloud of dust and they were no longer people.',
        'He went back to the horses.',
        'There were a hundred and four. He counted them twice.',
      ] },
      { titel: 'Waiting is something too', tekst: [
        'The weeks that followed were the longest of his life and almost nothing happened in them.',
        'That is the strange thing about war, Ayyur discovered: for almost everyone it is waiting. The stories are about the day it happened. Nobody tells you about the four weeks before, when you are looking for grass for a hundred and four horses on a slope where the grass has run out.',
        'In those weeks he learned three things.',
        'The first he learned from the old man with the goats, who came by every few days and then every day, and who eventually spent his afternoons at the enclosure without anyone being able to explain why. His name was something Ayyur was never able to say properly. He pointed at things and said the word, and Ayyur said it after him, and the old man corrected him, and that went on all summer.',
        'Water. Stone. Goat. Mountain. Child. Bread.',
        'That is how you learn a language. Not from a book. From an old man with nothing better to do.',
        'The second he learned from Yunus. One afternoon he asked, half as a joke, whether the scribe could teach him letters, and Yunus said: “No,” and three days later he was sitting beside him with a stick in the sand.',
        'It went slowly. Ayyur was bad at it. His hand did not do what his head intended and the letters came out crooked, like something an animal had touched.',
        'After a month he could write his own name.',
        'That evening he wrote it twenty times in the sand by the enclosure and rubbed it out twenty times, and the twenty-first time he left it standing until the wind took it away.',
        'The third he learned from nobody.',
        'He discovered that at the call he no longer stood up only out of politeness.',
        'It was somewhere in August. He was standing by Tafukt, it was getting dark, the man on the stone began, and Ayyur noticed that he liked it that it was happening. Not because of what was being said — he still understood little of it. Because of the fact that five times a day a line was drawn, on a coast where he knew nobody and nobody knew him, and that the day was not a mush because of it but a thing with parts.',
        'He still did not go and stand with them.',
        'But that week he did ask Yunus how the words went, and Yunus said them slowly, and Ayyur said them after him, and the scribe corrected him the way the old man corrected him at water, stone, goat.',
        'And in this book that is where it stops, because that is where it stopped.',
        'What became of it in the years after, we do not know. We only know that it began that way for thousands of boys like him: not with an army, not with a battle, but with someone who saw something happen five times a day until it belonged to the day.',
      ] },
      { titel: 'The news from the river', tekst: [
        'The news came on a Tuesday, with a rider who had ridden so hard that his horse could not be saved.',
        'Ayyur saw it in the horse before he saw it in the man. That is how it works when you belong to horses.',
        'There had been a battle at a river in the south of the country, eight days away. It had lasted three days, or five, depending on whom you asked. The king with the crown had been there and was no longer there, and about that the stories diverged so quickly that Ayyur stopped listening.',
        'What was the same in every story: the army had not been defeated. It was moving north. Cities would fall that nobody in the camp knew by name.',
        'There was cheering on the beach that evening.',
        'Ayyur did not cheer, because he still had not heard what he wanted to hear.',
        'He asked the rider, who was too tired to be polite.',
        '“Sa3id from Tlemcen. Grey horse. Scar through his eyebrow.”',
        'The man looked at him as if he were asking about one sheep out of a flock of ten thousand.',
        '“Boy,” he said. “I’m not even sure of the king’s name.”',
        'Three weeks later a second rider came, and he did not know either.',
        'In October a cart came back with wounded men and with men who did not want to go on, and Ayyur went along all twenty-eight of them and asked twenty-eight times.',
        'The twenty-fifth knew him.',
        '“Sa3id,” he said. “Yes. At the river.”',
        'Ayyur waited.',
        '“He was alive when I saw him,” said the man. “After that I fell and I saw nothing more.”',
        'That was all. That is all Ayyur ever found out, and it is also all we know, because of the seven thousand men who crossed the strait that year, four are known by name and the rest is dust.',
        'Ayyur went back to the enclosure.',
        'Amellal was not standing there. He had not been for three months, and still he looked every time.',
        'He fetched water, moved it with his hand the way you do for a horse that will not drink from still water, and gave it to another animal.',
      ] },
      { titel: 'The chest', tekst: [
        'At the end of October Yunus came through the camp with a chest under his arm, looking for someone who could ride and knew the road along the coast.',
        'There was nobody else left. That was the honest answer to the question of why he ended up at Ayyur.',
        'The chest had to go north, to a place where the army had set up a winter camp. There were tablets in it, and letters, and a leather bag with small things soldiers had handed in because they did not want to lose them — and had not come back to collect, which tells you everything about those soldiers that you do not want to know.',
        '“How long?” asked Ayyur.',
        '“Six days. Eight if it rains.”',
        '“And then?”',
        'Yunus looked at him.',
        '“Then you’re there,” he said. “And there is more than here.”',
        'Ayyur loaded the chest onto Tafukt.',
        'While he was lashing it down the bag tipped over and something rolled out onto the ground.',
        'It was bronze, as long as his hand, and it had a head with eight points. Like a star.',
        '“What’s that?” he asked.',
        'Yunus barely looked at it.',
        '“A key,” he said. “It was already in the bag when I got it. Nobody knows whose.”',
        'Ayyur held it in his hand for a moment. It was warm from the sun.',
        'He thought of a door somewhere, on the other side of the water, that someone had pulled shut behind them for the last time without knowing it was the last time. Of a house that might still be standing. Of a man who had gone on board with a key in his pocket because you do not leave one behind, and who had handed it in because you do not take it across the river either.',
        'He let it slide back into the bag.',
        'Then he took it out again, and pushed it into his own belt.',
        'Yunus saw it and said nothing.',
        '“Nobody’s coming for it,” said Ayyur.',
        '“No,” said Yunus. “Nobody’s coming for it.”',
        'Ayyur pulled the strap tight and climbed up.',
      ] },
      { titel: 'North', tekst: [
        'He rode away that afternoon along the coast, with a chest, a mare and a key that belonged to nobody.',
        'At the last bend before the slope he reined in and looked back.',
        'The camp lay below him as if it had always lain there: enclosures, tents in rows, the well, smoke from two fires. Seven months ago it had been pebbles and seaweed.',
        'The old man with the goats stood on the edge of his slope, as he stood there every afternoon.',
        'Ayyur raised his hand.',
        'The old man raised his stick.',
        'That was that.',
        'He rode on, and the land he rode into was green in a way he did not know, with different trees and too much water, and with villages where people stood by the road and looked at a boy on a mare with a chest.',
        'He greeted them in the words he had learned from the old man. Water. Stone. Bread.',
        'Some laughed. One woman gave him bread.',
        'He should have written that down later, because it is the kind of thing that disappears: that for a boy of twelve the first weeks of the conquest of that land consisted of strange trees, too much water and a woman who gave him bread.',
        'He never went back to the hills behind Tangier.',
        'That was not a decision. For almost nobody is it. Winter came, and there was work, and there were horses, and then a year had gone by and then another, and at some point it is no longer a journey you are putting off but a life you have.',
        'The shard with his name on it reached his father. We do not know that. We hope it.',
        'What we do know is that in the centuries afterwards millions of people crossed that strait, one way and the other, and that every time someone was left behind who waited.',
        'The key went north, in the belt of a boy who had been given it by nobody.',
        'Where it went after that is in the next book.',
      ] },
    ],
  },
}
