import type { SleutelVertaling } from './sleutels-talen'

/**
 * De sleutels van Marokko in het Frans.
 *
 * Wordt deel voor deel vertaald. Wat hier staat is af; de rest valt terug op
 * het Nederlands tot het zover is.
 *
 * De regelval van het Nederlands blijft staan: één alinea daar is één alinea
 * hier. Dat is geen vormfetisj — een hoofdstuk van dit boek is opgebouwd uit
 * korte alinea’s met stiltes ertussen, en wie die samenvoegt haalt het tempo
 * eruit.
 *
 * Aanhalingstekens zijn de Franse « en », de apostrof is overal de
 * typografische ’ en nooit de rechte: die breekt de string waar dit bestand
 * in staat.
 */
export const FR_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'L’incendie des olives',
    jaar: '± 200',
    waar: 'Walili (Volubilis), au pied du Zerhoun',
    verteller: 'Tala, onze ans, fille d’un maître pressier tombé malade',
    flap: 'Tala a la clé de la réserve, et l’intendant la veut. Quand l’huile de toute la ville est en danger, elle doit choisir entre obéir et avoir raison.',
    sleutel: 'La clé est forgée à Walili par le grand-père de Tala, et repart à la fin vers les collines avec une caravane amazighe.',
    echt: [
      'Volubilis — Walili en arabe — était une vraie ville romaine près de Meknès, avec des milliers d’habitants, des thermes et des rues pavées.',
      'La ville vivait de l’huile d’olive. On y a dégagé des dizaines de pressoirs, et ils fonctionnaient selon le même principe que ceux qu’on utilise encore au Maroc aujourd’hui.',
      'Les sols étaient couverts de mosaïques. Une partie est toujours là, à ciel ouvert.',
      'La population était en grande partie amazighe ; la vie romaine et la vie amazighe s’y mêlaient.',
    ],
    verzonnen: [
      'Tala, sa famille et l’intendant Marcus n’ont pas existé.',
      'L’incendie de l’histoire est inventé. Rien ne prouve qu’un grand incendie ait eu lieu à Walili à cette époque.',
      'La clé à l’étoile à huit branches est inventée. Le khatam à huit branches, lui, est un motif marocain bien réel et très ancien.',
    ],
    hoofdstukken: [
      { titel: 'La clé', tekst: [
        'Tala fut réveillée par l’odeur.',
        'Des olives. Des olives pressées, tièdes et amères. Toute la ville sentait cela, ces semaines-là. Elle resta allongée un instant et écouta. Dehors, le grand pressoir grinçait déjà. Cela voulait dire qu’elle était en retard.',
        'Elle sauta de son lit et enfila sa robe par la tête.',
        '« Tala ! » cria sa mère d’en bas. « La porte ! »',
        'La porte. Bien sûr, la porte.',
        'Depuis que son père était tombé malade, Tala faisait son travail. Chaque matin elle allait jusqu’à la réserve derrière la maison et ouvrait la porte. Les jarres étaient là. Cent jarres, remplies d’huile jusqu’au bord, prêtes à partir pour le port.',
        'La clé pendait à un cordon autour de son cou. Elle était en bronze et longue comme sa main. Son grand-père l’avait forgée, bien avant sa naissance. Dans la tête il y avait huit branches, comme une étoile.',
        '« Ne la perds pas », avait dit son père. Il l’avait dit tout bas, parce qu’il ne pouvait plus parler plus fort. « Cette porte ne s’ouvre pour rien d’autre. »',
        'Tala dévala l’escalier, passa devant la cuisine, traversa la cour. Il était encore tôt. Le soleil venait de se poser sur les collines et les pierres étaient froides sous ses pieds.',
        'Devant la réserve il y avait un homme.',
        'Elle s’arrêta net.',
        'Il était grand et portait le manteau rouge de l’intendant. Marcus. Tout le monde à Walili connaissait Marcus, et personne ne l’aimait.',
        '« Tu es en retard », dit-il.',
        '« Je suis à l’heure », dit Tala.',
        'Elle savait qu’elle n’aurait pas dû dire ça. Elle le dit quand même.',
        'Marcus la regarda. Puis il tendit la main.',
        '« Donne-moi donc cette clé. Un enfant n’a pas à garder cent jarres. »',
        'Tala fit un pas en arrière.',
        'Dans sa tête elle entendit son père. *Cette porte ne s’ouvre pour rien d’autre.* Et elle pensa à autre chose, quelque chose qu’elle avait vu la veille et dont elle s’était dit que ce n’était rien.',
        'Deux jarres qui n’étaient pas à leur place.',
        '« Alors ? » dit Marcus.',
        'Tala serra la main autour du bronze. Il était devenu tiède contre sa peau.',
        '« Non », dit-elle.'] },
      { titel: 'Deux jarres', tekst: [
        'Marcus ne rit pas. Il ne se mit pas en colère non plus. C’était ça, le pire.',
        'Il laissa retomber sa main, rajusta son manteau et dit : « Comme tu voudras. » Puis il s’en alla, sortit de la ruelle, sans se retourner.',
        'Tala resta immobile jusqu’à ce qu’elle n’entende plus ses pas. C’est seulement après qu’elle remarqua que ses mains tremblaient.',
        'Elle ouvrit la porte.',
        'À l’intérieur il faisait sombre et frais. Les jarres étaient rangées par dix, avec de la paille entre elles pour qu’elles ne se cognent pas. Dix rangées de dix. Chaque matin elle les comptait. Son père le lui avait appris quand elle avait six ans, et à l’époque c’était encore un jeu.',
        'Elle commença par la gauche et compta à voix haute, comme toujours.',
        'À la dernière rangée, elle s’arrêta.',
        'Il y en avait neuf.',
        'Tala recompta. Neuf. Elle fit le tour de la rangée, se baissa, regarda derrière la paille. Neuf.',
        'La veille aussi, elle avait vu quelque chose d’étrange. Deux jarres mal placées, les anses tournées vers le mur au lieu de l’allée. Elle s’était dit : quelqu’un a fait ça vite. Elle les avait remises droites et n’y avait plus pensé.',
        'Maintenant il en manquait une.',
        'Elle s’assit dans l’embrasure, le dos contre le montant et les genoux repliés, et essaya de décider quoi faire.',
        'Elle pouvait le dire à sa mère. Mais sa mère avait déjà bien assez ce mois-ci : un mari malade à l’étage, une maison pleine de gens à payer, et une récolte qui devait partir au port dans trois semaines.',
        'Elle pouvait le dire à Marcus. Marcus était l’intendant. C’était son travail.',
        'Tala regarda la ruelle où il avait disparu.',
        'Non.',
        '« Tu es dans le passage », dit une voix.',
        'Elle sursauta. Devant elle se tenait un garçon à peu près de son âge, un tablier de cuir sur le ventre et les bras chargés de fagots. Ses mains étaient noires.',
        '« Je ne suis pas dans le passage », dit Tala. « C’est ma porte. »',
        '« Alors tu es dans le passage de ta propre porte. »',
        'Il s’appelait Yidir et il travaillait à la forge, au bout de la rue. Tala le connaissait de vue comme on connaît tout le monde de vue à Walili, et pas plus.',
        'Elle se leva pour le laisser passer. Il ne passa pas.',
        '« Tu comptes tous les matins », dit-il.',
        '« Comment tu sais ça ? »',
        '« Je passe tous les matins. »',
        'Tala hésita. Puis elle le dit quand même, parce qu’il fallait que ça sorte et parce qu’il était là.',
        '« Il en manque une. »',
        'Yidir posa ses fagots par terre.',
        '« Une ? » dit-il. « Alors tu as eu de la chance. Chez nous il manque six barres de fer. »'] },
      { titel: 'Comment on fait l’huile', tekst: [
        'Cet après-midi-là, Tala était au pressoir, comme chaque jour pendant la récolte.',
        'Le pressoir était une pierre creusée, grande comme une charrette, avec une pierre ronde à l’intérieur qu’un âne faisait tourner. Les olives entraient, elles étaient broyées, et ce qui sortait était une pâte brune et épaisse qui ne ressemblait à rien.',
        'C’était la partie qui décevait toujours les étrangers. « C’est ça, l’huile ? » demandaient-ils. Non. C’était le début.',
        'La pâte allait dans des scourtins ronds tressés en jonc. On les empilait sous la presse à levier, et deux hommes tournaient la vis, lentement, comme s’ils avaient tout leur temps. Sous la pile courait une rigole.',
        'C’est de là que ça sortait.',
        'D’abord de l’eau, trouble et sale. Puis, au bout d’un moment, autre chose. Quelque chose qui flottait sur l’eau et qui était plus vert que tout ce que Tala connaissait.',
        'La première fois, son père l’avait prise par la nuque et lui avait tenu la tête au-dessus. « Sens », avait-il dit. « C’est ça. Si ça sent comme ça, c’est bon. Si ça ne sent rien, tu as trop attendu. »',
        'Ce jour-là elle avait menti en disant qu’elle sentait. Maintenant elle sentait vraiment.',
        'Walili vivait de ça. Pas des sols en mosaïque sur lesquels marchaient les visiteurs, pas des colonnes de la place, pas des rues pavées. De ça. D’olives pressées qui partaient en jarres, sur des charrettes vers la côte, puis sur des bateaux vers des endroits dont Tala ne connaissait que les noms.',
        'Elle surveillait la rigole, et les scourtins, et l’âne, et pendant ce temps elle pensait à quatre-vingt-dix-neuf jarres.',
        'Six barres de fer, avait dit Yidir. De la forge.',
        'Le fer coûtait cher. L’huile coûtait cher. Et les deux sortaient de la ville dans la même direction : par la route du port.',
        '« Tala. » Un des hommes montra la rigole. « Ça déborde. »',
        'Elle se précipita et glissa le bol dessous, trop tard. Un filet d’huile coula sur la pierre et disparut entre les joints.',
        'L’épaisseur d’un doigt, peut-être deux. De quoi nourrir une famille pendant une semaine.',
        'L’homme ne dit rien. C’était pire.'] },
      { titel: 'Ce qu’un intendant a le droit de faire', tekst: [
        'Marcus revint le troisième jour, et il ne vint pas seul.',
        'Tala le vit entrer dans la cour avec deux hommes derrière lui. Sa mère sortit, s’essuya les mains sur sa robe, et se planta exactement entre lui et la porte.',
        '« Paix », dit Marcus.',
        '« Paix », dit sa mère, sur le ton qu’on prend quand on ne le pense pas.',
        '« Ton mari est malade. »',
        '« Mon mari se repose. »',
        '« Trois semaines », dit Marcus. « Dans trois semaines la récolte part au port, et la ville compte sur ce qu’il y a dans cette maison. Je dois savoir que c’est là. »',
        '« C’est là. »',
        '« Je veux le voir. »',
        'Il y eut un silence. Tala se tenait dans l’embrasure de la cuisine et n’osait pas bouger.',
        'Sa mère dit : « Tu peux regarder. C’est ma fille qui ouvre. »',
        'Tala traversa la cour sous les yeux de cinq personnes. Elle fit passer le cordon par-dessus sa tête, glissa la clé dans la serrure et poussa la porte.',
        'Marcus entra. Il longea les rangées, lentement, les mains dans le dos. Devant la dernière rangée, il s’arrêta.',
        'Tala retint son souffle.',
        '« Quatre-vingt-dix-neuf », dit Marcus.',
        'Il se retourna et regarda sa mère.',
        '« Il devrait y en avoir cent. »',
        'Sa mère se raidit. Tala le vit à ses épaules.',
        '« Alors il y en a une de cassée », dit-elle.',
        '« Alors il y aurait des tessons. » Marcus écarta les mains. « Je ne vois pas de tessons. Je vois de la paille qu’on a remise droite. »',
        'Il attendit un instant, juste assez longtemps.',
        '« Je ne dis pas que vous volez », dit-il alors. « Je dis qu’une enfant de onze ans a la clé de cent jarres, et qu’aujourd’hui il y en a quatre-vingt-dix-neuf. Voilà ce que je dis. Et je le dirai aussi sur la place. »',
        'Il sortit et passa devant Tala comme si elle était un poteau.',
        'Quand il fut parti, sa mère s’assit sur la margelle du puits. Elle ne dit rien pendant très longtemps.',
        '« Maman », dit Tala. « Je ne l’ai pas— »',
        '« Je sais. »',
        '« Je les ai comptées lundi et il y en avait encore— »',
        '« Tala. » Sa mère leva les yeux. Ils étaient rouges. « Je sais. Et ça ne nous aide en rien. »'] },
      { titel: 'La forge', tekst: [
        'Yidir était assis sur un seau retourné devant la forge et ponçait une charnière.',
        '« Tu avais raison », dit Tala.',
        '« Les gens me disent rarement ça », dit Yidir sans lever les yeux. « À propos de quoi ? »',
        '« Du fait que ce n’était pas une seule jarre. »',
        'Cette fois il leva les yeux.',
        'Tala s’assit à côté de lui sur le seuil et raconta. Marcus, les quatre-vingt-dix-neuf, ce qu’il allait dire sur la place. Yidir écoutait comme il faisait tout : comme s’il pensait à autre chose en même temps, mais il ne ratait rien.',
        '« Et ton fer ? » demanda-t-elle.',
        '« Six barres. Mon maître pense qu’il s’est trompé en comptant. » Yidir haussa les épaules. « Mon maître ne se trompe jamais en comptant. »',
        '« Quand ? »',
        '« La semaine dernière. Et trois la semaine d’avant. »',
        'Tala remonta les genoux.',
        '« Qu’est-ce qui sort de la ville ? » demanda-t-elle. « Chaque jour, je veux dire. »',
        'Yidir réfléchit.',
        '« Des charrettes », dit-il. « De l’huile, du grain, des peaux, du fer. Tout passe par la route du nord. Il y a un poste de garde à la porte. Là, tout est noté. »',
        '« Par qui ? »',
        'Yidir la regarda.',
        '« Par l’intendant », dit-il.',
        'Ils ne dirent rien pendant un moment, ni l’un ni l’autre.',
        '« Ça ne prouve rien », finit par dire Tala.',
        '« Non. »',
        '« Si je dis ça, ils diront qu’une gamine de onze ans accuse un homme parce qu’il ne l’aime pas. »',
        '« Oui », dit Yidir. « C’est ce qu’ils diront. »',
        'Il posa la charnière.',
        '« Donc il te faut quelque chose qu’ils ne peuvent pas balayer avec des mots. »',
        '« Comme quoi ? »',
        '« Comme voir ce qui passe cette porte la nuit. »',
        'Tala le regarda. Il la regarda en retour, et pour la première fois depuis qu’elle le connaissait, il sourit.'] },
      { titel: 'Ce qui passe la porte la nuit', tekst: [
        'Ils étaient couchés sur le toit des thermes, à plat ventre, le menton sur les bras.',
        'Le toit était encore chaud de la journée. En dessous d’eux passait la rue qui menait à la porte nord, assez large pour deux charrettes côte à côte. À la porte brûlait une seule lampe.',
        '« Encore combien de temps ? » chuchota Tala.',
        '« Je ne sais pas. »',
        '« Tu as dit qu’il passait des charrettes la nuit. »',
        '« J’ai dit que je *croyais* qu’il passait des charrettes la nuit. »',
        'Tala soupira et posa la tête sur son bras.',
        'Les étoiles, cette nuit-là, étaient incroyables. En ville on n’en voyait que la moitié, à cause de la lumière et de la fumée, mais là-haut il y en avait tellement que ça en devenait inquiétant.',
        '« Ma grand-mère dit que c’est une carte », dit Yidir.',
        '« Les étoiles ? »',
        '« Oui. Si tu sais les lire, tu peux aller partout. Elle dit que sa famille est venue du désert jusqu’ici comme ça. »',
        '« Tu sais les lire, toi ? »',
        '« Non », dit Yidir. « Personne ne me l’a appris. »',
        'C’est là qu’ils l’entendirent.',
        'Une charrette. Pas deux ânes, pas de chevaux — un âne, au pas, et le bruit du bois qui craque sous le poids.',
        'Tala se glissa jusqu’au bord.',
        'La charrette sortait d’une rue de côté. Deux hommes marchaient à côté, tous deux la tête enveloppée d’un tissu. Sur la charrette il y avait de la paille, et sous la paille quelque chose de rond.',
        'À la porte, la charrette s’arrêta.',
        'Un homme sortit de la guérite avec une lampe. Il n’alla pas vers la charrette. Il alla vers les hommes, leur parla brièvement, et nota quelque chose sur une tablette.',
        'Puis il leva la barrière.',
        'La charrette s’enfonça dans la nuit.',
        'Tala relâcha son souffle. Elle n’avait pas remarqué qu’elle le retenait.',
        '« Il n’a pas regardé », dit-elle. « Il n’a pas regardé sous la paille. »',
        '« Non. »',
        '« C’est— »',
        '« Ça ne fait toujours rien », dit Yidir. « C’est un homme qui ne regarde pas assez bien. On ne pend personne pour ça. »',
        'Il avait raison, et Tala le savait aussi.',
        'Mais quand la charrette prit le virage, il se passa quelque chose. L’âne eut peur de quelque chose dans le noir, tira sur le côté, et la charrette monta d’une roue sur le bord du trottoir.',
        'Quelque chose tomba de la charrette.',
        'Ça roula, s’immobilisa contre le mur, et resta là.',
        'Une jarre.',
        'Un des hommes jura, revint sur ses pas, la ramassa et la remit sous la paille. La charrette repartit.',
        'Mais Tala avait vu ce qu’il y avait dessus.',
        'Sur l’épaule de chaque jarre de leur maison, son père imprimait un signe dans l’argile avant la cuisson. Huit branches. Une étoile.',
        'Elle attrapa le bras de Yidir si fort qu’il siffla entre ses dents.',
        '« Elle est à nous », dit-elle.'] },
      { titel: 'Ce que tu dis et ce qu’ils entendent', tekst: [
        'Le lendemain matin, Tala alla sur la place.',
        'Elle y avait pensé toute la nuit, ou en tout cas la moitié de la nuit ; l’autre moitié elle avait dormi sans le vouloir. Elle savait ce qu’elle allait dire. Elle l’avait répété trois fois contre le mur de sa chambre.',
        'Sur la place, sous les colonnes, le conseil siégeait. C’est-à-dire : cinq hommes sur des bancs de pierre, un scribe à côté, et autour tous ceux qui avaient quelque chose à réclamer.',
        'Marcus était déjà là.',
        'Tala attendit qu’un homme ait fini de parler d’un mur et d’un voisin. Puis elle s’avança.',
        '« Je voudrais dire quelque chose », dit-elle.',
        'Cinq hommes levèrent les yeux. L’un d’eux, le plus vieux, avec un visage de figue sèche, se pencha en avant.',
        '« Tu es la fille de qui ? »',
        '« De Yuba, le pressier. De la rue des Colonnes. »',
        '« Il est malade. »',
        '« Oui », dit Tala. « C’est pour ça que je suis là. »',
        'Elle raconta. La jarre disparue, et une autre le lendemain. La charrette dans la nuit et l’homme qui avait levé la barrière sans regarder sous la paille. La jarre tombée, et le signe aux huit branches.',
        'Elle raconta exactement comme elle l’avait répété, et pendant qu’elle le faisait, elle s’entendit elle aussi.',
        'Elle entendit comment ça sonnait.',
        'Une enfant. Un toit. Le noir. Un signe que personne d’autre n’avait vu.',
        'Quand elle eut fini, il y eut un silence. Puis Marcus dit, très calmement : « Vous permettez ? »',
        'Le plus vieux hocha la tête.',
        '« La petite a raison : il manque des jarres », dit Marcus. « Je les ai comptées moi-même, avant-hier, dans leur propre réserve. Quatre-vingt-dix-neuf sur cent. Je l’ai dit à ce moment-là. »',
        'Il écarta les mains, comme il le faisait.',
        '« Qui a la clé de cette porte ? »',
        'Personne ne dit rien.',
        '« Elle », dit Marcus. « Une enfant de onze ans. Et maintenant qu’il en manque une, c’est une charrette dans la nuit. Une charrette qu’elle est la seule à avoir vue. »',
        'Le plus vieux du conseil regarda Tala, et son regard n’était pas hostile. C’était encore ça, le pire.',
        '« Petite », dit-il. « Rentre chez toi. Occupe-toi de ton père. »',
        'Tala resta sur la place, les bras le long du corps et les oreilles brûlantes, et tout autour d’elle les gens s’étaient remis à parler d’un mur et d’un voisin.'] },
      { titel: 'L’incendie', tekst: [
        'L’incendie commença quatre jours plus tard, et il ne commença pas chez eux.',
        'Tala en fut réveillée. Pas par la lumière et pas par les cris — par le bruit. Un grondement profond et doux, comme si quelqu’un, tout près, expirait très longuement.',
        'Elle était à la fenêtre avant d’être réveillée.',
        'De l’autre côté de la rue, deux maisons plus loin, la réserve de Quintus brûlait. Quintus pressait de l’huile lui aussi. Ses jarres étaient dans une salle sous sa maison, et le feu en sortait maintenant par la fenêtre, à plat, et non vers le haut comme le feu est censé faire.',
        'C’est à cause de l’huile, Tala l’apprit plus tard. L’huile ne brûle pas pareil.',
        'On criait déjà. Il y avait déjà des gens dans la rue avec des seaux et des couvertures, et quelqu’un frappait avec un bâton la plaque de bronze près du puits, et Tala dévala l’escalier sans chaussures.',
        'Sa mère l’attrapa par le bras dans l’embrasure.',
        '« Pas par là. »',
        '« Mais— »',
        '« Tala. » Sa mère la tenait des deux mains. « Notre porte. Tout de suite. »',
        'Et Tala comprit.',
        'Si ça se propage, ce sera chez eux. Cent jarres — quatre-vingt-dix-neuf — pleines d’huile, derrière une porte en bois, contre le même mur.',
        'Elle courut à la réserve, fit passer le cordon par-dessus sa tête et glissa la clé dans la serrure. Ses mains étaient si moites que le bronze tournait à vide. La troisième fois, ça marcha.',
        'La porte s’ouvrit. La fraîcheur vint à sa rencontre, et l’odeur.',
        'Derrière elle, la rue entière se mit à porter des jarres.',
        'Ils les portaient dans la cour, près du puits, dans la rue, partout où aucun mur ne brûlait. Les voisins portaient, des gens qu’elle connaissait à peine, des gens à qui son père n’avait jamais parlé. Quelqu’un avait une échelle. Quelqu’un jetait des couvertures dans l’eau du puits et les faisait passer.',
        'Tala porta jusqu’à ce que ses bras refusent, et après elle porta encore.',
        'À la soixante-dixième jarre elle vit Yidir. Il arrivait avec quatre autres de la forge, et ils traînaient quelque chose qui ressemblait à un long croc.',
        'À la quatre-vingt-cinquième, le toit de la réserve de Quintus s’effondra vers l’intérieur.',
        'À la dernière, le soleil était presque levé.',
        'Il n’y avait plus de feu alors. Il n’y avait plus que de la fumée qui traînait bas dans la rue, et deux cents personnes debout qui regardaient sans rien dire, et des mains noires, et quelque part un enfant qui pleurait.',
        'Tala était assise sur le pas de la porte, contre sa mère.',
        'Et c’est pour ça qu’elle fut la seule à voir l’homme qui sortit de la ruelle à côté de la maison de Quintus, à contre-courant, son manteau sur le bras au lieu de sur les épaules.',
        'Le manteau était rouge.'] },
      { titel: 'Le manteau rouge', tekst: [
        'Elle le raconta à Yidir avant de le raconter à qui que ce soit.',
        'Il écouta sans l’interrompre, et quand elle eut fini, il dit : « Ça ne fait toujours rien. »',
        '« Je l’ai vu. »',
        '« Tu as vu un homme en manteau rouge dans une rue pleine de gens couverts de suie. » Yidir donna un coup de pied dans une pierre. « Moi je te crois. Le conseil, non. »',
        'Tala savait qu’il avait raison et elle en avait assez qu’il ait toujours raison.',
        '« Quoi alors ? » dit-elle. « Je ne peux quand même pas ne rien faire. »',
        '« Non », dit Yidir. « Mais il te faut quelque chose qui ne vienne pas de toi. »',
        'Il s’assit sur la margelle du puits, les talons contre la pierre.',
        '« À la porte, ils notent tout », dit-il. « Sur de la cire. Ce qui sort, combien, et de qui. Ces tablettes partent chaque mois à la maison de ville. »',
        '« Et s’il n’y a rien d’étrange dessus ? »',
        '« Alors il n’y a rien d’étrange dessus », dit Yidir. « Et alors tu sais que ce n’est pas dans les registres, mais dans le noir. C’est déjà quelque chose. »',
        'Il la regarda.',
        '« Mais s’il y a bien quelque chose — si c’est écrit douze jarres alors que treize sont sorties — alors ce n’est plus une enfant qui a vu quelque chose. C’est un nombre à côté d’un nombre, et les nombres, on ne les balaie pas avec des mots. »',
        'Tala pensa à la nuit sur le toit. À l’homme qui n’avait pas regardé sous la paille.',
        '« Qui peut consulter ces tablettes ? »',
        '« Pas nous. »',
        '« Qui alors ? »',
        'Yidir se tut un instant.',
        '« Mon maître », dit-il. « Il fournit le fer pour les serrures de la maison de ville. Il y entre sans que personne demande pourquoi. »',
        '« Demande-lui, alors. »',
        '« Ce n’est pas quelqu’un qui va se mêler des affaires de l’intendant. »',
        '« Demande-lui », répéta Tala.',
        'Yidir regarda ses mains noires.',
        '« D’accord », dit-il. « Mais pas ce soir. Ce soir c’est le vendredi du marché et il est de mauvaise humeur. »',
        'Malgré tout, Tala dut rire.',
        'C’était la première fois depuis des jours.'] },
      { titel: 'Ce qui était écrit sur la cire', tekst: [
        'Le forgeron s’appelait Amanar et c’était le plus grand homme que Tala ait jamais vu de près.',
        'Pendant deux jours il ne dit rien. Puis, le troisième matin, il arriva dans la rue des Colonnes avec un paquet sous le bras, et il s’assit sur le pas de la réserve comme si c’était normal.',
        '« Tu es la fille de Yuba », dit-il.',
        '« Oui. »',
        '« Ton père a donné à ma mère de l’huile pendant tout un hiver sans se faire payer. » Amanar regarda la rue. « C’était il y a seize ans. Moi je ne l’ai pas oublié et lui ne se souvient plus de l’avoir fait. »',
        'Il posa le paquet sur la marche.',
        'C’étaient deux tablettes de cire, dans un cadre de bois, griffure sur griffure sur griffure.',
        '« Tu peux regarder », dit Amanar. « Pas emporter. Dans une heure elles sont revenues à leur place. »',
        'Tala s’assit et lut.',
        'Elle savait lire. Pas couramment, mais assez. Son père y avait tenu : « Celui qui ne sait pas lire croit ce qu’un autre lui dit qui est écrit. »',
        'Sur la cire il y avait des lignes. Date, porte, quoi, combien, à qui.',
        'Elle chercha son propre nom. Elle le trouva onze fois.',
        '*Yuba, pressier, rue des Colonnes. Huit jarres.*',
        '*Yuba, pressier. Douze jarres.*',
        '*Yuba, pressier. Neuf jarres.*',
        'Tala additionna. Elle compta deux fois, et la deuxième fois elle l’écrivit dans le sable à côté de ses pieds.',
        'Cent dix-sept jarres. En quatre semaines, sorties par la porte, au nom de son père.',
        'Elle leva les yeux.',
        '« Ça ne va pas », dit-elle.',
        '« Non ? » dit Amanar.',
        '« On en a fait cent soixante cette saison. Je le sais exactement, je les ai comptées à la cuisson. Soixante ont été vendues en ville. Il y en avait cent dans la réserve. » Elle montra le sable. « Cent soixante. Pas cent soixante-dix-sept. »',
        'Amanar ne dit rien.',
        '« Dix-sept jarres sont sorties par la porte alors que nous ne les avons jamais faites », dit Tala. « À notre nom. »',
        'Elle entendit elle-même ce que cela voulait dire, en le disant.',
        'Ce n’étaient pas seulement leurs jarres qu’on volait.',
        'C’était leur nom.',
        'Quand on compterait à la maison de ville, et qu’il arriverait moins que ce qui était sorti par la porte, il y aurait une maison où la piste s’arrêtait. Et cette maison serait la leur.',
        '« Amanar », dit-elle, et sa voix sonnait bizarrement. « Ils sont en train de nous préparer. »',
        'Le forgeron se leva et épousseta ses genoux.',
        '« Oui », dit-il. « C’est ce qu’ils font. »',
        'Il reprit les tablettes.',
        '« Viens demain sur la place avec ta mère. Et apporte ce sable — non : recopie-le sur quelque chose qui ne s’envole pas. »'] },
      { titel: 'Deux nombres côte à côte', tekst: [
        'Le conseil siégeait comme toujours : cinq hommes, un scribe, et le brouhaha des gens qui attendaient que ce soit leur tour.',
        'Cette fois, Tala n’était pas seule.',
        'À sa gauche se tenait sa mère, dans la robe qu’elle ne mettait que quand il arrivait quelque chose de grave ou quelque chose de beau. À sa droite se tenait Amanar, et derrière Amanar quatre hommes de la forge qui n’avaient rien à voir là-dedans et qui étaient venus quand même.',
        'Plus loin, contre une colonne, se tenait Yidir.',
        'Le plus vieux du conseil — celui au visage de figue sèche — regarda le groupe et haussa les sourcils.',
        '« Encore toi », dit-il à Tala.',
        '« J’ai compté », dit Tala.',
        'Elle l’avait écrit sur un morceau de cuir, parce que le cuir ne s’envole pas. Elle lut à voix haute. Ce qu’ils avaient fabriqué. Ce qui avait été vendu en ville. Ce qu’il y avait dans la réserve. Et ensuite ce qui, d’après les tablettes de la porte, était sorti de la ville au nom de son père.',
        'Deux nombres.',
        'Quand elle eut fini, le silence fut d’une autre sorte que la fois précédente.',
        'Marcus s’avança. Il était toujours calme, mais plus de la même façon.',
        '« Une enfant a regardé dans les tablettes de la ville », dit-il. « C’est interdit. »',
        '« C’est moi qui les ai apportées », dit Amanar.',
        'Le silence se fit plus épais encore.',
        'Le plus vieux du conseil se tourna vers le scribe à côté de lui.',
        '« Va les chercher. »',
        'Ce fut long. Personne ne partit. Quelqu’un apporta un tabouret à la mère de Tala et elle ne s’assit pas dessus.',
        'Quand les tablettes furent là, le scribe lut à voix haute ce qui y était écrit, et un autre homme additionna avec des cailloux sur une planche, et toute la place l’entendit.',
        'Cent dix-sept.',
        'Le plus vieux regarda longuement les nombres, puis Marcus, puis de nouveau les nombres.',
        '« Qui écrit à la porte nord ? » demanda-t-il.',
        '« Ça change », dit Marcus.',
        '« Qui désigne celui qui écrit ? »',
        'Marcus ne répondit pas.',
        'Le plus vieux soupira, et c’était le soupir d’un homme qui comprend quelque chose qu’il aurait préféré ne pas comprendre, et qui sait qu’il va devoir en faire quelque chose.',
        '« Assieds-toi », dit-il à Tala. « Pas toi, Marcus. Toi, tu restes debout. »'] },
      { titel: 'Ce qui reste', tekst: [
        'Il fallut encore trois semaines avant que quelque chose change vraiment, et ce fut la plus longue leçon de cet été-là : la vérité ne fonctionne pas comme dans une histoire, où tu la dis et où tout le monde hoche la tête.',
        'Un homme vint de la ville dont dépendait Volubilis pour vérifier les registres. Des gens furent entendus. Deux fois on ne dit rien, et une fois on dit quelque chose que personne n’attendait : le garde de la porte nord, un garçon de dix-neuf ans, craqua à la troisième question et raconta tout.',
        'Marcus disparut avant la fin. Sa maison resta vide un mois, puis fut donnée à quelqu’un d’autre.',
        'Le père de Tala ne guérit pas, pas tout à fait. À l’automne il put de nouveau s’asseoir dans la cour et écouter le pressoir craquer, et cela semblait lui suffire. Il demanda les chiffres et elle les lui donna. Il lui fit raconter trois fois ce qui s’était passé sur la place, et la troisième fois il pleura, et elle ne l’avait jamais vu faire ça.',
        'La récolte partit au port. Cent jarres. Le compte était bon.',
        'La semaine suivante, Yidir passa avec sa grand-mère.',
        'Sa grand-mère était petite et vieille et elle avait les yeux de quelqu’un qui regarde bien plus loin que là où elle se trouve. Elle dit qu’elle s’en allait : elle retournait dans sa famille, vers les pâturages des montagnes, avant l’hiver. Elle le dit comme s’il s’agissait d’une promenade.',
        '« Yidir vient avec moi », dit-elle. « Un temps. »',
        'Tala regarda Yidir. Yidir regarda ses mains.',
        '« C’est long, un temps ? » demanda-t-elle.',
        '« Ça, on ne le sait qu’après », dit sa grand-mère.',
        'Ce soir-là, Tala fit passer le cordon par-dessus sa tête.',
        'La clé était tiède, comme toujours. Huit branches dans la tête, une étoile. Son grand-père l’avait forgée dans une forge qui n’existait plus.',
        'Elle la tint dans sa main et pensa à ce que son père avait dit. *Cette porte ne s’ouvre pour rien d’autre.*',
        'Elle la donna à Yidir.',
        '« Ce n’est pas possible », dit-il aussitôt.',
        '« Tu m’as crue quand personne ne me croyait. »',
        '« Ça ne vaut pas une clé. »',
        '« C’est ma clé », dit Tala. « C’est moi qui décide ce qu’elle vaut. »',
        'Yidir la tenait comme si elle était brûlante.',
        '« Qu’est-ce que j’en fais ? »',
        '« Je ne sais pas », dit Tala. « La donner, je crois. À quelqu’un que tu crois. »',
        'Ils partirent le lendemain matin, avec trois ânes et un chien, vers les collines, et Tala monta sur le toit des thermes pour les suivre du regard jusqu’à ce qu’on ne les voie plus.',
        'Elle ne savait pas encore que c’était une bonne chose que la clé s’en aille.',
        'Car Walili ne serait pas toujours là. Le tremblement de terre vint bien plus tard, et la ville fut lentement vidée — pierre après pierre, jusqu’à ce qu’il ne reste que les colonnes, les pressoirs à olives et les sols en mosaïque qui y sont encore aujourd’hui, à ciel ouvert, près de Meknès.',
        'Tout ce qu’il y avait dans les maisons a disparu.',
        'Sauf la clé.'] },
    ],
  },
}
