import type { SleutelVertaling } from './sleutels-talen'

/**
 * De sleutels van Marokko in het Spaans.
 *
 * Wordt deel voor deel vertaald. Wat hier staat is af; de rest valt terug op
 * het Nederlands tot het zover is.
 *
 * De dialoog staat tussen Spaanse aanhalingstekens («…»). Dat is een keuze:
 * het Nederlands zet de dialoog midden in de alinea, en met gedachtestreepjes
 * — de gewoonte in een Spaanse roman — zou elke zin een eigen regel vragen en
 * viel het tempo van het origineel weg.
 */
export const ES_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'El incendio de las aceitunas',
    jaar: '± 200',
    waar: 'Walili (Volubilis), al pie del Zerhoun',
    verteller: 'Tala, once años, hija de un maestro de almazara que ha caído enfermo',
    flap: 'Tala tiene la llave del almacén y el capataz la quiere. Cuando el aceite de toda la ciudad corre peligro, ha de elegir entre obedecer y tener razón.',
    sleutel: 'La llave la forja en Walili el abuelo de Tala y al final se va con una caravana amazigh hacia las colinas.',
    echt: [
      'Volubilis — en árabe Walili — fue una ciudad romana de verdad, cerca de Mequinez, con miles de habitantes, termas y calles de piedra.',
      'La ciudad vivía del aceite de oliva. Se han excavado decenas de prensas, y funcionaban según la misma idea que las prensas que todavía hoy se usan en Marruecos.',
      'Los suelos estaban llenos de mosaicos. Una parte sigue allí, al aire libre.',
      'La población era en su mayoría amazigh; la vida romana y la amazigh se entrelazaban aquí.',
    ],
    verzonnen: [
      'Tala, su familia y el capataz Marco no existieron.',
      'El incendio de la historia es inventado. No hay pruebas de un gran incendio en Walili en esta época.',
      'La llave de la estrella de ocho puntas es inventada. El khatam de ocho puntas sí es un motivo marroquí real y antiquísimo.',
    ],
    hoofdstukken: [
      { titel: 'La llave', tekst: [
        'A Tala la despertó el olor.',
        'Aceitunas. Aceitunas prensadas, calientes y amargas. En estas semanas la ciudad entera olía así. Se quedó quieta un momento y escuchó. Fuera ya crujía la prensa grande. Eso quería decir que llegaba tarde.',
        'Saltó de la cama y se pasó el vestido por la cabeza.',
        '«¡Tala!», gritó su madre desde abajo. «¡La puerta!»',
        'La puerta. Cómo no, la puerta.',
        'Desde que su padre había caído enfermo, Tala hacía su trabajo. Cada mañana iba al almacén detrás de la casa y abría la puerta. Allí estaban las tinajas. Cien tinajas, llenas hasta el borde de aceite, listas para ir al puerto.',
        'La llave colgaba de un cordón a su cuello. Era de bronce y larga como su mano. Su abuelo la había forjado mucho antes de que ella existiera. En la cabeza tenía ocho puntas, como una estrella.',
        '«No la pierdas», le había dicho su padre. Lo había dicho bajito, porque más alto ya no podía. «Esa puerta no se abre con ninguna otra cosa.»',
        'Tala bajó corriendo la escalera, pasó la cocina, cruzó el patio. Todavía era temprano. El sol acababa de asomar por encima de las colinas y las piedras estaban frías bajo sus pies.',
        'Junto al almacén había un hombre.',
        'Se paró en seco.',
        'Era grande y llevaba el manto rojo del capataz. Marco. Todo el mundo en Walili conocía a Marco, y a nadie le caía bien.',
        '«Llegas tarde», dijo él.',
        '«Llego a tiempo», dijo Tala.',
        'Sabía que no debería haber dicho eso. Lo dijo igual.',
        'Marco la miró. Después alargó la mano.',
        '«Dame esa llave. Una niña no tiene por qué guardar cien tinajas.»',
        'Tala dio un paso atrás.',
        'En su cabeza oía a su padre. *Esa puerta no se abre con ninguna otra cosa.* Y pensó en otra cosa, algo que había visto ayer y que había creído que no era nada.',
        'Dos tinajas que no estaban en su sitio.',
        '«¿Y bien?», dijo Marco.',
        'Tala cerró la mano alrededor del bronce. Se había entibiado con su piel.',
        '«No», dijo.',
      ] },
      { titel: 'Dos tinajas', tekst: [
        'Marco no se rió. Tampoco se enfadó. Eso fue lo peor.',
        'Bajó la mano, se estiró el manto y dijo: «Como quieras.» Después se fue, callejón abajo, sin volver la vista.',
        'Tala se quedó de pie hasta que dejó de oír sus pasos. Solo entonces notó que le temblaban las manos.',
        'Abrió la puerta.',
        'Dentro estaba oscuro y fresco. Las tinajas estaban en filas de diez, con paja entre ellas para que no chocaran. Diez filas de diez. Cada mañana las contaba. Se lo había enseñado su padre cuando ella tenía seis años, y entonces todavía era un juego.',
        'Empezó por la izquierda y contó en voz alta, como siempre.',
        'En la última fila se detuvo.',
        'Había nueve.',
        'Tala contó otra vez. Nueve. Rodeó la fila, se agachó, miró detrás de la paja. Nueve.',
        'Ayer también había visto algo raro. Dos tinajas mal puestas, con las asas hacia la pared en vez de hacia el pasillo. Había pensado: alguien lo ha hecho con prisa. Las había enderezado y no había vuelto a pensar en ello.',
        'Ahora había una menos.',
        'Se sentó en el umbral con la espalda contra la jamba y las rodillas recogidas, y trató de pensar qué hacer.',
        'Podía contárselo a su madre. Pero su madre ya tenía bastante este mes: un marido enfermo arriba, una casa llena de gente a la que había que pagar, y una cosecha que dentro de tres semanas tenía que ir al puerto.',
        'Podía contárselo a Marco. Marco era el capataz. Ese era su trabajo.',
        'Tala miró hacia el callejón por donde él había desaparecido.',
        'No.',
        '«Estás estorbando», dijo una voz.',
        'Se sobresaltó. Delante de ella había un chico más o menos de su edad, con un delantal de cuero y los brazos llenos de haces de leña. Tenía las manos negras.',
        '«No estoy estorbando», dijo Tala. «Esta es mi puerta.»',
        '«Entonces estorbas tu propia puerta.»',
        'Se llamaba Yidir y trabajaba en la herrería del final de la calle. Tala lo conocía de vista como se conoce de vista a todo el mundo en Walili, y nada más.',
        'Se levantó para dejarlo pasar. Él no pasó.',
        '«Cuentas todas las mañanas», dijo.',
        '«¿Y tú cómo lo sabes?»',
        '«Paso por aquí todas las mañanas.»',
        'Tala dudó. Después lo dijo igualmente, porque tenía que salir y porque él estaba allí.',
        '«Falta una.»',
        'Yidir dejó los haces en el suelo.',
        '«¿Una?», dijo. «Pues has tenido suerte. A nosotros nos faltan seis barras de hierro.»',
      ] },
      { titel: 'Cómo se hace el aceite', tekst: [
        'Aquella tarde Tala estaba junto a la prensa, como cada día de la cosecha.',
        'La prensa era una piedra ahuecada del tamaño de un carro, con otra piedra redonda dentro que un burro hacía girar. Las aceitunas entraban, se machacaban, y lo que salía era una masa espesa y parda que no se parecía a nada.',
        'Esa era la parte que siempre decepcionaba a los forasteros. «¿Eso es aceite?», preguntaban. No. Eso era el principio.',
        'La masa iba a esteras redondas de junco trenzado. Esas esteras se apilaban bajo la prensa de viga, y entonces dos hombres daban vueltas al husillo, despacio, como si tuvieran todo el tiempo del mundo. Bajo la pila corría un canalillo.',
        'De ahí salía.',
        'Primero agua, turbia y sucia. Después, al cabo de un rato, otra cosa. Algo que se quedaba flotando sobre el agua y era más verde que nada que Tala conociera.',
        'La primera vez su padre la había cogido por el cuello y le había puesto la cabeza encima. «Huele», había dicho. «Eso es. Si huele así, está bien. Si no huele a nada, has esperado demasiado.»',
        'Ella había mentido entonces diciendo que lo olía. Ahora lo olía de verdad.',
        'Walili vivía de esto. No de los suelos de mosaico por los que caminaban los visitantes, ni de las columnas de la plaza, ni de las calles de piedra. De esto. De aceitunas prensadas que iban a tinajas, en carros hacia la costa, y en barcos hacia lugares de los que Tala solo conocía el nombre.',
        'Vigilaba el canalillo y las esteras y el burro, y mientras tanto pensaba en noventa y nueve tinajas.',
        'Seis barras de hierro, había dicho Yidir. De la herrería.',
        'El hierro era caro. El aceite era caro. Y los dos salían de la ciudad en la misma dirección: por el camino del puerto.',
        '«Tala.» Uno de los hombres señaló el canalillo. «Se desborda.»',
        'Se lanzó hacia delante y metió el cuenco debajo, tarde. Un chorro de aceite corrió por la piedra y desapareció entre las juntas.',
        'Un dedo de grueso, puede que dos. Suficiente para una familia durante una semana.',
        'El hombre no dijo nada. Eso lo hizo peor.',
      ] },
      { titel: 'Lo que puede un capataz', tekst: [
        'Marco volvió al tercer día, y no vino solo.',
        'Tala lo vio entrar en el patio con dos hombres detrás. Su madre salió, se secó las manos en el vestido y se plantó justo entre él y la puerta.',
        '«Paz», dijo Marco.',
        '«Paz», dijo su madre, en el tono en que se dice eso cuando no se dice en serio.',
        '«Tu marido está enfermo.»',
        '«Mi marido descansa.»',
        '«Tres semanas», dijo Marco. «Dentro de tres semanas la cosecha va al puerto, y la ciudad cuenta con lo que hay en esta casa. Tengo que saber que está.»',
        '«Está.»',
        '«Quiero verlo.»',
        'Se hizo un silencio. Tala estaba en la puerta de la cocina y no se atrevía a moverse.',
        'Su madre dijo: «Puedes mirar. Abre mi hija.»',
        'Tala cruzó el patio bajo la mirada de cinco personas. Se pasó el cordón por encima de la cabeza, metió la llave en la cerradura y empujó la puerta.',
        'Marco entró. Recorrió las filas, despacio, con las manos a la espalda. En la última fila se detuvo.',
        'Tala contuvo la respiración.',
        '«Noventa y nueve», dijo Marco.',
        'Se dio la vuelta y miró a su madre.',
        '«Deberían ser cien.»',
        'Su madre se puso rígida. Tala lo vio en sus hombros.',
        '«Entonces se ha roto una», dijo ella.',
        '«Entonces habría cascos.» Marco abrió las manos. «No veo cascos. Veo paja que alguien ha vuelto a estirar.»',
        'Esperó un momento, exactamente lo justo.',
        '«No digo que robéis», dijo entonces. «Digo que una niña de once años tiene la llave de cien tinajas, y que hoy hay noventa y nueve. Eso digo. Y eso diré también en la plaza.»',
        'Salió por la puerta y pasó junto a Tala como si ella fuera un poste.',
        'Cuando se hubo ido, su madre se sentó en el brocal del pozo. Estuvo muchísimo rato sin decir nada.',
        '«Mamá», dijo Tala. «Yo no la he…»',
        '«Lo sé.»',
        '«Las conté el lunes y entonces todavía eran…»',
        '«Tala.» Su madre levantó la vista. Tenía los ojos rojos. «Lo sé. Y eso no nos sirve de nada.»',
      ] },
      { titel: 'La herrería', tekst: [
        'Yidir estaba sentado en un cubo del revés delante de la herrería, lijando un gozne.',
        '«Tenías razón», dijo Tala.',
        '«Eso me lo dice poca gente», dijo Yidir sin levantar la vista. «¿En qué?»',
        '«En que no era una sola tinaja.»',
        'Ahora sí levantó la vista.',
        'Tala se sentó a su lado en el umbral y se lo contó. Lo de Marco, lo de noventa y nueve, lo que él iba a decir en la plaza. Yidir escuchó como hacía todo: como si mientras tanto estuviera pensando en otra cosa, pero no se le escapaba nada.',
        '«¿Y vuestro hierro?», preguntó ella.',
        '«Seis barras. Mi maestro cree que se ha equivocado al contar.» Yidir se encogió de hombros. «Mi maestro no se equivoca nunca al contar.»',
        '«¿Cuándo?»',
        '«La semana pasada. Y la anterior tres.»',
        'Tala recogió las rodillas.',
        '«¿Qué sale de la ciudad?», preguntó. «Cada día, quiero decir.»',
        'Yidir se lo pensó.',
        '«Carros», dijo. «Aceite, grano, pieles, hierro. Todo va por el camino del norte. Hay un puesto de guardia en la puerta. Allí se anota todo.»',
        '«¿Quién lo anota?»',
        'Yidir la miró.',
        '«El capataz», dijo.',
        'Los dos se quedaron callados un rato.',
        '«Eso no demuestra nada», dijo Tala al final.',
        '«No.»',
        '«Si lo digo, dirán que una niña de once años acusa a un hombre porque no le cae bien.»',
        '«Sí», dijo Yidir. «Eso dirán.»',
        'Dejó el gozne a un lado.',
        '«Así que necesitas algo que no puedan quitarte con palabras.»',
        '«¿Como qué?»',
        '«Como ver qué sale de noche por esa puerta.»',
        'Tala lo miró. Él le devolvió la mirada, y por primera vez desde que lo conocía, se rió.',
      ] },
      { titel: 'Lo que pasa de noche por la puerta', tekst: [
        'Estaban tumbados en el tejado de las termas, boca abajo, con la barbilla sobre los brazos.',
        'El tejado estaba caliente del día. Debajo de ellos quedaba la calle que iba a la puerta del norte, lo bastante ancha para dos carros uno al lado del otro. Junto a la puerta ardía una lámpara.',
        '«¿Cuánto falta?», susurró Tala.',
        '«No lo sé.»',
        '«Dijiste que de noche pasan carros.»',
        '«Dije que *creía* que de noche pasan carros.»',
        'Tala suspiró y apoyó la cabeza en el brazo.',
        'Aquella noche las estrellas eran increíbles. En la ciudad se veían a medias, por la luz y el humo, pero aquí arriba había tantas que daba inquietud.',
        '«Mi abuela dice que son un mapa», dijo Yidir.',
        '«¿Las estrellas?»',
        '«Sí. Si sabes leerlas, puedes llegar a cualquier parte. Dice que su familia llegó así desde el desierto hasta aquí.»',
        '«¿Tú sabes leerlas?»',
        '«No», dijo Yidir. «Nadie me lo ha enseñado.»',
        'Entonces lo oyeron.',
        'Un carro. No dos burros, no caballos — un burro, despacio, y el ruido de la madera que cruje bajo un peso.',
        'Tala se arrastró hasta el borde.',
        'El carro venía de una bocacalle. A su lado iban dos hombres, los dos con un paño en la cabeza. Sobre el carro había paja, y bajo la paja algo redondo.',
        'En la puerta el carro se detuvo.',
        'De la garita salió un hombre con una lámpara. No se acercó al carro. Se acercó a los hombres, habló brevemente con ellos y anotó algo en una tablilla.',
        'Después levantó la barrera.',
        'El carro se metió en la noche.',
        'Tala soltó el aire. No se había dado cuenta de que lo estaba aguantando.',
        '«No ha mirado», dijo. «No ha mirado debajo de la paja.»',
        '«No.»',
        '«Eso es…»',
        '«Eso sigue sin ser nada», dijo Yidir. «Eso es un hombre que no mira lo bastante bien. Por eso no cuelgan a nadie.»',
        'Tenía razón, y Tala también lo sabía.',
        'Pero cuando el carro tomó la curva, pasó algo. El burro se asustó de algo en la oscuridad, se echó a un lado, y el carro pasó con una rueda por encima del bordillo.',
        'Algo se cayó del carro.',
        'Rodó, se paró contra el muro y se quedó allí.',
        'Una tinaja.',
        'Uno de los hombres soltó un juramento, volvió sobre sus pasos, la recogió y la puso otra vez bajo la paja. El carro siguió.',
        'Pero Tala había visto lo que llevaba.',
        'En el hombro de cada tinaja de su casa su padre marcaba un signo en la arcilla antes de que se cociera. Ocho puntas. Una estrella.',
        'Agarró el brazo de Yidir tan fuerte que él siseó.',
        '«Esa es nuestra», dijo.',
      ] },
      { titel: 'Lo que dices y lo que oyen', tekst: [
        'A la mañana siguiente Tala fue a la plaza.',
        'Se lo había pensado toda la noche, o por lo menos la mitad; la otra mitad la había dormido sin querer. Sabía lo que iba a decir. Lo había ensayado tres veces contra la pared de su cuarto.',
        'En la plaza, bajo las columnas, el consejo celebraba sesión. Eso quería decir: cinco hombres en bancos de piedra, un escribano al lado, y alrededor todo el que tuviera una queja.',
        'Marco ya estaba allí.',
        'Tala esperó a que un hombre terminara de hablar sobre un muro y un vecino. Después dio un paso al frente.',
        '«Quiero decir algo», dijo.',
        'Cinco hombres levantaron la vista. Uno de ellos, el más viejo, con una cara como un higo seco, se inclinó hacia delante.',
        '«¿De quién eres tú?»',
        '«De Yuba, el de la almazara. De la calle de las Columnas.»',
        '«Ese está enfermo.»',
        '«Sí», dijo Tala. «Por eso estoy aquí.»',
        'Lo contó. La tinaja que faltaba, y al día siguiente otra. El carro en la noche y el hombre que levantó la barrera sin mirar bajo la paja. La tinaja que se cayó y el signo de las ocho puntas.',
        'Lo contó exactamente como lo había ensayado, y mientras lo hacía, también se oyó a sí misma.',
        'Oyó cómo sonaba.',
        'Una niña. Un tejado. La oscuridad. Un signo que nadie más había visto.',
        'Cuando terminó, hubo un silencio. Entonces Marco dijo, muy tranquilo: «¿Puedo?»',
        'El más viejo asintió.',
        '«La niña tiene razón en que faltan tinajas», dijo Marco. «Lo conté yo mismo, anteayer, en su propio almacén. Noventa y nueve de cien. Ya lo dije entonces.»',
        'Abrió las manos, como hacía él.',
        '«¿Quién tiene la llave de esa puerta?»',
        'Nadie dijo nada.',
        '«Ella», dijo Marco. «Una niña de once años. Y ahora que falta una, ha sido un carro en la noche. Un carro que solo ha visto ella.»',
        'El más viejo del consejo miró a Tala, y su mirada no era antipática. Eso era lo peor.',
        '«Niña», dijo. «Vete a casa. Cuida de tu padre.»',
        'Tala se quedó en la plaza con los brazos pegados al cuerpo y las orejas ardiendo, y a su alrededor todos volvieron a hablar de un muro y un vecino.',
      ] },
      { titel: 'El incendio', tekst: [
        'El incendio empezó cuatro días después, y no empezó en su casa.',
        'A Tala la despertó. No la luz ni los gritos — el sonido. Un rugido hondo y suave, como si muy cerca alguien estuviera soltando el aire durante muchísimo rato.',
        'Estaba en la ventana antes de estar despierta.',
        'Al otro lado de la calle, dos casas más allá, ardía el almacén de Quinto. Quinto también prensaba aceite. Sus tinajas estaban en un espacio bajo su casa, y de allí salía ahora fuego por la ventana, plano, y no hacia arriba como debe hacer el fuego.',
        'Eso es por el aceite, lo supo Tala más tarde. El aceite arde de otra manera.',
        'Ya había gritos. Ya había gente en la calle con cubos y mantas, y alguien golpeaba con un palo la plancha de bronce junto al pozo, y Tala bajó corriendo la escalera descalza.',
        'Su madre la agarró del brazo en la puerta.',
        '«Por ahí no.»',
        '«Pero…»',
        '«Tala.» Su madre la sujetó con las dos manos. «Nuestra puerta. Ya.»',
        'Y Tala lo entendió.',
        'Si se propaga, viene hacia ellos. Cien tinajas — noventa y nueve — de aceite, detrás de una puerta de madera, contra el mismo muro.',
        'Corrió al almacén, se pasó el cordón por encima de la cabeza y metió la llave en la cerradura. Tenía las manos tan mojadas que el bronce se le escurría. A la tercera lo consiguió.',
        'La puerta se abrió. El frescor le salió al encuentro, y el olor.',
        'Detrás de ella la calle entera empezó a cargar tinajas.',
        'Las llevaron al patio, al pozo, a la calle, a todas partes donde no hubiera un muro ardiendo. Los vecinos cargaron con ellos, gente a la que apenas conocía, gente con la que su padre nunca había hablado. Alguien trajo una escalera. Alguien echaba mantas al agua del pozo y las iba pasando.',
        'Tala cargó hasta que los brazos ya no quisieron y entonces cargó más.',
        'En la tinaja número setenta vio a Yidir. Vino con otros cuatro de la herrería y arrastraban algo que parecía un gancho largo.',
        'En la ochenta y cinco se hundió el tejado del almacén de Quinto.',
        'Con la última ya estaba saliendo el sol.',
        'Para entonces ya no había fuego. Solo había humo que colgaba bajo sobre la calle, y doscientas personas que miraban sin decir nada, y manos negras, y en alguna parte un niño que lloraba.',
        'Tala estaba sentada en el escalón, apoyada en su madre.',
        'Y por eso fue la única que vio al hombre que salía del callejón junto a la casa de Quinto, a contracorriente, con el manto sobre el brazo en vez de sobre los hombros.',
        'El manto era rojo.',
      ] },
      { titel: 'El manto rojo', tekst: [
        'Se lo contó a Yidir antes que a nadie.',
        'Él la escuchó sin interrumpirla, y cuando terminó dijo: «Eso sigue sin ser nada.»',
        '«Lo he visto.»',
        '«Has visto a un hombre con un manto rojo en una calle llena de gente con hollín en la cara.» Yidir dio una patada a una piedra. «Yo te creo. El consejo no.»',
        'Tala sabía que tenía razón y estaba harta de que siempre la tuviera.',
        '«¿Entonces qué?», dijo. «No puedo no hacer nada.»',
        '«No», dijo Yidir. «Pero necesitas algo que no venga de ti.»',
        'Se sentó en el brocal del pozo, con los talones contra la piedra.',
        '«En la puerta lo anotan todo», dijo. «En cera. Lo que sale, cuánto, y de quién. Esas tablillas van cada mes a la casa de la ciudad.»',
        '«¿Y si no hay nada raro?»',
        '«Entonces no hay nada raro», dijo Yidir. «Y entonces sabes que no está en los libros, sino en la oscuridad. Eso también es algo.»',
        'La miró.',
        '«Pero si sí hay algo — si allí pone doce tinajas y por la puerta salieron trece — entonces no es una niña que ha visto algo. Entonces es un número al lado de otro número, y a los números nadie se los quita con palabras.»',
        'Tala pensó en la noche en el tejado. En el hombre que no había mirado bajo la paja.',
        '«¿Quién puede ver esas tablillas?»',
        '«Nosotros no.»',
        '«¿Quién entonces?»',
        'Yidir calló un momento.',
        '«Mi maestro», dijo. «Él entrega el hierro para las cerraduras de la casa de la ciudad. Entra allí sin que nadie pregunte por qué.»',
        '«Pues pídeselo.»',
        '«No es hombre de meterse con el capataz.»',
        '«Pídeselo», dijo Tala otra vez.',
        'Yidir se miró las manos negras.',
        '«Está bien», dijo. «Pero esta noche no. Esta noche es el viernes del mercado y está de mal humor.»',
        'A pesar de todo, Tala tuvo que reírse.',
        'Era la primera vez en días.',
      ] },
      { titel: 'Lo que ponía en la cera', tekst: [
        'El herrero se llamaba Amanar y era el hombre más grande que Tala había visto nunca de cerca.',
        'Durante dos días no dijo nada. Entonces, la tercera mañana, apareció por la calle de las Columnas con un paquete bajo el brazo, y se sentó en el escalón del almacén como si le correspondiera.',
        '«Tú eres la hija de Yuba», dijo.',
        '«Sí.»',
        '«Tu padre le dio a mi madre aceite durante todo un invierno sin cobrarle nada.» Amanar miró calle abajo. «Fue hace dieciséis años. Yo no lo he olvidado y él ya no se acuerda de haberlo hecho.»',
        'Dejó el paquete en el escalón.',
        'Eran dos tablillas de cera, en un marquito de madera, con raya sobre raya sobre raya.',
        '«Mirar, sí», dijo Amanar. «Llevárselas, no. Dentro de una hora están otra vez donde deben estar.»',
        'Tala se sentó y leyó.',
        'Sabía leer. No con soltura, pero lo suficiente. Su padre se había empeñado: «Quien no sabe leer, se cree lo que otro dice que pone.»',
        'En la cera había filas. Fecha, puerta, qué, cuánto, de quién.',
        'Buscó su propio apellido. Lo encontró once veces.',
        '*Yuba, almazara, calle de las Columnas. Ocho tinajas.*',
        '*Yuba, almazara. Doce tinajas.*',
        '*Yuba, almazara. Nueve tinajas.*',
        'Tala las sumó. Sumó dos veces y la segunda vez lo escribió en la arena junto a sus pies.',
        'Ciento diecisiete tinajas. En cuatro semanas, fuera de la ciudad, a nombre de su padre.',
        'Levantó la vista.',
        '«Eso no cuadra», dijo.',
        '«¿No?», dijo Amanar.',
        '«Esta temporada hemos hecho ciento sesenta. Lo sé exactamente, las conté cuando se cocieron. Se han vendido sesenta en la ciudad. Había cien en el almacén.» Señaló la arena. «Ciento sesenta. No ciento setenta y siete.»',
        'Amanar no dijo nada.',
        '«Han salido diecisiete tinajas por la puerta que nosotros no hemos hecho nunca», dijo Tala. «A nuestro nombre.»',
        'Oyó ella misma lo que eso significaba, mientras lo decía.',
        'No eran solo sus tinajas lo que estaban robando.',
        'Era su nombre.',
        'Cuando dentro de poco se contara en la casa de la ciudad, y entrara menos de lo que había salido por la puerta, habría una sola casa donde acababa el rastro. Y esa casa era la suya.',
        '«Amanar», dijo, y la voz le salió rara. «Nos están preparando.»',
        'El herrero se levantó y se sacudió el polvo de las rodillas.',
        '«Sí», dijo. «Eso están haciendo.»',
        'Recogió las tablillas.',
        '«Ven mañana a la plaza con tu madre. Y trae esa arena, o mejor — cópialo en algo que no se vuele.»',
      ] },
      { titel: 'Dos números uno al lado del otro', tekst: [
        'El consejo celebraba sesión como siempre: cinco hombres, un escribano, y el murmullo de la gente que esperaba a que le tocara.',
        'Esta vez Tala no estaba sola.',
        'A su izquierda estaba su madre, con el vestido que solo se ponía cuando había algo muy malo o algo muy bueno. A su derecha estaba Amanar, y detrás de Amanar cuatro hombres de la herrería que no tenían nada que ver y aun así estaban allí.',
        'Más allá, apoyado en una columna, estaba Yidir.',
        'El más viejo del consejo — el de la cara como un higo seco — miró al grupo y levantó las cejas.',
        '«Otra vez tú», le dijo a Tala.',
        '«He contado», dijo Tala.',
        'Lo había escrito en un trozo de cuero, porque el cuero no se vuela. Lo leyó en voz alta. Lo que habían hecho. Lo que se había vendido en la ciudad. Lo que había en el almacén. Y después lo que, según las tablillas de la puerta, había salido de la ciudad a nombre de su padre.',
        'Dos números.',
        'Cuando terminó, hubo un silencio distinto del de la otra vez.',
        'Marco dio un paso al frente. Seguía tranquilo, pero ya no de la misma manera.',
        '«Una niña ha mirado en las tablillas de la ciudad», dijo. «Eso está prohibido.»',
        '«Las he traído yo», dijo Amanar.',
        'Se hizo aún más silencio.',
        'El más viejo del consejo se volvió hacia el escribano que tenía al lado.',
        '«Tráelas.»',
        'Tardó mucho. Nadie se fue. Alguien le dio un taburete a la madre de Tala y ella no se sentó.',
        'Cuando llegaron las tablillas, el escribano leyó en voz alta lo que ponía, y otro hombre fue sumando con piedras en un tablero, y toda la plaza lo oyó.',
        'Ciento diecisiete.',
        'El más viejo miró largo rato los números, y después a Marco, y después otra vez los números.',
        '«¿Quién escribe en la puerta del norte?», preguntó.',
        '«Eso va cambiando», dijo Marco.',
        '«¿Quién señala a quien escribe?»',
        'Marco no contestó.',
        'El más viejo suspiró, y fue el suspiro de un hombre que entiende algo que habría preferido no entender, y que sabe que ahora tiene que hacer algo con ello.',
        '«Siéntate», le dijo a Tala. «Tú no, Marco. Tú te quedas de pie.»',
      ] },
      { titel: 'Lo que queda', tekst: [
        'Tardaron todavía tres semanas en cambiar de verdad las cosas, y esa fue la lección más larga de aquel verano: que la verdad no funciona como en un cuento, donde la dices y todos asienten.',
        'Vino un hombre de la ciudad madre de Volubilis a revisar los libros. Se tomó declaración a varias personas. Dos veces no se dijo nada y una vez se dijo algo que nadie esperaba: el guardia de la puerta del norte, un chico de diecinueve años, se vino abajo a la tercera pregunta y lo contó todo.',
        'Marco desapareció antes de que se cerrara el asunto. Su casa estuvo un mes vacía y después se le dio a otro.',
        'El padre de Tala no se curó, no del todo. En otoño pudo volver a sentarse en el patio y oír crujir la prensa, y con eso parecía contento. Preguntaba por los números y ella se los decía. Le hizo contar tres veces lo que había pasado en la plaza, y la tercera vez lloró, y eso ella no se lo había visto hacer nunca.',
        'La cosecha fue al puerto. Cien tinajas. Cuadraba.',
        'La semana siguiente Yidir pasó por allí con su abuela.',
        'Su abuela era pequeña y vieja y tenía ojos de quien mira mucho más lejos de donde está. Dijo que se iba: de vuelta con su familia, a los pastos de las montañas, antes de que llegara el invierno. Lo dijo como si hablara de un paseo.',
        '«Yidir viene conmigo», dijo. «Una temporada.»',
        'Tala miró a Yidir. Yidir se miró las manos.',
        '«¿Cuánto es una temporada?», preguntó.',
        '«Eso solo se sabe después», dijo su abuela.',
        'Aquella tarde Tala se pasó el cordón por encima de la cabeza.',
        'La llave estaba tibia, como siempre. Ocho puntas en la cabeza, una estrella. Su abuelo la había forjado en una herrería que ya no existía.',
        'La tuvo en la mano y pensó en lo que había dicho su padre. *Esa puerta no se abre con ninguna otra cosa.*',
        'Se la dio a Yidir.',
        '«No puede ser», dijo él enseguida.',
        '«Tú me creíste cuando no me creía nadie.»',
        '«Eso no vale una llave.»',
        '«Es mi llave», dijo Tala. «Yo decido lo que vale.»',
        'Yidir la sostuvo como si quemara.',
        '«¿Y qué hago con ella?»',
        '«No lo sé», dijo Tala. «Regalarla, creo. A alguien a quien creas.»',
        'Se fueron a la mañana siguiente, con tres burros y un perro, hacia las colinas, y Tala se subió al tejado de las termas para mirarlos hasta que no se vieron.',
        'Entonces todavía no sabía que era bueno que la llave se fuera.',
        'Porque Walili no iba a estar siempre. El terremoto llegó mucho más tarde, y la ciudad se fue vaciando despacio — piedra a piedra, hasta que no quedó más que las columnas, las prensas de aceite y los suelos de mosaico que siguen allí hoy, al aire libre, cerca de Mequinez.',
        'Todo lo que había en las casas ha desaparecido.',
        'Solo la llave no.',
      ] },
    ],
  },
  2: {
    titel: 'La otra orilla',
    jaar: '711',
    waar: 'Tánger y el estrecho hacia el norte',
    verteller: 'Ayyur, doce años, hijo de un pastor de ovejas que cuida de los caballos',
    flap: 'Un ejército cruza hacia una tierra que nadie conoce. A Ayyur le dejan ir para cuidar de los caballos — y descubre que el hombre al que todos siguen también tiene miedo.',
    sleutel: 'La llave cuelga del arnés de un caballo y se queda en la otra orilla, en la bolsa de un escribano.',
    echt: [
      'Táriq ibn Ziyad fue un jefe militar amazigh que en 711 cruzó el estrecho con un ejército hacia el sur de la España actual.',
      'El peñón donde desembarcó todavía lleva su nombre: Yábal Táriq, la montaña de Táriq — deformado hasta dar Gibraltar.',
      'La mayor parte de su ejército estaba formada por soldados amazigh del norte de África.',
      'La historia de que mandó quemar sus barcos se puso por escrito siglos después y los historiadores no la consideran un hecho.',
    ],
    verzonnen: [
      'Ayyur y su familia no existieron.',
      'Las conversaciones con Táriq son inventadas. De su carácter no se sabe casi nada.',
      'Que la llave viajara con ellos es inventado.',
    ],
    hoofdstukken: [
      { titel: 'El chico de los caballos', tekst: [
        'Ayyur tenía doce años y se le daban bien dos cosas: los caballos y esperar.',
        'Lo segundo lo había aprendido de su padre, que pastoreaba ovejas en las colinas detrás de Tánger y que podía callar desde el alba hasta la puesta del sol sin que le costara nada. Lo primero no lo había aprendido de nadie. A los caballos sencillamente les caía bien, y eso era así desde que sabía andar.',
        'Por eso estaba ahora en el campamento, fuera de la muralla, y no en las colinas.',
        'Su padre había perdido en invierno treinta ovejas por el frío y el resto por la deuda. Ya no había rebaño que pastorear. Sí había un ejército, y un ejército tiene caballos, y los caballos necesitan a alguien que se quede con ellos de noche.',
        'Pagaban en comida y en cobre. No mucho cobre.',
        'Ayyur no se quejaba. Podía dormir con los caballos y a estas alturas conocía a los cuarenta y siete por su nombre, también los nombres que se había inventado él porque nadie se los había dicho.',
        'En aquellas semanas de marzo el campamento se había llenado más de lo que él había visto nunca. Primero cien hombres, luego quinientos, luego tantos que ya no se podía contar. Venían del sur y del este, de las montañas y de la costa. La mayoría eran amazigh como él. Hablaban su lengua, con otras palabras para las mismas cosas, y se reían de cómo lo decía él.',
        'También había algunos que hablaban árabe. No muchos. Unos cientos.',
        'Y todos esperaban.',
        'A qué, lo sabían: a los barcos. Para qué eran los barcos, de eso se hablaba como hablan los hombres de algo que no saben con certeza — muy rotundamente, y cada día distinto.',
        '«La otra orilla», decía uno.',
        '«No hay nada en la otra orilla», decía otro. «Agua y después más agua.»',
        '«Hay un rey en la otra orilla», decía un tercero. «Con una corona de oro tan pesada que no la puede llevar.»',
        'Ayyur cepillaba el flanco de una yegua a la que llamaba Tafukt, que quiere decir sol, y escuchaba a los tres.',
        'Él había visto la otra orilla. Todo el mundo en Tánger había visto la otra orilla. En un día claro había una franja de tierra en el horizonte, y encima un peñón que parecía que alguien lo hubiera puesto allí.',
        'Se podía mirar sin pensar nunca en ello, toda la vida.',
        'Hasta que alguien empezó a reunir barcos.',
      ] },
      { titel: 'El hombre que no era grande', tekst: [
        'Vio a Táriq por primera vez un martes, junto a los caballos, y durante medio minuto no supo a quién tenía delante.',
        'El hombre no era grande. Eso fue lo primero.',
        'Ayyur se había imaginado a alguien como en las historias: una cabeza por encima de todos, un manto que se arrastrara detrás de él, diez hombres alrededor. Este hombre estaba solo, con una casaca polvorienta sin adorno, y miraba a Tafukt como mira a un caballo alguien que entiende de caballos.',
        '«¿Quién la monta?», preguntó.',
        '«Nadie», dijo Ayyur. «No deja que nadie se le suba.»',
        '«¿Por qué no?»',
        '«No lo sé. Se cayó una vez, creo. Antes de venir aquí.»',
        'El hombre puso la mano en el cuello de la yegua y la dejó allí sin acariciarla.',
        '«¿Y contigo?»',
        '«Conmigo está tranquila.»',
        '«Entonces no tiene miedo de las personas», dijo el hombre. «Tiene miedo de lo que las personas le hicieron.»',
        'Miró a Ayyur por primera vez.',
        '«¿Cómo te llamas?»',
        '«Ayyur.»',
        '«La luna.» El hombre asintió, como si fuera un nombre razonable. «Haz que dentro de dos semanas siga igual de bien.»',
        'Después se fue.',
        'Hasta la noche nadie se lo dijo a Ayyur, y cuando lo oyó se sentó en un cajón y se quedó allí un buen rato.',
        'Táriq ibn Ziyad. Amazigh, como él. De una familia que no conocía nadie. Gobernador de Tánger, y el hombre que tenía que pasar por encima del agua al ejército que estaba tumbado en aquella playa.',
        'Había estado mirando un caballo.',
        '«Viene todos los días», dijo Sa3id, el jinete viejo de la pierna mala, que ya se había sentado a su lado porque siempre se sentaba al lado de alguien. «Todos los días a los caballos y todos los días a los barcos. Creo que no duerme.»',
        '«No es grande», dijo Ayyur.',
        'Sa3id se rió tan fuerte que le dio tos.',
        '«No, chico», dijo. «No lo es.»',
      ] },
      { titel: 'Cuatro barcos para siete mil hombres', tekst: [
        'El problema era sencillo y nadie podía resolverlo.',
        'Había siete mil hombres en aquella playa, más caballos, más armas, más comida para semanas. Y había cuatro barcos.',
        'Ayyur oyó una vez a Sa3id calcular cuántas veces tenían entonces que ir y venir esos cuatro barcos, y a Sa3id le salió un número del que él mismo se rió, y después se quedó callado.',
        '«¿Qué pasa?», preguntó Ayyur.',
        '«Nada.»',
        '«Sa3id.»',
        'El viejo se frotó la rodilla, que era lo que hacía cuando pensaba.',
        '«Si tienes cuatro barcos», dijo, «la primera carga es la más peligrosa. Esa está en la otra orilla, sola, sin nadie detrás. Y si algo sale mal, los barcos están dos días fuera.»',
        'Miró el mar.',
        '«Yo no querría estar en la primera carga.»',
        'Los barcos no eran suyos. Eso lo sabía todo el campamento. Venían de un hombre de la otra orilla, un señor de Ceuta que estaba enemistado con su propio rey y que por eso ayudaba. Su nombre se pronunciaba de diez maneras y nadie lo había visto nunca.',
        '«¿Por qué ayuda?», preguntó Ayyur.',
        '«Porque quiere algo.»',
        '«¿El qué?»',
        '«Eso solo lo sabremos cuando se lo hayamos dado», dijo Sa3id.',
        'En aquellas semanas Ayyur aprendió sobre la guerra más de lo que nunca había querido saber, y casi nada de ello iba de pelear. Iba de agua en toneles que al cuarto día se echaba a perder. De cuánta cebada come un caballo al día y cuánto es eso para setecientos caballos. De hombres que se ponían malos de esperar y se peleaban por nada.',
        'Una mañana hubo una pelea en el pozo. Dos hombres de tribus distintas, por un cubo.',
        'Táriq vino en persona. Los hizo levantarse a los dos, les habló bajito y los mandó juntos con la misma tarea: un cubo, dos hombres, todo el día acarreando agua para los caballos.',
        'Por la noche cenaban uno al lado del otro.',
        'Sa3id vio que Ayyur miraba.',
        '«*Eso* es», dijo. «*Eso* es por lo que lo siguen. No porque sepa pelear. Pelear saben todos.»',
      ] },
      { titel: 'La noche antes', tekst: [
        'La tarde antes de la primera travesía fue calurosa y no corría viento, y esto último era justamente el problema.',
        'Ayyur no podía dormir. Estaba tumbado entre los caballos, con la cabeza sobre una silla que olía a cuero y a sudor, y miraba las estrellas que se veían entre las lonas.',
        'A su lado estaba Sa3id, y él tampoco dormía.',
        '«¿Tienes miedo?», preguntó Ayyur.',
        '«Sí», dijo Sa3id enseguida.',
        'Eso Ayyur no se lo esperaba. Se esperaba que el viejo se riera y dijera algo de que había estado en veinte batallas.',
        '«El que diga que no, miente», dijo Sa3id. «O es tonto. Los hombres tontos no sirven de nada en un barco.»',
        'Se incorporó, despacio, con la mano en la rodilla.',
        '«¿Sabes lo que hago yo cuando tengo miedo?»',
        '«No.»',
        '«Digo el nombre de Dios y después hago lo siguiente que hay que hacer. No la cosa entera. Lo siguiente.»',
        'Ayyur se lo pensó.',
        'La fe era en su pueblo algo de los últimos años. Su abuela no la tenía, su madre a medias, su padre entera — a su manera, callado, sin decir mucho al respecto. En el campamento estaba por todas partes: hombres que dejaban lo que estaban haciendo y se volvían en la misma dirección, y después seguían como si no hubiera pasado nada.',
        'Él nunca lo había entendido muy bien. Nadie se lo había explicado. Sencillamente lo hacían, y él se quedaba al lado con un cepillo en la mano.',
        '«Sa3id», dijo. «No sé cómo se hace.»',
        'El viejo lo miró en la oscuridad.',
        '«¿Qué no sabes?»',
        '«Nada. Las palabras. Cuándo. Cómo hay que ponerse.»',
        'Sa3id calló lo bastante para que Ayyur se sintiera incómodo.',
        '«Mañana por la mañana», dijo entonces, «te pones a mi lado. Haces lo que hago yo. No tienes que decir nada que no sepas.»',
        '«¿Con eso basta?»',
        '«Para mañana sí», dijo Sa3id. «El resto lo aprenderás de alguien que entienda más que yo. Yo no soy más que un jinete con la rodilla rota.»',
        'Se volvió a tumbar.',
        '«Duerme ya. Mañana será largo.»',
      ] },
      { titel: 'La playa al amanecer', tekst: [
        'Bajaron al agua de noche, y cuando se hizo de día la playa entera estaba llena.',
        'Ayyur no había visto nunca a tanta gente callada a la vez.',
        'Estaban en filas, hombro con hombro, desde las dunas hasta la orilla. Hombres que no se entendían entre sí porque venían de pueblos a diez jornadas de distancia, en la misma dirección, en el mismo orden.',
        'Él estaba al lado de Sa3id e hizo lo que hacía Sa3id, y durante los tres primeros tiempos se sintió ridículo y después ya no.',
        'El mar estaba aquella mañana como un lago.',
        'Cuando terminó, siguió el silencio un momento. Después todos empezaron a hablar a la vez y aquello volvió a ser un campamento.',
        'Ayyur llevó ocho caballos hasta la orilla. Esa era su tarea: ocho, en la primera carga, con Sa3id a su lado cuando estuvieran en la otra orilla.',
        'Tafukt era uno de ellos.',
        'Los caballos y los barcos no se llevan bien. Eso él lo sabía, y aquella mañana aprendió hasta qué punto. Tenían que meter a los animales en el barco por una tabla, y la tabla se movía, y el barco se movía de otra manera que la tabla.',
        'Dos caballos se negaron. Un tercero entró en pánico a la mitad y tiró a un hombre al suelo.',
        'Tafukt subió la tabla detrás de Ayyur como si fuera un sendero de las colinas.',
        'Él le sujetó la cabeza cuando estuvo dentro, y le habló en su propia lengua de cosas que no iban de nada: de su padre, del rebaño que ya no existía, del nombre que le había puesto y por qué.',
        'Alguien le dio una palmada en el hombro.',
        'Levantó la vista.',
        'Táriq estaba en el barco, entre los caballos, con la mano en la borda.',
        '«Sigue hablándole», dijo. «Toda la travesía. No pares.»',
        '«Sí», dijo Ayyur.',
        'Táriq miró la tabla, donde todavía faltaban el cuarto y el quinto.',
        '«Y Ayyur», dijo, sin volverse. «Si sale mal en el agua, la cortas. No la sujetes. Un caballo sabe nadar. Un chico con una cuerda en el brazo no.»',
      ] },
      { titel: 'Agua', tekst: [
        'El estrecho, en su punto más angosto, mide catorce kilómetros.',
        'Ayyur no lo sabía. Solo sabía que la playa detrás de él se hacía más pequeña y que pasó una hora en la que no ocurrió nada, y después otra hora.',
        'No salió mal. Eso fue lo raro.',
        'Se lo había imaginado todo: olas, gritos, agua por encima de la borda. En su lugar hubo sol, el ruido de los remos, y un balanceo que bastaba justo para que todo el que no estuviera acostumbrado a los barcos se colgara de la regala.',
        'Le habló a Tafukt hasta quedarse ronco.',
        'Entre medias miró hacia atrás.',
        'Detrás de ellos quedaba la costa donde había nacido: las colinas por donde habían andado las ovejas, la ciudad con la muralla, el punto donde su padre estaría ahora probablemente sentado mirando sin decir nada.',
        'No se había despedido. No de verdad. Había dicho que volvería dentro de un mes, y su padre había asentido, y los dos habían hecho como si esa fuera una frase que significaba algo.',
        'Delante de él el peñón se hacía más grande.',
        'Era distinto de como se veía desde Tánger. De lejos parecía un triángulo. De cerca era un muro de piedra que salía recto del agua, gris y pelado, con gaviotas flotando a su alrededor como polvo.',
        'No había nadie encima. No había nada encima. Era simplemente un peñón.',
        'A su lado Sa3id dijo algo.',
        '«¿Qué?»',
        '«He dicho: míralo bien.» El viejo se apoyó con los brazos en la borda. «Dentro de cien años alguien le preguntará a tu nieto de dónde viene su familia, y él dirá el nombre de esta cosa.»',
        '«No tiene nombre.»',
        'Sa3id sonrió con su dentadura torcida.',
        '«Todavía no», dijo.',
        'Los barcos tocaron tierra en una playa al pie del peñón. No había nadie. Ni ejército, ni puesto de guardia, ni aldea. Solo guijarros, algas y el ruido del mar.',
        'Setecientos hombres y sesenta y dos caballos estaban en una costa extraña, y los barcos dieron la vuelta enseguida para la siguiente carga.',
        'Dos días solos, había dicho Sa3id.',
        'Ayyur subió los caballos más arriba, a la hierba detrás de los guijarros, y empezó a trazar una línea en la arena para el cercado. Lo siguiente que había que hacer.',
        'Detrás de él Táriq subió la primera ladera para ver cómo era aquella tierra.',
      ] },
      { titel: 'Dos días solos', tekst: [
        'La primera noche en la otra orilla no durmió nadie.',
        'No fue por el miedo, aunque también estaba. Fue porque setecientos hombres que acaban de bajar de un barco piensan todos a la vez que tienen que hacer algo, y no hay nadie que sepa qué.',
        'Se levantó un cercado y se volvió a mover. Se hizo un fuego y se volvió a apagar, porque alguien dijo que un fuego se ve de lejos. Se pusieron centinelas en sitios donde no había nada que guardar.',
        'Ayyur hizo lo que hacía siempre. Llevó los caballos a la hierba, los contó, los volvió a contar, y se acostó junto a ellos.',
        'Sesenta y dos. Cuadraba.',
        'Por encima de él el peñón se alzaba como un muro que alguien hubiera dejado a medias.',
        'Hacia la mañana refrescó, como refresca junto al mar: no con fuerza, sino por todas partes a la vez. Ayyur se echó la manta por encima y escuchó a los caballos respirar a su alrededor, y pensó en su padre en las colinas detrás de Tánger, a seis horas de barco y a toda una vida de distancia.',
        'Entonces alguien empezó a llamar.',
        'Se incorporó de golpe, porque llamar suele querer decir que algo se acerca.',
        'Pero no se acercaba nada. Era un hombre que se había subido a una piedra al borde del campamento, con la cara hacia el este, y que llamaba como también habían llamado en el campamento de Tánger, cada mañana, desde que Ayyur trabajaba allí.',
        'Los hombres se levantaron. No todos. Los bastantes para verlo.',
        'Se pusieron en filas sobre los guijarros, y se inclinaron, y se volvieron a levantar, y se volvieron a inclinar, y sonaba sobre el agua como si la playa respirara.',
        'Ayyur se quedó sentado con los caballos.',
        'No le daba miedo. Simplemente no lo entendía, y nadie se había tomado la molestia de explicárselo, porque nadie le explica nada al chico que duerme con los caballos.',
        'Lo que sí vio fue esto: después estaban más tranquilos. Toda la noche habían andado por el campamento como gallinas, y después de aquel cuarto de hora andaban como hombres con una tarea.',
        'Eso fue lo primero que entendió de la nueva fe. No lo que decía. Lo que hacía.',
        'Los barcos volvieron aquella tarde para la segunda carga, y los dos días solos resultaron haber sido uno y medio.',
      ] },
      { titel: 'El pastor y la cabra', tekst: [
        'Al cuarto día vino alguien.',
        'Vino de arriba, de la ladera, con un bastón y con once cabras, y entró en el campamento como si aquello hubiera estado allí desde siempre.',
        'Tres hombres lo sujetaron a la vez.',
        'Ayyur lo vio desde el cercado y pensó: es viejo. Eso fue lo primero. Era viejo, y flaco, y agarraba su bastón como se agarra algo que llevas agarrando cuarenta años.',
        'Lo llevaron a la tienda. Vino un hombre que sabía latín, y le habló, y el viejo contestó en algo que no era latín.',
        'Después vino alguien que hablaba bereber, de la misma comarca que Ayyur, y lo intentó, y el viejo lo miró como quien escucha a un pájaro.',
        'Al final se hizo con las manos.',
        'Las cabras eran suyas. La ladera era suya, es decir: llevaba allí toda la vida con cabras, que viene a ser lo mismo. Había visto los barcos. No había avisado a nadie, porque a quién iba a avisar, y de qué.',
        'Eso último se preguntó tres veces y tres veces se contestó igual.',
        'Lo dejaron marchar.',
        'A Sa3id le pareció una tontería y lo dijo en voz alta. «Se va al primer pueblo y entonces lo sabrán.»',
        '«Ya lo saben», dijo el hombre del latín. «Había cuatro barcos en el agua. Eso lo ve todo el mundo desde Tarifa hasta Algeciras.»',
        'El viejo volvió a subir la ladera con sus once cabras y no miró atrás.',
        'Ayyur lo siguió con la vista hasta que desapareció tras el borde.',
        'Se había imaginado la otra orilla como otra cosa. Como una tierra con un rey y una corona y murallas, o como nada, como agua y después más agua. No como un viejo con cabras que agarraba el mismo bastón que los hombres de las colinas detrás de Tánger.',
        '«¿Qué te creías?», dijo Sa3id cuando él lo dijo. «¿Que aquí había monos?»',
        'Ayyur no dijo nada, porque la verdad es que no había sabido lo que se creía.',
        'Aquella tarde el viejo volvió con dos cabras atadas a una cuerda, las dejó junto a la tienda e hizo un gesto que nadie entendió exactamente y que todo el mundo entendió.',
        'Le pagaron en cobre. No mucho cobre.',
        'Lo cogió, miró las monedas, se las guardó y volvió a subir la ladera.',
        'Así empezó la conquista de la tierra de la otra orilla: con dos cabras y un precio justo.',
      ] },
      { titel: 'Lo que cree Sa3id', tekst: [
        'Sa3id tenía la dentadura torcida, una cicatriz que le partía la ceja y una opinión sobre todo.',
        'Era de Tremecén, tenía veintiocho años y estaba allí desde el principio. Había encontrado a Ayyur el primer día junto a los caballos y después había seguido viniendo, por razones que Ayyur nunca entendió del todo. Quizá porque el chico escuchaba. Quizá porque no escuchaba nadie más.',
        'La séptima tarde Ayyur se lo preguntó por fin.',
        '«¿Por qué llamáis por la mañana?»',
        'Sa3id levantó la vista de su correa, que estaba engrasando.',
        '«Es la llamada», dijo.',
        '«Eso ya lo sé. ¿Por qué?»',
        'Sa3id se lo pensó, cosa rara en él.',
        '«Porque es la hora», dijo entonces. «Cinco veces al día es la hora. Cuando se hace de día, cuando el sol está en lo más alto, cuando tu sombra se hace más larga que tú, cuando el sol se ha ido, y cuando es de noche.»',
        '«¿Y entonces?»',
        '«Entonces dejas lo que estás haciendo y te quedas quieto.»',
        '«¿Para qué?»',
        '«Para Dios.» Sa3id se encogió de hombros. «Hay uno. No me pidas más, que yo no soy sabio. Soy un hombre con un caballo y una lanza.»',
        'Ayyur calló un momento.',
        '«Mi padre dice que en la fuente de nuestro pueblo vive algo», dijo. «Cada primavera le deja leche.»',
        'Lo dijo con la tensión de quien no sabe si se van a reír de él.',
        'Sa3id no se rió.',
        '«Pues eso dice tu padre», dijo. «Yo digo lo que digo. Tu padre y yo no tenemos tiempo de averiguarlo, así que hacemos nuestro trabajo.»',
        'Siguió con la correa.',
        '«Nosotros también lo tenemos desde hace poco», dijo después. «Mi abuelo no sabía nada de esto. Mi padre empezó con ello y sabía la mitad. Yo sé algo más que él y menos que el hombre que llama por la mañana. Dentro de cien años lo sabrán todo y pensarán que siempre ha sido así.»',
        'Levantó la correa hacia la luz.',
        '«Así pasa con todo», dijo.',
        'Ayyur siguió dándole vueltas mucho tiempo, más del que Sa3id probablemente había pretendido.',
        'No se puso con ellos, ni aquella tarde ni las semanas siguientes. Pero desde entonces dejó de quedarse sentado con los caballos como si no pasara nada. Se levantaba cuando empezaba. Eso era todo lo que hacía. Se levantaba, y esperaba a que terminara, y después seguía.',
        'Le parecía lo mínimo que se podía hacer por algo por lo que setecientos hombres se quedan quietos.',
      ] },
      { titel: 'Tafukt', tekst: [
        'La segunda semana se murió un caballo.',
        'No fue Tafukt. Fue un alazán sin nombre, de la última carga, al que se le había quedado una pata entre los guijarros cuando lo bajaban del barco.',
        'Se había oído. Todos en la playa lo habían oído.',
        'Sa3id lo hizo con un cuchillo y lo hizo rápido, y no dejó que lo hiciera Ayyur, aunque Ayyur se había ofrecido porque era su caballo, el suyo de cuidar.',
        '«No», había dicho Sa3id. «Tú tienes doce años.»',
        '«Trece dentro de dos meses.»',
        '«Pues lo haces dentro de dos meses.»',
        'Después Ayyur se quedó el resto de la tarde junto al cercado sin hacer nada, cosa que no le pasaba nunca.',
        'No era por el alazán. Había visto morirse ovejas, muchas ovejas, y un invierno tantas que había dejado de contar.',
        'Era porque se dio cuenta de que en casa nadie lo sabría.',
        'En casa nadie sabía dónde estaba. No había podido decirlo, porque no sabía escribir y no iba nadie hacia allá. Si mañana se moría en una playa de la otra orilla, su padre esperaría en las colinas detrás de Tánger hasta el invierno y después pensaría que se había escapado.',
        'Tafukt le empujó el hombro con el morro.',
        'Se quedó sentado hasta que se hizo de noche y se levantó cuando llegó la llamada, como hacía ahora, y después se puso a trabajar.',
        'A la mañana siguiente fue a buscar al escribano.',
        'El escribano era un hombre pequeño con los dedos manchados de tinta que se pasaba el día sentado en una piedra apuntando cosas que nadie le pedía que apuntara. Se llamaba Yunus y era de Cairuán.',
        '«¿Me puedes escribir una cosa?»',
        'Yunus levantó la vista. «¿Para quién?»',
        '«Para mi padre.»',
        '«¿Tu padre sabe leer?»',
        'Ayyur calló.',
        '«No», dijo entonces.',
        '«¿Conoce a alguien que sepa?»',
        '«El hombre que cobra el impuesto viene dos veces al año. Ese sabe.»',
        'Yunus se lo pensó, sacó luego un trozo de tablilla de su caja y se lo puso sobre la rodilla.',
        '«Dime.»',
        'Ayyur dijo: «Ayyur vive. Ayyur está con los caballos. Ayyur vuelve.»',
        'Yunus lo escribió, lo miró y dijo: «¿Eso es todo?»',
        '«¿Qué más tendría que poner?»',
        'El escribano se encogió de hombros y dejó el trozo en la caja, con las cartas que volverían en el próximo barco.',
        'Fue la primera vez en su vida que el nombre de Ayyur estaba escrito en alguna parte.',
        'Le estuvo dando vueltas el resto del día, mientras recortaba cascos y acarreaba agua, y se sorprendió a sí mismo gustándole de una manera que casi le daba vergüenza.',
      ] },
      { titel: 'La montaña de Táriq', tekst: [
        'La tercera semana el peñón recibió su nombre, y Ayyur estaba allí cuando ocurrió, aunque en aquel momento no lo supo.',
        'Para entonces ya había un campamento. Había cercados, había un pozo que habían excavado, había tiendas en filas. Habían llegado cuatro cargas y vendrían más.',
        'Yunus estaba en su piedra con una tablilla sobre las rodillas, y le preguntó al hombre que tenía al lado cómo tenía que escribir el lugar.',
        '«¿Qué lugar?»',
        '«Este. Donde estamos. Tengo que escribir dónde está el ejército.»',
        'El hombre se encogió de hombros.',
        '«En la montaña», dijo.',
        '«¿Qué montaña?»',
        'Los dos miraron hacia arriba.',
        '«La montaña de Táriq», dijo el hombre, y lo dijo como se dice algo evidente.',
        'Yunus lo escribió. Yábal Táriq.',
        'Ayyur estaba dos pasos más allá con un cubo en la mano y lo oyó, y pensó: bien, y siguió andando.',
        'Así pasan estas cosas. Nunca hay nadie delante que piense: este es el momento. El momento parece un escribano que necesita una palabra y un soldado que no tiene ganas.',
        'Mil trescientos años después ese nombre sigue en todos los mapas del mundo, gastado hasta convertirse en algo que ya nadie reconoce, y ninguno de los que lo pronuncian sabe que hubo un hombre que se llamaba Táriq.',
        'Ayyur llevó el cubo a los caballos.',
      ] },
      { titel: 'El ejército va hacia el norte', tekst: [
        'Se fueron una mañana de julio, y desde la primera luz hasta mucho después del mediodía tardó la última fila en perderse de vista.',
        'Ayyur no fue.',
        'Se lo habían dicho dos días antes, se lo había dicho Sa3id, que lo soltó como soltaba todo: sin rodeos y en el orden equivocado.',
        '«Tú te quedas aquí.»',
        '«¿Por qué?»',
        '«Porque se quedan cien caballos y alguien tiene que cuidarlos.»',
        '«Hay otros hombres.»',
        '«No hay otros hombres que se sepan todos los nombres.»',
        'Ayyur no supo si eso era un elogio o una manera de mantenerlo fuera de la lucha. Sospechó lo segundo, y estaba a la vez enfadado y aliviado, y sentir esas dos cosas a la vez es algo para lo que a los doce años todavía no se tiene palabra.',
        'Sa3id sí fue.',
        'La mañana de la marcha pasó por el cercado con su caballo de la brida — un castrado pardo que Ayyur llevaba tres meses cuidando y al que llamaba Amellal, que quiere decir blanco, lo cual no cuadraba pero que el propio castrado nunca había discutido.',
        '«Que beba antes de que apriete el calor», dijo Ayyur.',
        '«Ya lo sé.»',
        '«No bebe de agua quieta. Hay que moverla con la mano.»',
        '«Eso también lo sé.»',
        'Los dos se quedaron allí como si todavía faltara algo.',
        '«Si pasa algo», dijo Sa3id, «vas a ver a Yunus. No es valiente pero es listo, y aquí lo listo vale más.»',
        '«Bien.»',
        'Sa3id montó, miró una última vez hacia abajo y dijo: «No eres mal chico, Ayyur. No te metas en el agua, que no sabes nadar.»',
        'Después se fue.',
        'Ayyur lo vio hasta más o menos la mitad de la segunda colina y después ya no, porque a partir de ahí era una sola nube de polvo y ya no eran personas.',
        'Volvió con los caballos.',
        'Eran ciento cuatro. Los contó dos veces.',
      ] },
      { titel: 'Esperar también es algo', tekst: [
        'Las semanas siguientes fueron las más largas de su vida y en ellas no pasó casi nada.',
        'Eso es lo raro de la guerra, descubrió Ayyur: para casi todo el mundo es esperar. Las historias hablan del día en que ocurrió. Nadie cuenta las cuatro semanas anteriores, en las que buscas hierba para ciento cuatro caballos en una ladera donde la hierba se ha acabado.',
        'En aquellas semanas aprendió tres cosas.',
        'La primera la aprendió del viejo de las cabras, que pasaba cada pocos días y después cada día, y que acabó pasando las tardes junto al cercado sin que nadie pudiera explicar por qué. Se llamaba algo que Ayyur nunca supo decir bien. Señalaba cosas y decía la palabra, y Ayyur la repetía, y el viejo lo corregía, y así fue todo el verano.',
        'Agua. Piedra. Cabra. Montaña. Niño. Pan.',
        'Así se aprende una lengua. No de un libro. De un viejo que no tiene nada mejor que hacer.',
        'La segunda la aprendió de Yunus. Le preguntó una tarde, medio en broma, si el escribano podía enseñarle letras, y Yunus dijo: «No», y tres días después estaba sentado a su lado con un palo en la arena.',
        'Iba despacio. A Ayyur se le daba mal. Su mano no hacía lo que su cabeza pensaba y las letras le salían torcidas, como algo que hubiera tocado un animal.',
        'Al cabo de un mes sabía su propio nombre.',
        'Aquella tarde lo escribió veinte veces en la arena junto al cercado y lo borró veinte veces, y la vigesimoprimera lo dejó hasta que se lo llevó el viento.',
        'La tercera no la aprendió de nadie.',
        'Descubrió que en la llamada ya no se levantaba solo por educación.',
        'Fue en algún momento de agosto. Estaba junto a Tafukt, se hacía de noche, el hombre de la piedra empezó, y Ayyur notó que le gustaba que ocurriera. No por lo que se decía — seguía entendiendo poco. Por el hecho de que cinco veces al día se trazara una raya, en una costa donde no conocía a nadie y nadie lo conocía a él, y de que el día por eso no fuera una papilla sino una cosa con partes.',
        'Seguía sin ponerse con ellos.',
        'Pero aquella semana sí le preguntó a Yunus cómo eran las palabras, y Yunus se las dijo despacio, y Ayyur las repitió, y el escribano lo corrigió como lo corregía el viejo con agua, piedra, cabra.',
        'En este libro no pasa de ahí, porque no pasó de ahí.',
        'Lo que fue de ello en los años siguientes, no lo sabemos. Solo sabemos que así empezó con miles de chicos como él: no con un ejército, no con un combate, sino con alguien que veía algo cinco veces al día hasta que formó parte del día.',
      ] },
      { titel: 'La noticia del río', tekst: [
        'La noticia llegó un martes, con un jinete que había cabalgado tan fuerte que a su caballo ya no había quien lo salvara.',
        'Ayyur se lo notó al caballo antes que al hombre. Así funciona cuando eres de los caballos.',
        'Se había combatido junto a un río en el sur de aquella tierra, a ocho días. Había durado tres días, o cinco, según a quién se lo preguntaras. El rey de la corona había estado allí y ya no estaba, y sobre eso las versiones se separaron enseguida tanto que Ayyur dejó de escuchar.',
        'Lo que era igual en todas las versiones: el ejército no había sido derrotado. Seguía hacia el norte. Caerían ciudades cuyos nombres no conocía nadie en el campamento.',
        'Aquella noche se celebró en la playa.',
        'Ayyur no celebró, porque seguía sin oír lo que quería oír.',
        'Se lo preguntó al jinete, que estaba demasiado cansado para ser educado.',
        '«Sa3id, de Tremecén. Caballo pardo. Una cicatriz que le parte la ceja.»',
        'El hombre lo miró como si le preguntara por una oveja de un rebaño de diez mil.',
        '«Chico», dijo. «Yo no sé ni el nombre del rey con seguridad.»',
        'Tres semanas después vino un segundo jinete, y tampoco lo sabía.',
        'En octubre volvió un carro con heridos y con hombres que ya no querían, y Ayyur recorrió a los veintiocho y lo preguntó veintiocho veces.',
        'El vigesimoquinto lo conocía.',
        '«Sa3id», dijo. «Sí. En el río.»',
        'Ayyur esperó.',
        '«Estaba vivo cuando lo vi», dijo el hombre. «Después me caí y ya no vi nada.»',
        'Eso fue todo. Eso es todo lo que Ayyur llegó a saber nunca, y es también todo lo que sabemos nosotros, porque de los siete mil hombres que aquel año cruzaron el estrecho se conocen cuatro por su nombre y el resto es polvo.',
        'Ayyur volvió al cercado.',
        'Amellal no estaba allí. Hacía tres meses que no estaba, y aun así miraba cada vez.',
        'Sacó agua, la movió con la mano como se hace para un caballo que no bebe de agua quieta, y se la dio a otro animal.',
      ] },
      { titel: 'El arcón', tekst: [
        'A finales de octubre Yunus cruzó el campamento con un arcón bajo el brazo, buscando a alguien que supiera montar y conociera el camino por la costa.',
        'Ya no quedaba nadie más. Esa era la respuesta honrada a por qué acabó en Ayyur.',
        'El arcón tenía que ir al norte, a un sitio donde el ejército había montado un campamento de invierno. Dentro había tablillas, y cartas, y un saco de cuero con cosas pequeñas que los soldados habían entregado porque no querían perderlas — y que no habían ido a recoger, lo cual dice de esos soldados todo lo que uno no quiere saber.',
        '«¿Cuánto?», preguntó Ayyur.',
        '«Seis días. Ocho si llueve.»',
        '«¿Y después?»',
        'Yunus lo miró.',
        '«Después estarás allí», dijo. «Y allí hay más que aquí.»',
        'Ayyur cargó el arcón sobre Tafukt.',
        'Al atarlo, el saco se volcó y algo rodó al suelo.',
        'Era de bronce, largo como su mano, y tenía una cabeza con ocho puntas. Como una estrella.',
        '«¿Qué es eso?», preguntó.',
        'Yunus apenas lo miró.',
        '«Una llave», dijo. «Ya estaba en el saco cuando me lo dieron. Nadie sabe de quién.»',
        'Ayyur la tuvo un momento en la mano. Estaba tibia del sol.',
        'Pensó en una puerta en alguna parte, al otro lado del agua, que alguien había cerrado tras de sí por última vez sin saber que era la última. En una casa que quizá siguiera en pie. En un hombre que se había embarcado con una llave en el bolsillo porque una llave no se deja, y que la había entregado porque tampoco te la llevas al otro lado del río.',
        'La dejó deslizarse otra vez dentro del saco.',
        'Después la volvió a sacar y se la metió en su propio cinturón.',
        'Yunus lo vio y no dijo nada.',
        '«No va a venir nadie a por ella», dijo Ayyur.',
        '«No», dijo Yunus. «No va a venir nadie.»',
        'Ayyur apretó la correa y montó.',
      ] },
      { titel: 'Hacia el norte', tekst: [
        'Aquella tarde se fue por la costa, con un arcón, una yegua y una llave que no era de nadie.',
        'En la última curva antes de la ladera se paró y miró atrás.',
        'El campamento quedaba debajo de él como algo que hubiera estado allí siempre: cercados, tiendas en filas, el pozo, humo de dos fuegos. Siete meses antes aquello eran guijarros y algas.',
        'El viejo de las cabras estaba al borde de su ladera, como estaba allí todas las tardes.',
        'Ayyur levantó la mano.',
        'El viejo levantó el bastón.',
        'Eso fue todo.',
        'Siguió cabalgando, y la tierra en la que entraba era verde de una manera que él no conocía, con otros árboles y demasiada agua, y con pueblos donde la gente se paraba junto al camino a mirar a un chico sobre una yegua con un arcón.',
        'Los saludaba con las palabras que había aprendido del viejo. Agua. Piedra. Pan.',
        'Algunos se reían. Una mujer le dio pan.',
        'Eso debería haberlo escrito después, porque es la clase de cosa que desaparece: que las primeras semanas de la conquista de aquella tierra consistieron, para un chico de doce años, en árboles extraños, demasiada agua y una mujer que le dio pan.',
        'Nunca volvió a las colinas detrás de Tánger.',
        'No fue una decisión. Casi nunca lo es. Llegó el invierno, y había trabajo, y había caballos, y entonces había pasado un año y otro, y en algún momento ya no es un viaje que aplazas sino una vida que tienes.',
        'El trozo de tablilla con su nombre llegó a su padre. Eso no lo sabemos. Eso lo esperamos.',
        'Lo que sí sabemos es que en los siglos siguientes millones de personas han cruzado ese estrecho, en un sentido y en el otro, y que siempre se ha quedado alguien esperando.',
        'La llave se fue al norte, en el cinturón de un chico al que nadie se la había dado.',
        'Adónde fue después, está en el libro siguiente.',
      ] },
    ],
  },
}
