import type { SleutelVertaling } from './sleutels-talen'

/**
 * De sleutels van Marokko in het Duits.
 *
 * Wordt deel voor deel vertaald. Wat hier staat is af; de rest valt terug op
 * het Nederlands tot het zover is.
 *
 * De regelval van het Nederlands blijft staan: één alinea daar is één alinea
 * hier. Dat is geen vormfetisj — een hoofdstuk van dit boek is opgebouwd uit
 * korte alinea’s met stiltes ertussen, en wie die samenvoegt haalt het tempo
 * eruit.
 *
 * Aanhalingstekens zijn de Duitse „ en “, de apostrof is overal de
 * typografische ’ en nooit de rechte: die breekt de string waar dit bestand
 * in staat.
 */
export const DE_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'Der Olivenbrand',
    jaar: '± 200',
    waar: 'Walili (Volubilis), am Fuß des Zerhoun',
    verteller: 'Tala, elf Jahre, Tochter eines erkrankten Ölmüllers',
    flap: 'Tala hat den Schlüssel zum Lager, und der Aufseher will ihn haben. Als das Öl der ganzen Stadt in Gefahr gerät, muss sie zwischen Gehorchen und Rechthaben wählen.',
    sleutel: 'Der Schlüssel wird in Walili von Talas Großvater geschmiedet und zieht am Ende mit einer amazighischen Karawane in die Hügel.',
    echt: [
      'Volubilis — auf Arabisch Walili — war eine wirkliche römische Stadt bei Meknès, mit Tausenden Einwohnern, Thermen und gepflasterten Straßen.',
      'Die Stadt lebte vom Olivenöl. Dutzende Ölpressen sind ausgegraben worden, und sie arbeiteten nach demselben Prinzip wie die Pressen, die in Marokko heute noch benutzt werden.',
      'Die Böden waren voller Mosaiken. Ein Teil davon liegt noch immer da, unter freiem Himmel.',
      'Die Bevölkerung war größtenteils amazighisch; römisches und amazighisches Leben gingen hier ineinander über.',
    ],
    verzonnen: [
      'Tala, ihre Familie und der Aufseher Marcus haben nicht existiert.',
      'Das Feuer in der Geschichte ist erfunden. Es gibt keinen Beleg für einen großen Brand in Walili in dieser Zeit.',
      'Der Schlüssel mit dem achtzackigen Stern ist erfunden. Der achtzackige Khatam ist dagegen ein echtes und jahrhundertealtes marokkanisches Motiv.',
    ],
    hoofdstukken: [
      { titel: 'Der Schlüssel', tekst: [
        'Tala wachte von dem Geruch auf.',
        'Oliven. Gepresste Oliven, warm und bitter. Die ganze Stadt roch in diesen Wochen danach. Sie blieb kurz liegen und horchte. Draußen knarrte die große Presse schon. Das hieß, sie war zu spät.',
        'Sie sprang aus dem Bett und zog sich das Kleid über den Kopf.',
        '„Tala!“, rief ihre Mutter von unten. „Das Tor!“',
        'Das Tor. Natürlich das Tor.',
        'Seit ihr Vater krank geworden war, machte Tala seine Arbeit. Jeden Morgen ging sie zum Lager hinter dem Haus und schloss die Tür auf. Dort standen die Krüge. Hundert Krüge, bis zum Rand mit Öl gefüllt, bereit für den Hafen.',
        'Der Schlüssel hing an einer Schnur um ihren Hals. Er war aus Bronze und so lang wie ihre Hand. Ihr Großvater hatte ihn geschmiedet, lange bevor es sie gab. Im Kopf saßen acht Zacken, wie ein Stern.',
        '„Verlier ihn nicht“, hatte ihr Vater gesagt. Er hatte es leise gesagt, denn lauter konnte er nicht mehr. „Diese Tür geht für nichts anderes auf.“',
        'Tala rannte die Treppe hinunter, an der Küche vorbei, über den Innenhof. Es war noch früh. Die Sonne stand gerade über den Hügeln und die Steine waren kalt unter ihren Füßen.',
        'Beim Lager stand ein Mann.',
        'Sie blieb stehen.',
        'Er war groß und trug den roten Mantel des Aufsehers. Marcus. Jeder in Walili kannte Marcus, und niemand mochte ihn.',
        '„Du bist spät“, sagte er.',
        '„Ich bin pünktlich“, sagte Tala.',
        'Sie wusste, dass sie das nicht hätte sagen sollen. Sie sagte es trotzdem.',
        'Marcus sah sie an. Dann streckte er die Hand aus.',
        '„Gib mir den Schlüssel. Ein Kind hat nicht auf hundert Krüge aufzupassen.“',
        'Tala trat einen Schritt zurück.',
        'In ihrem Kopf hörte sie ihren Vater. *Diese Tür geht für nichts anderes auf.* Und sie dachte an etwas anderes, an etwas, das sie gestern gesehen und für nichts gehalten hatte.',
        'Zwei Krüge, die nicht an ihrem Platz standen.',
        '„Nun?“, sagte Marcus.',
        'Tala schloss die Hand um die Bronze. Sie war warm geworden von ihrer Haut.',
        '„Nein“, sagte sie.',
      ] },
      { titel: 'Zwei Krüge', tekst: [
        'Marcus lachte nicht. Er wurde auch nicht wütend. Das war das Schlimmste.',
        'Er ließ die Hand sinken, zog seinen Mantel zurecht und sagte: „Wie du willst.“ Dann ging er weg, die Gasse hinaus, ohne sich umzudrehen.',
        'Tala blieb stehen, bis sie seine Schritte nicht mehr hörte. Erst danach merkte sie, dass ihre Hände zitterten.',
        'Sie machte die Tür auf.',
        'Drinnen war es dunkel und kühl. Die Krüge standen in Reihen zu zehnt, mit Stroh dazwischen, damit sie nicht aneinanderschlugen. Zehn Reihen zu zehn. Jeden Morgen zählte sie sie. Das hatte ihr Vater ihr beigebracht, als sie sechs war, und damals war es noch ein Spiel.',
        'Sie fing links an und zählte laut, wie immer.',
        'Bei der hintersten Reihe hörte sie auf.',
        'Es standen neun da.',
        'Tala zählte noch einmal. Neun. Sie ging um die Reihe herum, bückte sich, sah hinter das Stroh. Neun.',
        'Gestern hatte sie auch etwas Seltsames gesehen. Zwei Krüge, die falsch standen, mit den Henkeln zur Wand statt zum Gang. Sie hatte gedacht: das hat jemand in Eile gemacht. Sie hatte sie zurechtgerückt und nicht mehr daran gedacht.',
        'Jetzt stand einer weniger da.',
        'Sie setzte sich in die Türöffnung, den Rücken am Pfosten, die Knie angezogen, und versuchte sich zu überlegen, was sie tun sollte.',
        'Sie konnte es ihrer Mutter sagen. Aber ihre Mutter hatte diesen Monat schon genug: einen kranken Mann oben, ein Haus voller Leute, die bezahlt werden mussten, und eine Ernte, die in drei Wochen zum Hafen sollte.',
        'Sie konnte es Marcus sagen. Marcus war der Aufseher. Das war seine Arbeit.',
        'Tala sah in die Gasse, in der er verschwunden war.',
        'Nein.',
        '„Du stehst im Weg“, sagte eine Stimme.',
        'Sie schreckte auf. Vor ihr stand ein Junge in ihrem Alter, mit einer Lederschürze und den Armen voller Reisigbündel. Seine Hände waren schwarz.',
        '„Ich stehe nicht im Weg“, sagte Tala. „Das ist meine Tür.“',
        '„Dann stehst du deiner eigenen Tür im Weg.“',
        'Er hieß Yidir und arbeitete in der Schmiede am Ende der Straße. Tala kannte ihn vom Sehen, so wie man in Walili jeden vom Sehen kannte, und sonst nicht.',
        'Sie stand auf, um ihn vorbeizulassen. Er ging nicht weiter.',
        '„Du zählst jeden Morgen“, sagte er.',
        '„Woher weißt du das?“',
        '„Ich komme jeden Morgen vorbei.“',
        'Tala zögerte. Dann sagte sie es doch, weil es heraus musste und weil er nun einmal dastand.',
        '„Einer fehlt.“',
        'Yidir stellte seine Reisigbündel ab.',
        '„Einer?“, sagte er. „Dann hast du Glück gehabt. Bei uns fehlen sechs Eisenstangen.“',
      ] },
      { titel: 'Wie man Öl macht', tekst: [
        'An diesem Nachmittag stand Tala bei der Presse, wie jeden Tag in der Ernte.',
        'Die Presse war ein ausgehöhlter Stein, so groß wie ein Karren, mit einem runden Stein darin, den ein Esel im Kreis zog. Die Oliven kamen hinein, wurden zerquetscht, und was herauskam war ein dicker brauner Brei, der nach nichts aussah.',
        'Das war der Teil, der Fremde immer enttäuschte. „Das soll Öl sein?“, fragten sie dann. Nein. Das war der Anfang.',
        'Der Brei kam in runde Matten aus geflochtenem Schilf. Diese Matten wurden unter der Balkenpresse aufeinandergestapelt, und dann drehten zwei Männer an der Schraube, langsam, als hätten sie Zeit. Unter dem Stapel lief eine Rinne.',
        'Da kam es heraus.',
        'Zuerst Wasser, trüb und schmutzig. Dann, nach einer Weile, etwas anderes. Etwas, das auf dem Wasser schwamm und grüner war als alles, was Tala kannte.',
        'Ihr Vater hatte sie das erste Mal am Nacken gepackt und ihren Kopf darübergehalten. „Riech“, hatte er gesagt. „Das ist es. Wenn es so riecht, ist es gut. Wenn es nach nichts riecht, hast du zu lange gewartet.“',
        'Sie hatte damals gelogen, dass sie es rieche. Jetzt roch sie es wirklich.',
        'Walili lebte davon. Nicht von den Mosaikböden, über die Besucher liefen, nicht von den Säulen auf dem Platz, nicht von den gepflasterten Straßen. Davon. Von gepressten Oliven, die in Krüge kamen, auf Karren an die Küste und auf Schiffe zu Orten, von denen Tala nur die Namen kannte.',
        'Sie achtete auf die Rinne und auf die Matten und auf den Esel, und dabei dachte sie an neunundneunzig Krüge.',
        'Sechs Eisenstangen, hatte Yidir gesagt. Aus der Schmiede.',
        'Eisen war teuer. Öl war teuer. Und beides ging in dieselbe Richtung aus der Stadt: über die Straße zum Hafen.',
        '„Tala.“ Einer der Männer zeigte auf die Rinne. „Sie läuft über.“',
        'Sie schoss nach vorn und schob die Schale darunter, zu spät. Ein Strahl Öl lief über den Stein und verschwand zwischen den Fugen.',
        'Ein Finger dick, vielleicht zwei. Genug für eine Familie für eine Woche.',
        'Der Mann sagte nichts dazu. Das machte es schlimmer.',
      ] },
      { titel: 'Was ein Aufseher darf', tekst: [
        'Marcus kam am dritten Tag wieder, und er kam nicht allein.',
        'Tala sah ihn den Innenhof betreten, zwei Männer hinter sich. Ihre Mutter kam heraus, wischte sich die Hände am Kleid ab und stellte sich genau zwischen ihn und die Tür.',
        '„Friede“, sagte Marcus.',
        '„Friede“, sagte ihre Mutter, in dem Ton, in dem man das sagt, wenn man es nicht so meint.',
        '„Dein Mann ist krank.“',
        '„Mein Mann ruht.“',
        '„Drei Wochen“, sagte Marcus. „In drei Wochen geht die Ernte zum Hafen, und die Stadt rechnet mit dem, was in diesem Haus steht. Ich muss wissen, dass es da ist.“',
        '„Es ist da.“',
        '„Ich will es sehen.“',
        'Es entstand eine Stille. Tala stand in der Küchentür und traute sich nicht, sich zu bewegen.',
        'Ihre Mutter sagte: „Du darfst schauen. Meine Tochter schließt auf.“',
        'Tala ging über den Innenhof unter den Augen von fünf Menschen. Sie zog die Schnur über den Kopf, steckte den Schlüssel ins Schloss und drückte die Tür auf.',
        'Marcus ging hinein. Er ging die Reihen entlang, langsam, die Hände auf dem Rücken. Bei der hintersten Reihe blieb er stehen.',
        'Tala hielt den Atem an.',
        '„Neunundneunzig“, sagte Marcus.',
        'Er drehte sich um und sah ihre Mutter an.',
        '„Es müssten hundert sein.“',
        'Ihre Mutter erstarrte. Tala sah es an ihren Schultern.',
        '„Dann ist einer zerbrochen“, sagte sie.',
        '„Dann lägen Scherben da.“ Marcus breitete die Hände aus. „Ich sehe keine Scherben. Ich sehe Stroh, das zurechtgezogen worden ist.“',
        'Er wartete kurz, genau lang genug.',
        '„Ich sage nicht, dass ihr stehlt“, sagte er dann. „Ich sage, dass ein Kind von elf Jahren den Schlüssel zu hundert Krügen hat und dass heute neunundneunzig dastehen. Das sage ich. Und das werde ich auch auf dem Platz sagen.“',
        'Er ging zur Tür hinaus und an Tala vorbei, als wäre sie ein Pfosten.',
        'Als er weg war, setzte sich ihre Mutter auf den Rand des Brunnens. Sie sagte sehr lange nichts.',
        '„Mama“, sagte Tala. „Ich habe ihn nicht—“',
        '„Ich weiß.“',
        '„Ich habe sie am Montag gezählt und da waren es noch—“',
        '„Tala.“ Ihre Mutter sah auf. Ihre Augen waren rot. „Ich weiß. Und das hilft uns nichts.“',
      ] },
      { titel: 'Die Schmiede', tekst: [
        'Yidir saß auf einem umgedrehten Eimer vor der Schmiede und schmirgelte ein Scharnier.',
        '„Du hattest recht“, sagte Tala.',
        '„Das sagen mir die Leute selten“, sagte Yidir, ohne aufzusehen. „Womit?“',
        '„Damit, dass es nicht ein Krug war.“',
        'Jetzt sah er doch auf.',
        'Tala setzte sich neben ihn auf die Schwelle und erzählte es. Von Marcus, von neunundneunzig, von dem, was er auf dem Platz sagen würde. Yidir hörte zu, wie er alles tat: als dächte er nebenbei an etwas anderes, und dabei entging ihm nichts.',
        '„Und dein Eisen?“, fragte sie.',
        '„Sechs Stangen. Mein Meister denkt, er hat sich verzählt.“ Yidir zuckte mit den Schultern. „Mein Meister verzählt sich nie.“',
        '„Wann?“',
        '„Letzte Woche. Und die Woche davor drei.“',
        'Tala zog die Knie an.',
        '„Was geht aus der Stadt hinaus?“, fragte sie. „Jeden Tag, meine ich.“',
        'Yidir dachte nach.',
        '„Karren“, sagte er. „Öl, Getreide, Häute, Eisen. Alles geht über die Straße nach Norden. Am Tor steht ein Wachposten. Da wird alles aufgeschrieben.“',
        '„Von wem?“',
        'Yidir sah sie an.',
        '„Vom Aufseher“, sagte er.',
        'Sie sagten beide eine Weile nichts.',
        '„Das beweist nichts“, sagte Tala schließlich.',
        '„Nein.“',
        '„Wenn ich das sage, sagen sie, ein Kind von elf beschuldigt einen Mann, weil er es nicht mag.“',
        '„Ja“, sagte Yidir. „Das sagen sie.“',
        'Er legte das Scharnier weg.',
        '„Also brauchst du etwas, das sie nicht wegreden können.“',
        '„Zum Beispiel?“',
        '„Zum Beispiel sehen, was nachts durch das Tor geht.“',
        'Tala sah ihn an. Er sah zurück, und zum ersten Mal, seit sie ihn kannte, lachte er.',
      ] },
      { titel: 'Was nachts durch das Tor geht', tekst: [
        'Sie lagen auf dem Dach des Badehauses, flach auf dem Bauch, das Kinn auf den Armen.',
        'Das Dach war warm vom Tag. Unter ihnen lag die Straße, die zum nördlichen Tor führte, breit genug für zwei Karren nebeneinander. Am Tor brannte eine Lampe.',
        '„Wie lange noch?“, flüsterte Tala.',
        '„Weiß ich nicht.“',
        '„Du hast gesagt, nachts gehen Karren.“',
        '„Ich habe gesagt, ich dáchte, dass nachts Karren gehen.“',
        'Tala seufzte und legte den Kopf auf den Arm.',
        'Die Sterne waren in dieser Nacht unglaublich. In der Stadt sah man sie halb, durch das Licht und den Rauch, aber hier oben waren es so viele, dass es unruhig machte.',
        '„Meine Großmutter sagt, sie sind eine Karte“, sagte Yidir.',
        '„Die Sterne?“',
        '„Ja. Wer sie lesen kann, kommt überallhin. Sie sagt, ihre Familie ist so aus der Wüste bis hierher gelaufen.“',
        '„Kannst du sie lesen?“',
        '„Nein“, sagte Yidir. „Es hat es mir niemand beigebracht.“',
        'Dann hörten sie es.',
        'Ein Karren. Keine zwei Esel, keine Pferde — ein Esel, langsam, und das Geräusch von Holz, das unter Gewicht knarrt.',
        'Tala rutschte an den Rand.',
        'Der Karren kam aus einer Seitengasse. Zwei Männer gingen daneben, beide mit einem Tuch um den Kopf. Auf dem Karren lag Stroh, und unter dem Stroh stand etwas Rundes.',
        'Am Tor hielt der Karren an.',
        'Aus dem Wachhäuschen kam ein Mann mit einer Lampe. Er ging nicht zum Karren. Er ging zu den Männern, sprach kurz mit ihnen und schrieb etwas auf ein Täfelchen.',
        'Dann hob er den Schlagbaum.',
        'Der Karren fuhr in die Nacht hinaus.',
        'Tala ließ den Atem los. Sie hatte nicht gemerkt, dass sie ihn anhielt.',
        '„Er hat nicht nachgesehen“, sagte sie. „Er hat nicht unter das Stroh gesehen.“',
        '„Nein.“',
        '„Das ist—“',
        '„Das ist immer noch nichts“, sagte Yidir. „Das ist ein Mann, der nicht gut genug hinsieht. Dafür hängt niemand.“',
        'Er hatte recht, und das wusste Tala auch.',
        'Aber als der Karren um die Kurve bog, geschah etwas. Der Esel erschrak vor etwas im Dunkeln, zog zur Seite, und der Karren fuhr mit einem Rad über die Bordkante.',
        'Etwas fiel vom Karren.',
        'Es rollte, kam an der Mauer zum Stehen und blieb dort liegen.',
        'Ein Krug.',
        'Einer der Männer fluchte, kam zurück, hob ihn auf und stellte ihn wieder unter das Stroh. Der Karren fuhr weiter.',
        'Aber Tala hatte gesehen, was darauf stand.',
        'Auf die Schulter jedes Krugs aus ihrem Haus setzte ihr Vater ein Zeichen in den Ton, bevor er gebrannt wurde. Acht Zacken. Ein Stern.',
        'Sie packte Yidirs Arm so fest, dass er zischte.',
        '„Der ist von uns“, sagte sie.',
      ] },
      { titel: 'Was du sagst und was sie hören', tekst: [
        'Am nächsten Morgen ging Tala zum Platz.',
        'Sie hatte die ganze Nacht darüber nachgedacht, jedenfalls über die halbe; die andere Hälfte hatte sie geschlafen, ohne es zu wollen. Sie wusste, was sie sagen würde. Sie hatte es dreimal gegen die Wand ihres Zimmers geübt.',
        'Auf dem Platz, unter den Säulen, tagte der Rat. Das hieß: fünf Männer auf Steinbänken, ein Schreiber daneben, und alle, die etwas zu klagen hatten, ringsherum.',
        'Marcus stand schon da.',
        'Tala wartete, bis ein Mann über eine Mauer und einen Nachbarn zu Ende geredet hatte. Dann trat sie vor.',
        '„Ich möchte etwas sagen“, sagte sie.',
        'Fünf Männer sahen auf. Einer von ihnen, der Älteste, mit einem Gesicht wie eine getrocknete Feige, beugte sich vor.',
        '„Wessen Kind bist du?“',
        '„Von Yuba, dem Ölmüller. Aus der Säulenstraße.“',
        '„Der ist krank.“',
        '„Ja“, sagte Tala. „Darum stehe ich hier.“',
        'Sie erzählte es. Von dem Krug, der fehlte, und am Tag darauf noch einem. Von dem Karren in der Nacht und dem Mann, der den Schlagbaum hob, ohne unter das Stroh zu sehen. Von dem Krug, der herunterfiel, und von dem Zeichen mit den acht Zacken.',
        'Sie erzählte es genau so, wie sie es geübt hatte, und während sie es tat, hörte sie es selbst auch.',
        'Sie hörte, wie es klang.',
        'Ein Kind. Ein Dach. Das Dunkel. Ein Zeichen, das niemand sonst gesehen hatte.',
        'Als sie fertig war, war es kurz still. Dann sagte Marcus, ganz ruhig: „Darf ich?“',
        'Der Älteste nickte.',
        '„Das Mädchen hat recht, dass Krüge fehlen“, sagte Marcus. „Das habe ich selbst gezählt, vorgestern, in ihrem eigenen Lager. Neunundneunzig von hundert. Ich habe es damals auch gesagt.“',
        'Er breitete die Hände aus, wie er das tat.',
        '„Wer hat den Schlüssel zu dieser Tür?“',
        'Niemand sagte etwas.',
        '„Sie“, sagte Marcus. „Ein Kind von elf Jahren. Und jetzt, wo einer fehlt, ist es ein Karren in der Nacht gewesen. Ein Karren, den nur sie gesehen hat.“',
        'Der Älteste des Rates sah Tala an, und sein Blick war nicht unfreundlich. Das war das Schlimmste daran.',
        '„Kind“, sagte er. „Geh nach Hause. Kümmere dich um deinen Vater.“',
        'Tala stand auf dem Platz, die Hände am Körper und die Ohren glühend, und um sie herum fing jeder wieder an, über eine Mauer und einen Nachbarn zu reden.',
      ] },
      { titel: 'Das Feuer', tekst: [
        'Das Feuer begann vier Tage später, und es begann nicht bei ihnen.',
        'Tala wachte davon auf. Nicht von Licht und nicht von Geschrei — von einem Geräusch. Einem tiefen, leisen Brüllen, als atmete irgendwo ganz in der Nähe jemand sehr lange aus.',
        'Sie war am Fenster, bevor sie wach war.',
        'Gegenüber auf der anderen Straßenseite, zwei Häuser weiter, brannte das Lager von Quintus. Quintus presste auch Öl. Seine Krüge standen in einem Raum unter seinem Haus, und daraus kam jetzt Feuer zum Fenster heraus, flach, und nicht nach oben, wie Feuer es tun sollte.',
        'Das kommt vom Öl, wusste Tala später. Öl brennt anders.',
        'Es wurde schon geschrien. Es waren schon Leute auf der Straße mit Eimern und Decken, und jemand schlug mit einem Stock gegen die bronzene Platte am Brunnen, und Tala rannte ohne Schuhe die Treppe hinunter.',
        'Ihre Mutter packte sie in der Tür am Arm.',
        '„Nicht dahin.“',
        '„Aber—“',
        '„Tala.“ Ihre Mutter hielt sie mit beiden Händen fest. „Unsere Tür. Sofort.“',
        'Und Tala begriff.',
        'Wenn es überspringt, dann zu ihnen. Hundert Krüge — neunundneunzig — mit Öl, hinter einer Holztür, an derselben Mauer.',
        'Sie rannte zum Lager, zog die Schnur über den Kopf und steckte den Schlüssel ins Schloss. Ihre Hände waren so nass, dass die Bronze wegdrehte. Beim dritten Mal gelang es.',
        'Die Tür ging auf. Die Kühle kam ihr entgegen, und der Geruch.',
        'Hinter ihr fing die ganze Straße an, Krüge zu tragen.',
        'Sie trugen sie in den Innenhof, zum Brunnen, auf die Straße, überallhin, wo keine Mauer brannte. Die Nachbarn trugen mit, Menschen, die sie kaum kannte, Menschen, mit denen ihr Vater nie gesprochen hatte. Jemand hatte eine Leiter. Jemand warf Decken ins Wasser des Brunnens und reichte sie weiter.',
        'Tala trug, bis ihre Arme nicht mehr wollten, und dann trug sie weiter.',
        'Beim siebzigsten Krug sah sie Yidir. Er kam mit vier anderen aus der Schmiede und sie schleppten etwas, das aussah wie ein langer Haken.',
        'Beim fünfundachtzigsten stürzte das Dach von Quintus’ Lager ein.',
        'Beim letzten ging die Sonne schon fast auf.',
        'Da war kein Feuer mehr. Da war nur Rauch, der tief über der Straße hing, und zweihundert Menschen, die zusahen, ohne etwas zu sagen, und schwarze Hände, und irgendwo ein Kind, das weinte.',
        'Tala saß auf der Stufe an ihre Mutter gelehnt.',
        'Und deshalb sah sie als Einzige den Mann, der aus der Gasse neben Quintus’ Haus kam, gegen den Strom, den Mantel über dem Arm statt um die Schultern.',
        'Der Mantel war rot.',
      ] },
      { titel: 'Der rote Mantel', tekst: [
        'Sie erzählte es Yidir, bevor sie es irgendwem sonst erzählte.',
        'Er hörte es sich an, ohne sie zu unterbrechen, und als sie fertig war, sagte er: „Das ist immer noch nichts.“',
        '„Ich habe ihn gesehen.“',
        '„Du hast einen Mann mit einem roten Mantel gesehen, in einer Straße voller Leute mit Ruß im Gesicht.“ Yidir trat gegen einen Stein. „Ich glaube dir. Der Rat nicht.“',
        'Tala wusste, dass er recht hatte, und sie hatte genug davon, dass er immer recht hatte.',
        '„Was denn?“, sagte sie. „Ich kann doch nicht nichts tun.“',
        '„Nein“, sagte Yidir. „Aber du brauchst etwas, das nicht von dir kommt.“',
        'Er setzte sich auf den Brunnenrand, die Fersen gegen den Stein.',
        '„Am Tor schreiben sie alles auf“, sagte er. „Auf Wachs. Was hinausgeht, wie viel, und von wem. Diese Täfelchen gehen jeden Monat zum Rathaus.“',
        '„Und wenn nichts Seltsames draufsteht?“',
        '„Dann steht nichts Seltsames drauf“, sagte Yidir. „Und dann weißt du, dass es nicht in den Büchern steckt, sondern im Dunkeln. Das ist auch etwas.“',
        'Er sah sie an.',
        '„Aber wenn doch etwas draufsteht — wenn da zwölf Krüge stehen, während dreizehn durch das Tor gingen — dann ist das kein Kind, das etwas gesehen hat. Dann ist das eine Zahl neben einer Zahl, und Zahlen redet niemand weg.“',
        'Tala dachte an die Nacht auf dem Dach. An den Mann, der nicht unter das Stroh gesehen hatte.',
        '„Wer kann diese Täfelchen einsehen?“',
        '„Wir nicht.“',
        '„Wer dann?“',
        'Yidir schwieg kurz.',
        '„Mein Meister“, sagte er. „Er liefert das Eisen für die Schlösser des Rathauses. Er kommt da hinein, ohne dass jemand fragt, warum.“',
        '„Dann frag ihn.“',
        '„Er ist keiner, der sich mit dem Aufseher anlegt.“',
        '„Frag ihn“, sagte Tala noch einmal.',
        'Yidir sah auf seine schwarzen Hände.',
        '„Gut“, sagte er. „Aber nicht heute Abend. Heute Abend ist Markt-Freitag und da ist er schlecht gelaunt.“',
        'Trotz allem musste Tala lachen.',
        'Es war das erste Mal seit Tagen.',
      ] },
      { titel: 'Was auf dem Wachs stand', tekst: [
        'Der Schmied hieß Amanar und er war der größte Mann, den Tala je aus der Nähe gesehen hatte.',
        'Er sagte zwei Tage lang nichts. Dann kam er am dritten Morgen in die Säulenstraße, ein Päckchen unter dem Arm, und setzte sich auf die Stufe des Lagers, als gehörte sich das so.',
        '„Du bist die Tochter von Yuba“, sagte er.',
        '„Ja.“',
        '„Dein Vater hat meiner Mutter einmal einen Winter lang Öl gegeben, ohne dafür bezahlen zu lassen.“ Amanar sah die Straße hinunter. „Das ist sechzehn Jahre her. Ich habe es nicht vergessen und er weiß nicht mehr, dass er es getan hat.“',
        'Er legte das Päckchen auf die Stufe.',
        'Es waren zwei Wachstäfelchen in einem Holzrahmen, Kratzer über Kratzer über Kratzer.',
        '„Ansehen ja“, sagte Amanar. „Mitnehmen nein. Sie liegen in einer Stunde wieder, wo sie hingehören.“',
        'Tala setzte sich und las.',
        'Sie konnte lesen. Nicht flüssig, aber genug. Ihr Vater hatte darauf bestanden: „Wer nicht lesen kann, glaubt, was ein anderer sagt, dass da steht.“',
        'Auf dem Wachs standen Reihen. Datum, Tor, was, wie viel, wessen.',
        'Sie suchte ihren eigenen Namen. Sie fand ihn elfmal.',
        '*Yuba, Ölmüller, Säulenstraße. Acht Krüge.*',
        '*Yuba, Ölmüller. Zwölf Krüge.*',
        '*Yuba, Ölmüller. Neun Krüge.*',
        'Tala zählte zusammen. Sie zählte zweimal und beim zweiten Mal schrieb sie es in den Sand neben ihren Füßen.',
        'Hundertsiebzehn Krüge. In vier Wochen, zum Tor hinaus, auf den Namen ihres Vaters.',
        'Sie sah auf.',
        '„Das stimmt nicht“, sagte sie.',
        '„Nein?“, sagte Amanar.',
        '„Wir haben in dieser Saison hundertsechzig gemacht. Ich weiß es genau, ich habe sie gezählt, als sie gebrannt wurden. Sechzig sind in der Stadt verkauft worden. Hundert standen im Lager.“ Sie zeigte auf den Sand. „Hundertsechzig. Nicht hundertsiebenundsiebzig.“',
        'Amanar sagte nichts.',
        '„Es sind siebzehn Krüge durch das Tor gegangen, die wir nie gemacht haben“, sagte Tala. „Auf unseren Namen.“',
        'Sie hörte selbst, was das bedeutete, während sie es sagte.',
        'Es waren nicht nur ihre Krüge, die gestohlen wurden.',
        'Es war ihr Name.',
        'Wenn später im Rathaus gezählt wurde und weniger ankam, als durch das Tor hinausgegangen war, dann gäbe es ein Haus, in dem die Spur endete. Und dieses Haus war ihres.',
        '„Amanar“, sagte sie, und ihre Stimme klang seltsam. „Sie stellen uns hin.“',
        'Der Schmied stand auf und klopfte sich den Staub von den Knien.',
        '„Ja“, sagte er. „Das tun sie.“',
        'Er nahm die Täfelchen auf.',
        '„Komm morgen mit deiner Mutter zum Platz. Und bring den Sand mit, oder nein — schreib es auf etwas ab, das nicht wegweht.“',
      ] },
      { titel: 'Zwei Zahlen nebeneinander', tekst: [
        'Der Rat tagte wie immer: fünf Männer, ein Schreiber, und das Gemurmel von Leuten, die warteten, bis es um sie ging.',
        'Diesmal stand Tala nicht allein da.',
        'Links von ihr stand ihre Mutter, in dem Kleid, das sie nur trug, wenn etwas Schlimmes oder etwas Schönes war. Rechts von ihr stand Amanar, und hinter Amanar standen vier Männer aus der Schmiede, die damit nichts zu tun hatten und trotzdem da waren.',
        'Weiter hinten, an einer Säule, stand Yidir.',
        'Der Älteste des Rates — der mit dem Gesicht wie eine getrocknete Feige — sah die Gruppe an und zog die Augenbrauen hoch.',
        '„Du schon wieder“, sagte er zu Tala.',
        '„Ich habe gezählt“, sagte Tala.',
        'Sie hatte es auf ein Stück Leder geschrieben, denn Leder weht nicht weg. Sie las es vor. Was sie gemacht hatten. Was in der Stadt verkauft worden war. Was im Lager stand. Und danach, was den Täfelchen am Tor zufolge auf den Namen ihres Vaters aus der Stadt gegangen war.',
        'Zwei Zahlen.',
        'Als sie fertig war, war es still auf eine andere Art als beim letzten Mal.',
        'Marcus trat vor. Er war immer noch ruhig, aber nicht mehr auf dieselbe Weise.',
        '„Ein Kind hat in die Stadttäfelchen gesehen“, sagte er. „Das ist verboten.“',
        '„Ich habe sie gebracht“, sagte Amanar.',
        'Es wurde noch stiller.',
        'Der Älteste des Rates wandte sich an den Schreiber neben sich.',
        '„Hol sie.“',
        'Es dauerte lange. Niemand ging weg. Jemand gab Talas Mutter einen Hocker und sie setzte sich nicht darauf.',
        'Als die Täfelchen da waren, las der Schreiber laut vor, was darauf stand, und ein anderer Mann zählte mit Steinen auf einem Brett zusammen, und alle auf dem Platz hörten es.',
        'Hundertsiebzehn.',
        'Der Älteste sah lange auf die Zahlen, und danach auf Marcus, und danach wieder auf die Zahlen.',
        '„Wer schreibt am Nordtor?“, fragte er.',
        '„Das wechselt“, sagte Marcus.',
        '„Wer bestimmt, wer schreibt?“',
        'Marcus antwortete nicht.',
        'Der Älteste seufzte, und es war der Seufzer eines Mannes, der etwas begreift, das er lieber nicht begriffen hätte, und der weiß, dass er jetzt etwas damit tun muss.',
        '„Setz dich“, sagte er zu Tala. „Du nicht, Marcus. Du bleibst stehen.“',
      ] },
      { titel: 'Was übrig bleibt', tekst: [
        'Es dauerte noch drei Wochen, bis sich wirklich etwas änderte, und das war die längste Lehre jenes Sommers: dass die Wahrheit nicht so funktioniert wie in einer Geschichte, wo man sie sagt und alle nicken.',
        'Es kam ein Mann aus der Mutterstadt von Volubilis, um die Bücher zu prüfen. Es wurden Leute angehört. Zweimal wurde nichts gesagt und einmal etwas, das niemand erwartet hatte: der Wächter des Nordtors, ein Junge von neunzehn Jahren, brach bei der dritten Frage zusammen und erzählte alles.',
        'Marcus verschwand, bevor es abgeschlossen war. Sein Haus stand einen Monat leer und wurde dann jemand anderem gegeben.',
        'Talas Vater wurde nicht mehr gesund, nicht ganz. Er konnte im Herbst wieder im Innenhof sitzen und die Presse knarren hören, und damit schien er zufrieden. Er fragte nach den Zahlen und sie nannte sie ihm. Er ließ sie dreimal erzählen, was auf dem Platz geschehen war, und beim dritten Mal weinte er, und das hatte sie ihn noch nie tun sehen.',
        'Die Ernte ging zum Hafen. Hundert Krüge. Es stimmte.',
        'In der Woche darauf kam Yidir mit seiner Großmutter vorbei.',
        'Seine Großmutter war klein und alt und hatte Augen wie jemand, der viel weiter sieht als bis dahin, wo sie steht. Sie sagte, sie gehe fort: zurück zu ihrer Familie, auf die Weiden in den Bergen, bevor es Winter würde. Sie sagte es, als spräche sie von einem Spaziergang.',
        '„Yidir kommt mit“, sagte sie. „Eine Weile.“',
        'Tala sah Yidir an. Yidir sah auf seine Hände.',
        '„Wie lang ist eine Weile?“, fragte sie.',
        '„Das weißt du erst hinterher“, sagte seine Großmutter.',
        'An diesem Abend zog Tala die Schnur über den Kopf.',
        'Der Schlüssel war warm, wie immer. Acht Zacken im Kopf, ein Stern. Ihr Großvater hatte ihn in einer Schmiede geschmiedet, die es jetzt nicht mehr gab.',
        'Sie hielt ihn in der Hand und dachte an das, was ihr Vater gesagt hatte. *Diese Tür geht für nichts anderes auf.*',
        'Sie gab ihn Yidir.',
        '„Das geht nicht“, sagte er sofort.',
        '„Du hast mir geglaubt, als mir niemand geglaubt hat.“',
        '„Das ist keinen Schlüssel wert.“',
        '„Es ist mein Schlüssel“, sagte Tala. „Ich bestimme, was er wert ist.“',
        'Yidir hielt ihn fest, als wäre er zu heiß.',
        '„Was soll ich damit?“',
        '„Weiß ich nicht“, sagte Tala. „Weggeben, denke ich. An jemanden, dem du glaubst.“',
        'Sie gingen am nächsten Morgen fort, mit drei Eseln und einem Hund, in die Hügel, und Tala stieg auf das Dach des Badehauses und sah ihnen nach, bis sie nicht mehr zu sehen waren.',
        'Sie wusste damals noch nicht, dass es gut war, dass der Schlüssel fortging.',
        'Denn Walili würde nicht immer da sein. Das Erdbeben kam viel später, und die Stadt wurde langsam abgetragen — Stein für Stein, bis nichts übrig blieb als die Säulen, die Ölpressen und die Mosaikböden, die heute noch da liegen, unter freiem Himmel, bei Meknès.',
        'Alles, was in den Häusern stand, ist verschwunden.',
        'Nur der Schlüssel nicht.',
      ] },
    ],
  },
}
