import type { Hoofdstuk } from './sleutels'

/** Deel 9 — Het paleis van suiker. Marrakech, 1578–1603. */
export const DEEL9_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Tegels', tekst: [
    'Lalla was twaalf en ze kon zellige zetten, en er waren in Marrakech niet veel meisjes van wie je dat kon zeggen.',
    'Zellige is dit: je hakt uit een geglazuurde tegel een vorm. Een ster, een ruit, een stuk van een achthoek. Dan leg je die vormen omgekeerd in een patroon, met de glazuurkant naar beneden, zodat je niet ziet wat je maakt. Pas als het af is en je giet er gips overheen en je draait het om, zie je het.',
    'Je werkt dus blind aan iets waarvan je het resultaat pas achteraf ziet.',
    'Haar vader zei dat dat de hele kunst was: onthouden hoe het eruitziet terwijl je het niet kunt zien.',
    'In het jaar dat de nieuwe sultan aan de macht kwam, kregen ze werk waar heel Marrakech over praatte.',
    'Er kwam een paleis.',
    'Niet zomaar een paleis. De sultan had er een naam voor bedacht voordat er een steen lag: el Badi. De onvergelijkelijke.',
  ] },
  { nummer: 2, titel: 'Waar het van betaald werd', tekst: [
    'Het eerste wat Lalla opviel, was het marmer.',
    'Het kwam uit Italië, over zee, in blokken die met acht man gedragen moesten worden.',
    '“Wat kost dat?” vroeg ze aan haar vader.',
    '“Suiker,” zei hij.',
    'Ze dacht dat het een grap was.',
    'Het was geen grap. Het verhaal ging — en het staat ook zo in de boeken van die tijd — dat er betaald werd met suiker van hetzelfde gewicht als het marmer. Marokkaanse suiker, uit de rietvelden in het zuiden, was in Europa een luxe waar vorsten om vochten.',
    'Wat er verder betaald moest worden, kwam uit iets anders.',
    'In 1591 stuurde de sultan een leger door de Sahara naar het zuiden, naar het rijk van Songhai aan de rivier de Niger. Vierduizend man, dwars door de woestijn, wat op zichzelf al bijna niet kon.',
    'Ze kwamen terug met goud en met zout en met mensen.',
    'Timboektoe was tot dat moment een stad van geleerden geweest, met bibliotheken en scholen. Daarna was het dat niet meer.',
    'Lalla heeft dat als kind niet geweten. Ze wist dat er goud kwam.',
  ] },
  { nummer: 3, titel: 'Vijfentwintig jaar', tekst: [
    'Er is vijfentwintig jaar aan gebouwd.',
    'Dat is een zin die je leest en die je niet voelt. Lalla was twaalf toen ze begon en zevenendertig toen het af was. Ze trouwde tijdens de bouw. Ze kreeg drie kinderen tijdens de bouw. Haar vader stierf tijdens de bouw, en haar oudste zoon zette tegels naast haar in het laatste jaar.',
    'Wat er kwam te staan, was het volgende.',
    'Een binnenhof van honderdvijfendertig meter lang. Vier grote vijvers, met in het midden één waar je in kon zwemmen. Tuinen die verzonken lagen, zodat je over de toppen van sinaasappelbomen uitkeek. Paviljoens met namen als De Kristallen Koepel.',
    'Zevenendertighonderd kilo goud, zeggen sommige bronnen, in de plafonds.',
    'En zellige. Kilometers zellige. Lalla heeft er nooit uitgerekend hoeveel tegels er door haar handen zijn gegaan en ze heeft er ook nooit zin in gehad.',
    'Op de dag dat het klaar was, was er een feest waar iedereen over sprak.',
    'De sultan vroeg aan zijn gasten wat ze ervan vonden. Iedereen zei wat je zegt.',
    'Er was één man, een nar of een geleerde — daar verschillen de verhalen over — die zei: “Het zal een mooie ruïne zijn.”',
  ] },
  { nummer: 4, titel: 'Wat er in de muur ging', tekst: [
    'Het jaar daarvoor, bij de oostmuur, deed Lalla iets wat haar vader haar had geleerd.',
    'Hij had gezegd: als je aan iets werkt dat langer blijft staan dan jij, laat er dan iets van jezelf in achter. Niet je naam — je naam doet er niet toe. Iets wat van jou was.',
    'Ze had een sleutel.',
    'Hij was van brons, met acht punten aan de kop, en haar vader had hem jaren geleden gekocht van een jongen die net uit het noorden was gekomen. Ze had hem altijd bij zich gehad in de zak van haar schort, en ze wist niet meer waarom.',
    'Achter een rij tegels, waar de muur hol was voor de leidingen, legde ze hem neer.',
    'Toen zette ze de tegels erover.',
    'Omgekeerd, met de glazuurkant naar beneden, zoals altijd: ze zag pas wat ze had gemaakt toen het gips droog was en het geheel werd omgedraaid.',
    'Het was een ster met acht punten.',
    'Dat was niet met opzet. Dat patroon zit overal in Marrakech.',
  ] },
  { nummer: 5, titel: 'De mooie ruïne', tekst: [
    'De sultan stierf in 1603, aan de pest.',
    'Daarna vochten zijn zonen om wat hij had nagelaten, en dat duurde jaren, en het land raakte het grootste deel van zijn rijkdom kwijt.',
    'Het paleis bleef staan, leger en leger.',
    'Honderd jaar later kwam er een sultan die in Meknès een nieuwe hoofdstad wilde bouwen: Moulay Ismail. Hij had marmer nodig, en cederhout, en goud.',
    'Hij liet het Badi-paleis afbreken.',
    'Niet vernielen — uit elkaar halen, stuk voor stuk, en alles wat bruikbaar was op karren naar het noorden. Het duurde jaren. Er zijn er die zeggen tien.',
    'Wat er overbleef, is wat er nu nog staat: muren van rode aarde, de omtrek van de vijvers, een binnenhof waar ooievaars nestelen, en geen dak.',
    'Je kunt er vandaag naartoe. Het kost een paar dirham.',
    'De man die zei dat het een mooie ruïne zou worden, had gelijk, en hij heeft het zelf niet meer gezien.',
  ] },
  { nummer: 6, titel: 'Wat een muur loslaat', tekst: [
    'Lalla was oud toen ze hoorde dat het paleis werd afgebroken, en haar kleinkinderen hebben verteld dat ze er niet van opkeek.',
    'Ze zei: “Ik heb er vijfentwintig jaar aan gewerkt. Het heeft er honderd gestaan. Dat is vier keer zoveel.”',
    'Dat was het enige wat ze erover kwijt wilde.',
    'Toen de oostmuur werd gesloopt, kwamen de tegels los en viel er van alles uit de holle ruimte: stukken leiding, een lap, en iets van brons.',
    'Een sloper raapte het op.',
    'Hij hield het tegen de zon, zag dat er geen goud aan zat, en gooide het in de kar met rommel die naar de markt ging.',
    'Daar is het gekocht door een man uit Essaouira.',
    'Alleen heette Essaouira toen nog niet Essaouira, want de stad bestond nog niet.',
  ] },
]
