import type { Hoofdstuk } from './sleutels'

/**
 * Deel 1 — De olijvenbrand. Walili, rond het jaar 200.
 *
 * Wordt hoofdstuk voor hoofdstuk geschreven; wat er staat is af, wat er niet
 * staat komt nog. Een boek van honderd bladzijden in één zitting schrijven
 * levert honderd vlakke bladzijden op.
 */
export const DEEL1_HOOFDSTUKKEN: Hoofdstuk[] = [
  {
    nummer: 1,
    titel: 'De sleutel',
    tekst: [
      'Tala werd wakker van de geur.',
      'Olijven. Geperste olijven, warm en bitter. De hele stad rook er in deze weken naar. Ze bleef even liggen en luisterde. Buiten kraakte de grote pers al. Dat betekende dat ze te laat was.',
      'Ze sprong van haar bed en trok haar jurk over haar hoofd.',
      '“Tala!” riep haar moeder van beneden. “De poort!”',
      'De poort. Natuurlijk de poort.',
      'Sinds haar vader ziek was geworden, deed Tala zijn werk. Elke ochtend liep ze naar de opslag achter het huis en maakte de deur open. Daar stonden de kruiken. Honderd kruiken, tot de rand gevuld met olie, klaar om naar de haven te gaan.',
      'De sleutel hing aan een koord om haar nek. Hij was van brons en zo lang als haar hand. Haar opa had hem gesmeed, lang voordat zij er was. In de kop zaten acht punten, als een ster.',
      '“Verlies hem niet,” had haar vader gezegd. Hij had het zachtjes gezegd, want harder kon hij niet meer. “Die deur gaat nergens anders voor open.”',
      'Tala rende de trap af, langs de keuken, de binnenplaats over. Het was nog vroeg. De zon stond net boven de heuvels en de stenen waren koud onder haar voeten.',
      'Bij de opslag stond een man.',
      'Ze bleef staan.',
      'Hij was groot en hij droeg de rode mantel van de opzichter. Marcus. Iedereen in Walili kende Marcus, en niemand vond hem aardig.',
      '“Je bent laat,” zei hij.',
      '“Ik ben op tijd,” zei Tala.',
      'Ze wist dat ze dat niet had moeten zeggen. Ze zei het toch.',
      'Marcus keek haar aan. Toen stak hij zijn hand uit.',
      '“Geef mij die sleutel maar. Een kind hoort niet op honderd kruiken te passen.”',
      'Tala deed een stap naar achteren.',
      'In haar hoofd hoorde ze haar vader. *Die deur gaat nergens anders voor open.* En ze dacht aan iets anders, iets wat ze gisteren had gezien en waarvan ze had gedacht dat het niets was.',
      'Twee kruiken die niet op hun plaats stonden.',
      '“Nou?” zei Marcus.',
      'Tala kneep haar hand om het brons. Het was warm geworden van haar huid.',
      '“Nee,” zei ze.',
    ],
  },
  {
    nummer: 2,
    titel: 'Twee kruiken',
    tekst: [
      'Marcus lachte niet. Hij werd ook niet boos. Dat was het ergste.',
      'Hij liet zijn hand zakken, trok zijn mantel recht en zei: “Zoals je wilt.” Toen liep hij weg, de steeg uit, zonder om te kijken.',
      'Tala bleef staan tot ze zijn voetstappen niet meer hoorde. Pas daarna merkte ze dat haar handen trilden.',
      'Ze deed de deur open.',
      'Binnen was het donker en koel. De kruiken stonden in rijen van tien, met stro ertussen zodat ze niet tegen elkaar sloegen. Tien rijen van tien. Elke ochtend telde ze ze. Dat had haar vader haar geleerd toen ze zes was, en toen was het nog een spelletje.',
      'Ze begon links en telde hardop, zoals altijd.',
      'Bij de achterste rij hield ze op.',
      'Er stonden er negen.',
      'Tala telde opnieuw. Negen. Ze liep om de rij heen, bukte, keek achter het stro. Negen.',
      'Gisteren had ze ook iets vreemds gezien. Twee kruiken die verkeerd stonden, met de handvatten naar de muur in plaats van naar het pad. Ze had gedacht: dat heeft iemand haastig gedaan. Ze had ze rechtgezet en er niet meer aan gedacht.',
      'Nu stond er één minder.',
      'Ze ging in de deuropening zitten met haar rug tegen de post en haar knieën opgetrokken, en probeerde te bedenken wat ze moest doen.',
      'Ze kon het aan haar moeder vertellen. Maar haar moeder had deze maand al genoeg: een zieke man boven, een huis vol mensen die betaald moesten worden, en een oogst die over drie weken naar de haven moest.',
      'Ze kon het aan Marcus vertellen. Marcus was de opzichter. Dat was zijn werk.',
      'Tala keek naar de steeg waar hij was verdwenen.',
      'Nee.',
      '“Je zit in de weg,” zei een stem.',
      'Ze schrok op. Voor haar stond een jongen van ongeveer haar leeftijd, met een leren schort voor en zijn armen vol takkenbossen. Zijn handen zaten onder het zwart.',
      '“Ik zit niet in de weg,” zei Tala. “Dit is mijn deur.”',
      '“Dan zit je in de weg van je eigen deur.”',
      'Hij heette Yidir en hij werkte bij de smidse aan het eind van de straat. Tala kende hem van gezicht zoals je iedereen in Walili van gezicht kende, en verder niet.',
      'Ze stond op om hem erlangs te laten. Hij liep niet door.',
      '“Je telt elke ochtend,” zei hij.',
      '“Hoe weet jij dat?”',
      '“Ik loop elke ochtend langs.”',
      'Tala aarzelde. Toen zei ze het toch, omdat het eruit moest en omdat hij er nu eenmaal stond.',
      '“Er is er één weg.”',
      'Yidir zette zijn takkenbossen op de grond.',
      '“Eén?” zei hij. “Dan heb je geluk gehad. Bij ons zijn er zes ijzeren staven weg.”',
    ],
  },
  {
    nummer: 3,
    titel: 'Hoe je olie maakt',
    tekst: [
      'Die middag stond Tala bij de pers, zoals elke dag in de oogst.',
      'De pers was een uitgeholde steen zo groot als een kar, met een ronde steen erin die door een ezel werd rondgetrokken. De olijven gingen erin, werden gekraakt, en wat eruit kwam was een dikke bruine massa die naar niets leek.',
      'Dat was het deel dat vreemden altijd teleurstelde. “Is dát olie?” vroegen ze dan. Nee. Dat was het begin.',
      'De massa ging in ronde matten van gevlochten riet. Die matten werden op elkaar gestapeld onder de balkpers, en dan draaiden twee mannen aan de schroef, langzaam, alsof ze de tijd hadden. Onder de stapel liep een geul.',
      'Daar kwam het uit.',
      'Eerst water, troebel en vies. Dan, na een tijd, iets anders. Iets dat op het water bleef drijven en groener was dan alles wat Tala kende.',
      'Haar vader had haar de eerste keer bij haar nek gepakt en haar hoofd erboven gehouden. “Ruik,” had hij gezegd. “Dat is het. Als het zó ruikt, is het goed. Als het naar niets ruikt, heb je te lang gewacht.”',
      'Ze had toen gelogen dat ze het rook. Nu rook ze het echt.',
      'Walili leefde hiervan. Niet van de mozaïekvloeren waar bezoekers over liepen, niet van de zuilen op het plein, niet van de stenen straten. Van dit. Van geperste olijven die in kruiken gingen, op karren naar de kust, en op schepen naar plekken waarvan Tala alleen de namen kende.',
      'Ze lette op de geul en op de matten en op de ezel, en ondertussen dacht ze aan negenennegentig kruiken.',
      'Zes ijzeren staven, had Yidir gezegd. Uit de smidse.',
      'IJzer was duur. Olie was duur. En allebei gingen ze in dezelfde richting de stad uit: over de weg naar de haven.',
      '“Tala.” Een van de mannen wees naar de geul. “Hij loopt over.”',
      'Ze schoot naar voren en schoof de kom eronder, te laat. Een straal olie liep over de steen en verdween tussen de voegen.',
      'Een vinger dik, misschien twee. Genoeg voor een gezin voor een week.',
      'De man zei er niets van. Dat maakte het erger.',
    ],
  },
  {
    nummer: 4,
    titel: 'Wat een opzichter mag',
    tekst: [
      'Marcus kwam terug op de derde dag, en hij kwam niet alleen.',
      'Tala zag hem de binnenplaats op lopen met twee mannen achter zich. Haar moeder kwam naar buiten, veegde haar handen af aan haar jurk, en ging precies tussen hem en de deur staan.',
      '“Vrede,” zei Marcus.',
      '“Vrede,” zei haar moeder, op de toon waarop je dat zegt als je het niet meent.',
      '“Je man is ziek.”',
      '“Mijn man rust.”',
      '“Drie weken,” zei Marcus. “Over drie weken gaat de oogst naar de haven, en de stad rekent op wat er in dit huis staat. Ik moet weten dat het er is.”',
      '“Het is er.”',
      '“Ik wil het zien.”',
      'Er viel een stilte. Tala stond in de deuropening van de keuken en durfde zich niet te bewegen.',
      'Haar moeder zei: “Je mag kijken. Mijn dochter doet open.”',
      'Tala liep de binnenplaats over onder de ogen van vijf mensen. Ze haalde het koord over haar hoofd, stak de sleutel in het slot en duwde de deur open.',
      'Marcus ging naar binnen. Hij liep langs de rijen, langzaam, met zijn handen op zijn rug. Bij de achterste rij bleef hij staan.',
      'Tala hield haar adem in.',
      '“Negenennegentig,” zei Marcus.',
      'Hij draaide zich om en keek haar moeder aan.',
      '“Er hoort er honderd te staan.”',
      'Haar moeder verstijfde. Tala zag het aan haar schouders.',
      '“Dan is er één gebroken,” zei ze.',
      '“Dan lagen er scherven.” Marcus spreidde zijn handen. “Ik zie geen scherven. Ik zie stro dat is rechtgetrokken.”',
      'Hij wachtte even, precies lang genoeg.',
      '“Ik zeg niet dat jullie stelen,” zei hij toen. “Ik zeg dat een kind van elf de sleutel heeft van honderd kruiken, en dat er vandaag negenennegentig staan. Dat zeg ik. En dat zal ik ook zeggen op het plein.”',
      'Hij liep de deur uit en langs Tala heen alsof ze een paal was.',
      'Toen hij weg was, ging haar moeder op de rand van de put zitten. Ze zei heel lang niets.',
      '“Mama,” zei Tala. “Ik heb hem niet—”',
      '“Ik weet het.”',
      '“Ik heb hem geteld op maandag en toen waren het er nog—”',
      '“Tala.” Haar moeder keek op. Haar ogen waren rood. “Ik weet het. En dat helpt ons niets.”',
    ],
  },
  {
    nummer: 5,
    titel: 'De smidse',
    tekst: [
      'Yidir zat op een omgekeerde emmer voor de smidse en schuurde een scharnier.',
      '“Je had gelijk,” zei Tala.',
      '“Dat zeggen mensen zelden tegen mij,” zei Yidir zonder op te kijken. “Waarover?”',
      '“Over dat het niet één kruik was.”',
      'Nu keek hij wel op.',
      'Tala ging naast hem op de drempel zitten en vertelde het. Over Marcus, over negenennegentig, over wat hij op het plein zou gaan zeggen. Yidir luisterde zoals hij alles deed: alsof hij ondertussen ergens anders aan dacht, maar hij miste niets.',
      '“En jouw ijzer?” vroeg ze.',
      '“Zes staven. Mijn meester denkt dat hij zich vergist heeft in het tellen.” Yidir haalde zijn schouders op. “Mijn meester vergist zich nooit in het tellen.”',
      '“Wanneer?”',
      '“Vorige week. En de week daarvoor drie.”',
      'Tala trok haar knieën op.',
      '“Wat gaat er uit de stad?” vroeg ze. “Elke dag, bedoel ik.”',
      'Yidir dacht na.',
      '“Karren,” zei hij. “Olie, graan, huiden, ijzer. Alles gaat over de weg naar het noorden. Er staat een wachtpost bij de poort. Daar wordt alles opgeschreven.”',
      '“Door wie?”',
      'Yidir keek haar aan.',
      '“Door de opzichter,” zei hij.',
      'Ze zeiden allebei een tijdje niets.',
      '“Dat bewijst niets,” zei Tala uiteindelijk.',
      '“Nee.”',
      '“Als ik dat zeg, zeggen ze dat een kind van elf een man beschuldigt omdat hij haar niet aardig vindt.”',
      '“Ja,” zei Yidir. “Dat zeggen ze.”',
      'Hij legde het scharnier weg.',
      '“Dus je hebt iets nodig wat ze niet kunnen wegpraten.”',
      '“Zoals?”',
      '“Zoals zien wat er ’s nachts door die poort gaat.”',
      'Tala keek naar hem. Hij keek terug, en voor het eerst sinds ze hem kende, lachte hij.',
    ],
  },
  {
    nummer: 6,
    titel: 'Wat er ’s nachts door de poort gaat',
    tekst: [
      'Ze lagen op het dak van het badhuis, plat op hun buik, met hun kin op hun armen.',
      'Het dak was warm van de dag. Onder hen lag de straat die naar de noordelijke poort liep, breed genoeg voor twee karren naast elkaar. Bij de poort brandde één lamp.',
      '“Hoe lang nog?” fluisterde Tala.',
      '“Weet ik niet.”',
      '“Je zei dat er ’s nachts karren gaan.”',
      '“Ik zei dat ik dácht dat er ’s nachts karren gaan.”',
      'Tala zuchtte en legde haar hoofd op haar arm.',
      'De sterren waren die nacht ongelooflijk. In de stad zag je ze half, door het licht en de rook, maar hier boven waren het er zoveel dat het onrustig werd.',
      '“Mijn oma zegt dat ze een kaart zijn,” zei Yidir.',
      '“De sterren?”',
      '“Ja. Als je ze kunt lezen, kun je overal komen. Ze zegt dat haar familie zo van de woestijn naar hier is gelopen.”',
      '“Kun jij ze lezen?”',
      '“Nee,” zei Yidir. “Niemand heeft het me geleerd.”',
      'Toen hoorden ze het.',
      'Een kar. Geen twee ezels, geen paarden — één ezel, langzaam, en het geluid van hout dat kraakt onder gewicht.',
      'Tala schoof naar de rand.',
      'De kar kwam uit een zijstraat. Er liepen twee mannen naast, allebei met een doek om hun hoofd. Op de kar lag stro, en onder het stro stond iets dat rond was.',
      'Bij de poort stopte de kar.',
      'Uit het wachthuisje kwam een man met een lamp. Hij liep niet naar de kar toe. Hij liep naar de mannen, praatte kort met ze, en schreef iets op een tablet.',
      'Toen tilde hij de slagboom op.',
      'De kar reed de nacht in.',
      'Tala liet haar adem los. Ze had niet gemerkt dat ze hem inhield.',
      '“Hij heeft niet gekeken,” zei ze. “Hij heeft niet onder het stro gekeken.”',
      '“Nee.”',
      '“Dat is—”',
      '“Dat is nog steeds niets,” zei Yidir. “Dat is een man die niet goed genoeg kijkt. Daar hangt niemand voor.”',
      'Hij had gelijk, en dat wist Tala ook.',
      'Maar toen de kar de bocht om ging, gebeurde er iets. De ezel schrok van iets in het donker, trok opzij, en de kar sloeg met één wiel over de stoeprand.',
      'Er viel iets van de kar af.',
      'Het rolde, kwam tot stilstand tegen de muur, en bleef daar liggen.',
      'Een kruik.',
      'Een van de mannen vloekte, kwam teruglopen, raapte hem op en zette hem terug onder het stro. De kar reed verder.',
      'Maar Tala had gezien wat erop stond.',
      'Op de schouder van elke kruik uit hun huis zette haar vader een teken in de klei voordat hij gebakken werd. Acht punten. Een ster.',
      'Ze pakte Yidirs arm zo hard vast dat hij siste.',
      '“Die is van ons,” zei ze.',
    ],
  },
  {
    nummer: 7,
    titel: 'Wat je zegt en wat ze horen',
    tekst: [
      'De volgende ochtend ging Tala naar het plein.',
      'Ze had er de hele nacht over nagedacht, of in elk geval over de helft ervan; de andere helft had ze geslapen zonder het te willen. Ze wist wat ze ging zeggen. Ze had het drie keer geoefend tegen de muur van haar kamer.',
      'Op het plein, onder de zuilen, hield de raad zitting. Dat betekende: vijf mannen op stenen banken, een schrijver ernaast, en iedereen die iets te klagen had eromheen.',
      'Marcus stond er al.',
      'Tala wachtte tot een man over een muur en een buurman was uitgepraat. Toen stapte ze naar voren.',
      '“Ik wil iets zeggen,” zei ze.',
      'Vijf mannen keken op. Een van hen, de oudste, met een gezicht als een gedroogde vijg, boog zich naar voren.',
      '“Van wie ben jij er een?”',
      '“Van Yuba, de perser. Uit de Zuilenstraat.”',
      '“Die is ziek.”',
      '“Ja,” zei Tala. “Daarom sta ik hier.”',
      'Ze vertelde het. Over de kruik die weg was, en de dag erna nog een. Over de kar in de nacht en de man die de slagboom optilde zonder onder het stro te kijken. Over de kruik die eraf viel en over het teken met de acht punten.',
      'Ze vertelde het precies zoals ze het geoefend had, en terwijl ze het deed, hoorde ze het zelf ook.',
      'Ze hoorde hoe het klonk.',
      'Een kind. Een dak. Het donker. Een teken dat niemand anders had gezien.',
      'Toen ze klaar was, was het even stil. Toen zei Marcus, heel rustig: “Mag ik?”',
      'De oudste knikte.',
      '“Het meisje heeft gelijk dat er kruiken missen,” zei Marcus. “Dat heb ik zelf geteld, eergisteren, in hun eigen opslag. Negenennegentig van de honderd. Ik heb het toen ook gezegd.”',
      'Hij spreidde zijn handen, zoals hij dat deed.',
      '“Wie heeft de sleutel van die deur?”',
      'Niemand zei iets.',
      '“Zij,” zei Marcus. “Een kind van elf. En nu er één weg is, is het een kar in de nacht geweest. Een kar die alleen zij gezien heeft.”',
      'De oudste van de raad keek Tala aan, en zijn blik was niet onvriendelijk. Dat was nog het ergste.',
      '“Kind,” zei hij. “Ga naar huis. Zorg voor je vader.”',
      'Tala stond op het plein met haar handen langs haar lichaam en haar oren gloeiend, en om haar heen begon iedereen weer te praten over een muur en een buurman.',
    ],
  },
  {
    nummer: 8,
    titel: 'De brand',
    tekst: [
      'De brand begon vier dagen later, en hij begon niet bij hen.',
      'Tala werd er wakker van. Niet van licht en niet van geschreeuw — van geluid. Een diep, zacht gebrul, alsof er ergens heel dichtbij iemand heel lang uitademde.',
      'Ze was bij het raam voordat ze wakker was.',
      'Aan de overkant van de straat, twee huizen verder, stond de opslag van Quintus in brand. Quintus perste ook olie. Zijn kruiken stonden in een ruimte onder zijn huis, en daar kwam nu vuur uit het raam, plat, en niet omhoog zoals vuur hoort te doen.',
      'Dat komt door de olie, wist Tala later. Olie brandt anders.',
      'Er was al geschreeuw. Er waren al mensen op straat met emmers en dekens, en iemand sloeg met een stok tegen de bronzen plaat bij de put, en Tala rende de trap af zonder schoenen.',
      'Haar moeder greep haar bij haar arm in de deuropening.',
      '“Niet die kant op.”',
      '“Maar—”',
      '“Tala.” Haar moeder hield haar vast met beide handen. “Onze deur. Nú.”',
      'En Tala begreep het.',
      'Als het overslaat, dan naar hen. Honderd kruiken — negenennegentig — met olie, achter een houten deur, tegen dezelfde muur.',
      'Ze rende naar de opslag, haalde het koord over haar hoofd en stak de sleutel in het slot. Haar handen waren zo nat dat het brons wegdraaide. De derde keer lukte het.',
      'De deur ging open. De koelte kwam haar tegemoet, en de geur.',
      'Achter haar begon de hele straat kruiken te dragen.',
      'Ze droegen ze naar de binnenplaats, naar de put, naar de straat, overal heen waar geen muur brandde. De buren droegen mee, mensen die ze nauwelijks kende, mensen die haar vader nooit gesproken had. Iemand had een ladder. Iemand gooide dekens in het water van de put en gaf ze door.',
      'Tala droeg tot haar armen niet meer wilden en toen droeg ze nog.',
      'Bij de zeventigste kruik zag ze Yidir. Hij kwam met vier anderen van de smidse en ze sleepten iets mee dat op een lange haak leek.',
      'Bij de vijfentachtigste ging het dak van Quintus’ opslag naar binnen.',
      'Bij de laatste stond de zon al bijna op.',
      'Er was toen geen vuur meer. Er was alleen rook die laag over de straat hing, en tweehonderd mensen die stonden te kijken zonder iets te zeggen, en zwarte handen, en ergens een kind dat huilde.',
      'Tala zat op de stoep tegen haar moeder aan.',
      'En daarom zag zij als enige de man die uit de steeg naast Quintus’ huis kwam lopen, tegen de stroom in, met zijn mantel over zijn arm in plaats van om zijn schouders.',
      'De mantel was rood.',
    ],
  },
  {
    nummer: 9,
    titel: 'De rode mantel',
    tekst: [
      'Ze vertelde het aan Yidir voordat ze het aan wie dan ook vertelde.',
      'Hij hoorde het aan zonder haar te onderbreken, en toen ze klaar was, zei hij: “Dat is nog steeds niets.”',
      '“Ik heb hem gezien.”',
      '“Je hebt een man met een rode mantel gezien in een straat vol mensen met roet op hun gezicht.” Yidir schopte tegen een steen. “Ik geloof je. De raad niet.”',
      'Tala wist dat hij gelijk had en ze had er genoeg van dat hij altijd gelijk had.',
      '“Wat dan?” zei ze. “Ik kan toch niet niets doen.”',
      '“Nee,” zei Yidir. “Maar je moet iets hebben wat niet van jou komt.”',
      'Hij ging op de rand van de put zitten, met zijn hielen tegen de steen.',
      '“Bij de poort schrijven ze alles op,” zei hij. “Op was. Wat eruit gaat, hoeveel, en van wie. Die tabletten gaan elke maand naar het stadhuis.”',
      '“En als er niets vreemds op staat?”',
      '“Dan staat er niets vreemds op,” zei Yidir. “En dan weet je dat het niet in de boeken zit, maar in het donker. Dat is ook iets.”',
      'Hij keek haar aan.',
      '“Maar als er wél iets op staat — als daar twaalf kruiken staan terwijl er dertien de poort uit gingen — dan is dat geen kind dat iets gezien heeft. Dan is dat een getal naast een getal, en getallen praten niemand weg.”',
      'Tala dacht aan de nacht op het dak. Aan de man die niet onder het stro had gekeken.',
      '“Wie kan die tabletten inzien?”',
      '“Niet wij.”',
      '“Wie dan?”',
      'Yidir zweeg even.',
      '“Mijn meester,” zei hij. “Hij levert het ijzer voor de sloten van het stadhuis. Hij komt daar binnen zonder dat iemand vraagt waarom.”',
      '“Vraag het hem dan.”',
      '“Hij is niet iemand die zich met de opzichter bemoeit.”',
      '“Vraag het hem,” zei Tala nog een keer.',
      'Yidir keek naar zijn zwarte handen.',
      '“Goed,” zei hij. “Maar niet vanavond. Vanavond is het vrijdag van de markt en dan is hij chagrijnig.”',
      'Ondanks alles moest Tala lachen.',
      'Het was voor het eerst in dagen.',
    ],
  },
  {
    nummer: 10,
    titel: 'Wat er op de was stond',
    tekst: [
      'De smid heette Amanar en hij was de grootste man die Tala ooit van dichtbij had gezien.',
      'Hij zei twee dagen lang niets. Toen kwam hij op de derde ochtend de Zuilenstraat in lopen met een pakje onder zijn arm, en hij ging op de stoep van de opslag zitten alsof dat zo hoorde.',
      '“Jij bent de dochter van Yuba,” zei hij.',
      '“Ja.”',
      '“Je vader heeft mijn moeder ooit een winter lang olie gegeven zonder ervoor te laten betalen.” Amanar keek de straat in. “Dat was zestien jaar geleden. Ik ben het niet vergeten en hij weet niet meer dat hij het gedaan heeft.”',
      'Hij legde het pakje op de stoep.',
      'Het waren twee tabletten van was, in een houten lijstje, met kras op kras op kras.',
      '“Kijken mag,” zei Amanar. “Meenemen niet. Ze liggen over een uur terug waar ze horen.”',
      'Tala ging zitten en las.',
      'Ze kon lezen. Niet vlot, maar genoeg. Haar vader had erop gestaan: “Wie niet kan lezen, gelooft wat een ander zegt dat er staat.”',
      'Op de was stonden rijen. Datum, poort, wat, hoeveel, wiens.',
      'Ze zocht haar eigen naam. Ze vond hem elf keer.',
      '*Yuba, perser, Zuilenstraat. Acht kruiken.*',
      '*Yuba, perser. Twaalf kruiken.*',
      '*Yuba, perser. Negen kruiken.*',
      'Tala telde ze op. Ze telde twee keer en de tweede keer schreef ze het in het zand naast haar voeten.',
      'Honderdzeventien kruiken. In vier weken, de poort uit, op haar vaders naam.',
      'Ze keek op.',
      '“Dat klopt niet,” zei ze.',
      '“Nee?” zei Amanar.',
      '“We hebben er dit seizoen honderdzestig gemaakt. Ik weet het precies, ik heb ze geteld toen ze gebakken werden. Er zijn er zestig verkocht in de stad. Er stonden er honderd in de opslag.” Ze wees naar het zand. “Honderdzestig. Geen honderdzevenenzeventig.”',
      'Amanar zei niets.',
      '“Er zijn zeventien kruiken de poort uit gegaan die wij nooit gemaakt hebben,” zei Tala. “Op onze naam.”',
      'Ze hoorde zelf wat dat betekende, terwijl ze het zei.',
      'Het waren niet alleen hun kruiken die gestolen werden.',
      'Het was hun naam.',
      'Als er straks in het stadhuis geteld werd, en er kwam minder binnen dan er de poort uit was gegaan, dan zou er één huis zijn waar het spoor eindigde. En dat huis was het hunne.',
      '“Amanar,” zei ze, en haar stem deed raar. “Ze zijn ons aan het klaarzetten.”',
      'De smid stond op en veegde het stof van zijn knieën.',
      '“Ja,” zei hij. “Dat zijn ze.”',
      'Hij pakte de tabletten op.',
      '“Kom morgen met je moeder naar het plein. En neem dat zand mee, of nee — schrijf het over op iets wat niet wegwaait.”',
    ],
  },
  {
    nummer: 11,
    titel: 'Twee getallen naast elkaar',
    tekst: [
      'De raad hield zitting zoals altijd: vijf mannen, een schrijver, en het geroezemoes van mensen die wachtten tot het over hen ging.',
      'Deze keer stond Tala er niet alleen.',
      'Links van haar stond haar moeder, in de jurk die ze alleen droeg als er iets ergs of iets moois was. Rechts van haar stond Amanar, en achter Amanar stonden vier mannen van de smidse die er niets mee te maken hadden en er toch waren.',
      'Verderop, tegen een zuil, stond Yidir.',
      'De oudste van de raad — die met het gezicht als een gedroogde vijg — keek naar de groep en trok zijn wenkbrauwen op.',
      '“Jij weer,” zei hij tegen Tala.',
      '“Ik heb geteld,” zei Tala.',
      'Ze had het opgeschreven op een stuk leer, want leer waait niet weg. Ze las het voor. Wat ze gemaakt hadden. Wat er verkocht was in de stad. Wat er in de opslag stond. En daarna wat er volgens de tabletten bij de poort de stad uit was gegaan op naam van haar vader.',
      'Twee getallen.',
      'Toen ze klaar was, was het stil op een manier die anders was dan de vorige keer.',
      'Marcus stapte naar voren. Hij was nog steeds rustig, maar niet meer op dezelfde manier.',
      '“Een kind heeft in de stadstabletten gekeken,” zei hij. “Dat is verboden.”',
      '“Ik heb ze gebracht,” zei Amanar.',
      'Het werd nog stiller.',
      'De oudste van de raad wendde zich naar de schrijver naast hem.',
      '“Haal ze.”',
      'Het duurde lang. Niemand ging weg. Iemand gaf Tala’s moeder een kruk en ze ging er niet op zitten.',
      'Toen de tabletten er waren, las de schrijver hardop wat erop stond, en een andere man telde op met stenen op een bord, en iedereen op het plein hoorde het.',
      'Honderdzeventien.',
      'De oudste keek een hele tijd naar de getallen, en daarna naar Marcus, en daarna weer naar de getallen.',
      '“Wie schrijft er bij de noordpoort?” vroeg hij.',
      '“Dat wisselt,” zei Marcus.',
      '“Wie wijst aan wie er schrijft?”',
      'Marcus antwoordde niet.',
      'De oudste zuchtte, en het was de zucht van een man die iets begrijpt wat hij liever niet had begrepen, en die weet dat hij er nu iets mee moet.',
      '“Ga zitten,” zei hij tegen Tala. “Niet jij, Marcus. Jij blijft staan.”',
    ],
  },
  {
    nummer: 12,
    titel: 'Wat er overblijft',
    tekst: [
      'Het duurde nog drie weken voordat er echt iets veranderde, en dat was de langste les van die zomer: dat de waarheid niet werkt zoals in een verhaal, waar je hem zegt en iedereen knikt.',
      'Er kwam een man uit Volubilis’ moederstad om de boeken na te kijken. Er werden mensen gehoord. Er werd twee keer niets gezegd en één keer iets gezegd wat niemand had verwacht: de wachter van de noordpoort, een jongen van negentien, brak bij de derde vraag en vertelde alles.',
      'Marcus verdween voordat het afgerond was. Zijn huis stond een maand leeg en werd toen aan iemand anders gegeven.',
      'Tala’s vader werd niet meer beter, niet helemaal. Hij kon in het najaar weer op de binnenplaats zitten en de pers horen kraken, en daar leek hij tevreden mee. Hij vroeg naar de getallen en zij vertelde ze hem. Hij liet haar drie keer vertellen wat er op het plein was gebeurd, en de derde keer huilde hij, en dat had ze hem nog nooit zien doen.',
      'De oogst ging naar de haven. Honderd kruiken. Het klopte.',
      'In de week erna kwam Yidir langs met zijn oma.',
      'Zijn oma was klein en oud en ze had ogen als van iemand die veel verder kijkt dan waar ze staat. Ze zei dat ze wegging: terug naar haar familie, naar de weiden in de bergen, voordat het winter werd. Ze zei het alsof ze het over een wandeling had.',
      '“Yidir gaat mee,” zei ze. “Een tijdje.”',
      'Tala keek naar Yidir. Yidir keek naar zijn handen.',
      '“Hoe lang is een tijdje?” vroeg ze.',
      '“Dat weet je pas achteraf,” zei zijn oma.',
      'Die avond haalde Tala het koord over haar hoofd.',
      'De sleutel was warm, zoals altijd. Acht punten in de kop, een ster. Haar opa had hem gesmeed in een smidse die nu niet meer bestond.',
      'Ze hield hem in haar hand en dacht aan wat haar vader gezegd had. *Die deur gaat nergens anders voor open.*',
      'Ze gaf hem aan Yidir.',
      '“Dat kan niet,” zei hij meteen.',
      '“Jij hebt me geloofd toen niemand me geloofde.”',
      '“Dat is geen sleutel waard.”',
      '“Het is mijn sleutel,” zei Tala. “Ik bepaal wat hij waard is.”',
      'Yidir hield hem vast alsof hij te heet was.',
      '“Wat moet ik ermee?”',
      '“Weet ik niet,” zei Tala. “Weggeven, denk ik. Aan iemand die je gelooft.”',
      'Ze gingen de volgende ochtend weg, met drie ezels en een hond, de heuvels in, en Tala klom op het dak van het badhuis om ze na te kijken tot ze niet meer te zien waren.',
      'Ze wist toen nog niet dat het goed was dat de sleutel wegging.',
      'Want Walili zou er niet altijd zijn. De aardbeving kwam veel later, en de stad werd langzaam leeggehaald — steen voor steen, tot er niets overbleef dan de zuilen, de olijfpersen en de mozaïekvloeren die er vandaag nog liggen, in de open lucht, bij Meknès.',
      'Alles wat in de huizen stond is verdwenen.',
      'Alleen de sleutel niet.',
    ],
  },
]
