import type { Hoofdstuk } from './sleutels'

/** Deel 11 — Het eerste land dat ja zei. Tanger en Salé, 1777. */
export const DEEL11_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Brieven', tekst: [
    'Brahim was veertien en hij schreef brieven over die hij niet begreep.',
    'Dat was zijn werk. De havenschrijver van Tanger kreeg meer post dan hij aankon, en Brahim had een nette hand, en dus zat hij van zonsopgang tot het middaggebed aan een tafel bij het raam brieven te kopiëren in drie talen waarvan hij er één goed kende.',
    'Het meeste was saai. Vrachtbrieven. Klachten over tol. Een kapitein die zei dat hij bestolen was door een andere kapitein.',
    'Maar soms zat er iets tussen.',
    'In dat jaar — 1777 — begon er iets terug te komen in de stapel dat Brahim opviel omdat hij het niet kon thuisbrengen.',
    'Schepen die niet onder een vlag voeren die iemand kende.',
    'Ze zeiden dat ze uit Amerika kwamen.',
  ] },
  { nummer: 2, titel: 'De stad van de vlaggen', tekst: [
    'Als je in 1777 in Tanger op een dak ging staan, kon je de wereld tellen.',
    'Er hingen vlaggen. Op elk consulaat één: Engeland, Frankrijk, Spanje, Nederland, Denemarken, Zweden, Venetië, Genua.',
    'Brahim kende ze allemaal uit zijn hoofd voordat hij twaalf was, zoals andere kinderen vogels kennen.',
    'Tanger was klein. Twee-, drieduizend mensen misschien. Maar het lag op de plek waar de Middellandse Zee en de oceaan elkaar raken, en daar moet iedereen langs die ergens heen wil.',
    'Dus zat daar iedereen.',
    'Een consul is geen koopman en geen soldaat. Een consul is iemand die namens zijn land in jouw stad zit om te kijken wat er gebeurt, en om te klagen als er iets met een schip van zijn land is.',
    'Ze hadden allemaal een hekel aan elkaar en ze aten voortdurend bij elkaar.',
    'Brahim heeft dat van jongs af aan gezien en hij vond het lange tijd hypocriet.',
    'Si Lhabib heeft hem uitgelegd dat het precies andersom is.',
    '“Ze eten samen omdat ze een hekel aan elkaar hebben,” zei hij. “Wie samen eet, praat. Wie praat, schiet niet.”',
    'Er kwam één keer per jaar een moment waarop je zag hoe het echt zat.',
    'Dan kwam er een schip binnen met een lading die de ene consul aan de andere had beloofd, of juist niet, en dan stonden er twee mannen in de haven te schreeuwen die de avond ervoor samen hadden gegeten.',
    'Brahim heeft geleerd dat dat allebei echt was.',
    'Dat is de eerste les van dit deel en die heeft hij later beter kunnen gebruiken dan alles wat hij op school had gehad.',
  ] },
  { nummer: 3, titel: 'Waarom het uitmaakte', tekst: [
    'Om te begrijpen waarom één zin in een lijst zoveel waard was, moet je weten wat er met een schip kon gebeuren.',
    'De Middellandse Zee en de kust van de oceaan zaten vol kapers.',
    'Ze kwamen uit Salé, uit Algiers, uit Tunis, uit Tripoli. Ze kwamen ook uit Malta en uit Livorno en uit Spanje, want dit ging twee kanten op en dat wordt er in Europese boeken vaak niet bij verteld.',
    'Een kaper is geen zeerover in de zin van iemand die alles pakt. Een kaper heeft papieren van een vorst, en die papieren zeggen van welke landen hij de schepen mag nemen.',
    'Dus: is jouw land in vrede met dat van hem, dan vaar je veilig. Is het dat niet, of bestaat jouw land niet, dan ben je vogelvrij.',
    'En wat er dan gebeurde, was dit.',
    'Het schip werd opgebracht. De lading werd verkocht. De bemanning werd vastgehouden tot er losgeld kwam.',
    'Soms duurde dat maanden. Soms jaren. Soms kwam er niemand.',
    'Brahim heeft die brieven overgeschreven. Dat is wat hem dit deel heeft doen onthouden.',
    'Brieven van een vrouw uit Marseille over haar man. Brieven van een rederij in Amsterdam met een bedrag erin. Brieven van mannen zelf, gedicteerd aan iemand die kon schrijven, in een taal die ze niet spraken.',
    'Hij was veertien en hij schreef die dingen over met een nette hand, en hij heeft er niet altijd bij stilgestaan.',
    'Soms wel.',
    'Er was er één van een jongen die zei dat hij zeventien was en dat hij zijn moeder niet wilde laten schrikken.',
    'Die heeft Brahim twee keer overgeschreven omdat hij de eerste had verpest met een vlek, en daarna heeft hij de verpeste versie niet weggegooid.',
    'Dát is waarom een verdrag telt.',
    'Niet omdat het mooi is. Omdat er daarna geen brieven meer zijn.',
  ] },
  { nummer: 4, titel: 'Een land dat niemand kent', tekst: [
    'De havenschrijver heette Si Lhabib en hij was oud en hij had overal een mening over.',
    '“Amerika,” zei Brahim.',
    '“Engelse koloniën,” zei Si Lhabib zonder op te kijken.',
    '“Ze zeggen dat ze geen koloniën meer zijn.”',
    '“Dat zeggen ze, ja.”',
    'Dat was de hele kwestie, en Brahim begreep hem pas toen hij hem drie keer had opgeschreven.',
    'Er was aan de andere kant van de oceaan een oorlog bezig. Dertien Engelse koloniën hadden gezegd dat ze een eigen land waren. Engeland vond van niet.',
    'En zolang niemand anders zei dat ze een land waren, waren hun schepen geen schepen van een land maar schepen van niemand.',
    'Een schip van niemand mag iedereen aanhouden.',
    '“Wat willen ze dan van ons?” vroeg Brahim.',
    'Si Lhabib legde eindelijk zijn pen neer.',
    '“Dat wij als eerste ja zeggen,” zei hij.',
  ] },
  { nummer: 5, titel: 'Wat een handtekening is', tekst: [
    'Op 20 december 1777 liet sultan Mohammed ben Abdallah een verklaring uitgaan naar alle consuls in Tanger.',
    'Brahim heeft hem overgeschreven. Zeven keer, in zeven talen, want elke consul kreeg er een.',
    'Er stond in dat de havens van Marokko openstonden voor schepen van alle landen die met Marokko in vrede waren — en in de lijst van die landen stonden de Verenigde Staten van Amerika.',
    'Meer was het niet. Eén zin in een lijst.',
    'Brahim vond het teleurstellend. Hij had iets plechtigs verwacht.',
    '“Dit is het?” vroeg hij.',
    'Si Lhabib keek hem aan op de manier waarop oude mannen naar jonge kijken.',
    '“Jongen,” zei hij. “Er is daar een land dat vecht om te bestaan. Elke haven waar hun schepen niet mogen komen, is een deur die dicht is. Wij hebben er één opengezet.”',
    'Hij tikte op het papier.',
    '“Dit is geen zin in een lijst. Dit is het eerste land ter wereld dat zegt: jullie bestaan.”',
    'Brahim heeft het die avond nog een keer overgeschreven, voor zichzelf, en die kopie heeft hij zijn hele leven bewaard.',
  ] },
  { nummer: 6, titel: 'In welke taal', tekst: [
    'Er is één praktische vraag die in geen enkel geschiedenisboek staat en die Brahim de hele dag bezighield: in welke taal doe je dit?',
    'De sultan schreef Arabisch. De Amerikanen schreven Engels. De tussenpersonen spraken Spaans of Frans.',
    'En in de havens van de hele Middellandse Zee werd iets gesproken wat nergens iemands taal was.',
    'Ze noemden het de frankische taal. Het was een mengsel: Italiaanse woorden, Spaanse woorden, Arabische woorden, Portugese woorden, zonder vervoegingen, zonder naamvallen, zonder iets ingewikkelds.',
    'Je kon er niet mee dichten en je kon er alles mee kopen.',
    'Brahim sprak het zoals iedereen in die haven het sprak: hij wist niet dat het een taal was.',
    'Wat er bij een verdrag gebeurde, was dit.',
    'De Arabische tekst was de tekst. Die gold.',
    'Daarnaast werd er een vertaling gemaakt, meestal in het Spaans, want dat konden aan beide kanten genoeg mensen lezen. En uit die vertaling kwam weer een Engelse.',
    'Een vertaling van een vertaling.',
    'Brahim heeft ze naast elkaar gehad en hij heeft gezien wat iedereen ziet die dat doet: dat het niet helemaal hetzelfde is.',
    'Een woord dat in het Arabisch "vriendschap" is en in het Spaans iets tussen vriendschap en bondgenootschap in, en in het Engels weer iets anders.',
    'Hij heeft het een keer aan Si Lhabib laten zien.',
    'Die las het, knikte, en zei: “Dat is met opzet.”',
    '“Hoezo?”',
    '“Omdat twee landen die het precies eens zijn, geen verdrag nodig hebben.”',
    'Brahim heeft daar dertig jaar over nagedacht en hij is er nooit uitgekomen of dat cynisch was of wijs.',
  ] },
  { nummer: 7, titel: 'Negen jaar later', tekst: [
    'Er gebeurde daarna jarenlang niets, en dat is ook geschiedenis.',
    'Er kwam geen antwoord. Er kwam geen gezant. Amerika had het druk met een oorlog en met zichzelf, en brieven deden er maanden over.',
    'De sultan werd ongeduldig. In 1784 liet hij een Amerikaans schip aanhouden bij Tanger — niet om het te houden, maar om ervoor te zorgen dat iemand een brief zou schrijven.',
    'Dat werkte.',
    'In 1786 kwam er een verdrag. Het Marokkaans-Amerikaanse vriendschapsverdrag, getekend in Marrakech, ondertekend aan de andere kant door mannen wier namen op scholen in Amerika worden geleerd.',
    'Dat verdrag geldt nog steeds.',
    'Het is het oudste ononderbroken verdrag dat de Verenigde Staten hebben, met welk land ook ter wereld. Het is nooit verbroken. Het is nooit vervangen.',
    'Brahim was toen drieëntwintig en zelf havenschrijver, want Si Lhabib was gestorven, en hij heeft het afschrift met eigen hand gemaakt.',
  ] },
  { nummer: 8, titel: 'De man die kwam onderhandelen', tekst: [
    'Negen jaar na de verklaring kwam er eindelijk iemand.',
    'Hij heette Thomas Barclay en hij was door zijn regering gestuurd om een echt verdrag te maken, met handtekeningen en zegels.',
    'Brahim was toen drieëntwintig en zelf havenschrijver geworden, want Si Lhabib was gestorven in de winter van daarvoor.',
    'Barclay kwam niet met een vloot. Hij kwam met twee mannen en een kist.',
    'Dat viel iedereen op en er werd over gepraat in de stad.',
    'De Engelsen kwamen met oorlogsschepen. De Fransen kwamen met geschenken die drie karren vulden. Deze kwam met een kist papieren en te weinig geld.',
    'Dat was niet uit bescheidenheid. Het land dat hem stuurde was blut. Ze hadden net een oorlog gewonnen en er niets aan overgehouden dan schulden.',
    'Brahim heeft hem van dichtbij meegemaakt omdat hij de brieven deed.',
    'Wat hem bijstond: dat de man niets beloofde wat hij niet kon geven.',
    'De andere gezanten beloofden van alles. Dat hoorde erbij; je beloofde, en daarna onderhandelde je het weer weg.',
    'Barclay zei dat hij weinig had.',
    'Si Lhabib zou daar een mening over hebben gehad. Brahim heeft er zelf een gevormd, en die staat hier omdat het de kern van dit deel is:',
    'De sultan heeft dat verdrag niet gesloten omdat er iets tegenover stond. Er stond bijna niets tegenover.',
    'Hij deed het omdat hij een haven wilde waar alle schepen kwamen, en omdat een land dat je erkent voordat iemand anders het doet, dat de eerste honderd jaar niet vergeet.',
    'Dat is geen vriendelijkheid. Dat is ver vooruitkijken.',
    'Het heeft ook gewerkt.',
  ] },
  { nummer: 9, titel: 'Wat er in het verdrag stond', tekst: [
    'Het is in 1786 in Marrakech getekend en het is kort.',
    'Vijfentwintig artikelen, en de meeste gaan over gewone dingen: wat er gebeurt als een schip schipbreuk lijdt, hoe een koopman zijn recht haalt, wie er voor een geschil naar welke rechter gaat.',
    'Twee dingen zijn bijzonder, en Brahim heeft ze allebei overgeschreven.',
    'Het eerste: er wordt geen jaarlijkse betaling gevraagd.',
    'Dat is ongewoon. Bij de andere staten aan die kust betaalden landen elk jaar een bedrag om hun schepen met rust te laten, en over die betalingen werd eindeloos geruzied en er zijn oorlogen over gevoerd.',
    'Hier niet. Eén keer geschenken bij het sluiten, en daarna niets.',
    'Het tweede staat in het artikel over schipbreuk, en het is de zin waar Brahim bij bleef hangen.',
    'Er staat, kort gezegd: als een schip van het ene land op de kust van het andere vergaat, dan wordt de bemanning geholpen en wordt er niets van hen afgenomen.',
    'Dat lijkt vanzelfsprekend. Dat was het niet.',
    'Een gestrand schip was aan die hele kust, aan alle kanten, jarenlang beschouwd als iets wat de zee je gaf.',
    'Dat verdrag is nooit opgezegd.',
    'Het is van 1786 en het geldt nog steeds, en het is daarmee het oudste ononderbroken verdrag dat de Verenigde Staten met enig land hebben.',
    'Er zijn sindsdien veertig presidenten geweest, twee wereldoorlogen, en een Marokko dat bezet is geweest en weer vrij is geworden.',
    'Het ligt er nog.',
  ] },
  { nummer: 10, titel: 'De brief van de generaal', tekst: [
    'In 1789 kwam er een brief die Brahim niet hoefde over te schrijven en die hij toch heeft overgeschreven.',
    'Hij was van de man die in dat nieuwe land net president was geworden. Hij had de oorlog gewonnen als generaal en ze hadden hem daarna aan het hoofd gezet.',
    'Hij schreef aan de sultan.',
    'En hij begon zo: *Grote en edelmoedige vriend.*',
    'Brahim was toen zesentwintig en hij heeft er hardop om moeten lachen, en daarna heeft hij het nog een keer gelezen en is hij opgehouden met lachen.',
    'Want zo schrijft iemand die iets nodig heeft.',
    'In de brief staat dat het land nieuw is, dat de regering net is ingericht, dat er daarom vertraging is geweest in de brieven, en dat de vriendschap met Marokko hun hoog staat.',
    'Er staat ook iets in over dat hun handel nog klein is maar zal groeien.',
    'Dat laatste is de zin waar Brahim later het meest aan heeft gedacht, toen hij oud was.',
    'Want het is uitgekomen op een manier die niemand die er toen bij was had kunnen bedenken.',
    'In 1789 was dat land dertien staten aan een kust, met schulden, met een leger dat ontbonden was, en met schepen die nergens mochten komen.',
    'Tweehonderd jaar later was het het machtigste land van de wereld.',
    'En het eerste land dat tegen hen had gezegd dat ze bestonden, was Marokko.',
    'Er hangt in Tanger nog een huis dat de sultan hun later cadeau heeft gedaan. Het is het oudste bezit van de Amerikaanse staat buiten Amerika, en het is nu een museum.',
    'Je kunt er naar binnen. Er hangt een kopie van die brief.',
  ] },
  { nummer: 11, titel: 'Het huis in Tanger', tekst: [
    'In 1821 gaf de sultan een gebouw in de medina van Tanger cadeau aan de Verenigde Staten.',
    'Dat huis staat er nog.',
    'Het is het oudste Amerikaanse overheidsgebouw buiten Amerika, en het enige dat een nationaal monument is terwijl het op vreemde bodem staat. Er zit nu een museum in.',
    'Brahim heeft het nog meegemaakt. Hij was achtenvijftig.',
    'Hij is er gaan kijken op de dag dat de vlag werd gehesen, met zijn kleinzoon aan de hand, en hij heeft hem verteld dat hij de eerste zin had overgeschreven, zeven keer, in zeven talen.',
    'Zijn kleinzoon geloofde hem half.',
  ] },
  { nummer: 12, titel: 'In de kist met papieren', tekst: [
    'De sleutel kwam met een Amerikaans schip terug.',
    'Dat klinkt te mooi en het is toch wat er is gebeurd: hij was in 1778 uit Essaouira meegegaan, en hij kwam in 1786 in Tanger aan land in een kist met documenten, tussen het zegellak en de reservepennen.',
    'De klerk die de kist uitpakte wist niet wat het was en legde het op de plank.',
    'Toen het consulaat in het geschonken huis trok, ging de plank mee.',
    'Daar heeft hij honderd jaar gelegen tussen dingen die niemand durfde weg te gooien en die niemand nodig had.',
    'Tot iemand in de twintigste eeuw de kelder opruimde.',
  ] },
]
