import type { Hoofdstuk } from './sleutels'

/** Deel 9 — Het paleis van suiker. Marrakech, 1578 – 1603. */
export const DEEL9_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Tegels', tekst: [
    'Lalla was twaalf en ze kon zellige zetten, en er waren in Marrakech niet veel meisjes van wie je dat kon zeggen.',
    'Zellige is dit: je hakt uit een geglazuurde tegel een vorm. Een ster, een ruit, een stuk van een achthoek. Dan leg je die vormen omgekeerd in een patroon, met de glazuurkant naar beneden, zodat je niet ziet wat je maakt. Pas als het af is en je giet er gips overheen en je draait het om, zie je het.',
    'Je werkt dus blind aan iets waarvan je het resultaat pas achteraf ziet.',
    'Haar vader zei dat dat de hele kunst was: onthouden hoe het eruitziet terwijl je het niet kunt zien.',
    'Hij heeft het haar geleerd met scherven op de binnenplaats, toen ze zeven was. Eerst alleen ruiten, want die passen altijd. Daarna de ster met acht punten, die alleen past als alle acht de stukken even groot zijn, en dat zijn ze nooit.',
    '“Hak er één te klein,” zei hij, “en je ziet het pas als het hele veld ligt.”',
    'Ze heeft dat die eerste zomer drie keer gedaan. De derde keer heeft ze gehuild, en haar vader heeft gewacht tot ze klaar was en toen gezegd dat ze opnieuw moest beginnen.',
    'Op haar twaalfde hakte ze een punt op het gehoor. Je legt het mes op de tegel en je tikt, en aan het geluid hoor je of je goed zit.',
    'In het jaar dat de nieuwe sultan aan de macht kwam, kregen ze werk waar heel Marrakech over praatte.',
    'Er kwam een paleis.',
    'Niet zomaar een paleis. De sultan had er een naam voor bedacht voordat er een steen lag: el Badi. De onvergelijkelijke.',
    'Haar vader heeft die naam één keer hardop gezegd en toen zijn hoofd geschud, niet omdat hij hem te groot vond, maar om iets anders.',
    '“Als je iets zo noemt voordat het er staat,” zei hij, “dan moet het ook.”',
  ] },
  { nummer: 2, titel: 'Waar het van betaald werd', tekst: [
    'Het eerste wat Lalla opviel, was het marmer.',
    'Het kwam uit Italië, over zee, in blokken die met acht man gedragen moesten worden.',
    'Ze lagen een week op de binnenplaats voordat er iemand aan durfde te beginnen, en in die week is half Marrakech komen kijken, want wit steen van die afmeting had hier niemand ooit gezien.',
    '“Wat kost dat?” vroeg ze aan haar vader.',
    '“Suiker,” zei hij.',
    'Ze dacht dat het een grap was.',
    'Het was geen grap. Het verhaal ging — en het staat ook zo in de boeken van die tijd — dat er betaald werd met suiker van hetzelfde gewicht als het marmer. Marokkaanse suiker, uit de rietvelden in het zuiden, was in Europa een luxe waar vorsten om vochten.',
    'Lalla heeft later uitgerekend wat dat betekende voor één blok, en ze is halverwege opgehouden omdat het getal niet meer in haar hoofd paste.',
    'Wat er verder betaald moest worden, kwam uit iets anders.',
    'In 1591 stuurde de sultan een leger door de Sahara naar het zuiden, naar het rijk van Songhai aan de rivier de Niger. Vierduizend man, dwars door de woestijn, wat op zichzelf al bijna niet kon.',
    'Ze kwamen terug met goud en met zout en met mensen.',
    'Timboektoe was tot dat moment een stad van geleerden geweest, met bibliotheken en scholen. Daarna was het dat niet meer.',
    'Lalla heeft dat als kind niet geweten. Ze wist dat er goud kwam.',
    'Ze wist het zoals een kind dat weet: dat er iets binnenkwam waar de volwassenen zacht over praatten, en dat er daarna meer werk was.',
  ] },
  { nummer: 3, titel: 'Het riet', tekst: [
    'Suiker groeit niet in een pot. Suiker is een fabriek, en Lalla heeft er één gezien toen ze veertien was.',
    'Haar oom werkte in de Souss, in de vlakte ten zuiden van de bergen, waar het riet stond. Ze is er één zomer geweest omdat haar vader werk had elders en ze ergens moest zijn.',
    'Ze had zich er niets bij voorgesteld en wat ze zag was dit.',
    'Velden tot aan de horizon met stengels die hoger waren dan een man. Geulen ertussen waar water doorheen liep dat uit de bergen kwam, want riet drinkt meer dan wat dan ook.',
    'Als de wind erdoorheen ging, klonk het als regen. Dat is het eerste wat ze erover heeft verteld en het laatste wat ze ervan is vergeten.',
    'En aan het eind van de velden stond het gebouw.',
    'Het riet wordt geperst tussen stenen rollen die door een waterrad worden aangedreven. Het sap loopt in bakken. De bakken gaan op het vuur, uren achter elkaar, tot er iets overblijft dat dikker wordt en dan hard.',
    'Daar is hout voor nodig. Heel veel hout.',
    'Lalla heeft in die zomer de heuvels gezien waar het hout vandaan was gekomen, en er stond niets meer op.',
    'Haar oom zei dat er vroeger argan had gestaan tot aan de rand. Hij zei het zoals je iets zegt waar niemand meer iets aan kan doen.',
    'Het werk in die fabriek was het zwaarste dat ze ooit heeft gezien. De hitte van de ovens boven op de hitte van de Souss. Mensen die twaalf uur per dag bij die bakken stonden.',
    'Het sap moet geroerd blijven worden, anders brandt het aan. Dus staat er iemand te roeren, de hele tijd, met een stok die langer is dan hij.',
    'Lalla heeft één middag geroerd omdat ze het wilde proberen. Ze heeft het een halfuur volgehouden en haar armen deden de volgende dag nog pijn.',
    'De meesten waren niet uit vrije wil daar.',
    'Dat moet erbij, want het is waar, en het is het andere gezicht van de suiker die in Europa op de tafel van een koning kwam.',
    'Wat er uit die fabriek kwam, ging op kamelen naar de kust en vandaar op schepen naar Engeland, Italië en de Lage Landen, en het was daar zoveel waard dat het in kleine hoeveelheden werd verkocht, als medicijn bijna.',
    'En één keer, zegt het verhaal, is er marmer mee terugbetaald van hetzelfde gewicht.',
    'Lalla heeft het marmer aangeraakt toen het in Marrakech aankwam, en ze heeft eraan gedacht dat het in de Souss even zwaar had gewogen in iets wits dat je op kon eten.',
  ] },
  { nummer: 4, titel: 'De brief uit Engeland', tekst: [
    'In het jaar dat Lalla vierendertig werd, kwam er iets in Marrakech aan waar de hele stad over praatte: een gezantschap dat terugkwam uit Engeland.',
    'Ze waren bijna een jaar weg geweest.',
    'De sultan had ze gestuurd naar een koningin die Elizabeth heette en die op een eiland in het noorden regeerde, en het waren er zestien geweest, met de gezant voorop: een man die Abd el-Ouahed heette.',
    'Wat ze daar deden, was praten over schepen, over suiker, en over een vijand die ze allebei hadden — Spanje.',
    'In de stad werd er op twee manieren over gepraat. De ene helft vond het groot nieuws. De andere helft wilde weten wat ze daar hadden gegeten.',
    'Lalla heeft de gezant één keer gezien, van de zijkant, op een binnenplaats.',
    'Wat ze zich herinnerde was zijn gezicht: dat hij eruitzag als iemand die een jaar lang op zijn woorden had moeten letten.',
    'In Londen is er toen een portret van hem geschilderd. Dat hangt er nog.',
    'Er wordt gezegd — het is niet bewezen en het wordt al vierhonderd jaar gezegd — dat er een toneelschrijver in die stad naar dat gezantschap heeft gekeken, en dat hij kort daarna een stuk schreef over een Moor in Venetië.',
    'Wat wel vaststaat: er zijn in die jaren brieven heen en weer gegaan tussen Marrakech en Londen, en er is over een bondgenootschap gepraat dat er niet is gekomen.',
    'Dit is waarom het hier staat.',
    'In de boeken op school staat de zestiende eeuw als de eeuw waarin Europa de wereld ontdekte.',
    'In diezelfde eeuw stuurde een sultan uit Marrakech een gezant naar een koningin in Londen om zaken te doen, en kwam die gezant terug met een verslag over hoe het daar was.',
    'Het ging twee kanten op.',
    'Lalla heeft dat nooit zo gezegd. Zij zei alleen, toen haar kleindochter ernaar vroeg: “Ze gingen daarheen en ze kwamen terug. Ik weet niet waarom dat bijzonder zou zijn.”',
    'Dat is misschien wel het beste antwoord dat er is.',
  ] },
  { nummer: 5, titel: 'Vierduizend man de woestijn in', tekst: [
    'In het najaar van 1590 vertrok er een leger naar het zuiden en de halve stad geloofde niet dat het zou aankomen.',
    'Vierduizend man. De Sahara over. Ruim vijftienhonderd kilometer, met water dat je meeneemt en dat op een gegeven moment op is.',
    'Lalla was toen vierentwintig en ze zette tegels in de grote zaal, en ze heeft de soldaten zien vertrekken.',
    'Ze is ervoor naar het dak geklommen, met een kind op haar heup, en ze heeft gekeken tot de stofwolk niet meer van de lucht te onderscheiden was.',
    'Het bijzondere aan dat leger was niet het aantal. Het waren de wapens.',
    'Ze hadden vuurwapens. Musketten en kanonnen, gekocht van Europese handelaren en betaald met suiker, en er waren mannen bij die uit Spanje en Portugal kwamen en die wisten hoe je ermee omging.',
    'Aan de overkant van de woestijn lag het Songhai-rijk, dat groter was dan Marokko en dat al eeuwen stond, en dat vocht met paarden en met speren.',
    'Bij Tondibi, bij de rivier, duurde het één ochtend.',
    'Dat is wat een vuurwapen doet met een leger dat er geen heeft. Het gaat er niet om wie dapperder is.',
    'De helft van de mannen die vertrokken zijn nooit teruggekomen — niet door het vechten, maar door de woestijn, heen en terug.',
    'Wat er wel terugkwam, kwam in karavanen aan die maanden achter elkaar bleven komen.',
    'Goud. Zout. En mensen, geketend, die in Marrakech aan het werk werden gezet.',
    'Lalla heeft ze zien binnenkomen. Ze was toen zesentwintig en had twee kinderen.',
    'Ze stond bij de poort omdat iedereen bij de poort stond. Het duurde lang voordat de rij voorbij was, en op een gegeven moment is ze naar huis gegaan terwijl hij nog liep.',
    'Ze schrijft — haar kleindochter heeft het opgeschreven, want Lalla kon niet schrijven — dat het de eerste keer in haar leven was dat ze zich schaamde voor iets waar ze zelf niets aan had gedaan.',
    'Het paleis waar ze aan werkte, werd daarvan betaald.',
    'Ze is blijven werken. Dat is wat ze deed en wat ze moest, en het is ook het eerlijke antwoord: bijna iedereen blijft werken.',
    'Haar kleindochter heeft haar gevraagd of ze had kunnen stoppen.',
    'Lalla heeft gezegd: “Ja.” En daarna niets meer.',
  ] },
  { nummer: 6, titel: 'De geleerde die werd meegebracht', tekst: [
    'Tussen de mensen die uit Timboektoe werden meegevoerd, was er één van wie iedereen in Marrakech de naam kende.',
    'Hij heette Ahmad Baba en hij was de belangrijkste geleerde van zijn stad.',
    'Hij kwam in ketenen aan. Hij was achtendertig. Onderweg is hij van een kameel gevallen en heeft hij zijn been gebroken, en dat is nooit meer goed gekomen.',
    'Zijn bibliotheek was in beslag genomen. Zestienhonderd boeken.',
    'Hij heeft daar later één zin over gezegd die in dit boek thuishoort en die je even moet laten staan:',
    '*Van alle boeken van mijn familie had ik de kleinste verzameling.*',
    'Zestienhonderd boeken, en in zijn familie was dat de kleinste.',
    'Denk daar even over na, want het zegt iets over de stad waar hij vandaan kwam dat in geen enkel schoolboek staat. Timboektoe was geen dorp aan de rand van de wereld. Het was een plek waar families boeken verzamelden zoals andere families land verzamelden.',
    'Wat er daarna gebeurde, is het vreemdste van dit hele deel.',
    'Ze hielden hem eerst gevangen. Daarna lieten ze hem lesgeven.',
    'De geleerden van Marrakech kwamen bij hem. De rechters kwamen bij hem met vragen. Er zijn mannen uit Fes overgekomen om bij hem te studeren, twaalf jaar lang, bij een man die ze zelf hadden meegenomen.',
    'Lalla heeft hem één keer gezien, op straat, lopend met een stok.',
    'Ze wist wie het was omdat iedereen het wist. Wat haar bijbleef was dat er twee jonge mannen naast hem liepen die niets zeiden en die zijn tempo aanhielden, en dat hij praatte terwijl hij liep.',
    'Hij is uiteindelijk teruggegaan naar Timboektoe, jaren later, toen de sultan dood was.',
    'Hij heeft zijn boeken nooit teruggekregen.',
    'Er wordt verteld dat hij bij het verlaten van Marrakech heeft gezegd dat hij hoopte dat God de stad zou geven wat ze verdiende, en dat er verschillende uitleggingen van die zin bestaan.',
    'Zijn naam staat nu op een onderzoeksinstituut in Timboektoe, waar een deel van de handschriften van die stad wordt bewaard.',
  ] },
  { nummer: 7, titel: 'Vijfentwintig jaar', tekst: [
    'Er is vijfentwintig jaar aan gebouwd.',
    'Dat is een zin die je leest en die je niet voelt. Daarom staat hij hier nog een keer, maar dan anders.',
    'Lalla was twaalf toen ze begon en zevenendertig toen het af was.',
    'Ze trouwde tijdens de bouw. De man heette Hassan en hij zaagde cederhout, en ze hebben elkaar leren kennen omdat hij elke dag langs haar stelling liep en op een gegeven moment iets zei.',
    'Ze kreeg drie kinderen tijdens de bouw. De oudste is geboren in de winter dat de noordmuur werd gezet, en ze was zeventien dagen later terug.',
    'Haar vader stierf tijdens de bouw. Dat was in het twaalfde jaar. Hij was aan het werk tot drie weken daarvoor.',
    'Haar oudste zoon zette tegels naast haar in het laatste jaar, en hij hakte zijn eerste achtpuntige ster op zijn elfde, één punt te klein, en hij heeft gehuild.',
    'Zo gaat dat met iets wat vijfentwintig jaar duurt. Het is geen bouwwerk, het is een leven.',
    'Wat het werk zelf betreft: dat is vijfentwintig jaar lang hetzelfde geweest.',
    'Je zit op een lage kruk of op je knieën. Je hakt, je legt om, je controleert met je vingers of het vlak is, en je doet het nog een keer. Een veld van een armlengte kost een dag.',
    'Haar handen zijn ervan geworden zoals de handen van een tegelzetter worden: de duim en de wijsvinger van de rechterhand hard als leer, en in de winter barsten ze open.',
    'Er is in die vijfentwintig jaar twee keer werk afgekeurd dat zij had gezet. De eerste keer was ze zestien en had ze gelijk, en ze heeft het niet gezegd. De tweede keer was ze negenentwintig en had ze ongelijk, en ze heeft het meteen gezegd.',
    'Ze heeft haar kleindochter verteld dat dat het verschil is tussen zestien en negenentwintig, en verder niets.',
  ] },
  { nummer: 8, titel: 'Wat er af was', tekst: [
    'Toen het af was, is Lalla erdoorheen gelopen met haar zoon, en ze was zevenendertig.',
    'Dit is wat er stond.',
    'Een binnenhof van honderdvijfendertig bij honderdtien passen, met een vijver in het midden die zo groot was dat er bootjes op konden.',
    'Vier tuinen, lager gelegen dan de hof, zodat je over de toppen van de sinaasappelbomen keek in plaats van ertegenaan.',
    'Paviljoens op de vier zijden, met daken van verguld cederhout. Eén ervan heette De Kristallen Koepel.',
    'Marmer uit Italië. Onyx. Zellige waar zij vijfentwintig jaar aan had gewerkt, in patronen die nergens anders zo waren gezet.',
    'En goud. Zevenendertighonderd kilo in de plafonds, zeggen sommige bronnen. Zoveel dat bezoekers uit andere landen erover naar huis schreven, en dat is hoe we het weten.',
    'Bij de opening was er een feest waar iedereen bij was die iets voorstelde.',
    'Het verhaal gaat dat de sultan aan een nar vroeg wat hij ervan vond, en dat de nar zei: “Het zal een mooie ruïne worden.”',
    'Dat verhaal is waarschijnlijk later bedacht, want zo gaat dat met dat soort zinnen. Ze worden gemaakt als men weet hoe het afliep.',
    'Lalla stond die dag achteraan, tussen de mensen die het gebouwd hadden en die naar binnen mochten voordat de gasten kwamen.',
    'Ze mochten een uur. Daarna moesten ze eruit, en toen kwamen de tapijten.',
    'Haar zoon vroeg: “Welke heb jij gedaan?”',
    'Ze heeft het hem aangewezen. Een band van een handbreed, op ooghoogte, langs de oostelijke muur, over een lengte van veertig passen.',
    'Vijfentwintig jaar, en ze kon het aanwijzen met één hand.',
    'Zo is alles gebouwd wat groot is.',
  ] },
  { nummer: 9, titel: 'Het jaar van de ziekte', tekst: [
    'In 1603 kwam de pest naar Marrakech en de sultan is eraan gestorven.',
    'Hij was zesenvijftig. Hij had vijfentwintig jaar geregeerd, hij had het rijkste hof van zijn tijd, en hij ging dood aan hetzelfde als de mensen in de straat.',
    'Lalla was zevenendertig en ze heeft er twee kinderen aan verloren.',
    'Daar staat in dit boek verder niets over, omdat er niets over te zeggen valt.',
    'Wat er daarna gebeurde, hoort er wel in.',
    'De sultan had drie zonen en ze vochten alle drie om de troon. Dat duurde jaren. Het land viel uiteen in stukken die door verschillende mannen werden bestuurd, en het geld dat uit de woestijn was gekomen, was op.',
    'Het rijk dat in dit hoofdstuk op zijn hoogtepunt stond, was binnen vijftien jaar geen rijk meer.',
    'Dat is iets om te onthouden als je ergens leest dat een land machtig was. Machtig is een toestand en geen eigenschap. Het duurt zolang het duurt.',
    'Lalla heeft dat allemaal meegemaakt, en ze heeft tegels blijven zetten, want ook in een land dat uiteenvalt worden er muren betegeld.',
    'Het werk werd wel anders. Geen paleizen meer; huizen, en fonteinen, en één keer een badhuis in Taroudant waarvoor ze drie maanden weg is geweest.',
    'Ze is oud geworden. Haar kleindochter heeft haar verhaal opgeschreven toen ze zelf kon schrijven, en dat is de enige reden dat het er is.',
    'De laatste keer dat Lalla het paleis heeft gezien, was ze in de zestig en werd ze binnengelaten omdat een bewaker haar vader had gekend.',
    'Er woonde toen bijna niemand meer.',
    'De vijver stond droog.',
  ] },
  { nummer: 10, titel: 'Wat er in de muur ging', tekst: [
    'Het jaar daarvoor, bij de oostmuur, deed Lalla iets wat haar vader haar had geleerd.',
    'Hij had gezegd: als je aan iets werkt dat langer blijft staan dan jij, laat er dan iets van jezelf in achter. Niet je naam — je naam doet er niet toe. Iets wat van jou was.',
    'Hij had het zelf ook gedaan, zei hij, en hij heeft nooit willen zeggen waar of wat.',
    'Ze had een sleutel.',
    'Hij was van brons, met acht punten aan de kop, en haar vader had hem jaren geleden gekocht van een jongen die net uit het noorden was gekomen. Zes munten en een maaltijd, zei hij, en hij had er nooit iets mee gedaan.',
    'Ze had hem altijd bij zich gehad in de zak van haar schort, en ze wist niet meer waarom.',
    'Hij paste nergens op. Dat had ze uitgeprobeerd, als kind, op elke deur in de straat.',
    'Achter een rij tegels, waar de muur hol was voor de leidingen, legde ze hem neer.',
    'Toen zette ze de tegels erover.',
    'Omgekeerd, met de glazuurkant naar beneden, zoals altijd: ze zag pas wat ze had gemaakt toen het gips droog was en het geheel werd omgedraaid.',
    'Het was een ster met acht punten.',
    'Dat was niet met opzet. Dat patroon zit overal in Marrakech.',
  ] },
  { nummer: 11, titel: 'Steen voor steen weggehaald', tekst: [
    'Honderd jaar later kwam er een sultan die Meknès tot zijn hoofdstad maakte, en die had bouwmateriaal nodig.',
    'Hij heette Moulay Ismail en hij liet het Badi afbreken.',
    'Niet vernielen — uit elkaar halen. Dat is iets anders en het is erger, want het is zorgvuldig.',
    'Er kwamen mannen die wisten hoe een plafond in elkaar zat, en die haalden het in omgekeerde volgorde weer uit elkaar.',
    'Twaalf jaar lang reden er karren van Marrakech naar Meknès, driehonderdvijftig kilometer, volgeladen met marmer, met onyx, met cederhout, met de vergulde balken uit de daken.',
    'Reken dat eens om. Een kar doet er twee weken over. Twaalf jaar lang, elke week karren.',
    'De zellige is er grotendeels afgehakt. Dat gaat met een beitel en het gaat snel, want zellige zit in gips en gips laat los.',
    'Wat niet mee kon, bleef liggen: gebroken stukken, het gips, de scherven waar de patronen in hadden gezeten.',
    'Mensen uit de stad hebben die meegenomen. Er zijn in Marrakech huizen waar een stuk vloer ligt dat uit het Badi komt, en de families weten het niet meer.',
    'Er is nooit opgeschreven hoeveel karren het waren. Er is wel opgeschreven dat het werk jaren duurde en dat er mannen waren die hun hele leven niets anders hebben gedaan dan dit paleis uit elkaar halen.',
    'Hun vaders hadden het gebouwd.',
  ] },
  { nummer: 12, titel: 'De mooie ruïne', tekst: [
    'Wat er nu staat, is wat er niet de moeite waard was om mee te nemen.',
    'De muren van gestampte aarde, rood, een paar meter dik, want die kun je niet verplaatsen.',
    'De vorm van de hof, die je nog helemaal kunt zien: honderdvijfendertig passen, en je loopt ze zelf af.',
    'De lege bakken waar de vijvers waren, en de verzonken tuinen, die nu gewoon kuilen zijn.',
    'Er nestelen ooievaars op de muren. Elk jaar.',
    'Je kunt er naar binnen. Het kost een paar dirham en je loopt over een vlakte van rode aarde waar het mooiste paleis van zijn eeuw heeft gestaan, en er is niets wat je vertelt hoe het eruitzag behalve de afmetingen.',
    'Dat is wat er van over is, en het is misschien wel eerlijker dan wanneer het er nog had gestaan.',
    'Want dan zou je naar het goud kijken en niet naar waar het vandaan kwam.',
    'Nu zie je alleen de maat van het ding, en de maat is het verhaal: zoveel mensen, zoveel jaar, zoveel suiker, zoveel goud uit een stad die er niet meer hetzelfde van werd.',
    'De man die zei dat het een mooie ruïne zou worden, had gelijk.',
    'Hij heeft het zelf niet meer gezien, en het is maar de vraag of hij heeft bestaan.',
  ] },
  { nummer: 13, titel: 'Wat een muur loslaat', tekst: [
    'Lalla was oud toen ze hoorde dat het paleis werd afgebroken, en haar kleinkinderen hebben verteld dat ze er niet van opkeek.',
    'Ze zei: “Ik heb er vijfentwintig jaar aan gewerkt. Het heeft er honderd gestaan. Dat is vier keer zoveel.”',
    'Dat was het enige wat ze erover kwijt wilde.',
    'Haar kleindochter heeft toen gevraagd of ze het niet erg vond van haar eigen muur.',
    'Lalla heeft gezegd dat een muur van iemand anders is zodra je hem af hebt, en dat ze dat op haar twaalfde al wist.',
    'Toen de oostmuur werd gesloopt, kwamen de tegels los en viel er van alles uit de holle ruimte: stukken leiding, een lap, en iets van brons.',
    'Een sloper raapte het op.',
    'Hij hield het tegen de zon, zag dat er geen goud aan zat, en gooide het in de kar met rommel die naar de markt ging.',
    'Daar is het gekocht door een man uit Essaouira.',
    'Alleen heette Essaouira toen nog niet Essaouira, want de stad bestond nog niet.',
  ] },
]
