import type { Hoofdstuk } from './sleutels'

/** Deel 3 — Wat Fatima bouwde. Fes, 859. */
export const DEEL3_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Water dragen', tekst: [
    'Hind was dertien en ze droeg water, en dat was alles wat iemand van haar wist.',
    'Ze had geen ouders. Dat is een zin die je snel opschrijft en die een heel leven beslaat. Haar moeder was gestorven toen zij vier was, haar vader twee jaar later op weg naar Kairouan, en sindsdien woonde ze bij de familie van haar moeders zus, in een huis met te weinig kamers en te veel kinderen.',
    'Ze klaagde niet. Ze was er ook niet dankbaar voor. Ze droeg water.',
    'Elke ochtend liep ze naar de rivier met twee kruiken aan een juk, en elke ochtend zag ze de bouwplaats.',
    'Die lag aan de overkant van de straat, op een stuk grond waar tot vorig jaar niets had gestaan. Nu stonden er stellingen, lagen er stapels steen, en werkten er mannen van zonsopgang tot het te donker werd.',
    'Iedereen in Fes had er een mening over.',
    '“Een moskee,” zei haar tante. “Er zijn al moskeeën.”',
    '“Ze betaalt het zelf,” zei de buurvrouw. “Uit de erfenis van haar vader. Alles. Tot de laatste munt.”',
    '“Dan is ze gek.”',
    'Hind zei niets, want niemand vroeg haar iets. Maar ze keek elke ochtend, en ze zag iets wat de anderen blijkbaar niet zagen.',
    'De bouwplaats had een vorm.',
    'Niet zomaar muren. Er was een binnenhof gepland die groter was dan het gebouw eromheen, en aan drie kanten kwamen er rijen bogen. Daar paste geen bidruimte in. Daar paste iets anders in, iets wat Hind niet kon benoemen omdat ze het nooit had gezien.',
  ] },
  { nummer: 2, titel: 'De vrouw met het stof', tekst: [
    'De eerste keer dat ze haar sprak, wist ze niet wie ze was.',
    'Het was midden op de dag. Hind bracht water naar de metselaars — dat was er sinds een maand bij gekomen, en het leverde koper op — en bij de put stond een vrouw in een eenvoudige jurk met stof tot aan haar ellebogen.',
    '“Mag ik?” vroeg de vrouw.',
    'Hind gaf haar de schep.',
    'De vrouw dronk, veegde haar mond af en keek naar de stellingen.',
    '“Wat vind je ervan?”',
    'Hind wist niet of ze antwoord moest geven.',
    '“Ik vind het te groot,” zei ze toen.',
    'De vrouw lachte. “Waarom?”',
    '“Voor wie is het? Er zijn al moskeeën. Er zijn geen mensen genoeg.”',
    '“Nee,” zei de vrouw. “Nu niet.”',
    'Ze zette de schep terug.',
    '“Mijn vader kwam hier vandaan de zee. Uit Kairouan. Hij had niets en hij is met handel begonnen, en toen hij stierf had hij genoeg om zijn dochters iets na te laten.” Ze keek Hind aan. “Ik heb geen zoon. Ik heb geen man meer. Ik heb geld en ik heb een stad die vol loopt met mensen die uit alle richtingen komen.”',
    '“En dan bouw je dit.”',
    '“En dan bouw je dit,” zei de vrouw.',
    'Ze liep terug naar de stellingen, en pas toen een voorman zich omdraaide en “Lalla Fatima” zei, begreep Hind wie er water uit haar schep had gedronken.',
  ] },
  { nummer: 3, titel: 'Wat er tussen de bogen past', tekst: [
    'Vanaf die dag lette Hind beter op.',
    'Ze telde de bogen. Ze telde de dagen. Ze leerde de namen van de steensoorten van de metselaars, die haar uitlachten en het haar daarna toch vertelden.',
    'En ze begreep waarom het niet klopte.',
    'Een moskee is voor bidden. Dit gebouw had ruimtes die daar niets mee te maken hadden: kleine kamers langs de rand van de binnenhof, met elk een deur en een raam. Nissen in de muren, op de hoogte van een zittende man.',
    '“Waar zijn die voor?” vroeg ze aan de oudste metselaar.',
    '“Boeken,” zei hij.',
    '“Boeken?”',
    '“Ze wil dat er boeken staan. En mensen die erbij zitten.” Hij spuugde in zijn handen. “Een moskee waar geleerd wordt, zegt ze. Ik doe wat ze zegt. Ik denk er niet over na.”',
    'Hind dacht er wel over na.',
    'Ze kon niet lezen. Bijna niemand die zij kende kon lezen. Lezen was iets voor kooplieden en voor de zonen van kooplieden, en voor mannen die daar jaren voor naar een andere stad gingen.',
    'Als er boeken in een binnenhof staan, en er zitten mensen bij die er hardop uit voorlezen, dan hoeft niemand ergens heen.',
    'Dan komt het naar hier.',
    'Ze zette haar kruiken neer op de rand van de put en ging zitten, en ze bleef daar zo lang zitten dat de voorman riep of ze soms betaald werd om te kijken.',
  ] },
  { nummer: 4, titel: 'De steen die niet paste', tekst: [
    'Het ging mis in het derde jaar.',
    'Het geld raakte op. Niet ineens — zoals geld opraakt: eerst twee dagen later betalen, dan een week, dan mannen die niet meer kwamen opdagen omdat ze elders wel geld kregen.',
    'De bouwplaats werd stil. Er stonden vier muren en een halve rij bogen, en er lag een stapel steen die langzaam begroeid raakte.',
    'In de stad werd erover gepraat op de toon waarop mensen praten als ze gelijk hebben gekregen.',
    '“Ik zei het toch.”',
    '“Een vrouw die bouwt.”',
    'Hind droeg water naar andere plekken. Ze hield niet op met langs de bouwplaats lopen.',
    'Op een ochtend stond Lalla Fatima er weer, alleen, met haar hand op een steen.',
    'Hind bleef staan met haar juk op haar schouders.',
    '“Het spijt me,” zei ze, en ze wist zelf niet precies waarvoor.',
    'Fatima keek op. Ze zag er ouder uit dan drie jaar geleden.',
    '“Weet je wat ik verkeerd heb gedaan?” zei ze. “Ik heb geteld wat ik had. Ik heb niet geteld wat het kost om iets te bouwen dat er nog nooit is geweest.”',
    '“Gaat het door?”',
    '“Ja.”',
    '“Hoe?”',
    'Fatima haalde haar schouders op, en voor het eerst leek ze op iedereen.',
    '“Langzamer,” zei ze. “Dat is hoe.”',
  ] },
  { nummer: 5, titel: 'Wat een stad doet', tekst: [
    'Wat er daarna gebeurde, heeft Hind haar hele leven niet helemaal kunnen uitleggen.',
    'Het begon met de metselaars. Drie van hen kwamen terug, onbetaald, en gingen verder waar ze gestopt waren. Niemand had ze gevraagd.',
    'Toen kwam er een koopman met een kar steen. Daarna nog een.',
    'De bakker aan de overkant begon brood te brengen om twaalf uur, elke dag, voor wie er werkte. Zijn vrouw zei dat hij gek was. Hij bleef het doen.',
    'Er kwam geld binnen dat niemand kon herleiden. Kleine bedragen. Iemand liet een zak bij de put staan.',
    'En Hind droeg water, want dat was wat zij had.',
    'Ze droeg het gratis. Ze had het koper nodig en ze deed het toch, en als haar tante ernaar vroeg zei ze dat ze het bij de rivier had verspeeld.',
    'Het is haar nooit gelukt uit te leggen waarom een stad dat doet.',
    'Het beste wat ze er later over kon zeggen was dit: er was iets begonnen dat te groot was om van één iemand te zijn, en toen het dreigde om te vallen merkten mensen dat ze niet wilden dat het omviel.',
    'Dat is geen verklaring. Dat is wat er gebeurde.',
    'Het duurde nog vier jaar.',
  ] },
  { nummer: 6, titel: 'De zus aan de overkant', tekst: [
    'Er was nog een bouwplaats in Fes.',
    'Dat wist Hind wel, maar ze had er nooit over nagedacht, want hij lag aan de andere oever en de andere oever was een ander land.',
    'Zo was de stad gemaakt. Aan deze kant woonden de mensen die uit Kairouan waren gekomen, de stad in het oosten waar Lalla Fatima’s vader vandaan kwam. Aan de overkant woonden de mensen die uit Andalusië waren gekomen, over zee, toen het daar te gevaarlijk werd. Twee steden met een rivier ertussen en een brug erover, en iedereen deed alsof de brug er niet was.',
    'De grap in Hinds straat was dat je aan de overkant niet wist hoe je brood moest bakken.',
    'De grap aan de overkant was waarschijnlijk hetzelfde, met een ander woord voor brood.',
    'In het vierde jaar liep Hind voor het eerst van haar leven over die brug.',
    'Ze deed het omdat ze het gehoord had en het niet geloofde, en omdat ze dertien was geweest en nu bijna zeventien, en op die leeftijd loop je over een brug om iets niet te geloven.',
    'Aan de overkant stond een tweede bouwplaats.',
    'Kleiner. Verder. Er stonden al bogen.',
    'Ze vroeg het aan een vrouw met een mand.',
    '“Wie bouwt dat?”',
    'De vrouw keek haar aan zoals je kijkt naar iemand die vraagt wie de zon heeft opgehangen.',
    '“Lalla Maryam,” zei ze.',
    '“Wie is dat?”',
    '“De zus.”',
    'Hind stond daar met haar juk op haar schouders en begreep het in één keer, en het was het soort begrijpen dat je in je borst voelt.',
    'Twee zussen. Eén erfenis, in tweeën. Twee bouwplaatsen, aan twee kanten van dezelfde rivier, in een stad die deed alsof er twee steden waren.',
    '“Waarom twee?” vroeg ze.',
    'De vrouw haalde haar schouders op.',
    '“Omdat wij hier wonen,” zei ze. “En zij daar.”',
    'Hind liep terug over de brug, en bleef halverwege staan om naar het water te kijken.',
    'Later heeft ze er dit van gemaakt, en ze wist dat het meer was dan er stond: dat je een stad niet één maakt door te zeggen dat hij één is, maar door aan beide kanten hetzelfde neer te zetten.',
    'De moskee aan de overkant staat er ook nog. Hij heet al-Andalusiyyin.',
    'Hij is nooit zo beroemd geworden als die van haar zus. Zo gaat dat met de tweede.',
  ] },
  { nummer: 7, titel: 'Het water van de rivier', tekst: [
    'In de winter van dat jaar ging de rivier over de kant.',
    'Dat gebeurde vaker. Fes ligt in een kom, en als het twee weken achter elkaar regent in de bergen dan komt dat water ergens naar beneden, en beneden is waar de mensen wonen.',
    'Hind werd er ’s nachts wakker van, van het geluid. Water dat ergens is waar het niet hoort klinkt niet als water.',
    'De volgende ochtend stond de laagste rij van de bouwplaats onder water en lag er modder tot aan de tweede boog.',
    'Ze gingen erheen, iedereen. Niet uit medelijden: er lag kalk, en kalk die nat wordt is geld dat weg is.',
    'Ze schepten tot het donker werd. Hind schepte met de emmers waarmee ze anders water bracht, wat haar de eerste uren grappig leek en daarna niet meer.',
    '’s Middags kwam Lalla Fatima, met haar rokken opgebonden als een vrouw die op het land werkt, en ze schepte mee.',
    'Er werd niets bijzonders van gezegd. Dat is het punt.',
    'Toen het donker werd stonden ze met zijn allen in de modder naar de muur te kijken, die er nog stond, en iemand begon te lachen om niets, en toen lachte iedereen, op de manier waarop je lacht als je te moe bent om iets anders te doen.',
    'Er was die avond geen brood van de bakker, want de bakker stond ook in de modder.',
    'Dit is wat Hind zich van de hele bouw het best is blijven herinneren. Niet de dag dat het af was. Deze dag.',
    'Ze heeft dat later aan haar dochter proberen uit te leggen en het klonk als iets kleins.',
    '“Jullie schepten modder,” zei haar dochter.',
    '“Ja.”',
    '“En dat was het mooiste?”',
    '“Ja.”',
    'Haar dochter was toen acht en begreep er niets van, en op haar dertigste snapte ze het ineens, aan een tafel in een ander huis, zonder dat er iets bijzonders gebeurde.',
  ] },
  { nummer: 8, titel: 'De man die de bogen telde', tekst: [
    'De metselaar heette Driss en hij had drie vingers aan zijn linkerhand.',
    'Hij was de oudste op de plaats en hij werkte langzamer dan de rest en niemand zei daar iets van, want zijn bogen stonden en dat van anderen soms niet.',
    'Hind bracht hem water, vier keer per dag, en hij zei elke keer dankjewel, wat de anderen niet deden.',
    'Op een dag vroeg ze waarom een boog niet omvalt.',
    'Ze vroeg het half voor de grap, omdat ze het gewicht van de steen kende uit haar armen en niet begreep hoe iets dat zo zwaar is boven je hoofd kan blijven hangen.',
    'Driss legde zijn troffel neer.',
    'Dat was het eerste wat haar opviel: dat hij zijn troffel neerlegde.',
    '“Kom hier,” zei hij.',
    'Hij zette twee stenen rechtop in het zand, schuin naar elkaar toe, zodat ze tegen elkaar leunden.',
    '“Duw ze om.”',
    'Ze duwde. Ze vielen niet.',
    '“Harder.”',
    'Ze duwde harder. Ze vielen nog niet.',
    '“Dat is een boog,” zei Driss. “Elke steen duwt tegen de volgende. Niemand houdt zichzelf overeind. Als je er één weghaalt valt alles.”',
    'Hind keek naar de twee stenen in het zand en toen naar de rij bogen achter hem.',
    '“En de bovenste?”',
    '“De sluitsteen.” Hij wees. “Die gaat er als laatste in en die doet het minste werk. Hij houdt alleen de rest op zijn plek.”',
    '“Dat is toch juist het meeste werk?”',
    'Driss keek haar aan met de blik van een man die een antwoord hoort dat hij zelf niet had bedacht.',
    '“Ja,” zei hij toen. “Dat is waar.”',
    'Hij pakte zijn troffel weer op.',
    'Hind droeg de rest van die dag water met twee stenen in haar hoofd die tegen elkaar leunden, en ze heeft er haar leven lang mee gedacht.',
    'Over haar tante, die haar eten gaf en haar nooit iets vroeg.',
    'Over de bakker die brood bleef brengen terwijl zijn vrouw zei dat hij gek was.',
    'Over een stad die overeind blijft doordat iedereen tegen de volgende duwt.',
  ] },
  { nummer: 9, titel: 'Wat Hind vroeg', tekst: [
    'Ze vroeg het in het vijfde jaar, en ze had er twee maanden voor nodig gehad om het te durven.',
    'Er zat toen al iemand bij de bogen. Het gebouw was nog niet af, maar er werd al gebeden, en waar gebeden wordt komt iemand zitten die iets uitlegt, en om hem heen komen mensen zitten die het willen horen. Zo begint het overal.',
    'Er zaten mannen. Er zaten jongens van tien. Er zat één keer een oude vrouw, en Hind heeft haar daarna nooit meer gezien.',
    'Hind zette haar juk neer, ging op de rand van de binnenhof zitten en luisterde.',
    'Ze begreep er weinig van. Het ging over regels, en over wat er in een boek stond, en de man las voor uit iets wat hij op zijn knie hield.',
    'Wat haar bezighield was niet wat hij zei.',
    'Het was dat de tekens op de bladzijde elke keer hetzelfde waren en dat er elke keer hetzelfde uitkwam.',
    'Ze bleef drie weken komen voordat ze iets vroeg.',
    '“Kan ik dat leren?”',
    'De man keek op.',
    'Hij was niet onvriendelijk. Dat maakte het erger.',
    '“Kun je betalen?” vroeg hij.',
    '“Nee.”',
    '“Heb je tijd?”',
    'Ze dacht aan de rivier, en aan de vier keer per dag, en aan haar tante.',
    '“Nee.”',
    'Hij knikte, alsof ze samen iets hadden opgelost.',
    'Hind pakte haar juk en ging weg, en ze was pas bij de brug toen ze merkte dat ze huilde, wat haar nooit gebeurde en waar ze woedend om was.',
    'Ze is de volgende dag teruggegaan.',
    'Niet om het nog eens te vragen. Om te zitten.',
    'Ze zat er die zomer bijna elke dag een kwartier, met haar juk naast zich, en ze zei niets en niemand zei iets tegen haar.',
    'Ze leerde in die zomer drie letters, door te kijken.',
    'Het is haar tien jaar later alsnog gelukt, en in dat boek staat wie haar het heeft geleerd, en het was niet die man.',
  ] },
  { nummer: 10, titel: 'Haar tante', tekst: [
    'Haar tante heette Rahma en ze was geen slechte vrouw. Dat moet er eerst staan, omdat wat daarna komt anders klinkt dan het was.',
    'Ze had Hind in huis genomen toen er niemand anders was. Ze had vijf eigen kinderen en een man die met leer werkte en te weinig verdiende, en ze had er een zesde bij genomen zonder dat iemand haar dat had gevraagd, en dat is geen kleinigheid.',
    'Ze had er alleen geen zachte woorden bij.',
    'In het vijfde jaar begon ze over trouwen.',
    'Hind was zeventien. Dat was aan de late kant, en daar werd in de straat over gepraat, en Rahma hoorde dat en vond het erg, en zei het.',
    '“Er is een man in de leerstraat.”',
    '“Ik weet het.”',
    '“Hij is niet oud.”',
    '“Ik weet het.”',
    '“Je draagt water,” zei Rahma. “Je bent negentien over twee jaar en dan draag je nog steeds water, en dan is die man weg.”',
    'Hind zei niets, want ze had geen antwoord dat haar tante iets waard zou vinden.',
    'Ze kon niet zeggen: ik wil eerst leren lezen. Dat is geen reden. Dat is in die straat, in dat jaar, in dat huis met zes kinderen, geen reden.',
    'Ze kon ook niet zeggen dat ze elke middag een kwartier bij de bogen zat, want dat was van haar.',
    'Wat ze wel zei was: “Nog niet.”',
    'Haar tante keek haar lang aan.',
    '“Je lijkt op je moeder,” zei ze. “Die zei dat ook.”',
    'Het was de eerste keer in vier jaar dat iemand haar moeder noemde.',
    'Hind heeft er die nacht wakker van gelegen en nooit gevraagd wat ze bedoelde, en dat heeft haar later gespeten, want Rahma is gestorven in de winter dat het gebouw af was.',
    'Ze is er wel geweest, die laatste dag. Ze stond in de straat, met de rest.',
    'Ze zei er niets over. Ze zei alleen, toen ze thuiskwamen: “Het is groot.”',
    'Van Rahma was dat veel.',
  ] },
  { nummer: 11, titel: 'De maand dat er niet gegeten werd', tekst: [
    'Er wordt verteld dat Lalla Fatima heeft gevast zolang de bouw duurde.',
    'Hind heeft dat ook gehoord, en ze wist niet of het waar was, en dat is precies waarom het het vertellen waard is: het werd al verteld toen de mensen die erbij waren nog leefden.',
    'Wat Hind zelf zag, was de maand van het vasten op de bouwplaats.',
    'Het is geen kleinigheid om een muur te metselen als je sinds het licht niets hebt gedronken. In de zomer, in Fes, in de zon.',
    'Ze werkten door. Langzamer, met meer pauzes, met minder praten.',
    'Hind droeg water dat niemand aannam, wat het vreemdste werk van haar leven was.',
    '“Waarom kom je dan?” vroeg Driss op de derde dag, met zijn stem die droog was op een manier die ze nooit eerder had gehoord.',
    '“Voor daarna,” zei ze.',
    'En daarna was het beste uur van de dag.',
    'Als de zon achter de muur wegzakte hield alles op. De troffels gingen neer waar ze waren. Iemand riep. En dan zaten er veertig mannen in het stof met een dadel en een kom water, en Hind schonk bij tot haar kruiken leeg waren, en niemand had haast.',
    'Er werd in die uren meer gepraat dan in de rest van het jaar bij elkaar.',
    'Ze hoorde toen pas waar de mannen vandaan kwamen. Twee uit Kairouan, zoals Lalla Fatima. Eén uit Córdoba. Eén die niet wist waar hij vandaan kwam, want hij was als kind meegenomen en had het nooit gevraagd.',
    'Ze hoorde dat Driss een zoon had gehad die was gestorven, en dat hij daarom langzaam werkte, wat zij nooit begrepen zou hebben als hij het niet gezegd had.',
    '“Als je langzaam werkt,” zei hij, “is de dag langer.”',
    'Hij zei het zonder zelfmedelijden, alsof hij uitlegde hoe een boog staat.',
    'Toen de maand voorbij was ging alles terug naar hoe het was, en had iedereen elkaar iets verteld wat er anders nooit uit gekomen was.',
    'Hind heeft later gedacht dat dat er misschien de bedoeling van is. Ze wist het niet zeker. Ze heeft het nooit aan iemand gevraagd die het zou weten.',
  ] },
  { nummer: 12, titel: 'De put', tekst: [
    'In het zesde jaar groeven ze een put op het terrein, en dat was het einde van haar werk.',
    'Hind wist dat al voordat ze begonnen. Ze had het gezien aan de lijn die in het zand werd getrokken, en ze had er niets over gezegd.',
    'Zes jaar lang had ze water van de rivier naar die plek gedragen, vier keer per dag, en nu kwam het water uit de grond omhoog op vijftig stappen van de muur.',
    'Ze bleef de eerste dagen weg.',
    'Op de vierde dag ging ze toch, omdat ze het niet uithield thuis.',
    'De put was een gat met een ring van steen eromheen en een emmer aan een touw, en er stond een jongen bij van een jaar of tien die Hind niet kende en die nu deed wat zij had gedaan.',
    'Driss zag haar staan.',
    '“Het is beter zo,” zei hij.',
    '“Ik weet het.”',
    '“Het is niet beter voor jou.”',
    '“Nee.”',
    'Hij veegde zijn handen af.',
    '“Er komt ook geen metselaar meer als dit af is,” zei hij. “Dat is wat bouwen is. Je werkt jezelf weg.”',
    'Hind heeft daar de rest van haar leven over nagedacht, en ze is er nooit helemaal uit gekomen of het troostend was of niet.',
    'Ze droeg water naar andere plekken. De leerlooiers, de bakker, de huizen aan de helling. Ze verdiende er meer, want die betaalden.',
    'Maar ze kwam elke middag nog langs, met haar lege juk, en ze zat een kwartier op de rand van de binnenhof.',
    'Dat is negenhonderd keer geweest, ongeveer. Ze heeft het nooit geteld.',
  ] },
  { nummer: 13, titel: 'De laatste boog', tekst: [
    'Op de dag dat de laatste boog werd gesloten, stond er zoveel volk in de straat dat de karren er niet door konden.',
    'Hind stond tussen de mensen met haar juk nog op haar schouders, omdat ze net van de leerlooiers kwam en niet had willen wachten.',
    'Ze zag Driss niet. Hij was er wel, zei hij later; hij had achteraan gestaan omdat hij niet van drukte hield.',
    'Ze zag Lalla Fatima niet. Die stond ergens binnen, of thuis; daar werd later over gediscussieerd en niemand wist het zeker.',
    'De sluitsteen ging erin zonder dat iemand het kon zien, want hij ging erin op zes meter hoogte tussen twee mannen op een stelling.',
    'Toen hij erin zat gebeurde er niets.',
    'Dat is wat Hind zich herinnerde: dat er niets gebeurde. Geen gejuich, niet meteen. Veertig mensen hielden hun adem in omdat ze allemaal hetzelfde dachten, namelijk of het nu om zou vallen.',
    'Het viel niet om.',
    'Elke steen duwde tegen de volgende.',
    'Toen pas begon het geroep, en het duurde tot het donker werd.',
    'Wat Hind daarna zag, toen de mensen naar binnen mochten, waren de kamers langs de binnenhof.',
    'Er stonden boeken in.',
    'Ze kon ze niet lezen. Ze heeft er lang naar staan kijken.',
    'Een jongen van een jaar of twaalf stond naast haar, ook te kijken, en die zei: “Mijn vader zegt dat ik hier mag komen.”',
    '“Wat ga je dan doen?”',
    'De jongen dacht na.',
    '“Leren,” zei hij, zoals je iets zegt wat voor de hand ligt.',
    'Hind keek nog een keer naar de kamers en toen naar hem.',
    '“Doe dat,” zei ze.',
  ] },
  { nummer: 14, titel: 'Wat er daarna van kwam', tekst: [
    'Er wordt in dit soort verhalen meestal gestopt op de dag dat het af is.',
    'Dat is jammer, want wat het is geworden ging pas daarna beginnen, en dat duurde langer dan een mensenleven.',
    'Eerst was het een moskee waar iemand uitlegde. Toen waren er meer mensen die uitlegden. Toen kwamen er studenten van buiten de stad, en die moesten ergens wonen, en toen kwamen er kamers.',
    'Toen kwamen er boeken die niemand in Fes had, uit Bagdad, uit Córdoba, uit Egypte.',
    'Toen kwamen er mensen die niet uit Fes kwamen en ook geen moslim waren, want wie wil leren gaat waar geleerd wordt, en dat is in elke eeuw zo geweest.',
    'Er zijn er een paar bij van wie de naam is blijven hangen. Een geleerde uit Córdoba. Een geograaf. Een paus, zegt het verhaal, al is daar ruzie over onder mensen die het kunnen weten.',
    'Al die namen samen zeggen minder dan dit ene feit: het is nooit opgehouden.',
    'Elfhonderd jaar. Door hongersnoden heen, door oorlogen heen, door tijden waarin de stad geplunderd werd en tijden waarin niemand geld had.',
    'Er is in al die eeuwen geen jaar geweest waarin er niemand zat te leren in die binnenhof.',
    'Dat is waarom het in de boeken staat als de oudste universiteit ter wereld die nog werkt, en dat is waarom er een zin over gaat in een gebouw in Parijs waar ze zulke dingen bijhouden.',
    'Hind heeft daar niets van geweten. Ze is gestorven lang voordat er iemand het woord universiteit op zou plakken.',
    'Wat ze wel wist, en wat genoeg is: ze heeft het water gedragen.',
  ] },
  { nummer: 15, titel: 'De sleutel in de muur', tekst: [
    'Ze is er tien jaar later nog een keer geweest, en toen kon ze lezen.',
    'Niet goed. Genoeg om een bord te ontcijferen en de eerste regel van een bladzijde, en daarna langzaam de tweede. Een man die bij de bogen zat had het haar geleerd omdat ze het gevraagd had, en omdat hij zei dat het zoeken naar kennis niet alleen voor de zonen van kooplieden was.',
    'Ze was toen drieëntwintig en getrouwd en ze had een dochter, en aan die dochter heeft ze het hele verhaal verteld, elk jaar opnieuw, tot het meisje het uit haar hoofd kende.',
    'Dit is het stuk dat er niemand anders van wist.',
    'In het eerste jaar, toen ze water bracht en de fundamenten nog open lagen, had ze iets in de muur gelegd.',
    'Ze had het gevonden in het zand bij de rivier: iets van brons, zo lang als haar hand, met een kop van acht punten. Ze had het meegenomen zonder te weten waarom, en toen de metselaars een nis dichtmetselden had ze het erin laten glijden tussen twee stenen.',
    'Ze wist niet waarom ze dat deed. Ze was dertien.',
    'Later dacht ze: ik wilde dat er iets van mij in stond.',
    'De sleutel bleef daar honderdveertig jaar zitten, tot er verbouwd werd en een metselaar hem eruit haalde en in zijn zak stak, en dat is hoe hij verder reisde.',
    'Het gebouw staat er nog. Er wordt nog steeds geleerd. Het heet al-Qarawiyyin, naar de stad waar Fatima’s vader vandaan kwam, en het is de oudste school ter wereld die nooit is opgehouden.',
    'En het is er gekomen omdat een vrouw haar hele erfenis uitgaf aan iets waarvan niemand snapte waar het goed voor was, en een stad langzaam besloot dat ze gelijk had.',
  ] },
]
