import type { SleutelVertaling } from './sleutels-talen'

/**
 * De sleutels van Marokko in het Frans.
 *
 * Wordt deel voor deel vertaald. Wat hier staat is af; de rest valt terug op
 * het Nederlands tot het zover is.
 *
 * De regelval van het Nederlands blijft staan: één alinea daar is één alinea
 * hier. Dat is geen vormfetisj — een hoofdstuk van dit boek is opgebouwd uit
 * korte alinea’s met stiltes ertussen, en wie die samenvoegt haalt het tempo
 * eruit.
 *
 * Aanhalingstekens zijn de Franse « en », de apostrof is overal de
 * typografische ’ en nooit de rechte: die breekt de string waar dit bestand
 * in staat.
 */
export const FR_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'L’incendie des olives',
    jaar: '± 200',
    waar: 'Walili (Volubilis), au pied du Zerhoun',
    verteller: 'Tala, onze ans, fille d’un maître pressier tombé malade',
    flap: 'Tala a la clé de la réserve, et l’intendant la veut. Quand l’huile de toute la ville est en danger, elle doit choisir entre obéir et avoir raison.',
    sleutel: 'La clé est forgée à Walili par le grand-père de Tala, et repart à la fin vers les collines avec une caravane amazighe.',
    echt: [
      'Volubilis — Walili en arabe — était une vraie ville romaine près de Meknès, avec des milliers d’habitants, des thermes et des rues pavées.',
      'La ville vivait de l’huile d’olive. On y a dégagé des dizaines de pressoirs, et ils fonctionnaient selon le même principe que ceux qu’on utilise encore au Maroc aujourd’hui.',
      'Les sols étaient couverts de mosaïques. Une partie est toujours là, à ciel ouvert.',
      'La population était en grande partie amazighe ; la vie romaine et la vie amazighe s’y mêlaient.',
    ],
    verzonnen: [
      'Tala, sa famille et l’intendant Marcus n’ont pas existé.',
      'L’incendie de l’histoire est inventé. Rien ne prouve qu’un grand incendie ait eu lieu à Walili à cette époque.',
      'La clé à l’étoile à huit branches est inventée. Le khatam à huit branches, lui, est un motif marocain bien réel et très ancien.',
    ],
    hoofdstukken: [
      { titel: 'La clé', tekst: [
        'Tala fut réveillée par l’odeur.',
        'Des olives. Des olives pressées, tièdes et amères. Toute la ville sentait cela, ces semaines-là. Elle resta allongée un instant et écouta. Dehors, le grand pressoir grinçait déjà. Cela voulait dire qu’elle était en retard.',
        'Elle sauta de son lit et enfila sa robe par la tête.',
        '« Tala ! » cria sa mère d’en bas. « La porte ! »',
        'La porte. Bien sûr, la porte.',
        'Depuis que son père était tombé malade, Tala faisait son travail. Chaque matin elle allait jusqu’à la réserve derrière la maison et ouvrait la porte. Les jarres étaient là. Cent jarres, remplies d’huile jusqu’au bord, prêtes à partir pour le port.',
        'La clé pendait à un cordon autour de son cou. Elle était en bronze et longue comme sa main. Son grand-père l’avait forgée, bien avant sa naissance. Dans la tête il y avait huit branches, comme une étoile.',
        '« Ne la perds pas », avait dit son père. Il l’avait dit tout bas, parce qu’il ne pouvait plus parler plus fort. « Cette porte ne s’ouvre pour rien d’autre. »',
        'Tala dévala l’escalier, passa devant la cuisine, traversa la cour. Il était encore tôt. Le soleil venait de se poser sur les collines et les pierres étaient froides sous ses pieds.',
        'Devant la réserve il y avait un homme.',
        'Elle s’arrêta net.',
        'Il était grand et portait le manteau rouge de l’intendant. Marcus. Tout le monde à Walili connaissait Marcus, et personne ne l’aimait.',
        '« Tu es en retard », dit-il.',
        '« Je suis à l’heure », dit Tala.',
        'Elle savait qu’elle n’aurait pas dû dire ça. Elle le dit quand même.',
        'Marcus la regarda. Puis il tendit la main.',
        '« Donne-moi donc cette clé. Un enfant n’a pas à garder cent jarres. »',
        'Tala fit un pas en arrière.',
        'Dans sa tête elle entendit son père. *Cette porte ne s’ouvre pour rien d’autre.* Et elle pensa à autre chose, quelque chose qu’elle avait vu la veille et dont elle s’était dit que ce n’était rien.',
        'Deux jarres qui n’étaient pas à leur place.',
        '« Alors ? » dit Marcus.',
        'Tala serra la main autour du bronze. Il était devenu tiède contre sa peau.',
        '« Non », dit-elle.'] },
      { titel: 'Deux jarres', tekst: [
        'Marcus ne rit pas. Il ne se mit pas en colère non plus. C’était ça, le pire.',
        'Il laissa retomber sa main, rajusta son manteau et dit : « Comme tu voudras. » Puis il s’en alla, sortit de la ruelle, sans se retourner.',
        'Tala resta immobile jusqu’à ce qu’elle n’entende plus ses pas. C’est seulement après qu’elle remarqua que ses mains tremblaient.',
        'Elle ouvrit la porte.',
        'À l’intérieur il faisait sombre et frais. Les jarres étaient rangées par dix, avec de la paille entre elles pour qu’elles ne se cognent pas. Dix rangées de dix. Chaque matin elle les comptait. Son père le lui avait appris quand elle avait six ans, et à l’époque c’était encore un jeu.',
        'Elle commença par la gauche et compta à voix haute, comme toujours.',
        'À la dernière rangée, elle s’arrêta.',
        'Il y en avait neuf.',
        'Tala recompta. Neuf. Elle fit le tour de la rangée, se baissa, regarda derrière la paille. Neuf.',
        'La veille aussi, elle avait vu quelque chose d’étrange. Deux jarres mal placées, les anses tournées vers le mur au lieu de l’allée. Elle s’était dit : quelqu’un a fait ça vite. Elle les avait remises droites et n’y avait plus pensé.',
        'Maintenant il en manquait une.',
        'Elle s’assit dans l’embrasure, le dos contre le montant et les genoux repliés, et essaya de décider quoi faire.',
        'Elle pouvait le dire à sa mère. Mais sa mère avait déjà bien assez ce mois-ci : un mari malade à l’étage, une maison pleine de gens à payer, et une récolte qui devait partir au port dans trois semaines.',
        'Elle pouvait le dire à Marcus. Marcus était l’intendant. C’était son travail.',
        'Tala regarda la ruelle où il avait disparu.',
        'Non.',
        '« Tu es dans le passage », dit une voix.',
        'Elle sursauta. Devant elle se tenait un garçon à peu près de son âge, un tablier de cuir sur le ventre et les bras chargés de fagots. Ses mains étaient noires.',
        '« Je ne suis pas dans le passage », dit Tala. « C’est ma porte. »',
        '« Alors tu es dans le passage de ta propre porte. »',
        'Il s’appelait Yidir et il travaillait à la forge, au bout de la rue. Tala le connaissait de vue comme on connaît tout le monde de vue à Walili, et pas plus.',
        'Elle se leva pour le laisser passer. Il ne passa pas.',
        '« Tu comptes tous les matins », dit-il.',
        '« Comment tu sais ça ? »',
        '« Je passe tous les matins. »',
        'Tala hésita. Puis elle le dit quand même, parce qu’il fallait que ça sorte et parce qu’il était là.',
        '« Il en manque une. »',
        'Yidir posa ses fagots par terre.',
        '« Une ? » dit-il. « Alors tu as eu de la chance. Chez nous il manque six barres de fer. »'] },
      { titel: 'Comment on fait l’huile', tekst: [
        'Cet après-midi-là, Tala était au pressoir, comme chaque jour pendant la récolte.',
        'Le pressoir était une pierre creusée, grande comme une charrette, avec une pierre ronde à l’intérieur qu’un âne faisait tourner. Les olives entraient, elles étaient broyées, et ce qui sortait était une pâte brune et épaisse qui ne ressemblait à rien.',
        'C’était la partie qui décevait toujours les étrangers. « C’est ça, l’huile ? » demandaient-ils. Non. C’était le début.',
        'La pâte allait dans des scourtins ronds tressés en jonc. On les empilait sous la presse à levier, et deux hommes tournaient la vis, lentement, comme s’ils avaient tout leur temps. Sous la pile courait une rigole.',
        'C’est de là que ça sortait.',
        'D’abord de l’eau, trouble et sale. Puis, au bout d’un moment, autre chose. Quelque chose qui flottait sur l’eau et qui était plus vert que tout ce que Tala connaissait.',
        'La première fois, son père l’avait prise par la nuque et lui avait tenu la tête au-dessus. « Sens », avait-il dit. « C’est ça. Si ça sent comme ça, c’est bon. Si ça ne sent rien, tu as trop attendu. »',
        'Ce jour-là elle avait menti en disant qu’elle sentait. Maintenant elle sentait vraiment.',
        'Walili vivait de ça. Pas des sols en mosaïque sur lesquels marchaient les visiteurs, pas des colonnes de la place, pas des rues pavées. De ça. D’olives pressées qui partaient en jarres, sur des charrettes vers la côte, puis sur des bateaux vers des endroits dont Tala ne connaissait que les noms.',
        'Elle surveillait la rigole, et les scourtins, et l’âne, et pendant ce temps elle pensait à quatre-vingt-dix-neuf jarres.',
        'Six barres de fer, avait dit Yidir. De la forge.',
        'Le fer coûtait cher. L’huile coûtait cher. Et les deux sortaient de la ville dans la même direction : par la route du port.',
        '« Tala. » Un des hommes montra la rigole. « Ça déborde. »',
        'Elle se précipita et glissa le bol dessous, trop tard. Un filet d’huile coula sur la pierre et disparut entre les joints.',
        'L’épaisseur d’un doigt, peut-être deux. De quoi nourrir une famille pendant une semaine.',
        'L’homme ne dit rien. C’était pire.'] },
      { titel: 'Ce qu’un intendant a le droit de faire', tekst: [
        'Marcus revint le troisième jour, et il ne vint pas seul.',
        'Tala le vit entrer dans la cour avec deux hommes derrière lui. Sa mère sortit, s’essuya les mains sur sa robe, et se planta exactement entre lui et la porte.',
        '« Paix », dit Marcus.',
        '« Paix », dit sa mère, sur le ton qu’on prend quand on ne le pense pas.',
        '« Ton mari est malade. »',
        '« Mon mari se repose. »',
        '« Trois semaines », dit Marcus. « Dans trois semaines la récolte part au port, et la ville compte sur ce qu’il y a dans cette maison. Je dois savoir que c’est là. »',
        '« C’est là. »',
        '« Je veux le voir. »',
        'Il y eut un silence. Tala se tenait dans l’embrasure de la cuisine et n’osait pas bouger.',
        'Sa mère dit : « Tu peux regarder. C’est ma fille qui ouvre. »',
        'Tala traversa la cour sous les yeux de cinq personnes. Elle fit passer le cordon par-dessus sa tête, glissa la clé dans la serrure et poussa la porte.',
        'Marcus entra. Il longea les rangées, lentement, les mains dans le dos. Devant la dernière rangée, il s’arrêta.',
        'Tala retint son souffle.',
        '« Quatre-vingt-dix-neuf », dit Marcus.',
        'Il se retourna et regarda sa mère.',
        '« Il devrait y en avoir cent. »',
        'Sa mère se raidit. Tala le vit à ses épaules.',
        '« Alors il y en a une de cassée », dit-elle.',
        '« Alors il y aurait des tessons. » Marcus écarta les mains. « Je ne vois pas de tessons. Je vois de la paille qu’on a remise droite. »',
        'Il attendit un instant, juste assez longtemps.',
        '« Je ne dis pas que vous volez », dit-il alors. « Je dis qu’une enfant de onze ans a la clé de cent jarres, et qu’aujourd’hui il y en a quatre-vingt-dix-neuf. Voilà ce que je dis. Et je le dirai aussi sur la place. »',
        'Il sortit et passa devant Tala comme si elle était un poteau.',
        'Quand il fut parti, sa mère s’assit sur la margelle du puits. Elle ne dit rien pendant très longtemps.',
        '« Maman », dit Tala. « Je ne l’ai pas— »',
        '« Je sais. »',
        '« Je les ai comptées lundi et il y en avait encore— »',
        '« Tala. » Sa mère leva les yeux. Ils étaient rouges. « Je sais. Et ça ne nous aide en rien. »'] },
      { titel: 'La forge', tekst: [
        'Yidir était assis sur un seau retourné devant la forge et ponçait une charnière.',
        '« Tu avais raison », dit Tala.',
        '« Les gens me disent rarement ça », dit Yidir sans lever les yeux. « À propos de quoi ? »',
        '« Du fait que ce n’était pas une seule jarre. »',
        'Cette fois il leva les yeux.',
        'Tala s’assit à côté de lui sur le seuil et raconta. Marcus, les quatre-vingt-dix-neuf, ce qu’il allait dire sur la place. Yidir écoutait comme il faisait tout : comme s’il pensait à autre chose en même temps, mais il ne ratait rien.',
        '« Et ton fer ? » demanda-t-elle.',
        '« Six barres. Mon maître pense qu’il s’est trompé en comptant. » Yidir haussa les épaules. « Mon maître ne se trompe jamais en comptant. »',
        '« Quand ? »',
        '« La semaine dernière. Et trois la semaine d’avant. »',
        'Tala remonta les genoux.',
        '« Qu’est-ce qui sort de la ville ? » demanda-t-elle. « Chaque jour, je veux dire. »',
        'Yidir réfléchit.',
        '« Des charrettes », dit-il. « De l’huile, du grain, des peaux, du fer. Tout passe par la route du nord. Il y a un poste de garde à la porte. Là, tout est noté. »',
        '« Par qui ? »',
        'Yidir la regarda.',
        '« Par l’intendant », dit-il.',
        'Ils ne dirent rien pendant un moment, ni l’un ni l’autre.',
        '« Ça ne prouve rien », finit par dire Tala.',
        '« Non. »',
        '« Si je dis ça, ils diront qu’une gamine de onze ans accuse un homme parce qu’il ne l’aime pas. »',
        '« Oui », dit Yidir. « C’est ce qu’ils diront. »',
        'Il posa la charnière.',
        '« Donc il te faut quelque chose qu’ils ne peuvent pas balayer avec des mots. »',
        '« Comme quoi ? »',
        '« Comme voir ce qui passe cette porte la nuit. »',
        'Tala le regarda. Il la regarda en retour, et pour la première fois depuis qu’elle le connaissait, il sourit.'] },
      { titel: 'Ce qui passe la porte la nuit', tekst: [
        'Ils étaient couchés sur le toit des thermes, à plat ventre, le menton sur les bras.',
        'Le toit était encore chaud de la journée. En dessous d’eux passait la rue qui menait à la porte nord, assez large pour deux charrettes côte à côte. À la porte brûlait une seule lampe.',
        '« Encore combien de temps ? » chuchota Tala.',
        '« Je ne sais pas. »',
        '« Tu as dit qu’il passait des charrettes la nuit. »',
        '« J’ai dit que je *croyais* qu’il passait des charrettes la nuit. »',
        'Tala soupira et posa la tête sur son bras.',
        'Les étoiles, cette nuit-là, étaient incroyables. En ville on n’en voyait que la moitié, à cause de la lumière et de la fumée, mais là-haut il y en avait tellement que ça en devenait inquiétant.',
        '« Ma grand-mère dit que c’est une carte », dit Yidir.',
        '« Les étoiles ? »',
        '« Oui. Si tu sais les lire, tu peux aller partout. Elle dit que sa famille est venue du désert jusqu’ici comme ça. »',
        '« Tu sais les lire, toi ? »',
        '« Non », dit Yidir. « Personne ne me l’a appris. »',
        'C’est là qu’ils l’entendirent.',
        'Une charrette. Pas deux ânes, pas de chevaux — un âne, au pas, et le bruit du bois qui craque sous le poids.',
        'Tala se glissa jusqu’au bord.',
        'La charrette sortait d’une rue de côté. Deux hommes marchaient à côté, tous deux la tête enveloppée d’un tissu. Sur la charrette il y avait de la paille, et sous la paille quelque chose de rond.',
        'À la porte, la charrette s’arrêta.',
        'Un homme sortit de la guérite avec une lampe. Il n’alla pas vers la charrette. Il alla vers les hommes, leur parla brièvement, et nota quelque chose sur une tablette.',
        'Puis il leva la barrière.',
        'La charrette s’enfonça dans la nuit.',
        'Tala relâcha son souffle. Elle n’avait pas remarqué qu’elle le retenait.',
        '« Il n’a pas regardé », dit-elle. « Il n’a pas regardé sous la paille. »',
        '« Non. »',
        '« C’est— »',
        '« Ça ne fait toujours rien », dit Yidir. « C’est un homme qui ne regarde pas assez bien. On ne pend personne pour ça. »',
        'Il avait raison, et Tala le savait aussi.',
        'Mais quand la charrette prit le virage, il se passa quelque chose. L’âne eut peur de quelque chose dans le noir, tira sur le côté, et la charrette monta d’une roue sur le bord du trottoir.',
        'Quelque chose tomba de la charrette.',
        'Ça roula, s’immobilisa contre le mur, et resta là.',
        'Une jarre.',
        'Un des hommes jura, revint sur ses pas, la ramassa et la remit sous la paille. La charrette repartit.',
        'Mais Tala avait vu ce qu’il y avait dessus.',
        'Sur l’épaule de chaque jarre de leur maison, son père imprimait un signe dans l’argile avant la cuisson. Huit branches. Une étoile.',
        'Elle attrapa le bras de Yidir si fort qu’il siffla entre ses dents.',
        '« Elle est à nous », dit-elle.'] },
      { titel: 'Ce que tu dis et ce qu’ils entendent', tekst: [
        'Le lendemain matin, Tala alla sur la place.',
        'Elle y avait pensé toute la nuit, ou en tout cas la moitié de la nuit ; l’autre moitié elle avait dormi sans le vouloir. Elle savait ce qu’elle allait dire. Elle l’avait répété trois fois contre le mur de sa chambre.',
        'Sur la place, sous les colonnes, le conseil siégeait. C’est-à-dire : cinq hommes sur des bancs de pierre, un scribe à côté, et autour tous ceux qui avaient quelque chose à réclamer.',
        'Marcus était déjà là.',
        'Tala attendit qu’un homme ait fini de parler d’un mur et d’un voisin. Puis elle s’avança.',
        '« Je voudrais dire quelque chose », dit-elle.',
        'Cinq hommes levèrent les yeux. L’un d’eux, le plus vieux, avec un visage de figue sèche, se pencha en avant.',
        '« Tu es la fille de qui ? »',
        '« De Yuba, le pressier. De la rue des Colonnes. »',
        '« Il est malade. »',
        '« Oui », dit Tala. « C’est pour ça que je suis là. »',
        'Elle raconta. La jarre disparue, et une autre le lendemain. La charrette dans la nuit et l’homme qui avait levé la barrière sans regarder sous la paille. La jarre tombée, et le signe aux huit branches.',
        'Elle raconta exactement comme elle l’avait répété, et pendant qu’elle le faisait, elle s’entendit elle aussi.',
        'Elle entendit comment ça sonnait.',
        'Une enfant. Un toit. Le noir. Un signe que personne d’autre n’avait vu.',
        'Quand elle eut fini, il y eut un silence. Puis Marcus dit, très calmement : « Vous permettez ? »',
        'Le plus vieux hocha la tête.',
        '« La petite a raison : il manque des jarres », dit Marcus. « Je les ai comptées moi-même, avant-hier, dans leur propre réserve. Quatre-vingt-dix-neuf sur cent. Je l’ai dit à ce moment-là. »',
        'Il écarta les mains, comme il le faisait.',
        '« Qui a la clé de cette porte ? »',
        'Personne ne dit rien.',
        '« Elle », dit Marcus. « Une enfant de onze ans. Et maintenant qu’il en manque une, c’est une charrette dans la nuit. Une charrette qu’elle est la seule à avoir vue. »',
        'Le plus vieux du conseil regarda Tala, et son regard n’était pas hostile. C’était encore ça, le pire.',
        '« Petite », dit-il. « Rentre chez toi. Occupe-toi de ton père. »',
        'Tala resta sur la place, les bras le long du corps et les oreilles brûlantes, et tout autour d’elle les gens s’étaient remis à parler d’un mur et d’un voisin.'] },
      { titel: 'L’incendie', tekst: [
        'L’incendie commença quatre jours plus tard, et il ne commença pas chez eux.',
        'Tala en fut réveillée. Pas par la lumière et pas par les cris — par le bruit. Un grondement profond et doux, comme si quelqu’un, tout près, expirait très longuement.',
        'Elle était à la fenêtre avant d’être réveillée.',
        'De l’autre côté de la rue, deux maisons plus loin, la réserve de Quintus brûlait. Quintus pressait de l’huile lui aussi. Ses jarres étaient dans une salle sous sa maison, et le feu en sortait maintenant par la fenêtre, à plat, et non vers le haut comme le feu est censé faire.',
        'C’est à cause de l’huile, Tala l’apprit plus tard. L’huile ne brûle pas pareil.',
        'On criait déjà. Il y avait déjà des gens dans la rue avec des seaux et des couvertures, et quelqu’un frappait avec un bâton la plaque de bronze près du puits, et Tala dévala l’escalier sans chaussures.',
        'Sa mère l’attrapa par le bras dans l’embrasure.',
        '« Pas par là. »',
        '« Mais— »',
        '« Tala. » Sa mère la tenait des deux mains. « Notre porte. Tout de suite. »',
        'Et Tala comprit.',
        'Si ça se propage, ce sera chez eux. Cent jarres — quatre-vingt-dix-neuf — pleines d’huile, derrière une porte en bois, contre le même mur.',
        'Elle courut à la réserve, fit passer le cordon par-dessus sa tête et glissa la clé dans la serrure. Ses mains étaient si moites que le bronze tournait à vide. La troisième fois, ça marcha.',
        'La porte s’ouvrit. La fraîcheur vint à sa rencontre, et l’odeur.',
        'Derrière elle, la rue entière se mit à porter des jarres.',
        'Ils les portaient dans la cour, près du puits, dans la rue, partout où aucun mur ne brûlait. Les voisins portaient, des gens qu’elle connaissait à peine, des gens à qui son père n’avait jamais parlé. Quelqu’un avait une échelle. Quelqu’un jetait des couvertures dans l’eau du puits et les faisait passer.',
        'Tala porta jusqu’à ce que ses bras refusent, et après elle porta encore.',
        'À la soixante-dixième jarre elle vit Yidir. Il arrivait avec quatre autres de la forge, et ils traînaient quelque chose qui ressemblait à un long croc.',
        'À la quatre-vingt-cinquième, le toit de la réserve de Quintus s’effondra vers l’intérieur.',
        'À la dernière, le soleil était presque levé.',
        'Il n’y avait plus de feu alors. Il n’y avait plus que de la fumée qui traînait bas dans la rue, et deux cents personnes debout qui regardaient sans rien dire, et des mains noires, et quelque part un enfant qui pleurait.',
        'Tala était assise sur le pas de la porte, contre sa mère.',
        'Et c’est pour ça qu’elle fut la seule à voir l’homme qui sortit de la ruelle à côté de la maison de Quintus, à contre-courant, son manteau sur le bras au lieu de sur les épaules.',
        'Le manteau était rouge.'] },
      { titel: 'Le manteau rouge', tekst: [
        'Elle le raconta à Yidir avant de le raconter à qui que ce soit.',
        'Il écouta sans l’interrompre, et quand elle eut fini, il dit : « Ça ne fait toujours rien. »',
        '« Je l’ai vu. »',
        '« Tu as vu un homme en manteau rouge dans une rue pleine de gens couverts de suie. » Yidir donna un coup de pied dans une pierre. « Moi je te crois. Le conseil, non. »',
        'Tala savait qu’il avait raison et elle en avait assez qu’il ait toujours raison.',
        '« Quoi alors ? » dit-elle. « Je ne peux quand même pas ne rien faire. »',
        '« Non », dit Yidir. « Mais il te faut quelque chose qui ne vienne pas de toi. »',
        'Il s’assit sur la margelle du puits, les talons contre la pierre.',
        '« À la porte, ils notent tout », dit-il. « Sur de la cire. Ce qui sort, combien, et de qui. Ces tablettes partent chaque mois à la maison de ville. »',
        '« Et s’il n’y a rien d’étrange dessus ? »',
        '« Alors il n’y a rien d’étrange dessus », dit Yidir. « Et alors tu sais que ce n’est pas dans les registres, mais dans le noir. C’est déjà quelque chose. »',
        'Il la regarda.',
        '« Mais s’il y a bien quelque chose — si c’est écrit douze jarres alors que treize sont sorties — alors ce n’est plus une enfant qui a vu quelque chose. C’est un nombre à côté d’un nombre, et les nombres, on ne les balaie pas avec des mots. »',
        'Tala pensa à la nuit sur le toit. À l’homme qui n’avait pas regardé sous la paille.',
        '« Qui peut consulter ces tablettes ? »',
        '« Pas nous. »',
        '« Qui alors ? »',
        'Yidir se tut un instant.',
        '« Mon maître », dit-il. « Il fournit le fer pour les serrures de la maison de ville. Il y entre sans que personne demande pourquoi. »',
        '« Demande-lui, alors. »',
        '« Ce n’est pas quelqu’un qui va se mêler des affaires de l’intendant. »',
        '« Demande-lui », répéta Tala.',
        'Yidir regarda ses mains noires.',
        '« D’accord », dit-il. « Mais pas ce soir. Ce soir c’est le vendredi du marché et il est de mauvaise humeur. »',
        'Malgré tout, Tala dut rire.',
        'C’était la première fois depuis des jours.'] },
      { titel: 'Ce qui était écrit sur la cire', tekst: [
        'Le forgeron s’appelait Amanar et c’était le plus grand homme que Tala ait jamais vu de près.',
        'Pendant deux jours il ne dit rien. Puis, le troisième matin, il arriva dans la rue des Colonnes avec un paquet sous le bras, et il s’assit sur le pas de la réserve comme si c’était normal.',
        '« Tu es la fille de Yuba », dit-il.',
        '« Oui. »',
        '« Ton père a donné à ma mère de l’huile pendant tout un hiver sans se faire payer. » Amanar regarda la rue. « C’était il y a seize ans. Moi je ne l’ai pas oublié et lui ne se souvient plus de l’avoir fait. »',
        'Il posa le paquet sur la marche.',
        'C’étaient deux tablettes de cire, dans un cadre de bois, griffure sur griffure sur griffure.',
        '« Tu peux regarder », dit Amanar. « Pas emporter. Dans une heure elles sont revenues à leur place. »',
        'Tala s’assit et lut.',
        'Elle savait lire. Pas couramment, mais assez. Son père y avait tenu : « Celui qui ne sait pas lire croit ce qu’un autre lui dit qui est écrit. »',
        'Sur la cire il y avait des lignes. Date, porte, quoi, combien, à qui.',
        'Elle chercha son propre nom. Elle le trouva onze fois.',
        '*Yuba, pressier, rue des Colonnes. Huit jarres.*',
        '*Yuba, pressier. Douze jarres.*',
        '*Yuba, pressier. Neuf jarres.*',
        'Tala additionna. Elle compta deux fois, et la deuxième fois elle l’écrivit dans le sable à côté de ses pieds.',
        'Cent dix-sept jarres. En quatre semaines, sorties par la porte, au nom de son père.',
        'Elle leva les yeux.',
        '« Ça ne va pas », dit-elle.',
        '« Non ? » dit Amanar.',
        '« On en a fait cent soixante cette saison. Je le sais exactement, je les ai comptées à la cuisson. Soixante ont été vendues en ville. Il y en avait cent dans la réserve. » Elle montra le sable. « Cent soixante. Pas cent soixante-dix-sept. »',
        'Amanar ne dit rien.',
        '« Dix-sept jarres sont sorties par la porte alors que nous ne les avons jamais faites », dit Tala. « À notre nom. »',
        'Elle entendit elle-même ce que cela voulait dire, en le disant.',
        'Ce n’étaient pas seulement leurs jarres qu’on volait.',
        'C’était leur nom.',
        'Quand on compterait à la maison de ville, et qu’il arriverait moins que ce qui était sorti par la porte, il y aurait une maison où la piste s’arrêtait. Et cette maison serait la leur.',
        '« Amanar », dit-elle, et sa voix sonnait bizarrement. « Ils sont en train de nous préparer. »',
        'Le forgeron se leva et épousseta ses genoux.',
        '« Oui », dit-il. « C’est ce qu’ils font. »',
        'Il reprit les tablettes.',
        '« Viens demain sur la place avec ta mère. Et apporte ce sable — non : recopie-le sur quelque chose qui ne s’envole pas. »'] },
      { titel: 'Deux nombres côte à côte', tekst: [
        'Le conseil siégeait comme toujours : cinq hommes, un scribe, et le brouhaha des gens qui attendaient que ce soit leur tour.',
        'Cette fois, Tala n’était pas seule.',
        'À sa gauche se tenait sa mère, dans la robe qu’elle ne mettait que quand il arrivait quelque chose de grave ou quelque chose de beau. À sa droite se tenait Amanar, et derrière Amanar quatre hommes de la forge qui n’avaient rien à voir là-dedans et qui étaient venus quand même.',
        'Plus loin, contre une colonne, se tenait Yidir.',
        'Le plus vieux du conseil — celui au visage de figue sèche — regarda le groupe et haussa les sourcils.',
        '« Encore toi », dit-il à Tala.',
        '« J’ai compté », dit Tala.',
        'Elle l’avait écrit sur un morceau de cuir, parce que le cuir ne s’envole pas. Elle lut à voix haute. Ce qu’ils avaient fabriqué. Ce qui avait été vendu en ville. Ce qu’il y avait dans la réserve. Et ensuite ce qui, d’après les tablettes de la porte, était sorti de la ville au nom de son père.',
        'Deux nombres.',
        'Quand elle eut fini, le silence fut d’une autre sorte que la fois précédente.',
        'Marcus s’avança. Il était toujours calme, mais plus de la même façon.',
        '« Une enfant a regardé dans les tablettes de la ville », dit-il. « C’est interdit. »',
        '« C’est moi qui les ai apportées », dit Amanar.',
        'Le silence se fit plus épais encore.',
        'Le plus vieux du conseil se tourna vers le scribe à côté de lui.',
        '« Va les chercher. »',
        'Ce fut long. Personne ne partit. Quelqu’un apporta un tabouret à la mère de Tala et elle ne s’assit pas dessus.',
        'Quand les tablettes furent là, le scribe lut à voix haute ce qui y était écrit, et un autre homme additionna avec des cailloux sur une planche, et toute la place l’entendit.',
        'Cent dix-sept.',
        'Le plus vieux regarda longuement les nombres, puis Marcus, puis de nouveau les nombres.',
        '« Qui écrit à la porte nord ? » demanda-t-il.',
        '« Ça change », dit Marcus.',
        '« Qui désigne celui qui écrit ? »',
        'Marcus ne répondit pas.',
        'Le plus vieux soupira, et c’était le soupir d’un homme qui comprend quelque chose qu’il aurait préféré ne pas comprendre, et qui sait qu’il va devoir en faire quelque chose.',
        '« Assieds-toi », dit-il à Tala. « Pas toi, Marcus. Toi, tu restes debout. »'] },
      { titel: 'Ce qui reste', tekst: [
        'Il fallut encore trois semaines avant que quelque chose change vraiment, et ce fut la plus longue leçon de cet été-là : la vérité ne fonctionne pas comme dans une histoire, où tu la dis et où tout le monde hoche la tête.',
        'Un homme vint de la ville dont dépendait Volubilis pour vérifier les registres. Des gens furent entendus. Deux fois on ne dit rien, et une fois on dit quelque chose que personne n’attendait : le garde de la porte nord, un garçon de dix-neuf ans, craqua à la troisième question et raconta tout.',
        'Marcus disparut avant la fin. Sa maison resta vide un mois, puis fut donnée à quelqu’un d’autre.',
        'Le père de Tala ne guérit pas, pas tout à fait. À l’automne il put de nouveau s’asseoir dans la cour et écouter le pressoir craquer, et cela semblait lui suffire. Il demanda les chiffres et elle les lui donna. Il lui fit raconter trois fois ce qui s’était passé sur la place, et la troisième fois il pleura, et elle ne l’avait jamais vu faire ça.',
        'La récolte partit au port. Cent jarres. Le compte était bon.',
        'La semaine suivante, Yidir passa avec sa grand-mère.',
        'Sa grand-mère était petite et vieille et elle avait les yeux de quelqu’un qui regarde bien plus loin que là où elle se trouve. Elle dit qu’elle s’en allait : elle retournait dans sa famille, vers les pâturages des montagnes, avant l’hiver. Elle le dit comme s’il s’agissait d’une promenade.',
        '« Yidir vient avec moi », dit-elle. « Un temps. »',
        'Tala regarda Yidir. Yidir regarda ses mains.',
        '« C’est long, un temps ? » demanda-t-elle.',
        '« Ça, on ne le sait qu’après », dit sa grand-mère.',
        'Ce soir-là, Tala fit passer le cordon par-dessus sa tête.',
        'La clé était tiède, comme toujours. Huit branches dans la tête, une étoile. Son grand-père l’avait forgée dans une forge qui n’existait plus.',
        'Elle la tint dans sa main et pensa à ce que son père avait dit. *Cette porte ne s’ouvre pour rien d’autre.*',
        'Elle la donna à Yidir.',
        '« Ce n’est pas possible », dit-il aussitôt.',
        '« Tu m’as crue quand personne ne me croyait. »',
        '« Ça ne vaut pas une clé. »',
        '« C’est ma clé », dit Tala. « C’est moi qui décide ce qu’elle vaut. »',
        'Yidir la tenait comme si elle était brûlante.',
        '« Qu’est-ce que j’en fais ? »',
        '« Je ne sais pas », dit Tala. « La donner, je crois. À quelqu’un que tu crois. »',
        'Ils partirent le lendemain matin, avec trois ânes et un chien, vers les collines, et Tala monta sur le toit des thermes pour les suivre du regard jusqu’à ce qu’on ne les voie plus.',
        'Elle ne savait pas encore que c’était une bonne chose que la clé s’en aille.',
        'Car Walili ne serait pas toujours là. Le tremblement de terre vint bien plus tard, et la ville fut lentement vidée — pierre après pierre, jusqu’à ce qu’il ne reste que les colonnes, les pressoirs à olives et les sols en mosaïque qui y sont encore aujourd’hui, à ciel ouvert, près de Meknès.',
        'Tout ce qu’il y avait dans les maisons a disparu.',
        'Sauf la clé.'] },
    ],
  },
  2: {
    titel: 'L’autre rive',
    jaar: '711',
    waar: 'Tanger, et le détroit vers le nord',
    verteller: 'Ayyur, douze ans, fils d’un berger, chargé des chevaux',
    flap: 'Une armée traverse vers un pays que personne ne connaît. Ayyur a le droit de venir pour s’occuper des chevaux — et il découvre que l’homme que tout le monde suit a peur, lui aussi.',
    sleutel: 'La clé pend au harnais d’un cheval et reste de l’autre côté, dans la sacoche d’un scribe.',
    echt: [
      'Tariq ibn Ziyad était un chef de guerre amazigh qui, en 711, traversa le détroit avec une armée vers le sud de l’Espagne actuelle.',
      'Le rocher où il débarqua porte encore son nom : Jabal Tariq, la montagne de Tariq — déformé en Gibraltar.',
      'La plus grande partie de son armée était composée de soldats amazighs d’Afrique du Nord.',
      'L’histoire selon laquelle il aurait fait brûler ses navires n’a été écrite que des siècles plus tard et n’est pas tenue pour un fait par les historiens.',
    ],
    verzonnen: [
      'Ayyur et sa famille n’ont pas existé.',
      'Les conversations avec Tariq sont inventées. On ne sait presque rien de son caractère.',
      'Le voyage de la clé est inventé.',
    ],
    hoofdstukken: [
      { titel: 'Le garçon aux chevaux', tekst: [
        'Ayyur avait douze ans et il était bon à deux choses : les chevaux et l’attente.',
        'La deuxième, il la tenait de son père, qui gardait des moutons dans les collines derrière Tanger et qui pouvait se taire du lever au coucher du soleil sans que cela lui coûte rien. La première, il ne la tenait de personne. Les chevaux l’aimaient bien, tout simplement, et c’était ainsi depuis qu’il savait marcher.',
        'C’est pour ça qu’il se tenait maintenant dans le camp, hors des murs de la ville, et non dans les collines.',
        'Son père avait perdu trente moutons au froid pendant l’hiver, et le reste à la dette. Il n’y avait plus de troupeau à garder. Il y avait par contre une armée, et une armée a des chevaux, et les chevaux ont besoin de quelqu’un qui reste auprès d’eux la nuit.',
        'On le payait en nourriture et en cuivre. Pas beaucoup de cuivre.',
        'Ayyur ne s’en plaignait pas. Il avait le droit de dormir près des chevaux et il connaissait désormais les quarante-sept par leur nom, y compris ceux qu’il avait inventés lui-même parce que personne ne les lui avait dits.',
        'Ce mois de mars-là, le camp était devenu plus plein qu’il ne l’avait jamais vu. D’abord cent hommes, puis cinq cents, puis tellement qu’on ne pouvait plus compter. Ils venaient du sud et de l’est, des montagnes et de la côte. La plupart étaient amazighs comme lui. Ils parlaient sa langue, avec d’autres mots pour les mêmes choses, et ils riaient de sa façon de dire.',
        'Il y en avait aussi qui parlaient arabe. Pas beaucoup. Quelques centaines.',
        'Et tout le monde attendait.',
        'Quoi, ils le savaient : des navires. À quoi serviraient les navires, on en parlait comme les hommes parlent de ce qu’ils ne savent pas — avec beaucoup d’assurance, et autrement chaque jour.',
        '« L’autre rive », disait l’un.',
        '« Il n’y a rien sur l’autre rive », disait l’autre. « De l’eau, et puis encore de l’eau. »',
        '« Il y a un roi sur l’autre rive », disait un troisième. « Avec une couronne d’or si lourde qu’il ne peut pas la porter. »',
        'Ayyur brossait le flanc d’une jument qu’il appelait Tafukt, ce qui veut dire soleil, et il écoutait les trois.',
        'Il avait vu l’autre rive. Tout le monde à Tanger avait vu l’autre rive. Par temps clair il y avait une bande de terre à l’horizon, et au-dessus un rocher qui avait l’air d’avoir été posé là par quelqu’un.',
        'On pouvait le regarder sans jamais y penser, toute une vie durant.',
        'Jusqu’à ce que quelqu’un se mette à rassembler des navires.'] },
      { titel: 'L’homme qui n’était pas grand', tekst: [
        'Il vit Tariq pour la première fois un mardi, auprès des chevaux, et pendant une demi-minute il ne sut pas qui il avait devant lui.',
        'L’homme n’était pas grand. Ce fut la première chose.',
        'Ayyur s’était imaginé quelqu’un comme dans les histoires : une tête de plus que tous les autres, un manteau qui traîne derrière lui, dix hommes autour. Celui-là était seul, dans une veste poussiéreuse sans ornement, et il regardait Tafukt comme regarde un cheval quelqu’un qui s’y connaît en chevaux.',
        '« Qui monte celle-ci ? » demanda-t-il.',
        '« Personne », dit Ayyur. « Elle ne laisse personne monter. »',
        '« Pourquoi pas ? »',
        '« Je ne sais pas. Elle est tombée une fois, je crois. Avant d’arriver ici. »',
        'L’homme posa la main sur l’encolure de la jument et l’y laissa sans caresser.',
        '« Et avec toi ? »',
        '« Avec moi elle est calme. »',
        '« Alors elle n’a pas peur des gens », dit l’homme. « Elle a peur de ce que les gens lui ont fait. »',
        'Il regarda Ayyur pour la première fois.',
        '« Comment t’appelles-tu ? »',
        '« Ayyur. »',
        '« La lune. » L’homme hocha la tête, comme si c’était un nom raisonnable. « Fais en sorte qu’elle soit encore comme ça dans deux semaines. »',
        'Puis il s’en alla.',
        'Il fallut attendre le soir pour que quelqu’un le dise à Ayyur, et quand il l’apprit il s’assit sur une caisse et y resta un moment.',
        'Tariq ibn Ziyad. Amazigh, comme lui. D’une famille que personne ne connaissait. Gouverneur de Tanger, et l’homme qui devait faire passer l’eau à l’armée couchée là sur la plage.',
        'Il était resté là à regarder un cheval.',
        '« Il vient tous les jours », dit Sa3id, le vieux cavalier à la mauvaise jambe, qui était entre-temps venu s’asseoir à côté de lui parce qu’il venait toujours s’asseoir à côté de quelqu’un. « Tous les jours aux chevaux et tous les jours aux navires. Il ne dort pas, je crois. »',
        '« Il n’est pas grand », dit Ayyur.',
        'Sa3id rit si fort qu’il en toussa.',
        '« Non, petit », dit-il. « Ça, il ne l’est pas. »'] },
      { titel: 'Quatre navires pour sept mille hommes', tekst: [
        'Le problème était simple et personne ne pouvait le résoudre.',
        'Il y avait sept mille hommes sur cette plage, plus les chevaux, plus les armes, plus de quoi manger pendant des semaines. Et il y avait quatre navires.',
        'Ayyur entendit une fois Sa3id calculer combien de fois ces quatre navires devraient alors faire l’aller-retour, et Sa3id arriva à un nombre dont il rit lui-même, et après il se tut.',
        '« Qu’est-ce qu’il y a ? » demanda Ayyur.',
        '« Rien. »',
        '« Sa3id. »',
        'Le vieil homme se frotta le genou, ce qu’il faisait quand il réfléchissait.',
        '« Quand tu as quatre navires », dit-il, « c’est le premier chargement le plus dangereux. Celui-là est de l’autre côté, seul, sans personne derrière lui. Et si quelque chose tourne mal, les navires sont partis pour deux jours. »',
        'Il regarda la mer.',
        '« Je n’aimerais pas être dans le premier chargement. »',
        'Les navires n’étaient pas à eux. Tout le camp le savait. Ils venaient d’un homme de l’autre côté, un seigneur de Ceuta qui était en querelle avec son propre roi et qui aidait pour cette raison. Son nom se prononçait de dix façons et personne ne l’avait jamais vu.',
        '« Pourquoi est-ce qu’il aide ? » demanda Ayyur.',
        '« Parce qu’il veut quelque chose. »',
        '« Quoi ? »',
        '« Ça, on ne le saura qu’une fois qu’on l’aura donné », dit Sa3id.',
        'Ces semaines-là, Ayyur apprit sur la guerre plus qu’il n’aurait jamais voulu savoir, et presque rien de tout cela ne parlait de combattre. Cela parlait d’eau dans des tonneaux qui tourne au bout de quatre jours. De la quantité d’orge que mange un cheval par jour et de ce que cela fait pour sept cents chevaux. D’hommes qui tombent malades à force d’attendre et qui se disputent pour rien.',
        'Un matin il y eut une bagarre au puits. Deux hommes de tribus différentes, pour un seau.',
        'Tariq vint lui-même. Il les fit relever tous les deux, il leur parla doucement, et il les renvoya ensemble avec la même tâche : un seau, deux hommes, porter de l’eau pour les chevaux toute la journée.',
        'Le soir ils mangeaient côte à côte.',
        'Sa3id vit Ayyur regarder.',
        '« C’est *ça* », dit-il. « C’est pour ça qu’ils le suivent. Pas parce qu’il sait se battre. Ils savent tous se battre. »'] },
      { titel: 'La nuit d’avant', tekst: [
        'Le soir avant la première traversée était chaud et il n’y avait pas de vent, et c’était précisément ce dernier point le problème.',
        'Ayyur n’arrivait pas à dormir. Il était couché entre les chevaux, la tête sur une selle qui sentait le cuir et la sueur, et il regardait les étoiles qu’on apercevait entre les toiles des tentes.',
        'À côté de lui il y avait Sa3id, qui ne dormait pas non plus.',
        '« Tu as peur ? » demanda Ayyur.',
        '« Oui », dit Sa3id aussitôt.',
        'Ayyur ne s’attendait pas à ça. Il s’attendait à ce que le vieil homme rie et dise quelque chose sur les vingt batailles qu’il avait déjà faites.',
        '« Tous ceux qui disent le contraire mentent », dit Sa3id. « Ou alors ils sont bêtes. Les hommes bêtes ne servent à rien dans un bateau. »',
        'Il se redressa, lentement, la main sur le genou.',
        '« Tu sais ce que je fais quand j’ai peur ? »',
        '« Non. »',
        '« Je dis le nom de Dieu et ensuite je fais la chose suivante qui doit être faite. Pas toute la chose. La chose suivante. »',
        'Ayyur y réfléchit.',
        'Dans son village, la religion était quelque chose des dernières années. Sa grand-mère ne l’avait pas, sa mère à moitié, son père entièrement — à sa manière, en silence, sans en dire grand-chose. Dans le camp, elle était partout : des hommes qui s’arrêtaient au milieu de ce qu’ils faisaient et se tournaient dans la même direction, puis reprenaient comme s’il ne s’était rien passé.',
        'Il n’avait jamais bien compris. Personne ne le lui avait expliqué. Ils le faisaient, simplement, et lui restait là avec une brosse à la main.',
        '« Sa3id », dit-il. « Je ne sais pas comment on fait. »',
        'Le vieil homme le regarda dans le noir.',
        '« Qu’est-ce que tu ne sais pas ? »',
        '« Tout. Les mots. Quand. Comment on se tient. »',
        'Sa3id se tut assez longtemps pour mettre Ayyur mal à l’aise.',
        '« Demain matin », dit-il alors, « tu te mets à côté de moi. Tu fais ce que je fais. Tu n’as rien à dire que tu ne saches pas. »',
        '« Ça suffit ? »',
        '« Pour demain matin, oui », dit Sa3id. « Le reste, tu l’apprendras de quelqu’un qui s’y connaît mieux que moi. Je ne suis qu’un cavalier avec un genou cassé. »',
        'Il se recoucha.',
        '« Dors, maintenant. Demain sera long. »'] },
      { titel: 'La plage au lever du soleil', tekst: [
        'Ils descendirent à l’eau dans le noir, et quand le jour se leva toute la plage était pleine.',
        'Ayyur n’avait jamais vu autant de gens silencieux en même temps.',
        'Ils se tenaient en rangées, épaule contre épaule, des dunes jusqu’à la ligne de marée. Des hommes qui ne se comprenaient pas parce qu’ils venaient de villages distants de dix jours de route, dans la même direction, dans le même ordre.',
        'Il se tenait à côté de Sa3id et faisait ce que Sa3id faisait, et il se sentit ridicule pendant trois battements de cœur, et plus du tout ensuite.',
        'La mer, ce matin-là, était comme un lac.',
        'Quand ce fut fini, le silence dura encore un moment. Puis tout le monde se mit à parler en même temps et cela redevint un camp.',
        'Ayyur amena huit chevaux jusqu’à la ligne de marée. C’était sa tâche : huit, dans le premier chargement, avec Sa3id auprès d’eux une fois de l’autre côté.',
        'Tafukt en faisait partie.',
        'Les chevaux et les bateaux ne vont pas ensemble. Il le savait, et ce matin-là il apprit à quel point. Il fallait faire monter les bêtes sur une planche pour entrer dans le bateau, et la planche bougeait, et le bateau bougeait autrement que la planche.',
        'Deux chevaux refusèrent. Un troisième paniqua à mi-chemin et jeta un homme à terre.',
        'Tafukt monta la planche derrière Ayyur comme si c’était un sentier dans les collines.',
        'Il lui tint la tête une fois à bord, et il lui parla dans sa propre langue de choses qui ne servaient à rien : de son père, du troupeau qui n’existait plus, du nom qu’il lui avait donné et pourquoi.',
        'Quelqu’un lui tapa sur l’épaule.',
        'Il leva les yeux.',
        'Tariq était dans le bateau, entre les chevaux, la main sur le bord.',
        '« Continue à lui parler », dit-il. « Toute la traversée. N’arrête pas. »',
        '« Oui », dit Ayyur.',
        'Tariq regarda la planche, où le quatrième et le cinquième devaient encore passer.',
        '« Et Ayyur », dit-il sans se retourner. « Si ça tourne mal sur l’eau, tu la détaches. Tu ne la retiens pas. Un cheval sait nager. Un garçon avec une corde au bras, non. »'] },
      { titel: 'L’eau', tekst: [
        'Le détroit fait quatorze kilomètres à son plus étroit.',
        'Ayyur l’ignorait. Il savait seulement que la plage derrière lui rapetissait et qu’une heure passa sans qu’il ne se passe rien, puis une autre.',
        'Rien ne tourna mal. C’était ça, l’étrange.',
        'Il s’était imaginé tout le reste : des vagues, des cris, l’eau par-dessus bord. À la place il y eut le soleil, le bruit des rames, et une houle juste assez forte pour faire pencher par-dessus le bastingage tous ceux qui n’avaient pas l’habitude des bateaux.',
        'Il parla à Tafukt jusqu’à en avoir la voix cassée.',
        'Entre deux, il se retournait.',
        'Derrière eux s’étendait la côte où il était né : les collines où les moutons avaient marché, la ville et son mur, l’endroit où son père était sans doute assis à regarder sans rien dire.',
        'Il n’avait pas fait ses adieux. Pas vraiment. Il avait dit qu’il serait de retour dans un mois, et son père avait hoché la tête, et tous les deux avaient fait comme si c’était une phrase qui voulait dire quelque chose.',
        'Devant lui, le rocher grandissait.',
        'Il n’était pas comme il paraissait depuis Tanger. De loin on aurait dit un triangle. De près c’était un mur de pierre qui montait droit hors de l’eau, gris et nu, avec des mouettes qui flottaient autour comme de la poussière.',
        'Il n’y avait personne dessus. Il n’y avait rien dessus. C’était juste un rocher.',
        'À côté de lui, Sa3id dit quelque chose.',
        '« Quoi ? »',
        '« J’ai dit : regarde bien. » Le vieil homme s’appuya des deux bras sur le bord. « Dans cent ans, quelqu’un demandera à ton petit-fils d’où vient sa famille, et il dira le nom de ce truc-là. »',
        '« Il n’a pas de nom. »',
        'Sa3id sourit de ses dents de travers.',
        '« Pas encore », dit-il.',
        'Les bateaux abordèrent sur une plage au pied du rocher. Il n’y avait personne. Pas d’armée, pas de poste de garde, pas de village. Seulement des galets, des algues et le bruit de la mer.',
        'Sept cents hommes et soixante-deux chevaux se tenaient sur une côte étrangère, et les navires firent aussitôt demi-tour pour le chargement suivant.',
        'Deux jours seuls, avait dit Sa3id.',
        'Ayyur mena les chevaux plus haut, vers l’herbe derrière les galets, et commença à tracer une ligne dans le sable pour l’enclos. La chose suivante qui devait être faite.',
        'Derrière lui, Tariq gravissait la première pente pour voir à quoi ressemblait le pays.'] },
      { titel: 'Deux jours seuls', tekst: [
        'La première nuit sur l’autre rive, personne ne dormit.',
        'Ce n’était pas à cause de la peur, même si elle était là aussi. C’était parce que sept cents hommes qui viennent de débarquer se disent tous en même temps qu’ils doivent faire quelque chose, et que personne ne sait quoi.',
        'On monta un enclos et on le déplaça. On fit un feu et on l’éteignit, parce que quelqu’un dit qu’un feu se voit de loin. On posta des gardes à des endroits où il n’y avait rien à garder.',
        'Ayyur fit ce qu’il faisait toujours. Il mena les chevaux à l’herbe, les compta, les recompta, et se coucha près d’eux.',
        'Soixante-deux. Le compte était bon.',
        'Au-dessus de lui, le rocher se dressait comme un mur que quelqu’un aurait laissé à moitié.',
        'Vers le matin il fit froid, comme il fait froid au bord de la mer : pas mordant, mais partout à la fois. Ayyur tira sa couverture sur lui et écouta les chevaux respirer autour de lui, et pensa à son père dans les collines derrière Tanger, à six heures de navigation et à toute une vie de là.',
        'Puis quelqu’un se mit à appeler.',
        'Il se redressa d’un coup, parce qu’un cri veut généralement dire que quelque chose arrive.',
        'Mais rien n’arrivait. C’était un homme monté sur une pierre au bord du camp, le visage tourné vers l’est, et qui appelait comme on appelait aussi au camp près de Tanger, chaque matin, depuis qu’Ayyur y travaillait.',
        'Des hommes se levèrent. Pas tous. Assez pour qu’on le voie.',
        'Ils se placèrent en rangées sur les galets, et ils s’inclinèrent, et ils se relevèrent, et ils s’inclinèrent encore, et par-dessus l’eau on aurait dit que la plage respirait.',
        'Ayyur resta assis près des chevaux.',
        'Il n’en avait pas peur. Simplement, il ne comprenait pas, et personne n’avait pris la peine de le lui expliquer, parce qu’on n’explique rien au garçon qui dort près des chevaux.',
        'Ce qu’il vit, en revanche, c’est ceci : ils étaient plus calmes après. Toute la nuit ils avaient couru dans le camp comme des poules, et après ce quart d’heure-là ils marchaient comme des hommes qui ont une tâche.',
        'Ce fut la première chose qu’il comprit de la nouvelle religion. Pas ce qu’il y avait dedans. Ce qu’elle faisait.',
        'Les navires revinrent cet après-midi-là pour le deuxième chargement, et les deux jours seuls s’avérèrent en avoir été un et demi.'] },
      { titel: 'Le berger et la chèvre', tekst: [
        'Le quatrième jour, quelqu’un vint.',
        'Il venait d’en haut, de la pente, avec un bâton et onze chèvres, et il entra dans le camp comme si celui-ci avait toujours été là.',
        'Trois hommes lui mirent la main dessus en même temps.',
        'Ayyur vit la scène depuis l’enclos et pensa : il est vieux. Ce fut la première chose. Il était vieux, et maigre, et il tenait son bâton comme on tient une chose qu’on tient depuis quarante ans.',
        'On l’amena à la tente. Un homme qui savait le latin vint, et lui parla, et le vieil homme répondit dans quelque chose qui n’était pas du latin.',
        'Puis vint quelqu’un qui parlait berbère, de la même région qu’Ayyur, et qui essaya, et le vieil homme le regarda comme s’il écoutait un oiseau.',
        'Finalement cela se fit avec les mains.',
        'Les chèvres étaient à lui. La pente était à lui, c’est-à-dire : il y marchait avec des chèvres depuis toujours, ce qui revient au même. Il avait vu les navires. Il n’avait prévenu personne, car qui aurait-il prévenu, et de quoi.',
        'Cette dernière question fut posée trois fois et reçut trois fois la même réponse.',
        'On le laissa partir.',
        'Sa3id trouva ça idiot et le dit tout haut. « Il va jusqu’au premier village et après ils le sauront. »',
        '« Ils le savent déjà », dit l’homme au latin. « Il y avait quatre navires dans l’eau. Ça se voit de Tarifa jusqu’à Algésiras. »',
        'Le vieil homme remonta la pente avec ses onze chèvres et ne se retourna pas.',
        'Ayyur le suivit des yeux jusqu’à ce qu’il disparaisse derrière la crête.',
        'Il s’était imaginé l’autre rive autrement. Comme un pays avec un roi, une couronne et des murailles, ou comme rien du tout, de l’eau et puis encore de l’eau. Pas comme un vieil homme avec des chèvres qui tenait le même bâton que les hommes des collines derrière Tanger.',
        '« Tu croyais quoi », dit Sa3id quand il le dit. « Qu’il y aurait des singes ? »',
        'Ayyur ne répondit rien, car à vrai dire il n’avait pas su ce qu’il croyait.',
        'Ce soir-là le vieil homme revint avec deux chèvres au bout d’une corde, les posa devant la tente, et fit un geste que personne ne comprit exactement mais que tout le monde comprit quand même.',
        'On le paya en cuivre. Pas beaucoup de cuivre.',
        'Il le prit, regarda les pièces, les rangea, et remonta la pente.',
        'C’est ainsi que commença la conquête du pays d’en face : avec deux chèvres et un prix honnête.'] },
      { titel: 'Ce que Sa3id croit', tekst: [
        'Sa3id avait les dents de travers, une cicatrice à travers le sourcil et un avis sur tout.',
        'Il venait de Tlemcen, il avait vingt-huit ans, et il était là depuis le début. Il avait trouvé Ayyur le premier jour auprès des chevaux et n’avait plus cessé de revenir, pour des raisons qu’Ayyur ne comprit jamais tout à fait. Peut-être parce que le garçon écoutait. Peut-être parce que personne d’autre n’écoutait.',
        'Le septième soir, Ayyur posa enfin la question.',
        '« Pourquoi est-ce que vous appelez, le matin ? »',
        'Sa3id leva les yeux de sa sangle, qu’il était en train de graisser.',
        '« C’est l’appel », dit-il.',
        '« Ça je sais. Pourquoi ? »',
        'Sa3id y réfléchit, ce qui était inhabituel chez lui.',
        '« Parce que c’est l’heure », dit-il alors. « Cinq fois par jour c’est l’heure. Quand le jour se lève, quand le soleil est au plus haut, quand ton ombre devient plus longue que toi, quand le soleil est parti, et quand il fait noir. »',
        '« Et alors ? »',
        '« Alors tu arrêtes ce que tu fais et tu te tiens debout, immobile. »',
        '« Pour quoi ? »',
        '« Pour Dieu. » Sa3id haussa les épaules. « Il y en a un. Ne m’en demande pas plus, je ne suis pas un savant. Je suis un homme avec un cheval et une lance. »',
        'Ayyur se tut un instant.',
        '« Mon père dit qu’il y a quelque chose qui habite dans la source, chez nous », dit-il. « Il y laisse du lait chaque printemps. »',
        'Il le dit avec la tension de celui qui ne sait pas s’il va se faire rire au nez.',
        'Sa3id ne rit pas.',
        '« Alors c’est ce que dit ton père », dit-il. « Moi je dis ce que je dis. Ton père et moi n’avons ni l’un ni l’autre le temps de tirer ça au clair, alors on fait notre travail. »',
        'Il reprit la sangle.',
        '« Nous aussi on ne l’a que depuis peu », dit-il ensuite. « Mon grand-père n’en savait rien. Mon père a commencé et en savait la moitié. J’en sais un peu plus que lui et moins que l’homme qui appelle le matin. Dans cent ans ils sauront tout et croiront que ça a toujours été comme ça. »',
        'Il tint la sangle contre la lumière.',
        '« C’est comme ça pour tout », dit-il.',
        'Ayyur y repensa longtemps encore, plus longtemps que Sa3id ne l’avait sans doute voulu.',
        'Il n’alla pas se mettre avec eux, ni ce soir-là ni les semaines suivantes. Mais à partir de là il cessa de rester assis près des chevaux comme s’il ne se passait rien. Il se levait quand cela commençait. C’était tout ce qu’il faisait. Il se levait, et il attendait que ce soit fini, et ensuite il reprenait son travail.',
        'Cela lui semblait le minimum pour quelque chose devant quoi sept cents hommes se tiennent debout en silence.'] },
      { titel: 'Tafukt', tekst: [
        'La deuxième semaine, un cheval mourut.',
        'Ce n’était pas Tafukt. C’était un étalon bai sans nom, d’un des derniers chargements, qui avait coincé une jambe dans les galets pendant qu’on le sortait du bateau.',
        'Ils l’avaient entendu. Toute la plage l’avait entendu.',
        'Sa3id le fit au couteau et il le fit vite, et il ne laissa pas Ayyur le faire, même si Ayyur avait proposé de le faire parce que c’était son cheval à soigner.',
        '« Non », avait dit Sa3id. « Tu as douze ans. »',
        '« Treize dans deux mois. »',
        '« Alors tu le feras dans deux mois. »',
        'Ensuite Ayyur resta assis le reste de l’après-midi près de l’enclos sans rien faire, ce qui ne lui arrivait jamais.',
        'Ce n’était pas à cause de l’étalon. Il avait vu mourir des moutons, beaucoup de moutons, et un hiver tellement qu’il avait cessé de compter.',
        'C’était parce qu’il se rendit compte que personne, chez lui, ne le saurait.',
        'Personne chez lui ne savait où il était. Il n’avait pas pu le dire, parce qu’il ne savait pas écrire et que personne n’allait dans cette direction. S’il mourait demain sur une plage de l’autre côté, son père attendrait dans les collines derrière Tanger jusqu’à l’hiver et penserait ensuite qu’il s’était sauvé.',
        'Tafukt poussa son museau contre son épaule.',
        'Il resta assis jusqu’à la nuit et se leva quand vint l’appel, comme il le faisait désormais, et se remit ensuite au travail.',
        'Le lendemain matin il alla trouver le scribe.',
        'Le scribe était un petit homme aux doigts tachés d’encre qui restait assis toute la journée sur une pierre et notait des choses que personne ne lui demandait de noter. Il s’appelait Yunus et il venait de Kairouan.',
        '« Tu peux écrire quelque chose pour moi ? »',
        'Yunus leva les yeux. « Pour qui ? »',
        '« Pour mon père. »',
        '« Ton père sait lire ? »',
        'Ayyur se tut.',
        '« Non », dit-il alors.',
        '« Il connaît quelqu’un qui sait ? »',
        '« L’homme qui vient pour l’impôt passe deux fois par an. Lui, il sait. »',
        'Yunus réfléchit, puis sortit un éclat de tablette de sa caisse et le posa sur son genou.',
        '« Vas-y. »',
        'Ayyur dit : « Ayyur est vivant. Ayyur est aux chevaux. Ayyur revient. »',
        'Yunus l’écrivit, le regarda, et dit : « C’est tout ? »',
        '« Qu’est-ce qu’il faudrait de plus ? »',
        'Le scribe haussa les épaules et posa l’éclat dans la caisse, avec les lettres qui repartiraient par le prochain bateau.',
        'C’était la première fois de sa vie que le nom d’Ayyur était écrit quelque part.',
        'Il y repensa tout le reste de la journée, en parant des sabots et en portant de l’eau, et il se surprit à en être content d’une manière dont il avait presque honte.'] },
      { titel: 'La montagne de Tariq', tekst: [
        'La troisième semaine, le rocher reçut son nom, et Ayyur était là quand cela arriva, même s’il ne le sut pas sur le moment.',
        'Il y avait déjà un camp. Il y avait des enclos, il y avait un puits qu’ils avaient creusé, il y avait des tentes en rangées. Quatre chargements étaient arrivés et il en viendrait d’autres.',
        'Yunus était assis sur sa pierre, une tablette sur les genoux, et il demanda à l’homme à côté de lui comment il devait écrire le lieu.',
        '« Quel lieu ? »',
        '« Celui-ci. Là où nous sommes. Je dois écrire où est l’armée. »',
        'L’homme haussa les épaules.',
        '« À la montagne », dit-il.',
        '« Quelle montagne ? »',
        'Ils levèrent les yeux tous les deux.',
        '« La montagne de Tariq », dit l’homme, et il le dit comme on dit une évidence.',
        'Yunus l’écrivit. Jabal Tariq.',
        'Ayyur se tenait à deux pas de là, un seau à la main, et il entendit, et pensa : bon, et passa son chemin.',
        'C’est ainsi que ça se passe. Il n’y a jamais personne pour se dire : voilà le moment. Le moment ressemble à un scribe qui a besoin d’un mot et à un soldat qui n’en a pas envie.',
        'Treize siècles plus tard, ce nom est encore sur toutes les cartes du monde, usé jusqu’à ce que plus personne ne le reconnaisse, et aucun de ceux qui le prononcent ne sait qu’il y a eu un homme qui s’appelait Tariq.',
        'Ayyur porta le seau aux chevaux.'] },
      { titel: 'L’armée part vers le nord', tekst: [
        'Ils partirent un matin de juillet, et il fallut du premier jour jusqu’à bien après midi pour que la dernière rangée disparaisse.',
        'Ayyur ne partit pas.',
        'On le lui avait dit deux jours plus tôt, par Sa3id, qui l’annonça comme il annonçait tout : sans détour et dans le mauvais ordre.',
        '« Toi, tu restes ici. »',
        '« Pourquoi ? »',
        '« Parce que cent chevaux restent et qu’il faut quelqu’un pour s’en occuper. »',
        '« Il y a d’autres hommes. »',
        '« Il n’y a pas d’autres hommes qui connaissent tous les noms. »',
        'Ayyur ne savait pas si c’était un compliment ou une façon de le tenir loin du combat. Il soupçonnait la seconde, et il en était à la fois fâché et soulagé, et ressentir ces deux choses en même temps est quelque chose pour quoi on n’a pas encore de mot à douze ans.',
        'Sa3id, lui, partit.',
        'Le matin du départ il passa près de l’enclos, son cheval à la main — un hongre gris qu’Ayyur soignait depuis trois mois et qu’il appelait Amellal, ce qui veut dire blanc, ce qui était faux mais que le hongre lui-même n’avait jamais contesté.',
        '« Fais en sorte qu’il boive avant qu’il fasse chaud », dit Ayyur.',
        '« Je sais. »',
        '« Il ne boit pas dans l’eau dormante. Il faut la remuer avec la main. »',
        '« Ça aussi je le sais. »',
        'Ils restèrent là tous les deux comme s’il devait encore venir quelque chose.',
        '« S’il y a un problème », dit Sa3id, « tu vas voir Yunus. Il n’est pas courageux mais il est malin, et ici malin vaut plus. »',
        '« D’accord. »',
        'Sa3id monta en selle, regarda encore une fois vers le bas et dit : « Tu n’es pas un mauvais garçon, Ayyur. Reste loin de l’eau, tu ne sais pas nager. »',
        'Puis il partit au trot.',
        'Ayyur le suivit des yeux jusqu’à mi-chemin de la deuxième colline et puis plus du tout, car à partir de là ce n’était plus qu’un nuage de poussière et ce n’étaient plus des hommes.',
        'Il retourna aux chevaux.',
        'Il y en avait cent quatre. Il les compta deux fois.'] },
      { titel: 'Attendre, c’est quelque chose aussi', tekst: [
        'Les semaines qui suivirent furent les plus longues de sa vie et il ne s’y passa presque rien.',
        'C’est ça, l’étrange, dans la guerre, découvrit Ayyur : pour presque tout le monde, c’est de l’attente. Les histoires parlent du jour où c’est arrivé. Personne ne raconte les quatre semaines d’avant, où l’on cherche de l’herbe pour cent quatre chevaux sur une pente où il n’y a plus d’herbe.',
        'Ces semaines-là, il apprit trois choses.',
        'La première, il l’apprit du vieil homme aux chèvres, qui passait tous les deux ou trois jours, puis tous les jours, et qui finit par passer ses après-midi près de l’enclos sans que personne ne puisse expliquer pourquoi. Il s’appelait quelque chose qu’Ayyur n’a jamais bien su dire. Il montrait des choses et disait le mot, et Ayyur le répétait, et le vieil homme le corrigeait, et cela dura tout l’été.',
        'Eau. Pierre. Chèvre. Montagne. Enfant. Pain.',
        'C’est comme ça qu’on apprend une langue. Pas dans un livre. D’un vieil homme qui n’a rien de mieux à faire.',
        'La deuxième, il l’apprit de Yunus. Il demanda un après-midi, à moitié pour rire, si le scribe pouvait lui apprendre les lettres, et Yunus dit : « Non », et trois jours plus tard il était assis à côté de lui avec un bâton dans le sable.',
        'Cela allait lentement. Ayyur était mauvais. Sa main ne faisait pas ce que sa tête inventait et les lettres sortaient de travers, comme touchées par une bête.',
        'Au bout d’un mois il savait écrire son propre nom.',
        'Ce soir-là il l’écrivit vingt fois dans le sable près de l’enclos et l’effaça vingt fois, et la vingt et unième fois il le laissa jusqu’à ce que le vent l’emporte.',
        'La troisième, il ne l’apprit de personne.',
        'Il découvrit qu’il ne se levait plus à l’appel seulement par politesse.',
        'C’était quelque part en août. Il était près de Tafukt, la nuit tombait, l’homme sur la pierre commença, et Ayyur remarqua qu’il aimait que cela arrive. Pas pour ce qui était dit — il n’en comprenait toujours que peu. Pour le fait qu’une ligne était tracée cinq fois par jour, sur une côte où il ne connaissait personne et où personne ne le connaissait, et que la journée n’était plus une bouillie mais une chose faite de morceaux.',
        'Il n’alla toujours pas se mettre avec eux.',
        'Mais cette semaine-là il demanda quand même à Yunus comment allaient les mots, et Yunus les dit lentement, et Ayyur les répéta, et le scribe le corrigea comme le vieil homme le corrigeait pour eau, pierre, chèvre.',
        'Ce livre s’arrête là, parce que c’est là que ça s’est arrêté.',
        'Ce que c’est devenu dans les années suivantes, nous ne le savons pas. Nous savons seulement que cela a commencé ainsi chez des milliers de garçons comme lui : pas avec une armée, pas avec un combat, mais avec quelqu’un qui voit une chose arriver cinq fois par jour jusqu’à ce qu’elle fasse partie de la journée.'] },
      { titel: 'La nouvelle du fleuve', tekst: [
        'La nouvelle arriva un mardi, avec un cavalier qui avait tant poussé son cheval qu’on ne pouvait plus le sauver.',
        'Ayyur le vit au cheval avant de le voir à l’homme. C’est comme ça quand on est des chevaux.',
        'On s’était battu près d’un fleuve dans le sud du pays, à huit jours de là. Cela avait duré trois jours, ou cinq, selon à qui on le demandait. Le roi à la couronne y était et n’y était plus, et là-dessus les récits divergeaient tellement qu’Ayyur cessa d’écouter.',
        'Ce qui était pareil dans tous les récits : l’armée n’avait pas été battue. Elle continuait vers le nord. Des villes allaient tomber dont personne au camp ne connaissait le nom.',
        'Ce soir-là on cria de joie sur la plage.',
        'Ayyur ne cria pas, car il n’avait toujours pas entendu ce qu’il voulait entendre.',
        'Il le demanda au cavalier, qui était trop fatigué pour être poli.',
        '« Sa3id, de Tlemcen. Cheval gris. Une cicatrice à travers le sourcil. »',
        'L’homme le regarda comme s’il lui demandait un mouton dans un troupeau de dix mille.',
        '« Petit », dit-il. « Je ne suis même pas sûr du nom du roi. »',
        'Trois semaines plus tard vint un deuxième cavalier, et lui non plus ne savait pas.',
        'En octobre revint une charrette avec des blessés et des hommes qui ne voulaient plus, et Ayyur passa les vingt-huit en revue et posa vingt-huit fois la question.',
        'Le vingt-cinquième le connaissait.',
        '« Sa3id », dit-il. « Oui. Près du fleuve. »',
        'Ayyur attendit.',
        '« Il était vivant quand je l’ai vu », dit l’homme. « Après je suis tombé et je n’ai plus rien vu. »',
        'Ce fut tout. C’est tout ce qu’Ayyur a jamais su, et c’est aussi tout ce que nous savons, car des sept mille hommes qui traversèrent le détroit cette année-là, quatre sont connus par leur nom et le reste est poussière.',
        'Ayyur retourna à l’enclos.',
        'Amellal n’y était pas. Il n’y était plus depuis trois mois, et pourtant il regardait à chaque fois.',
        'Il alla chercher de l’eau, la remua avec la main comme on le fait pour un cheval qui ne boit pas dans l’eau dormante, et la donna à une autre bête.'] },
      { titel: 'La caisse', tekst: [
        'Fin octobre, Yunus traversa le camp avec une caisse sous le bras, à la recherche de quelqu’un qui savait monter à cheval et connaissait la route le long de la côte.',
        'Il n’y avait plus personne d’autre. C’était la réponse honnête à la question de savoir pourquoi il aboutit chez Ayyur.',
        'La caisse devait aller vers le nord, vers un endroit où l’armée avait installé un camp d’hiver. Il y avait dedans des tablettes, et des lettres, et un sac de cuir avec de petites choses que des soldats avaient déposées parce qu’ils ne voulaient pas les perdre — et qu’ils n’étaient pas venus rechercher, ce qui dit de ces soldats tout ce qu’on ne veut pas savoir.',
        '« Combien de temps ? » demanda Ayyur.',
        '« Six jours. Huit s’il pleut. »',
        '« Et après ? »',
        'Yunus le regarda.',
        '« Après tu es là-bas », dit-il. « Et là-bas, il y a plus qu’ici. »',
        'Ayyur chargea la caisse sur Tafukt.',
        'En sanglant, le sac bascula et quelque chose roula par terre.',
        'C’était en bronze, long comme sa main, avec une tête à huit branches. Comme une étoile.',
        '« Qu’est-ce que c’est ? » demanda-t-il.',
        'Yunus y jeta à peine un regard.',
        '« Une clé », dit-il. « Elle était déjà dans le sac quand je l’ai reçu. Personne ne sait à qui. »',
        'Ayyur la garda un instant dans la main. Elle était tiède de soleil.',
        'Il pensa à une porte quelque part, de l’autre côté de l’eau, que quelqu’un avait tirée derrière lui pour la dernière fois sans savoir que c’était la dernière. À une maison qui était peut-être encore debout. À un homme embarqué avec une clé dans sa poche parce qu’on ne laisse pas ça derrière soi, et qui l’avait déposée parce qu’on ne l’emmène pas non plus de l’autre côté du fleuve.',
        'Il la laissa reglisser dans le sac.',
        'Puis il la ressortit, et la passa à sa propre ceinture.',
        'Yunus le vit et ne dit rien.',
        '« Personne ne viendra la chercher », dit Ayyur.',
        '« Non », dit Yunus. « Personne ne viendra la chercher. »',
        'Ayyur serra la sangle et monta en selle.'] },
      { titel: 'Vers le nord', tekst: [
        'Il partit cet après-midi-là le long de la côte, avec une caisse, une jument et une clé qui n’était à personne.',
        'Au dernier virage avant la pente il retint son cheval et se retourna.',
        'Le camp était en dessous de lui comme s’il avait toujours été là : des enclos, des tentes en rangées, le puits, la fumée de deux feux. Sept mois plus tôt c’étaient des galets et des algues.',
        'Le vieil homme aux chèvres se tenait au bord de sa pente, comme il s’y tenait chaque après-midi.',
        'Ayyur leva la main.',
        'Le vieil homme leva son bâton.',
        'Ce fut tout.',
        'Il continua, et le pays dans lequel il entrait était vert d’une façon qu’il ne connaissait pas, avec d’autres arbres et trop d’eau, et avec des villages où les gens se tenaient au bord de la route à regarder un garçon sur une jument avec une caisse.',
        'Il les salua avec les mots qu’il avait appris du vieil homme. Eau. Pierre. Pain.',
        'Certains rirent. Une femme lui donna du pain.',
        'Il aurait dû l’écrire plus tard, car c’est le genre de chose qui disparaît : que les premières semaines de la conquête de ce pays, pour un garçon de douze ans, ce furent des arbres étranges, trop d’eau et une femme qui lui donna du pain.',
        'Il n’est jamais retourné dans les collines derrière Tanger.',
        'Ce ne fut pas une décision. Ça ne l’est chez presque personne. L’hiver vint, et il y avait du travail, et il y avait des chevaux, et puis une année passa et puis une autre, et à un moment ce n’est plus un voyage qu’on repousse mais une vie qu’on a.',
        'L’éclat avec son nom est-il arrivé chez son père ? Nous ne le savons pas. Nous l’espérons.',
        'Ce que nous savons, c’est que dans les siècles qui ont suivi, des millions de gens ont traversé ce détroit, dans un sens et dans l’autre, et qu’à chaque fois quelqu’un restait derrière à attendre.',
        'La clé partit vers le nord, à la ceinture d’un garçon à qui personne ne l’avait donnée.',
        'Où elle est allée ensuite, c’est dans le tome suivant.'] },
    ],
  },
}
