import type { Hoofdstuk } from './sleutels'

/**
 * Deel 2 — De overkant. Tanger en de zeestraat, 711.
 *
 * Hier komt het nieuwe geloof de reeks binnen, en het komt binnen zoals het
 * werkelijk kwam: met soldaten, met kooplieden, met mensen die het pas net
 * zelf hadden. Ayyur ziet het van dichtbij en snapt de helft — wat precies
 * klopt, want zo zag het er voor de meeste Amazigh in die jaren uit.
 */
export const DEEL2_HOOFDSTUKKEN: Hoofdstuk[] = [
  {
    nummer: 1,
    titel: 'De jongen bij de paarden',
    tekst: [
      'Ayyur was twaalf en hij was goed in twee dingen: paarden en wachten.',
      'Het tweede had hij van zijn vader geleerd, die schapen hoedde in de heuvels achter Tanger en die kon zwijgen van zonsopgang tot zonsondergang zonder dat het hem iets deed. Het eerste had hij van niemand. Paarden vonden hem gewoon aardig, en dat was al zo sinds hij kon lopen.',
      'Daarom stond hij nu in het kamp buiten de stadsmuur en niet in de heuvels.',
      'Zijn vader had in de winter dertig schapen verloren aan de kou en de rest aan de schuld. Er was geen kudde meer om te hoeden. Er was wel een leger, en een leger heeft paarden, en paarden hebben iemand nodig die er ’s nachts bij blijft.',
      'Ze betaalden in eten en in koper. Niet veel koper.',
      'Ayyur klaagde er niet over. Hij mocht bij de paarden slapen en hij kende inmiddels alle zevenenveertig bij naam, ook de namen die hij zelf verzonnen had omdat niemand hem ze had verteld.',
      'Het kamp was in die weken van maart voller geworden dan hij ooit had gezien. Eerst honderd man, toen vijfhonderd, toen zoveel dat tellen niet meer ging. Ze kwamen uit het zuiden en uit het oosten, uit de bergen en van de kust. De meesten waren Amazigh zoals hij. Ze spraken zijn taal, met andere woorden voor dezelfde dingen, en ze lachten om hoe hij het zei.',
      'Er waren er ook die Arabisch spraken. Niet veel. Een paar honderd.',
      'En iedereen wachtte.',
      'Waarop wisten ze wel: op schepen. Waarvoor de schepen waren, daar werd over gepraat op de manier waarop mannen over iets praten dat ze niet zeker weten — heel stellig, en elke dag anders.',
      '“De overkant,” zei de een.',
      '“Er is niets aan de overkant,” zei de ander. “Water en dan nog meer water.”',
      '“Er is een koning aan de overkant,” zei een derde. “Met een kroon van goud zo zwaar dat hij hem niet kan dragen.”',
      'Ayyur borstelde de flank van een merrie die hij Tafukt noemde, wat zon betekent, en luisterde naar alle drie.',
      'Hij had de overkant gezien. Iedereen in Tanger had de overkant gezien. Op een heldere dag lag er een streep land aan de horizon, met daarboven een rots die eruitzag alsof iemand hem daar had neergezet.',
      'Je kon er kijken zonder er ooit over na te denken, je hele leven lang.',
      'Tot iemand schepen begon te verzamelen.',
    ],
  },
  {
    nummer: 2,
    titel: 'De man die niet groot was',
    tekst: [
      'Hij zag Tariq voor het eerst op een dinsdag, bij de paarden, en hij wist een halve minuut lang niet wie hij voor zich had.',
      'De man was niet groot. Dat was het eerste.',
      'Ayyur had zich iemand voorgesteld als de verhalen: een kop boven iedereen uit, een mantel die achter hem aan sleepte, tien man eromheen. Deze man stond alleen, in een stoffige jas zonder versiering, en hij stond naar Tafukt te kijken zoals iemand naar een paard kijkt die verstand van paarden heeft.',
      '“Wie rijdt op deze?” vroeg hij.',
      '“Niemand,” zei Ayyur. “Ze laat niemand op zich zitten.”',
      '“Waarom niet?”',
      '“Weet ik niet. Ze is een keer gevallen, denk ik. Voordat ze hier kwam.”',
      'De man legde zijn hand op de hals van de merrie en liet hem daar liggen zonder te aaien.',
      '“En bij jou?”',
      '“Bij mij is ze rustig.”',
      '“Dan is ze niet bang voor mensen,” zei de man. “Dan is ze bang voor wat mensen met haar deden.”',
      'Hij keek Ayyur aan voor het eerst.',
      '“Hoe heet je?”',
      '“Ayyur.”',
      '“De maan.” De man knikte, alsof dat een redelijke naam was. “Zorg dat ze er over twee weken nog zo bij staat.”',
      'Toen liep hij weg.',
      'Het duurde tot de avond voordat iemand het Ayyur vertelde, en toen hij het hoorde ging hij op een kist zitten en bleef daar een tijdje zitten.',
      'Tariq ibn Ziyad. Amazigh, zoals hij. Uit een familie die niemand kende. Gouverneur van Tanger, en de man die het leger dat hier op het strand lag over het water moest zetten.',
      'Hij had naar een paard staan kijken.',
      '“Hij komt elke dag,” zei Sa3id, de oude ruiter met het slechte been, die inmiddels naast hem was komen zitten omdat hij altijd naast iemand kwam zitten. “Elke dag bij de paarden en elke dag bij de schepen. Hij slaapt niet, geloof ik.”',
      '“Hij is niet groot,” zei Ayyur.',
      'Sa3id lachte zo hard dat hij moest hoesten.',
      '“Nee, jongen,” zei hij. “Dat is hij niet.”',
    ],
  },
  {
    nummer: 3,
    titel: 'Vier schepen voor zevenduizend man',
    tekst: [
      'Het probleem was eenvoudig en niemand kon het oplossen.',
      'Er lagen zevenduizend man op dat strand, plus paarden, plus wapens, plus eten voor weken. En er waren vier schepen.',
      'Ayyur hoorde Sa3id een keer uitrekenen hoeveel keer die vier schepen dan heen en weer moesten, en Sa3id kwam op een getal waar hij zelf om moest lachen, en daarna werd hij stil.',
      '“Wat is er?” vroeg Ayyur.',
      '“Niets.”',
      '“Sa3id.”',
      'De oude man wreef over zijn knie, wat hij deed als hij nadacht.',
      '“Als je vier schepen hebt,” zei hij, “dan is de eerste lading het gevaarlijkst. Die staat aan de overkant, alleen, met niemand achter zich. En als er iets misgaat, zijn de schepen twee dagen weg.”',
      'Hij keek naar de zee.',
      '“Ik zou niet in de eerste lading willen zitten.”',
      'De schepen waren niet van hen. Dat wist het hele kamp. Ze kwamen van een man aan de overkant, een heer van Ceuta die ruzie had met zijn eigen koning en die daarom hielp. Zijn naam werd op tien manieren uitgesproken en niemand had hem ooit gezien.',
      '“Waarom helpt hij?” vroeg Ayyur.',
      '“Omdat hij iets wil.”',
      '“Wat dan?”',
      '“Dat weten we pas als we het hebben gegeven,” zei Sa3id.',
      'In die weken leerde Ayyur meer over oorlog dan hij ooit had willen weten, en bijna niets ervan ging over vechten. Het ging over water in vaten dat na vier dagen bedierf. Over hoeveel gerst een paard per dag eet en hoeveel dat is voor zevenhonderd paarden. Over mannen die ziek werden van het wachten en ruzie kregen over niets.',
      'Op een ochtend was er een vechtpartij bij de put. Twee mannen uit verschillende stammen, om een emmer.',
      'Tariq kwam zelf. Hij liet ze allebei opstaan, hij sprak zacht met ze, en hij stuurde ze samen weg met dezelfde opdracht: één emmer, twee man, de hele dag water dragen voor de paarden.',
      '’s Avonds zaten ze naast elkaar te eten.',
      'Sa3id zag Ayyur kijken.',
      '“Dát is het,” zei hij. “Dát is waarom ze met hem meegaan. Niet omdat hij kan vechten. Ze kunnen allemaal vechten.”',
    ],
  },
  {
    nummer: 4,
    titel: 'De nacht ervoor',
    tekst: [
      'De avond voor de eerste overtocht was warm en er stond geen wind, en dat laatste was precies het probleem.',
      'Ayyur kon niet slapen. Hij lag tussen de paarden, met zijn hoofd op een zadel dat naar leer en zweet rook, en hij keek naar de sterren die tussen de tentdoeken door te zien waren.',
      'Naast hem lag Sa3id, en die sliep ook niet.',
      '“Ben je bang?” vroeg Ayyur.',
      '“Ja,” zei Sa3id meteen.',
      'Dat had Ayyur niet verwacht. Hij had verwacht dat de oude man zou lachen en iets zou zeggen over dat hij al in twintig veldslagen had gestaan.',
      '“Iedereen die zegt van niet, liegt,” zei Sa3id. “Of hij is dom. Aan domme mannen heb je niets in een boot.”',
      'Hij ging rechtop zitten, langzaam, met zijn hand op zijn knie.',
      '“Weet je wat ik doe als ik bang ben?”',
      '“Nee.”',
      '“Ik zeg de naam van God en dan doe ik het volgende ding dat gedaan moet worden. Niet het hele ding. Het volgende ding.”',
      'Ayyur dacht daarover na.',
      'Het geloof was in zijn dorp iets van de laatste jaren. Zijn grootmoeder had het niet, zijn moeder half, zijn vader helemaal — op zijn eigen manier, stil, zonder er veel over te zeggen. In het kamp was het overal: mannen die stopten met waar ze mee bezig waren en zich in dezelfde richting draaiden, en daarna weer verder gingen alsof er niets gebeurd was.',
      'Hij had het nooit zo goed begrepen. Niemand had het hem uitgelegd. Ze deden het gewoon, en hij stond erbij met een borstel in zijn hand.',
      '“Sa3id,” zei hij. “Ik weet niet hoe het moet.”',
      'De oude man keek hem aan in het donker.',
      '“Wat weet je niet?”',
      '“Alles. De woorden. Wanneer. Hoe je staat.”',
      'Sa3id zweeg lang genoeg om Ayyur ongemakkelijk te maken.',
      '“Morgenochtend,” zei hij toen, “ga je naast mij staan. Je doet wat ik doe. Je hoeft niets te zeggen wat je niet weet.”',
      '“Is dat genoeg?”',
      '“Voor vanochtend wel,” zei Sa3id. “De rest leer je van iemand die er meer verstand van heeft dan ik. Ik ben maar een ruiter met een kapotte knie.”',
      'Hij ging weer liggen.',
      '“Slaap nu. Morgen wordt lang.”',
    ],
  },
  {
    nummer: 5,
    titel: 'Het strand bij zonsopgang',
    tekst: [
      'Ze gingen in het donker naar het water, en toen het licht werd stond het hele strand vol.',
      'Ayyur had nog nooit zoveel mensen tegelijk stil gezien.',
      'Ze stonden in rijen, schouder aan schouder, van de duinen tot aan de vloedlijn. Mannen die elkaar niet verstonden omdat ze uit dorpen kwamen die tien dagreizen uit elkaar lagen, in dezelfde richting, in dezelfde volgorde.',
      'Hij stond naast Sa3id en deed wat Sa3id deed, en hij voelde zich de eerste drie tellen belachelijk en daarna niet meer.',
      'De zee lag er die ochtend bij als een meer.',
      'Toen het afgelopen was, bleef het nog even stil. Daarna begon iedereen tegelijk te praten en werd het weer een kamp.',
      'Ayyur bracht acht paarden naar de vloedlijn. Dat was zijn opdracht: acht, in de eerste lading, met Sa3id erbij als ze aan de overkant waren.',
      'Tafukt was er een van.',
      'Paarden en boten gaan niet samen. Dat wist hij, en die ochtend leerde hij hoe erg het is. Ze moesten de dieren over een plank de boot in krijgen, en de plank bewoog, en de boot bewoog anders dan de plank.',
      'Twee paarden weigerden. Een derde raakte in paniek halverwege en sloeg een man tegen de grond.',
      'Tafukt liep achter Ayyur aan de plank op alsof het een pad in de heuvels was.',
      'Hij hield haar hoofd vast toen ze eenmaal binnen was, en hij praatte tegen haar in zijn eigen taal over dingen die nergens over gingen: over zijn vader, over de kudde die er niet meer was, over de naam die hij haar gegeven had en waarom.',
      'Iemand sloeg hem op zijn schouder.',
      'Hij keek op.',
      'Tariq stond in de boot, tussen de paarden, met zijn hand op de rand.',
      '“Blijf bij haar praten,” zei hij. “De hele overtocht. Hou niet op.”',
      '“Ja,” zei Ayyur.',
      'Tariq keek naar de plank, waar de vierde en vijfde nog moesten.',
      '“En Ayyur,” zei hij, zonder om te kijken. “Als het misgaat op het water, snij je haar los. Niet vasthouden. Een paard kan zwemmen. Een jongen met een touw om zijn arm niet.”',
    ],
  },
  {
    nummer: 6,
    titel: 'Water',
    tekst: [
      'De zeestraat is op zijn smalst veertien kilometer.',
      'Ayyur wist dat niet. Hij wist alleen dat het strand achter hem kleiner werd en dat er een uur voorbijging waarin er niets gebeurde, en daarna nog een uur.',
      'Het ging niet mis. Dat was het vreemde.',
      'Hij had zich alles voorgesteld: golven, schreeuwen, water over de rand. In plaats daarvan was er de zon, het geluid van riemen, en een deining die precies genoeg was om iedereen die niet gewend was aan boten over de reling te laten hangen.',
      'Hij praatte tegen Tafukt tot zijn stem hees werd.',
      'Tussendoor keek hij om.',
      'Achter hen lag de kust waar hij geboren was: de heuvels waar de schapen hadden gelopen, de stad met de muur, het punt waar zijn vader nu waarschijnlijk zat te kijken zonder iets te zeggen.',
      'Hij had geen afscheid genomen. Niet echt. Hij had gezegd dat hij over een maand terug zou zijn, en zijn vader had geknikt, en ze hadden allebei gedaan alsof dat een zin was die iets betekende.',
      'Voor hem uit werd de rots groter.',
      'Die was anders dan hij eruitzag vanaf Tanger. Van veraf leek het een driehoek. Van dichtbij was het een muur van steen die recht uit het water omhoogkwam, grijs en kaal, met meeuwen die eromheen dreven als stof.',
      'Er zat niemand op. Er stond niets op. Het was gewoon een rots.',
      'Naast hem zei Sa3id iets.',
      '“Wat?”',
      '“Ik zei: kijk goed.” De oude man leunde met zijn armen op de rand. “Over honderd jaar vraagt iemand je kleinzoon waar zijn familie vandaan komt, en dan zegt hij de naam van dit ding.”',
      '“Het heeft geen naam.”',
      'Sa3id grijnsde met zijn scheve gebit.',
      '“Nog niet,” zei hij.',
      'De boten kwamen aan land op een strand aan de voet van de rots. Er was niemand. Geen leger, geen wachtpost, geen dorp. Alleen kiezels, wier en het geluid van de zee.',
      'Zevenhonderd man en tweeënzestig paarden stonden op een vreemde kust, en de schepen keerden meteen om voor de volgende lading.',
      'Twee dagen alleen, had Sa3id gezegd.',
      'Ayyur bracht de paarden hogerop, naar het gras achter de kiezels, en begon een lijn te trekken in het zand voor de omheining. Het volgende ding dat gedaan moest worden.',
      'Achter hem klom Tariq de eerste helling op om te kijken hoe het land eruitzag.',
    ],
  },
  {
    nummer: 7,
    titel: 'Twee dagen alleen',
    tekst: [
      'De eerste nacht op de overkant sliep niemand.',
      'Dat kwam niet door de angst, al was die er ook. Het kwam doordat zevenhonderd mannen die net van boord zijn gestapt allemaal tegelijk bedenken dat ze iets moeten doen, en dat er niemand is die weet wat.',
      'Er werd een omheining gezet en weer verzet. Er werd een vuur gemaakt en weer gedoofd, omdat iemand zei dat je van ver een vuur ziet. Er werden wachten uitgezet op plekken waar niets te bewaken viel.',
      'Ayyur deed wat hij altijd deed. Hij bracht de paarden naar het gras, telde ze, telde ze nog eens, en ging bij ze liggen.',
      'Tweeënzestig. Het klopte.',
      'Boven hem stond de rots als een muur die iemand halverwege had laten staan.',
      'Tegen de ochtend werd het koud, zoals het aan zee koud wordt: niet fel, maar overal tegelijk. Ayyur trok zijn deken over zich heen en luisterde naar de paarden die om hem heen ademden, en dacht aan zijn vader in de heuvels achter Tanger, zes uur varen en een heel leven verderop.',
      'Toen begon iemand te roepen.',
      'Hij schoot overeind, want roepen betekent meestal dat er iets aankomt.',
      'Maar er kwam niets aan. Het was een man die op een steen was gaan staan aan de rand van het kamp, met zijn gezicht naar het oosten, en die riep zoals ze in het kamp bij Tanger ook hadden geroepen, elke ochtend, sinds Ayyur er werkte.',
      'Mannen stonden op. Niet allemaal. Genoeg om het te zien.',
      'Ze zetten zich in rijen op de kiezels, en ze bogen, en ze stonden weer op, en ze bogen weer, en het klonk over het water alsof het strand ademde.',
      'Ayyur bleef bij de paarden zitten.',
      'Hij was er niet bang voor. Hij begreep het alleen niet, en niemand had de moeite genomen het hem uit te leggen, want niemand legt iets uit aan de jongen die bij de paarden slaapt.',
      'Wat hij wel zag was dit: ze waren rustiger daarna. De hele nacht hadden ze als kippen door het kamp gelopen, en na dat ene kwartier liepen ze als mannen met een taak.',
      'Dat was het eerste wat hij van het nieuwe geloof begreep. Niet wat erin stond. Wat het deed.',
      'De schepen kwamen die middag terug voor de tweede lading, en de twee dagen alleen bleken er anderhalf te zijn geweest.',
    ],
  },
  {
    nummer: 8,
    titel: 'De herder en de geit',
    tekst: [
      'Op de vierde dag kwam er iemand.',
      'Hij kwam van boven, van de helling, met een stok en met elf geiten, en hij liep het kamp binnen alsof het er altijd al had gestaan.',
      'Drie mannen hadden hem tegelijk te pakken.',
      'Ayyur zag het vanaf de omheining en dacht: hij is oud. Dat was het eerste. Hij was oud, en mager, en hij hield zijn stok vast zoals je iets vasthoudt wat je al veertig jaar vasthoudt.',
      'Ze brachten hem bij de tent. Er kwam een man bij die Latijn kende, en die praatte tegen hem, en de oude man antwoordde in iets wat geen Latijn was.',
      'Toen kwam er iemand die Berbers sprak, uit dezelfde streek als Ayyur, en die probeerde het, en de oude man keek hem aan alsof hij naar een vogel luisterde.',
      'Uiteindelijk ging het met handen.',
      'De geiten waren van hem. De helling was van hem, dat wil zeggen: hij liep er al zijn hele leven met geiten, wat op hetzelfde neerkomt. Hij had de schepen gezien. Hij had niemand gewaarschuwd, want wie zou hij waarschuwen, en waarvoor.',
      'Dat laatste werd drie keer gevraagd en drie keer hetzelfde beantwoord.',
      'Ze lieten hem gaan.',
      'Sa3id vond dat dom en zei het hardop. “Hij loopt naar het eerste dorp en dan weten ze het.”',
      '“Ze weten het al,” zei de man met het Latijn. “Er lagen vier schepen in het water. Dat ziet iedereen van Tarifa tot Algeciras.”',
      'De oude man liep de helling weer op met zijn elf geiten en keek niet om.',
      'Ayyur keek hem na tot hij achter de rand verdween.',
      'Hij had zich de overkant voorgesteld als iets anders. Als een land met een koning en een kroon en muren, of als niets, als water en dan nog meer water. Niet als een oude man met geiten die dezelfde stok vasthield als de mannen in de heuvels achter Tanger.',
      '“Wat dacht je dan,” zei Sa3id toen hij het zei. “Dat het hier aapjes waren?”',
      'Ayyur zei niets, want hij had eerlijk gezegd niet geweten wat hij dacht.',
      'Die avond kwam de oude man terug met twee geiten aan een touw en zette ze neer bij de tent, en gebaarde iets wat niemand precies begreep maar iedereen wel begreep.',
      'Ze betaalden hem in koper. Niet veel koper.',
      'Hij nam het aan, bekeek de munten, stak ze weg, en liep de helling weer op.',
      'Zo begon de verovering van het land aan de overkant: met twee geiten en een eerlijke prijs.',
    ],
  },
  {
    nummer: 9,
    titel: 'Wat Sa3id gelooft',
    tekst: [
      'Sa3id had een scheef gebit, een litteken door zijn wenkbrauw en een mening over alles.',
      'Hij was uit Tlemcen, hij was achtentwintig, en hij was er sinds het begin bij. Hij had Ayyur op de eerste dag bij de paarden gevonden en was daarna blijven komen, om redenen die Ayyur nooit helemaal begreep. Misschien omdat de jongen luisterde. Misschien omdat er verder niemand luisterde.',
      'Op de zevende avond vroeg Ayyur het eindelijk.',
      '“Waarom roepen jullie ’s ochtends?”',
      'Sa3id keek op van zijn riem, die hij aan het invetten was.',
      '“Dat is de oproep,” zei hij.',
      '“Dat weet ik. Waarom?”',
      'Sa3id dacht erover na, wat voor hem ongewoon was.',
      '“Omdat het tijd is,” zei hij toen. “Vijf keer op een dag is het tijd. Als het licht wordt, als de zon op zijn hoogst staat, als je schaduw langer wordt dan jij, als de zon weg is, en als het donker is.”',
      '“En dan?”',
      '“Dan stop je met wat je doet en sta je stil.”',
      '“Waarvoor?”',
      '“Voor God.” Sa3id haalde zijn schouders op. “Er is er één. Meer moet je van mij niet vragen, want ik ben geen geleerde. Ik ben een man met een paard en een speer.”',
      'Ayyur zweeg even.',
      '“Mijn vader zegt dat er in de bron bij ons dorp iets woont,” zei hij. “Hij laat er elk voorjaar melk staan.”',
      'Hij zei het met de spanning van iemand die niet weet of hij uitgelachen gaat worden.',
      'Sa3id lachte niet.',
      '“Dan zegt jouw vader dat,” zei hij. “Ik zeg wat ik zeg. Je vader en ik hebben allebei geen tijd om het uit te zoeken, dus we doen ons werk.”',
      'Hij ging verder met de riem.',
      '“Wij hebben het ook pas net,” zei hij daarna. “Mijn grootvader wist er niets van. Mijn vader is ermee begonnen en wist er de helft van. Ik weet er iets meer van dan hij en minder dan de man die ’s ochtends roept. Over honderd jaar weten ze er alles van en denken ze dat het altijd zo geweest is.”',
      'Hij hield de riem tegen het licht.',
      '“Zo gaat dat met alles,” zei hij.',
      'Ayyur bleef daar nog lang over nadenken, langer dan Sa3id vermoedelijk bedoeld had.',
      'Hij was er niet bij gaan staan, niet die avond en niet de weken daarna. Maar hij hield vanaf toen wel op met bij de paarden blijven zitten alsof er niets gebeurde. Hij stond op als het begon. Dat was alles wat hij deed. Hij stond op, en hij wachtte tot het klaar was, en dan ging hij verder.',
      'Het leek hem het minste wat je kon doen voor iets waar zevenhonderd man stil voor gaan staan.',
    ],
  },
  {
    nummer: 10,
    titel: 'Tafukt',
    tekst: [
      'In de tweede week ging er een paard dood.',
      'Het was niet Tafukt. Het was een bruine hengst zonder naam, een van de laatste lading, die met een been in de kiezels was blijven steken toen ze hem van de boot haalden.',
      'Ze hadden het gehoord. Iedereen op het strand had het gehoord.',
      'Sa3id deed het met een mes en hij deed het snel, en hij liet het Ayyur niet doen, ook al had Ayyur aangeboden het te doen omdat het zijn paard was om voor te zorgen.',
      '“Nee,” had Sa3id gezegd. “Jij bent twaalf.”',
      '“Dertien over twee maanden.”',
      '“Dan doe je het over twee maanden.”',
      'Daarna zat Ayyur de rest van de middag bij de omheining zonder iets te doen, wat hem nooit overkwam.',
      'Het was niet om de hengst. Hij had schapen zien doodgaan, veel schapen, en één winter zoveel dat hij was opgehouden met tellen.',
      'Het was omdat hij zich realiseerde dat niemand thuis het zou weten.',
      'Niemand thuis wist waar hij was. Hij had het niet kunnen zeggen, want hij kon niet schrijven en er ging niemand die kant op. Als hij morgen doodging op een strand aan de overkant, zou zijn vader in de heuvels achter Tanger tot in de winter wachten en daarna denken dat hij was weggelopen.',
      'Tafukt duwde haar neus tegen zijn schouder.',
      'Hij bleef zitten tot het donker werd en stond op toen de oproep kwam, zoals hij nu deed, en ging daarna aan het werk.',
      'De volgende ochtend zocht hij de schrijver op.',
      'De schrijver was een kleine man met inktvingers die de hele dag op een steen zat en dingen opschreef die niemand hem vroeg op te schrijven. Hij heette Yunus en hij kwam uit Kairouan.',
      '“Kun je iets voor me opschrijven?”',
      'Yunus keek op. “Voor wie?”',
      '“Mijn vader.”',
      '“Kan je vader lezen?”',
      'Ayyur zweeg.',
      '“Nee,” zei hij toen.',
      '“Kent hij iemand die het kan?”',
      '“De man die de belasting int komt twee keer per jaar. Die kan het.”',
      'Yunus dacht na, haalde toen een scherf tablet uit zijn kist en zette hem op zijn knie.',
      '“Zeg het maar.”',
      'Ayyur zei: “Ayyur leeft. Ayyur is bij de paarden. Ayyur komt terug.”',
      'Yunus schreef het op, keek ernaar, en zei: “Is dat alles?”',
      '“Wat moet er nog meer staan?”',
      'De schrijver haalde zijn schouders op en legde de scherf in de kist bij de brieven die met de volgende boot mee terug zouden gaan.',
      'Het was de eerste keer in zijn leven dat Ayyurs naam ergens stond.',
      'Hij dacht daar de rest van de dag aan terug, terwijl hij hoeven uitsneed en water haalde, en hij betrapte zichzelf erop dat hij het fijn vond op een manier waar hij zich bijna voor schaamde.',
    ],
  },
  {
    nummer: 11,
    titel: 'De berg van Tariq',
    tekst: [
      'In de derde week kreeg de rots zijn naam, en Ayyur was erbij toen het gebeurde, al wist hij dat op dat moment niet.',
      'Er was toen al een kamp. Er waren omheiningen, er was een put die ze hadden uitgegraven, er stonden tenten in rijen. Er waren vier ladingen aangekomen en er zouden er nog meer komen.',
      'Yunus zat op zijn steen met een tablet op zijn knieën, en hij vroeg aan de man naast hem hoe hij de plaats moest opschrijven.',
      '“Welke plaats?”',
      '“Deze. Waar we zijn. Ik moet opschrijven waar het leger is.”',
      'De man haalde zijn schouders op.',
      '“Bij de berg,” zei hij.',
      '“Welke berg?”',
      'Ze keken allebei omhoog.',
      '“De berg van Tariq,” zei de man, en hij zei het zoals je iets zegt wat voor de hand ligt.',
      'Yunus schreef het op. Jabal Tariq.',
      'Ayyur stond twee passen verderop met een emmer in zijn hand en hoorde het, en dacht: goed, en liep door.',
      'Zo gaan die dingen. Er is nooit iemand bij die denkt: dit is het moment. Het moment ziet eruit als een schrijver die een woord nodig heeft en een soldaat die er geen zin in heeft.',
      'Dertienhonderd jaar later staat die naam nog op elke kaart ter wereld, versleten tot iets wat geen mens meer herkent, en niemand die hem uitspreekt weet dat er een man was die Tariq heette.',
      'Ayyur bracht de emmer naar de paarden.',
    ],
  },
  {
    nummer: 12,
    titel: 'Het leger gaat naar het noorden',
    tekst: [
      'Ze vertrokken op een ochtend in juli, en het duurde van het eerste licht tot ver na het middaguur voor de laatste rij uit het zicht was.',
      'Ayyur ging niet mee.',
      'Dat was hem twee dagen eerder verteld, door Sa3id, die het bracht zoals hij alles bracht: zonder omhaal en met de verkeerde volgorde.',
      '“Jij blijft hier.”',
      '“Waarom?”',
      '“Omdat er honderd paarden achterblijven en iemand voor ze moet zorgen.”',
      '“Er zijn andere mannen.”',
      '“Er zijn geen andere mannen die alle namen kennen.”',
      'Ayyur wist niet of dat een compliment was of een manier om hem uit de strijd te houden. Hij vermoedde het tweede, en hij was er tegelijk boos en opgelucht over, en die twee dingen naast elkaar voelen is iets waar je op je twaalfde nog geen woord voor hebt.',
      'Sa3id ging wel.',
      'Op de ochtend van het vertrek kwam hij langs de omheining met zijn paard aan de hand — een grauwe ruin die Ayyur al drie maanden verzorgde en die hij Amellal noemde, wat wit betekent, wat niet klopte maar wat de ruin zelf nooit had tegengesproken.',
      '“Zorg dat hij drinkt voor het heet wordt,” zei Ayyur.',
      '“Dat weet ik.”',
      '“Hij drinkt niet uit stilstaand water. Je moet het bewegen met je hand.”',
      '“Dat weet ik ook.”',
      'Ze stonden er allebei bij alsof er nog iets moest komen.',
      '“Als er iets is,” zei Sa3id, “ga je naar Yunus. Die is niet dapper maar die is slim, en slim is hier meer waard.”',
      '“Goed.”',
      'Sa3id klom op, keek nog één keer naar beneden en zei: “Je bent geen slechte jongen, Ayyur. Blijf van het water af, je kunt niet zwemmen.”',
      'Toen reed hij weg.',
      'Ayyur zag hem tot ergens halverwege de tweede heuvel en daarna niet meer, want vanaf daar was het één stofwolk en waren het geen mensen meer.',
      'Hij ging terug naar de paarden.',
      'Er waren er honderdvier. Hij telde ze twee keer.',
    ],
  },
  {
    nummer: 13,
    titel: 'Wachten is ook iets',
    tekst: [
      'De weken daarna waren de langste van zijn leven en er gebeurde bijna niets in.',
      'Dat is het vreemde aan oorlog, ontdekte Ayyur: het is voor bijna iedereen wachten. De verhalen gaan over de dag dat het gebeurde. Niemand vertelt over de vier weken ervoor, waarin je gras zoekt voor honderdvier paarden op een helling waar het gras op is.',
      'Hij leerde in die weken drie dingen.',
      'Het eerste leerde hij van de oude man met de geiten, die om de paar dagen langskwam en daarna elke dag, en die uiteindelijk zijn middagen bij de omheining doorbracht zonder dat iemand kon uitleggen waarom. Hij heette iets wat Ayyur nooit goed heeft kunnen zeggen. Hij wees dingen aan en zei het woord, en Ayyur zei het na, en de oude man verbeterde hem, en dat ging zo de hele zomer door.',
      'Water. Steen. Geit. Berg. Kind. Brood.',
      'Zo leer je een taal. Niet uit een boek. Van een oude man die niets beters te doen heeft.',
      'Het tweede leerde hij van Yunus. Hij vroeg op een middag, half voor de grap, of de schrijver hem letters kon leren, en Yunus zei: “Nee,” en drie dagen later zat hij met een stok in het zand naast hem.',
      'Het ging traag. Ayyur was er slecht in. Zijn hand deed niet wat zijn hoofd bedacht en de letters kwamen er scheef uit, als iets wat door een dier was aangeraakt.',
      'Na een maand kon hij zijn eigen naam.',
      'Hij schreef hem die avond twintig keer in het zand bij de omheining en veegde hem twintig keer uit, en de eenentwintigste keer liet hij hem staan tot de wind hem meenam.',
      'Het derde leerde hij van niemand.',
      'Hij ontdekte dat hij bij de oproep niet meer alleen opstond omdat het beleefd was.',
      'Het was ergens in augustus. Hij stond bij Tafukt, het werd donker, de man op de steen begon, en Ayyur merkte dat hij het fijn vond dat het gebeurde. Niet om wat er gezegd werd — hij verstond er nog steeds weinig van. Om het feit dat er op een dag vijf keer een streep werd getrokken, op een kust waar hij niemand kende en niemand hem kende, en dat de dag daardoor geen brij was maar een ding met stukken.',
      'Hij ging er nog altijd niet bij staan.',
      'Maar hij vroeg Yunus die week wel hoe de woorden gingen, en Yunus zei ze langzaam voor, en Ayyur zei ze na, en de schrijver verbeterde hem zoals de oude man hem verbeterde bij water, steen, geit.',
      'Daar blijft het in dit boek bij, want daar bleef het bij.',
      'Wat er in de jaren daarna van geworden is, weten we niet. We weten alleen dat het zo begon bij duizenden jongens als hij: niet met een leger, niet met een gevecht, maar met iemand die iets vijf keer per dag zag gebeuren tot het bij de dag hoorde.',
    ],
  },
  {
    nummer: 14,
    titel: 'Het nieuws van de rivier',
    tekst: [
      'Het nieuws kwam op een dinsdag, met een ruiter die zo hard had gereden dat zijn paard niet meer te redden was.',
      'Ayyur zag het aan het paard voordat hij het aan de man zag. Zo werkt dat als je bij paarden hoort.',
      'Er was gevochten bij een rivier in het zuiden van het land, acht dagen ver. Het had drie dagen geduurd, of vijf, afhankelijk van wie je het vroeg. De koning met de kroon was er geweest en was er niet meer, en daarover liepen de verhalen meteen zo ver uiteen dat Ayyur ophield met luisteren.',
      'Wat er in elk verhaal hetzelfde was: het leger was niet verslagen. Het trok door naar het noorden. Er zouden steden vallen die niemand in het kamp bij naam kende.',
      'Er werd die avond gejuicht op het strand.',
      'Ayyur juichte niet, want hij had nog steeds niet gehoord wat hij wilde horen.',
      'Hij vroeg het aan de ruiter, die te moe was om beleefd te zijn.',
      '“Sa3id uit Tlemcen. Grauw paard. Litteken door zijn wenkbrauw.”',
      'De man keek hem aan alsof hij hem vroeg naar één schaap uit een kudde van tienduizend.',
      '“Jongen,” zei hij. “Ik weet de naam van de koning niet eens zeker.”',
      'Drie weken later kwam er een tweede ruiter, en die wist het ook niet.',
      'In oktober kwam er een kar terug met gewonden en met mannen die niet meer wilden, en Ayyur liep alle achtentwintig langs en vroeg het achtentwintig keer.',
      'De vijfentwintigste kende hem.',
      '“Sa3id,” zei hij. “Ja. Bij de rivier.”',
      'Ayyur wachtte.',
      '“Hij leefde toen ik hem zag,” zei de man. “Daarna ben ik gevallen en heb ik niets meer gezien.”',
      'Dat was alles. Dat is alles wat Ayyur ooit te weten is gekomen, en het is ook alles wat wij weten, want van de zevenduizend mannen die dat jaar de zeestraat overstaken zijn er vier bij naam bekend en de rest is stof.',
      'Ayyur ging terug naar de omheining.',
      'Amellal stond er niet bij. Dat had hij al drie maanden niet, en toch keek hij er elke keer.',
      'Hij haalde water, bewoog het met zijn hand zoals je dat doet voor een paard dat niet uit stilstaand water drinkt, en gaf het aan een ander dier.',
    ],
  },
  {
    nummer: 15,
    titel: 'De kist',
    tekst: [
      'Eind oktober kwam Yunus het kamp door met een kist onder zijn arm, op zoek naar iemand die met paarden kon rijden en de weg wist langs de kust.',
      'Er was niemand anders meer. Dat was het eerlijke antwoord op de vraag waarom hij bij Ayyur uitkwam.',
      'De kist moest naar het noorden, naar een plaats waar het leger een winterkamp had ingericht. Er zaten tabletten in, en brieven, en een leren zak met kleine dingen die soldaten hadden ingeleverd omdat ze ze niet wilden verliezen — en die ze niet waren komen ophalen, wat over die soldaten alles zegt wat je niet wilt weten.',
      '“Hoe lang?” vroeg Ayyur.',
      '“Zes dagen. Acht als het regent.”',
      '“En dan?”',
      'Yunus keek hem aan.',
      '“Dan ben je daar,” zei hij. “En daar is meer dan hier.”',
      'Ayyur laadde de kist op Tafukt.',
      'Bij het vastsjorren viel de zak om en er rolde iets uit op de grond.',
      'Het was van brons, zo lang als zijn hand, en er zat een kop aan met acht punten. Als een ster.',
      '“Wat is dat?” vroeg hij.',
      'Yunus keek er nauwelijks naar.',
      '“Een sleutel,” zei hij. “Die zat al in de zak toen ik hem kreeg. Niemand weet van wie.”',
      'Ayyur hield hem even in zijn hand. Hij was warm van de zon.',
      'Hij dacht aan een deur ergens, aan de andere kant van het water, die iemand voor het laatst achter zich had dichtgetrokken zonder te weten dat het voor het laatst was. Aan een huis dat er misschien nog stond. Aan een man die was ingescheept met een sleutel in zijn zak omdat je die niet achterlaat, en die hem had ingeleverd omdat je hem ook niet meeneemt de rivier over.',
      'Hij liet hem terugglijden in de zak.',
      'Toen haalde hij hem er weer uit, en stak hem in zijn eigen gordel.',
      'Yunus zag het en zei niets.',
      '“Er komt niemand voor,” zei Ayyur.',
      '“Nee,” zei Yunus. “Er komt niemand voor.”',
      'Ayyur trok de riem aan en klom op.',
    ],
  },
  {
    nummer: 16,
    titel: 'Naar het noorden',
    tekst: [
      'Hij reed die middag weg langs de kust, met een kist, een merrie en een sleutel die van niemand was.',
      'Bij de laatste bocht voor de helling hield hij in en keek om.',
      'Het kamp lag beneden hem als iets wat er altijd had gelegen: omheiningen, tenten in rijen, de put, rook van twee vuren. Zeven maanden geleden was het kiezels en wier geweest.',
      'De oude man met de geiten stond op de rand van zijn helling, zoals hij daar elke middag stond.',
      'Ayyur stak zijn hand op.',
      'De oude man stak zijn stok op.',
      'Dat was het.',
      'Hij reed verder, en het land dat hij in reed was groen op een manier die hij niet kende, met andere bomen en te veel water, en met dorpen waar mensen langs de weg stonden en keken naar een jongen op een merrie met een kist.',
      'Hij groette ze in de woorden die hij van de oude man had geleerd. Water. Steen. Brood.',
      'Sommigen lachten. Eén vrouw gaf hem brood.',
      'Dat had hij later moeten opschrijven, want het is het soort ding dat verdwijnt: dat de eerste weken van de verovering van dat land voor een jongen van twaalf bestonden uit vreemde bomen, te veel water en een vrouw die hem brood gaf.',
      'Hij is nooit teruggegaan naar de heuvels achter Tanger.',
      'Dat was geen besluit. Dat is het bij bijna niemand. Het werd winter, en er was werk, en er waren paarden, en toen was er een jaar voorbij en nog een, en op een gegeven moment is het geen reis meer die je uitstelt maar een leven dat je hebt.',
      'De scherf met zijn naam erop is bij zijn vader aangekomen. Dat weten we niet. Dat hopen we.',
      'Wat we wel weten is dat in de eeuwen daarna miljoenen mensen die zeestraat zijn overgestoken, de ene kant op en de andere kant op, en dat er telkens iemand achterbleef die wachtte.',
      'De sleutel ging mee naar het noorden, in de gordel van een jongen die hem van niemand had gekregen.',
      'Waar hij daarna heen ging, staat in het volgende deel.',
    ],
  },
]
