/**
 * De sleutels van Marokko in het Italiaans.
 *
 * De dialoog staat tussen Italiaanse aanhalingstekens («…»). Dat is dezelfde
 * keuze als bij het Spaans: het Nederlands zet de dialoog midden in de alinea,
 * en met gedachtestreepjes — de gewoonte in een Italiaanse roman — zou elke
 * zin een eigen regel vragen en viel het tempo van het origineel weg.
 */
import type { SleutelVertaling } from './sleutels-talen'

export const IT_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'L’incendio delle olive',
    jaar: '± 200',
    waar: 'Walili (Volubilis), ai piedi dello Zerhoun',
    verteller: 'Tala, undici anni, figlia di un capo frantoio che si è ammalato',
    flap: 'Tala ha la chiave del magazzino e il sorvegliante la vuole. Quando l’olio di tutta la città è in pericolo, deve scegliere fra ubbidire e avere ragione.',
    sleutel: 'La chiave viene forgiata a Walili dal nonno di Tala e alla fine parte con una carovana amazigh verso le colline.',
    echt: [
      'Volubilis — in arabo Walili — è stata una vera città romana vicino a Meknès, con migliaia di abitanti, terme e strade lastricate.',
      'La città viveva di olio d’oliva. Sono stati scavati decine di frantoi, e funzionavano con la stessa idea dei frantoi che in Marocco si usano ancora oggi.',
      'I pavimenti erano coperti di mosaici. Una parte è ancora lì, all’aperto.',
      'La popolazione era in gran parte amazigh; la vita romana e quella amazigh qui si intrecciavano.',
    ],
    verzonnen: [
      'Tala, la sua famiglia e il sorvegliante Marcus non sono esistiti.',
      'L’incendio della storia è inventato. Non ci sono prove di un grande incendio a Walili in quel periodo.',
      'La chiave con la stella a otto punte è inventata. Il khatam a otto punte è invece un motivo marocchino vero e antichissimo.',
    ],
    hoofdstukken: [
      { titel: 'La chiave', tekst: [
        'Tala si svegliò per l’odore.',
        'Olive. Olive frante, calde e amare. In quelle settimane tutta la città odorava così. Restò un momento sdraiata e ascoltò. Fuori il grande frantoio scricchiolava già. Voleva dire che era in ritardo.',
        'Saltò giù dal letto e si infilò il vestito dalla testa.',
        '«Tala!» gridò sua madre da basso. «La porta!»',
        'La porta. Naturalmente la porta.',
        'Da quando suo padre si era ammalato, Tala faceva il suo lavoro. Ogni mattina andava al magazzino dietro casa e apriva la porta. Lì stavano le giare. Cento giare, riempite fino all’orlo di olio, pronte per andare al porto.',
        'La chiave le pendeva al collo da un cordoncino. Era di bronzo e lunga come la sua mano. Gliel’aveva forgiata suo nonno, molto prima che lei ci fosse. Nella testa aveva otto punte, come una stella.',
        '«Non perderla», aveva detto suo padre. L’aveva detto piano, perché più forte non gli riusciva più. «Quella porta non si apre con nient’altro.»',
        'Tala corse giù per le scale, oltre la cucina, attraverso il cortile. Era ancora presto. Il sole stava appena sopra le colline e le pietre erano fredde sotto i suoi piedi.',
        'Davanti al magazzino c’era un uomo.',
        'Si fermò.',
        'Era grande e portava il mantello rosso del sorvegliante. Marcus. A Walili conoscevano tutti Marcus, e non piaceva a nessuno.',
        '«Sei in ritardo», disse lui.',
        '«Sono in orario», disse Tala.',
        'Sapeva che non avrebbe dovuto dirlo. Lo disse lo stesso.',
        'Marcus la guardò. Poi tese la mano.',
        '«Dammi quella chiave. Una bambina non deve sorvegliare cento giare.»',
        'Tala fece un passo indietro.',
        'Nella testa sentiva suo padre. *Quella porta non si apre con nient’altro.* E pensò a un’altra cosa, una cosa che aveva visto il giorno prima e che le era sembrata niente.',
        'Due giare che non erano al loro posto.',
        '«Allora?» disse Marcus.',
        'Tala strinse la mano attorno al bronzo. Si era scaldato sulla sua pelle.',
        '«No», disse.',
      ] },
      { titel: 'Due giare', tekst: [
        'Marcus non rise. E non si arrabbiò neanche. Quella fu la cosa peggiore.',
        'Abbassò la mano, si aggiustò il mantello e disse: «Come vuoi.» Poi se ne andò, fuori dal vicolo, senza voltarsi.',
        'Tala rimase ferma finché non sentì più i suoi passi. Solo dopo si accorse che le tremavano le mani.',
        'Aprì la porta.',
        'Dentro era buio e fresco. Le giare stavano in file da dieci, con la paglia in mezzo perché non sbattessero l’una contro l’altra. Dieci file da dieci. Ogni mattina le contava. Gliel’aveva insegnato suo padre quando aveva sei anni, e allora era ancora un gioco.',
        'Cominciò da sinistra e contò ad alta voce, come sempre.',
        'All’ultima fila si fermò.',
        'Ce n’erano nove.',
        'Tala contò di nuovo. Nove. Girò intorno alla fila, si chinò, guardò dietro la paglia. Nove.',
        'Anche il giorno prima aveva visto una cosa strana. Due giare messe male, con i manici verso il muro invece che verso il passaggio. Aveva pensato: qualcuno ha fatto in fretta. Le aveva raddrizzate e non ci aveva più pensato.',
        'Adesso ce n’era una in meno.',
        'Si sedette sulla soglia con la schiena contro lo stipite e le ginocchia raccolte, e cercò di capire cosa doveva fare.',
        'Poteva dirlo a sua madre. Ma quel mese sua madre ne aveva già abbastanza: un marito malato di sopra, una casa piena di gente da pagare, e un raccolto che fra tre settimane doveva partire per il porto.',
        'Poteva dirlo a Marcus. Marcus era il sorvegliante. Era il suo lavoro.',
        'Tala guardò il vicolo dove era sparito.',
        'No.',
        '«Sei in mezzo», disse una voce.',
        'Sobbalzò. Davanti a lei c’era un ragazzo più o meno della sua età, con un grembiule di cuoio e le braccia piene di fascine. Aveva le mani nere.',
        '«Non sono in mezzo», disse Tala. «Questa è la mia porta.»',
        '«Allora sei in mezzo alla tua porta.»',
        'Si chiamava Yidir e lavorava alla fucina in fondo alla strada. Tala lo conosceva di vista come si conoscono tutti di vista a Walili, e nient’altro.',
        'Si alzò per farlo passare. Lui non passò.',
        '«Tu conti ogni mattina», disse.',
        '«Come fai a saperlo?»',
        '«Passo di qui ogni mattina.»',
        'Tala esitò. Poi lo disse lo stesso, perché doveva uscirle e perché lui ormai era lì.',
        '«Ne manca una.»',
        'Yidir posò le fascine per terra.',
        '«Una?» disse. «Allora sei stata fortunata. Da noi mancano sei barre di ferro.»',
      ] },
      { titel: 'Come si fa l’olio', tekst: [
        'Quel pomeriggio Tala era al frantoio, come ogni giorno durante il raccolto.',
        'Il frantoio era una pietra scavata grande come un carro, con dentro una pietra rotonda che un asino trascinava in tondo. Le olive andavano dentro, venivano schiacciate, e quello che ne usciva era una massa bruna e spessa che non somigliava a niente.',
        'Era la parte che deludeva sempre i forestieri. «*Quello* sarebbe olio?» chiedevano. No. Quello era l’inizio.',
        'La massa andava in stuoie rotonde di giunco intrecciato. Le stuoie si impilavano una sull’altra sotto la pressa a trave, e poi due uomini giravano la vite, lentamente, come se avessero tempo. Sotto la pila correva un canaletto.',
        'Era da lì che usciva.',
        'Prima acqua, torbida e sporca. Poi, dopo un po’, un’altra cosa. Qualcosa che restava a galla sull’acqua ed era più verde di tutto quello che Tala conosceva.',
        'La prima volta suo padre l’aveva presa per la nuca e le aveva tenuto la testa sopra. «Annusa», aveva detto. «È questo. Se odora *così*, è buono. Se non odora di niente, hai aspettato troppo.»',
        'Allora aveva mentito, aveva detto che lo sentiva. Adesso lo sentiva davvero.',
        'Walili viveva di questo. Non dei pavimenti a mosaico su cui camminavano i visitatori, non delle colonne della piazza, non delle strade lastricate. Di questo. Di olive frante che finivano nelle giare, sui carri verso la costa, e sulle navi verso posti di cui Tala conosceva soltanto i nomi.',
        'Teneva d’occhio il canaletto e le stuoie e l’asino, e intanto pensava a novantanove giare.',
        'Sei barre di ferro, aveva detto Yidir. Dalla fucina.',
        'Il ferro costava caro. L’olio costava caro. E tutti e due uscivano dalla città nella stessa direzione: per la strada del porto.',
        '«Tala.» Uno degli uomini indicò il canaletto. «Trabocca.»',
        'Scattò in avanti e ci mise sotto la ciotola, troppo tardi. Un filo d’olio corse sulla pietra e sparì fra le fughe.',
        'Un dito, forse due. Abbastanza per una famiglia per una settimana.',
        'L’uomo non disse niente. Questo la fece sentire peggio.',
      ] },
      { titel: 'Cosa può fare un sorvegliante', tekst: [
        'Marcus tornò il terzo giorno, e non venne da solo.',
        'Tala lo vide entrare nel cortile con due uomini dietro. Sua madre uscì, si asciugò le mani sul vestito e si mise esattamente fra lui e la porta.',
        '«Pace», disse Marcus.',
        '«Pace», disse sua madre, con il tono che si usa quando non lo si pensa.',
        '«Tuo marito è malato.»',
        '«Mio marito riposa.»',
        '«Tre settimane», disse Marcus. «Fra tre settimane il raccolto parte per il porto, e la città conta su quello che c’è in questa casa. Devo sapere che c’è.»',
        '«C’è.»',
        '«Voglio vederlo.»',
        'Cadde un silenzio. Tala stava sulla soglia della cucina e non osava muoversi.',
        'Sua madre disse: «Puoi guardare. Apre mia figlia.»',
        'Tala attraversò il cortile sotto gli occhi di cinque persone. Si sfilò il cordoncino dalla testa, infilò la chiave nella serratura e spinse la porta.',
        'Marcus entrò. Camminò lungo le file, lentamente, con le mani dietro la schiena. All’ultima fila si fermò.',
        'Tala trattenne il fiato.',
        '«Novantanove», disse Marcus.',
        'Si voltò e guardò sua madre.',
        '«Ne dovrebbero essere cento.»',
        'Sua madre si irrigidì. Tala lo vide dalle spalle.',
        '«Allora una si è rotta», disse.',
        '«Allora ci sarebbero i cocci.» Marcus allargò le mani. «Non vedo cocci. Vedo paglia che è stata rimessa a posto.»',
        'Aspettò un momento, esattamente quanto bastava.',
        '«Non sto dicendo che rubate», disse poi. «Sto dicendo che una bambina di undici anni ha la chiave di cento giare, e che oggi ce ne sono novantanove. Questo dico. E questo dirò anche in piazza.»',
        'Uscì e passò accanto a Tala come se fosse un palo.',
        'Quando se ne fu andato, sua madre si sedette sul bordo del pozzo. Per molto tempo non disse niente.',
        '«Mamma», disse Tala. «Non l’ho—»',
        '«Lo so.»',
        '«L’ho contate lunedì e allora erano ancora—»',
        '«Tala.» Sua madre alzò gli occhi. Erano rossi. «Lo so. E questo non ci aiuta.»',
      ] },
      { titel: 'La fucina', tekst: [
        'Yidir era seduto su un secchio rovesciato davanti alla fucina e limava un cardine.',
        '«Avevi ragione», disse Tala.',
        '«È una cosa che la gente mi dice di rado», disse Yidir senza alzare gli occhi. «Su cosa?»',
        '«Sul fatto che non era una giara sola.»',
        'Adesso alzò gli occhi.',
        'Tala si sedette accanto a lui sulla soglia e raccontò. Di Marcus, di novantanove, di quello che avrebbe detto in piazza. Yidir ascoltò come faceva tutto: come se intanto pensasse ad altro, ma non gli sfuggiva niente.',
        '«E il tuo ferro?» chiese lei.',
        '«Sei barre. Il mio maestro pensa di aver sbagliato a contare.» Yidir fece spallucce. «Il mio maestro non sbaglia mai a contare.»',
        '«Quando?»',
        '«La settimana scorsa. E tre quella prima.»',
        'Tala raccolse le ginocchia.',
        '«Cosa esce dalla città?» chiese. «Ogni giorno, intendo.»',
        'Yidir ci pensò.',
        '«Carri», disse. «Olio, grano, pelli, ferro. Tutto passa per la strada verso nord. Alla porta c’è un posto di guardia. Lì si scrive tutto.»',
        '«Chi scrive?»',
        'Yidir la guardò.',
        '«Il sorvegliante», disse.',
        'Per un po’ non dissero niente, né l’uno né l’altra.',
        '«Questo non prova niente», disse alla fine Tala.',
        '«No.»',
        '«Se lo dico, diranno che una bambina di undici anni accusa un uomo perché non le sta simpatico.»',
        '«Sì», disse Yidir. «Lo diranno.»',
        'Mise via il cardine.',
        '«Quindi ti serve qualcosa che non possano rigirare a parole.»',
        '«Tipo?»',
        '«Tipo vedere cosa passa di notte da quella porta.»',
        'Tala lo guardò. Lui ricambiò lo sguardo, e per la prima volta da quando lo conosceva, rise.',
      ] },
      { titel: 'Cosa passa di notte dalla porta', tekst: [
        'Erano sdraiati sul tetto delle terme, a pancia in giù, con il mento sulle braccia.',
        'Il tetto era caldo dalla giornata. Sotto di loro c’era la strada che andava alla porta nord, larga abbastanza per due carri affiancati. Alla porta ardeva una lampada.',
        '«Quanto manca?» sussurrò Tala.',
        '«Non lo so.»',
        '«Avevi detto che di notte passano i carri.»',
        '«Avevo detto che *pensavo* che di notte passassero i carri.»',
        'Tala sospirò e posò la testa sul braccio.',
        'Quella notte le stelle erano incredibili. In città le vedevi a metà, per via della luce e del fumo, ma quassù erano così tante che diventava inquietante.',
        '«Mia nonna dice che sono una mappa», disse Yidir.',
        '«Le stelle?»',
        '«Sì. Se le sai leggere, puoi andare dappertutto. Dice che la sua famiglia è arrivata così dal deserto fin qui.»',
        '«Tu le sai leggere?»',
        '«No», disse Yidir. «Nessuno me l’ha insegnato.»',
        'Poi lo sentirono.',
        'Un carro. Non due asini, non cavalli — un asino solo, lento, e il rumore del legno che scricchiola sotto il peso.',
        'Tala si spostò sul bordo.',
        'Il carro sbucò da una traversa. Accanto camminavano due uomini, tutti e due con un panno in testa. Sul carro c’era paglia, e sotto la paglia qualcosa di tondo.',
        'Alla porta il carro si fermò.',
        'Dalla garitta uscì un uomo con una lampada. Non andò verso il carro. Andò verso gli uomini, parlò con loro un momento, e scrisse qualcosa su una tavoletta.',
        'Poi alzò la sbarra.',
        'Il carro entrò nella notte.',
        'Tala lasciò andare il fiato. Non si era accorta di trattenerlo.',
        '«Non ha guardato», disse. «Non ha guardato sotto la paglia.»',
        '«No.»',
        '«Questo è—»',
        '«Questo continua a non essere niente», disse Yidir. «È un uomo che non guarda abbastanza bene. Non si impicca nessuno per questo.»',
        'Aveva ragione, e Tala lo sapeva.',
        'Ma quando il carro prese la curva, successe una cosa. L’asino si spaventò per qualcosa nel buio, tirò di lato, e il carro salì con una ruota sul bordo della strada.',
        'Dal carro cadde qualcosa.',
        'Rotolò, si fermò contro il muro, e lì rimase.',
        'Una giara.',
        'Uno degli uomini imprecò, tornò indietro, la raccolse e la rimise sotto la paglia. Il carro proseguì.',
        'Ma Tala aveva visto cosa c’era sopra.',
        'Sulla spalla di ogni giara della loro casa suo padre imprimeva un segno nell’argilla prima della cottura. Otto punte. Una stella.',
        'Afferrò il braccio di Yidir così forte che lui sibilò.',
        '«Quella è nostra», disse.',
      ] },
      { titel: 'Quel che dici e quel che sentono', tekst: [
        'La mattina dopo Tala andò in piazza.',
        'Ci aveva pensato tutta la notte, o almeno per metà; l’altra metà aveva dormito senza volerlo. Sapeva cosa avrebbe detto. L’aveva provato tre volte davanti al muro della sua stanza.',
        'In piazza, sotto le colonne, il consiglio teneva seduta. Voleva dire: cinque uomini su panche di pietra, uno scrivano accanto, e intorno chiunque avesse qualcosa da lamentare.',
        'Marcus era già lì.',
        'Tala aspettò che un uomo finisse di litigare su un muro e un vicino. Poi si fece avanti.',
        '«Voglio dire una cosa», disse.',
        'Cinque uomini alzarono gli occhi. Uno di loro, il più vecchio, con una faccia come un fico secco, si sporse in avanti.',
        '«Di chi sei figlia?»',
        '«Di Yuba, il frantoiano. Della via delle Colonne.»',
        '«Quello è malato.»',
        '«Sì», disse Tala. «Per questo sono qui io.»',
        'Raccontò. Della giara sparita, e del giorno dopo un’altra. Del carro nella notte e dell’uomo che aveva alzato la sbarra senza guardare sotto la paglia. Della giara caduta e del segno con le otto punte.',
        'Lo raccontò esattamente come l’aveva provato, e mentre lo faceva, lo sentì anche lei.',
        'Sentì come suonava.',
        'Una bambina. Un tetto. Il buio. Un segno che non aveva visto nessun altro.',
        'Quando ebbe finito, per un momento ci fu silenzio. Poi Marcus disse, molto tranquillo: «Posso?»',
        'Il più vecchio annuì.',
        '«La bambina ha ragione, mancano delle giare», disse Marcus. «L’ho contate io stesso, l’altro ieri, nel loro magazzino. Novantanove su cento. L’ho detto anche allora.»',
        'Allargò le mani, come faceva lui.',
        '«Chi ha la chiave di quella porta?»',
        'Nessuno disse niente.',
        '«Lei», disse Marcus. «Una bambina di undici anni. E adesso che ne manca una, è stato un carro nella notte. Un carro che ha visto soltanto lei.»',
        'Il più vecchio del consiglio guardò Tala, e il suo sguardo non era ostile. Quella fu la cosa peggiore.',
        '«Bambina», disse. «Vai a casa. Occupati di tuo padre.»',
        'Tala rimase in piazza con le braccia lungo i fianchi e le orecchie che bruciavano, e intorno a lei ricominciarono tutti a parlare di un muro e di un vicino.',
      ] },
      { titel: 'L’incendio', tekst: [
        'L’incendio scoppiò quattro giorni dopo, e non scoppiò da loro.',
        'Tala si svegliò per quello. Non per la luce e non per le grida — per il suono. Un brontolio basso e sordo, come se lì vicinissimo qualcuno stesse buttando fuori il fiato per moltissimo tempo.',
        'Era alla finestra prima di essere sveglia.',
        'Dall’altra parte della strada, due case più in là, bruciava il magazzino di Quintus. Anche Quintus faceva olio. Le sue giare stavano in un locale sotto casa, e adesso dalla finestra usciva il fuoco, piatto, e non verso l’alto come il fuoco dovrebbe fare.',
        'È per via dell’olio, lo imparò dopo. L’olio brucia in un altro modo.',
        'Si gridava già. C’era già gente in strada con secchi e coperte, e qualcuno batteva con un bastone sulla lastra di bronzo accanto al pozzo, e Tala corse giù per le scale senza scarpe.',
        'Sua madre la afferrò per un braccio sulla soglia.',
        '«Non da quella parte.»',
        '«Ma—»',
        '«Tala.» Sua madre la teneva con tutte e due le mani. «La nostra porta. *Adesso.*»',
        'E Tala capì.',
        'Se si propaga, viene da loro. Cento giare — novantanove — piene d’olio, dietro una porta di legno, contro lo stesso muro.',
        'Corse al magazzino, si sfilò il cordoncino dalla testa e infilò la chiave nella serratura. Aveva le mani così bagnate che il bronzo le girava via. La terza volta ci riuscì.',
        'La porta si aprì. Le venne incontro il fresco, e l’odore.',
        'Dietro di lei tutta la strada cominciò a portare giare.',
        'Le portarono nel cortile, al pozzo, in strada, dovunque non ci fosse un muro che bruciava. I vicini portavano, gente che conosceva appena, gente con cui suo padre non aveva mai parlato. Qualcuno aveva una scala. Qualcuno buttava le coperte nell’acqua del pozzo e le passava avanti.',
        'Tala portò finché le braccia non vollero più, e poi portò ancora.',
        'Alla settantesima giara vide Yidir. Arrivò con altri quattro della fucina e trascinavano una cosa che sembrava un lungo gancio.',
        'All’ottantacinquesima il tetto del magazzino di Quintus crollò dentro.',
        'All’ultima il sole stava quasi sorgendo.',
        'Allora non c’era più fuoco. C’era solo fumo basso sulla strada, e duecento persone che guardavano senza dire niente, e mani nere, e da qualche parte un bambino che piangeva.',
        'Tala era seduta sul gradino, appoggiata a sua madre.',
        'Ed è per questo che fu l’unica a vedere l’uomo che usciva dal vicolo accanto alla casa di Quintus, controcorrente, con il mantello sul braccio invece che sulle spalle.',
        'Il mantello era rosso.',
      ] },
      { titel: 'Il mantello rosso', tekst: [
        'Lo raccontò a Yidir prima di raccontarlo a chiunque altro.',
        'Lui ascoltò senza interromperla, e quando ebbe finito disse: «Continua a non essere niente.»',
        '«L’ho visto.»',
        '«Hai visto un uomo con un mantello rosso in una strada piena di gente con la fuliggine in faccia.» Yidir diede un calcio a un sasso. «Io ti credo. Il consiglio no.»',
        'Tala sapeva che aveva ragione e ne aveva abbastanza che avesse sempre ragione.',
        '«E allora cosa?» disse. «Non posso mica non fare niente.»',
        '«No», disse Yidir. «Ma ti serve qualcosa che non venga da te.»',
        'Si sedette sul bordo del pozzo, con i talloni contro la pietra.',
        '«Alla porta scrivono tutto», disse. «Sulla cera. Cosa esce, quanto, e di chi. Quelle tavolette ogni mese vanno al municipio.»',
        '«E se non c’è scritto niente di strano?»',
        '«Allora non c’è scritto niente di strano», disse Yidir. «E allora sai che non è nei registri ma nel buio. Anche quello è qualcosa.»',
        'La guardò.',
        '«Ma se invece c’è scritto qualcosa — se lì ci sono dodici giare mentre dalla porta ne sono uscite tredici — allora non è una bambina che ha visto una cosa. È un numero accanto a un numero, e i numeri non li rigira nessuno a parole.»',
        'Tala pensò alla notte sul tetto. All’uomo che non aveva guardato sotto la paglia.',
        '«Chi può vedere quelle tavolette?»',
        '«Noi no.»',
        '«E chi allora?»',
        'Yidir tacque un momento.',
        '«Il mio maestro», disse. «Fornisce il ferro per le serrature del municipio. Entra lì senza che nessuno gli chieda perché.»',
        '«E allora chiediglielo.»',
        '«Non è uno che si mette contro il sorvegliante.»',
        '«Chiediglielo», disse Tala un’altra volta.',
        'Yidir si guardò le mani nere.',
        '«Va bene», disse. «Ma non stasera. Stasera è il venerdì del mercato e allora è di cattivo umore.»',
        'Nonostante tutto Tala dovette ridere.',
        'Era la prima volta dopo giorni.',
      ] },
      { titel: 'Cosa c’era scritto sulla cera', tekst: [
        'Il fabbro si chiamava Amanar ed era l’uomo più grande che Tala avesse mai visto da vicino.',
        'Per due giorni non disse niente. Poi la terza mattina arrivò nella via delle Colonne con un pacchetto sotto il braccio, e si sedette sul gradino del magazzino come se fosse la cosa più normale.',
        '«Tu sei la figlia di Yuba», disse.',
        '«Sì.»',
        '«Tuo padre una volta ha dato a mia madre olio per tutto un inverno senza farselo pagare.» Amanar guardò la strada. «Erano sedici anni fa. Io non l’ho dimenticato e lui non si ricorda più di averlo fatto.»',
        'Posò il pacchetto sul gradino.',
        'Erano due tavolette di cera, in una cornice di legno, con graffio su graffio su graffio.',
        '«Guardare sì», disse Amanar. «Portare via no. Fra un’ora sono di nuovo dove devono stare.»',
        'Tala si sedette e lesse.',
        'Sapeva leggere. Non spedita, ma abbastanza. Suo padre ci aveva tenuto: «Chi non sa leggere crede a quello che un altro dice che c’è scritto.»',
        'Sulla cera c’erano righe. Data, porta, cosa, quanto, di chi.',
        'Cercò il proprio nome. Lo trovò undici volte.',
        '*Yuba, frantoiano, via delle Colonne. Otto giare.*',
        '*Yuba, frantoiano. Dodici giare.*',
        '*Yuba, frantoiano. Nove giare.*',
        'Tala le sommò. Contò due volte e la seconda volta scrisse il risultato nella sabbia accanto ai suoi piedi.',
        'Centodiciassette giare. In quattro settimane, fuori dalla porta, a nome di suo padre.',
        'Alzò gli occhi.',
        '«Non torna», disse.',
        '«No?» disse Amanar.',
        '«Questa stagione ne abbiamo fatte centosessanta. Lo so con precisione, le ho contate quando le hanno cotte. Sessanta sono state vendute in città. Cento erano nel magazzino.» Indicò la sabbia. «Centosessanta. Non centosettantasette.»',
        'Amanar non disse niente.',
        '«Sono uscite dalla porta diciassette giare che noi non abbiamo mai fatto», disse Tala. «A nostro nome.»',
        'Mentre lo diceva, sentì lei stessa cosa voleva dire.',
        'Non erano solo le loro giare a essere rubate.',
        'Era il loro nome.',
        'Se al municipio avessero fatto i conti, e fosse arrivato meno di quanto era uscito dalla porta, ci sarebbe stata una sola casa in cui la traccia finiva. E quella casa era la loro.',
        '«Amanar», disse, e le venne una voce strana. «Ci stanno preparando.»',
        'Il fabbro si alzò e si scrollò la polvere dalle ginocchia.',
        '«Sì», disse. «È così.»',
        'Raccolse le tavolette.',
        '«Domani vieni in piazza con tua madre. E porta quella sabbia, anzi no — riscrivila su qualcosa che non voli via.»',
      ] },
      { titel: 'Due numeri accanto', tekst: [
        'Il consiglio teneva seduta come sempre: cinque uomini, uno scrivano, e il brusio della gente che aspettava che toccasse a lei.',
        'Questa volta Tala non era sola.',
        'Alla sua sinistra c’era sua madre, con il vestito che metteva solo quando c’era qualcosa di brutto o qualcosa di bello. Alla sua destra c’era Amanar, e dietro Amanar c’erano quattro uomini della fucina che non c’entravano niente ed erano lì lo stesso.',
        'Più in là, contro una colonna, c’era Yidir.',
        'Il più vecchio del consiglio — quello con la faccia come un fico secco — guardò il gruppo e inarcò le sopracciglia.',
        '«Ancora tu», disse a Tala.',
        '«Ho contato», disse Tala.',
        'L’aveva scritto su un pezzo di cuoio, perché il cuoio non vola via. Lo lesse. Quello che avevano prodotto. Quello che era stato venduto in città. Quello che c’era nel magazzino. E poi quello che secondo le tavolette della porta era uscito dalla città a nome di suo padre.',
        'Due numeri.',
        'Quando ebbe finito, il silenzio fu di un genere diverso dalla volta prima.',
        'Marcus si fece avanti. Era ancora tranquillo, ma non più allo stesso modo.',
        '«Una bambina ha guardato nelle tavolette della città», disse. «È vietato.»',
        '«Le ho portate io», disse Amanar.',
        'Il silenzio si fece ancora più grande.',
        'Il più vecchio del consiglio si voltò verso lo scrivano accanto a lui.',
        '«Vai a prenderle.»',
        'Ci volle molto. Non se ne andò nessuno. Qualcuno diede uno sgabello alla madre di Tala e lei non ci si sedette.',
        'Quando le tavolette arrivarono, lo scrivano lesse ad alta voce cosa c’era scritto, e un altro uomo sommò con dei sassolini su una tavola, e tutta la piazza sentì.',
        'Centodiciassette.',
        'Il più vecchio guardò a lungo i numeri, e poi Marcus, e poi di nuovo i numeri.',
        '«Chi scrive alla porta nord?» chiese.',
        '«Cambia», disse Marcus.',
        '«E chi decide chi scrive?»',
        'Marcus non rispose.',
        'Il più vecchio sospirò, e fu il sospiro di un uomo che capisce una cosa che avrebbe preferito non capire, e che sa che adesso deve farci qualcosa.',
        '«Siediti», disse a Tala. «Non tu, Marcus. Tu resti in piedi.»',
      ] },
      { titel: 'Quel che resta', tekst: [
        'Ci vollero ancora tre settimane prima che cambiasse davvero qualcosa, e fu la lezione più lunga di quell’estate: che la verità non funziona come in una storia, dove la dici e tutti annuiscono.',
        'Venne un uomo dalla città madre di Volubilis a controllare i registri. Furono ascoltate delle persone. Due volte non si disse niente e una volta si disse una cosa che nessuno si aspettava: la guardia della porta nord, un ragazzo di diciannove anni, crollò alla terza domanda e raccontò tutto.',
        'Marcus sparì prima che la cosa si chiudesse. La sua casa restò vuota un mese e poi fu data a un altro.',
        'Il padre di Tala non guarì più, non del tutto. In autunno poté di nuovo sedersi nel cortile e sentire scricchiolare il frantoio, e di quello sembrava contento. Chiedeva i numeri e lei glieli diceva. Si fece raccontare tre volte cos’era successo in piazza, e la terza volta pianse, e lei non l’aveva mai visto piangere.',
        'Il raccolto andò al porto. Cento giare. Tornava.',
        'La settimana dopo passò Yidir con sua nonna.',
        'Sua nonna era piccola e vecchia e aveva gli occhi di chi guarda molto più in là di dove sta. Disse che se ne andava: tornava dalla sua famiglia, ai pascoli in montagna, prima dell’inverno. Lo disse come se parlasse di una passeggiata.',
        '«Yidir viene con me», disse. «Per un po’.»',
        'Tala guardò Yidir. Yidir si guardò le mani.',
        '«Quanto è un po’?» chiese.',
        '«Lo si sa solo dopo», disse sua nonna.',
        'Quella sera Tala si sfilò il cordoncino dalla testa.',
        'La chiave era calda, come sempre. Otto punte nella testa, una stella. Suo nonno l’aveva forgiata in una fucina che adesso non esisteva più.',
        'La tenne in mano e pensò a quello che aveva detto suo padre. *Quella porta non si apre con nient’altro.*',
        'La diede a Yidir.',
        '«Non si può», disse lui subito.',
        '«Tu mi hai creduta quando non mi credeva nessuno.»',
        '«Non vale una chiave.»',
        '«È la mia chiave», disse Tala. «Decido io quanto vale.»',
        'Yidir la teneva come se scottasse.',
        '«E che ci faccio?»',
        '«Non lo so», disse Tala. «Regalarla, credo. A qualcuno a cui credi.»',
        'Partirono la mattina dopo, con tre asini e un cane, verso le colline, e Tala salì sul tetto delle terme per guardarli finché non si videro più.',
        'Allora non sapeva ancora che era un bene che la chiave se ne andasse.',
        'Perché Walili non sarebbe stata lì per sempre. Il terremoto venne molto più tardi, e la città fu svuotata lentamente — pietra dopo pietra, finché non restarono che le colonne, i frantoi e i pavimenti a mosaico che ci sono ancora oggi, all’aperto, vicino a Meknès.',
        'Tutto quello che stava nelle case è sparito.',
        'Solo la chiave no.',
      ] },
    ],
  },
}
