/**
 * De sleutels van Marokko in het Engels.
 *
 * Dialoog tussen dubbele aanhalingstekens, zoals in een Engels kinderboek.
 * Deel 15 speelt ook in het Engels in Utrecht: het gaat over een Nederlandse
 * derde generatie, en een verhaal dat per taal verhuist is nergens meer waar.
 */
import type { SleutelVertaling } from './sleutels-talen'

export const EN_SLEUTELS: SleutelVertaling = {
  1: {
    titel: 'The Olive Fire',
    jaar: '± 200',
    waar: 'Walili (Volubilis), at the foot of the Zerhoun',
    verteller: 'Tala, eleven, daughter of an oil-press owner who has fallen ill',
    flap: 'Tala holds the key to the storehouse and the overseer wants it. When the whole city’s oil is at risk, she has to choose between obeying and being right.',
    sleutel: 'The key is forged in Walili by Tala’s grandfather and leaves at the end with an Amazigh caravan into the hills.',
    echt: [
      'Volubilis — Walili in Arabic — was a real Roman city near Meknès, with thousands of inhabitants, bathhouses and stone streets.',
      'The city lived on olive oil. Dozens of presses have been excavated, and they worked on the same principle as the presses still used in Morocco today.',
      'The floors were covered in mosaic. Part of it is still there, in the open air.',
      'The population was largely Amazigh; Roman and Amazigh life ran through one another here.',
    ],
    verzonnen: [
      'Tala, her family and the overseer Marcus did not exist.',
      'The fire in the story is made up. There is no evidence of a great fire at Walili in this period.',
      'The key with the eight-pointed star is made up. The eight-pointed khatam is a real and very old Moroccan motif.',
    ],
    hoofdstukken: [
      { titel: 'The key', tekst: [
        'Tala woke up because of the smell.',
        'Olives. Pressed olives, warm and bitter. The whole city smelled of it in these weeks. She lay still for a moment and listened. Outside, the big press was already creaking. That meant she was late.',
        'She jumped off her bed and pulled her dress over her head.',
        '“Tala!” her mother called from below. “The door!”',
        'The door. Of course, the door.',
        'Since her father had fallen ill, Tala did his work. Every morning she walked to the storehouse behind the house and unlocked the door. The jars stood there. A hundred jars, filled to the brim with oil, ready to go to the harbour.',
        'The key hung on a cord around her neck. It was bronze and as long as her hand. Her grandfather had forged it, long before she existed. Its head had eight points, like a star.',
        '“Don’t lose it,” her father had said. He had said it quietly, because louder was no longer possible for him. “Nothing else opens that door.”',
        'Tala ran down the stairs, past the kitchen, across the courtyard. It was still early. The sun stood just above the hills and the stones were cold under her feet.',
        'There was a man at the storehouse.',
        'She stopped.',
        'He was big and he wore the red cloak of the overseer. Marcus. Everyone in Walili knew Marcus, and nobody liked him.',
        '“You’re late,” he said.',
        '“I’m on time,” said Tala.',
        'She knew she should not have said that. She said it anyway.',
        'Marcus looked at her. Then he held out his hand.',
        '“Give me that key. A child has no business guarding a hundred jars.”',
        'Tala took a step back.',
        'In her head she heard her father. *Nothing else opens that door.* And she thought of something else, something she had seen yesterday and had decided was nothing.',
        'Two jars that were not in their place.',
        '“Well?” said Marcus.',
        'Tala closed her hand around the bronze. It had grown warm from her skin.',
        '“No,” she said.',
      ] },
      { titel: 'Two jars', tekst: [
        'Marcus did not laugh. He did not get angry either. That was the worst of it.',
        'He lowered his hand, straightened his cloak and said: “As you wish.” Then he walked away, out of the alley, without looking back.',
        'Tala stood still until she could no longer hear his footsteps. Only then did she notice her hands were shaking.',
        'She opened the door.',
        'Inside it was dark and cool. The jars stood in rows of ten, with straw between them so they would not knock against each other. Ten rows of ten. Every morning she counted them. Her father had taught her that when she was six, and back then it was still a game.',
        'She started on the left and counted aloud, as always.',
        'At the back row she stopped.',
        'There were nine.',
        'Tala counted again. Nine. She walked around the row, crouched, looked behind the straw. Nine.',
        'Yesterday she had seen something odd too. Two jars standing the wrong way, handles towards the wall instead of towards the path. She had thought: someone did that in a hurry. She had set them straight and thought no more about it.',
        'Now there was one fewer.',
        'She sat down in the doorway with her back against the post and her knees pulled up, and tried to work out what to do.',
        'She could tell her mother. But her mother already had enough this month: a sick husband upstairs, a house full of people who had to be paid, and a harvest that had to go to the harbour in three weeks.',
        'She could tell Marcus. Marcus was the overseer. That was his job.',
        'Tala looked at the alley where he had disappeared.',
        'No.',
        '“You’re in the way,” said a voice.',
        'She started. In front of her stood a boy about her own age, in a leather apron, his arms full of bundles of kindling. His hands were black.',
        '“I’m not in the way,” said Tala. “This is my door.”',
        '“Then you’re in the way of your own door.”',
        'His name was Yidir and he worked at the smithy at the end of the street. Tala knew him by sight the way you know everyone in Walili by sight, and no further.',
        'She got up to let him past. He did not go past.',
        '“You count every morning,” he said.',
        '“How do you know that?”',
        '“I walk past every morning.”',
        'Tala hesitated. Then she said it anyway, because it had to come out and because he happened to be standing there.',
        '“One is gone.”',
        'Yidir put his bundles down on the ground.',
        '“One?” he said. “Then you’ve been lucky. We’re missing six iron bars.”',
      ] },
      { titel: 'How oil is made', tekst: [
        'That afternoon Tala stood at the press, as she did every day during the harvest.',
        'The press was a hollowed-out stone as big as a cart, with a round stone inside it that a donkey dragged round and round. The olives went in, were crushed, and what came out was a thick brown mass that looked like nothing at all.',
        'That was the part that always disappointed strangers. “*That* is oil?” they would ask. No. That was the beginning.',
        'The mass went into round mats of woven reed. The mats were stacked on top of each other under the beam press, and then two men turned the screw, slowly, as if they had all the time in the world. Under the stack ran a channel.',
        'That was where it came out.',
        'First water, cloudy and dirty. Then, after a while, something else. Something that floated on the water and was greener than anything Tala knew.',
        'The first time, her father had taken her by the neck and held her head over it. “Smell,” he had said. “That’s it. If it smells like *that*, it’s good. If it smells of nothing, you waited too long.”',
        'She had lied then and said she could smell it. Now she really could.',
        'Walili lived on this. Not on the mosaic floors that visitors walked across, not on the columns on the square, not on the stone streets. On this. On pressed olives that went into jars, onto carts to the coast, and onto ships to places whose names were all Tala knew of them.',
        'She watched the channel and the mats and the donkey, and all the while she was thinking about ninety-nine jars.',
        'Six iron bars, Yidir had said. From the smithy.',
        'Iron was expensive. Oil was expensive. And both left the city in the same direction: along the road to the harbour.',
        '“Tala.” One of the men pointed at the channel. “It’s overflowing.”',
        'She shot forward and pushed the bowl underneath, too late. A stream of oil ran over the stone and disappeared between the joints.',
        'A finger thick, maybe two. Enough for a family for a week.',
        'The man said nothing about it. That made it worse.',
      ] },
      { titel: 'What an overseer may do', tekst: [
        'Marcus came back on the third day, and he did not come alone.',
        'Tala saw him walk into the courtyard with two men behind him. Her mother came out, wiped her hands on her dress, and stood exactly between him and the door.',
        '“Peace,” said Marcus.',
        '“Peace,” said her mother, in the voice you use when you don’t mean it.',
        '“Your husband is ill.”',
        '“My husband is resting.”',
        '“Three weeks,” said Marcus. “In three weeks the harvest goes to the harbour, and the city is counting on what stands in this house. I need to know it’s there.”',
        '“It’s there.”',
        '“I want to see it.”',
        'There was a silence. Tala stood in the kitchen doorway and did not dare move.',
        'Her mother said: “You may look. My daughter will open it.”',
        'Tala walked across the courtyard under the eyes of five people. She lifted the cord over her head, put the key in the lock and pushed the door open.',
        'Marcus went in. He walked along the rows, slowly, hands behind his back. At the back row he stopped.',
        'Tala held her breath.',
        '“Ninety-nine,” said Marcus.',
        'He turned around and looked at her mother.',
        '“There should be a hundred.”',
        'Her mother went stiff. Tala could see it in her shoulders.',
        '“Then one has broken,” she said.',
        '“Then there would be shards.” Marcus spread his hands. “I see no shards. I see straw that has been pulled straight.”',
        'He waited a moment, exactly long enough.',
        '“I am not saying you are stealing,” he said then. “I am saying that an eleven-year-old child holds the key to a hundred jars, and that today there are ninety-nine. That is what I am saying. And that is what I shall say on the square as well.”',
        'He walked out of the door and past Tala as if she were a post.',
        'When he had gone, her mother sat down on the edge of the well. She said nothing for a very long time.',
        '“Mama,” said Tala. “I didn’t take—”',
        '“I know.”',
        '“I counted them on Monday and then there were still—”',
        '“Tala.” Her mother looked up. Her eyes were red. “I know. And it doesn’t help us.”',
      ] },
      { titel: 'The smithy', tekst: [
        'Yidir sat on an upturned bucket in front of the smithy, filing a hinge.',
        '“You were right,” said Tala.',
        '“People rarely say that to me,” said Yidir without looking up. “About what?”',
        '“About it not being one jar.”',
        'Now he did look up.',
        'Tala sat down beside him on the doorstep and told him. About Marcus, about ninety-nine, about what he was going to say on the square. Yidir listened the way he did everything: as if he were thinking about something else at the same time, but he missed nothing.',
        '“And your iron?” she asked.',
        '“Six bars. My master thinks he miscounted.” Yidir shrugged. “My master never miscounts.”',
        '“When?”',
        '“Last week. And three the week before.”',
        'Tala pulled up her knees.',
        '“What leaves the city?” she asked. “Every day, I mean.”',
        'Yidir thought about it.',
        '“Carts,” he said. “Oil, grain, hides, iron. Everything goes along the road to the north. There’s a guard post at the gate. Everything gets written down there.”',
        '“By whom?”',
        'Yidir looked at her.',
        '“By the overseer,” he said.',
        'Neither of them said anything for a while.',
        '“That proves nothing,” said Tala at last.',
        '“No.”',
        '“If I say it, they’ll say an eleven-year-old is accusing a man because he doesn’t like her.”',
        '“Yes,” said Yidir. “That’s what they’ll say.”',
        'He put the hinge down.',
        '“So you need something they can’t talk away.”',
        '“Such as?”',
        '“Such as seeing what goes through that gate at night.”',
        'Tala looked at him. He looked back, and for the first time since she had known him, he laughed.',
      ] },
      { titel: 'What goes through the gate at night', tekst: [
        'They lay on the roof of the bathhouse, flat on their stomachs, chins on their arms.',
        'The roof was warm from the day. Below them lay the street that ran to the northern gate, wide enough for two carts side by side. One lamp burned at the gate.',
        '“How much longer?” whispered Tala.',
        '“I don’t know.”',
        '“You said carts go at night.”',
        '“I said I *thought* carts go at night.”',
        'Tala sighed and laid her head on her arm.',
        'The stars that night were unbelievable. In the city you saw half of them, because of the light and the smoke, but up here there were so many it made you restless.',
        '“My grandmother says they’re a map,” said Yidir.',
        '“The stars?”',
        '“Yes. If you can read them, you can go anywhere. She says her family walked from the desert to here that way.”',
        '“Can you read them?”',
        '“No,” said Yidir. “Nobody taught me.”',
        'Then they heard it.',
        'A cart. Not two donkeys, not horses — one donkey, slow, and the sound of wood creaking under weight.',
        'Tala shifted to the edge.',
        'The cart came out of a side street. Two men walked beside it, both with cloths around their heads. On the cart lay straw, and under the straw stood something round.',
        'At the gate the cart stopped.',
        'A man with a lamp came out of the guard hut. He did not walk to the cart. He walked to the men, spoke with them briefly, and wrote something on a tablet.',
        'Then he lifted the barrier.',
        'The cart drove into the night.',
        'Tala let out her breath. She had not noticed she was holding it.',
        '“He didn’t look,” she said. “He didn’t look under the straw.”',
        '“No.”',
        '“That’s—”',
        '“That’s still nothing,” said Yidir. “That’s a man who doesn’t look carefully enough. Nobody hangs for that.”',
        'He was right, and Tala knew it.',
        'But as the cart went round the bend, something happened. The donkey shied at something in the dark, pulled sideways, and the cart went over the kerb with one wheel.',
        'Something fell off the cart.',
        'It rolled, came to rest against the wall, and stayed there.',
        'A jar.',
        'One of the men swore, came back, picked it up and set it under the straw again. The cart drove on.',
        'But Tala had seen what was on it.',
        'On the shoulder of every jar from their house, her father pressed a mark into the clay before it was fired. Eight points. A star.',
        'She grabbed Yidir’s arm so hard that he hissed.',
        '“That one is ours,” she said.',
      ] },
      { titel: 'What you say and what they hear', tekst: [
        'The next morning Tala went to the square.',
        'She had thought about it all night, or at least half the night; the other half she had slept without meaning to. She knew what she was going to say. She had practised it three times against the wall of her room.',
        'On the square, under the columns, the council was in session. That meant: five men on stone benches, a scribe beside them, and everyone with a complaint standing around.',
        'Marcus was already there.',
        'Tala waited until a man had finished about a wall and a neighbour. Then she stepped forward.',
        '“I want to say something,” she said.',
        'Five men looked up. One of them, the oldest, with a face like a dried fig, leaned forward.',
        '“Whose child are you?”',
        '“Yuba’s, the presser. From Column Street.”',
        '“He’s ill.”',
        '“Yes,” said Tala. “That’s why I’m here.”',
        'She told it. About the jar that was gone, and another the day after. About the cart in the night and the man who lifted the barrier without looking under the straw. About the jar that fell off and about the mark with the eight points.',
        'She told it exactly as she had practised it, and while she did, she heard it herself too.',
        'She heard how it sounded.',
        'A child. A roof. The dark. A mark nobody else had seen.',
        'When she had finished it was quiet for a moment. Then Marcus said, very calmly: “May I?”',
        'The oldest nodded.',
        '“The girl is right that jars are missing,” said Marcus. “I counted them myself, the day before yesterday, in their own storehouse. Ninety-nine out of a hundred. I said so at the time as well.”',
        'He spread his hands, the way he did.',
        '“Who holds the key to that door?”',
        'Nobody said anything.',
        '“She does,” said Marcus. “An eleven-year-old child. And now that one is gone, it was a cart in the night. A cart only she has seen.”',
        'The oldest of the council looked at Tala, and his look was not unkind. That was the worst part.',
        '“Child,” he said. “Go home. Look after your father.”',
        'Tala stood on the square with her hands at her sides and her ears burning, and all around her everyone started talking again about a wall and a neighbour.',
      ] },
      { titel: 'The fire', tekst: [
        'The fire started four days later, and it did not start with them.',
        'Tala woke from it. Not from light and not from shouting — from sound. A deep, soft roar, as if somewhere very close by someone were breathing out for a very long time.',
        'She was at the window before she was awake.',
        'Across the street, two houses along, Quintus’s storehouse was burning. Quintus pressed oil too. His jars stood in a room under his house, and fire was coming out of the window now, flat, and not upwards the way fire is supposed to.',
        'That is because of the oil, Tala learned later. Oil burns differently.',
        'There was already shouting. There were already people in the street with buckets and blankets, and someone was beating a stick against the bronze plate by the well, and Tala ran down the stairs without shoes.',
        'Her mother caught her by the arm in the doorway.',
        '“Not that way.”',
        '“But—”',
        '“Tala.” Her mother held her with both hands. “Our door. *Now.*”',
        'And Tala understood.',
        'If it spreads, it comes to them. A hundred jars — ninety-nine — of oil, behind a wooden door, against the same wall.',
        'She ran to the storehouse, lifted the cord over her head and put the key in the lock. Her hands were so wet that the bronze turned away from her. The third time it worked.',
        'The door opened. The coolness came to meet her, and the smell.',
        'Behind her the whole street started carrying jars.',
        'They carried them to the courtyard, to the well, to the street, anywhere there was no burning wall. The neighbours carried, people she hardly knew, people her father had never spoken to. Someone had a ladder. Someone threw blankets into the water of the well and passed them along.',
        'Tala carried until her arms would not, and then she carried some more.',
        'At the seventieth jar she saw Yidir. He came with four others from the smithy and they were dragging something that looked like a long hook.',
        'At the eighty-fifth the roof of Quintus’s storehouse fell in.',
        'At the last one the sun was almost up.',
        'By then there was no more fire. There was only smoke hanging low over the street, and two hundred people standing and looking without saying anything, and black hands, and somewhere a child crying.',
        'Tala sat on the step leaning against her mother.',
        'And that is why she was the only one who saw the man come out of the alley beside Quintus’s house, against the flow, his cloak over his arm instead of around his shoulders.',
        'The cloak was red.',
      ] },
      { titel: 'The red cloak', tekst: [
        'She told Yidir before she told anyone else.',
        'He listened without interrupting her, and when she had finished he said: “That’s still nothing.”',
        '“I saw him.”',
        '“You saw a man in a red cloak in a street full of people with soot on their faces.” Yidir kicked a stone. “I believe you. The council won’t.”',
        'Tala knew he was right and she had had enough of him always being right.',
        '“What then?” she said. “I can’t just do nothing.”',
        '“No,” said Yidir. “But you need something that doesn’t come from you.”',
        'He sat down on the edge of the well, heels against the stone.',
        '“At the gate they write everything down,” he said. “On wax. What goes out, how much, and whose. Those tablets go to the town hall every month.”',
        '“And if there’s nothing strange on them?”',
        '“Then there’s nothing strange on them,” said Yidir. “And then you know it isn’t in the books but in the dark. That’s something too.”',
        'He looked at her.',
        '“But if there *is* something on them — if it says twelve jars while thirteen went out of the gate — then that isn’t a child who saw something. Then it’s a number next to a number, and nobody talks numbers away.”',
        'Tala thought of the night on the roof. Of the man who had not looked under the straw.',
        '“Who can see those tablets?”',
        '“Not us.”',
        '“Who then?”',
        'Yidir was quiet for a moment.',
        '“My master,” he said. “He supplies the iron for the locks of the town hall. He walks in there without anyone asking why.”',
        '“Then ask him.”',
        '“He isn’t someone who gets involved with the overseer.”',
        '“Ask him,” said Tala again.',
        'Yidir looked at his black hands.',
        '“All right,” he said. “But not tonight. Tonight is market Friday and then he’s in a foul mood.”',
        'In spite of everything Tala had to laugh.',
        'It was the first time in days.',
      ] },
      { titel: 'What the wax said', tekst: [
        'The smith was called Amanar and he was the biggest man Tala had ever seen up close.',
        'He said nothing for two days. Then on the third morning he came walking into Column Street with a parcel under his arm, and he sat down on the storehouse step as if that were the natural thing to do.',
        '“You are Yuba’s daughter,” he said.',
        '“Yes.”',
        '“Your father once gave my mother oil for a whole winter without letting her pay.” Amanar looked down the street. “That was sixteen years ago. I have not forgotten it and he no longer remembers doing it.”',
        'He laid the parcel on the step.',
        'They were two tablets of wax, in a wooden frame, scratch upon scratch upon scratch.',
        '“Looking is allowed,” said Amanar. “Taking is not. In an hour they are back where they belong.”',
        'Tala sat down and read.',
        'She could read. Not fluently, but enough. Her father had insisted: “Whoever cannot read believes what somebody else says is written there.”',
        'On the wax were rows. Date, gate, what, how much, whose.',
        'She looked for her own name. She found it eleven times.',
        '*Yuba, presser, Column Street. Eight jars.*',
        '*Yuba, presser. Twelve jars.*',
        '*Yuba, presser. Nine jars.*',
        'Tala added them up. She counted twice and the second time she wrote it in the sand beside her feet.',
        'One hundred and seventeen jars. In four weeks, out of the gate, in her father’s name.',
        'She looked up.',
        '“That isn’t right,” she said.',
        '“No?” said Amanar.',
        '“We made a hundred and sixty this season. I know exactly, I counted them when they were fired. Sixty were sold in the city. A hundred stood in the storehouse.” She pointed at the sand. “A hundred and sixty. Not a hundred and seventy-seven.”',
        'Amanar said nothing.',
        '“Seventeen jars have gone out of that gate that we never made,” said Tala. “In our name.”',
        'She heard herself what that meant, as she said it.',
        'It was not only their jars that were being stolen.',
        'It was their name.',
        'When the counting was done at the town hall, and less came in than had gone out of the gate, there would be one house where the trail ended. And that house was theirs.',
        '“Amanar,” she said, and her voice went strange. “They are setting us up.”',
        'The smith stood up and brushed the dust from his knees.',
        '“Yes,” he said. “They are.”',
        'He picked up the tablets.',
        '“Come to the square tomorrow with your mother. And bring that sand — no, write it out on something that doesn’t blow away.”',
      ] },
      { titel: 'Two numbers side by side', tekst: [
        'The council was in session as always: five men, a scribe, and the murmur of people waiting for their turn.',
        'This time Tala was not alone.',
        'On her left stood her mother, in the dress she only wore when something was very bad or very good. On her right stood Amanar, and behind Amanar stood four men from the smithy who had nothing to do with it and were there anyway.',
        'Further off, against a column, stood Yidir.',
        'The oldest of the council — the one with the face like a dried fig — looked at the group and raised his eyebrows.',
        '“You again,” he said to Tala.',
        '“I have counted,” said Tala.',
        'She had written it on a piece of leather, because leather does not blow away. She read it out. What they had made. What had been sold in the city. What stood in the storehouse. And then what, according to the tablets at the gate, had left the city in her father’s name.',
        'Two numbers.',
        'When she had finished, the silence was a different kind from last time.',
        'Marcus stepped forward. He was still calm, but no longer in the same way.',
        '“A child has looked in the city tablets,” he said. “That is forbidden.”',
        '“I brought them,” said Amanar.',
        'It got quieter still.',
        'The oldest of the council turned to the scribe beside him.',
        '“Fetch them.”',
        'It took a long time. Nobody left. Someone gave Tala’s mother a stool and she did not sit on it.',
        'When the tablets came, the scribe read aloud what was on them, and another man added it up with pebbles on a board, and everyone on the square heard it.',
        'One hundred and seventeen.',
        'The oldest looked at the numbers for a long while, and then at Marcus, and then at the numbers again.',
        '“Who writes at the north gate?” he asked.',
        '“It varies,” said Marcus.',
        '“Who decides who writes?”',
        'Marcus did not answer.',
        'The oldest sighed, and it was the sigh of a man who understands something he would rather not have understood, and who knows he now has to do something about it.',
        '“Sit down,” he said to Tala. “Not you, Marcus. You stay standing.”',
      ] },
      { titel: 'What is left', tekst: [
        'It took another three weeks before anything really changed, and that was the longest lesson of that summer: that the truth does not work the way it does in a story, where you say it and everybody nods.',
        'A man came from Volubilis’s mother city to check the books. People were questioned. Twice nothing was said and once something was said that nobody expected: the guard of the north gate, a boy of nineteen, broke at the third question and told everything.',
        'Marcus disappeared before it was finished. His house stood empty for a month and was then given to someone else.',
        'Tala’s father did not get better, not entirely. In the autumn he could sit in the courtyard again and hear the press creak, and he seemed content with that. He asked about the numbers and she told him. He made her tell three times what had happened on the square, and the third time he cried, and she had never seen him do that.',
        'The harvest went to the harbour. A hundred jars. It added up.',
        'The week after, Yidir came by with his grandmother.',
        'His grandmother was small and old and she had the eyes of someone who looks much further than where she is standing. She said she was leaving: back to her family, to the pastures in the mountains, before winter came. She said it as if she were talking about a walk.',
        '“Yidir is coming,” she said. “For a while.”',
        'Tala looked at Yidir. Yidir looked at his hands.',
        '“How long is a while?” she asked.',
        '“You only know that afterwards,” said his grandmother.',
        'That evening Tala lifted the cord over her head.',
        'The key was warm, as always. Eight points in the head, a star. Her grandfather had forged it in a smithy that no longer existed.',
        'She held it in her hand and thought of what her father had said. *Nothing else opens that door.*',
        'She gave it to Yidir.',
        '“You can’t,” he said at once.',
        '“You believed me when nobody believed me.”',
        '“That isn’t worth a key.”',
        '“It’s my key,” said Tala. “I decide what it’s worth.”',
        'Yidir held it as if it were too hot.',
        '“What am I supposed to do with it?”',
        '“I don’t know,” said Tala. “Give it away, I think. To someone you believe.”',
        'They left the next morning, with three donkeys and a dog, into the hills, and Tala climbed onto the roof of the bathhouse to watch them until she could not see them any more.',
        'She did not know yet that it was a good thing the key was leaving.',
        'Because Walili would not always be there. The earthquake came much later, and the city was slowly emptied — stone by stone, until nothing was left but the columns, the olive presses and the mosaic floors that lie there to this day, in the open air, near Meknès.',
        'Everything that stood in the houses is gone.',
        'Only the key is not.',
      ] },
    ],
  },
}
