import type { Hoofdstuk } from './sleutels'

/**
 * Deel 1 — De olijvenbrand. Walili, rond het jaar 200.
 *
 * Wordt hoofdstuk voor hoofdstuk geschreven; wat er staat is af, wat er niet
 * staat komt nog. Een boek van honderd bladzijden in één zitting schrijven
 * levert honderd vlakke bladzijden op.
 */
export const DEEL1_HOOFDSTUKKEN: Hoofdstuk[] = [
  {
    nummer: 1,
    titel: 'De sleutel',
    tekst: [
      'Tala werd wakker van de geur.',
      'Olijven. Geperste olijven, warm en bitter. De hele stad rook er in deze weken naar. Ze bleef even liggen en luisterde. Buiten kraakte de grote pers al. Dat betekende dat ze te laat was.',
      'Ze sprong van haar bed en trok haar jurk over haar hoofd.',
      '“Tala!” riep haar moeder van beneden. “De poort!”',
      'De poort. Natuurlijk de poort.',
      'Sinds haar vader ziek was geworden, deed Tala zijn werk. Elke ochtend liep ze naar de opslag achter het huis en maakte de deur open. Daar stonden de kruiken. Honderd kruiken, tot de rand gevuld met olie, klaar om naar de haven te gaan.',
      'De sleutel hing aan een koord om haar nek. Hij was van brons en zo lang als haar hand. Haar opa had hem gesmeed, lang voordat zij er was. In de kop zaten acht punten, als een ster.',
      '“Verlies hem niet,” had haar vader gezegd. Hij had het zachtjes gezegd, want harder kon hij niet meer. “Die deur gaat nergens anders voor open.”',
      'Tala rende de trap af, langs de keuken, de binnenplaats over. Het was nog vroeg. De zon stond net boven de heuvels en de stenen waren koud onder haar voeten.',
      'Bij de opslag stond een man.',
      'Ze bleef staan.',
      'Hij was groot en hij droeg de rode mantel van de opzichter. Marcus. Iedereen in Walili kende Marcus, en niemand vond hem aardig.',
      '“Je bent laat,” zei hij.',
      '“Ik ben op tijd,” zei Tala.',
      'Ze wist dat ze dat niet had moeten zeggen. Ze zei het toch.',
      'Marcus keek haar aan. Toen stak hij zijn hand uit.',
      '“Geef mij die sleutel maar. Een kind hoort niet op honderd kruiken te passen.”',
      'Tala deed een stap naar achteren.',
      'In haar hoofd hoorde ze haar vader. *Die deur gaat nergens anders voor open.* En ze dacht aan iets anders, iets wat ze gisteren had gezien en waarvan ze had gedacht dat het niets was.',
      'Twee kruiken die niet op hun plaats stonden.',
      '“Nou?” zei Marcus.',
      'Tala kneep haar hand om het brons. Het was warm geworden van haar huid.',
      '“Nee,” zei ze.',
    ],
  },
  {
    nummer: 2,
    titel: 'Twee kruiken',
    tekst: [
      'Marcus lachte niet. Hij werd ook niet boos. Dat was het ergste.',
      'Hij liet zijn hand zakken, trok zijn mantel recht en zei: “Zoals je wilt.” Toen liep hij weg, de steeg uit, zonder om te kijken.',
      'Tala bleef staan tot ze zijn voetstappen niet meer hoorde. Pas daarna merkte ze dat haar handen trilden.',
      'Ze deed de deur open.',
      'Binnen was het donker en koel. De kruiken stonden in rijen van tien, met stro ertussen zodat ze niet tegen elkaar sloegen. Tien rijen van tien. Elke ochtend telde ze ze. Dat had haar vader haar geleerd toen ze zes was, en toen was het nog een spelletje.',
      'Ze begon links en telde hardop, zoals altijd.',
      'Bij de achterste rij hield ze op.',
      'Er stonden er negen.',
      'Tala telde opnieuw. Negen. Ze liep om de rij heen, bukte, keek achter het stro. Negen.',
      'Gisteren had ze ook iets vreemds gezien. Twee kruiken die verkeerd stonden, met de handvatten naar de muur in plaats van naar het pad. Ze had gedacht: dat heeft iemand haastig gedaan. Ze had ze rechtgezet en er niet meer aan gedacht.',
      'Nu stond er één minder.',
      'Ze ging in de deuropening zitten met haar rug tegen de post en haar knieën opgetrokken, en probeerde te bedenken wat ze moest doen.',
      'Ze kon het aan haar moeder vertellen. Maar haar moeder had deze maand al genoeg: een zieke man boven, een huis vol mensen die betaald moesten worden, en een oogst die over drie weken naar de haven moest.',
      'Ze kon het aan Marcus vertellen. Marcus was de opzichter. Dat was zijn werk.',
      'Tala keek naar de steeg waar hij was verdwenen.',
      'Nee.',
      '“Je zit in de weg,” zei een stem.',
      'Ze schrok op. Voor haar stond een jongen van ongeveer haar leeftijd, met een leren schort voor en zijn armen vol takkenbossen. Zijn handen zaten onder het zwart.',
      '“Ik zit niet in de weg,” zei Tala. “Dit is mijn deur.”',
      '“Dan zit je in de weg van je eigen deur.”',
      'Hij heette Yidir en hij werkte bij de smidse aan het eind van de straat. Tala kende hem van gezicht zoals je iedereen in Walili van gezicht kende, en verder niet.',
      'Ze stond op om hem erlangs te laten. Hij liep niet door.',
      '“Je telt elke ochtend,” zei hij.',
      '“Hoe weet jij dat?”',
      '“Ik loop elke ochtend langs.”',
      'Tala aarzelde. Toen zei ze het toch, omdat het eruit moest en omdat hij er nu eenmaal stond.',
      '“Er is er één weg.”',
      'Yidir zette zijn takkenbossen op de grond.',
      '“Eén?” zei hij. “Dan heb je geluk gehad. Bij ons zijn er zes ijzeren staven weg.”',
    ],
  },
  {
    nummer: 3,
    titel: 'Hoe je olie maakt',
    tekst: [
      'Die middag stond Tala bij de pers, zoals elke dag in de oogst.',
      'De pers was een uitgeholde steen zo groot als een kar, met een ronde steen erin die door een ezel werd rondgetrokken. De olijven gingen erin, werden gekraakt, en wat eruit kwam was een dikke bruine massa die naar niets leek.',
      'Dat was het deel dat vreemden altijd teleurstelde. “Is dát olie?” vroegen ze dan. Nee. Dat was het begin.',
      'De massa ging in ronde matten van gevlochten riet. Die matten werden op elkaar gestapeld onder de balkpers, en dan draaiden twee mannen aan de schroef, langzaam, alsof ze de tijd hadden. Onder de stapel liep een geul.',
      'Daar kwam het uit.',
      'Eerst water, troebel en vies. Dan, na een tijd, iets anders. Iets dat op het water bleef drijven en groener was dan alles wat Tala kende.',
      'Haar vader had haar de eerste keer bij haar nek gepakt en haar hoofd erboven gehouden. “Ruik,” had hij gezegd. “Dat is het. Als het zó ruikt, is het goed. Als het naar niets ruikt, heb je te lang gewacht.”',
      'Ze had toen gelogen dat ze het rook. Nu rook ze het echt.',
      'Walili leefde hiervan. Niet van de mozaïekvloeren waar bezoekers over liepen, niet van de zuilen op het plein, niet van de stenen straten. Van dit. Van geperste olijven die in kruiken gingen, op karren naar de kust, en op schepen naar plekken waarvan Tala alleen de namen kende.',
      'Ze lette op de geul en op de matten en op de ezel, en ondertussen dacht ze aan negenennegentig kruiken.',
      'Zes ijzeren staven, had Yidir gezegd. Uit de smidse.',
      'IJzer was duur. Olie was duur. En allebei gingen ze in dezelfde richting de stad uit: over de weg naar de haven.',
      '“Tala.” Een van de mannen wees naar de geul. “Hij loopt over.”',
      'Ze schoot naar voren en schoof de kom eronder, te laat. Een straal olie liep over de steen en verdween tussen de voegen.',
      'Een vinger dik, misschien twee. Genoeg voor een gezin voor een week.',
      'De man zei er niets van. Dat maakte het erger.',
    ],
  },
  {
    nummer: 4,
    titel: 'Wat een opzichter mag',
    tekst: [
      'Marcus kwam terug op de derde dag, en hij kwam niet alleen.',
      'Tala zag hem de binnenplaats op lopen met twee mannen achter zich. Haar moeder kwam naar buiten, veegde haar handen af aan haar jurk, en ging precies tussen hem en de deur staan.',
      '“Vrede,” zei Marcus.',
      '“Vrede,” zei haar moeder, op de toon waarop je dat zegt als je het niet meent.',
      '“Je man is ziek.”',
      '“Mijn man rust.”',
      '“Drie weken,” zei Marcus. “Over drie weken gaat de oogst naar de haven, en de stad rekent op wat er in dit huis staat. Ik moet weten dat het er is.”',
      '“Het is er.”',
      '“Ik wil het zien.”',
      'Er viel een stilte. Tala stond in de deuropening van de keuken en durfde zich niet te bewegen.',
      'Haar moeder zei: “Je mag kijken. Mijn dochter doet open.”',
      'Tala liep de binnenplaats over onder de ogen van vijf mensen. Ze haalde het koord over haar hoofd, stak de sleutel in het slot en duwde de deur open.',
      'Marcus ging naar binnen. Hij liep langs de rijen, langzaam, met zijn handen op zijn rug. Bij de achterste rij bleef hij staan.',
      'Tala hield haar adem in.',
      '“Negenennegentig,” zei Marcus.',
      'Hij draaide zich om en keek haar moeder aan.',
      '“Er hoort er honderd te staan.”',
      'Haar moeder verstijfde. Tala zag het aan haar schouders.',
      '“Dan is er één gebroken,” zei ze.',
      '“Dan lagen er scherven.” Marcus spreidde zijn handen. “Ik zie geen scherven. Ik zie stro dat is rechtgetrokken.”',
      'Hij wachtte even, precies lang genoeg.',
      '“Ik zeg niet dat jullie stelen,” zei hij toen. “Ik zeg dat een kind van elf de sleutel heeft van honderd kruiken, en dat er vandaag negenennegentig staan. Dat zeg ik. En dat zal ik ook zeggen op het plein.”',
      'Hij liep de deur uit en langs Tala heen alsof ze een paal was.',
      'Toen hij weg was, ging haar moeder op de rand van de put zitten. Ze zei heel lang niets.',
      '“Mama,” zei Tala. “Ik heb hem niet—”',
      '“Ik weet het.”',
      '“Ik heb hem geteld op maandag en toen waren het er nog—”',
      '“Tala.” Haar moeder keek op. Haar ogen waren rood. “Ik weet het. En dat helpt ons niets.”',
    ],
  },
  {
    nummer: 5,
    titel: 'De smidse',
    tekst: [
      'Yidir zat op een omgekeerde emmer voor de smidse en schuurde een scharnier.',
      '“Je had gelijk,” zei Tala.',
      '“Dat zeggen mensen zelden tegen mij,” zei Yidir zonder op te kijken. “Waarover?”',
      '“Over dat het niet één kruik was.”',
      'Nu keek hij wel op.',
      'Tala ging naast hem op de drempel zitten en vertelde het. Over Marcus, over negenennegentig, over wat hij op het plein zou gaan zeggen. Yidir luisterde zoals hij alles deed: alsof hij ondertussen ergens anders aan dacht, maar hij miste niets.',
      '“En jouw ijzer?” vroeg ze.',
      '“Zes staven. Mijn meester denkt dat hij zich vergist heeft in het tellen.” Yidir haalde zijn schouders op. “Mijn meester vergist zich nooit in het tellen.”',
      '“Wanneer?”',
      '“Vorige week. En de week daarvoor drie.”',
      'Tala trok haar knieën op.',
      '“Wat gaat er uit de stad?” vroeg ze. “Elke dag, bedoel ik.”',
      'Yidir dacht na.',
      '“Karren,” zei hij. “Olie, graan, huiden, ijzer. Alles gaat over de weg naar het noorden. Er staat een wachtpost bij de poort. Daar wordt alles opgeschreven.”',
      '“Door wie?”',
      'Yidir keek haar aan.',
      '“Door de opzichter,” zei hij.',
      'Ze zeiden allebei een tijdje niets.',
      '“Dat bewijst niets,” zei Tala uiteindelijk.',
      '“Nee.”',
      '“Als ik dat zeg, zeggen ze dat een kind van elf een man beschuldigt omdat hij haar niet aardig vindt.”',
      '“Ja,” zei Yidir. “Dat zeggen ze.”',
      'Hij legde het scharnier weg.',
      '“Dus je hebt iets nodig wat ze niet kunnen wegpraten.”',
      '“Zoals?”',
      '“Zoals zien wat er ’s nachts door die poort gaat.”',
      'Tala keek naar hem. Hij keek terug, en voor het eerst sinds ze hem kende, lachte hij.',
    ],
  },
  {
    nummer: 6,
    titel: 'Wat er ’s nachts door de poort gaat',
    tekst: [
      'Ze lagen op het dak van het badhuis, plat op hun buik, met hun kin op hun armen.',
      'Het dak was warm van de dag. Onder hen lag de straat die naar de noordelijke poort liep, breed genoeg voor twee karren naast elkaar. Bij de poort brandde één lamp.',
      '“Hoe lang nog?” fluisterde Tala.',
      '“Weet ik niet.”',
      '“Je zei dat er ’s nachts karren gaan.”',
      '“Ik zei dat ik dácht dat er ’s nachts karren gaan.”',
      'Tala zuchtte en legde haar hoofd op haar arm.',
      'De sterren waren die nacht ongelooflijk. In de stad zag je ze half, door het licht en de rook, maar hier boven waren het er zoveel dat het onrustig werd.',
      '“Mijn oma zegt dat ze een kaart zijn,” zei Yidir.',
      '“De sterren?”',
      '“Ja. Als je ze kunt lezen, kun je overal komen. Ze zegt dat haar familie zo van de woestijn naar hier is gelopen.”',
      '“Kun jij ze lezen?”',
      '“Nee,” zei Yidir. “Niemand heeft het me geleerd.”',
      'Toen hoorden ze het.',
      'Een kar. Geen twee ezels, geen paarden — één ezel, langzaam, en het geluid van hout dat kraakt onder gewicht.',
      'Tala schoof naar de rand.',
      'De kar kwam uit een zijstraat. Er liepen twee mannen naast, allebei met een doek om hun hoofd. Op de kar lag stro, en onder het stro stond iets dat rond was.',
      'Bij de poort stopte de kar.',
      'Uit het wachthuisje kwam een man met een lamp. Hij liep niet naar de kar toe. Hij liep naar de mannen, praatte kort met ze, en schreef iets op een tablet.',
      'Toen tilde hij de slagboom op.',
      'De kar reed de nacht in.',
      'Tala liet haar adem los. Ze had niet gemerkt dat ze hem inhield.',
      '“Hij heeft niet gekeken,” zei ze. “Hij heeft niet onder het stro gekeken.”',
      '“Nee.”',
      '“Dat is—”',
      '“Dat is nog steeds niets,” zei Yidir. “Dat is een man die niet goed genoeg kijkt. Daar hangt niemand voor.”',
      'Hij had gelijk, en dat wist Tala ook.',
      'Maar toen de kar de bocht om ging, gebeurde er iets. De ezel schrok van iets in het donker, trok opzij, en de kar sloeg met één wiel over de stoeprand.',
      'Er viel iets van de kar af.',
      'Het rolde, kwam tot stilstand tegen de muur, en bleef daar liggen.',
      'Een kruik.',
      'Een van de mannen vloekte, kwam teruglopen, raapte hem op en zette hem terug onder het stro. De kar reed verder.',
      'Maar Tala had gezien wat erop stond.',
      'Op de schouder van elke kruik uit hun huis zette haar vader een teken in de klei voordat hij gebakken werd. Acht punten. Een ster.',
      'Ze pakte Yidirs arm zo hard vast dat hij siste.',
      '“Die is van ons,” zei ze.',
    ],
  },
  {
    nummer: 7,
    titel: 'Wat je zegt en wat ze horen',
    tekst: [
      'De volgende ochtend ging Tala naar het plein.',
      'Ze had er de hele nacht over nagedacht, of in elk geval over de helft ervan; de andere helft had ze geslapen zonder het te willen. Ze wist wat ze ging zeggen. Ze had het drie keer geoefend tegen de muur van haar kamer.',
      'Op het plein, onder de zuilen, hield de raad zitting. Dat betekende: vijf mannen op stenen banken, een schrijver ernaast, en iedereen die iets te klagen had eromheen.',
      'Marcus stond er al.',
      'Tala wachtte tot een man over een muur en een buurman was uitgepraat. Toen stapte ze naar voren.',
      '“Ik wil iets zeggen,” zei ze.',
      'Vijf mannen keken op. Een van hen, de oudste, met een gezicht als een gedroogde vijg, boog zich naar voren.',
      '“Van wie ben jij er een?”',
      '“Van Yuba, de perser. Uit de Zuilenstraat.”',
      '“Die is ziek.”',
      '“Ja,” zei Tala. “Daarom sta ik hier.”',
      'Ze vertelde het. Over de kruik die weg was, en de dag erna nog een. Over de kar in de nacht en de man die de slagboom optilde zonder onder het stro te kijken. Over de kruik die eraf viel en over het teken met de acht punten.',
      'Ze vertelde het precies zoals ze het geoefend had, en terwijl ze het deed, hoorde ze het zelf ook.',
      'Ze hoorde hoe het klonk.',
      'Een kind. Een dak. Het donker. Een teken dat niemand anders had gezien.',
      'Toen ze klaar was, was het even stil. Toen zei Marcus, heel rustig: “Mag ik?”',
      'De oudste knikte.',
      '“Het meisje heeft gelijk dat er kruiken missen,” zei Marcus. “Dat heb ik zelf geteld, eergisteren, in hun eigen opslag. Negenennegentig van de honderd. Ik heb het toen ook gezegd.”',
      'Hij spreidde zijn handen, zoals hij dat deed.',
      '“Wie heeft de sleutel van die deur?”',
      'Niemand zei iets.',
      '“Zij,” zei Marcus. “Een kind van elf. En nu er één weg is, is het een kar in de nacht geweest. Een kar die alleen zij gezien heeft.”',
      'De oudste van de raad keek Tala aan, en zijn blik was niet onvriendelijk. Dat was nog het ergste.',
      '“Kind,” zei hij. “Ga naar huis. Zorg voor je vader.”',
      'Tala stond op het plein met haar handen langs haar lichaam en haar oren gloeiend, en om haar heen begon iedereen weer te praten over een muur en een buurman.',
    ],
  },
  {
    nummer: 8,
    titel: 'De brand',
    tekst: [
      'De brand begon vier dagen later, en hij begon niet bij hen.',
      'Tala werd er wakker van. Niet van licht en niet van geschreeuw — van geluid. Een diep, zacht gebrul, alsof er ergens heel dichtbij iemand heel lang uitademde.',
      'Ze was bij het raam voordat ze wakker was.',
      'Aan de overkant van de straat, twee huizen verder, stond de opslag van Quintus in brand. Quintus perste ook olie. Zijn kruiken stonden in een ruimte onder zijn huis, en daar kwam nu vuur uit het raam, plat, en niet omhoog zoals vuur hoort te doen.',
      'Dat komt door de olie, wist Tala later. Olie brandt anders.',
      'Er was al geschreeuw. Er waren al mensen op straat met emmers en dekens, en iemand sloeg met een stok tegen de bronzen plaat bij de put, en Tala rende de trap af zonder schoenen.',
      'Haar moeder greep haar bij haar arm in de deuropening.',
      '“Niet die kant op.”',
      '“Maar—”',
      '“Tala.” Haar moeder hield haar vast met beide handen. “Onze deur. Nú.”',
      'En Tala begreep het.',
      'Als het overslaat, dan naar hen. Honderd kruiken — negenennegentig — met olie, achter een houten deur, tegen dezelfde muur.',
      'Ze rende naar de opslag, haalde het koord over haar hoofd en stak de sleutel in het slot. Haar handen waren zo nat dat het brons wegdraaide. De derde keer lukte het.',
      'De deur ging open. De koelte kwam haar tegemoet, en de geur.',
      'Achter haar begon de hele straat kruiken te dragen.',
      'Ze droegen ze naar de binnenplaats, naar de put, naar de straat, overal heen waar geen muur brandde. De buren droegen mee, mensen die ze nauwelijks kende, mensen die haar vader nooit gesproken had. Iemand had een ladder. Iemand gooide dekens in het water van de put en gaf ze door.',
      'Tala droeg tot haar armen niet meer wilden en toen droeg ze nog.',
      'Bij de zeventigste kruik zag ze Yidir. Hij kwam met vier anderen van de smidse en ze sleepten iets mee dat op een lange haak leek.',
      'Bij de vijfentachtigste ging het dak van Quintus’ opslag naar binnen.',
      'Bij de laatste stond de zon al bijna op.',
      'Er was toen geen vuur meer. Er was alleen rook die laag over de straat hing, en tweehonderd mensen die stonden te kijken zonder iets te zeggen, en zwarte handen, en ergens een kind dat huilde.',
      'Tala zat op de stoep tegen haar moeder aan.',
      'En daarom zag zij als enige de man die uit de steeg naast Quintus’ huis kwam lopen, tegen de stroom in, met zijn mantel over zijn arm in plaats van om zijn schouders.',
      'De mantel was rood.',
    ],
  },
]
