import type { Hoofdstuk } from './sleutels'

/** Deel 11 — Het eerste land dat ja zei. Tanger en Salé, 1777. */
export const DEEL11_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Brieven', tekst: [
    'Brahim was veertien en hij schreef brieven over die hij niet begreep.',
    'Dat was zijn werk. De havenschrijver van Tanger kreeg meer post dan hij aankon, en Brahim had een nette hand, en dus zat hij van zonsopgang tot het middaggebed aan een tafel bij het raam brieven te kopiëren in drie talen waarvan hij er één goed kende.',
    'Het meeste was saai. Vrachtbrieven. Klachten over tol. Een kapitein die zei dat hij bestolen was door een andere kapitein.',
    'Maar soms zat er iets tussen.',
    'In dat jaar — 1777 — begon er iets terug te komen in de stapel dat Brahim opviel omdat hij het niet kon thuisbrengen.',
    'Schepen die niet onder een vlag voeren die iemand kende.',
    'Ze zeiden dat ze uit Amerika kwamen.',
  ] },
  { nummer: 2, titel: 'Een land dat niemand kent', tekst: [
    'De havenschrijver heette Si Lhabib en hij was oud en hij had overal een mening over.',
    '“Amerika,” zei Brahim.',
    '“Engelse koloniën,” zei Si Lhabib zonder op te kijken.',
    '“Ze zeggen dat ze geen koloniën meer zijn.”',
    '“Dat zeggen ze, ja.”',
    'Dat was de hele kwestie, en Brahim begreep hem pas toen hij hem drie keer had opgeschreven.',
    'Er was aan de andere kant van de oceaan een oorlog bezig. Dertien Engelse koloniën hadden gezegd dat ze een eigen land waren. Engeland vond van niet.',
    'En zolang niemand anders zei dat ze een land waren, waren hun schepen geen schepen van een land maar schepen van niemand.',
    'Een schip van niemand mag iedereen aanhouden.',
    '“Wat willen ze dan van ons?” vroeg Brahim.',
    'Si Lhabib legde eindelijk zijn pen neer.',
    '“Dat wij als eerste ja zeggen,” zei hij.',
  ] },
  { nummer: 3, titel: 'Wat een handtekening is', tekst: [
    'Op 20 december 1777 liet sultan Mohammed ben Abdallah een verklaring uitgaan naar alle consuls in Tanger.',
    'Brahim heeft hem overgeschreven. Zeven keer, in zeven talen, want elke consul kreeg er een.',
    'Er stond in dat de havens van Marokko openstonden voor schepen van alle landen die met Marokko in vrede waren — en in de lijst van die landen stonden de Verenigde Staten van Amerika.',
    'Meer was het niet. Eén zin in een lijst.',
    'Brahim vond het teleurstellend. Hij had iets plechtigs verwacht.',
    '“Dit is het?” vroeg hij.',
    'Si Lhabib keek hem aan op de manier waarop oude mannen naar jonge kijken.',
    '“Jongen,” zei hij. “Er is daar een land dat vecht om te bestaan. Elke haven waar hun schepen niet mogen komen, is een deur die dicht is. Wij hebben er één opengezet.”',
    'Hij tikte op het papier.',
    '“Dit is geen zin in een lijst. Dit is het eerste land ter wereld dat zegt: jullie bestaan.”',
    'Brahim heeft het die avond nog een keer overgeschreven, voor zichzelf, en die kopie heeft hij zijn hele leven bewaard.',
  ] },
  { nummer: 4, titel: 'Negen jaar later', tekst: [
    'Er gebeurde daarna jarenlang niets, en dat is ook geschiedenis.',
    'Er kwam geen antwoord. Er kwam geen gezant. Amerika had het druk met een oorlog en met zichzelf, en brieven deden er maanden over.',
    'De sultan werd ongeduldig. In 1784 liet hij een Amerikaans schip aanhouden bij Tanger — niet om het te houden, maar om ervoor te zorgen dat iemand een brief zou schrijven.',
    'Dat werkte.',
    'In 1786 kwam er een verdrag. Het Marokkaans-Amerikaanse vriendschapsverdrag, getekend in Marrakech, ondertekend aan de andere kant door mannen wier namen op scholen in Amerika worden geleerd.',
    'Dat verdrag geldt nog steeds.',
    'Het is het oudste ononderbroken verdrag dat de Verenigde Staten hebben, met welk land ook ter wereld. Het is nooit verbroken. Het is nooit vervangen.',
    'Brahim was toen drieëntwintig en zelf havenschrijver, want Si Lhabib was gestorven, en hij heeft het afschrift met eigen hand gemaakt.',
  ] },
  { nummer: 5, titel: 'Het huis in Tanger', tekst: [
    'In 1821 gaf de sultan een gebouw in de medina van Tanger cadeau aan de Verenigde Staten.',
    'Dat huis staat er nog.',
    'Het is het oudste Amerikaanse overheidsgebouw buiten Amerika, en het enige dat een nationaal monument is terwijl het op vreemde bodem staat. Er zit nu een museum in.',
    'Brahim heeft het nog meegemaakt. Hij was achtenvijftig.',
    'Hij is er gaan kijken op de dag dat de vlag werd gehesen, met zijn kleinzoon aan de hand, en hij heeft hem verteld dat hij de eerste zin had overgeschreven, zeven keer, in zeven talen.',
    'Zijn kleinzoon geloofde hem half.',
  ] },
  { nummer: 6, titel: 'In de kist met papieren', tekst: [
    'De sleutel kwam met een Amerikaans schip terug.',
    'Dat klinkt te mooi en het is toch wat er is gebeurd: hij was in 1778 uit Essaouira meegegaan, en hij kwam in 1786 in Tanger aan land in een kist met documenten, tussen het zegellak en de reservepennen.',
    'De klerk die de kist uitpakte wist niet wat het was en legde het op de plank.',
    'Toen het consulaat in het geschonken huis trok, ging de plank mee.',
    'Daar heeft hij honderd jaar gelegen tussen dingen die niemand durfde weg te gooien en die niemand nodig had.',
    'Tot iemand in de twintigste eeuw de kelder opruimde.',
  ] },
]
