import type { Hoofdstuk } from './sleutels'

/** Deel 4 — De stad die er nog niet was. Marrakech, rond 1070. */
export const DEEL4_HOOFDSTUKKEN: Hoofdstuk[] = [
  { nummer: 1, titel: 'Niets', tekst: [
    'Het eerste wat Isli zag toen ze aankwamen, was niets.',
    'Dat klinkt als een grap en dat was het niet. Er was een vlakte. Er was gras dat in augustus geel was. Er waren palmen in de verte en bergen achter de palmen, met sneeuw erop, in de zomer, wat Isli nog steeds niet geloofde ook al keek hij ernaar.',
    'En er waren geen huizen.',
    '“Hier?” zei hij.',
    '“Hier,” zei zijn oom.',
    'Isli was twaalf en hij dreef kamelen, samen met zijn oom, en ze kwamen uit het zuiden — van achter de bergen, waar het zand begint. Hun werk was simpel: iets ergens vandaan halen en ergens anders neerzetten.',
    'Deze keer was het steen, en de plek waar het neer moest was een vlakte zonder naam.',
    'Er lagen al stapels. Er stonden al tenten, honderden, in rijen. Er waren mannen die geulen groeven in een patroon dat van dichtbij nergens op sloeg.',
    '“Wat wordt het?” vroeg Isli.',
    'Zijn oom spuwde in het zand.',
    '“Een stad, zeggen ze.”',
    '“Waarom hier?”',
    '“Omdat iemand het gezegd heeft.”',
    'Dat was geen antwoord, en Isli bleef ernaar zoeken, en hij vond het pas toen iemand het hem uitlegde die er verstand van had.',
  ] },
  { nummer: 2, titel: 'De vrouw die de vraag stelde', tekst: [
    'Ze was niet wat hij verwachtte, en inmiddels had hij moeten weten dat niemand ooit is wat je verwacht.',
    'Hij zag haar bij de geulen. Ze stond met drie mannen te praten die tekeningen vasthielden, en ze stelde vragen. Dat was het eerste wat hem opviel: ze zei bijna niets, ze vroeg.',
    '“Hoe diep?”',
    '“Vijf el.”',
    '“En in augustus?”',
    'Stilte.',
    '“In augustus,” zei ze nog een keer.',
    'De man met de tekening keek naar zijn voeten.',
    'Ze heette Zaynab. Dat hoorde Isli later. De vrouw van de man die het bevel gaf, en volgens de kooplieden degene die wist hoe geld werkt.',
    'Die avond kwam ze bij de kamelen. Ze liep langs de dieren zoals iemand langs dieren loopt die weet hoe ze staan als ze te zwaar geladen zijn.',
    '“Waar kom je vandaan?” vroeg ze aan Isli.',
    'Hij noemde zijn dorp. Ze knikte alsof ze het kende, en misschien was dat zo.',
    '“Waarom hier?” vroeg Isli, voordat hij bedacht dat je dat niet vraagt.',
    'Zaynab keek hem aan.',
    'Toen wees ze naar de bergen.',
    '“Daar ligt water,” zei ze. “Het hele jaar. In de sneeuw.” Ze wees naar de vlakte. “Hier is niets. Maar hier kruisen de wegen: uit het zuiden het goud, uit het noorden het graan, uit het oosten de mensen.”',
    '“En het water dan?”',
    '“Dat halen we hierheen,” zei ze. “Onder de grond.”',
  ] },
  { nummer: 3, titel: 'De rivier die je niet ziet', tekst: [
    'Het systeem heette khettara en Isli heeft er een halve zomer aan meegewerkt, en hij vond het het knapste wat hij ooit had gezien.',
    'Het idee is eenvoudig genoeg om aan een kind uit te leggen en moeilijk genoeg om er honderden mannen jarenlang aan te laten werken.',
    'Aan de voet van de bergen zit water in de grond. Je graaft daar een put. Dan graaf je een stukje verderop nog een put, iets minder diep. Dan nog een. En onder de grond verbind je ze allemaal met een gang die héél licht afloopt.',
    'Het water loopt vanzelf. Geen emmer, geen dier, geen pomp. Het loopt kilometers ondergronds en komt aan de andere kant tevoorschijn in een stad die er zonder dat water niet had kunnen staan.',
    'En het verdampt niet, want de zon komt er niet bij.',
    'Isli bracht steen naar de putten. Hij klom er een keer in, tegen de regels, en stond in het donker in een gang waar water langs zijn enkels liep.',
    'Boven hem, door het putgat, was een cirkel blauw.',
    'Hij bleef daar langer staan dan verstandig was.',
  ] },
  { nummer: 4, titel: 'De naam', tekst: [
    'De stad kreeg haar naam voordat ze bestond, en daar heeft Isli altijd om moeten lachen.',
    'Er werd over gepraat bij de vuren. Het meest gehoorde verhaal was dat het uit het Amazigh kwam: *mur akush*, het land van God. Er waren er ook die zeiden dat het iets anders betekende en dat zij het beter wisten.',
    'Wat Isli wel zeker weet, is dat er die zomer al mensen waren die zeiden “ik ga naar Marrakech” terwijl er niets stond dan tenten en geulen.',
    'Een naam gaat sneller dan muren.',
    'In de tweede zomer stond er een muur. In de derde stonden er huizen binnen die muur, en een markt, en een moskee waar de mannen uit het kamp naartoe gingen op vrijdag in plaats van op het zand.',
    'Isli bracht nog steeds steen.',
    'Zijn oom rekende uit dat ze in drie jaar meer verdiend hadden dan in de tien jaar daarvoor, en hij zei dat ze moesten stoppen nu het goed was, en dat deden ze niet.',
  ] },
  { nummer: 5, titel: 'Tamghart', tekst: [
    'Isli had zesentwintig kamelen en hij hield van er drie.',
    'Dat is eerlijker dan zeggen dat hij van ze allemaal hield. Een kameel is geen hond. De meeste kamelen zijn een werktuig met een slecht humeur, en dat is niet erg, want jij bent voor hen ook niet meer dan dat.',
    'Maar er zijn er altijd een paar.',
    'De oudste heette Tamghart, wat oude vrouw betekent, en ze was inderdaad oud. Zijn oom had haar gekocht toen Isli vier was.',
    'Ze liep achteraan. Ze liep altijd achteraan, en ze kwam altijd aan.',
    'In de tweede zomer ging het mis met haar voet. Een steen, of een doorn, of iets wat niemand zag — dat weet je bij kamelen pas als het te laat is.',
    'Ze liep drie dagen mank en toen liep ze niet meer.',
    'Zijn oom zei wat je op zo’n moment zegt, en het klopte allemaal: er zijn vijfentwintig andere, we hebben een lading, we zijn twee dagen van de vlakte.',
    'Isli bleef bij haar.',
    'Dat was ongehoorzaam en het was dom en hij had geen water voor twee dagen.',
    'Zijn oom kwam terug. Dat had Isli niet verwacht, en het is het enige moment in dit boek waarop hij gehuild heeft.',
    'Ze hebben Tamghart op een slee van stokken de laatste twaalf kilometer getrokken, met twee kamelen ervoor, en het ging zo langzaam dat een man te voet ze voorbijliep.',
    'Ze is nog vier jaar blijven leven op de vlakte bij Marrakech, waar ze niets meer deed dan eten en in de weg staan.',
    'Zijn oom heeft er nooit iets over gezegd. Dat was zijn manier.',
    'Isli heeft er zijn hele leven aan teruggedacht als aan het moment waarop hij begreep wat voor man zijn oom was, en dat je dat van mensen soms pas weet als het ze iets kost.',
  ] },
  { nummer: 6, titel: 'Aghmat', tekst: [
    'Er was al een stad. Dat is het rare aan dit verhaal.',
    'Een dag lopen naar het zuiden, tegen de bergen aan, lag Aghmat. Daar was de markt, daar was het bestuur, daar woonden de mensen van wie de karavanen kwamen. Aghmat was rijk en oud en het werkte.',
    'En ze gingen weg.',
    'Isli heeft het in het begin niet begrepen, en hij was niet de enige. Bij de vuren werd erover gemopperd door mannen die niet snapten waarom je een stad verlaat die er staat om er een te bouwen die er niet staat.',
    '“In Aghmat is water,” zei iemand. “Hier is zand.”',
    '“In Aghmat zijn muren.”',
    '“In Aghmat zijn huizen met daken.”',
    'Isli heeft het antwoord pas jaren later gehoord, en niet van iemand belangrijks.',
    'Een oude kameeldrijver uit het oosten legde het hem uit met zijn stok in het zand.',
    'Hij tekende de bergen. Hij tekende Aghmat ertegenaan.',
    '“Waar kun je heen vanuit Aghmat?”',
    '“De bergen over. Of terug.”',
    'Toen tekende hij een punt noordelijker, midden op de vlakte.',
    '“En hier?”',
    'Isli keek ernaar.',
    'Naar het zuiden: de passen, de woestijn, het goud. Naar het noorden: Fes, de kust, de zee. Naar het westen: de oceaan. Naar het oosten: alles.',
    '“Overal,” zei hij.',
    'De oude man veegde het zand glad.',
    '“Een stad tegen een berg is een stad met zijn rug tegen de muur,” zei hij. “Een stad op de vlakte is een stad waar alle wegen langskomen.”',
    'Dat is waarom Marrakech er is en waarom Aghmat het niet is geworden.',
    'Aghmat bestaat nog. Er wordt opgegraven. Er staat een graf van een koning die uit Andalusië werd verbannen en daar is gestorven, en er komen mensen naar kijken, en die rijden er in een uur heen vanuit Marrakech.',
  ] },
  { nummer: 7, titel: 'Het goud dat hij nooit zag', tekst: [
    'Twee keer per jaar kwam er een karavaan uit het zuiden waar iedereen van opkeek, en Isli heeft er in vier jaar acht gezien.',
    'Ze kwamen uit een land dat zo ver weg was dat de mannen die erover praatten het zelf nooit hadden gezien. Ze waren twee maanden onderweg geweest, of drie. Ze hadden onderweg mensen verloren; dat hoorde erbij en werd genoemd zoals je het weer noemt.',
    'Ze brachten zout naar het zuiden en ze kwamen terug met goud.',
    'Isli heeft dat goud nooit gezien.',
    'Dat is het punt. Er kwamen zeshonderd kamelen de vlakte op en er lag ergens in die zeshonderd ladingen iets waar het hele land van leefde, en een jongen die de dieren drenkte kwam er niet bij in de buurt.',
    'Wat hij wel zag waren de mannen.',
    'Ze waren donkerder dan hij. Ze spraken een taal die hij niet thuis kon brengen. Twee van hen droegen ijzeren ringen om hun enkels, en Isli heeft er later over nagedacht en is er nooit uitgekomen wat dat betekende.',
    'Sommigen bleven. Er zijn in die jaren mensen in Marrakech gaan wonen die uit Ghana kwamen, en uit het gebied dat nu Mali heet, en hun kleinkinderen waren gewoon mensen uit Marrakech.',
    'Zo is die stad gemaakt: uit mensen uit de bergen, mensen van de kust, mensen uit Andalusië en mensen uit het zuiden.',
    'Isli vroeg een keer aan een van de mannen hoe het daar was.',
    'De man dacht lang na, want hij zocht naar woorden in een taal die niet van hem was.',
    '“Groen,” zei hij. “En een rivier zo breed dat je de overkant niet ziet.”',
    'Isli, die was opgegroeid met wadi’s die elf maanden per jaar droog stonden, geloofde er niets van.',
    'Hij had ongelijk. Het is de Niger, en je ziet de overkant inderdaad niet.',
  ] },
  { nummer: 8, titel: 'De mannen die in de grond werkten', tekst: [
    'De khettara-gravers waren een apart soort mensen en de rest van het kamp liet ze met rust.',
    'Ze waren met een man of veertig. Ze werkten in ploegen van drie: één beneden in de gang, één in de put om de mand op te halen, één boven aan het touw.',
    'Ze aten apart. Niet omdat het moest, maar omdat ze het zo deden.',
    'Isli bracht ze steen en water, en hij keek naar ze zoals je naar iets kijkt wat je niet zou durven.',
    'De gang was zo breed als een man met zijn schouders ingetrokken. Hij liep soms twintig meter onder de grond. Boven je hoofd zat aarde die niet altijd aarde bleef.',
    'In de tweede zomer stortte er een stuk in bij de zevende put.',
    'Ze hebben twee dagen gegraven. De man die beneden zat heette Brahim en hij was tweeëntwintig, en ze hebben hem er levend uitgehaald, en dat was zo ongebruikelijk dat er die avond een schaap geslacht is.',
    'Hij is de week daarna weer naar beneden gegaan.',
    'Isli heeft hem gevraagd waarom.',
    'Brahim keek hem aan met het gezicht van iemand die de vraag niet snapt.',
    '“Het is mijn werk,” zei hij.',
    '“Er is ander werk.”',
    '“Dit kan ik.”',
    'Later, toen Isli vijftig was en zijn eigen zoons zag kiezen wat ze deden, heeft hij dat gesprek nog vaak nagespeeld in zijn hoofd.',
    'Hij is er nooit uit gekomen of Brahim moedig was of dat hij gewoon niets anders wist, en hij is gaan vermoeden dat het bij de meeste dappere mensen allebei is.',
    'Die gangen liggen er nog. Onder Marrakech, onder de Palmeraie, onder land waar nu huizen staan. De meeste zijn droog. Een paar doen het nog.',
    'Er is geen naam van een graver bewaard gebleven. Van de stad wel.',
  ] },
  { nummer: 9, titel: 'De muur van aarde', tekst: [
    'Isli dacht dat de muur van steen zou zijn en dat was hij niet.',
    'Hij was van aarde.',
    'Dat vond hij in het begin een slecht plan en hij zei het hardop, wat hem een klap op zijn achterhoofd opleverde van een metselaar die dertig jaar met aarde werkte.',
    'Het heet tabia. Je maakt twee houten schotten, je zet ze op hun kant, je vult de ruimte ertussen met aarde en kalk en kiezel, en dan sla je erop.',
    'Dat is het. Je slaat erop.',
    'Met stampers, met zijn vieren, in een ritme, uren achter elkaar, tot de aarde zo hard is dat je er een mes op breekt. Dan haal je de schotten weg, zet je ze een stuk verder, en begin je opnieuw.',
    'Isli heeft er één zomer aan meegewerkt en hij heeft er zijn schouders aan bezeerd voor de rest van zijn leven.',
    'Wat hem bijbleef was het geluid.',
    'Vierhonderd mannen die tegelijk stampen, in de zon, in hetzelfde ritme, met een man die het tempo zong.',
    'Je hoorde het van een uur gaans.',
    'De muur die ze zo gemaakt hebben is negentien kilometer lang geworden en staat er in grote delen nog. Hij is rood, want de aarde daar is rood, en daarom heet Marrakech de rode stad.',
    'Niet vanwege een keuze. Vanwege de grond die er toevallig lag.',
    'Isli heeft dat later aan mensen uitgelegd die dachten dat het geverfd was.',
    '“Het is gewoon de grond,” zei hij dan.',
    'Ze geloofden hem meestal niet.',
  ] },
  { nummer: 10, titel: 'De eerste markt', tekst: [
    'De markt kwam voordat iemand een markt had bedacht.',
    'Dat is Isli’s lievelingsverhaal over die jaren, want het bewijst iets wat hij altijd is blijven geloven: dat een stad niet gebouwd wordt maar gebeurt.',
    'Het begon met een man met dadels.',
    'Hij kwam uit een dorp in het zuiden, hij had een ezel, en hij had gehoord dat er duizenden werklui op een vlakte zaten die niets te eten hadden dan wat er werd uitgedeeld. Hij ging op een kruispunt van twee geulen zitten en verkocht dadels.',
    'De week erna zat er iemand naast hem met brood.',
    'De week daarna een man met touw, want op een bouwplaats gaat touw kapot.',
    'Binnen twee maanden waren het er veertig. Er was een hoek waar je een mes kon laten slijpen. Er was een vrouw met thee. Er was een man die brieven schreef voor wie niet schrijven kon, en die het druk had, want de helft van het kamp kwam ergens anders vandaan.',
    'Niemand had toestemming gevraagd. Niemand had een plek aangewezen.',
    'Toen de stad er eenmaal stond, is er een plein gekomen op ongeveer die plek, en dat plein is er nog steeds, en er zitten nog steeds mensen thee te verkopen.',
    'Isli heeft daar op zijn negenentwintigste gestaan, tussen de mensen, en hij heeft geprobeerd uit te leggen aan een jongen die er werkte dat hij hier had gestaan toen er niets was.',
    'De jongen was beleefd en geloofde er niets van.',
    'Dat is het lot van iedereen die ergens bij was: je mag het één keer vertellen en daarna ben je een oude man met een verhaal.',
  ] },
  { nummer: 11, titel: 'Sneeuw', tekst: [
    'In de derde winter zag Isli sneeuw.',
    'Hij had er over gehoord. Iedereen uit het zuiden heeft erover gehoord en niemand gelooft het echt.',
    'Op een ochtend in januari werd het kamp wakker en stonden de bergen wit.',
    'Niet een beetje. Van de voet tot de top, over de hele lengte, honderd kilometer wit tegen een lucht die blauw was op een manier die zeer deed aan je ogen.',
    'Isli stond er een uur naar te kijken met een emmer in zijn hand.',
    'Zijn oom vond hem daar en zei niets, en ging naast hem staan, en toen stonden ze er met zijn tweeën.',
    '“Het smelt,” zei zijn oom uiteindelijk.',
    '“Wanneer?”',
    '“In het voorjaar.”',
    '“En dan?”',
    'Zijn oom wees naar de grond onder hun voeten, waar ergens op vijf meter diepte een gang liep die ze de zomer ervoor hadden helpen graven.',
    '“Dan komt het hier langs,” zei hij.',
    'Isli heeft daar zijn hele verdere leven over gedacht als over het moment waarop hij begreep waar hij aan meewerkte.',
    'Het water dat in die bergen als sneeuw valt, zakt de grond in, loopt maanden later ondergronds de vlakte op en komt tevoorschijn in een tuin in een stad.',
    'Niemand kan dat zien gebeuren. Het duurt te lang en het gaat onder de grond.',
    'Je kunt het alleen weten.',
  ] },
  { nummer: 12, titel: 'Wat hij achterliet', tekst: [
    'De sleutel kwam bij hem terecht op de manier waarop de meeste dingen bij mensen terechtkomen: per ongeluk en zonder dat iemand oplette.',
    'Hij kocht een zadeltas van een handelaar uit het noorden, tweedehands, omdat zijn eigen tas kapot was. Er zat van alles in dat de handelaar vergeten was eruit te halen: twee munten die niet meer golden, een stuk touw, en iets van brons met acht punten aan de kop.',
    'Isli hield het tegen het licht.',
    '“Waar is dit van?”',
    '“Weet ik veel,” zei de handelaar. “Uit Fes. Alles wat ik heb komt uit Fes.”',
    'Isli hield hem. Hij was mooi, en hij was warm in je hand, en hij deed hem denken aan de ster die zijn moeder in het deeg drukte voordat ze brood bakte.',
    'In de vierde zomer bouwden ze de poort aan de noordkant, en Isli hielp met de laatste lading steen.',
    'Terwijl de metselaars de bovenkant dichtzetten, deed hij iets wat hij nooit aan iemand heeft verteld.',
    'Hij legde de sleutel in de muur.',
    'Niet om hem te verstoppen. Hij dacht: ik heb hier vier jaar van mijn leven gelaten, en straks ga ik terug naar het zuiden en dan weet niemand meer dat ik er was.',
    'Zo weet de poort het.',
  ] },
  { nummer: 13, titel: 'Wat er van komt', tekst: [
    'Isli is later teruggekomen. Twee keer.',
    'De eerste keer was hij negenentwintig. Er woonden toen meer mensen in Marrakech dan in alle dorpen die hij kende bij elkaar. Er stonden tuinen waar hij geulen had gegraven. Het water uit de bergen kwam onder de grond aan en liep door de binnenhoven alsof het altijd zo was geweest.',
    'De tweede keer was hij oud en had hij een kleinzoon bij zich, en hij wees naar de noordelijke poort en zei: “Daar zit iets van mij in.”',
    'Zijn kleinzoon geloofde hem niet.',
    'Dat gaf niet.',
    'Wat er van gekomen is, staat er nog: een stad die uit niets is gebouwd op een kruispunt van wegen, met water dat van veertig kilometer verderop onder de grond wordt aangevoerd.',
    'En het land dat eromheen ligt heeft de naam van die stad gekregen. Marrakech werd in de talen van het noorden verbasterd tot Marokko — en zo heet het vandaag nog.',
    'Een muur is later afgebroken en weer opgebouwd, en de sleutel kwam vrij tussen het puin, en een metselaarsjongen nam hem mee naar het noorden omdat hij mooi was.',
    'Dat is niet zeker. Dat is wat een verhaal doet met een gat.',
  ] },
]
