import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, join, normalize, resolve, sep } from 'node:path'
import { getEnv } from '@/env'

/**
 * Object storage abstraction for private media.
 *
 * The MVP ships a local-disk adapter. `S3Storage` documents the interface a
 * production adapter has to satisfy; it deliberately throws rather than
 * pretending to work, so a misconfigured deployment fails loudly.
 */

export interface MediaStorage {
  readonly name: string
  put(key: string, data: Buffer, contentType: string): Promise<void>
  get(key: string): Promise<Buffer>
  delete(key: string): Promise<void>
  exists(key: string): Promise<boolean>
}

/** Keys are generated by us, but never trust one that came back from a request. */
export function assertSafeKey(key: string): void {
  // Letters, digits, and the separators our own key builder uses. `..` is
  // rejected outright so no key can walk out of the storage root.
  if (!/^[a-z0-9][a-z0-9/_.-]{0,180}$/i.test(key) || key.includes('..')) {
    throw new Error('Unsafe media key')
  }
}

export class LocalDiskStorage implements MediaStorage {
  readonly name = 'local'
  private readonly root: string

  constructor(root: string) {
    this.root = resolve(root)
  }

  private path(key: string): string {
    assertSafeKey(key)
    const full = resolve(join(this.root, normalize(key)))
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error('Unsafe media key')
    }
    return full
  }

  async put(key: string, data: Buffer): Promise<void> {
    const target = this.path(key)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, data, { mode: 0o600 })
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.path(key))
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true })
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.path(key))
      return true
    } catch {
      return false
    }
  }
}

export class S3Storage implements MediaStorage {
  readonly name = 's3'
  private fail(): never {
    throw new Error(
      'The S3 media adapter is not implemented in the MVP. Set MEDIA_DRIVER=local or implement S3Storage.',
    )
  }
  async put(): Promise<void> {
    this.fail()
  }
  async get(): Promise<Buffer> {
    this.fail()
  }
  async delete(): Promise<void> {
    this.fail()
  }
  async exists(): Promise<boolean> {
    this.fail()
  }
}

let storage: MediaStorage | null = null

export function getMediaStorage(): MediaStorage {
  if (!storage) {
    const env = getEnv()
    storage = env.MEDIA_DRIVER === 's3' ? new S3Storage() : new LocalDiskStorage(env.MEDIA_LOCAL_DIR)
  }
  return storage
}

/** Test seam. */
export function setMediaStorage(next: MediaStorage | null): void {
  storage = next
}
