import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is regenerated by Next on every build; linting a
    // generated file only ever produces noise.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'playwright-report/**',
      'test-results/**',
    ],
  },
  {
    rules: {
      // The seed and the studio pass Prisma models through as Json snapshots;
      // an explicit `unknown` cast at each site is noise, not safety.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
];

export default config;
