import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * A small, opinionated rule set. It is deliberately not exhaustive: the rules
 * that are here are the ones that would otherwise let a privacy or correctness
 * mistake through unnoticed.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/.expo/**',
      '**/playwright-report/**',
      '**/test-results/**',
      'packages/db/prisma/migrations/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      parserOptions: { ecmaVersion: 2023, sourceType: 'module' },
      globals: {
        console: 'readonly',
        process: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        __dirname: 'readonly',
        module: 'writable',
        require: 'readonly',
        jest: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      // A silently swallowed failure is how invented data gets shipped.
      'no-empty': ['error', { allowEmptyCatch: false }],
      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error', 'log'] }],
    },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx', '**/e2e/**'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
  {
    // Metro and the optional native-module probes are CommonJS by necessity:
    // an optional native module has to be resolved at runtime, not linked.
    files: ['apps/mobile/*.js', 'apps/mobile/src/native/**'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // Generated by the Next.js build.
    files: ['apps/web/next-env.d.ts'],
    rules: { '@typescript-eslint/triple-slash-reference': 'off' },
  },
);
