/**
 * Marokkaanse voornamen in Arabisch schrift.
 *
 * Met de hand nagekeken, en dat is de hele reden dat dit een lijst is en geen
 * omzetter. Latijn naar Arabisch automatisch omzetten gaat juist mis bij de
 * namen die ertoe doen — Mohamed, Aicha, Chaimae — en een verkeerd gespelde
 * naam van iemands kind is erger dan geen naam.
 *
 * De sleutels zijn kleingeschreven en ontdaan van accenten en streepjes;
 * `normaliseer` doet hetzelfde met wat iemand intypt. Staat een schrijfwijze
 * er niet bij, dan voeg je die toe als extra sleutel bij dezelfde naam —
 * Yasmine, Yasmin en Jasmine wijzen alle drie naar ياسمين.
 *
 * Wie zijn naam niet vindt, kan hem aanvragen. Dat is met opzet: honderd
 * namen die kloppen zijn meer waard dan tienduizend die soms fout zijn.
 */

/** Kleingeschreven, zonder accenten, streepjes of spaties. */
export const normaliseer = (naam: string): string =>
  naam.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z]/g, '')

export const NAMEN: Record<string, string> = {
  // ------------------------------------------------------------- jongens
  amir: 'أمير',
  abdelilah: 'عبد الإله',
  abdessamad: 'عبد الصمد',
  abdelhamid: 'عبد الحميد',
  abdelmajid: 'عبد المجيد',
  jalal: 'جلال',
  jad: 'جاد',
  lahcen: 'لحسن',
  mohcine: 'محسن', mohsine: 'محسن',
  mimoun: 'ميمون',
  mohamed: 'محمد', mohammed: 'محمد', muhammad: 'محمد', mhamed: 'محمد',
  ahmed: 'أحمد', ahmad: 'أحمد',
  youssef: 'يوسف', yousef: 'يوسف', yusuf: 'يوسف', youssouf: 'يوسف',
  omar: 'عمر', oumar: 'عمر',
  ali: 'علي',
  hamza: 'حمزة',
  bilal: 'بلال', bilel: 'بلال',
  anas: 'أنس',
  ayoub: 'أيوب', ayyoub: 'أيوب', ayub: 'أيوب',
  ilyas: 'إلياس', ilias: 'إلياس', elias: 'إلياس',
  adam: 'آدم',
  rayan: 'ريان', rayane: 'ريان', rayyan: 'ريان',
  zakaria: 'زكريا', zakariya: 'زكريا', zakariae: 'زكريا',
  mehdi: 'مهدي', mahdi: 'مهدي',
  ismail: 'إسماعيل', ismael: 'إسماعيل',
  ibrahim: 'إبراهيم', brahim: 'إبراهيم',
  idris: 'إدريس', idriss: 'إدريس', driss: 'إدريس',
  yassine: 'ياسين', yacine: 'ياسين', yassin: 'ياسين',
  younes: 'يونس', younis: 'يونس', youness: 'يونس',
  amine: 'أمين', amin: 'أمين',
  ayman: 'أيمن', aymen: 'أيمن',
  walid: 'وليد',
  soufiane: 'سفيان', sofiane: 'سفيان', sufyan: 'سفيان',
  achraf: 'أشرف', ashraf: 'أشرف',
  khalid: 'خالد', khaled: 'خالد',
  hicham: 'هشام', hisham: 'هشام',
  tarik: 'طارق', tariq: 'طارق', tarek: 'طارق',
  redouane: 'رضوان', ridouan: 'رضوان', ridwan: 'رضوان',
  jawad: 'جواد', jaouad: 'جواد',
  anouar: 'أنور', anwar: 'أنور',
  nabil: 'نبيل',
  karim: 'كريم',
  rachid: 'رشيد', rashid: 'رشيد',
  said: 'سعيد', saed: 'سعيد',
  hassan: 'حسن',
  hussein: 'حسين', houssein: 'حسين', houcine: 'حسين',
  mustapha: 'مصطفى', mustafa: 'مصطفى',
  abdellah: 'عبد الله', abdallah: 'عبد الله', abdullah: 'عبد الله',
  abderrahman: 'عبد الرحمن', abderrahmane: 'عبد الرحمن', abdurrahman: 'عبد الرحمن',
  abdelkarim: 'عبد الكريم',
  abdelaziz: 'عبد العزيز',
  abdelhak: 'عبد الحق',
  noureddine: 'نور الدين', nordin: 'نور الدين', nourdin: 'نور الدين',
  imad: 'عماد',
  adnan: 'عدنان', adnane: 'عدنان',
  marwan: 'مروان', marouane: 'مروان',
  mounir: 'منير', monir: 'منير',
  jamal: 'جمال', djamal: 'جمال',
  samir: 'سمير',
  sami: 'سامي',
  othman: 'عثمان', outman: 'عثمان', ousmane: 'عثمان',
  oussama: 'أسامة', osama: 'أسامة',
  reda: 'رضا', rida: 'رضا',
  saad: 'سعد',
  salim: 'سليم', selim: 'سليم',
  soulaiman: 'سليمان', souleiman: 'سليمان', sulaiman: 'سليمان',
  taha: 'طه',
  wassim: 'وسيم',
  yahya: 'يحيى',
  zaid: 'زيد', zayd: 'زيد',
  ziyad: 'زياد', ziad: 'زياد',
  bassam: 'بسام',
  badr: 'بدر',
  fouad: 'فؤاد',
  hakim: 'حكيم',
  kamal: 'كمال',
  nassim: 'نسيم',
  imrane: 'عمران', imran: 'عمران',
  issam: 'عصام',
  kacem: 'قاسم', qacem: 'قاسم',
  naoufal: 'نوفل',
  nizar: 'نزار',
  rami: 'رامي', ramy: 'رامي',
  riad: 'رياض', riyad: 'رياض',
  sabri: 'صبري',
  yassir: 'ياسر', yasser: 'ياسر',
  chakib: 'شكيب',
  chouaib: 'شعيب', choaib: 'شعيب',
  hamid: 'حميد',
  hatim: 'حاتم',
  jaber: 'جابر',
  majid: 'ماجد',
  mansour: 'منصور',
  mourad: 'مراد',
  nouh: 'نوح',
  rabie: 'ربيع',
  salman: 'سلمان',
  sohaib: 'صهيب', souhaib: 'صهيب',
  zouhair: 'زهير',
  nadir: 'نادر',
  zine: 'زين', zayn: 'زين',

  // ------------------------------------------------------------- meisjes
  amira: 'أميرة',
  aziza: 'عزيزة',
  farida: 'فريدة',
  hanae: 'هناء', hanaa: 'هناء',
  ines: 'إيناس', inas: 'إيناس', iness: 'إيناس',
  malika: 'مليكة',
  mayssa: 'ميساء', maissa: 'ميساء',
  nassira: 'نصيرة',
  rayhana: 'ريحانة',
  saadia: 'سعدية',
  warda: 'وردة',
  zahira: 'زهيرة',
  fatima: 'فاطمة', fatema: 'فاطمة', fatiha: 'فتيحة',
  fatimazahra: 'فاطمة الزهراء', fatimaezzahra: 'فاطمة الزهراء',
  khadija: 'خديجة',
  aicha: 'عائشة', aisha: 'عائشة', aycha: 'عائشة',
  maryam: 'مريم', meryem: 'مريم', mariam: 'مريم', meriem: 'مريم',
  yasmin: 'ياسمين', yasmine: 'ياسمين', jasmine: 'ياسمين', yasmina: 'ياسمين',
  sara: 'سارة', sarah: 'سارة',
  salma: 'سلمى', selma: 'سلمى',
  imane: 'إيمان', iman: 'إيمان',
  hajar: 'هاجر',
  nour: 'نور', noor: 'نور',
  noura: 'نورة', nora: 'نورة',
  aya: 'آية', aia: 'آية',
  malak: 'ملاك',
  lina: 'لينا',
  rania: 'رانية', ranya: 'رانية',
  hiba: 'هبة',
  asma: 'أسماء', asmae: 'أسماء', asmaa: 'أسماء',
  safae: 'صفاء', safaa: 'صفاء',
  sanae: 'سناء', sanaa: 'سناء',
  kaoutar: 'كوثر', kawtar: 'كوثر',
  oumaima: 'أميمة',
  chaimae: 'شيماء', chaima: 'شيماء', chaimaa: 'شيماء',
  ikram: 'إكرام',
  nada: 'ندى',
  doha: 'ضحى',
  israa: 'إسراء', isra: 'إسراء',
  hafsa: 'حفصة',
  zineb: 'زينب', zaynab: 'زينب', zeineb: 'زينب',
  samira: 'سميرة',
  naima: 'نعيمة',
  latifa: 'لطيفة',
  rachida: 'رشيدة',
  jamila: 'جميلة',
  halima: 'حليمة',
  souad: 'سعاد',
  nawal: 'نوال', naoual: 'نوال',
  wafa: 'وفاء', wafae: 'وفاء', ouafa: 'وفاء',
  loubna: 'لبنى', lubna: 'لبنى',
  houda: 'هدى', hoda: 'هدى',
  ghita: 'غيثة', rhita: 'غيثة',
  firdaous: 'فردوس',
  dounia: 'دنيا', donia: 'دنيا',
  nisrine: 'نسرين', nesrine: 'نسرين',
  siham: 'سهام', sihame: 'سهام',
  hind: 'هند',
  saida: 'سعيدة',
  zahra: 'زهرة',
  zakia: 'زكية',
  rajae: 'رجاء',
  yousra: 'يسرا',
  marwa: 'مروة',
  amina: 'أمينة',
  nezha: 'نزهة',
  soraya: 'ثريا', thoraya: 'ثريا',
  karima: 'كريمة',
  nadia: 'نادية',
  sofia: 'صوفيا', soufia: 'صوفيا',
  leila: 'ليلى', laila: 'ليلى', layla: 'ليلى',
  lamia: 'لمياء', lamiae: 'لمياء',
  manal: 'منال',
  mouna: 'منى', mona: 'منى',
  najat: 'نجاة',
  nouhaila: 'نهيلة',
  rim: 'ريم', reem: 'ريم',
  sabah: 'صباح',
  salwa: 'سلوى',
  soumaya: 'سمية', soumia: 'سمية',
  tasnim: 'تسنيم',
  widad: 'وداد',
  kenza: 'كنزة',
  ihsane: 'إحسان',
  ilham: 'إلهام',
  hanane: 'حنان', hanan: 'حنان',
  bouchra: 'بشرى',
  btissam: 'ابتسام', ibtissam: 'ابتسام',
  fadwa: 'فدوى',
  ghizlane: 'غزلان',
  hayat: 'حياة',
  jihane: 'جيهان',
  khaoula: 'خولة',
  maha: 'مها',
  mounia: 'منية',
  rabab: 'رباب',
  roqaya: 'رقية', rokaya: 'رقية',
  safia: 'صفية',
  sakina: 'سكينة', soukaina: 'سكينة',
  samia: 'سامية',
  zoulikha: 'زليخة',
}

/** Het Arabisch bij een naam, of null als hij er niet in staat. */
export const arabischeNaam = (naam: string): string | null => NAMEN[normaliseer(naam)] ?? null
